### ISSUE TITLE
[netease] support for embedding videos

### ISSUE THREAD

**Issue by lilydjwg** [soimort/you-get#1001]
Examples:

http://mooc.guokr.com/talk/1231/ has
http://swf.ws.126.net/openplayer/v01/-0-2_MB3M6LDG1_MB3OBKTVH-vimg1_ws_126_net//image/snapshot_movie/2015/9/V/I/MB3OBKTVI-14230318056545654.swf

http://mooc.guokr.com/talk/663/ has
http://swf.ws.126.net/openplayer/v01/-0-2_MAD7EMDVE_MAD7K95I9-vimg1_ws_126_net//image/snapshot_movie/2014/12/5/9/MAD7K9359-1423031805654.swf

我[这里](https://github.com/lilydjwg/you-get/commit/736b10e9fe6e2ac6f25be7d3730f2b013f355690)有一个实现，不过实现得不是太好。我是这样想的：

* [ ] 支持从网页里爬取这样的链接
* [ ] 支持 swf 文件地址解析

关于网易视频，还有另一个更麻烦的 issue #1002。

**Comment by soimort** [comment]
不需要 swf，直接从页面里正则匹配出
* http://open.163.com/movie/2015/10/V/H/MB3M6LDG1_MB3OBKTVH.html

让`embed.py`引导到相应的 extractor 即可。

这个地址应该是可以下的
@soimort-bot try this http://open.163.com/movie/2015/10/V/H/MB3M6LDG1_MB3OBKTVH.html
