### ISSUE TITLE
[netease] 下载带独立字幕的多种清晰度的视频

### ISSUE THREAD

**Issue by lilydjwg** [soimort/you-get#1002]
比如这个视频： http://open.163.com/movie/2014/12/I/9/MAD7EMDVE_MAD7K95I9.html

使用目前的方式只能获取到低清晰度的视频，通过解密 xml 文档可以获得多种格式的视频，并且有独立的字幕。这里是我写了一半的提交： https://github.com/lilydjwg/you-get/commit/618a31d433b33c65fd4759501c0ff3be8bf778d6

然而问题来了：
- [ ] 多个字幕文件的下载、保存和播放（`you-get -p mpv` 时如何显示双语字幕呢？）
- [ ] 重构时，网易音乐部分因为在一起，也得重构，然而它们逻辑上是分立的。这样也增加了单个  commit/pr 的大小
- [ ] 在没有 PyCrypto 时还得 fallback 到现在的方式
- [ ] 用户想下载现在的方式得到的自带字幕的视频时怎么办？

**Comment by cnbeining** [comment]
第二条：

因为逻辑按照URL送到不同的解析器 所以除非我们把netease拆成只有按URL送到别的解析器的办法 应该没有吧。

第三条：

可以预见以后这种视频会变多。。。让用户装一个吧。那么多依赖都装了。。或者看看```youtube-dl```怎么办？

**Comment by yan12125** [comment]
> 或者看看youtube-dl怎么办？

There's a pure Python implementation of AES algorithms at https://github.com/rg3/youtube-dl/blob/master/youtube_dl/aes.py.

**Comment by lilydjwg** [comment]
WOW, AES 的实现这么短！

**Comment by soimort** [comment]
I don't find any particular site I'm interest in (or that I care about) that makes use of AES (or such like) crypto algorithms. However, if we had an implementation of AES, `--cookies` could be made to support Chrome cookies.

**Comment by moboard** [comment]
像流这样的弹幕彼下载呢
