### ISSUE TITLE
风行网失效了。。。 python3 you-get --debug http://www.fun.tv/vplay/m-102695.e-1/

### ISSUE THREAD

**Issue by sunyymq** [soimort/you-get#1004]
python3 you-get --debug http://www.fun.tv/vplay/m-102695.e-1/
没有任何返回内容

**Comment by cnbeining** [comment]
We need to handle the 302.

**Comment by sunyymq** [comment]
使用 python3 you-get --debug http://www.fun.tv/vplay/g-102695.e-1/?uc=19&webuc=13获取到的视频都是默认宣传风行的那个视频- - 似乎是没有tkoen导致的

**Comment by cnbeining** [comment]
是么？你把我那个pr拽下来看一下。我这里实在没得下载了。

反正超清文件是5段 105MB。看起来不像是宣传教育片。

**Comment by sunyymq** [comment]
python3 you-get --debug http://www.fun.tv/vplay/m-102695.e-1/
![image](https://cloud.githubusercontent.com/assets/3898351/13944365/b840fef0-f03f-11e5-8ff0-8d99d053f85f.png)

**Comment by cnbeining** [comment]
用那个新的PR。

我都不知道我当时为什么做出了那种事情。

也许我应该白天工作的。

**Comment by sunyymq** [comment]
下了一个，还是宣传片。。。。。 so bad

**Comment by cnbeining** [comment]
困了，再说。

**Comment by cnbeining** [comment]
我弄明白新的番剧逻辑了。
