### ISSUE TITLE
爱奇艺新key

### ISSUE THREAD

**Issue by xyuanmu** [soimort/you-get#1005]
昨天更新的播放器，新key：4a1caba4b4465345366f28da7c117d20
旧key估计过几天就会失效了：8ed797d224d043e7ac23d95b70227d32

以下是测试图片，新key是可以正常解析的：
![iqiyi](https://cloud.githubusercontent.com/assets/12442896/13944114/55e24bda-f03d-11e5-86e1-6adf455c6bcd.png)

**Comment by cnbeining** [comment]
Thanks, will update.

**Comment by soimort** [comment]
It seems @soimort-bot is actually doing his job... (but a little pointless for this issue)

**Comment by soimort** [comment]
Updated, thanks!
