### ISSUE TITLE
求助一下，Windows安装版的程序具体到底怎么用啊？

### ISSUE THREAD

**Issue by helloqingfeng** [soimort/you-get#1012]
我下载完成这个安装包you-get-0.4.350-win32-full.7z之后，解压到桌面，
然后里面看到有.bat与.exe两个文件，打开之后是都命令窗口。
但是我到底该打开哪个啊？

打开之后还是不会用啊。并且打开exe程序时，会出现闪退，用不了啊（或者说不会用）。

那接下来，下载一个视频的具体步骤是什么呢？

**有没有大神来详细解答一下啊？**

谢谢了！

**Comment by soimort** [comment]
![963105b2-a30a-11e5-9a02-e2ca3cadaa94](https://cloud.githubusercontent.com/assets/342945/14060978/acd21b48-f374-11e5-8896-1f1d138806a3.png)

**Comment by helloqingfeng** [comment]
@soimort 我试试看哈，谢谢了大神。

**Comment by helloqingfeng** [comment]
@soimort 
![360 20160327000923479](https://cloud.githubusercontent.com/assets/9712785/14061021/50fa35da-f3b0-11e5-90b3-4d8597847f00.jpg)
按你的方法试了，正在下载中。
谢谢大神，这才是最好的使用说明。
对了，下载的文件就直接在youget当前文件夹里是吧？

**Comment by soimort** [comment]
:ok_hand:
