### ISSUE TITLE
you-get: [error] outdated iQIYI key

### ISSUE THREAD

**Issue by imcaffrey** [soimort/you-get#1025]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get: [error] outdated iQIYI key
you-get: is your you-get up-to-date?
```

I installed you-get on CentOS with pip3 an hour ago.

Got this now. Should I provide any other info?

**Comment by imcaffrey** [comment]
@soimort-bot Please test this link: http://www.iqiyi.com/v_19rrkxmiss.html#curid=461008400_923adfd01ae5a08ab892d1b20b739e9b

**Comment by imcaffrey** [comment]
@soimort-bot Please test this link agin: http://www.iqiyi.com/v_19rrkxmiss.html#curid=461008400_923adfd01ae5a08ab892d1b20b739e9b

**Comment by soimort** [comment]
Again, please run the command with the `--debug` option. Also, please report **the exact version** you used.

**Comment by cnbeining** [comment]
```enc_key = 4a1caba4b4465345366f28da7c117d20```

It should be working.

**Comment by soimort** [comment]
It seems @soimort-bot mistakenly takes anything from `stderr` as a "not working" sign. This needs to be fixed on my side.

Currently iQIYI download is working. So you need to make sure `you-get` is indeed up-to-date.

**Comment by imcaffrey** [comment]
XD, thanks for replying.
I've tried again and it's working now.

**Comment by imcaffrey** [comment]
I got the problem!
If the url is not valid, I get `you-get: [error] outdated iQIYI key`.

for example,
```
# you-get --format=standard -O 8.flv http://www.iqiyi.com/v_19rrkxmiss.html#curid=460591800_c12d4c2c30072c7573e82f4d501fe691http://www.iqiyi.com/v_19rrkxmiss.html#curid=460591800_c12d4c2c30072c7573e82f4d501fe691 --debug

```
