### ISSUE TITLE
serious problem

### ISSUE THREAD

**Issue by shadowhaou** [soimort/you-get#1030]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get --debug "http://www.tudou.com/albumplay/pEFBZGfERLo.html" 
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTUyMTM2MjU4OA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTUyMTM2MjU4OA==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/245982272401212d3d1c7_00/st/flv/fileid/0300800B0057000975A78B1468DEFE40A948AC-BD7B-D015-A3FF-E3F05320D0BD?ep=cCaRE0GPVMkC4SPeij8bMy%2B2dSQIXP4J9h%2BNgdIQALshT%2Bi%2FmTfWwuy3Ro1DEv8RBldwZe%2Fx2tnjYjFnYYI3rhoQq06pPPqR%2FYaV5dhQspAFZRs2Bs2lwFSfQDH1&oip=3702798522&yxon=1&token=1314&ev=1&K=e6bdfa37436ae2de261ef00b&ctype=12
you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['http://www.tudou.com/albumplay/pEFBZGfERLo.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/tudou.py", line 46, in tudou_download
    return youku_download_by_vid(vcode, title=title, output_dir=output_dir, merge=merge, info_only=info_only, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 68, in download_by_vid
    self.extract(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/youku.py", line 300, in extract
    ksegs += [i['server'] for i in json.loads(get_content(u))]
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 324, in get_content
    data = data.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 16: invalid start byte

```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by cnbeining** [comment]
Did you check https://github.com/soimort/you-get/wiki/FAQ ?

**Comment by cnbeining** [comment]
Cannot reproduce.

```
python3 you-get -di -y proxy.uku.im:443 http://www.tudou.com/albumplay/pEFBZGfERLo.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTUyMTM2MjU4OA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTUyMTM2MjU4OA==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/4459823970054127167d6_00/st/flv/fileid/0300800B0057000975A78B1468DEFE40A948AC-BD7B-D015-A3FF-E3F05320D0BD?K=9e0c47aec19b661d282b5012&yxon=1&ev=1&token=2124&ep=diaRE0GPVccH5SPajD8bYC3kcyMJXP4J9h%2BNgdIQALshT%2Bi%2FmTfWwuy3Ro1DEv8RBldwZe%2Fx2tnjYjFnYYI3rhoQq06pPPqR%2FYaV5dhQspAFZRs2Bs2lwFScQjL1&ctype=12&oip=2042948938
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/4459823970054127167d6_00/st/flv/fileid/0300800B0157000975A78B1468DEFE40A948AC-BD7B-D015-A3FF-E3F05320D0BD?K=8cdd8c8e3992a37424129007&yxon=1&ev=1&token=2124&ep=diaRE0GPVccH5SPajD8bYC3kcyMJXP4J9h%2BNgdIQALohT%2Bi%2FmTfWwuy3Ro1DEv8RBldwZe%2Fx2tnjYjFnYYI3rhoQq06pPPqR%2FYaV5dhQspAFZRs2Bs2lwFScQjL1&ctype=12&oip=2042948938
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/4459823970054127167d6_00/st/flv/fileid/0300800B0257000975A78B1468DEFE40A948AC-BD7B-D015-A3FF-E3F05320D0BD?K=66017b631df17e6b24129007&yxon=1&ev=1&token=2124&ep=diaRE0GPVccH5SPajD8bYC3kcyMJXP4J9h%2BNgdIQALkhT%2Bi%2FmTfWwuy3Ro1DEv8RBldwZe%2Fx2tnjYjFnYYI3rhoQq06pPPqR%2FYaV5dhQspAFZRs2Bs2lwFScQjL1&ctype=12&oip=2042948938
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/4459823970054127167d6_00/st/flv/fileid/0300800B0357000975A78B1468DEFE40A948AC-BD7B-D015-A3FF-E3F05320D0BD?K=781dd034f151cc88261ef00d&yxon=1&ev=1&token=2124&ep=diaRE0GPVccH5SPajD8bYC3kcyMJXP4J9h%2BNgdIQALghT%2Bi%2FmTfWwuy3Ro1DEv8RBldwZe%2Fx2tnjYjFnYYI3rhoQq06pPPqR%2FYaV5dhQspAFZRs2Bs2lwFScQjL1&ctype=12&oip=2042948938
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/4459823970054127167d6_00/st/flv/fileid/0300800B0457000975A78B1468DEFE40A948AC-BD7B-D015-A3FF-E3F05320D0BD?K=a8974054452d2169282b5012&yxon=1&ev=1&token=2124&ep=diaRE0GPVccH5SPajD8bYC3kcyMJXP4J9h%2BNgdIQAL8hT%2Bi%2FmTfWwuy3Ro1DEv8RBldwZe%2Fx2tnjYjFnYYI3rhoQq06pPPqR%2FYaV5dhQspAFZRs2Bs2lwFScQjL1&ctype=12&oip=2042948938
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/4459823970054127167d6_00/st/flv/fileid/0300800B0557000975A78B1468DEFE40A948AC-BD7B-D015-A3FF-E3F05320D0BD?K=cb9c0e700e3b867124129007&yxon=1&ev=1&token=2124&ep=diaRE0GPVccH5SPajD8bYC3kcyMJXP4J9h%2BNgdIQAL4hT%2Bi%2FmTfWwuy3Ro1DEv8RBldwZe%2Fx2tnjYjFnYYI3rhoQq06pPPqR%2FYaV5dhQspAFZRs2Bs2lwFScQjL1&ctype=12&oip=2042948938
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/4459823970054127167d6_00/st/flv/fileid/0300800B0657000975A78B1468DEFE40A948AC-BD7B-D015-A3FF-E3F05320D0BD?K=86f64a493b24aa57282b5012&yxon=1&ev=1&token=2124&ep=diaRE0GPVccH5SPajD8bYC3kcyMJXP4J9h%2BNgdIQAL0hT%2Bi%2FmTfWwuy3Ro1DEv8RBldwZe%2Fx2tnjYjFnYYI3rhoQq06pPPqR%2FYaV5dhQspAFZRs2Bs2lwFScQjL1&ctype=12&oip=2042948938
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/4459823970054127167d6_00/st/flv/fileid/0300800B0757000975A78B1468DEFE40A948AC-BD7B-D015-A3FF-E3F05320D0BD?K=f2e79002f92a1fc824129007&yxon=1&ev=1&token=2124&ep=diaRE0GPVccH5SPajD8bYC3kcyMJXP4J9h%2BNgdIQALwhT%2Bi%2FmTfWwuy3Ro1DEv8RBldwZe%2Fx2tnjYjFnYYI3rhoQq06pPPqR%2FYaV5dhQspAFZRs2Bs2lwFScQjL1&ctype=12&oip=2042948938
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/4459823970054127167d6_00/st/flv/fileid/0300800B0857000975A78B1468DEFE40A948AC-BD7B-D015-A3FF-E3F05320D0BD?K=94ee1260de2ddc1d24129007&yxon=1&ev=1&token=2124&ep=diaRE0GPVccH5SPajD8bYC3kcyMJXP4J9h%2BNgdIQALMhT%2Bi%2FmTfWwuy3Ro1DEv8RBldwZe%2Fx2tnjYjFnYYI3rhoQq06pPPqR%2FYaV5dhQspAFZRs2Bs2lwFScQjL1&ctype=12&oip=2042948938
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/4459823970054127167d6_00/st/flv/fileid/0300800B0957000975A78B1468DEFE40A948AC-BD7B-D015-A3FF-E3F05320D0BD?K=d7b5c7c2369ff374282b5012&yxon=1&ev=1&token=2124&ep=diaRE0GPVccH5SPajD8bYC3kcyMJXP4J9h%2BNgdIQALIhT%2Bi%2FmTfWwuy3Ro1DEv8RBldwZe%2Fx2tnjYjFnYYI3rhoQq06pPPqR%2FYaV5dhQspAFZRs2Bs2lwFScQjL1&ctype=12&oip=2042948938
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/4459823970054127167d6_00/st/flv/fileid/0300800B0A57000975A78B1468DEFE40A948AC-BD7B-D015-A3FF-E3F05320D0BD?K=6a9cb84919f6e97d282b5012&yxon=1&ev=1&token=2124&ep=diaRE0GPVccH5SPajD8bYC3kcyMJXP4J9h%2BNgdIQAMohT%2Bi%2FmTfWwuy3Ro1DEv8RBldwZe%2Fx2tnjYjFnYYI3rhoQq06pPPqR%2FYaV5dhQspAFZRs2Bs2lwFScQjL1&ctype=12&oip=2042948938
site:                优酷 (Youku)
title:               第01话 绿谷出久:原点
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          550.4 MiB (577101005 bytes)
    # download-with: you-get --format=hd3 [URL]

    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          286.9 MiB (300796812 bytes)
    # download-with: you-get --format=hd2 [URL]

    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          152.1 MiB (159498254 bytes)
    # download-with: you-get --format=mp4 [URL]

    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          73.6 MiB (77153615 bytes)
    # download-with: you-get --format=flvhd [URL]
```

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by shadowhaou** [comment]
I did it as you did,but it still occured problem
saro@SaRo:~$ you-get -i "http://www.tudou.com/albumplay/pEFBZGfERLo.html"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by cnbeining** [comment]
You OK?
