### ISSUE TITLE
youku播单只能解析一页

### ISSUE THREAD

**Issue by cani1see** [soimort/you-get#1033]
优酷播单超出20项不解析
实例：
http://list.youku.com/albumlist/show?id=22253424&ascending=1&page=2.html

**Comment by 4ft35t** [comment]
剧集只能获取前 100 集，比如火影忍者
http://www.youku.com/show_page/id_zcc001f06962411de83b1.html

**Comment by tokenian** [comment]
无法下载mp4格式，只下载了70MB左右
http://v.youku.com/v_show/id_XMTUxMTU0NzA3Ng==.html

**Comment by cani1see** [comment]
@tokenian 你这个不是一回事吧

**Comment by chitanda** [comment]
@tokenian  你这个是付费的片子免费帐号自然下载不玩吧。。。

**Comment by tokenian** [comment]
我再说下我的问题，我个人是会员，所以you-get是不是已经能拿到浏览器的cookie信息呢？还是说需要我手动传入you-get

**Comment by ichenkaihua** [comment]
@tokenian 需要手动传，--cookies cookie.txt

**Comment by soimort** [comment]
Closed via #1289.
