### ISSUE TITLE
请问未来能支持火猫TV直播下载吗

### ISSUE THREAD

**Issue by hola46** [soimort/you-get#1035]
不知以後是否有机会支持火猫TV此网站，谢谢!
http://www.huomaotv.cn/

**Comment by cnbeining** [comment]
Seems easy...

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/you-get/blob/master/you_get/extractors/huomaotv.py

**Comment by lki2019** [comment]
可以关闭啦
