### ISSUE TITLE
请问，有办法获取视频的m3u8地址吗？

### ISSUE THREAD

**Issue by RaynorZhong** [soimort/you-get#1036]
请问，有办法获取视频的m3u8地址吗？

**Comment by soimort** [comment]
并不是所有视频网站都提供m3u8地址。

请给出具体的网站和链接信息。

**Comment by RaynorZhong** [comment]
谢谢你的回复。

下面是 乐视 的视频地址：《甄嬛传》01

http://www.le.com/ptv/vplay/1578861.html#vid=1578861

我能正常下载视频。想获取它的m3u8，谢谢。
