### ISSUE TITLE
风行解析的视频源播放的时候自动变成广告

### ISSUE THREAD

**Issue by Roryjia** [soimort/you-get#1039]
如解析：http://221.229.165.23:80/play/446A11F8C41D86568234C79CF21EE4B8626A4C50.mp4
跳转：http://61.164.142.210/play/36F862DFC1A3636DC493EBB9AFFACBE14F8AF0A0/306534.mp4?token=QjVFQjZBRUREQjBCMTI3RUY1MzhFNzU5QzY5REE0MzE2MEI3QzYzQV9mdW5fMTQ2MDAyMjU4Nw== 播放的为风行宣传广告

**Comment by cnbeining** [comment]
Duplicate of #1004 .

**Comment by jonerxq** [comment]
这个bug是不是还没有修复，我在develop 中看还是不对的
