### ISSUE TITLE
代理方面可否支持下socks5

### ISSUE THREAD

**Issue by sergio13848** [soimort/you-get#1046]
**shadowsocks**使用面积较广，可否支持下**socks5**代理方式？  
非常感谢！！！

**Comment by cnbeining** [comment]
很难。Python并没有内置一种办法可以方便的支持。

如果需要支持，则需要添加一捆依赖。是不是会搞坏windows也不好说。

请暂时使用转化小程序们搭桥吧...

2016年4月9日星期六，Mort the Bot <notifications@github.com> 写道：

**Comment by soimort** [comment]
Try: https://github.com/rofl0r/proxychains-ng

**Comment by yan12125** [comment]
SOCKS protocol非常簡單，可以用pure Python實現
我在youtube-dl有一個WIP PR https://github.com/rg3/youtube-dl/pull/9287 ，用的是public domain的SOCKS library，可以參考看看。
