### ISSUE TITLE
exe版和python版下载b站效果不一样的？

### ISSUE THREAD

**Issue by saiatsai** [soimort/you-get#1050]
linux上用的py版是git clone的，win版下载的full版，两者版本都是0.4.365
运行you-get http://www.bilibili.com/video/av1057210

py版可以自动多P下载，文件名正常，但没有下载弹幕文件
win版只下载1p视频及1p弹幕文件，1p文件名为up主投稿标题，而非1p的标题
试过加/index_1.html（只下载1p，文件名也是投稿标题）和&page=1（win版无效）
加/index_2.html这样子下载2p的话文件名就是2p标题

问题：win版不能自动多P下载？

**Comment by soimort** [comment]
自动下载多P是 #1019 新加的，还没有发布。

需要的话就先用 git 的版本好了。
