### ISSUE TITLE
断点续传、中英双语wiki、程序双开、文件合并、大文件后程链接甄选

### ISSUE THREAD

**Issue by linux0ne** [soimort/you-get#1052]
1、ctrl + c 可以终止下载，那么终止后，键入相同的参数后就可以继续下载，可这个时候的下载服务器还是原来的么？如果原来的服务器的下载速度很慢的话，重新来过也好不到哪里去，有没有一个甄选的机制呢？

2、全是英文的wiki，总觉得在中国还是加上中文的wiki说明才显得完整，并且能方便更多的人。

3、程序经测试是允许双开的，但是一旦开了二个下载后，不一会儿第一个下载就变得超慢，不知道是下载资源的问题，还是网速或者是软件的问题呢？
两个例子：
a、http://v.youku.com/v_show/id_XMTQ1NTk1NTk1Mg==.html?from=s1.8-3-1.2
b、http://v.youku.com/v_show/id_XMTM4ODE1MDg2NA==.html?from=s1.8-3-1.2

4、因为我到现在为止一直没有成功下载过一个文件，所以我不知道程序是否具备自动合并文件的功能，即将多个flv超清视频合成一个。

5、如上方的两个例子URL，越到后程下载的时候，其下载速度越慢，甚至到了4KB、10KB/S的情况，我觉得这不是服务器的原因吧？因为在用硕鼠软件在windows平台上下载时，发现每个文件的下载速度都是很可观的，是不是服务器的甄选机制上可以再改进一下？

注：其实我的重点是第2条。

**Comment by linux0ne** [comment]
比如说：我的路由器突然断电，然后再通电启动后，我的IP地址就变了，那么我在接着下载的时候，会不会断点续传？

**Comment by nujabse** [comment]
@linux0ne wiki 里面有中文选项。下载的确是可以断点续传的，不过近期优酷的视频下载貌似一直无法合并，之前是完全可以的。

**Comment by linux0ne** [comment]
@nujabse 
这个合并是一个问题了，建议设置一个参数m来实现可选合并。

**Comment by soimort** [comment]
(1) 我不清楚你在说哪个视频网站，但是对于绝大多数而言，服务器并不存在自己选择的可能性。基本上 API 给你的是什么，下载用的就是什么。至于优酷，两次调用 API 的结果肯定是不同的。

(2) 这个项目的wiki有中文选项，维护者也都会用中文回复你的问题。
![screenshot from 2016-04-13 16-20-23](https://cloud.githubusercontent.com/assets/342945/14496583/dbf632e2-0193-11e6-8936-4b4480b5b2f7.png)

没有打算把它做成“只有中国人才会用的项目”，所以我不会用中文来写主要文档。抱歉。

(4.) 有，文档里面有写的问题，请不要再重复提问。

(3. & 5.) 优酷可能会限速，我不知道是不是硕鼠有自己的缓存机制。但硕鼠本身是闭源+商业运作，我们不可能知道它是怎么实现的。`you-get`是开源，任何网站想要针对我们的UA搞一个限速，或者改个key让现在的算法失效，都是分分钟的事情。所以，这问题的讨论到此为止。

以上。

**Comment by linux0ne** [comment]
@soimort 
收到回复，之前已得到相关的回复，对软件有了进一步的了解，对项目也有了一定的认识。问题已得到解决。
