### ISSUE TITLE
下载地址相似的页面可以用通配符实现多页下载吗？

### ISSUE THREAD

**Issue by helloqingfeng** [soimort/you-get#1057]
> 比如我要下载这样的一些页面里的图片，地址是:

- http://www.xiusebizhi.com/iphonewallpaper?page=2
- http://www.xiusebizhi.com/iphonewallpaper?page=3
- http://www.xiusebizhi.com/iphonewallpaper?page=4
……

依次类推，我可以用下面的链接进行多页连续下载吗？
> you-get http://www.xiusebizhi.com/iphonewallpaper?page=*

**Comment by soimort** [comment]
这取决于你用的shell。

别的不知道。zsh：

```
$ you-get 'http://www.xiusebizhi.com/iphonewallpaper?page='{2..100}
```

**Comment by helloqingfeng** [comment]
@soimort 我用的是Windows exe客户端，试了下你那条语句，不行。
![360 20160414235813651](https://cloud.githubusercontent.com/assets/9712785/14534709/f72aff34-029c-11e6-8677-ddfa22292ca3.jpg)

**Comment by soimort** [comment]
Windows batch的话，写个FOR循环吧。

这不是`you-get`该做的事情。
