### ISSUE TITLE
可否在优酷网站获取以 "http://k.youku.com/player/getFlvPath/sid/" 开头的视频地址？

### ISSUE THREAD

**Issue by silver-zhao** [soimort/you-get#1058]
如题。

我不需要下载视频，只是想用本地播放器 MPC-HC 播放。

目前 you-get 获取到的 .flv 格式文件的地址形如：
http://103.41.141.60/youku/657131A491A407BBFCA204A1F/0300010200569CEC78795A019BE2E215B5B29F-DAB9-A784-4442-E0353954A67F.flv

在其他抓取网站获取到的地址，则形如：
http://k.youku.com/player/getFlvPath/sid/346063901799720e8a009_00/st/flv/fileid/0300010200569CEC78795A019BE2E215B5B29F-DAB9-A784-4442-E0353954A67F?K=6d76aeb885993763282b563e&hd=2&ts=185&pid=6b5f94f4ab33c702&ymovie=1&r=/3sLngL0Q6CXymAIiF9JUQQtnOFNJPUClO8A56KJJcT8UB+NRAMQ09zE6rNj4EKMxAvRByWf6hitgv75Fv0ffR/zhwt2uVfKLekBad9vUCUz1b+Xw4zfcXGbiWKzikhG0ZHGVdKogKJroO8dQL5WpBqH3a/ej0v0BoN/CTmC1URFZ46E3uo7v8u0gz3s91Jc&ypremium=1&oip=1931268481&token=7810&sid=346063901799720e8a009&did=1460639018&ev=1&ctype=20&ep=A6nfAPKOaKHzDn%2FQd4sRZM3aHMKLtueYWhcDIFg99ewwCOAb0WklZBbihjQVi9%2BHR95cyWL7K%2ByDF4N89cupJ%2FgeNw0uHfaspc1HbRxiINUi27Fu34xnagX6xZVcSxJ0

由于 IP (103.41.141.60) 位于北京优酷，离我较远，播放时需要缓冲好久，而若是使用 k.youku.com 开头的视频地址，则可以秒开，似乎是用了 CDN 的缘故，可以直接解析到我所在地的 IP。

我大致查看了下代码，应该是和[这里](https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/youku.py#L293)的变量 `u` 有关，但是缺少一些参数。希望帮忙指点一二，多谢了！

**Comment by zhangn1985** [comment]
请用-p参数

**Comment by silver-zhao** [comment]
@zhangn1985  多谢回复。不过我需要的并不是这个。用 `-p` 参数，所获得的 URL 应该也是以 IP 地址开头的文件路径，我希望获取的是以 k.youku.com 开头的路径，这样可以使用 CDN 解析到最近的 IP。

我想或许也是因为我是用长城宽带的缘故？我在上海，可是 you-get 最终获取到 URL 里面的 IP 地址却总是北京的。

**Comment by zhangn1985** [comment]
https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/youku.py#L293-L300

这几行其实已经是http://k.youku.com

你可以试试不加转换。

但我记得要这么做的原因是这个地址会有很大概率的403。

**Comment by silver-zhao** [comment]
@zhangn1985 这个我也仔细看过，不过直接访问这个链接的话，返回的是 JSON 格式的数据，并不是直接可播放的文件地址。

将 you-get 这里获取的数据和例中其他抓取网站获取到的地址对比了下，其中少了 `ts` `pid` `r` `did` 等参数。

**Comment by linhua55** [comment]
@silver-zhao 
`k.youku.com`不是最终的地址,有两种方法可以获取最终的地址,可参考  https://github.com/soimort/you-get/pull/783#issuecomment-163141741   https://github.com/soimort/you-get/issues/793#issuecomment-163167864
直接用浏览器访问是使用了第三种方法, you-get使用的是第二种方法
你可以测试一下,这两个地址速度差别大吗?

**Comment by silver-zhao** [comment]
@linhua55 多谢回复。呃，看了一下，好像比较复杂的样子，要获得 cookie 什么的。我本来只是想问下是否有选项可以获取以 k.youku.com 开头的视频地址，而不是以 IP 开头的。既然现在的设计是特意如此，以避免 403 错误，那就先按现在的来吧。

这个 issue 可以关闭了。多谢。

**Comment by wmttom** [comment]
@silver-zhao k.youku.com 开头的地址，把 yxon 参数设置为 0，请求这个地址就会 302 到实际的视频文件了。

**Comment by silver-zhao** [comment]
@wmttom 将 yxon 设定为 0，测试有效，非常感谢！

**Comment by redstoneleo** [comment]
@wmttom 大哥你咋知道的啊？把 yxon 参数设置为 0就可以，好棒

**Comment by lin-N** [comment]
@silver-zhao @wmttom 谢谢几位dalao的讨论，遇到同样的问题，请求加了yxon=0后取到ip的地址，感谢几位
