### ISSUE TITLE
can't get all of the Youku video clip(special case)

### ISSUE THREAD

**Issue by dangger** [soimort/you-get#1060]
# DEBUG INFO:

[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTUyODA3MDI1Mg==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTUyODA3MDI1Mg==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/646066303634212ae422c_00/st/flv/fileid/0300800B005707C50D00581468DEFE020AC07F-8EE0-295D-4407-EF63BDEF3F4A?ep=dCaSGk%2BLVc4D4yDbij8bNnnmdnVcXP4J9h%2BNgdIQALshT%2Bi46jvRs52wS%2FdDEv8RBldwZevzq6GUakdiYfg23GgQ3UetTfrk%2BvDk5dglwpNyEmxAcbvTxVScSjH1&K=33abe32782edb0c7261ef49a&ctype=12&yxon=1&oip=2060369532&token=2914&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/646066303634212ae422c_00/st/flv/fileid/0300800B015707C50D00581468DEFE020AC07F-8EE0-295D-4407-EF63BDEF3F4A?ep=dCaSGk%2BLVc4D4yDbij8bNnnmdnVcXP4J9h%2BNgdIQALohT%2Bi46jvRs52wS%2FdDEv8RBldwZevzq6GUakdiYfg23GgQ3UetTfrk%2BvDk5dglwpNyEmxAcbvTxVScSjH1&K=0e7a4701fbf5d001282b5672&ctype=12&yxon=1&oip=2060369532&token=2914&ev=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/646066303634212ae422c_00/st/flv/fileid/0300800B025707C50D00581468DEFE020AC07F-8EE0-295D-4407-EF63BDEF3F4A?ep=dCaSGk%2BLVc4D4yDbij8bNnnmdnVcXP4J9h%2BNgdIQALkhT%2Bi46jvRs52wS%2FdDEv8RBldwZevzq6GUakdiYfg23GgQ3UetTfrk%2BvDk5dglwpNyEmxAcbvTxVScSjH1&K=dacd2cd1d76e9fc7261ef49a&ctype=12&yxon=1&oip=2060369532&token=2914&ev=1
site:                优酷 (Youku)
title:               第01话 不劳者不得食
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          552.2 MiB (579060424 bytes)
    # download-with: you-get --format=hd3 [URL]

Real URLs:
http://103.41.141.166/youku/6571126CE0A3679E2742B6976/0300800B005707C50D00581468DEFE020AC07F-8EE0-295D-4407-EF63BDEF3F4A.flv
http://103.41.141.97/youku/6571570756A3B7AD11D624274/0300800B015707C50D00581468DEFE020AC07F-8EE0-295D-4407-EF63BDEF3F4A.flv
http://103.41.141.48/youku/6972AE0EAE9447C7EC14237FE/0300800B025707C50D00581468DEFE020AC07F-8EE0-295D-4407-EF63BDEF3F4A.flv

---

as you see it only get 3 clips of the video,not all.
I have tried some other videos,it work successfully.
So can you try to solve it?it's strange that only this video can't fully download.
PS:this is a VIP only video,but I have VIP and I have add --cookies.
the command I used is :
`you-get -c youku.txt http://v.youku.com/v_show/id_XMTUyODA3MDI1Mg==.html`

**Comment by soimort** [comment]
VIP videos require another set of methods, I guess. The public accessible API will stream only a few segments at the beginning. If `--cookies` doesn't work, then it might be a different API, or at least you'll have to pass an additional (private) token, which we don't have.

I hope someone with VIP access can come up with a solution.

**Comment by rosynirvana** [comment]
outdated
