### ISSUE TITLE
How can i get infomations of any video?

### ISSUE THREAD

**Issue by johnsmeeth** [soimort/you-get#1068]
Dear sir.
How can i get only infomation (no need download) of a video from my python code as title, filesize, url download, quaility.

Many thanks.

**Comment by zhangn1985** [comment]
Try  -u  or -i

**Comment by johnsmeeth** [comment]
@zhangn1985 That seem run from external. Please you tell me how to get that information in my python.

**Comment by soimort** [comment]
We have no stable API at this point, not to mention documentation. So the answer is:

**Read the source code.**
