### ISSUE TITLE
希望添加对“网易云课堂”的支持

### ISSUE THREAD

**Issue by johnhi2015** [soimort/you-get#1075]
希望添加对“网易云课堂”的支持

For example: http://study.163.com/course/courseMain.htm?courseId=1002954002#/courseDetail

If can support batch download for a playlist, that would be nice~

感谢作者！

**Comment by lki2019** [comment]
网易晕课堂 支持添加的人还不少啊

**Comment by lki2019** [comment]
https://github.com/soimort/you-get/issues/213

重复了
