### ISSUE TITLE
添加对mgtv(芒果TV)的支持

### ISSUE THREAD

**Issue by protream** [soimort/you-get#1076]
为什么没有对芒果TV的支持呢?

**Comment by nuomi1** [comment]
@protream 为什么你不写呢？

**Comment by zhangn1985** [comment]
@protream 欢迎改写：https://github.com/zhangn1985/you-get/blob/master/you_get/extractors/mgtv.py
并upstream

**Comment by cnbeining** [comment]
@zhangn1985 我正在写，正在纠结于```VideoExtrator```到底需要点啥东西以及到底怎么实现。。。

**Comment by cnbeining** [comment]
写好了，除了暂时不能合并文件外都很好。

合并是另一个问题。

**Comment by tulip33** [comment]
@zhangn1985 
请问mgtv.py怎样使用呢？系统装了python3.4.4，双击过，但是youget还是无法解析下载芒果视频

**Comment by cnbeining** [comment]
最新版的you-get已经添加了mgtv的支持，可以直接调用。

请务必使用最新的版本。

2016年5月21日星期六，tulip33 <notifications@github.com> 写道：

**Comment by tulip33** [comment]
@cnbeining 
xp下，在python装了youget0.4.390，乐视的可以下载，但芒果没反应
debug如下：
[DEBUG] get_content: http://www.mgtv.com/v/1/292405/f/3176564.html
you-get: version 0.4.390, a tiny downloader that scrapes the web.
you-get: ['http://www.mgtv.com/v/1/292405/f/3176564.html']
Traceback (most recent call last):
  File "d:\Python34\Scripts\you-get-script.py", line 9, in <module>
    load_entry_point('you-get==0.4.390', 'console_scripts', 'you-get')()
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\__main__
.py", line 92, in main
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\common.p
y", line 1274, in main
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\common.p
y", line 1187, in script_main
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\common.p
y", line 1030, in download_main
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\common.p
y", line 1267, in any_download
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\extracto
rs\universal.py", line 18, in universal_download
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\common.p
y", line 263, in get_response
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\common.p
y", line 239, in ungzip
  File "d:\python34\lib\gzip.py", line 360, in read
    while self._read(readsize):
  File "d:\python34\lib\gzip.py", line 449, in _read
    self._read_eof()
  File "d:\python34\lib\gzip.py", line 482, in _read_eof
    crc32, isize = struct.unpack("<II", self._read_exact(8))
  File "d:\python34\lib\gzip.py", line 286, in _read_exact
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

**Comment by cnbeining** [comment]
这是你的Python的问题，和liblzma包有关，和项目无关。

我们可以试着修修，但是可能没什么用...

2016年5月21日星期六，tulip33 <notifications@github.com> 写道：

**Comment by zhangn1985** [comment]
@tulip33 请更新。

**Comment by tulip33** [comment]
@zhangn1985 
更新什么？

**Comment by cnbeining** [comment]
你本地的you-get版本。

**Comment by tulip33** [comment]
@cnbeining 
xp下能解析下载芒果了，但是解析不正确啊，只是个3K的小图片，本应该是视频

D:\Python34\Scripts>you-get -o N:\vidown http://www.mgtv.com/v/1/292405/f/317656
4.html
Site:       mgtv.com
Title:      ios-fav
Type:       Portable Network Graphics (image/png)
Size:       0.0 MiB (3440 Bytes)

**Comment by tulip33** [comment]
http://www.mgtv.com/v/1/292405/f/3176564.html

**Comment by zhangn1985** [comment]
@soimort-bot please test:  http://www.mgtv.com/v/1/292405/f/3176564.html

**Comment by cnbeining** [comment]
@tulip33 请使用**最新** 的 ```you-get``` 。最低版本为0.4.390.

**Comment by soimort** [comment]
不不，mgtv 的支持还没有发布到新版本，0.4.390 肯定是不行的。

@soimort-bot Test this on master: http://www.mgtv.com/v/1/292405/f/3176564.html

**Comment by cnbeining** [comment]
我看commit log好像有了呀...最新那个小fix可有可无。

2016年5月22日星期日，Mort Yao <notifications@github.com> 写道：

**Comment by soimort** [comment]
@soimort-bot Test this: http://www.mgtv.com/v/1/292405/f/3176564.html

**Comment by xinshangshangxin** [comment]
可以合并吗? 每次合并提示 `arguments too long`
看上去是 参数太长了(因为 mgtv 下载下来可能有 250个文件........)

**Comment by zhangn1985** [comment]
好像不会耶，我也是把下载的片段放到input.txt然后用`ffmpeg -f concat -i input.txt -c copy ....`

**Comment by cnbeining** [comment]
就是我们没有好的合并。

或调用ffmpeg。

2016年6月19日星期日，zhangn1985 <notifications@github.com> 写道：

**Comment by xinshangshangxin** [comment]
@zhangn1985 手动的还是程序自动的? 我没有看见生成 `input.txt ` ......

**Comment by zhangn1985** [comment]
https://github.com/soimort/you-get/blob/develop/src/you_get/processor/ffmpeg.py#L117

最后被删掉了：
https://github.com/soimort/you-get/blob/develop/src/you_get/processor/ffmpeg.py#L130

**Comment by xinshangshangxin** [comment]
thanks!! @zhangn1985

**Comment by yanshixin** [comment]
请问现在可以吗?
我执行you-get -di http://www.mgtv.com/v/1/292405/f/3176564.html 会报错, 最后的错误信息是

File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
