### ISSUE TITLE
Could you-get support proxy auto-config ?

### ISSUE THREAD

**Issue by j16180339887** [soimort/you-get#1079]
Please see [https://github.com/Unblocker/Unblock-Youku/wiki/代理服务器设置示例](https://github.com/Unblocker/Unblock-Youku/wiki/代理服务器设置示例)

Could you-get support proxy auto-config such as `http://pac.uku.im/pac.pac` ?

Thanks.

**Comment by j16180339887** [comment]
Actually it's not a big deal without this functionality.

You guys could close this issue if you want!

**Comment by jackyzy823** [comment]
To support pac(in javascript syntax), we should parse javascript . However it's far more than this project could do...
Maybe you could choose [pacparser](http://github.com/pacparser/pacparser) to make your own proxy wrapper for you-get.

**Comment by soimort** [comment]
We _may_ need a JavaScript interpreter at some point; not just for parsing PAC files, but some sites (YouTube, Videomega) use JS obfuscation and we need to deal with them anyway.

However I'm reluctant to include things like PyV8 as a dependency of this project. That is simply too much.

**Comment by mozbugbox** [comment]
There are a few embedable javascript implementations.

If you search for `javascript` in pipy, you can find some python bindings for `duketape` which is one of the embedable javascript interpreter.

**Comment by mozbugbox** [comment]
And https://github.com/PiotrDabkowski/Js2Py claims do js (ECMA Script 5.1)  in pure python code.

**Comment by yan12125** [comment]
If you are going to use a pure python solution, you have to implement ```dnsResolve```, ```myIpAddress```, and maybe other native functions in Python and register them to the JS context, like [what pacparser does](https://github.com/pacparser/pacparser/blob/02f0018/src/pacparser.c#L162-L180).

I bet using pacparser is simpler. I have an **experimental** implementation for youtube-dl at https://github.com/yan12125/youtube-dl/tree/proxy-auto-config-support.

**Comment by j16180339887** [comment]
@yan12125 is right.

There is no need to embed v8 (or anything like that).

It could be mentioned in ReadMe.md as a recommend option to install `pacparser`.

Just like `ffmpeg` is a strongly recommended option.
