### ISSUE TITLE
Feature Request: socks5 proxy should support.

### ISSUE THREAD

**Issue by abcfy2** [soimort/you-get#1091]
For now, you-get just support http proxy. I think it's not enough. Many other proxy should also be supported. 

Now I use a socks5 proxy(shadowsocks), should this proxy protocol be support in the future?

**Comment by cnbeining** [comment]
Good question.

I haven't found any small and cross-platform package to do this job.

For now you can use quite a lot of softwares (privovy comes to my mind) to
convert your SOCKS proxy into HTTP one.

2016年4月29日星期五，Mort the Bot <notifications@github.com> 写道：

**Comment by soimort** [comment]
Same old feature request: #1046 

Just use https://github.com/rofl0r/proxychains-ng. I have no plan to support SOCKS5 at `you-get` side.
