### ISSUE TITLE
B站不能跳转到指定的分P

### ISSUE THREAD

**Issue by yangxuan8282** [soimort/you-get#1093]
比如C菌的这个视频： http://www.bilibili.com/video/av4306452/index_2.html
我想只解析第二集的地址，但是结果所有分P全解析了，这样的话调用播放器每次只能从第一集开始看：

    you-get -i --debug 'http://www.bilibili.com/video/av4306452/index_2.html'
    [DEBUG] get_content: http://www.bilibili.com/video/av4306452/index_2.html
    [DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=8e9fc618fbd41e28&cid=6967711
    Site:       bilibili.com
    Title:      1、第一幕 第一章「王的力量」
    Type:       Flash video (video/x-flv)
    Size:       353.23 MiB (370393537 Bytes)
    
    [DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=8e9fc618fbd41e28&cid=6967712
    Site:       bilibili.com
    Title:      2、第一幕 第二章「大逃亡」
    Type:       Flash video (video/x-flv)
    Size:       274.87 MiB (288216960 Bytes)
    
    [DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=8e9fc618fbd41e28&cid=6967713
    Site:       bilibili.com
    Title:      3、第一幕 第三章「兄弟情深」
    Type:       Flash video (video/x-flv)
    Size:       260.07 MiB (272699341 Bytes)
    
    [DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=8e9fc618fbd41e28&cid=6990811
    Site:       bilibili.com
    Title:      4、分岔点1「强硬手段 vs 公关」
    Type:       Flash video (video/x-flv)
    Size:       128.03 MiB (134250189 Bytes)
    ......

信息比较长没有全贴，另外有办法选定清晰度吗

**Comment by yangxuan8282** [comment]
@soimort 第一次提交issue的时候还没输完不小心就提交了，结果被机器人关了，能不能重开下，已经加入 --debug 信息

**Comment by soimort** [comment]
Sorry for the mess. Reopened.

**Comment by 4321qasdfv** [comment]
同有这个问题！想下载一个持续更新的视频集，结果每次都会从头重新下载一遍，很不方便！

**Comment by soimort** [comment]
Closing via #1192.

**Comment by Evifly** [comment]
嗨，我可以请教下楼主如何下载一个专辑里所有的视频么，在B站，因为我现在下载的视频都只能默认一个个下载，所以想问问楼主的思路或者命令~非常感谢~

**Comment by yangxuan8282** [comment]
@Evifly 
好久没用了，不过根据上面的那条 PR 来看想下列表里的所有视频应该是类似这样：

```
you-get http://www.bilibili.com/video/av3278560/
```

只下第一个就是：

```
you-get http://www.bilibili.com/video/av3278560/index_1.html 
```

**Comment by rosynirvana** [comment]
```you-get``` release或是develop branch的代码早就不能用了啊，你用的修改过的代码？
另外专辑指什么？一个av号下面的，还是一个bangumi，还是mylist ?

**Comment by yangxuan8282** [comment]
@Evifly 刚装了一下 you-get 发现确实用不了了，建议看看别的同类软件吧，比如 youtube-dl
