### ISSUE TITLE
解析tv.sohu.com视频总是出错

### ISSUE THREAD

**Issue by callmelanmao** [soimort/you-get#1094]
下面是错误信息：
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

网络是没问题的，下载优酷和爱奇艺视频都不会出错

**Comment by zhangn1985** [comment]
@soimort-bot please test: http://tv.sohu.com/20160430/n447051147.shtml
