### ISSUE TITLE
I can download the video from tudou via u-get.But I can't use vlc to play the url.

### ISSUE THREAD

**Issue by cybmp3** [soimort/you-get#1095]
you-get -u http://www.tudou.com/programs/view/nmgG2b7HZ30/
So I can get the url.Such like this. But Vlc can't play it.
http://124.14.8.90/f4v/73/242097173.h264_4_seg_19.04001520195627C0BC0EE66D320764C9063661-234F-A36C-48C3-000361535105.f4v?key=97a96e82b8395b615609f45726bfd000112a08b9e3&qrs=1510477436&p=3714430663117687075&playtype=15&tk=76469989190395985440322118&brt=15&bc=0&xid=04001520195627C0BC0EE66D320764C9063661-234F-A36C-48C3-000361535105&nt=0&nw=1&bs=0&ispid=25&rc=200&inf=12&si=un&npc=2320&pp=0&ul=2&mt=0&sid=0&pc=0&cip=101.39.27.192&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=361535105&fi=0&sz=33071649
When I use brower to open it.

![qq 20160502105413](https://cloud.githubusercontent.com/assets/14276116/14946432/abee1f36-1054-11e6-8332-dcf79ac79a51.png)
ng…]()

**Comment by zhangn1985** [comment]
direct play tudou original video by you-get -p PLAYER, please set PLAYER's UA to empty

**Comment by zhangn1985** [comment]
@cybmp3 please feedback and close this issue.

**Comment by cybmp3** [comment]
![qq 20160510184901](https://cloud.githubusercontent.com/assets/14276116/15144131/0f9948f8-16e0-11e6-8849-0e224814abd5.png)
![qq 20160510184950](https://cloud.githubusercontent.com/assets/14276116/15144152/407ac514-16e0-11e6-81a9-9411967a9359.png)
![qq 20160510185033](https://cloud.githubusercontent.com/assets/14276116/15144155/40a49b64-16e0-11e6-9cab-e0a630d77ef9.png)
still not work.....
