### ISSUE TITLE
求简单图形界面

### ISSUE THREAD

**Issue by jdfq** [soimort/you-get#1100]
现在优酷的解析工具皆阵亡，不知这个？然后我不懂英文和命令，求图形界面，对你们不难吧？

**Comment by cnbeining** [comment]
在可预见的未来```you-get```不会主动成为具有GUI的程序。

一部分其他软件可以调用```you-get```作为插件使用。

**Comment by jdfq** [comment]
求调用的程序

**Comment by cybmp3** [comment]
图形界面并不好用啊。自己用Python写一个不麻烦的，几十行的事情。 
------------------ Original ------------------
