### ISSUE TITLE
优酷土豆有VIP账号也无法下载完整视频

### ISSUE THREAD

**Issue by shuijign** [soimort/you-get#1101]
有优酷土豆的VIP账号，在线观看正常。约四五天前仍然可以通过cookies下载到完整视频。
但现在只能下载到视频的前3段，无法下载全部内容。

例如：http://www.tudou.com/albumplay/krKFWeKKSvY/tCZ2TAECCmw.html

请问是cookies问题还是优酷土豆调整导致这一问题？

you-get: version 0.4.390, a tiny downloader that scrapes the web.

>you-get -c C:/Users/smith/AppData/Roaming/Mozilla/Firefox/Profiles/exa0hx1k.default\cookies.sqlite http://www.tudou.com/albumplay/krKFWeKKSvY/tCZ2TAECCmw.html
site:                优酷 (Youku)
title:               第05话 相反
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          536.0 MiB (562058639 bytes)
    # download-with: you-get --format=hd3 [URL]

Downloading 第05话 相反.flv ...
 0.0% (  0.0/536.0MB) ├──────────────────────────── 0.0% (  0.2/536.0MB) ├──────────────────────────── 0.1% (  0.5/536.0MB) ├──────────────────────────── 0.1% (  0.8/536.0MB) ├──────────────────────────── 0.2% (  1.0/536.0MB) ├──────────────────────────── 0.2% (  1.2/536.0MB) ├──────────────────────────── 0.3% (  1.5/536.0MB) ├──────────────────────────── 0.3% (  1.8/536.0MB) ├──────────────────────────── 0.4% (  2.0/536.0MB) ├──────────────────────────── 0.4% (  2.2/536.0MB) ├──────────────────────────── 0.5% (  2.5/536.0MB) ├────────────────────────────27.0% (145.0/536.0MB) ├████████████────────────────
─────────────┤[3/3]    2 MB/s
Merging video parts... Done.

**Comment by AtaraxiaEta** [comment]
同样出现了这个问题
