### ISSUE TITLE
Yinyuetai视频无法下载

### ISSUE THREAD

**Issue by imcaffrey** [soimort/you-get#1102]
link: v.yinyuetai.com/video/h5/2466113

执行you-get之后直接退出

加--debug之后也是直接退出

谢谢！

**Comment by imcaffrey** [comment]
http:v.yinyuetai.com/video/h5/2466113

**Comment by cnbeining** [comment]
@soimort-bot Please kindly test this: http://v.yinyuetai.com/video/h5/2466113

**Comment by imcaffrey** [comment]
正常的链接大概都是这样的:`http://v.yinyuetai.com/video/2534905`

video之后是个数字

yinyuetai.py#20 直接用了 `\d` 会不会是这个问题？

**Comment by zhangn1985** [comment]
@imcaffrey 不是
API改变了把
https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/yinyuetai.py#L8
改成
http://ext.yinyuetai.com/main/get-h-mv-info?json=true&videoId=%s
就可以了。

**Comment by imcaffrey** [comment]
Thx.
