### ISSUE TITLE
acfun跳转letvcloud的视频下载不了

### ISSUE THREAD

**Issue by chweiii** [soimort/you-get#1104]
link:    http://www.acfun.tv/v/ac1536756
执行you-get之后直接退出
加--debug之后也是直接退出
是letvcloud的资源

**Comment by soimort** [comment]
@soimort-bot Test this: http://www.acfun.tv/v/ac1536756

**Comment by zhangn1985** [comment]
这个URL用浏览器也不能播放，请提供新的URL

**Comment by cnbeining** [comment]
It could be Acfun's problem. I will get in touch with them while I dig out something.

**Comment by cnbeining** [comment]
我细看了一下 好像不是Acfun的锅。

直到 http://play.g3proxy.lecloud.com/vod/v2/MTI1LzIvMTEzL2JjbG91ZC8xMjM5NjYvdmVyXzAwXzE4LTMxMzM2ODc2LWF2Yy02ODExNjctYWFjLTk2MDAwLTIzNDA4Ny0yMjk4NjQ4Mi00MTQyZGVkOGQxZGVmMmQ5NzJjZWU3NGY4ZDAzMTc0OS0xNDE1ODc0OTI2NTA4Lm1wNA==?b=785&mmsid=24754261&tm=1462469909&key=48a7009456fab94598e87c75cd42b098&platid=2&splatid=207&playid=0&tss=ios&vtype=28&cvid=1740420513944&payff=0&pip=a0ddc6cf2981a58055563e561a80b63c&tag=flash&sign=bcloud_123966&termid=1&pay=0&ostype=windows&hwtype=un&ctv=pc&m3v=1&format=1&hwtype=un&ostype=MacOS10.11.4&tag=bcloud&sign=bcloud_123966&ch=bcloud_123966&expect=3&tn=0.9285116097889841&uuid=D90F443B82E6112921F981E39B7FA74163A9B219&rateid=yuanhua 都是好的 但是link就404.

估计我们也没办法。

如果有其他确定转码好的文件还是报错，请继续。如果没有 3日后先关掉。

**Comment by chweiii** [comment]
@zhangn1985 这个链接页面可以播放的

**Comment by cnbeining** [comment]
我复测失败啊亲

![en 1 c9mvs03 gvfrv 6c](https://cloud.githubusercontent.com/assets/1560962/15063563/4988aa24-1319-11e6-9e63-235bcbd999dd.jpg)

**Comment by zhangn1985** [comment]
lecloud 似乎已经不能用了。

**Comment by cnbeining** [comment]
钱花完了吧。

那也没什么办法 为这个hack不值。

2016年6月18日星期六，zhangn1985 <notifications@github.com> 写道：

**Comment by zhangn1985** [comment]
lecloud的算法似乎失效了，不过目前似乎没有哪家在用lecloud 做视频存储了吧。

没必要在去弄lecloud。

**Comment by cnbeining** [comment]
多烦人啊。

以后我啥时候有心再说吧。


2016年6月18日星期六，zhangn1985 <notifications@github.com> 写道：

**Comment by cnbeining** [comment]
乐视云算法没失效。

但是Ac和乐视的协议到期了。

```
http://api.letvcloud.com/gpc.php?ver=2.2&format=json&ran=1466570102&cf=flash&uu=ab417c1571&vu=b4c30c21c0&sign=4846d53b034ca49f6a3bac3b22bb40e8
```
![image](https://cloud.githubusercontent.com/assets/1560962/16254759/6784e700-3811-11e6-92ff-5a09a5dfd193.png)

**Comment by zhangn1985** [comment]
我看了letvcloud的json请求，似乎需要一个page_url的参数。

**Comment by cnbeining** [comment]
对于某些站需要。

某些站不需要也可以解析。

至少sign里面没有强制。。。算法还是没变。

**Comment by zhangn1985** [comment]
目前我看到的规律是，如果视频能在yun.letv.com上播放的话，就不需要page_url。反之则需要。

所以乐视云的视频嵌入到其他网站播放，那么就会带page_url这个参数，那不带这个参数去请求视频，就会得到错误。

**Comment by cnbeining** [comment]
坑爹。

也许以后我们可以加一个faker 应对这种情况吧。

![image](https://cloud.githubusercontent.com/assets/1560962/16255691/f7aac1f8-3819-11e6-9a84-04865b15cc07.png)

**Comment by adslen** [comment]
乐视云计算sign的key值换成“04c5e1e616f668bc559af2afa98b9a25”这个了，整个算法在vrp.js中，里面两个关键函数getSign和getRequestList。请更新下，我不会python

**Comment by cnbeining** [comment]
AC没有任何letvcloud的视频了。
