### ISSUE TITLE
无法解析dilidili.com新番，在http://www.dilidili.com/watch3/域名下的视频

### ISSUE THREAD

**Issue by ksnzh** [soimort/you-get#1113]
错误还原：

```
➜  ~ you-get -p mpv http://www.dilidili.com/watch3/37348/
➜  ~ you-get -p mpv http://www.dilidili.com/watch3/37348/
➜  ~ 
```

我看了下源码，dilidili.py没有匹配`/watch3`

```python
def dilidili_download(url, output_dir = '.', merge = False, info_only = False, **kwargs):
    if re.match(r'http://www.dilidili.com/watch/\w+', url):
```

**Comment by cnbeining** [comment]
啧。

我找时间修下。

2016年5月9日星期一，ksnzh <notifications@github.com> 写道：

**Comment by kwokts** [comment]
改 line 38
if re.match(r'http://www.dilidili.com/watch\d*/\w+', url):

you-get -i http://www.dilidili.com/watch3/37348/
Site:       CKPlayer General
Title:      我叫坂本我最屌 第4话 坂本是臭流氓吗？
Type:       MPEG-4 video (video/mp4)
Size:       184.63 MiB (193598554 Bytes)

**Comment by soimort** [comment]
Closed via #1120.
