### ISSUE TITLE
About the default download file

### ISSUE THREAD

**Issue by changecheung** [soimort/you-get#1130]
Hi,there.How can I find the youget default download file?Because it kinda weird that when I change the download file,the whole download just never made,yeah...never.so please is there any way to locate the default file where some of video already being in?or something really went wrong about youget?

**Comment by cnbeining** [comment]
Most of the time the file is located at the working folder.

Did you tried to search for the name of video?

2016年5月14日星期六，Mort the Bot <notifications@github.com> 写道：

**Comment by changecheung** [comment]
Thanks you guys.I finally found it in Administrator folder.And maybe I just made a stupid mistake writting a command like this "you-get -o ~/Videos xxx(url)"which you can find it on https://github.com/soimort/you-get. The turth is you don't wanna type the "~/",or it won't work. Like"you-get -o C:\workplace xxx(url)"just goes pretty well !  BTW,really appreciate your kindness and quick response.
