### ISSUE TITLE
关于默认下载路径的问题

### ISSUE THREAD

**Issue by changecheung** [soimort/you-get#1131]
你好，请问youget的默认下载路径在哪呢？有几个视频成功下载，但是根本找不到在哪里。后来知道可以修改下载路径，但是修改后没有一次成功下载，因此感到很奇怪，请问有谁知道是什么原因吗？

**Comment by cnbeining** [comment]
请勿开多个issue。

2016年5月14日星期六，Mort the Bot <notifications@github.com> 写道：
