### ISSUE TITLE
对于分段视频(如优酷),如何进行多线程下载(像之前硕鼠那样支持最多5个视频同时下载)

### ISSUE THREAD

**Issue by xinshangshangxin** [soimort/you-get#1136]
RT

**Comment by cnbeining** [comment]
目前没有这种功能。

**Comment by xinshangshangxin** [comment]
`描述过于简短`  被close了,
是不是应该 reopen下?
@cnbeining

**Comment by soimort** [comment]
Duplicate of #510.

请求新功能请如 #510 一样给出具体的描述和建议方案，否则还是会被 close。

**Comment by xinshangshangxin** [comment]
@soimort 
为我的偷懒道歉..

但是从 #510 来看, 只是 on plan? 有确切的计划实现吗?

**Comment by soimort** [comment]
> 只是 might need a rewrite from scratch to support this. It's on my plan, though 有确切的计划实现吗?

因为没有时间去做，所以暂时只能搁置在那里而已。

欢迎pull request。
