### ISSUE TITLE
[Netease] Please support downloading music from its program shows.

### ISSUE THREAD

**Issue by Jackeriss** [soimort/you-get#1145]
Now you-get can download music from urls like :
http://music.163.com/#/song?id=410801515
but can't download music from urls like:
http://music.163.com/#/program?id=787307503

Is there any way to support this?

**Comment by soimort** [comment]
I got a `ERR_CONNECTION_REFUSED` message on their MP3 files, even in my browser. Don't know if it's a region restriction or alike.
