### ISSUE TITLE
可以在不或不完全下载时获取视频时长吗？

### ISSUE THREAD

**Issue by harr999y** [soimort/you-get#1146]
因为项目有这个需求，类似youtube-dl的 --get-duration，不过他那个经常不好使。

不知道有办法吗？

谢谢~ 😃

**Comment by cnbeining** [comment]
Youube-dl的办法是。。。。。。。。。很简单 页面上或者API里面给了就有 没有就没有。

要是没给呢？

我只有一种坑爹办法：

https://github.com/cnbeining/Biligrab/blob/master/biligrab.py#L641-L678

我不准备大量在本项目使用这个方法，因为解析速度估计会慢的不能接受。

希望有所帮助。

**Comment by soimort** [comment]
> 因为项目有这个需求，类似youtube-dl的 --get-duration，不过他那个经常不好使。

自己的项目自己写。您这得看具体情况具体实现。

有些视频网站 API 给了长度信息，不给的解析出来真实地址后用 `ffprobe`。HTML5 video 有 duration 属性，当然前提是能访问到它的 DOM，`you-get`这种纯 Python 爬虫估计是不行了。

当然ffprobe/avprobe不是什么坑爹办法，而且可能是唯一能获取任意视频metadata的办法。当然本项目应该不会用，因为下载器基本没这个需求。想看的用户可以解析出地址自己用ffprobe看。

**Comment by harr999y** [comment]
好的，我了解了~ 非常感谢两位详细的解答，太赞了  💯 
🆒
