### ISSUE TITLE
希望添加对“企鹅直播”的支持

### ISSUE THREAD

**Issue by j20120307** [soimort/you-get#1148]
应该和斗鱼差不多

For example: http://live.qq.com/q/xiaochenNBA

感谢作者！

**Comment by zhangn1985** [comment]
是挺简单的。

**Comment by cnbeining** [comment]
@yan12125 It seems that the player is almost the same as Douyu's, but I cannot get the douyu.py working on this player. Do you want to have a look while I work out a temp solution?
