### ISSUE TITLE
是必须要python3.5吗？但是python3.5不支持xp

### ISSUE THREAD

**Issue by tulip33** [soimort/you-get#1150]
在xpsp3安装了python3.4.4，系统属性中设置了环境变量，运行youget.bat，提示【无法定位程序输入点 getfinalpathnamebyhandlew于动态链接库kernel32.dll上】，命令窗口显示【Error loading Python DLL: c:\temp\_MEI29162\python35.dll (error code 127)】，
在win7安装了python3.51，运行youget正常，
但是python3.51无法在xp中安装，youget只能在win7运行吗？怎样在xp下运行？
谢谢！

**Comment by cnbeining** [comment]
```you-get```可以在所有主流的Python3中运行。

这里不使用很激进的东西。

**Comment by soimort** [comment]
1. `you-get.bat` 是用来运行 `you-get.exe` 的脚本，而用 `you-get.exe` 根本不需要自己安装 Python。但是这个预编译包肯定不支持 Win 7 以前的版本。
2. 如果要在 XP 上用 `you-get`，可以自己从 pip 安装。

**Comment by tulip33** [comment]
非常感谢！问题解决，可以在xp下使用youget下载了

**Comment by jdfq** [comment]
xp 怎么安装？

**Comment by cnbeining** [comment]
Python的官网就有下载。

而且讲道理，xp并不需要一定升级到最新的Python：大版本好了就OK。

2016年6月15日星期三，jdfq <notifications@github.com> 写道：

**Comment by jdfq** [comment]
怎么装和用you-get?

**Comment by jdfq** [comment]
好像是python环境变量问题。希望教程写明
