### ISSUE TITLE
Mac下 本地播放器播放流媒体如何将播放器喂进终端？

### ISSUE THREAD

**Issue by agonyice123** [soimort/you-get#1153]
$ you-get -p VLC.app http://www.bilibili.com/video/av1358868/
Site:       bilibili.com
Title:      1、太阳的黑点
Type:       Flash video (video/x-flv)
Size:       170.4 MiB (178675236 Bytes)

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

不知道是不是这么弄？

**Comment by agonyice123** [comment]
..能解答下吗~~实在没弄懂这里

**Comment by soimort** [comment]
Hello @agonyice123,
Please rerun the command with --debug option, and report this issue with the full output.
Thanks.

Yours harmlessly
Mort

**Comment by HuberyHuan** [comment]
@agonyice123  You can try this **`you-get -p /Applications/VLC.app/Contents/MacOS/VLC http://www.bilibili.com/video/av1358868/ `**
Good luck

**Comment by agonyice123** [comment]
Thanks  a lot.
