### ISSUE TITLE
xp能下载，但是无法合并，xp下怎样安装ffmpeg？谢谢！

### ISSUE THREAD

**Issue by tulip33** [soimort/you-get#1154]
> [xp下在python中安装了youget，能下载视频了，但是下载的分段视频不能合并，怎样在xp安装ffmpeg？谢谢！
> 用安装youget方式输入命令【pip3.4.exe install ffmpeg】，提示【Collecting ffmpeg
  Could not find a version that satisfies the requirement ffmpeg (from versions:
 )
No matching distribution found for ffmpeg】

**Comment by zhangn1985** [comment]
https://ffmpeg.zeranoe.com/builds/

**Comment by soimort** [comment]
如上。
记得把`ffmpeg`加入路径。

**Comment by tulip33** [comment]
@soimort 
环境变量里设置ffmpeg路径了，运行ffmpeg提示【无法定位程序输入点 _wfopen_s 于动态链接库 msvcrt.dll上】，怎么解决呢？谢谢

**Comment by tulip33** [comment]
@soimort
但在windows\system32目录下有msvcrt.dll这个文件，版本是7.0.2600.5512，大小是343,040字节
是否ffmpeg不支持xp？

**Comment by soimort** [comment]
你应该去下32位+静态链接的版本。如果再不支持那就是真的不支持了。

**Comment by tulip33** [comment]
@soimort 
试了ffmpeg旧版,3.0及之前版本可以运行,但是无法合并,提示
99.6% (168.2/168.8MB) ├███████████████████████████
 100% (168.8/168.8MB) ├███████████████████████████
█████████┤[302/302]   13 MB/s
Merging video parts... you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

下载的视频网址和参数是 --format 350 http://www.le.com/ptv/vplay/25468632.html
debug信息如下：
99.0% (167.0/168.8MB) ├████████████████████████████
99.3% (167.6/168.8MB) ├████████████████████████████
99.6% (168.2/168.8MB) ├████████████████████████████
 100% (168.8/168.8MB) ├████████████████████████████
█████████┤[302/302]   13 MB/s
Merging video parts... you-get: version 0.4.390, a tiny downloader that scrapes
the web.
you-get: ['http://www.le.com/ptv/vplay/25468632.html']
Traceback (most recent call last):
  File "D:\Python34\Scripts\you-get-script.py", line 9, in <module>
    load_entry_point('you-get==0.4.390', 'console_scripts', 'you-get')()
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\__main__
.py", line 92, in main
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\common.p
y", line 1274, in main
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\common.p
y", line 1182, in script_main
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\common.p
y", line 1030, in download_main
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\common.p
y", line 1267, in any_download
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\extracto
rs\le.py", line 137, in letv_download
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\extracto
rs\le.py", line 98, in letv_download_by_vid
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\common.p
y", line 762, in download_urls
  File "d:\python34\lib\site-packages\you_get-0.4.390-py3.4.egg\you_get\processo
r\ffmpeg.py", line 174, in ffmpeg_concat_mp4_to_mp4
  File "d:\python34\lib\subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ffmpeg', '-loglevel', 'quiet', '-f', '
concat', '-safe', '-1', '-y', '-i', 'N:\\vidown\\《全员加速中第二季》20160520：
宋小宝扮八戒被坑惨 女版田大圣亮瞎.mp4.txt', '-c', 'copy', 'N:\\vidown\\《全员加
速中第二季》20160520：宋小宝扮八戒被坑惨 女版田大圣亮瞎.mp4']' returned non-zero
 exit status 1

**Comment by tulip33** [comment]
使用的ffmpeg版本是这个
https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-3.0-win32-static.7z

**Comment by soimort** [comment]
@cnbeining You might want to bring to table #1041, if you'd like to redo it. Otherwise I'll do that later.

**Comment by tulip33** [comment]
@soimort 
谢谢回复！
加参数-bsf:a aac_adtstoasc手工合并成功，难道xp下只能手工合并了吗？哎，麻烦

**Comment by soimort** [comment]
#813 应该很快就会修复的。请稍等。
