### ISSUE TITLE
更改默认下载路径？

### ISSUE THREAD

**Issue by xxf1995** [soimort/you-get#1160]
OSX 10.11如何更改默认下载路径？现在默认在~/，希望更改到~/downloads

**Comment by soimort** [comment]
See `you-get --help`

**Comment by xxf1995** [comment]
`-o` It's changing default path? I thought it is only changing for the particular file

**Comment by soimort** [comment]
There's no such thing like a "default" path. `you-get` only downloads file to the **current path**; and if another path is specified via `-o`, it will use that one instead.

**Comment by isky0824** [comment]
you-get https://www.youtube.com/xxx
用过上面默认的下载方式下载，下载完之后文件在哪啊，亲？？？到处找不到，再次下载的时候说文件已存在，自动Skip了。

**Comment by rosynirvana** [comment]
@isky0824 
终端里敲```pwd```
windows的```cmd.exe```是直接显示全路径的
