### ISSUE TITLE
B站只解析到一个清晰度版本，不能选择其它版本

### ISSUE THREAD

**Issue by cangling** [soimort/you-get#1167]
you-get: version 0.4.424

you-get -i -d http://www.bilibili.com/video/av2510745/
[DEBUG] get_content: http://www.bilibili.com/video/av2510745/
[DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=8e9fc618fbd41e28&cid=3921626
Site:       bilibili.com
Title:      【剧场版】东京教父
Type:       Flash video (video/x-flv)
Size:       1054.51 MiB (1105730949 Bytes)

在网页端，这个视频有3个清晰度可以选择，you-get 只能解析‘超清’。
有时想下载后复制到手机上看，这时下载超清的没必要，不但下载时间长，复制时间也长。

不知可以解决？

谢谢！

**Comment by cnbeining** [comment]
需要大重写。

好大的工作，优先度不是很高。。有空写吧。

**Comment by cangling** [comment]
好的。谢谢！

**Comment by rosynirvana** [comment]
close via #1698
