### ISSUE TITLE
bilibili failed 

### ISSUE THREAD

**Issue by zhangn1985** [soimort/you-get#1176]
````
you-get -diu http://www.bilibili.com/video/av4790783/
[DEBUG] get_content: http://www.bilibili.com/video/av4790783/
[DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=8e9fc618fbd41e28&cid=7773908
Site:       bilibili.com
Title:      【4月】逆转裁判 09
Type:       Unknown type ()
Size:       0.0 MiB (0 Bytes)
```

@soimort-bot please test: http://www.bilibili.com/video/av4790783/

**Comment by yan12125** [comment]
#1174

**Comment by zhangn1985** [comment]
no no
api 调用返回的是：
```
{"error_code":"E103","error_text":"API调用失败.校验失败"}
```

**Comment by zhangn1985** [comment]
目前猜测是appkey失效了
暂时可以用这个方法workaround
```
vid = match1(url, 'av(\d+)')
page = match1(url, 'page=(\d+)', '_(\d+).html') or 1
api_url = 'http://www.bilibili.com/m/html5?aid={}&page={}'.format(self.vid,page)
```

**Comment by yan12125** [comment]
了解。Bilibili Android client用的appkey f3bb208b3d081dc8看起來還沒被封，只是需要sign。See yan12125/iqiyi-hack#2

**Comment by soimort** [comment]
The `sign` paramater is the md5 sum of _something_, which we don't know.

If you know the algorithm to calculate `sign` from timestamp, `appkey` is not even necesssary, since this is the way how a valid request is formed: (in a browser)

http://interface.bilibili.com/playurl?accel=1&cid=7774760&player=1&ts=1464438338&sign=e5e613396d162bdf36f06343cd5d2d89

**Comment by yan12125** [comment]
Well my fault appkey f3bb208b3d081dc8 works without a signature. Tested on youtube-dl.

**Comment by yan12125** [comment]
Another appkey fetched by sniffing Android client traffic, 86385cdc024c0f6c, also works.

**Comment by soimort** [comment]
Makes sense, so we don't need to reverse that `sign` after all.

Thanks @yan12125

**Comment by cnbeining** [comment]
Should this fix dead sometime in the future, I shall public the signing
algorithm of SWF player.

Separate APPSEC for iOS and Android are loaded via a remote file. That's
why doing reverse engineering on the APK would be in vain.

2016年5月28日星期六，Mort Yao <notifications@github.com> 写道：

**Comment by yan12125** [comment]
> Separate APPSEC for iOS and Android are loaded via a remote file.

Do you know the URL?

**Comment by cnbeining** [comment]
No.

But you should able to capture the package on level 7.

2016年5月28日星期六，Yen Chi Hsuan <notifications@github.com> 写道：

**Comment by yan12125** [comment]
Thanks. There are way too many packets and shamefully I don't know which one contains the key.

**Comment by cnbeining** [comment]
It is a lua script.

2016年5月28日星期六，David.Zhuang <cnbeining@gmail.com> 写道：

**Comment by yan12125** [comment]
Sounds hijacking the flash is still the way. There are too many possibilities on Android. AFAIK Lua decompilers are not mature enough for generic uses, and BiliBili can always change the bytecode mapping of Lua. Last time I've tried to install Flash debug player on my machine but failed. I'm afraid I can't help on breaking BiliBili recently.

**Comment by cnbeining** [comment]
They are using a sh*tload of obfuscation.

Next time we want to start with ram dump.

2016年5月28日星期六，Yen Chi Hsuan <notifications@github.com> 写道：
