### ISSUE TITLE
Contributing Zsh completion definition

### ISSUE THREAD

**Issue by zmwangx** [soimort/you-get#1178]
I would like to contribute a Zsh completion definition script for `you-get`:

```zsh
#compdef you-get

setopt localoptions noshwordsplit noksharrays
local -a args

args=(
    '(- : *)'{-V,--version}'[print version and exit]'
    '(- : *)'{-h,--help}'[print help and exit]'
    '(-i --info)'{-i,--info}'[print extracted information]'
    '(-u --url)'{-u,--url}'[print extracted information with URLs]'
    '(--json)--json[print extracted URLs in JSON format]'
    '(-n --no-merge)'{-n,--no-merge}'[do not merge video parts]'
    '(--no-caption)--no-caption[do not download captions]'
    '(-f --force)'{-f,--force}'[force overwrite existing files]'
    '(-F --format)'{-F,--format}'[set video format to the specified stream id]:stream id'
    '(-O --output-filename)'{-O,--output-filename}'[set output filename]:filename:_files'
    '(-o --output-dir)'{-o,--output-dir}'[set output directory]:directory:_files -/'
    '(-p --player)'{-p,--player}'[stream extracted URL to the specified player]:player and options'
    '(-c --cookies)'{-c,--cookies}'[load cookies.txt or cookies.sqlite]:cookies file:_files'
    '(-x --http-proxy)'{-x,--http-proxy}'[use the specified HTTP proxy for downloading]:host\:port:'
    '(-y --extractor-proxy)'{-y,--extractor-proxy}'[use the specified HTTP proxy for extraction only]:host\:port'
    '(--no-proxy)--no-proxy[do not use a proxy]'
    '(-t --timeout)'{-t,--timeout}'[set socket timeout]:seconds'
    '(-d --debug)'{-d,--debug}'[show traceback and other debug info]'
    '*: :_guard "^-*" url'
)
_arguments -S -s $args
```

It could be put in `contrib/completion/_you-get` or something like that. I need to make sure this is welcome and figure out the desired path before being able to make a PR.

**Comment by soimort** [comment]
This is surely welcome _on my side_.

I don't have a clear idea on their convention of desired paths (and I don't use completions a whole lot); choose whatever you think is proper.

**Comment by cnbeining** [comment]
Nice PR.

I am thinking it would be easier later if we use some automatic script to
generate this file...just thinking.

2016年5月28日星期六，Mort Yao <notifications@github.com> 写道：

**Comment by zmwangx** [comment]
@soimort Path of the script in this repo doesn't matter much because users will most likely need to either symlink or copy the file to a standard or aggregate directory.

@cnbeining If you have a good idea of automating this I'm ears.

**Comment by MYJN** [comment]
@cnbeining 
我的哪个问题#1179，视频播放是正常的，you-get 解析出错，最大原因涉及到账户权限问题！

**Comment by cnbeining** [comment]
请不要在不相关的issue里谈论其他issue的问题。

**Comment by zmwangx** [comment]
@MYJN Please stay on topic.

**Comment by MYJN** [comment]
OK

**Comment by zmwangx** [comment]
@cnbeining Could you please remove the off-topic comments? Thanks.
