### ISSUE TITLE
bilibili的解析不出来，是我的系统、python有问题？

### ISSUE THREAD

**Issue by MYJN** [soimort/you-get#1179]
python ：3.5.1
windows 10 （10.0.10586）
+------------------------------------+
C:\Users\WINDOWS>you-get -i http://www.bilibili.com/video/av4789557/ 
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
+--------------------------------------+
C:\Users\WINDOWS>you-get -i -d http://www.bilibili.com/video/av4789557/
[DEBUG] get_content: http://www.bilibili.com/video/av4789557/
you-get: version 0.4.424, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av4789557/']
Traceback (most recent call last):
  File "c:\tool\python\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\tool\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Tool\Python\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\tool\python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\tool\python\lib\site-packages\you_get\common.py", line 1277, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\tool\python\lib\site-packages\you_get\common.py", line 1190, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\tool\python\lib\site-packages\you_get\common.py", line 1033, in download_main
    download(url, **kwargs)
  File "c:\tool\python\lib\site-packages\you_get\common.py", line 1270, in any_download
    m.download(url, **kwargs)
  File "c:\tool\python\lib\site-packages\you_get\extractors\bilibili.py", line 122, in bilibili_download
    assert flashvars
AssertionError
+-----------------------------+
求解！谢谢！

**Comment by cnbeining** [comment]
请升级到Github上分支develop的最新版。

2016年5月28日星期六，Mort the Bot <notifications@github.com> 写道：

**Comment by 411261479** [comment]
升级后还是同样的问题

**Comment by zhangn1985** [comment]
这个视频不存在， 或者需要登陆

**Comment by 411261479** [comment]
不不不，我是昨天晚上突然下载不来的。之前还在B站下了几个。

**Comment by lbc001** [comment]
i have the same quesion  = .=.what happened.it is that the bilibili has changed something......

**Comment by cnbeining** [comment]
For anyone having similar problem:

- Are you using the latest develop branch?

- Are you sure that this video is not encoding? This can be very long, even months!

- Are you sure that you do not have to login to watch such video? If not, kindly check out Wiki for instructions. 

- Are you sure that this video is not subject to geography restrictions? Also we have provided detailed instructions in the Wiki.  

Please notice those restrictions would differ from video to video: your able to download video A could have nothing to do with you cannot download video B. 

And, if worst comes to worst, please leave the video link here so we can try to reproduce such problem. It would be very helpful.

**Comment by 411261479** [comment]
How to update the latest by pip3？

**Comment by cnbeining** [comment]
I don't think PIP is having the latest patch updated... You may have to
grab this develop branch and do a python3 setup.py install.

Or you can wait for a little while if possible for I don't want you to mess
up your PIP..

2016年5月29日星期日，Bowenliang <notifications@github.com> 写道：

**Comment by lbc001** [comment]
It is that means  you are going to put the latest package on the pypi.XD,Then can i use "pip3 install --upgrate you-get" to get upgrated the you-get?

**Comment by nuomi1** [comment]
@411261479 @lbc001 
```
➜  ~ pip3 install --upgrade git+https://github.com/soimort/you-get
Collecting git+https://github.com/soimort/you-get
  Cloning https://github.com/soimort/you-get to /var/folders/dc/_sktz5gj1k3cvlvc6kqyhv880000gn/T/pip-spt1e_v9-build
Installing collected packages: you-get
  Found existing installation: you-get 0.4.424
    Uninstalling you-get-0.4.424:
      Successfully uninstalled you-get-0.4.424
  Running setup.py install for you-get ... done
Successfully installed you-get-0.4.424
```
After that, you still can use `pip3 install --upgrade you-get` to upgrade it from `https://pypi.python.org/pypi/you-get`.

**Comment by lbc001** [comment]
Thx.it can work now.XD.

**Comment by MYJN** [comment]
+----------------------------+
C:\Users\WINDOWS>pip3 -V
pip 8.1.2 from c:\tool\python\lib\site-packages (python 3.5)
+----------------------------+
C:\Users\WINDOWS>you-get -V
you-get: version 0.4.424, a tiny downloader that scrapes the web.
+----------------------------+
我的还是不行！

**Comment by lbc001** [comment]
@MYJN
你这个已经是最新的版本了.讲道理应该没问题.

**Comment by MYJN** [comment]
@lbc001 
我想我应该找到为什么下载不了的原因。是视频资源的问题！
同个上传者资源，我用you-get解析没有问题！
PS:目前只发现这个资源解析有问题！

**Comment by cnbeining** [comment]
要是视频不能看 那也没法下载呀。

难道不是天经地义的么。。。。。。。。。。
