### ISSUE TITLE
getopt + sys is stupid and and difficult to maintain,Why not use argparse or docopt instead

### ISSUE THREAD

**Issue by minghu6** [soimort/you-get#1181]
As the title said, 

using getopt + sys to parse shell args is stupid:

     python3 -m you_get -u http://v.yinyuetai.com/video/  # is ok
     python3 -m you_get   http://v.yinyuetai.com/video/ -u #is error
because you can't parse the url correctly. Furthermore, this way are not flexiable for args !

Besides, look at the relative code  in `common.script_main`,

fat `help`
terrible `opts` dared to have 254 columns,
What's the width of your screen,tuhao?! 

If you do not change the approach to parse args, You would became yu-xian-yu-s when deal
with multilevel args sucn as `--player<optional>`   and masses of args with a littele difficult data struct

**Comment by cnbeining** [comment]
As I understand your limited ability of English, I must urge you to
immediately stop using harassing language in your issues.

An formal complaint is being raised to Github officials.

2016年5月29日星期日，minghu6 <notifications@github.com> 写道：

**Comment by zhangn1985** [comment]
@cnbeining , @minghu6 says, using `getopt + sys ` is stupid, better to use argparse.

using argparse is better to maintain, and can avoid lots of issues.

https://github.com/zhangn1985/you-get/blob/master/you_get/param.py

this is a example to use argparse!

**Comment by lilydjwg** [comment]
So nobody is actually against rewriting with argparse? If so, I may do that so that no options will be left out from help any more.

**Comment by rosynirvana** [comment]
```getopt``` is far from stupid, just you linux guys hate BSD conventions

actually it's fine with ```gnu_getopt``` https://github.com/soimort/you-get/pull/1736
```
./you-get http://nb.zol.com.cn/650/6509483.html -u
site:                爱奇艺 (Iqiyi)
title:               拆机pa：如何变得更轻薄还带指纹识别？华硕U4100U拆机直播
stream:
    - format:        HD
      container:     m3u8
      video-profile: 540p
      m3u8_url:      http://cache.m.iqiyi.com/mus/8799075709/22f201c46ec0435665025c2c7d2e42dd/afbe8fd3d73448c9//20170811/d5/31/f0f6429dc49837c680510367a8a82392.m3u8?qd_originate=tmts_py&tvid=8799075709&bossStatus=0&qd_vip=0&px=&qd_src=null&prv=&previewType=&previewTime=&from=&qd_time=1502544267776&qd_p=7d2db2af&qd_asc=4c5b2f354d49f8464276bf17af499f65&qypid=8799075709_04022000001000000000_2&qd_k=5529b4f9fc908695f9cced92af703e34&vf=ca59499dc61db175d3cb675f077698fd&np_tag=nginx_part_tag
    # download-with: you-get --format=HD [URL]

Real URL:
['http://cache.m.iqiyi.com/mus/8799075709/22f201c46ec0435665025c2c7d2e42dd/afbe8fd3d73448c9//20170811/d5/31/f0f6429dc49837c680510367a8a82392.m3u8?qd_originate=tmts_py&tvid=8799075709&bossStatus=0&qd_vip=0&px=&qd_src=null&prv=&previewType=&previewTime=&from=&qd_time=1502544267776&qd_p=7d2db2af&qd_asc=4c5b2f354d49f8464276bf17af499f65&qypid=8799075709_04022000001000000000_2&qd_k=5529b4f9fc908695f9cced92af703e34&vf=ca59499dc61db175d3cb675f077698fd&np_tag=nginx_part_tag']
```

**Comment by lilydjwg** [comment]
`getopt` is too low-level. One issue of it is that it doesn't maintain help text so nothing can ensure the  help text is in sync.

**Comment by rosynirvana** [comment]
Before we move to some higher level cmdline lib there is much to fix first.
F. I. by definition, ```-i``` ```-u``` ```--json``` are all dry run options
```
Dry-run options: (no actual downloading)
    -i | --info                         Print extracted information.
    -u | --url                          Print extracted information with URLs.
         --json                         Print extracted URLs in JSON format.
```
So they should be put in an exclusive group. But actually ```--json``` is a monkey-patching like dirty hack. ```info_only``` must be turned on to use it. And every module file import all from ```common.py``` and they may access the globals in ```common.py```. The flags got from argparse must be exported to global.

```argparse``` is somewhat low level itself. It does not support a configure file last time I check it.

So moving is good, but low priority IMHO.
