### ISSUE TITLE
bilibili视频无法下载

### ISSUE THREAD

**Issue by 4321qasdfv** [soimort/you-get#1185]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:
```
 you-get -u --debug http://www.bilibili.com/video/av4806450
[DEBUG] get_content: http://www.bilibili.com/video/av4806450
[DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=8e9fc618fbd41e28&cid=7799354
Site:       bilibili.com
Title:      【4月】Re：从零开始的异世界生活 09
Type:       Unknown type ()
Size:       0.0 MiB (0 Bytes)

you-get: version 0.4.424, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av4806450']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1277, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1190, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1033, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1270, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/bilibili.py", line 155, in bilibili_download
    info_only=info_only)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/bilibili.py", line 99, in bilibili_download_by_cid
    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, merge=merge)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 679, in download_urls
    assert urls
AssertionError
```
如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 一星期前 还是可以下载的 今天突然不行了。导入cookies也是一样的结果。试了好几个视频都不能下了（ 这几个视频还是上星期成功下过的）。更新提示无新版本。
而且，一星期前就有无法定位到某一p的问题。输入某一分p的地址还是会解析到所有视频的地址。

> [舔 :icecream:!]

**Comment by cnbeining** [comment]
请升级到Github上的最新版。

2016年5月30日星期一，Mort the Bot <notifications@github.com> 写道：

**Comment by jackjin987** [comment]
请问这个b站视频不能下载的问题解决了吗？我也遇到同样的问题，还有youtube也不能下载啊，只能下优酷，爱奇艺

**Comment by babopo** [comment]
*解决了吗? 同不能下*

**Comment by cnbeining** [comment]
@jackjin987 @babopo 你是否使用了**最新** 版？

**Comment by jackjin987** [comment]
是使用的最新版本啊，b站和youtube都无法下载，其他网站可以

**Comment by cnbeining** [comment]
请提供测试URL。

**Comment by jackjin987** [comment]
C:\Users\Administrator>you-get http://www.bilibili.com/video/av4061568/
Site: bilibili.com
Title: 【咬人猫】妖精的尾巴OP15❤MASAYUME CHASING o(-≧▽≦)ツ
UME CHASING o(-≧▽≦)ツ
��)ツ

Type: Unknown type ()
Size: 0.0 MiB (0 Bytes)

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get: (1) Rule out any network problem.
you-get: (2) Make sure you-get is up-to-date.
you-get: (3) Check if the issue is already known, on
you-get: https://github.com/soimort/you-get/wiki/Known-Bugs
you-get: https://github.com/soimort/you-get/issues
you-get: (4) Run the command with '--debug' option,
you-get: and report this issue with the full output.

**Comment by nuomi1** [comment]
@jackjin987 No problem with https://github.com/soimort/you-get/commit/cb39f4b9f34066b7d4c053f7922420d38dd88e72.

**Comment by jackjin987** [comment]
@nuomi1 你好，能不能贴一下完整的下载方式，看不懂你上面的。看那个说要载入cookies，可是怎么载入
you-get -i -c ~/.mozilla/firefox/gggfz9xl.default/cookies.sqlite \ http://www.bilibili.com/video/av2987444
按照上面这种方式也无法下载啊

**Comment by nuomi1** [comment]
@jackjin987 Use `pip3 install --upgrade git+https://github.com/soimort/you-get@develop` to upgrade  the latest version.

**Comment by jackjin987** [comment]
@nuomi1 这应该是最新版本了pip (8.1.2)
setuptools (18.2)
wheel (0.29.0)
you-get (0.4.424)

**Comment by nuomi1** [comment]
![](https://tb2.bdstatic.com/tb/editor/images/xyj/xyj_038.gif)
已阵亡。

**Comment by jackjin987** [comment]
C:\Users\Administrator> you-get -u --debug http://www.bilibili.com/video/av48381
20/
[DEBUG] get_content: http://www.bilibili.com/video/av4838120/
[DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=8e9fc618fbd41e
28&cid=7853154
Site:       bilibili.com
Title:      【马猴给给组合】【初投稿】谎言与玩偶【新人渣向勿喷】
��投稿】谎言与玩偶【新人渣向勿喷】
玩偶【新人渣向勿喷】
人渣向勿喷】
�勿喷】
�】

Type:       Unknown type ()
Size:       0.0 MiB (0 Bytes)

you-get: version 0.4.424, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av4838120/']
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\runpy.
py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\runpy.
py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\Scripts\yo
u-get.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\you_get\common.py", line 1277, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\you_get\common.py", line 1190, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\you_get\common.py", line 1033, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\you_get\common.py", line 1270, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\you_get\extractors\bilibili.py", line 155, in bilibili_download
    info_only=info_only)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\you_get\extractors\bilibili.py", line 99, in bilibili_download_by_cid
    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, me
rge=merge)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\you_get\common.py", line 679, in download_urls
    assert urls
AssertionError

**Comment by zhangn1985** [comment]
appkey 仍然有效

**Comment by 4321qasdfv** [comment]
升级到开发版可以下载了，但是仍然不能定位到分p。

**Comment by zhiyue** [comment]
不能正常下载

**Comment by cnbeining** [comment]
请升级到最新版。

如不能使用 请务必提供URL。

**Comment by soimort** [comment]
#1176 is fixed. And the video provided in this issue is gone.

**Comment by omaidb** [comment]
http://www.bilibili.com/video/av2635346/index_1.html

bilibili下载不了啊

**Comment by Cphilo** [comment]
bilibili下载不了啊

+1

**Comment by nuomi1** [comment]
@omaidb @Cphilo 0.4.715 正常。
