### ISSUE TITLE
Can only download the first item on youtube playlist

### ISSUE THREAD

**Issue by kungfucop** [soimort/you-get#1188]
```
you-get --debug --itag=18 https://www.youtube.com/watch?v=plDO8meaxiw&list=PLotg-oruJ2Zn-jREu4tmwTSE08Zq80BhK
[1] 17592
my-MacBook-Pro $ [DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=plDO8meaxiw
[DEBUG] get_content: https://www.youtube.com/watch?v=plDO8meaxiw
[DEBUG] get_content: https://s.ytimg.com/yts/jsbin/player-en_US-vflAwQJsE/base.js
site:                YouTube
title:               Kevin  "The Monster"  Randleman Highlights
stream:
    - itag:          18
      container:     mp4
      quality:       medium
      size:          9.9 MiB (10348335 bytes)
    # download-with: you-get --itag=18 [URL]

Downloading Kevin  "The Monster"  Randleman Highlights.mp4 ...
 100% (  9.9/  9.9MB) ├█████████████████████████████████████████████████████████████████████████████████████████████████████┤[1/1]    1 MB/s

Now it just freeze here without downloading the next ones.
```

**Comment by h4ppily** [comment]
Doesn't show it in the options list but it seems like adding "-l" to your args will do the trick(line 1080 in common.py). The command below is downloading the entire playlist in mp4.

you-get -l --itag=18 https://www.youtube.com/watch?v=plDO8meaxiw&list=PLotg-oruJ2Zn-jREu4tmwTSE08Zq80BhK

**Comment by kungfucop** [comment]
@h4ppily  thanks for the reply but I got '[Failed] Unsupported URL pattern' when trying 
you-get -l --itag=18 https://www.youtube.com/watch?v=plDO8meaxiw&list=PLotg-oruJ2Zn-jREu4tmwTSE08Zq80BhK

**Comment by h4ppily** [comment]
Try putting quotation marks around the URL. "https://www.youtube.com/watch?v=plDO8meaxiw&list=PLotg-oruJ2Zn-jREu4tmwTSE08Zq80BhK"

**Comment by kungfucop** [comment]
@h4ppily Thanks very much, it worked!

**Comment by soimort** [comment]
You may also use the playlist URL, not the video specific URL:

https://www.youtube.com/playlist?list=PLotg-oruJ2Zn-jREu4tmwTSE08Zq80BhK
