### ISSUE TITLE
can not download any video from youku website

### ISSUE THREAD

**Issue by mabier** [soimort/you-get#1191]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ y] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [y ] Your `you-get` is up-to-date.
- [ y] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ y] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ y] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[you-get: [Error] HTTP Error 403: Forbidden
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/5465047561750128fb0fb_00/st/mp4/fileid/030008170051F79854650D0501E0C473B6D55F-49A6-91D9-BF21-D8BD29FB40FB?ep=dyaSH0mJUcsG5CTaiD8bb3qwdCFdXP4J9h%2BFidNlALshSZ64kDbUw5u1TotCE%2FkYByJ1FOzy2daTb0ViYfRK2G4Q1k%2FcMPqSiPLi5dlbtuQCb29Eds2hxlSaRDX1&ctype=12&ev=1&yxon=1&K=d602805f1a027a2b282b77bf&token=4754&oip=1001189419
]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [it worked well before, but since about 4 or 5 days earlier, it keeps being not able to download anything,the response is : you-get:[error] HTTP Error 403: Forbidden]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by nuomi1** [comment]
Please show the url.
```
➜  ~ yg -i http://v.youku.com/v_show/id_XMTU1MDcxNDIyOA\=\=.html
site:                优酷 (Youku)
title:               01 镇魂街
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          466.8 MiB (489469603 bytes)
    # download-with: you-get --format=hd3 [URL]

    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          244.3 MiB (256171658 bytes)
    # download-with: you-get --format=hd2 [URL]

    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          130.0 MiB (136293258 bytes)
    # download-with: you-get --format=mp4 [URL]

    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          63.7 MiB (66809262 bytes)
    # download-with: you-get --format=flvhd [URL]
```

**Comment by mabier** [comment]
thank you for prompt reply !
my networks connection has no problem.
Actually I can not download anything, for example, this url : http://v.youku.com/v_show/id_XMTU5NTU5ODQ2MA==.html , I can not download corresponding video from youku !

**Comment by cnbeining** [comment]
I am receiving multiple reports regarding Youku. It seems that the problem
is on their side, not yours( or ours!).

2016年6月4日星期六，mabier <notifications@github.com> 写道：

**Comment by nuomi1** [comment]
...
```
➜  ~ yg http://v.youku.com/v_show/id_XMTU5NTU5ODQ2MA\=\=.html
site:                优酷 (Youku)
title:               非凡搭档 160603
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          1048.1 MiB (1099011523 bytes)
    # download-with: you-get --format=hd2 [URL]

Downloading 非凡搭档 160603.flv ...
 0.8% (   8.5/1048.1MB) ├─────────────────────────────────────┤[ 1/28]   33 MB/s^C%
```

**Comment by mabier** [comment]
`-> ~ you-get http://v.youku.com/v_show/id_XMTU5NTU5ODQ2MA\=\=.html

Traceback (most recent call last):
  File "/usr/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.3.36', 'console_scripts', 'you-get')()
  File "/usr/lib/python3.5/site-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1152, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 966, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 851, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 1145, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/extractor.py", line 36, in download_by_url
    self.prepare(**kwargs)
  File "/usr/lib/python3.5/site-packages/you_get/extractors/youku.py", line 105, in prepare
    meta = json.loads(get_html('http://v.youku.com/player/getPlayList/VideoIDS/%s/Pf/4/ctype/12/ev/1' % self.vid))
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 168, in get_html
    content = get_response(url, faker).data
  File "/usr/lib/python3.5/site-packages/you_get/common.py", line 156, in get_response
    response = request.urlopen(url)
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1268, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1243, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
`
I also tried youtube-dl since it has similar function as that of you-get:
`youtube-dl http://v.youku.com/v_show/id_XMTU5NTU5ODQ2MA\=\=.html
[youku] XMTU5NTU5ODQ2MA: Downloading JSON metadata
[download] Downloading playlist: 非凡搭档 160603
[youku] playlist 非凡搭档 160603: Collected 16 video ids (downloading 16 of them)
[download] Downloading video 1 of 16
ERROR: unable to download video data: HTTP Error 403: Forbidden
`

**Comment by zhangn1985** [comment]
``load_entry_point('you-get==0.3.36', 'console_scripts', 'you-get')()``

**Comment by mabier** [comment]
@zhangn1985 , I checked the version, I found I installed python-you-get (version:0.3.36-1), then I uninstalled it and installed the latest version of you-get(0.4.424), then below is the report ,
`you-get --debug http://v.youku.com/v_show/id_XMTU5NTU5ODQ2MA\=\=.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTU5NTU5ODQ2MA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTU5NTU5ODQ2MA==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/046510239581912c9d3aa_00/st/flv/fileid/0300011C005751C3669CC7080D48DD04B92788-4086-C562-AE85-22DC32BFD146?ctype=12&ev=1&token=2987&oip=1001189419&yxon=1&K=0476ccefdd1241d9282b782a&ep=ciaSH0iNVM0J4CvegT8bNCW2dyZeXP4J9h%2BFgNMRALshT%2B2%2B6j3XwZTDPfhCHvltdipyZOv12dnlbUgcYfRDoW4QrEuuO%2FqRi%2Fjm5a9RsOMDZGtABszTslScSjj2
you-get: [Error] HTTP Error 403: Forbidden
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/046510239581912c9d3aa_00/st/flv/fileid/0300011C005751C3669CC7080D48DD04B92788-4086-C562-AE85-22DC32BFD146?ctype=12&ev=1&token=2987&oip=1001189419&yxon=1&K=0476ccefdd1241d9282b782a&ep=ciaSH0iNVM0J4CvegT8bNCW2dyZeXP4J9h%2BFgNMRALshT%2B2%2B6j3XwZTDPfhCHvltdipyZOv12dnlbUgcYfRDoW4QrEuuO%2FqRi%2Fjm5a9RsOMDZGtABszTslScSjj2
`

**Comment by mabier** [comment]
Today I tried this  command "http://v.youku.com/v_show/id_XMTU5NTU5ODQ2MA\=\=.html" in another city (Shanghai,  I am on a business trip now, in a hotel in Shanghai), it works. 
`you-get -i http://v.youku.com/v_show/id_XMTU5NTU5ODQ2MA\=\=.html
site:                优酷 (Youku)
title:               非凡搭档 160603
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          1048.1 MiB (1099011523 bytes)
    # download-with: you-get --format=hd2 [URL]

    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          554.7 MiB (581612206 bytes)
    # download-with: you-get --format=mp4 [URL]

    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          268.3 MiB (281297269 bytes)
    # download-with: you-get --format=flvhd [URL]`

I did this by using my cellphone 4G's usb tethering function to share cellphone's 4G signal with laptop computer. So I confirm you-get works well with youku website when do you-get command in laptop computer by sharing cellphone's 4G usb tethering option in Shanghai . When I return to Wuhan tomorrow, I will try if it would work with the same setup .

**Comment by mabier** [comment]
Now I am back to Wuhan home, I tried the same configuration which I setup in Shanghai(during my business trip) in my desktop computer, i.e. using my cellphone's China Mobile 4G USB tethering option to share the 4G data with my desktop computer, it also worked without any problem. 
I wondered why you-get works well with China Mobile's 4G signal whereas it can not work well with China Telecom's broadband service(in my case, I subscribe to China Telecom's 20 Mb optical cable broadband service ). Finally I found out the root cause , the reason why it did not work is because my desktop computer is connected directly to a rounter which is in turn connected to the optical modem, so in a nutshell , the desktop computer is behind a rounter !
Now I unplug the ethernet cable from router and then plug it into the optical modem directly, everthing return to its normal status, you-get works again !! 
You-get  is such a fantanstic tool ! Thanks !

**Comment by chenguandan** [comment]
When I try to download videos below, I got 403 forbidden. I notice Issue 845, but I am not sure. 

How  can I fix this?

I have already tried: (1) update you-get; (2) open the URLs in the mobile, then use URLs in my mobile to download them. Any one do me a favor?

Below is the debug info.

http://v.youku.com/v_show/id_XNDIyNjg0OTE2.html?f=4649175
http://v.youku.com/v_show/id_XNjYyMTY1MTY4.html?spm=a2h1n.8251843.playList.5!5~1!2~3~A.nqrVEv&f=21709932&o=1
http://v.youku.com/v_show/id_XNjYyMTU4MDQ0.html?spm=a2h1n.8251843.playList.5!2~1!2~3~A.nqrVEv&f=21709932&o=1

you-get: ['http://v.youku.com/v_show/id_XNDIyNjg0OTE2.html?f=4649175']
Traceback (most recent call last):
  File "C:\Python34\Scripts\you-get-script.py", line 9, in <module>
    load_entry_point('you-get==0.4.626', 'console_scripts', 'you-get')()
  File "C:\Python34\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1410, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1323, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, i    nfo_only=info_only, json_output=json_output, caption=caption)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1139, in download_main
    download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1403, in any_download
    m.download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractor.py", line 52, in download_by_url
    self.download(**kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractor.py", line 208, in download
    av=stream_id in self.dash_streams)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 793, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 473, in url_save
    file_size = url_size(url, faker = faker, headers = headers)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 391, in url_size
    response = request.urlopen(url)
  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 501, in error
    result = self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 684, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python34\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 507, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by mabier** [comment]
I am using linux ,so I have no problem here to properly download this video.
you-get http://v.youku.com/v_show/id_XNDIyNjg0OTE2.html?f=4649175
site:                优酷 (Youku)
title:               8分钟腹肌锻炼第3级
stream:
    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          22.7 MiB (23765588 bytes)
    # download-with: you-get --format=flvhd [URL]

Downloading 8分钟腹肌锻炼第3级.flv ...
 100% ( 22.7/ 22.7MB) ├███████████████████████████████████████████████████████████████████████████████████████████████████┤[2/2]    5 MB/s
Merging video parts... Merged into 8分钟腹肌锻炼第3级.mp4

I don't use you-get in windows, so if you are using you-get in windows , I am sorry that I can not help you !
