### ISSUE TITLE
微博视频下载路径设置无法生效

### ISSUE THREAD

**Issue by zhuqihan** [soimort/you-get#1194]
下载微博视频设置相应的下载路径，但是下载下来的文件还是下载到了在当前目录下。
![qq 20160607125311](https://cloud.githubusercontent.com/assets/5293028/15846360/e8b21e1a-2cae-11e6-8ce2-18a5871cb9c7.png)
![qq 20160607125254](https://cloud.githubusercontent.com/assets/5293028/15846365/ec3e87e4-2cae-11e6-8ea8-e97a1c8694a5.png)

**Comment by zhangn1985** [comment]
```
def miaopai_download(url, output_dir = '.', merge = False, info_only = False, **kwargs):
    """"""
    if re.match(r'http://video.weibo.com/show\?fid=(\d{4}:\w{32})\w*', url):
        miaopai_download_by_url(url, output_dir, merge, info_only)
    elif re.match(r'http://weibo.com/p/230444\w+', url):
        _fid = match1(url, r'http://weibo.com/p/230444(\w+)')
        miaopai_download_by_url('http://video.weibo.com/show?fid=1034:{_fid}'.format(_fid = _fid))  #<-- mistake here!!
```

**Comment by soimort** [comment]
Should be an easy fix.

**Comment by zhuqihan** [comment]
thanks so much！

**Comment by cnbeining** [comment]
我的锅 我的锅...

2016年6月23日星期四，zhuqihan <notifications@github.com> 写道：

**Comment by zhangn1985** [comment]
@cnbeining No, it's not your fault.

**Comment by soimort** [comment]
This issue is yet to be fixed.

**Comment by huangpingchun** [comment]
微博视频这种 http://weibo.com/tv/v/   url的不能播放

**Comment by cnbeining** [comment]
请提供详细日志。

**Comment by huangpingchun** [comment]
sorry，我用词错误， 应该是不支持 “./you-get  "http://weibo.com/tv/v/Eodqj5Vmk?fid=1034:7760c9b11e3b5c618b6440ae32728c9e" 不支持。

**Comment by whohow123** [comment]
不能下载微博的视频 
you-get --json "http://weibo.com/3167305545/EzCklcsgp"  无任何输出
