### ISSUE TITLE
想把you-get转正Python2

### ISSUE THREAD

**Issue by ichenfujun** [soimort/you-get#1197]
hi  大牛：
     打算把you-get代码转成Python2.7，不知道您有什么好的建议
谢谢！

**Comment by zhangn1985** [comment]
@ichenfujun try this: https://github.com/zhangn1985/ykdl

**Comment by zhangn1985** [comment]
支持python2很麻烦，很辛苦。量力而为。

**Comment by zhangn1985** [comment]
https://www.python.org/dev/peps/pep-0263/
另外请搜索 python2 unicode

**Comment by minghu6** [comment]
同意 @zhangn1985 ,.

所谓量力而行， 力不仅指能力， 更指的是体力、耐力233。

首先， 是完全可以做到同时兼容python2、3，但这样做的代价是代码团成一个球， 看起来像嵌入html的php,。因此需要单独维护一个python2的版本。

其次，具体的讲，恐怕大部分程序从python3 迁移到python2,，最麻烦的就是编码问题。
       
    1. python3 中返回str类型的__call__，python2里返回的也是str，这意味着不是你自己使用unicode就碰不到str了
    2. python2 里， ascii-plaintext is str, bytes is also str
       因吹思婷是吧，你需要很清楚每一个 __call__返回的到底是  ascii-plaintext还是 bytes，
       以便进行encode/decode
      （又因为默认是ascill，而不是latin-1，所以多字节字符必须先编码成二进制） 

  因为前些日子（在看到you-get之前。。。），刚把一个python2的从音乐Tai搂视频的工具转成

python3，嗯，有几个东西也许你也用得上

https://gist.github.com/minghu6/74197ac107b7833c4b4a7284eeac6cfb


最后两点，

    1. 探讨转成python2的意义：以我的了解， 
       能用python2的地方都能用python3,；
       而python3，无论性能还是易用性都强过python2，也不存在什么还在维护的库python2有，
       而python3没有 。更不要提转成python2还要增加大量的额外的维护。

    2. 其实没必要来这问， 对于他们所谓的团队来讲，除了 ‘making a feature request or bug report,’
      （而且对于，`feature`，他有一套自己的逻辑来判定，
       你的request可能是`feature`也可能it is a waste of time），至于其他，Who care?
       就算你做出来了又能怎样。。。，自己fork，自己玩就好了
 
ps；写了这么多中文， 不知道会不会被举报，好担心啊

**Comment by cnbeining** [comment]
First thing first, it is not in the foreseeable future route map that Python 2 support been added officially.

Second, I highly doubt why you need the whole code base being translated. The logic in every single extractor is very clear: Just grab what you want.

P.S: One thing I must point out is we do not need any harassment speech anywhere in this project. Should anyone cannot keep a good (or at least reasonable) manner, any public speech would be the utmost improper. Leave your hate at home and talk about the code.

**Comment by zhangn1985** [comment]
@minghu6 完全赞成。我大概花了二周的时间完成我自己一个项目的py3->py2的兼容，那段时间真的很苦逼。 真的有时候看到那些个返回值类型，py2和py3各不相同，想死都有。

特别是就算你print能正常把一个string打印出来，但是你把这个string放到`__str__`函数里面返回就`UnicodeDecodeError`

**Comment by ichenfujun** [comment]
英文不好就不用英文回答了！首先感谢这么多热心朋友的解答，第一次在github上提问题，就收到这么中肯的建议，甚是惊恐和激动。我花了3天的时间尝试把代码转成Python3，由于程序中用到了很多第三方类库，升级过程中各种报错才让我有了把you-get转成Python2的想法，不过看到大伙的解答，我果断放弃了。

**Comment by cnbeining** [comment]
别的程序转成Python3？哪个？

**Comment by zhangn1985** [comment]
@ichenfujun 如果你真想做这件事，可以参考我的项目，有惊喜。
