### ISSUE TITLE
couldn't download video from lesports.com

### ISSUE THREAD

**Issue by Token713** [soimort/you-get#1200]
couldn't download video from lesports.com,such as http://sports.le.com/video/25737697.html

> you-get: version 0.4.424, a tiny downloader that scrapes the web.
> 
> you-get http://sports.le.com/video/25737697.html
> you-get: [error] oops, something went wrong.
> you-get: don't panic, c'est la vie. please try the following steps:
> you-get:   (1) Rule out any network problem.
> you-get:   (2) Make sure you-get is up-to-date.
> you-get:   (3) Check if the issue is already known, on
> you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
> you-get:         https://github.com/soimort/you-get/issues
> you-get:   (4) Run the command with '--debug' option,
> you-get:       and report this issue with the full output.

**Comment by Token713** [comment]
> >you-get --debug http://sports.le.com/video/25737697.html
[DEBUG] get_content: http://sports.le.com/video/25737697.html
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=None&platid=1
&splatid=101&format=1&tkey=198945940&domain=www.letv.com
you-get: version 0.4.424, a tiny downloader that scrapes the web.
you-get: ['http://sports.le.com/video/25737697.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1277, in main
  File "src\you_get\common.py", line 1190, in script_main
  File "src\you_get\common.py", line 1033, in download_main
  File "src\you_get\common.py", line 1270, in any_download
  File "src\you_get\extractors\le.py", line 137, in letv_download
  File "src\you_get\extractors\le.py", line 90, in letv_download_by_vid
  File "src\you_get\extractors\le.py", line 61, in video_info
KeyError: 'playurl'
you-get returned -1

>

**Comment by jacwl** [comment]
the latest git is still not working with some vids from le.com

examples:
[http://sports.le.com/video/25418114.html](http://sports.le.com/video/25418114.html)
[http://sports.le.com/video/25741493.html](http://sports.le.com/video/25741493.html)
[http://www.le.com/ptv/vplay/25606975.html](http://www.le.com/ptv/vplay/25606975.html)
[http://www.le.com/ptv/vplay/25726861.html](http://www.le.com/ptv/vplay/25726861.html)

@yan12125 suggested adding --hls-prefer-native(youtube-dl) as a workaround, but I don't know if you-get has any option like this

**Comment by zhangn1985** [comment]
http://sports.le.com/live/1020160607143215.html#record/25741461
和
http://sports.le.com/video/25741493.html
的算法完全不一样。不好做。

**Comment by zhangn1985** [comment]
http://sports.le.com/live/1020160607143215.html#record/25741461
和原乐视视频的算法一样。具体实现可以参照我的fork。
