### ISSUE TITLE
优酷会员视频解析问题

### ISSUE THREAD

**Issue by zhanght021** [soimort/you-get#1202]
可以解析到优酷会员视频，可是下载时候只会下载刚开始优酷上试看的几分钟，别的都下不下来

**Comment by zhanght021** [comment]
@soimort-bot   
例如下面这个链接，解析到
> http://v.youku.com/v_show/id_XMTU5Nzg1MzM2MA==.html 解析到了高清格式的视频是1247M
可是我用这个命令you-get --format=mp4 http://v.youku.com/v_show/id_XMTU5Nzg1MzM2MA==.html下载的时候，下载到4.1%就停止下载了
> 

![1](https://cloud.githubusercontent.com/assets/19857363/15990243/2b88fffa-30c0-11e6-9299-4294404920b7.PNG)

![default](https://cloud.githubusercontent.com/assets/19857363/15990189/b48ff77e-30be-11e6-94dc-25ae1c896fb1.PNG)

还有就是在解析乐视会员视频的时候只会解析到一种格式，并且只有可以试看的那一部分，

**Comment by nuomi1** [comment]
没有传入 cookie。

**Comment by zhanght021** [comment]
@nuomi1 那这个要怎么操作，我是小白不是很懂，求指导一下子

**Comment by nuomi1** [comment]
@zhanght021 我也不是很懂，因为没用过←_←

**Comment by zhanght021** [comment]
@nuomi1 那你有没有用过什么可以下载会员视频的方法，我有会员的账号，就想把视频下下来

**Comment by NoahChang94** [comment]
https://github.com/soimort/you-get#load-cookies

**Comment by zhanght021** [comment]
@NoahChang94  你好，是不是用这样的指令，
you-get -c cookies.sqlite http://v.youku.com/v_show/id_XMTU5Nzg1MzM2MA==.html
但我这样子依旧是上面的情况，优酷上的会员视频还是这种情况

**Comment by NoahChang94** [comment]
你需要找到cookies.sqlite的位置， 像Ubuntu下firefox的cookie路径是~/.mozilla/firefox/*default/cookies.sqlite， 所以是you-get -c ~/.mozilla/firefox/*default/cookies.sqlite VIDEO_URL

**Comment by NoahChang94** [comment]
你需要找到cookies.sqlite的位置， 像Ubuntu下firefox的cookie路径是~/.mozilla/firefox/\*default/cookies.sqlite， 所以是you-get -c ~/.mozilla/firefox/\*default/cookies.sqlite VIDEO_URL

**Comment by zhanght021** [comment]
@NoahChang94 谢谢你啦，好像可以了，乐视的会员视频也是这样子解析是吗？

**Comment by yangfan3333** [comment]
@NoahChang94  请问QQ收费视频 怎么选择清晰度？默认是 270P 很模糊  而且不能选择蓝光下载

**Comment by nuomi1** [comment]
@yangfan3333 即使不是收费视频，一样只能解析最低清晰度……
v.qq.com 的视频可以改 UA 到 OS X 直接使用 HTML5 播放。

**Comment by yangfan3333** [comment]
@nuomi1  第一句 我懂了，后面一句我不太懂，我是新手。我用的是WIN版本。

您说的     UA 到 OS X 直接使用 HTML5 播放  这一句话是什么意思？

**Comment by nuomi1** [comment]
User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36`

**Comment by yangfan3333** [comment]
@nuomi1  谢谢您，现在默认是蓝光了，但是我用you-get下载 还是 270 这个怎么解决呢？ 谢谢您啦。

**Comment by yangfan3333** [comment]
@nuomi1  意思就是让WIN版的 youget 调用 火狐浏览器的UA 让他自动变成蓝光，因为我火狐默认变成蓝光了。YOUGET 还是。270

**Comment by nuomi1** [comment]
@yangfan3333 无法解决，除非有人重写解析规则。

**Comment by yangfan3333** [comment]
@nuomi1  好的，太感谢您了，我知道了。好人啊。。还是国外论坛好，国内论坛都没理你的。都是一些水贴

**Comment by AbsoluteRay** [comment]
@NCACN 学到了 给力

**Comment by cnbeining** [comment]
谁帮我eli5下...我们好改code啊。

2017年1月2日 上午2:13，"AbsoluteRay" <notifications@github.com>写道：

**Comment by cwbsw** [comment]
貌似从昨天开始，优酷会员视频解析就一直失败，已加载cookies。
```
D:\>you-get -d -c Downloads\cookies.txt http://v.youku.com/v_show/id_XMjUzNDA5MTc2NA==.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjUzNDA5MTc2NA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjUzNDA5MTc2NA==&ct=12
site:                优酷 (Youku)
title:               【怀旧党】更新内容意向第三次投票视频
stream:
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          29.0 MiB (30435963 bytes)
    # download-with: you-get --format=mp4 [URL]

you-get: [Failed] Cannot extract video source.
```

**Comment by czmecho** [comment]
对，现在即使传入cookies也不能下载完整的vip视频。
cookies是由这个生成的文件：https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg

**Comment by rosynirvana** [comment]
outdated
