### ISSUE TITLE
you-get docs to use it as library 

### ISSUE THREAD

**Issue by gozes** [soimort/you-get#1206]
I love you-get, I use it all the time, but I will like to use it from some of my scripts/tool but I don't see any API docs and using a processes is not what I am looking for. 

Any I should start looking in the src or is there any plans to make an api to use you-get as a library?

**Comment by cnbeining** [comment]
Thanks for your request.

As for now, we haven't fully decided how we will implement every extractor,
so my best bet is you call --json for now. Also, if you have any idea in
your head, any PR shall be the most helpful.

Cheers,

2016年6月14日星期二，Mort the Bot <notifications@github.com> 写道：

**Comment by cnbeining** [comment]
Dumplicate of #851 .
