### ISSUE TITLE
有些网址为什么会下不下来呢？https://www.youtube.com/watch?v=Uw_1iNGntZU

### ISSUE THREAD

**Issue by rainbow0727** [soimort/you-get#1207]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by zhangn1985** [comment]
@soimort-bot  please test: https://www.youtube.com/watch?v=Uw_1iNGntZU

**Comment by rainbow0727** [comment]
我的还是不行，是因为网址的原因么？

**Comment by rainbow0727** [comment]
@soimort-bot

**Comment by cnbeining** [comment]
是因为代理吧...？

2016年6月14日星期二，rainbow0727 <notifications@github.com> 写道：

**Comment by rainbow0727** [comment]
那我该怎么做呢？求帮忙

**Comment by rainbow0727** [comment]
@cnbeining

**Comment by rainbow0727** [comment]
Do  you solve it? @soimort-bot

**Comment by rainbow0727** [comment]
有些youtube的网址是可以正常打开并且下载的，但是有些网址就不能正常播放，出现错误，也不能下载。

**Comment by nuomi1** [comment]
Please post another url which can't download.

```
➜  ~ pyg https://www.youtube.com/watch\?v\=Uw_1iNGntZU
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.11/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.11
[proxychains] DLL init: proxychains-ng 4.11
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  www.youtube.com:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  www.youtube.com:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  s.ytimg.com:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  r15---sn-a5m7lnel.googlevideo.com:443  ...  OK
site:                YouTube
title:               Water Polo - Kristina Alogbo (English subtitling)
stream:
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          24.4 MiB (25535772 bytes)
    # download-with: you-get --itag=22 [URL]

Downloading Water Polo - Kristina Alogbo (English subtitling).mp4 ...
 0.0% (  0.0/ 24.4MB) ├─────────────────────────────────────────┤[1/1]
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  r15---sn-a5m7lnel.googlevideo.com:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  r15---sn-a5m7lnel.googlevideo.com:443  ...  OK
 100% ( 24.4/ 24.4MB) ├█████████████████████████████████████████┤[1/1]  807 kB/s
```

**Comment by rainbow0727** [comment]
我用了xx-net的代理，能正常播放这个视频，但是用you-get还是无法下载https://www.youtube.com/watch?v=0Gr4aKQzGYk，在这以前，我没有代理，视频也播放不了，但是现在还是下载不了 @soimort-bot@nuomi1

**Comment by rainbow0727** [comment]
感觉地址都解析出来了，单独处理这一句的时候就不会出错，是因为批量处理，代理造成的吗？
