### ISSUE TITLE
letv 無法下載

### ISSUE THREAD

**Issue by goodneo** [soimort/you-get#1209]
Please make sure these boxes are checked before submitting your issue – thank you!
- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read https://github.com/soimort/you-get/wiki/FAQ and tried to do so.
- [x] The issue is not yet reported on https://github.com/soimort/you-get/issues or  https://github.com/soimort/you-get/wiki/Known-Bugs. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 https://github.com/soimort/you-get/wiki/FAQ 中的指引进行了操作.
- [x] 您的问题没有在https://github.com/soimort/you-get/issues , https://github.com/soimort/you-get/wiki/FAQ 或 https://github.com/soimort/you-get/wiki/Known-Bugs 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

想請問letv的解析是不是失效了 都跳這個畫面
![le](https://cloud.githubusercontent.com/assets/12432658/16106234/64bc1246-33c5-11e6-98df-51ffb68fcb18.jpg)

**Comment by nuomi1** [comment]
能把 URL 贴出来么……

**Comment by goodneo** [comment]
http://www.le.com/ptv/vplay/23113817.html#vid=23113817

**Comment by nuomi1** [comment]
```
➜  ~ yg http://www.le.com/ptv/vplay/23113817.html
Current Video Supports:
	--format 1080p <URL>
	--format 1300 <URL>
	--format 350 <URL>
	--format 720p <URL>
	--format 1000 <URL>
Site:       Le.com
Title:      来自未来的史密特01集
Type:       MPEG-4 video (video/mp4)
Size:       484.49 MiB (508020932 Bytes)

Downloading 来自未来的史密特01集.mp4 ...
 1.4% (  6.6/484.5MB) ├█──────────────────────────────────────┤[ 4/80]    9 MB/s
```

**Comment by goodneo** [comment]
不太懂是哪邊出了問題 更了Python最新版也一樣  也把you-get重弄 依然沒作用  windows 7平台

**Comment by nuomi1** [comment]
使用 `you-get -di http://www.le.com/ptv/vplay/23113817.html` 测试，然后把结果贴出来。

**Comment by cnbeining** [comment]
```
$ python3 you-get -di http://www.le.com/ptv/vplay/23113817.html 
[DEBUG] get_content: http://www.le.com/ptv/vplay/23113817.html
[DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=23113817&platid=1&splatid=101&format=1&tkey=3912138900&domain=www.letv.com
Current Video Supports:
	--format 720p <URL>
	--format 1080p <URL>
	--format 350 <URL>
	--format 1300 <URL>
	--format 1000 <URL>
[DEBUG] get_content: http://play.g3proxy.lecloud.com/vod/v2/MTU1LzIyLzUvbGV0di11dHMvMTQvdmVyXzAwXzIyLTMyMzAwNjM0Mi1hdmMtMjk5MjMxOS1hYWMtMTI4MDAxLTEyNjA3MjYtNDkzODA2NDE1LWRhZjEyMTFhODdjZjk5ZjJjNzU3OTQyODQ1ZWU5Mjc2LTE0MzY5NzcxMTYzNTAubXA0?b=3133&mmsid=33132933&tm=1466138391&key=3314e95e02aa4a0f1b62eba7a16c01b9&platid=1&splatid=101&playid=0&tss=ios&vtype=52&cvid=1372462645400&payff=0&pip=7d8b6690269bb3ad22769795f9601019&ctv=pc&m3v=1&termid=1&format=1&hwtype=un&ostype=Linux&tag=letv&sign=letv&expect=3&tn=0.03551543489963116&pay=0&iscpn=f9051&rateid=1080p
[DEBUG] get_content: http://107.155.40.18/155/22/5/letv-uts/14/ver_00_22-323006342-avc-2992319-aac-128001-1260726-493806415-daf1211a87cf99f2c757942845ee9276-1436977116350.m3u8?crypt=8aa7f2e1691&b=3133&nlh=4096&nlt=60&bf=43&p2p=1&video_type=mp4&termid=1&tss=ios&platid=1&splatid=101&its=0&qos=3&fcheck=0&mltag=100&proxy=1107239064,1805330707,467484303&uid=1176177320.rp&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&ntm=1466149200&nkey=d4cd462e8e7af9e425b7b29c53647a58&nkey2=7e1d73f1284155acd1b1f48b705cd5d0&geo=CA-0-0-100&mmsid=33132933&tm=1466138391&key=3314e95e02aa4a0f1b62eba7a16c01b9&playid=0&vtype=52&cvid=1372462645400&payff=0&ctv=pc&m3v=1&hwtype=un&ostype=Linux&tag=letv&sign=letv&tn=0.03551543489963116&pay=0&iscpn=f9051&rateid=1080p&errc=0&gn=906&vrtmcd=104&buss=100&cips=70.27.10.168
Site:       Le.com
Title:      来自未来的史密特01集
Type:       MPEG-4 video (video/mp4)
Size:       484.49 MiB (508020932 Bytes)

```


![image](https://cloud.githubusercontent.com/assets/1560962/16140943/2cd5b2d8-3424-11e6-90ba-93ee5323e404.png)

**Comment by goodneo** [comment]
![le1](https://cloud.githubusercontent.com/assets/12432658/16143812/c3c91388-34a1-11e6-8f51-315364342e33.jpg)

**Comment by cnbeining** [comment]
能不能再运行一次打印log，然后把

http://api.letv.com/mms/out/video/playJson?id=23113817&platid=1&splatid=101&format=1&tkey=换成你这次生成的tkey&domain=www.letv.com

的内容丢在这样呀？

**Comment by goodneo** [comment]
{"danmu":"0","firstlook":"0","isAlbumPay":0,"isTryLook":"0","paylist":["1080p"],"playstatus":{"status":"1"},"playurl":{"videoType":180001,"cid":"2","pid":"10010551","vid":"23113817","title":"\u6765\u81ea\u672a\u6765\u7684\u53f2\u5bc6\u7279\u0030\u0031\u96c6","mid":",33132933,","duration":"1260","pic":"http://i2.letvimg.com/lc03_isvrs/201507/21/10/44/b1efde35-67d7-4e47-901d-2d12a6f3c4af.jpg","filter":1,"download":["290005","290003","290001","290002"],"total":"0","nextvid":"23135081","domain":["http://play.g3proxy.lecloud.com","http://bplay.g3proxy.lecloud.com","http://117.121.54.219"],"dispatch":{"1000":["/vod/v2/MTcyLzI2LzcwL2xldHYtdXRzLzE0L3Zlcl8wMF8yMi0zMjMwMDYzMzYtYXZjLTQ3OTE1MS1hYWMtMzIwMDEtMTI2MDcyNi04MjE0NDA5Ny1kN2Y5NTg1ZjliZTc5ZjQ0MjgyMDUwNDk4ZmI5NTA5Mi0xNDM2OTcyNTEzNjg3Lm1wNA==?b=521&mmsid=33132933&tm=1466226008&key=46da3a383c9b3fdb59589775480ce7aa&platid=1&splatid=101&playid=0&tss=ios&vtype=13&cvid=1642070221563&payff=0&pip=33a4f416ce313184a41590c7e64e9f56","172/26/70/letv-uts/14/ver_00_22-323006336-avc-479151-aac-32001-1260726-82144097-d7f9585f9be79f44282050498fb95092-1436972513687.mp4"],"1080p":["/vod/v2/MTU1LzIyLzUvbGV0di11dHMvMTQvdmVyXzAwXzIyLTMyMzAwNjM0Mi1hdmMtMjk5MjMxOS1hYWMtMTI4MDAxLTEyNjA3MjYtNDkzODA2NDE1LWRhZjEyMTFhODdjZjk5ZjJjNzU3OTQyODQ1ZWU5Mjc2LTE0MzY5NzcxMTYzNTAubXA0?b=3133&mmsid=33132933&tm=1466226008&key=cf833dca83e078a085b40516585bdb11&platid=1&splatid=101&playid=0&tss=ios&vtype=52&cvid=1642070221563&payff=0&pip=33a4f416ce313184a41590c7e64e9f56","155/22/5/letv-uts/14/ver_00_22-323006342-avc-2992319-aac-128001-1260726-493806415-daf1211a87cf99f2c757942845ee9276-1436977116350.mp4"],"1300":["/vod/v2/MTc1LzMvOTcvbGV0di11dHMvMTQvdmVyXzAwXzIyLTMyMzAwNjMzNy1hdmMtODc1NDk3LWFhYy02NDAwMS0xMjYwNzI2LTE0OTY1MDgwNS1hZWE3YjViZjMzODUwNjk2OTIyMDQwYzBiMGM3ODQ3OC0xNDM2OTczMzEyMjAxLm1wNA==?b=949&mmsid=33132933&tm=1466226008&key=061263e32d81d9b67beed203ee9a12ca&platid=1&splatid=101&playid=0&tss=ios&vtype=22&cvid=1642070221563&payff=0&pip=33a4f416ce313184a41590c7e64e9f56","175/3/97/letv-uts/14/ver_00_22-323006337-avc-875497-aac-64001-1260726-149650805-aea7b5bf33850696922040c0b0c78478-1436973312201.mp4"],"350":["/vod/v2/MTUzLzQ5LzI0L2xldHYtdXRzLzE0L3Zlcl8wMF8yMi0zMjMwMDYzMzUtYXZjLTIzMDA3NC1hYWMtMzIwMDEtMTI2MDcyNi00Mjg5MDEzMi0wODViYzUyZDQ2MjQ3NmY5MzdmZmQyYmQyMjllY2NkMy0xNDM2OTcyMjEyNjc4Lm1wNA==?b=272&mmsid=33132933&tm=1466226008&key=5eb53d4ed11d8019a0353791330f74e8&platid=1&splatid=101&playid=0&tss=ios&vtype=21&cvid=1642070221563&payff=0&pip=33a4f416ce313184a41590c7e64e9f56","153/49/24/letv-uts/14/ver_00_22-323006335-avc-230074-aac-32001-1260726-42890132-085bc52d462476f937ffd2bd229eccd3-1436972212678.mp4"],"720p":["/vod/v2/MTc4LzQvNzIvbGV0di11dHMvMTQvdmVyXzAwXzIyLTMyMzAwNjM0MS1hdmMtMTc5NDgxNS1hYWMtOTYwMDAtMTI2MDcyNi0zMDAwMzkzMTQtMDUwMzk1M2JjYzUwYTc0NGIyODIwZTkyMmM3N2EwZmQtMTQzNjk3MzY4MTE3OS5tcDQ=?b=1903&mmsid=33132933&tm=1466226008&key=c878763e5c77e63ca50efd59012ff106&platid=1&splatid=101&playid=0&tss=ios&vtype=51&cvid=1642070221563&payff=0&pip=33a4f416ce313184a41590c7e64e9f56","178/4/72/letv-uts/14/ver_00_22-323006341-avc-1794815-aac-96000-1260726-300039314-0503953bcc50a744b2820e922c77a0fd-1436973681179.mp4"]}},"point":{"skip":[0,1201]},"statuscode":"1001","trylook":"0","watermark":{"imgs":[{"lasttime":"1800","link":"","position":"2","url100":"http://i1.letvimg.com/lc04_iscms/201601/12/15/22/47615b27e213449da27bfd356df13f38.png"},{"lasttime":"1800","link":"","position":"1","url100":"http://i0.letvimg.com/lc04_iscms/201601/12/15/22/afd7ca79d3564037acd9606ce04069c2.png"}],"offset":"3"}}

**Comment by redstoneleo** [comment]
@cnbeining 是因为乐视采用了新的API  url以 api.le.com 开头了

**Comment by goodneo** [comment]
所以感覺要小修改? 搞不懂我這邊出錯的問題在哪

**Comment by soimort** [comment]
Can you watch the video in your browser?

**Comment by goodneo** [comment]
可以

**Comment by lki2019** [comment]
Downloading 来自未来的史密特01集.mp4 ...
 0.0% (  0.0/ 84.0MB) ├───────────────────────────
 0.1% (  0.1/ 84.0MB) ├───────────────────────────
 0.4% (  0.3/ 84.0MB) ├───────────────────────────
 0.6% (  0.5/ 84.0MB) ├───────────────────────────
 0.9% (  0.8/ 84.0MB) ├───────────────────────────
 1.2% (  1.0/ 84.0MB) ├█──────────────────────────
 1.3% (  1.1/ 84.0MB) ├█──────────────────────────
 1.6% (  1.3/ 84.0MB) ├█──────────────────────────
 1.9% (  1.6/ 84.0MB) ├█──────────────────────────
 2.2% (  1.8/ 84.0MB) ├█──────────────────────────
 2.5% (  2.1/ 84.0MB) ├█──────────────────────────
 2.6% (  2.2/ 84.0MB) ├█──────────────────────────
 2.9% (  2.4/ 84.0MB) ├█──────────────────────────
 3.2% (  2.7/ 84.0MB) ├██─────────────────────────
 3.5% (  2.9/ 84.0MB) ├██─────────────────────────
 3.8% (  3.2/ 84.0MB) ├██─────────────────────────
 4.1% (  3.4/ 84.0MB) ├██─────────────────────────
 4.4% (  3.7/ 84.0MB) ├██─────────────────────────
───────────┤[ 5/80]    5 MB/s



可以下载啊，可以关闭啦
