### ISSUE TITLE
Need help to fix Douyutv

### ISSUE THREAD

**Issue by RazerBoy** [soimort/you-get#1214]
![image](https://cloud.githubusercontent.com/assets/20024220/16176771/c77ec882-3641-11e6-9adb-d56759ff9b7b.png)
im new  pls help me i dont know how to fix this :(

**Comment by zhangn1985** [comment]
@RazerBoy 很明显，你用了一个很老版本的you-get改出来的代码。新代码用了一个完全不一样的API。

自行下载新代码。

**Comment by RazerBoy** [comment]
and how to do that?
can u guide me please :D where's can i get the new code and how to apply it's to my present version of you-get?

**Comment by cnbeining** [comment]
https://github.com/soimort/you-get#upgrading

**Comment by soimort** [comment]
This has nothing to do with `you-get`, as far as I can tell.
