### ISSUE TITLE
关于IPv6

### ISSUE THREAD

**Issue by huanghe2015** [soimort/you-get#1215]
请问这个是否支持IPv6网络？

**Comment by cnbeining** [comment]
取决于网站是不是支持。

2016年6月20日星期一，Mort the Bot <notifications@github.com> 写道：

**Comment by soimort** [comment]
我们这里不关心IP协议层。

Python 标准库的底层实现当然是支持IPv6的。尽管可以强制指定`AF_INET`或`AF_INET6`，但是这个对我们来说意义不大。
