### ISSUE TITLE
iqiyi 所有链接返回广告视频

### ISSUE THREAD

**Issue by fixee** [soimort/you-get#1216]
you-get -i http://www.iqiyi.com/v_19rrle48gg.html
site:                爱奇艺 (Iqiyi)
title:               广告宣传片
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        suprt-high
      container:     f4v
      video-profile: 超高清
      size:          16.4 MiB (17190194 bytes)
    # download-with: you-get --format=suprt-high [URL]

    - format:        high
      container:     f4v
      video-profile: 高清
      size:          6.6 MiB (6946897 bytes)
    # download-with: you-get --format=high [URL]

    - format:        standard
      container:     f4v
      video-profile: 标清
      size:          4.3 MiB (4500446 bytes)
    # download-with: you-get --format=standard [URL]

    - format:        topspeed
      container:     f4v
      video-profile: 最差
      size:          1.8 MiB (1862837 bytes)
    # download-with: you-get --format=topspeed [URL]

**Comment by nuomi1** [comment]
#1211
