### ISSUE TITLE
我用Python写了一段脚本，可以批量下载youtube的视频，但是在下载的过程中，总是一部分网址错误，但是单独下载那一个网址又没有问题。

### ISSUE THREAD

**Issue by rainbow0727** [soimort/you-get#1217]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
这个是Python写的
import os
import re
file=open("label_test.txt")

for line in file:
    line=line.strip()
    line=line.split()
    name=line[0]
    subset=line[1]
    url=line[2]
    com1='you-get   -o /activity-net/test -O'
    com2='.wbem'
    os.system("%s %s%s %s"%(com1,name,com2,url))
file.close()


如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rainbow0727** [comment]
@soimort

**Comment by cnbeining** [comment]
把有问题部分的log拿上来吧。

另 

    com2='.webm'

**Comment by rainbow0727** [comment]
https://www.youtube.com/watch?v=5i2Vf0seCWI
 https://www.youtube.com/watch?v=bIxkfJuPGIU
  https://www.youtube.com/watch?v=ykPa3jGYdAM  比如这几个，

**Comment by cnbeining** [comment]
我的意思是。。。你遇到的错误。

2016年6月21日星期二，rainbow0727 <notifications@github.com> 写道：

**Comment by rainbow0727** [comment]
单独you-get  网址是可以正常下载的，但是在用Python尝试批量下载的过程中就出错了

**Comment by cnbeining** [comment]
我要看你当时不能下载时遇见的错误。

2016年6月21日星期二，rainbow0727 <notifications@github.com> 写道：

**Comment by rainbow0727** [comment]
![Uploading 3.jpg…]()

**Comment by rainbow0727** [comment]
我上传不了图片。。。。--debug的最后一句是urlopen error 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。在浏览器中是可以打开播放的。

**Comment by soimort** [comment]
也许是的。
