### ISSUE TITLE
[Feature Request] SHOWROOM (general HLS support)

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#1218]
https://www.showroom-live.com/

Sample API:
https://www.showroom-live.com/room/get_live_data?room_id=61720

![1-160430142r3](https://cloud.githubusercontent.com/assets/342945/16250757/4a659ff2-3820-11e6-8816-adf94c4ac5ae.jpg)

General support for HLS [1] needs to be implemented in order to accommodate this. Another simple showcase:
http://live.schou.me/fish.m3u8

See also an earlier issue regarding YouTube Live streaming: #37.

Furthermore, encoding on the fly should be provided as an option.

[1] https://en.wikipedia.org/wiki/HTTP_Live_Streaming

**Comment by zhangn1985** [comment]
pip show m3u8
https://github.com/globocom/m3u8

this lib can help to parse m3u8. and it's stable.

**Comment by cnbeining** [comment]
#1237
