### ISSUE TITLE
同一个视频，exe版和python版youget下载合并的文件为何不同格式？

### ISSUE THREAD

**Issue by tulip33** [soimort/you-get#1227]
如这个优酷视频 [http://v.youku.com/v_show/id_XMTYxMjg0NTQ2MA==.html?from=y1.2-2.4.2-1](http://v.youku.com/v_show/id_XMTYxMjg0NTQ2MA==.html?from=y1.2-2.4.2-1)
最高清晰度，exe版下载合并成的是mp4，而python中安装的youget，下载合并成的却是flv，为何会这样？python怎样下载成mp4文件？

**Comment by tulip33** [comment]
exe是指you-get-0.4.455-win32-full.7z那个集成版

**Comment by zhangn1985** [comment]
有可能你选取的是不同清晰度的视频。youku基本上都是flv。只有当mp4这个profile时才是mp4

**Comment by tulip33** [comment]
我没加参数，就是【you-get 链接】 下载的，都是最高清晰度，

**Comment by tulip33** [comment]
mp4大小是1603957473
flv的是1604885766
flv文件普遍播放时拖动反应慢，而mp4拖动播放反应即时

**Comment by soimort** [comment]
python 版需要你自行安装 ffmpeg。有了 ffmpeg，才能合并成 mp4。

Windows 打包版自带 ffmpeg。

**Comment by tulip33** [comment]
是装了ffmpeg，加了环境变量，不然也不能自动合并吧

**Comment by tulip33** [comment]
ffmpeg是最新版 ffmpeg-latest-win64-static.zip

**Comment by tulip33** [comment]
晕，是环境变量少了个\bin
好了，能合并成mp4了
