### ISSUE TITLE
sth. wrong while downloading videos via you-get from vk, with cookies.sqlite

### ISSUE THREAD

**Issue by mapleaimer** [soimort/you-get#1230]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\maple>you-get -c C:\\Users\\maple\\AppData\\Roaming\\Mozilla\\Firefox\\
Profiles\\"lz5el7ec.default"\\cookies.sqlite http://vk.com/id262353410#/videos-4
6371384?section=all&z=video-46371384_170674389%2Fclub46371384%2Calbum-46371384%2
Fpl_-46371384
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
'z' is not recognized as an internal or external command,
operable program or batch file.

while, this video could be watched on firefox, but when i tried to download it with you-get, i turned out to be alike this~ 

anyone help? thanks~

**Comment by mapleaimer** [comment]
...in china mainland... we can't open Google... really sorry~

**Comment by cnbeining** [comment]
Use " to quote your URL if non-alphabetical characters exist in it. Or
unpredictable behavior should be expected.

2016年6月27日星期一，Mort Yao <notifications@github.com> 写道：

**Comment by soimort** [comment]
Please read the hint given by `you-get`. Also, please format your command-line output properly and paste the _exact URL_ so it would be possible for our bot to test it.
