### ISSUE TITLE
video from http://v.qq.com did`t work well,please correct this bug,thx for ur work!

### ISSUE THREAD

**Issue by huangtao00** [soimort/you-get#1234]
First ,thx for your excellent work for us! I have upated you-get to python3 version. But it did`t work well for some webpage ,especially for the website http://v.qq.com.

Maybe u can check out the source code to find the bug!Below is an example that works baddly,which can only get a piece of video, 10.76 MiB!
$ you-get  -i http://v.qq.com/page/p/8/d/p0180p2kr8d.html
Site:       QQ.com
Title:      p0180p2kr8d
Type:       MPEG-4 video (video/mp4)
Size:       10.76 MiB (11279999 Bytes)

**Comment by rosynirvana** [comment]
```
Site:       QQ.com
Title:      恩典浪潮第7堂：神信实的盟约，会改变吗？
Type:       MPEG-4 video (video/mp4)
Size:       319.38 MiB (334890289 Bytes)
```
