### ISSUE TITLE
douyoutv 不是以房间号结尾的url 无法下载

### ISSUE THREAD

**Issue by sosmygirl** [soimort/you-get#1235]
Please make sure these boxes are checked before submitting your issue – thank you!
- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read https://github.com/soimort/you-get/wiki/FAQ and tried to do so.
- [x] The issue is not yet reported on https://github.com/soimort/you-get/issues or  https://github.com/soimort/you-get/wiki/Known-Bugs. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 https://github.com/soimort/you-get/wiki/FAQ 中的指引进行了操作.
- [x] 您的问题没有在https://github.com/soimort/you-get/issues , https://github.com/soimort/you-get/wiki/FAQ 或 https://github.com/soimort/you-get/wiki/Known-Bugs 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:
C:\Users\lee>you-get --debug http://www.douyu.com/cms/zt/lpl.html
you-get: version 0.4.455, a tiny downloader that scrapes the web.
you-get: ['http://www.douyu.com/cms/zt/lpl.html']
Traceback (most recent call last):
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\you-get\you-get.exe__main__.py", line 9, in <module>
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get__main__.py", line 92, in main
    main(*_kwargs)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1291, in main
    script_main('you-get', any_download, any_download_playlist, *_kwargs)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1204, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1041, in download_main
    download(url, *_kwargs)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1284, in any_download
    m.download(url, *_kwargs)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\douyutv.py", line 18, in douyutv_download
    server_status = data.get('error',0)
AttributeError: 'str' object has no attribute 'get'

C:\Users\lee>you-get --debug http://www.douyu.com/cms/zt/lpl.html
you-get: version 0.4.455, a tiny downloader that scrapes the web.
you-get: ['http://www.douyu.com/cms/zt/lpl.html']
Traceback (most recent call last):
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\you-get\you-get.exe__main__.py", line 9, in <module>
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get__main__.py", line 92, in main
    main(*_kwargs)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1291, in main
    script_main('you-get', any_download, any_download_playlist, *_kwargs)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1204, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1041, in download_main
    download(url, *_kwargs)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\common.py", line 1284, in any_download
    m.download(url, *_kwargs)
  File "c:\users\lee\appdata\local\programs\python\python35-32\lib\site-packages\you_get\extractors\douyutv.py", line 18, in douyutv_download
    server_status = data.get('error',0)
AttributeError: 'str' object has no attribute 'get'

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]
> http://www.douyu.com/cms/zt/lpl .html
> http://www.douyu.com/cms/zt/demaxiya.html

**Comment by ERioK** [comment]
点一下举报按钮就能看到房间号了，这个问题好像没人想去修

**Comment by sosmygirl** [comment]
@ERioK 谢谢啊。。。

**Comment by nuomi1** [comment]
专题页面的源码都不统一，难道要一个一个适配么……

**Comment by lamlam123tld3** [comment]
douyu has a new api now
http://www.douyu.com/lapi/live/getPlay/{roomID}
the old swf_api can only retrieve the room info but the the url
who knows how long can the v1 api exists

**Comment by steven7851** [comment]
new api need data
"sign" and "did" is new method, wait someone decompile it

Example:
```
data = {
    "cdn": "ws",
    "rate": "0",
    "tt": "24453709",
    "sign": "af3bf46411c0b32645531c6164d9d398",
    "did": "4221E644EDABEADD4E954BEF3ECF367D"
}
 #cdns: ws,主线路 tct,备用线路5  ws2,备用线路2 dl,备用线路3
 #rate: 0,超清 2,高清 1,普清
 #tt: int(time.time()/60)
```

**Comment by hellofwy** [comment]
@lamlam123tld3 
It seems v1 api has been gone.
Get following reply:
```
{'error': 1002, 'data': 'api身份信息错误'}
```
Hope someone will provide the new api soon.

**Comment by steven7851** [comment]
old v1 api still can use by changing domain
```python
src/you_get/extractors/douyutv.py line 15

-    json_request_url = "http://www.douyu.com/api/v1/%s&auth=%s" % (suffix, sign)
+    json_request_url = "http://capi.douyucdn.cn/api/v1/%s&auth=%s" % (suffix, sign)
```

**Comment by lamlam123tld3** [comment]
thx for the patch @steven7851

**Comment by hellofwy** [comment]
@steven7851 
It works! Thanks a lot!
The video url returned by api can been downloaded by wget, but won't open directly by MPC-HC. Sad...

**Comment by steven7851** [comment]
@hellofwy 
use --player-http ?

**Comment by hellofwy** [comment]
@steven7851 
No, my own little program use this api, and I'm using Windows.
My program gets the video url, and I open it with MPC-HC by "File > Open File...".

**Comment by hellofwy** [comment]
@steven7851 
The api after changing domain has stop working.
Being forbidden so quickly makes me think maybe somebody from douyu is watching this.

**Comment by lamlam123tld3** [comment]
failed

**Comment by hellofwy** [comment]
Try to decompile the douyu apk.
It's too hard...
The encrypt code part is in libdanmu.so.
But I don't know how to decompile c code.
Give up...

**Comment by hellofwy** [comment]
@steven7851 

> 
```
post http://www.douyu.com/lapi/live/getPlay/{roomID}
data = {
    "cdn": "ws",
    "rate": "0",
    "tt": "24453709",
    "sign": "af3bf46411c0b32645531c6164d9d398",
    "did": "4221E644EDABEADD4E954BEF3ECF367D"
}
#cdn: ws,主线路 tct,备用线路5 ws2,备用线路2 dl,备用线路3
#rate: 0,超清 2,高清 1,普清
#tt: int(time.time()/60)
```

```
#did: an device id, 32 characters
sign = md5(room_id + did + "A12Svb&%1UUmf@hC" + tt)
```

Hope someone can put it in the you-get code.
This is Douyu's Flash api, so it may changes soon.

**Comment by cnbeining** [comment]
Wow.

I will implement the change soon.

Can you tell us how and where you find the salt?

Thanks.

2016年7月24日星期日，hellofwy <notifications@github.com> 写道：

**Comment by hellofwy** [comment]
@cnbeining 
Anyone who decompiled the Douyu's swf file can find the salt after some digging.

**Comment by cnbeining** [comment]
I see. So the decryption of the player SWF haven't changed and the password
is still the same?

2016年7月24日星期日，hellofwy <notifications@github.com> 写道：

**Comment by steven7851** [comment]
@hellofwy
Thank you for great work.
The core.swf is encryption and I don't know how to decrypt...

**Comment by steven7851** [comment]
```python
#!/usr/bin/env python

__all__ = ['douyutv_download']

from ..common import *
import json
import hashlib
import time
import random
import string

def douyutv_download(url, output_dir = '.', merge = True, info_only = False, **kwargs):
    room_id = url[url.rfind('/')+1:]

    json_request_url = "http://m.douyu.com/html5/live?roomId=%s" % (room_id)
    content = get_html(json_request_url)
    data = json.loads(content)['data']
    server_status = data.get('error',0)
    if server_status is not 0:
        raise ValueError("Server returned error:%s" % server_status)

    title = data.get('room_name')
    show_status = data.get('show_status')
    if show_status is not "1":
        raise ValueError("The live stream is not online! (Errno:%s)" % server_status)

    tt = int(time.time() / 60)
    did = ''.join([random.choice(string.ascii_uppercase + string.digits) for n in xrange(32)])
    sign = hashlib.md5((room_id + did + 'A12Svb&%1UUmf@hC' + tt).encode("utf-8")).hexdigest()
    json_request_url = "http://www.douyu.com/lapi/live/getPlay/%s" % (room_id)
    content = parse_query_param(json_request_url, rate=0&tt=tt&did=did&sign=sign&cdn=ws)
    data = json.loads(content)['data']
    server_status = data.get('error',0)
    if server_status is not 0:
        raise ValueError("Server returned error:%s" % server_status)

    real_url = data.get('rtmp_url')+'/'+data.get('rtmp_live')

    print_info(site_info, title, 'flv', float('inf'))
    if not info_only:
        download_urls([real_url], title, 'flv', None, output_dir, merge = merge)

site_info = "douyu.com"
download = douyutv_download
download_playlist = playlist_not_supported('douyu')
```
I try to code extractors for you-get first time.
But I don't know how to post data via you-get.
Please see my PR of livestreamer for reference.
https://github.com/chrippa/livestreamer/pull/1414

**Comment by hellofwy** [comment]
@steven7851 JPEXS can find swf files from the memory of a process.

**Comment by steven7851** [comment]
@hellofwy 
Thank you for providing the method. I'll try to find the key by myself.

**Comment by rosynirvana** [comment]
outdated
