### ISSUE TITLE
Downloading from Iqiyi gives 1:30, 16MB Chinese video

### ISSUE THREAD

**Issue by delpetra** [soimort/you-get#1238]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
>you-get --debug -O "R1 Kerber Robson.mp4" -o "D:\Wimbledon" "http://www.iqiyi.com/v_19rrli054g.html#vfrm=8-8-0-1"
[DEBUG] get_content: http://cache.video.qiyi.com/vms?key=fvip&src=1702633101b340d8917a69cf8a4b8c7&tvId=502278300&vid=b3336c7d61bd0585da883066f3ca978e&vinfo=1&tm=2887&enc=2d1bcdf9bf088cce541bf33612a10c5f&qyid=e8f9e6c9b2374f2cb3acc61ef54fc8a4&tn=0.301563043228793&um=1&authkey=574380e1cea03e0af9840cc16f8dcc05
[DEBUG] get_content: http://data.video.qiyi.com/t?tn=0.47890892158186393
[DEBUG] get_content: http://data.video.qiyi.com/1e2ca676510c987646810688534ed1b9/videos/v0/20160614/7f/bc/463a675a7a52033ba0174a1f159adb51.f4v?qd_tvid=496130600&qd_vipres=0&qd_index=1&qd_aid=496130600&qd_stert=0&qd_scc=9180d1951ed4bf6e18b30b02fedba4cc&qd_sc=4611a8a60af8c8f6de1b05813c5c085b&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_ip=ca6c0ef0&qd_uid=2047395208&qd_tm=1465957198790&qd_vip=1?su=e8f9e6c9b2374f2cb3acc61ef54fc8a4&qyid=9a8060ea182b499fa73ca05640135cdc&client=&z=&bt=&ct=&tn=11170
stream:
    - format:        suprt-high
      container:     f4v
      size:          16.4 MiB (17190194 bytes)
    # download-with: you-get --format=suprt-high [URL]

Downloading R1 Kerber Robson.mp4 ...
 100% ( 16.4/ 16.4MB) ├█████████████████████████████████████████┤[1/1]  897 kB/s
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> Have been able to download fine from Iqiyi for several weeks but have recently started to only get these 16MB files downloaded. Here is a link to what is downloaded: https://youtu.be/AN_rkWK5EL4 
Kept trying to download the same file and did get the chance to download the proper video but after a few minutes I wasn't able to again. Can watch the full video fine on the website. I don't recognise the 16MB video that's downloaded either - it doesn't seem to be what plays as the advert when you first load the video. Wasn't able to translate the red text.

**Comment by soimort** [comment]
The issue was resolved by #1236.
