### ISSUE TITLE
B站视频可以下载分段但合并出错

### ISSUE THREAD

**Issue by gonejack** [soimort/you-get#1244]
http://www.bilibili.com/video/av815389/

已经git pull至最新，运行环境是Linux debian

加上debug参数也没有更多信息。

**Comment by soimort** [comment]
请给出出错信息和ffmpeg版本。

**Comment by gonejack** [comment]
抱歉刚刚是youget url --debug，没有得到debug信息，调整为youget --debug url后有报错，报在ffmpeg.py 158行，然后才想起有ffmpeg依赖。

这里是否能优化一下提示呢，提示说没装ffmpeg什么的。

我先把ffmpeg装上，再回来汇报

**Comment by gonejack** [comment]
装完ffmpeg后正常运行了，谢谢。
