### ISSUE TITLE
youku视频只能解析到预览部分,vip

### ISSUE THREAD

**Issue by janice000** [soimort/you-get#1255]
如下视频：
http://www.tudou.com/albumplay/5V0r_-4bU7o/oKR38Wsg3dU.html

D:\python\Scripts>you-get -d http://www.tudou.com/albumplay/5V0r_-4bU7o/oKR38Wsg3dU.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTYyNzY5NjM1Mg==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTYyNzY5NjM1Mg==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/346769946608812b0cdf6_00/st/flv/fileid/03008001005756AC0E8896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109?token=1744&ctype=12&K=3b96c1969dcdcd4a2412a9aa&oip=758885274&ep=cSaSHU%2BEX8oG4yPXgD8bNSyxICEJXP4J9h%2BNgdJjALshT%2B256E3RspW4R%2FlCFvkZcSB1GOyEqaKSY0FlYflE324Q3jurS%2FqR%2BPPn5dknseV1YhFDAMzXvVSfRDT1&ev=1&yxon=1
site:                优酷 (Youku)
title:               终极一班4 13
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          549.8 MiB (576507406 bytes)
    # download-with: you-get --format=hd3 [URL]

Downloading 终极一班4 13.flv ...
 0.0% (  0.0/549.8MB) ├──────────────────────────── 0.0% (  0.2/549.8MB) ├──────────────────────────── 0.1% (  0.5/549.8MB) ├──────────────────────────── 0.1% (  0.8/549.8MB) ├──────────────────────────── 0.2% (  1.0/549.8MB) ├──────────────────────────── 0.2% (  1.2/549.8MB) ├──────────────────────────── 0.3% (  1.5/549.8MB) ├──────────────────────────── 0.3% (  1.8/549.8MB) ├──────────────────────────── 0.3% (  1.8/549.8MB) ├─────────────────────────────────────────┤[1/1]    3 MB/s

**Comment by soimort** [comment]
这是付费视频，当然。
