### ISSUE TITLE
对比一下youtube-dl （本身只是 下载google nexus 原厂镜像 无任何反应）

### ISSUE THREAD

**Issue by mengyyy** [soimort/you-get#1257]
一点反应都没有 
![2016-07-07_140817](https://cloud.githubusercontent.com/assets/10589755/16644012/3d1766ae-444c-11e6-8eaf-0528ecfb9ca8.jpg)
另外下载youtube 4k 时特别慢
![2016-07-07_141011](https://cloud.githubusercontent.com/assets/10589755/16644046/7e287ce6-444c-11e6-9982-8e1808b3d387.jpg)
===================
在对比一下 youtube-dl 
镜像可以下载
![2016-07-07_141139](https://cloud.githubusercontent.com/assets/10589755/16644080/be018114-444c-11e6-9d01-1efa7845b486.jpg)
 4k 下载完全无压力
![2016-07-07_141103](https://cloud.githubusercontent.com/assets/10589755/16644090/cf8aab40-444c-11e6-89ee-2c239786c585.jpg)

**Comment by mengyyy** [comment]
不知道这软件写出来的定位是什么  
体验还不如youtube-dl    还没有socks5代理支持……
真的感觉很垃圾

**Comment by cnbeining** [comment]
UCUP。

**Comment by nuomi1** [comment]
居然能在 GitHub 看到三观帖，服了……

手动滑稽.PNG

**Comment by zhangn1985** [comment]
这个是提issue请求关闭项目的吗？

**Comment by cnbeining** [comment]
Github什么时候出个对project block用户就好了。。。

也许应该请个愿什么的 去dear-github。

**Comment by soimort** [comment]
![tumblr_inline_mwt1trwlb71sokgt1](https://cloud.githubusercontent.com/assets/342945/16654307/772a9c22-4455-11e6-8079-b9ec1f4ab8de.gif)

**Comment by sosmygirl** [comment]
唉，智商啊

**Comment by kcschan** [comment]
HATERS GONNA HATE

sosmygirl <notifications@github.com>于2016年7月8日周五 下午12:01写道：

**Comment by zhangn1985** [comment]
youtube-dl 已经有近13000次提交，而you-get只有1300次。
youtube-dl有 425个贡献者，you-get只有73个。
youtube-dl 社区运行时间也应该比 you-get长。

所以you-get跟youtube-dl相比有些不足很正常。

但是you-get也有它的优点。
简单，简洁。less is more.
去看看youtube-dl提供的命令行参数有多少就知道使用youtube-dl是多么困难

**Comment by cnbeining** [comment]
支持网站的侧面不同。现在you-get已经基本覆盖所有大陆视频站了：其他华语视频站也差不多全覆盖了。我快想不出还有什么解析需要写了。。。

2016年7月8日星期五，zhangn1985 <notifications@github.com> 写道：

**Comment by cybmp3** [comment]
MDZZ
