### ISSUE TITLE
[bilibili]当来源是QQ视频的时候支持

### ISSUE THREAD

**Issue by NStal** [soimort/you-get#126]
例子:http://www.bilibili.tv/video/av23789/

当使用cid判定然后来源是
http://vhot2.qqvideo.tc.qq.com/87528110/ZWuB0zrSVh6.flv?sdtfrom=v2&r=979

直接访问会导致405，网页版本的会转化成http://vsrctfs.tc.qq.com/87528110/ZWuB0zrSVh6.flv?channel=vhot2&sdtfrom=v2&r=256&rfc=v10,其中只有channel=vhot2是必须的参数.

我不太清楚背后发生了什么,但是87528110/ZWuB0zrSVh6 似乎就是qq_download_by_id中的id参数.所以我考虑做一个不太优雅的hack

要么在bilibili_download_by_cid中匹配vhot2.qqvideo.tc.qq.com重定向到vsrctfs去.
要么在bilibili_download_by_cid中匹配vhot2.qqvideo.tc.qq.com抓出id然后调用qq_download_by_id

哪个比较合适呢?

**Comment by cnbeining** [comment]
Requesting issue close. @soimort
