### ISSUE TITLE
Exception with some Facebook videos

### ISSUE THREAD

**Issue by oadiazp** [soimort/you-get#1263]
Please make sure these boxes are checked before submitting your issue – thank you!
- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ x ] Your `you-get` is up-to-date.
- [ x ] I have read https://github.com/soimort/you-get/wiki/FAQ and tried to do so.
- [ x ] The issue is not yet reported on https://github.com/soimort/you-get/issues or  https://github.com/soimort/you-get/wiki/Known-Bugs. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```

(video_downloader)➜  video_downloader you-get --debug https://www.facebook.com/ferro.dania/videos/vb.100000075904362/1204011846278001/\?type\=2\&theater
you-get: version 0.4.455, a tiny downloader that scrapes the web.
you-get: ['https://www.facebook.com/ferro.dania/videos/vb.100000075904362/1204011846278001/?type=2&theater']
Traceback (most recent call last):
  File "/Users/zcool/venvs/video_downloader/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Users/zcool/venvs/video_downloader/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/zcool/venvs/video_downloader/lib/python3.5/site-packages/you_get/common.py", line 1291, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Users/zcool/venvs/video_downloader/lib/python3.5/site-packages/you_get/common.py", line 1204, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Users/zcool/venvs/video_downloader/lib/python3.5/site-packages/you_get/common.py", line 1041, in download_main
    download(url, **kwargs)
  File "/Users/zcool/venvs/video_downloader/lib/python3.5/site-packages/you_get/common.py", line 1284, in any_download
    m.download(url, **kwargs)
  File "/Users/zcool/venvs/video_downloader/lib/python3.5/site-packages/you_get/extractors/facebook.py", line 17, in facebook_download
    type, ext, size = url_info(sd_urls[0], True)
IndexError: list index out of range

```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!
- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 https://github.com/soimort/you-get/wiki/FAQ 中的指引进行了操作.
- [ ] 您的问题没有在https://github.com/soimort/you-get/issues , https://github.com/soimort/you-get/wiki/FAQ 或 https://github.com/soimort/you-get/wiki/Known-Bugs 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by soimort** [comment]
This is not even public viewable.

![screenshot from 2016-07-08 19-42-45](https://cloud.githubusercontent.com/assets/342945/16696197/36833798-4544-11e6-95a0-0744a37b7fc7.png)

**Comment by oadiazp** [comment]
Ahh the video is not public? Good to know, thanks

**Comment by soimort** [comment]
There's no way for me to fix this (even if it's a bug), since I have no access to the page.

Closing.

**Comment by ellisonleao** [comment]
I am getting this with a public video right now https://www.facebook.com/Molejooficial/videos/946784505421804/

**Comment by rosynirvana** [comment]
```
./you-get -d -o /tmp https://www.facebook.com/Molejooficial/videos/946784505421804/
[DEBUG] get_response: https://www.facebook.com/Molejooficial/videos/946784505421804/
[DEBUG] url_info: https://fb-l-b-a.akamaihd.net/h-ak-fbx/v/t43.1792-2/15628131_573420462854142_7740265854691966976_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&oh=6a9de781573a6a055ba78ad3fd11b9b9&oe=59AE3FE2&__gda__=1504593868_45f1c29c5692bdf67231011c3c1a8ece
Site:       Facebook.com
Title:      Molejo - Feliz Natal, galera! Muita paz pra todos vocês e...
Type:       MPEG-4 video (video/mp4)
Size:       6.77 MiB (7101548 Bytes)

Downloading Molejo - Feliz Natal, galera! Muita paz pra todos vocês e....mp4 ...
14.8% (  1.0/  6.8MB) ├██████───────────────────────────────────┤[1/1]   98 kB/s
```
