### ISSUE TITLE
冒昧的弄了群99968842

### ISSUE THREAD

**Issue by weigeloveu** [soimort/you-get#1269]
点击链接加入群【you-get issues】：http://jq.qq.com/?_wv=1027&k=2GLsLGu
如果不允许的话，麻烦删除，我啥也不懂，只是希望有一个方便的交流平台。

**Comment by soimort** [comment]
1. 如果需要报 Issue，建议收集好完整的信息后发在这里。GitHub是一个公共的平台，发在这里的问题所有人都能看到，想修issue的人谁都能修。如果之前有人提过类似的问题，还可以高效地利用搜索功能找到答案。
2. 如果需要提问、或者发起无关Issue的讨论，可以使用 gitter。

当然要自建封闭的聊天群讨论我也是不反对的，只是没有办法得到来自我的反馈而已。

**Comment by cnbeining** [comment]
根据我为其他项目做支持的经验，我必须指出，这种封闭交流平台的消息众多然而问题集中，造成没有人去翻issue，问的问题都一样。

请高效使用issue和Gitter。

2016年7月10日星期日，Mort Yao <notifications@github.com> 写道：
