### ISSUE TITLE
如何得到每段视频的时长

### ISSUE THREAD

**Issue by MathiasLuo** [soimort/you-get#1276]
我现在遇到了一些问题，主要是我想知道每段小的视频时间长度，但是我没有找到，你有没有一个接口可以让我直接获取到呢？

**Comment by MathiasLuo** [comment]
比如像youku的视频，我可以获取到 几段  xxx.flv 的真实地址，但是我不能得到 这个真实地址的时间长度

**Comment by cnbeining** [comment]
目前没有。

这个接口会让解析时间长的不能忍受 而且很多时候除非下载下来 是不能确定的。

2016年7月11日星期一，罗武侠 <notifications@github.com> 写道：

**Comment by MathiasLuo** [comment]
那现在我能不能用其他的方式去获取 那段视频的时长呢？

**Comment by soimort** [comment]
```
$ ffprobe -show_streams [URL] | grep duration=
```

**Comment by MathiasLuo** [comment]
噢 谢谢了
