### ISSUE TITLE
[Feature Request] Periscope

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#1286]
https://www.periscope.tv/

Samples:
- https://www.periscope.tv/w/1BRJjkDBddoxw
- https://www.periscope.tv/w/1ynJOzvBZzkGR

**Comment by yan12125** [comment]
There are some site support requests here that are already supported by youtube-dl. Is there a need to reinvent the wheel? For example: #1040 #1213 #445 #195 #114 #113 #90 #89 #82 #70  #41

**Comment by soimort** [comment]
You're right.
