### ISSUE TITLE
战旗TV在线播放不了。。

### ISSUE THREAD

**Issue by LockVer** [soimort/you-get#1291]
地址：http://www.zhanqi.tv/edmunddzhang
如果不是在线播放，则可以下载，如果在线播放则提示
Site:       zhanqi.tv
Title:      【老E】正义的直播间
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

rtmpdump -r 'rtmp://dlrtmp.cdn.zhanqi.tv/zqlive//9469_lNZYA?k=0d5d0dc3f6e073abc4fe15859b66308d&t=578f39ec'  -o - | mpv.exe -
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
WARNING: Unknown protocol!

WARNING: You haven't specified an output file (-o filename), using stdout
Connecting ...
INFO: Connected...
ERROR: RTMP_ReadPacket, failed to read RTMP packet header
't' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

不知道为什么。。

**Comment by mengmo** [comment]
rtmpdump -r "rtmp://dlrtmp.cdn.zhanqi.tv/zqlive//9469_lNZYA?k=0d5d0dc3f6e073abc4fe15859b66308d&t=578f39ec" -o - | mpv.exe -

**Comment by zhangn1985** [comment]
windows支持管道？

**Comment by LockVer** [comment]
@mengmo 
![image](https://cloud.githubusercontent.com/assets/3351118/17007990/b3e732ae-4f1f-11e6-9ce2-e9af34b13426.png)
用你的代码提示这个。。

**Comment by LockVer** [comment]
@zhangn1985 管道是什么？rtmpdump吗？

**Comment by zhangn1985** [comment]
管道指的是 `|` , 就是 mpv.exe前的竖线。

**Comment by LockVer** [comment]
@zhangn1985 额，这个我也不知道。。如果不支持是不是就播不了了？

**Comment by LockVer** [comment]
@zhangn1985 对了，我是用的windows 10

**Comment by soimort** [comment]
@cnbeining 
This code is non-portable:
https://github.com/soimort/you-get/blob/2fdea30d8d8ad978cdd68014a9f6fc9cf3976b81/src/you_get/processor/rtmpdump.py#L52

**Comment by zhangn1985** [comment]
估计的用subprocess 重写了。

**Comment by zhangn1985** [comment]
```
live_base = "http://dlhls.cdn.zhanqi.tv/zqlive/"
html = get_content(url)
rtmp_id = match1(html, 'videoId":"([^"]+)"').replace('\\/','/')
real_url = live_base+'/'+rtmp_id+'.m3u8'
```
得到的m3u8是一个播放列表，包含不同清晰度。

**Comment by LockVer** [comment]
@zhangn1985 额。。上面的代码要怎么用啊？

**Comment by LockVer** [comment]
@zhangn1985 你好，我得到了m3u8文件，但是文件内容是 
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,PUBLISHEDTIME=1469098856,CURRENTTIME=1469109339,BANDWIDTH=400000,RESOLUTION=854x480
81873_OjyWk_400/index.m3u8?Dnion_vsnae=81873_OjyWk
#EXT-X-STREAM-INF:PROGRAM-ID=1,PUBLISHEDTIME=1469098856,CURRENTTIME=1469109339,BANDWIDTH=700000,RESOLUTION=1280x720
81873_OjyWk_700/index.m3u8?Dnion_vsnae=81873_OjyWk
#EXT-X-STREAM-INF:PROGRAM-ID=1,PUBLISHEDTIME=1469098856,CURRENTTIME=1469109339,BANDWIDTH=1024000,RESOLUTION=1920x1080
81873_OjyWk_1024/index.m3u8?Dnion_vsnae=81873_OjyWk
如果直接用播放器打开是播放不了的。。需要做什么其他处理吗？

**Comment by LockVer** [comment]
@zhangn1985 我把这里面的index.m3u8也下载下来了，但是还是播放不了。里面的路径是1469110057694_1469110057694.ts?Dnion_vsnae=81873_OjyWk这样的。。我加上
http://dlhls.cdn.zhanqi.tv/zqlive/这个也播放不了。

**Comment by cnbeining** [comment]
ffmpeg吃了pipe给播放器 或者VLC这种牙口好的 直接喂M3U地址进去 才行。

**Comment by mengmo** [comment]
1. @zhangn1985 `Windows`应该是支持管道的，我这边测试没有问题
2. 

> rtmpdump -r 'rtmp://dlrtmp.cdn.zhanqi.tv/zqlive//9469_lNZYA?k=0d5d0dc3f6e073abc4fe15859b66308d&t=578f39ec' -o - | mpv.exe -

在`Windows`下，直播流的`url`得用英文的双引号。用`ffplay`和`mpv`播放这种`url`里带`&t=`这类参数的也必须加英文的双引号
@cnbeining 我觉得这儿可能得改 https://github.com/soimort/you-get/blob/2fdea30d8d8ad978cdd68014a9f6fc9cf3976b81/src/you_get/processor/rtmpdump.py#L49
3. @LockVer 获取的直播流`url`有时间限制，而且直播间肯定得开着，所以你用我给的代码才提示出错。一般情况，目前我看直播遇到这种问题时都是复制直播流的`url`用`ffplay`或者`mpv`看

**Comment by soimort** [comment]
Fixed by #1294.
