### ISSUE TITLE
potplayer在线播放问题

### ISSUE THREAD

**Issue by LockVer** [soimort/you-get#1292]
使用potplayer在线播放视频时，因为很多视频时分段的，用potplayer播放时它会把所有的链接当成一个，而不会增加多个链接到播放列表。。所以会导致播放失败。。有没有解决方法啊？
操作如下：
you-get -p PotPlayerMini64.exe http://v.youku.com/v_show/id_XMTQyMzczMzU2NA==.html?from=y1.3-movie-index1-5324-11897.103402-103204-103199.12-1

![image](https://cloud.githubusercontent.com/assets/3351118/17007858/970cd9c8-4f1e-11e6-87f6-bf49b0607c28.png)
结果如下：
![image](https://cloud.githubusercontent.com/assets/3351118/17007865/a36a2be4-4f1e-11e6-99ae-1ecc47d2188d.png)
这里面列表中只有一个文件，实际上，这个视频是有很多分段的。使用VLC播放时如下：
![image](https://cloud.githubusercontent.com/assets/3351118/17007921/30a6b752-4f1f-11e6-9737-ab0c5955f721.png)

**Comment by cnbeining** [comment]
这好像是PotPlayer的锅。。。

**Comment by LockVer** [comment]
@cnbeining O.O是的potplayer接收到参数后没有分割，把所有的段落当成一个URL了。。我现在自己弄了个处理把分段处理成了一个播放列表然后再调用potplayer就可以了。

**Comment by cnbeining** [comment]
怎么处理的？我觉得在这个issue里留下，以后万一需要可以hack。。。

**Comment by LockVer** [comment]
@cnbeining O.O 我是自己写了一个处理程序，然后用you-get -p 处理程序 url 这里会将参数传到我自己的处理程序里面，接收到之后将参数分割处理成m3u8格式后再调用potplayermini.exe [列表地址]
![image](https://cloud.githubusercontent.com/assets/3351118/17012830/04984f8a-4f4d-11e6-8985-5d3a6fa6fc69.png)

**Comment by cnbeining** [comment]
![image](https://cloud.githubusercontent.com/assets/1560962/17012853/93de316a-4ee8-11e6-9cb7-6ae6c694a39a.png)

好吧 受教了。。。

**Comment by LockVer** [comment]
@cnbeining O.O。。哈哈。我刚接触python。。没办法。。帮不上忙。。。

**Comment by hzc54188** [comment]
@LockVer 能分享那段批处理吗？

**Comment by foisonocean** [comment]
@LockVer 请分享一下你的代码

**Comment by liuxb** [comment]
[@LockVer](https://github.com/LockVer) ，同求，希望能分享下解决方案。

**Comment by tzw0745** [comment]
@hzc54188 @foisonocean @liuxb 
.m3u8文件的格式：
![](http://ofpb4e3i2.bkt.clouddn.com/17-4-24/57821443-file_1492986232349_1425e.png)
Python处理（参考）：
![](http://ofpb4e3i2.bkt.clouddn.com/17-4-24/24387624-file_1492986300289_f48a.png)
* 这里我是采用"视频名称 part00"、"视频名称 part01"的格式
