### ISSUE TITLE
希望增加支持今日头条(toutiao.com)视频下载 

### ISSUE THREAD

**Issue by wangby** [soimort/you-get#1295]
如 http://toutiao.com/a6309629233085809154/

**Comment by cnbeining** [comment]
请提供测试link。

**Comment by wangby** [comment]
http://toutiao.com/a6309629233085809154/

**Comment by cnbeining** [comment]
404

**Comment by wangby** [comment]
http://toutiao.com/video/
http://toutiao.com/a6287510883346153985/
