### ISSUE TITLE
战旗TV解析的问题

### ISSUE THREAD

**Issue by mengmo** [soimort/you-get#1297]
这个问题只存在于`Windows`版打包的 binary 上

> you-get --debug http://www.zhanqi.tv/huashan
> you-get: version 0.4.486, a tiny downloader that scrapes the web.
> you-get: ['http://www.zhanqi.tv/huashan']
> Traceback (most recent call last):
>   File "<string>", line 11, in <module>
>   File "src\you_get\__main__.py", line 92, in main
>     main(**kwargs)
>   File "src\you_get\common.py", line 1328, in main
>     script_main('you-get', any_download, any_download_playlist, **kwargs)
>   File "src\you_get\common.py", line 1241, in script_main
>     download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
>   File "src\you_get\common.py", line 1060, in download_main
>     download(url, **kwargs)
>   File "src\you_get\common.py", line 1320, in any_download
>     m, url = url_to_module(url)
>   File "src\you_get\common.py", line 1307, in url_to_module
>     return import_module('.'.join(['you_get', 'extractors', SITES[k]])), url
>   File "importlib\__init__.py", line 126, in import_module
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
> ImportError: No module named 'you_get.extractors.zhanqi'
> you-get returned -1

而这样就没有问题

> python you-get -i http://www.zhanqi.tv/huashan
> Site:       zhanqi.tv
> Title:      岳不群OB 死亡凝视！oh no !!!
> Type:       Flash video (video/x-flv)
> Size:       inf MiB (inf Bytes)

**Comment by mengmo** [comment]
> you-get -di http://www.zhanqi.tv/huashan
> you-get: version 0.4.486, a tiny downloader that scrapes the web.
> you-get: ['http://www.zhanqi.tv/huashan']
> Traceback (most recent call last):
>   File "<string>", line 11, in <module>
>   File "src\you_get\__main__.py", line 92, in main
>     main(**kwargs)
>   File "src\you_get\common.py", line 1328, in main
>     script_main('you-get', any_download, any_download_playlist, **kwargs)
>   File "src\you_get\common.py", line 1241, in script_main
>     download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
>   File "src\you_get\common.py", line 1060, in download_main
>     download(url, **kwargs)
>   File "src\you_get\common.py", line 1320, in any_download
>     m, url = url_to_module(url)
>   File "src\you_get\common.py", line 1307, in url_to_module
>     return import_module('.'.join(['you_get', 'extractors', SITES[k]])), url
>   File "importlib\__init__.py", line 126, in import_module
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
> ImportError: No module named 'you_get.extractors.zhanqi'
> you-get returned -1

这输出还不太一样

**Comment by soimort** [comment]
Someone forgot to import `.zhanyi` module in `__init__.py`, so PyInstaller could not find it.

Thanks for reporting.

**Comment by zhangn1985** [comment]
你可以用Pyinstaller的hooks，这样就不用把每个extractor import一次了。

**Comment by zhangn1985** [comment]
```
from PyInstaller.utils.hooks import collect_submodules

hiddenimports = [x for x in collect_submodules('you_get') ]
```

**Comment by foisonocean** [comment]
Same problem in macOS.

**Comment by outsinre** [comment]
python3: 3.4.5

```
you-get -di http://www.zhanqi.tv/huashan
[DEBUG] get_content: http://www.zhanqi.tv/huashan
[DEBUG] get_content: http://www.zhanqi.tv/api/static/live.roomid/76068.json
you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://www.zhanqi.tv/huashan']
Traceback (most recent call last):
  File "/home/outsinre/opt/pyvenv3/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/common.py", line 1129, in download_main
    download(url, **kwargs)
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "/home/outsinre/opt/pyvenv3/lib64/python3.4/site-packages/you_get/extractors/zhanqi.py", line 40, in zhanqi_download
    cdn = base64.b64decode(cdn).decode("utf-8")
  File "/usr/lib64/python3.4/base64.py", line 83, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/lib64/python3.4/base64.py", line 46, in _bytes_from_decode_data
    "string, not %r" % s.__class__.__name__) from None
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
```
