### ISSUE TITLE
腾讯视频清晰度获取问题。。

### ISSUE THREAD

**Issue by LockVer** [soimort/you-get#1298]
you-get -i http://v.qq.com/x/cover/rzi5ypky1rwvyh8/w0020ca68z9.html
Site:       QQ.com
Title:      w0020ca68z9
Type:       MPEG-4 video (video/mp4)
Size:       12.4 MiB (13000352 Bytes)
这里获取到的是最低清晰度的视频，实际这个视频有超清的。。能获取到超清的吗？

**Comment by nuomi1** [comment]
#1202 下面有 QQ 的说明。

**Comment by lamlam123tld3** [comment]
except the cache files for live stream, v.qq.com would not be able to grab a single file for higher definitions using geturl api.
instead, one should grab the segments one by one using getinfo and getkey api

http://vv.video.qq.com/getinfo
get details, format, filename
http://vv.video.qq.com/getkey
get vkey

**Comment by LockVer** [comment]
@nuomi1 也就是说现在还是没有解决办法吗？我看那边也没有解决。。只是说用浏览器默认成最高画质。。

**Comment by zhangn1985** [comment]
@lamlam123tld3 
http://vv.video.qq.com/getinfo 这个API参数的构造方式，不同视频类型，有不同的构造方式。
任何一种构造方式，都能得到正确的视频地址，但是，被限速了。

**Comment by chitanda** [comment]
顺带着腾讯的视频分段的也只会获取第一部分。
@nuomi1  
如这个视频:
http://v.qq.com/x/page/m0314f4quem.html

**Comment by zmwangx** [comment]
This issue is pretty annoying. I just investigated a bit, and put together the following script to download shd (超清) videos. I have stripped the requests to `http://vv.video.qq.com/getvinfo` and `http://vv.video.qq.com/getvkey` down to the minimum set of queries, and several of those query parameters has to be grabbed from your browser's inspector (e.g., the Network tab of Chrome DevTools). In particular, there's a fluid parameter `cKey` that's only valid for a limited period of time (30 minutes I think). I didn't look into how `cKey` is generated. Whoever has the time and ability is welcome to figure this out and convert my script to a you-get extractor. Also, there might be a way to extract VIP-only 1080p streams, too, but since I'm not a VIP, I don't know the right parameters to `getvinfo`.

My script uses [`jq`](https://stedolan.github.io/jq/) as the JSON parser.

```zsh
#!/usr/bin/env zsh

print_progress () print -R $'\e[32m'"$*"$'\e[0m' >&2
print_error () print -R $'\e[31m'"Error: $*"$'\e[0m' >&2

# Obvious parameters
vid=f00213kcpwl
defn=shd

# To be extracted from browser's network inspector
appver=3.2.19.358
encryptver=5.4
platform=70902
format=10201
ckey=x-NT24B0-3FJRXQI6uALnc12Ws8AVeCu2DmFBWMmWK2yzefOiiRUyvB8ol_69Y09sIPJu3mp4RhTc7oEaog0sXSh12zwBuyUGmjsbCjFiFU1zkUBlLxyjhyCATw7ogn91GxDB8IfzzyAqL3byEqTgOz_Yy3hRoPq_d88CXJDv7x-ynNV7uXL2f0Araieh1w6cLoFFEqbGCNqmAmYqqhkHQB9Sjkvaqr8UaLdPq5UYUSBvyOLkLij7IPIfM5O0SuQpp96aP5Cxug4bgPN2tbbyG0vbp4 # valid for a limited period of time, probably ~30min

parts=()
ffmpeg_concat_list=$vid.list
trap 'rm -f $ffmpeg_concat_list' EXIT
cat /dev/null >$ffmpeg_concat_list

vinfo=$(curl -sS 'http://vv.video.qq.com/getvinfo' --data "otype=json&appver=$appver&platform=$platform&defn=$defn&vid=$vid&cKey=$ckey" | sed 's/^QZOutputJson=//; s/;$//')
base_url=$(jq -r '.vl.vi[].ul.ui[0].url' <<< $vinfo)
base_filename=${$(jq -r '.vl.vi[].fn' <<< $vinfo)%.mp4}
total=$(jq -r '.vl.vi[].cl.ci | length' <<< $vinfo)
jq -r '.vl.vi[].cl.ci[] | ((.idx | tostring) + " " + (.cs | tostring) + " " + .cmd5)' <<< $vinfo | \
    while read index size md5; do
        segment_filename=$base_filename.$index.mp4
        vkey=$(curl -sS 'http://vv.video.qq.com/getvkey' --data "otype=json&appver=$appver&encryptVer=$encryptver&platform=$platform&format=$format&vid=$vid&cKey=$ckey&filename=$segment_filename" | sed 's/^QZOutputJson=//; s/;$//' | jq -r '.key')
        print_progress "Downloading part $index/$total..."
        curl -Lo $segment_filename "$base_url/$segment_filename?vkey=$vkey"
        parts+=$segment_filename
        print -R "file '$segment_filename'" >>$ffmpeg_concat_list
    done

print_progress "Concatenating into $vid.mp4..."
if ffmpeg -f concat -safe -1 -i $ffmpeg_concat_list -c copy $vid.mp4; then
    print_progress "Concatenated into $vid.mp4."
    rm $parts
else
    print_error 'Concatenation failed.'
    exit 1
fi
```

**Comment by lamlam123tld3** [comment]
@zmwangx u can just skip ckey
as u hv already added platform in the query

**Comment by zmwangx** [comment]
> u can just skip ckey as u hv already added platform in the query

Which will simply result in `client not auth` errors.

**Comment by lamlam123tld3** [comment]
@zmwangx 
u should use the getkey api instead of getvkey
getvkey need ckey
who know how to generate ckey!

**Comment by zmwangx** [comment]
> u should use the getkey api instead of getvkey
> getvkey need ckey
> who know how to generate ckey!

Both `getvinfo` and `getvkey` require `cKey`. If you know how to get around that, feel free to roll your own and share the results.

**Comment by lamlam123tld3** [comment]
use getinto to get format 
than use getkey to get vkey
than u get the url

**Comment by lamlam123tld3** [comment]
dont use getvinfo or getvkey

**Comment by zmwangx** [comment]
I used what I used because those are the APIs used by the current player, at least from my testing. If you know better, why don't you just submit a PR? That would be good for everyone.

**Comment by lamlam123tld3** [comment]
$info_api = http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=$vid;
$json = json_decode(get_api($info_api),true);
$new_vid = $json['vl']['vi'][0]['lnk'];
$domain= $json['vl']['vi'][0]['ul']['ui'][0]['url'];
$format = end($json['fl']['fi'])['id'];

$download_url = [];
while(condition){
$count = 0;
$filename = $vid.'.p'.((int)substr($format,-4)).".$count).mp4";
$key_api = "http://vv.video.qq.com/getkey?otype=json&platform=11&format=$format&vid=$vid&filename=".str_replace('.', '%2E', $filename);
$json2 = json_decode(get_api($key_api),true);
$vkey = $json2['key'];
$download_url[] = $domain.$filename."?vkey=$vkey";
$count++;
}

**Comment by zmwangx** [comment]
Yeah, that does seem to work. Just scrap the `cKey`.

**Comment by lamlam123tld3** [comment]
@zmwangx by adding platform, u can skip ckey

**Comment by lamlam123tld3** [comment]
this approach works on many qq's api too

**Comment by zmwangx** [comment]
Not the case with `getvinfo` and `getvkey`. I guess `getinfo` and `getkey` are legacy APIs that will be phased out at some point. Why would they make it more complicated otherwise.

**Comment by lamlam123tld3** [comment]
@zmwangx maybe
i have been using the getinfo and getkey for over 2 years

**Comment by zhangn1985** [comment]
据说空的ckey也是合法ckey. 我用的是 getinfo and getkey 这两个API。

**Comment by qwIvan** [comment]
getkey得到的vkey很下载很慢的，getvkey得到的vkey倒是下载很快

**Comment by qwIvan** [comment]
刚刚已经被我找到了ckey的生成方法了，应该可以解决了

**Comment by denobisipsis** [comment]
Maybe we can get the ckey parameter hacking around:

- download http://static.video.qq.com/TPout.swf 
- rabcdasm it and trace ckey generator in tpout-0\com\tencent\tpv3\media\players\VideoInfoGetter.class.asasm
- insert avm2 code to call localhost to show the ckey
- recompile swf

Now,

- in your script, set a listening localhost server
- open in local your tpout.swf hacked with ?v=$vidid&auto=1
- when ckey appears stop

ckey is the same for getinfo and getvkey.

With ckey, ahead of better speed downloading, you have access to vip-only 1080p without login

**Comment by dkl3** [comment]
Do you have the compiled tpout.swf? I kinda need it
