### ISSUE TITLE
[Youku] Protected video

### ISSUE THREAD

**Issue by Z0IC** [soimort/you-get#1302]
Does you-get support downloading of password protected video from youku ? If so, how to activate this functionality ?

**Comment by Z0IC** [comment]
Oh, sorry ! The intended link is http://v.youku.com/v_show/id_XMTI1NzAyODExMg==.html?f=23689185&from=y1.2-3.4.27

**Comment by zhangn1985** [comment]
you'd better ask video uploader for the password firstly.
