### ISSUE TITLE
you-get如何下载优酷VIP视频？

### ISSUE THREAD

**Issue by jaszou** [soimort/you-get#1303]
you-get http://v.youku.com/v_show/id_XMTQ3MzQxNzY2NA==.html
ite:                优酷 (Youku)
itle:               你是谁-学校2015 08
tream:
   - format:        hd3
     container:     flv
     video-profile: 1080P
     size:          995.8 MiB (1044127568 bytes)
   # download-with: you-get --format=hd3 [URL]

ou-get: [Failed] Cannot extract video source.
ou-get: [error] oops, something went wrong.
ou-get: don't panic, c'est la vie. please try the following steps:
ou-get:   (1) Rule out any network problem.
ou-get:   (2) Make sure you-get is up-to-date.
ou-get:   (3) Check if the issue is already known, on
ou-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
ou-get:         https://github.com/soimort/you-get/issues
ou-get:   (4) Run the command with '--debug' option,
ou-get:       and report this issue with the full output.

you-get  能不能通过登录优酷账号和密码，下载1080P视频

**Comment by lamlam123tld3** [comment]
actually,
youku got a server in beijing (for oversea IPs) that can download segments without key
if u can get the fileid, u can directly download the files.
(including vip files)

**Comment by v1-hermit** [comment]
-c cookies.sqlite 
cookies.sqlite只支持firefox导出的格式

**Comment by jaszou** [comment]
Windows 用户是如何导入cookies.sqlite  有没有完整的命令啊 @v1-hermit

**Comment by jaszou** [comment]
How to download, use agent? @lamlam123tld3

**Comment by v1-hermit** [comment]
cookies.sqlite放到你you-get所在的同一目录
