### ISSUE TITLE
[IQIYI]爱奇艺又不行了，只有我出现这个问题吗？

### ISSUE THREAD

**Issue by westspy** [soimort/you-get#1306]
M3U8 url获取没有问题，但是请求m3u8中的链接不会返回数据，超时。上周五还是可以的。

**Comment by westspy** [comment]
site:                爱奇艺 (Iqiyi)
title:               老九门第1集
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://cache.m.iqiyi.com/dc/dt/a4199f12x20efcf04x777a6171/20160716/c7/db/5c9d68256bb6be11d526532acb892a28.m3u8?qd_sc=6f62534b88f3b676d02ab3fbb2d1d5a8&t_sign=-0-76f90cbd92f94a2e925d83e8ccd22cb7-504028400_04022000001000000000_17 -c copy -bsf:a aac_adtstoasc 老九门第1集.mp4
ffmpeg version 3.1.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with llvm-gcc 4.2.1 (LLVM build 2336.11.00)
  configuration: --prefix=/Volumes/Ramdisk/sw --enable-gpl --enable-pthreads --enable-version3 --enable-libspeex --enable-libvpx --disable-decoder=libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libgsm --enable-libvidstab --enable-libx265 --disable-doc --arch=x86_64 --enable-runtime-cpudetect
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
[hls,applehttp @ 0x7fc03a806200] Failed to open segment of playlist 0
    Last message repeated 1 times

**Comment by westspy** [comment]
@soimort-bot 
site:                爱奇艺 (Iqiyi)
title:               老九门第1集
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://cache.m.iqiyi.com/dc/dt/a4199f12x20efcf04x777a6171/20160716/c7/db/5c9d68256bb6be11d526532acb892a28.m3u8?qd_sc=6f62534b88f3b676d02ab3fbb2d1d5a8&t_sign=-0-76f90cbd92f94a2e925d83e8ccd22cb7-504028400_04022000001000000000_17 -c copy -bsf:a aac_adtstoasc 老九门第1集.mp4
ffmpeg version 3.1.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with llvm-gcc 4.2.1 (LLVM build 2336.11.00)
  configuration: --prefix=/Volumes/Ramdisk/sw --enable-gpl --enable-pthreads --enable-version3 --enable-libspeex --enable-libvpx --disable-decoder=libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libgsm --enable-libvidstab --enable-libx265 --disable-doc --arch=x86_64 --enable-runtime-cpudetect
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
[hls,applehttp @ 0x7fc03a806200] Failed to open segment of playlist 0
    Last message repeated 1 times

**Comment by westspy** [comment]
好像IP被封了，换了一个网络环境就好了。再换回去出问题的网络就是不行

**Comment by cnbeining** [comment]
不要下的太狠啦。

**Comment by v1-hermit** [comment]
现在请求有返回也是错误的了。。
