### ISSUE TITLE
you-get下载优酷的视频，但附加了优酷宣传片？

### ISSUE THREAD

**Issue by FallenDante** [soimort/you-get#1310]
你好，我使用you-get下载优酷视频的时候，下载下来的视频在片尾附加了优酷的宣传片，请问能消除这个附加的宣传片吗？我是用最新develop版本的youget. 下载命令是：you-get http://v.youku.com/v_show/id_XMTY1OTMzMzEyMA==.html

**Comment by FallenDante** [comment]
加了两行代码将广告视频过滤了

**Comment by cnbeining** [comment]
您好：

能否告诉我们您如何进行过滤？如何复现此问题？
