### ISSUE TITLE
代码里用来请求到视频源相关信息的 url 是怎么得来的？

### ISSUE THREAD

**Issue by carlxj** [soimort/you-get#1318]
非常感谢提供了这么好的开源项目，我自己也会去做这开源项目的一份子。

我想请教一个问题，我在学习这段代码过程中，发现内部是通过一个固定的链接+视频的id，去获取视频的源信息相关的内容。 如下 QQ下载：
![1](https://cloud.githubusercontent.com/assets/20727639/17254907/5a9a956c-55e9-11e6-9658-da657482ee19.png)

我的问题是 这个api 的链接是怎么得到的？ 我debug了qq的网页没有找到，能介绍一下吗？ 多谢了

**Comment by steven7851** [comment]
qq视频html5的api, 改user-agent就能看到了
#663

**Comment by cnbeining** [comment]
关闭以不占地方，欢迎继续讨论。

**Comment by carlxj** [comment]
@steven7851 能举例操作一下吗，多谢了。  没明白是怎么操作的

**Comment by steven7851** [comment]
像是chrome有可以改UA的扩充:User-Agent Switcher for Chrome
把UA改成手机的，在网页按右键选检查元素，然后随意载个QQ视频连接
网路的页签就会看到后台载入的连接，包含上述的api
