### ISSUE TITLE
[iqiyi] Error parsing ADTS frame header!

### ISSUE THREAD

**Issue by liuxu623** [soimort/you-get#1320]
➜  ~ you-get -id http://www.iqiyi.com/v_19rrmdszvo.html\#vfrm\=2-3-0-1
[DEBUG] get_content: http://cache.video.qiyi.com/vms?key=fvip&src=1702633101b340d8917a69cf8a4b8c7&tvId=515981000&vid=4d7af00026e9ecb1e90d4066a3f51cea&vinfo=1&tm=2828&enc=a47750ca080840859eeecf2591b886f5&qyid=2e082ac6d1fb4617b0fa0dbd4fe688da&tn=0.3349581434643786&um=1&authkey=d41c7d67213c16334762cb7a754937c9
[DEBUG] get_content: http://data.video.qiyi.com/t?tn=0.15809759742531748
[DEBUG] get_content: http://data.video.qiyi.com/6424073913f2b5f0a0009c36d18218f7/videos/v0/20160614/7f/bc/463a675a7a52033ba0174a1f159adb51.f4v?qd_tvid=496130600&qd_vipres=0&qd_index=1&qd_aid=496130600&qd_stert=0&qd_scc=9180d1951ed4bf6e18b30b02fedba4cc&qd_sc=4611a8a60af8c8f6de1b05813c5c085b&qd_src=1702633101b340d8917a69cf8a4b8c7c&qd_ip=ca6c0ef0&qd_uid=2047395208&qd_tm=1465957198790&qd_vip=1?su=2e082ac6d1fb4617b0fa0dbd4fe688da&qyid=d76750788519420c8573aca37ecd31bf&client=&z=&bt=&ct=&tn=15275
site:                爱奇艺 (Iqiyi)
title:               广告宣传片
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        suprt-high
      container:     f4v
      video-profile: 超高清
      size:          16.4 MiB (17190194 bytes)
    # download-with: you-get --format=suprt-high [URL]

```
- format:        high
  container:     f4v
  video-profile: 高清
  size:          6.6 MiB (6946897 bytes)
# download-with: you-get --format=high [URL]

- format:        standard
  container:     f4v
  video-profile: 标清
  size:          4.3 MiB (4500446 bytes)
# download-with: you-get --format=standard [URL]

- format:        topspeed
  container:     f4v
  video-profile: 最差
  size:          1.8 MiB (1862837 bytes)
# download-with: you-get --format=topspeed [URL]
```

**Comment by jkng** [comment]
you-get: version 0.4.486, a tiny downloader that scrapes the web.

>you-get http://www.iqiyi.com/v_19rrmdszvo.html\#vfrm\=2-3-0-1
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

>^A

**Comment by jkng** [comment]
我下载你那个视频显示这个

**Comment by jkng** [comment]
好像知道了 显示版权受限的视频 好像不能下载

**Comment by Irving23** [comment]
➜  ~ you-get -id http://www.iqiyi.com/v_19rrmdszvo.html\#vfrm\=2-3-0-1
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/515981000/4d7af00026e9ecb1e90d4066a3f51cea/?t=1470027636861&sc=df84d86b9700653c5b9c209ef81b74ab&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrmdszvo.html#vfrm=2-3-0-1']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.486', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1331, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1244, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1324, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractor.py", line 40, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/iqiyi.py", line 139, in prepare
    assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video

**Comment by soimort** [comment]
@soimort-bot Please test this link: http://www.iqiyi.com/v_19rrmdszvo.html#vfrm=2-3-0-1

**Comment by soimort** [comment]
Anyway, it's confirmed.

**Comment by Irving23** [comment]
```
➜  ~  you-get -id http://www.iqiyi.com/v_19rrmdszvo.html\#vfrm\=2-3-0-1
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/515981000/4d7af00026e9ecb1e90d4066a3f51cea/?t=1471417318369&sc=d14f3c86590c1b377097bc60008d5fb3&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               航海王第751集
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=LD [URL]
```
```
➜  ~ you-get --format=TD http://www.iqiyi.com/v_19rrmdszvo.html\#vfrm\=2-3-0-1
site:                爱奇艺 (Iqiyi)
title:               航海王第751集
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://cache.m.iqiyi.com/dc/dt/5854df5x20ce6d71x777a6171/20160731/52/74/dad128077964fc0b232b0ddc8f10a048.m3u8?qd_sc=0427e91a3f3e66d3d1a4c1296eddf695&t_sign=-0-76f90cbd92f94a2e925d83e8ccd22cb7-515981000_04022000001000000000_17 -c copy -bsf:a aac_adtstoasc 航海王第751集.mp4
ffmpeg version 3.0.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 7.3.0 (clang-703.0.29)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.0.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --enable-vda
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, hls,applehttp, from 'http://cache.m.iqiyi.com/dc/dt/5854df5x20ce6d71x777a6171/20160731/52/74/dad128077964fc0b232b0ddc8f10a048.m3u8?qd_sc=0427e91a3f3e66d3d1a4c1296eddf695&t_sign=-0-76f90cbd92f94a2e925d83e8ccd22cb7-515981000_04022000001000000000_17':
  Duration: 00:22:29.00, start: 0.000000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv), 1280x720, 23 fps, 23.98 tbr, 90k tbn, 23 tbc
    Stream #0:1: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 65 kb/s
Output #0, mp4, to '航海王第751集.mp4':
  Metadata:
    encoder         : Lavf57.25.100
    Stream #0:0: Video: hevc ([35][0][0][0] / 0x0023), yuv420p, 1280x720, q=2-31, 23 fps, 23.98 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (HE-AAC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 65 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x7fd73c801000] Non-monotonous DTS in output stream 0:1; previous: 15958016, current: 19848; changing to 15958017. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fd73c801000] Non-monotonous DTS in output stream 0:1; previous: 15958017, current: 21896; changing to 15958018. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fd73c801000] Non-monotonous DTS in output stream 0:0; previous: 32538534, current: 0; changing to 32538535. This may result in incorrect timestamps in the output file.

......

[mp4 @ 0x7fd73c801000] Non-monotonous DTS in output stream 0:0; previous: 32564276, current: 31809277; changing to 32564277. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fd73c801000] Non-monotonous DTS in output stream 0:0; previous: 32564277, current: 31813030; changing to 32564278. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fd73c801000] Non-monotonous DTS in output stream 0:0; previous: 32564278, current: 31816943; changing to 32564279. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fd73c801000] pts has no value
[NULL @ 0x7fd73c062200] Error parsing ADTS frame header!
[NULL @ 0x7fd73c062200] Failed to open bitstream filter aac_adtstoasc for stream 0 with codec copy: Invalid data found when processing input
[mp4 @ 0x7fd73c801000] Non-monotonous DTS in output stream 0:1; previous: 15981128, current: 15591398; changing to 15981129. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fd73c801000] aac bitstream error
frame=34411 fps= 71 q=-1.0 Lsize=  150192kB time=00:06:02.43 bitrate=3394.8kbits/s speed=0.744x
video:138494kB audio:11176kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.348332%
```

**Comment by soimort** [comment]
Seems like a failure of ffmpeg in processing the stream data -- unfortunately I'm not able to confirm this.

**Comment by xf1** [comment]
播放列表不是连续的，m3u8文件里面标记了#EXT-X-DISCONTINUITY。
先按标记的分段把ts拼接成mp4，再把mp4拼接成一个。手动下了一个，长度跟音画同步快进看了下没问题。
视频链接:http://www.iqiyi.com/v_19rrmbg1jk.html
文件链接:http://pan.baidu.com/s/1pLB2Eb5 提取密码:xnet

**Comment by rosynirvana** [comment]
outdated
