### ISSUE TITLE
you-get 保存编码问题！？？

### ISSUE THREAD

**Issue by MYJN** [soimort/you-get#1321]
环境：
C:\Users\WINDOWS>Python -V && you-get -V
Python 3.5.1
you-get: version 0.4.486, a tiny downloader that scrapes the web.
--------------------------------------------------------------------
DEBUG:
C:\Users\WINDOWS>you-get  --debug   https://www.youtube.com/watch?v=BEULybZnLO8
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=BEULybZnLO8
[DEBUG] get_content: https://www.youtube.com/watch?v=BEULybZnLO8
[DEBUG] get_content: https://www.youtube.com/api/timedtext?signature=D289F1EA9D2BD14113CBF7D5A866E1F41F09B6F0.527A6B64245AF6CDF6EF3A0945843CD786887279&asr_langs=ko%2Cde%2Cnl%2Cja%2Cen%2Cpt%2Cit%2Ces%2Cfr%2Cru&sparams=asr_langs%2Ccaps%2Cv%2Cexpire&caps=asr&hl=en_US&key=yttt1&v=BEULybZnLO8&expire=1469992619&lang=zh-CN
[DEBUG] get_content: https://www.youtube.com/api/timedtext?signature=D289F1EA9D2BD14113CBF7D5A866E1F41F09B6F0.527A6B64245AF6CDF6EF3A0945843CD786887279&asr_langs=ko%2Cde%2Cnl%2Cja%2Cen%2Cpt%2Cit%2Ces%2Cfr%2Cru&sparams=asr_langs%2Ccaps%2Cv%2Cexpire&caps=asr&hl=en_US&key=yttt1&v=BEULybZnLO8&expire=1469992619&lang=zh-TW
[DEBUG] get_content: https://www.youtube.com/api/timedtext?signature=D289F1EA9D2BD14113CBF7D5A866E1F41F09B6F0.527A6B64245AF6CDF6EF3A0945843CD786887279&asr_langs=ko%2Cde%2Cnl%2Cja%2Cen%2Cpt%2Cit%2Ces%2Cfr%2Cru&sparams=asr_langs%2Ccaps%2Cv%2Cexpire&caps=asr&hl=en_US&key=yttt1&v=BEULybZnLO8&expire=1469992619&lang=en
[DEBUG] get_content: https://www.youtube.com/api/timedtext?signature=D289F1EA9D2BD14113CBF7D5A866E1F41F09B6F0.527A6B64245AF6CDF6EF3A0945843CD786887279&asr_langs=ko%2Cde%2Cnl%2Cja%2Cen%2Cpt%2Cit%2Ces%2Cfr%2Cru&sparams=asr_langs%2Ccaps%2Cv%2Cexpire&caps=asr&hl=en_US&key=yttt1&v=BEULybZnLO8&expire=1469992619&lang=ja
[DEBUG] get_content: https://s.ytimg.com/yts/jsbin/player-en_US-vfld7sVQ3/base.js
site:                YouTube
stream:
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          62.3 MiB (65298250 bytes)
    # download-with: you-get --itag=22 [URL]

you-get: [error] oops, the current environment does not seem to support Unicode.
you-get: please set it to a UTF-8-aware locale first,
you-get: so as to save the video (with some Unicode characters) correctly.
you-get: you can do it like this:
you-get:     (Windows)    % chcp 65001
you-get:     (Linux)      $ LC_CTYPE=en_US.UTF-8
-----------------------------------------------------------
这个如何解决？（文件名为日文）是否已经有例子？
PS:
我之前在另外一台win7上发现个很奇怪的现象，you-get的下载超过视频的总大小，还在继续下，
99.9% (300MB/112.2MB) ，当时没有查看DEBUG，只记得大概是这样情况！
谢谢！

**Comment by cnbeining** [comment]
请查看Wiki。

**Comment by zhumingyu** [comment]
@cnbeining 如果是fedora，那么如何进行修改？thks
下载地址形式:
ftp://ygdy8:ygdy8@y153.dydytt.net:9115/[阳光电影www.ygdy8.com].X战警：天启.BD.720p.中英双字幕.rmvb

**Comment by cnbeining** [comment]
请查看Wiki。

而且这玩意就拿迅雷离线或者百度云挂aria2吧。。。。。。。。。。

**Comment by zhumingyu** [comment]
OK,这是我的~/.bashrc文件中添加的内容并已source ~/.bashrc：
export PATH="/home/zjhxmjl/Documents/you-get:$PATH"
只想弄个明白，thks
