### ISSUE TITLE
最近下载AcFun的视频，一直报错“sign参数错误”

### ISSUE THREAD

**Issue by makelove** [soimort/you-get#1322]
you-get  -V
you-get: version 0.4.486

you-get --debug http://www.acfun.tv/v/ac2008708
[DEBUG] get_content: http://api.aixifan.com/plays/2364336
[DEBUG] get_content: https://api.youku.com/players/custom.json?client_id=908a519d032263f8&video_id=CMjc0NDAw
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8&vid=CMjc0NDAw&ct=85&sign=
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8&vid=CMjc0NDAw&ct=86&sign=
you-get: [Failed] sign参数错误

不知道为什么？
下载其他网站，正常。

**Comment by cnbeining** [comment]
I will look into this issue.

2016年7月31日星期日，No War <notifications@github.com> 写道：

**Comment by lamlam123tld3** [comment]
youku has modified its api
https://api.youku.com/players/custom.json?client_id=908a519d032263f8&video_id=$sourceId&embsig=$encode
in which sourceid and encode could be obtain through
http://www.acfun.tv/video/getVideo.aspx?id=$vid

**Comment by cnbeining** [comment]
Didn't I patch it?

2016年7月31日星期日，lamlam123tld3 <notifications@github.com> 写道：

**Comment by cnbeining** [comment]
@soimort-bot Please kindly test this link: http://www.acfun.tv/v/ac2008708

**Comment by cnbeining** [comment]
请升级到Github的最新版。
