### ISSUE TITLE
腾讯视频加载cookies.sqlite后仍然只能下载5分钟试看片

### ISSUE THREAD

**Issue by gameclamp** [soimort/you-get#1326]
已登录VIP，网页可以观看全片，在you-get使用了-c加载火狐的cookies.sqlite文件，但是VIP观看视频仍然只能下载5分钟片段，是还不支持吗？
测试视频：http://v.qq.com/cover/z/zs0no2mkjjunzem.html

**Comment by rosynirvana** [comment]
outdated
