### ISSUE TITLE
iqiyi-error

### ISSUE THREAD

**Issue by hobmgcode** [soimort/you-get#1331]
C:\Users\hhh>you-get -i http://www.iqiyi.com/v_19rrmcmsyw.html?vfm=2008_aldbd
site:                爱奇艺 (Iqiyi)
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=LD [URL]C:\Users\hhh>you-get -i http://www.iqiyi.com/v_19rrmcmsyw.html?vfm=2008_aldbd
site:                爱奇艺 (Iqiyi)
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=LD [URL]

**Comment by soimort** [comment]
See #1252.
