### ISSUE TITLE
youku 加密视频

### ISSUE THREAD

**Issue by liuyug** [soimort/you-get#1334]
优酷加密视频，you-get 能否给出下载 title 和 url？

现在直接是一大堆 Exception stack，很不友好

**Comment by soimort** [comment]
> 现在直接是一大堆 Exception stack，很不友好

请说得更具体些。

**Comment by sky7987** [comment]
youku加密视频怎么输入密码

**Comment by rosynirvana** [comment]
没测试链接可用，所以patch里去掉了

**Comment by soimort** [comment]
#2133
