### ISSUE TITLE
douyutv又看不了了 >_>

### ISSUE THREAD

**Issue by kevinbakbak** [soimort/you-get#1336]
```
you-get --debug http://www.douyu.com/dushuren
[DEBUG] get_content: http://www.douyu.com/dushuren
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=319538
Site:       douyu.com
Title:      誓约：浪一次胖一斤！
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://hdl3a.douyucdn.cn/live/319538rDG2ZRgsi7.flv?wsAuth=51932025c41736cb65ec5b9a7e08faa0&token=web-0-319538-97af1b19cbe3f89541c659984c55135d&logo=0&expire=0 -c copy -bsf:a aac_adtstoasc 誓约：浪一次胖一斤！.flv
ffmpeg version 3.1.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 6.1.1 (GCC) 20160707
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-netcdf --enable-shared --enable-version3 --enable-x11grab
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
[flv @ 0x55feb3a699e0] audio stream discovered after head already parsed
[flv @ 0x55feb3a699e0] video stream discovered after head already parsed
Input #0, flv, from 'http://hdl3a.douyucdn.cn/live/319538rDG2ZRgsi7.flv?wsAuth=51932025c41736cb65ec5b9a7e08faa0&token=web-0-319538-97af1b19cbe3f89541c659984c55135d&logo=0&expire=0':
  Metadata:
    fileSize        : 0
    audiochannels   : 2
    encoder         : Open Broadcaster Software v0.625b
  Duration: 00:00:00.00, start: 0.014000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp
    Stream #0:1: Video: h264 (High), yuv420p(tv, bt709/bt709/iec61966-2-1), 1920x1080, 25 fps, 25 tbr, 1k tbn, 2k tbc
[flv @ 0x55feb3bb1fe0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
    Last message repeated 1 times
Output #0, flv, to '誓约：浪一次胖一斤！.flv':
  Metadata:
    fileSize        : 0
    audiochannels   : 2
    encoder         : Lavf57.41.100
    Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuv420p(tv, bt709/bt709/iec61966-2-1), 1920x1080, q=2-31, 25 fps, 25 tbr, 1k tbn, 1k tbc
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 48000 Hz, stereo
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   14 fps=0.0 q=-1.0 size=     320kB time=00:00:00.51 bitrate=5129.2kbits/s frame=   26 fps= 26 q=-1.0 size=     442kB time=00:00:01.04 bitrate=3468.7kbits/s frame=   39 fps= 26 q=-1.0 size=     598kB time=00:00:01.53 bitrate=3189.6kbits/s frame=   52 fps= 26 q=-1.0 size=     781kB time=00:00:02.02 bitrate=3157.3kbits/s frame=   64 fps= 24 q=-1.0 size=    1058kB time=00:00:02.53 bitrate=3413.8kbits/s frame=   75 fps= 24 q=-1.0 size=    1178kB time=00:00:02.98 bitrate=3229.8kbits/s frame=   86 fps= 23 q=-1.0 size=    1320kB time=00:00:03.41 bitrate=3167.9kbits/s frame=   95 fps= 21 q=-1.0 size=    1561kB time=00:00:03.77 bitrate=3387.1kbits/s frame=  110 fps= 22 q=-1.0 size=    1738kB time=00:00:04.37 bitrate=3255.0kbits/s frame=  121 fps= 22 q=-1.0 size=    1870kB time=00:00:04.82 bitrate=3177.5kbits/s frame=  129 fps= 21 q=-1.0 size=    1976kB time=00:00:05.14 bitrate=3149.5kbits/s frame=  137 fps= 19 q=-1.0 size=    2099kB time=00:00:05.46 bitrate=3148.8kbits/s frame=  144 fps= 19 q=-1.0 size=    2220kB time=00:00:05.73 bitrate=3169.4kbits/s frame=  150 fps= 18 q=-1.0 size=    2305kB time=00:00:05.97 bitrate=3161.1kbits/s frame=  157 fps= 18 q=-1.0 size=    2406kB time=00:00:06.25 bitrate=3152.8kbits/s frame=  164 fps= 17 q=-1.0 size=    2513kB time=00:00:06.52 bitrate=3153.9kbits/s frame=  170 fps= 17 q=-1.0 size=    2607kB time=00:00:06.78 bitrate=3148.2kbits/s frame=  174 fps= 16 q=-1.0 size=    2666kB time=00:00:06.95 bitrate=3140.4kbits/s frame=  179 fps= 16 q=-1.0 size=    2759kB time=00:00:07.14 bitrate=3162.3kbits/s frame=  183 fps= 16 q=-1.0 size=    2819kB time=00:00:07.29 bitrate=3165.1kbits/s frame=  190 fps= 16 q=-1.0 size=    2911kB time=00:00:07.57 bitrate=3148.7kbits/s frame=  193 fps= 15 q=-1.0 size=    2957kB time=00:00:07.72 bitrate=3136.6kbits/s frame=  199 fps= 15 q=-1.0 size=    3062kB time=00:00:07.93 bitrate=3161.0kbits/s frame=  205 fps= 15 q=-1.0 size=    3147kB time=00:00:08.17 bitrate=3154.9kbits/s frame=  209 fps= 15 q=-1.0 size=    3217kB time=00:00:08.34 bitrate=3159.6kbits/s frame=  216 fps= 14 q=-1.0 size=    3321kB time=00:00:08.61 bitrate=3156.5kbits/s frame=  223 fps= 14 q=-1.0 size=    3417kB time=00:00:08.89 bitrate=3147.4kbits/s frame=  228 fps= 14 q=-1.0 size=    3508kB time=00:00:09.08 bitrate=3162.2kbits/s frame=  232 fps= 14 q=-1.0 size=    3572kB time=00:00:09.25 bitrate=3160.7kbits/s frame=  239 fps= 14 q=-1.0 size=    3663kB time=00:00:09.53 bitrate=3146.6kbits/s frame=  244 fps= 14 q=-1.0 size=    3741kB time=00:00:09.72 bitrate=3151.0kbits/s frame=  246 fps= 13 q=-1.0 size=    3816kB time=00:00:09.81 bitrate=3185.8kbits/s frame=  251 fps= 13 q=-1.0 size=    3968kB time=00:00:10.02 bitrate=3241.6kbits/s ^Xframe=  262 fps= 13 q=-1.0 size=    4090kB time=00:00:10.45 bitrate=3205.1kbits/frame=  275 fps= 14 q=-1.0 size=    4213kB time=00:00:10.98 bitrate=3141.6kbits/s frame=  284 fps= 13 q=-1.0 size=    4357kB time=00:00:11.32 bitrate=3151.4kbits/s frame=  296 fps= 14 q=-1.0 size=    4550kB time=00:00:11.81 bitrate=3153.5kbits/s frame=  307 fps= 14 q=-1.0 size=    4705kB time=00:00:12.26 bitrate=3141.7kbits/s ^Carchgay ~ $ frame=  308 fps= 14 q=-1.0 Lsize=    4735kB time=00:00:12.26 bitrate=3161.9kbits/s speed=0.547x    
video:4527kB audio:192kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.339240%
Exiting normally, received signal 2.
^C

```
uname -a
Linux archsb 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux

you-get -V
you-get: version 0.4.523, a tiny downloader that scrapes the web.

> [舔 :icecream:!]

**Comment by steven7851** [comment]
我看2个LOG都是正常下载，可以具体形容一下你的问题吗？

**Comment by incharges** [comment]
參數(自訂輸出檔名) -o,參數(指定輸出目錄) -O 無效, 即使自行指定輸出檔名或輸出資料夾
you-get仍舊會預設抓取斗鱼房間號標題做為輸出檔名且輸出目錄仍為you-get.exe所在目錄

**Comment by steven7851** [comment]
ffmpeg processor don't support -o and -O options, need someome to update.

**Comment by incharges** [comment]
明白了,真的非常感謝更新,you-get應該是目前唯一個可以直接錄製斗鱼串流的程式
原來的"斗鱼TV小助手"和"youtube-dl"目前都還是沒有更新

因為無法使用-o,-O,目前的替代方法是寫一個批次檔自動改名,不然一旦串流斷了重連就會覆寫先前錄製的檔案

**Comment by cnbeining** [comment]
@incharges @steven7851 Give me more details please? Like detailed log?

@soimort I will look into to this.

**Comment by cnbeining** [comment]
I see where the problem comes from.

Check #1342 .

**Comment by kevinbakbak** [comment]
![2222](https://cloud.githubusercontent.com/assets/13382012/17631676/9d5d499e-60f7-11e6-8d46-f5cfa452a7df.png)

`you-get --debug http://www.douyu.com/315279
[DEBUG] get_content: http://www.douyu.com/315279
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=315279
Site:       douyu.com
Title:      龙拾柒盲僧野区教学
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://hdl1a.douyucdn.cn/live/315279rsNdpwiS4k.flv?wsAuth=03ea4476d02e077d2c3f7412634bc679&token=web-0-315279-17c7040202f54d4bd6462f2f67dab0cc&logo=0&expire=0 -c copy -bsf:a aac_adtstoasc 龙拾柒盲僧野区教学.flv
ffmpeg version 3.1.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 6.1.1 (GCC) 20160802
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-netcdf --enable-shared --enable-version3 --enable-x11grab
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
[flv @ 0x5631dd16f9e0] audio stream discovered after head already parsed
[flv @ 0x5631dd16f9e0] video stream discovered after head already parsed
Input #0, flv, from 'http://hdl1a.douyucdn.cn/live/315279rsNdpwiS4k.flv?wsAuth=03ea4476d02e077d2c3f7412634bc679&token=web-0-315279-17c7040202f54d4bd6462f2f67dab0cc&logo=0&expire=0':
  Metadata:
    fileSize        : 0
    audiochannels   : 2
    encoder         : Open Broadcaster Software v0.658b
  Duration: 00:00:00.00, start: 0.015000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp
    Stream #0:1: Video: h264 (High), yuv420p(tv, bt709/bt709/iec61966-2-1), 1920x1080, 30.30 fps, 30 tbr, 1k tbn, 60 tbc
[flv @ 0x5631dd28c480] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
    Last message repeated 1 times
Output #0, flv, to '龙拾柒盲僧野区教学.flv':
  Metadata:
    fileSize        : 0
    audiochannels   : 2
    encoder         : Lavf57.41.100
    Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuv420p(tv, bt709/bt709/iec61966-2-1), 1920x1080, q=2-31, 30.30 fps, 30 tbr, 1k tbn, 1k tbc
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 48000 Hz, stereo
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   16 fps=0.0 q=-1.0 size=     134kB time=00:00:00.53 bitrate=2052.2kbits/s frame=   32 fps= 32 q=-1.0 size=     257kB time=00:00:01.02 bitrate=2055.2kbits/s frame=   46 fps= 31 q=-1.0 size=     318kB time=00:00:01.53 bitrate=1698.4kbits/s frame=   54 fps= 20 q=-1.0 size=     386kB time=00:00:01.79 bitrate=1763.1kbits/s frame=   63 fps= 19 q=-1.0 size=     449kB time=00:00:02.09 bitrate=1757.1kbits/s frame=   72 fps= 19 q=-1.0 size=     500kB time=00:00:02.38 bitrate=1714.0kbits/s frame=   79 fps= 16 q=-1.0 size=     542kB time=00:00:02.62 bitrate=1693.5kbits/s frame=   86 fps= 16 q=-1.0 size=     577kB time=00:00:02.85 bitrate=1652.1kbits/s 1frame=   87 fps= 15 q=-1.0 size=     591kB time=00:00:02.88 bitrate=1682.4kbits/sframe=   92 fps= 14 q=-1.0 size=     623kB time=00:00:03.05 bitrate=1673.9kbits/s frame=   95 fps= 14 q=-1.0 size=     646kB time=00:00:03.15 bitrate=1677.5kbits/s 1frame=   99 fps= 12 q=-1.0 size=     674kB time=00:00:03.28 bitrate=1680.8kbits/sframe=  107 fps= 12 q=-1.0 size=     736kB time=00:00:03.54 bitrate=1703.2kbits/s frame=  116 fps= 12 q=-1.0 size=     800kB time=00:00:03.84 bitrate=1707.3kbits/s frame=  128 fps= 13 q=-1.0 size=     881kB time=00:00:04.24 bitrate=1700.7kbits/s ^Cframe=  139 fps= 14 q=-1.0 Lsize=     955kB time=00:00:04.58 bitrate=1705.1kbits/s speed=0.447x    
video:876kB audio:72kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.709941%
Exiting normally, received signal 2.
`
调用不了播放器，貌似在录制了已经？。。我只想安静的看个直播=。=

**Comment by soimort** [comment]
I'm not sure if `ffmpeg_play_stream` was properly working, and the douyu extractor raises an error if `-u` option is used:

```
$ you-get -u http://www.douyu.com/757878 
[DEBUG] get_content: http://www.douyu.com/757878
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=757878
Site:       douyu.com
Title:      Bblythe艺的直播间
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Real URL:
['http://hdl3.douyucdn.cn/live/757878r5hacRyCzz.flv?wsAuth=828abbc5b88f2facabfe3a05e000b829&token=web-0-757878-1e3613d65c8947e0f008878558039198&logo=0&expire=0']

you-get: version 0.4.529, a tiny downloader that scrapes the web.
you-get: ['http://www.douyu.com/757878']
Traceback (most recent call last):
  File "/home/soimort/Projects/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1332, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1245, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1061, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1325, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/extractors/douyutv.py", line 52, in douyutv_download
    download_url_ffmpeg(real_url, title, 'flv', None, output_dir = output_dir, merge = merge)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 908, in download_url_ffmpeg
    if params.get("-y",False): #None or unset ->False
AttributeError: 'NoneType' object has no attribute 'get'
```

So my question is: why not just `vlc [URL]`, instead of `ffmpeg ... [URL] | vlc -`? @cnbeining

**Comment by cnbeining** [comment]
Honestly speaking: I don't know.

I copied the format from rtmpdump. That's it....

2016年8月13日星期六，Mort Yao <notifications@github.com> 写道：

**Comment by soimort** [comment]
`rtmpdump` writes data to stdout when no file name specified; `ffmpeg` doesn't work that way. It's not necessary to have `ffmpeg` handle the stream (most players have good support for flv or m3u steams already).

(A little off-topic) I don't know about the relation between these two projects. The homepage of `rtmpdump` is hosted on MPlayer's server, but their git repository is with FFmpeg. Should the functionality provided by `rtmpdump` be fully taken over by `ffmpeg` now?

**Comment by cnbeining** [comment]
You are right: it is not necessary to use ```ffmpeg``` or ```rtmpdump``` when **playing** the links.

And,

from https://rtmpdump.mplayerhq.hu/ ,

>Projects using librtmp: 
>FFmpeg
>MPlayer (thru ffmpeg)

So ```ffmpeg``` and ```rtmpdump``` are basicly the same thing regarding handling rtmp stream, I suppose...

**Comment by soimort** [comment]
> You are right: it is not necessary to use ffmpeg or rtmpdump when playing the links.

`rtmpdump` is still needed for playing since RTMP is a proprietary protocol not widely supported by all players. (more or less due to legal concerns. MPlayer, mpv and VLC do support RTMP, though.)

**Comment by lamlam123tld3** [comment]
i use curl to dump http stream
