### ISSUE TITLE
[CNTV] 下载视频后无合并过程

### ISSUE THREAD

**Issue by zzwaker** [soimort/you-get#1337]
CNTV 在下载后，视频没有合并, 直接退出.

$ you-get -V
you-get: version 0.4.523, a tiny downloader that scrapes the web.

测试地址:
http://tv.cctv.com/2016/07/31/VIDErisrERshXQuaJdbLBy4p160731.shtml

辛苦了，谢谢！

**Comment by soimort** [comment]
See the discussion in #767.
