### ISSUE TITLE
bilibili api changed

### ISSUE THREAD

**Issue by lamlam123tld3** [soimort/you-get#1340]
date: 160810
site: bilibili
issue: api changed

now, when requesting http://interface.bilibili.com/playurl?appkey=f3bb208b3d081dc8&cid=$cid
quality will by default set to 2 i.e. hdmp4

in the old day it was by default set to be the highest quality (flv)

so, quality need to be explicitly set to 4 in the url query in order to retrieve the highest quality

i.e. http://interface.bilibili.com/playurl?appkey=f3bb208b3d081dc8&quality=4&cid=$cid

example:

**[http://interface.bilibili.com/playurl?appkey=f3bb208b3d081dc8&otype=json&cid=7926898](url)**
{"from":"local","result":"suee","format":"hdmp4","timelength":1457296,"accept_format":"mp4,hdmp4,flv","accept_quality":[3,2,1],"seek_param":"start","seek_type":"second","durl":[{"order":1,"length":1457296,"size":243744002,"url":"http://ws.acgvideo.com/9/75/7926898-1hd.mp4?wsTime=1470841945&wsSecret2=b22b25a246c271e10519bf528f5d8437&oi=3742495673","backup_url":["http://ws.acgvideo.com/9/75/7926898-1.flv?wsTime=1470841945&wsSecret2=f5b77d113017c8da38ea51d1da31350c&oi=3742495673","http://ws.acgvideo.com/9/75/7926898-1.mp4?wsTime=1470841945&wsSecret2=9245f1b515aad61b103135288db91ce1&oi=3742495673"]}]}

**[http://interface.bilibili.com/playurl?appkey=f3bb208b3d081dc8&otype=json&cid=7926898&quality=4](url)**
{"from":"local","result":"suee","format":"flv","timelength":1456814,"accept_format":"mp4,hdmp4,flv","accept_quality":[3,2,1],"seek_param":"start","seek_type":"offset","durl":[{"order":1,"length":394712,"size":149946541,"url":"http://ws.acgvideo.com/9/75/7926898-1.flv?wsTime=1470841982&wsSecret2=dd90a05810c9c40cf72854abad727a29&oi=3742495673","backup_url":["http://ws.acgvideo.com/9/75/7926898-1hd.mp4?wsTime=1470841982&wsSecret2=ba8c84350c360ae5f13e6da2ab0bc68b&oi=3742495673","http://ws.acgvideo.com/9/75/7926898-1.mp4?wsTime=1470841982&wsSecret2=d597a47af9a9ac834ba5c3e100f6b854&oi=3742495673"]},{"order":2,"length":343979,"size":38222694,"url":"http://ws.acgvideo.com/9/75/7926898-2.flv?wsTime=1470841982&wsSecret2=cec78d235ca6096b2a87ea5409f18c72&oi=3742495673","backup_url":[]},{"order":3,"length":346411,"size":46602815,"url":"http://ws.acgvideo.com/9/75/7926898-3.flv?wsTime=1470841982&wsSecret2=c56a9740efe270a29aa00f9e190a69d7&oi=3742495673","backup_url":[]},{"order":4,"length":371712,"size":50239606,"url":"http://ws.acgvideo.com/9/75/7926898-4.flv?wsTime=1470841982&wsSecret2=2cfcbb0adcc8173ed02485a5e93470ae&oi=3742495673","backup_url":[]}]}

**Comment by cnbeining** [comment]
I am thinking they are REALLY getting ready to make the huge turnover to HTML5 player instead of the old Flash one, and I suppose the idea of remuxing FLV stream within browser with Media API is not working or just got abandoned. 

For later contributors who wants to know a little bit of the history,

- the ```quality=4``` came from the age when they were hotlinking from Youku.
- The reason why we did not explicitly set the quality is in the past, 
  - 0 could be the highest quality
  - 4 could be just not exist(for Sina)

I would like to see more test being conducted worldwide(i.e., both within and out of Mainland China) before we make a PR and merge it in.

@lamlam123tld3 many thanks.

**Comment by nuomi1** [comment]
For http://www.bilibili.com/video/av5767119/, bilibili supports four format such as mp4, hdmp4, flv and hdflv2.
The default format returns hdflv2 which you-get can't identify.

```
yg -di http://www.bilibili.com/video/av5767119/
[DEBUG] get_content: http://www.bilibili.com/video/av5767119/
[DEBUG] get_content: http://interface.bilibili.com/playurl?appkey=f3bb208b3d081dc8&cid=9363411
Site:       bilibili.com
Title:      【7月】美男高校地球防卫部LOVE!LOVE! 06
Type:       Unknown type (None)
Size:       467.52 MiB (490229417 Bytes)
```

**Comment by bjlewo** [comment]
Now, the appkey f3bb208b3d081dc8 is invalid， the server return:
{"code":-5003,"result":"checksum error"}

**Comment by lamlam123tld3** [comment]
@bjlewo you are right
api changed
it requires checksum now...

**Comment by cnbeining** [comment]
We have to work on the player.

https://gist.github.com/cnbeining/695caa547dd3b0a6b4d62676492383e2

**Comment by soimort** [comment]
The obfuscated code for generating the 128-bit sign is located at Line 512 of http://static.hdslb.com/player/js/bilibiliPlayer.min.js, which is 44k compressed in total. I don't see how one could reverse this algorithm without a daunting amount of human labor.

**Comment by lamlam123tld3** [comment]
someone has already dug out the hash method, you may take a look on that

**Comment by cnbeining** [comment]
@lamlam123tld3 details?

**Comment by lamlam123tld3** [comment]
@cnbeining 
https://github.com/jijiwuming/bilibilidownload

**Comment by cnbeining** [comment]
thx.

Will look into that later.

**Comment by lamlam123tld3** [comment]
source
https://www.blackglory.me/bilibili-video-source-get/

**Comment by lamlam123tld3** [comment]
it seems that this method may not be the same as using in both the flash player and html5 player

**Comment by lamlam123tld3** [comment]
all other query params must be added before the sign param and need to be hashed

**Comment by cnbeining** [comment]
https://www.blackglory.me/bilibili-video-source-get/ <https://www.blackglory.me/bilibili-video-source-get/>

was using my APPKEY.

Never mind, I will dig the HTML5 player later.

**Comment by cnbeining** [comment]
@lamlam123tld3 Flash is not the same as HTML5. Flash uses only one key attached at the end, which can be dumped in the ram if you want to do so.

**Comment by lamlam123tld3** [comment]
@cnbeining your code in two years ago still working hehehe

**Comment by soimort** [comment]
> https://www.blackglory.me/bilibili-video-source-get/ <https://www.blackglory.me/bilibili-video-source-get/>
>
> was using my APPKEY.

I thought your key was banned by Bilibili a long time ago. No?
https://github.com/soimort/you-get/commit/0ac3bdd5b3139976502a79ef2cf684c92420e9cb#diff-d47ee45cc2b148642e4738ea66dcfb71

If someone could decompile the appkey and appsecret from the official APK, that would be the best.

**Comment by cnbeining** [comment]
YES that was banned. In fact AFAIK all 3rd party keys are banned for now.

For the APK:

- Everyone knows the appkey.
- Appsecret is loaded dynamically by a remote lua script, which contains encrypted appsecret. I am not publishing this.

**Comment by soimort** [comment]
HTML5 JS player is much, much harder to deal with, and they could change the method (or the encrypted key) any time they want. I believe using the same set of keys as the official APK is the most durable way to resolve this issue.

**Comment by cnbeining** [comment]
@soimort APK is no easier than HTML5 JS since the KEY is loaded every time when the programme runs. It is not something like they have to do a version upgrade to patch the new key: they can do that on the fly...

**Comment by soimort** [comment]
> @soimort APK is no easier than HTML5 JS since the KEY is loaded every time when the programme runs.

Based on [this article I came across earlier](http://www.jianshu.com/p/5087346d8e93), the secretkey was directly encoded in a shared library from which you can disassemble. Disclaimer: didn't have time to try this myself. And I don't know if the described method is still valid for now (2016-08-18 or after).

It's not all obvious how to find out that secretkey from the HTML5 player at my first glance (although one don't have to decompile anything indeed, the code is already there.)

**Comment by cnbeining** [comment]
That was back in January.

The way of storing secretkey is changed for now.

**Comment by ivanhu42** [comment]
I use the html5 player of bilibili.com to get the video source url. however, I don't know python. and I'm not able to contribute to you-get for now. so I just code some js and make it a javascript bookmark. it will add three links on the right of '稿件投诉'. besides, it doesn't need an appkey or a secretkey. hope it helps.

[ivanhu42/BiliMark](https://github.com/ivanhu42/BiliMark)

**Comment by soimort** [comment]
The mobile HTML5 API seems available for only low-quality format (360p), so that is just a temporarily (and suboptimal) solution. However, it's still better than nothing.

Thanks, @ivanhu42 !

**Comment by weituotian** [comment]
@cnbeining have you finish diging the  HTML5 player later?
so may i know  how the player js do that?

**Comment by cnbeining** [comment]
The only thing I can confirm is the app secret is within the ram as
plaintext.



weituotian <notifications@github.com>于2017年4月28日 周五上午12:00写道：

**Comment by rosynirvana** [comment]
@weituotian 
checksum algo should be impled in C and then interpreted to emscripten, about 5000 thousand lines of js code, which is definitely not for avg human beings. 

Emscripten code describes a vm which has its own data seg and text seg with more than 100 opcodes. checksum algo and sec are hidden in the hard coded data seg and text seg.

**Comment by weituotian** [comment]
@cnbeining @rosynirvana 
how can the programers in bilibili wrote this code ? Are they all genius?

**Comment by rosynirvana** [comment]
@weituotian They did not write the js code directly. The C code they writed, compiled to LLVM code firstly, then interpreted to emscripten.

**Comment by weituotian** [comment]
@rosynirvana 
i know a people @gdkchan .
she wrote a c# [script ](https://gist.github.com/gdkchan/fed0d38eeef241e7d3d243c9e5b788e3)to generate the sign

the most impotant part in this script was
```
        const string AppKey = "6f90a59ac58a4123";
        const string BiliKey = "0bfd84cc3940035173f35e6777508326";
```

the appkey we can easily find in url params , 
but the secretkey is hard to find in js.

**Comment by weituotian** [comment]
@soimort 

> The obfuscated code for generating the 128-bit sign is located at Line 512 of http://static.hdslb.com/player/js/bilibiliPlayer.min.js, which is 44k compressed in total. I don't see how one could reverse this algorithm without a daunting amount of human labor.

where ? does it below ?

how could you find that?

where to see the secretkey?
```
function J(a, b, c, f) {
                    var g, h;
                    "number" === typeof a ? (g = !0,
                    h = a) : (g = !1,
                    h = a.length);
                    var k = "string" === typeof b ? b : null ;
                    c = 4 == c ? f : [ua, w.A, w.N, w.p][void 0 === c ? 2 : c](Math.max(h, k ? 1 : b.length));
                    if (g) {
                        f = c;
                        assert(0 == (c & 3));
                        for (a = c + (h & -4); f < a; f += 4)
                            I[f >> 2] = 0;
                        for (a = c + h; f < a; )
                            G[f++ >> 0] = 0;
                        return c
```

**Comment by rosynirvana** [comment]
@weituotian That post was on 19 Aug 2016, more than 8 month ago.
As I said above, avg human could not *read* the emscripten code, let alone dig the sec from it.
If you really want to get the sec directly, try to play with it in the chrome dev tools. Choose breakpoint wisely and after plenty time & energy were consumed you would get it.

**Comment by weituotian** [comment]
@rosynirvana 
now i am working in this step

my idea is to change the Video definition, and then the playerurl request will be fire,
in this process, someting to gen the sign must be called.

using chrome developer tools to format the playerjs below in 5604

![qq 20170428184519](https://cloud.githubusercontent.com/assets/7270968/25526391/eb54d684-2c45-11e7-8fbb-391119d683f0.jpg)

and Jb:a is the video definition

and then it come into a vm script,

then i feel hard to know what happen,

may you help me?

**Comment by rosynirvana** [comment]
You can get the calling stack from the devtool. For bilibili the breakpoint must be set a little earlier.

In bilibiliPlayer.min.js two part of code is relevant, the emscripten code and its entry. Make yourself familiar with them. Yep, it's daunting. Code generated by ```eval``` is not critical and I believe they are used to push data into the emscripten vm.

**Comment by weituotian** [comment]
@rosynirvana 

android studio 动态smali调试取到密匙了，看看能不能用?

![q -20170430164047](https://cloud.githubusercontent.com/assets/7270968/25562975/b0097bcc-2dc4-11e7-8af5-6539917773e3.png)


```
appkey=1d8b6e7d45233436&build=501000&keyword=weiii&mobi_app=android&platform=android&ts=1493540815000&type=accurate
6f1005564a4bec56e39bbdaa2896784f
```

**Comment by rosynirvana** [comment]
@weituotian 
搜了一下好像是直播用的key，不知道别的分区认不认

**Comment by weituotian** [comment]
@rosynirvana 

断的是md5函数的smali  
bll.smali
```
appkey=1d8b6e7d45233436&build=501000&mobi_app=android&platform=android&ts=1493569411000
key:1d8b6e7d45233436
secret:560c52ccd288fed045859ed18bffd973
```
![q -20170501003016](https://cloud.githubusercontent.com/assets/7270968/25566068/6b133aa8-2e05-11e7-8221-dca1991e25e4.png)
```
GET http://app.bilibili.com/x/v2/region?appkey=1d8b6e7d45233436&build=501000&mobi_app=android&platform=android&ts=1493567972000&ver=188703795824240229&sign=9e08976b10168a995f0a189284fda126 HTTP/1.1
User-Agent: Mozilla/5.0 BiliDroid/5.1.0 (bbcallen@gmail.com)
Device-ID: Pwc3BzUCMAZkBWRWKlYq
Host: app.bilibili.com
Connection: Keep-Alive
Accept-Encoding: gzip

```
搜索，视频详情都是用这个key，自己也写过md5函数确认过一致。  
这个key我看它是MyApplication初始化的时候就读取so得来的。


然而fidder抓包到视频url用另外一个key播放
fidder截到的是api.bilibili.com/playurl?
然后？

**Comment by rosynirvana** [comment]
@weituotian
还是找key吗？不在apk里的，移动端是动态下载了一些lua文件，key在那些lua里

**Comment by weituotian** [comment]
@rosynirvana 

已经好了，上面发的key是可以用的
之前是参数顺序不对,调整下顺序可以了

附上测试文件，取quality为3的视频
[c#文件](https://gist.github.com/weituotian/83f6a914ae3d221e8b302ca60f8c3009)
