### ISSUE TITLE
error with bilibili

### ISSUE THREAD

**Issue by llconan** [soimort/you-get#1349]
Recently you-get doesn't work with bilibili site.
like this：
d:\Program Files\DAUM\PotPlayer>you-get http://www.bilibili.com/video/av5856558/
Site:       bilibili.com
Title:      奥林匹克运动的悲剧傻缺视频集锦【Part 2】
Type:       Unknown type ()
Size:       0.0 MiB (0 Bytes)

**Comment by llconan** [comment]
you-get: version 0.4.523, a tiny downloader that scrapes the web.

**Comment by nuomi1** [comment]
#1340
