### ISSUE TITLE
话说Libav怎么安装呢？

### ISSUE THREAD

**Issue by wangx2** [soimort/you-get#1352]
Libav这个怎么在debian上安装，搜索了一圈也没找到资料？？？

**Comment by soimort** [comment]
https://libav.org/download/

**Comment by vipzrx** [comment]
你是说在debian下安装libav吗？
我的是jessie x86 已经成功安装了。请说明下你的版本

**Comment by wangx2** [comment]
@vipzrx
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24)
是这个吗？

**Comment by zhangn1985** [comment]
现在debian都是ffmpeg，谁还用libav呀！？
