### ISSUE TITLE
下载腾讯视频时的清晰度问题

### ISSUE THREAD

**Issue by pthreadself** [soimort/you-get#1354]
下载腾讯视频的时候，下载的清晰度是最低的。
http://www.flvurl.cn 这个网站提供解析腾讯视频URL的问题，可以解析出所有清晰度，并提供下载链接。
具体原理各路大神可以分析下，谢谢！

**Comment by sinofool** [comment]
flvurl是服务器端抓取，有可能是模拟播放了一遍。
