### ISSUE TITLE
[Bilibili] Can't download member-only videos

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#1356]
The current method has no access to Bilibili's member-only videos, even with cookies:

```
$ you-get -c ~/.mozilla/firefox/gggfz9xl.default/cookies.sqlite -di http://www.bilibili.com/video/av5891902/
[DEBUG] get_content: http://www.bilibili.com/video/av5891902/
[DEBUG] get_content: http://www.bilibili.com/m/html5?aid=5891902&page=1
you-get: version 0.4.532, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av5891902/']
Traceback (most recent call last):
  File "/home/soimort/Projects/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1331, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1244, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1324, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/extractors/bilibili.py", line 69, in bilibili_download
    src = info['src']
KeyError: 'src'
```

**Comment by ivanhu42** [comment]
fyi, this video (av5891902) has been removed from the site

**Comment by soimort** [comment]
@ivanhu42 The video has not been removed, but it needs login with Bilibili membership; Although it is possible to bypass this limitation by directly accessing http://static.hdslb.com/play.swf?cid=9567035&aid=5891902 (!)

**Comment by soimort** [comment]
Not sure if it's CDN related, but the Flash player could not access the video anymore _(-ω-`_)⌒)_

http://interface.bilibili.com/playurl?cid=9567035&appkey=6f90a59ac58a4123&otype=json&type=mp4&quality=2&sign=ac858bed50601bf3404282b9160d0803

**Comment by lamlam123tld3** [comment]
is there any api to get the cid by aid only

**Comment by soimort** [comment]
> is there any api to get the cid by aid only without request to the main site

http://www.bilibili.com/widget/getPageList?aid=5912519

Member-only videos require your cookie, otherwise it shows a 404 page:
http://www.bilibili.com/widget/getPageList?aid=5891902

**Comment by cnbeining** [comment]
@lamlam123tld YES there do exist one API at 

```'https://api.bilibili.com/view?appkey={APPKEY}&id={vid}&type=xml'.format(APPKEY = '8e9fc618fbd41e28', vid = vid, SECRETKEY = SECRETKEY)```

.

@soimort I am really having a hard time digging their HTML5 JS file. If only they can use their talent at somewhere else such like better video quality or more CDN nodes...

**Comment by soimort** [comment]
> @soimort I am really having a hard time digging their HTML5 JS file.

That is some Emscripten generated code. Shouldn't have wasted your time on it.

**Comment by cnbeining** [comment]
I will try to grab a Windows machine to look into their SWF's ram. Should be able to find something...
