### ISSUE TITLE
下载不了这个凤凰视频

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#1358]
http://v.ifeng.com/gongkaike/sjdjiangtang/201203/b2a540b4-32b6-41d1-ba5f-68552cb05833.shtml

**Comment by soimort** [comment]
@soimort-bot Test this http://v.ifeng.com/gongkaike/sjdjiangtang/201203/b2a540b4-32b6-41d1-ba5f-68552cb05833.shtml

**Comment by soimort** [comment]
以后报 issue 请自带 debug 信息，或者具体描述一下情况。谢谢合作。
