### ISSUE TITLE
在you-get下使用播放器播放在线视频的问题

### ISSUE THREAD

**Issue by zdhtop1** [soimort/you-get#1360]
E:\mpv\mpv-x86_64-20160816>you-get -p mpv http://www.douyu.com/209436
Site:       douyu.com
Title:      Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Playing streaming content with FFmpeg, press 1 to stop recording...
ffmpeg -loglevel quiet -y -re -i http://hdl3.douyucdn.cn/live/209436rdwGcOYmh7.flv?wsAuth=d6ff7257bd027c2a26a1ee7764be4f59&token=web-0-209436-9dbd3e6194f1334b6b76e0a8ac5b4ff5&logo=0&expire=0 -c copy -bsf:a aac_adtstoasc | mpv -

然后就没有然后 就再起了一行

在twitch中也是这样 但是twitch就是直接没反应重新起了一行

**Comment by soimort** [comment]
#1336
