### ISSUE TITLE
about bilibilijj API

### ISSUE THREAD

**Issue by ivanhu42** [soimort/you-get#1367]
is it legally justified to use [API of bilibilijj](http://www.bilibilijj.com/apiword/) in you-get? if so, there may be a way to get the direct link of a video. in js:

```js
let jsdom = require('jsdom')

let getUrl = (url) => {
  jsdom.env({
    url: url,
    done: (err, window) => {
      if(!err) {
        console.log(window.location.href)
      }
    }
  })
}

jsdom.env({
  url: 'http://www.bilibilijj.com/Api/AvToCid/10086',
  done: (err, window) => {
    if(!err) {
      let t = JSON.parse(window.document.getElementsByTagName('body')[0].innerHTML.replace(/\\/, '\\\\'))
      getUrl(t.list[0].Mp4Url)
    }
  }
})
```

**Comment by cnbeining** [comment]
Thanks for your observation.

Unfortunately ```you-get``` is based on the idea that this programme does not to the extract job relying on third party services. Thus I am not going to implement the change in this way.

Thanks again,
