### ISSUE TITLE
一个资源重复下载

### ISSUE THREAD

**Issue by crazw** [soimort/you-get#1369]
我下载一个优酷的资源分片：[you-get "http://223.111.11.105/youku/697771B8EB34782011EB1D69DD/0300800C0057B6EEB9D3BA366E02D44A9B2162-4F4C-2356-ED94-570D0791BCCE.flv"](you-get "http://223.111.11.105/youku/697771B8EB34782011EB1D69DD/0300800C0057B6EEB9D3BA366E02D44A9B2162-4F4C-2356-ED94-570D0791BCCE.flv")

抓包发现下载的**_不止一次_**，详情如下图：

1.  下载过程：
![image](https://cloud.githubusercontent.com/assets/4703608/18001850/68d8794e-6bb7-11e6-8d2d-e54428a92b48.png)

2.  抓包详情：
![image](https://cloud.githubusercontent.com/assets/4703608/18004297/8cc65566-6bc5-11e6-9a0d-16e229d84d8d.png)

3.  Follow详情：
![image](https://cloud.githubusercontent.com/assets/4703608/18004370/10303b7e-6bc6-11e6-8c1d-43df50f79a4d.png)

大家能给点解释吗？或者有什么参数配置一下吗？不胜感激！

**Comment by soimort** [comment]
不是“下载”了5次，是发送了5次 GET requests，实际的下载发生在最后一次：

0. [universal.py#L10](https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/universal.py#L10)
1. [universal.py#L18](https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/universal.py#L18)
2. [universal.py#L87](https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/universal.py#L87)
3. [common.py#L431](https://github.com/soimort/you-get/blob/develop/src/you_get/common.py#L431)
4. [common.py#L475](https://github.com/soimort/you-get/blob/develop/src/you_get/common.py#L475)

当然这里的实现有值得改进的地方。

**Comment by crazw** [comment]
@soimort 恩 谢谢，是5次Get requests，不过我有个疑问 ：有两个大小是53MB，见Follow图中的1和4标示，这是不是相当于下载了两次？

**Comment by soimort** [comment]
@crazw 是的…… 这一步会先把 URL 当作网页下载一遍，如果发现结果不能作为 HTML 解析，就当作 binary 再下载一遍（实际上是多余的）

感谢提醒，已经 fix。

**Comment by crazw** [comment]
@soimort 恩恩  非常感谢👍
