### ISSUE TITLE
[bilibili] 下载到的视频的清晰度较低

### ISSUE THREAD

**Issue by lilydjwg** [soimort/you-get#1371]
Please make sure these boxes are checked before submitting your issue – thank you!

- [*] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [*] Your `you-get` is up-to-date.
- [*] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [*] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [*] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

下载[此视频](http://www.bilibili.com/video/av12999/)。最新版（ 099cd3e1a4b36f64c049dfa828d8b0b9a5c0af1b ）会下载 360p 的视频。而 618a31d433b33c65fd4759501c0ff3be8bf778d6 这个版本的 bilibili.py 却能够下载 720p 的版本（可直接使用旧版本的文件覆盖）。

**Comment by soimort** [comment]
@cnbeining Since when is your key revived? :disappointed_relieved:
