### ISSUE TITLE
爱奇艺不能下载

### ISSUE THREAD

**Issue by mogu1121** [soimort/you-get#1373]
you-get -x http://111.13.136.46:80 --format=TD -d http://www.iqiyi.com/v_19rrm6syj4.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/529370300/7b5d1a0158ded1bbd81f9638c5b53cf4/?t=1472360893351&sc=0bdcd99556f0815dadf25df0cd562578&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               航海王第754集
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrm6syj4.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1331, in main
  File "src\you_get\common.py", line 1239, in script_main
  File "src\you_get\common.py", line 1060, in download_main
  File "src\you_get\common.py", line 1324, in any_download
  File "src\you_get\extractor.py", line 51, in download_by_url
  File "src\you_get\extractors\iqiyi.py", line 203, in download
  File "src\you_get\common.py", line 917, in download_url_ffmpeg
AssertionError: FFmpeg not installed.
you-get returned -1

**Comment by damoguyanzero** [comment]
我这里可以解析。
you-get -i http://www.iqiyi.com/v_19rrm6syj4.html
site:                爱奇艺 (Iqiyi)
title:               航海王第754集
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=LD [URL]

**Comment by mogu1121** [comment]
@damoguyanzero 我也能解析 但是不能下载，我要挂代理

**Comment by xlfjn** [comment]
现在爱奇艺需要ffmpeg才能下载

**Comment by mogu1121** [comment]
怎么做，我是windows 下载的是you-get-0.4.536-win32-full.7z

**Comment by xlfjn** [comment]
去 https://ffmpeg.zeranoe.com/builds/
下载一个已经编译好的ffmpeg (Static/Shared无所谓)，解压到you-get的目录下

**Comment by mogu1121** [comment]
you-get-0.4.536-win32-full.7z 有自带

**Comment by mogu1121** [comment]
![123](https://cloud.githubusercontent.com/assets/21261903/18032491/acf20488-6d38-11e6-986f-afdcfbf21796.gif)
