### ISSUE TITLE
一个资源下载混乱

### ISSUE THREAD

**Issue by crazw** [soimort/you-get#1374]
你好，请问这是什么原因？
我下载时明明指定的是mp4格式，可是他下载的是hd2！
![image](https://cloud.githubusercontent.com/assets/4703608/18032130/a846b172-6d2e-11e6-8c73-554b0590260c.png)

**Comment by soimort** [comment]
请给出视频地址。

**Comment by crazw** [comment]
@soimort 抱歉，当时没有保存，不过今天我重新下载同一个资源时又正常啦！估计是偶然发生的，你可以从上面的截图看出来，后来多次重试那种情况都没有复现！
