### ISSUE TITLE
不支持风行网微电影的下载（非会员）

### ISSUE THREAD

**Issue by as7777071as** [soimort/you-get#1378]
![7a9ig2g q ekh5s bzo](https://cloud.githubusercontent.com/assets/17898853/18048410/8124f1da-6e14-11e6-949f-9b1a5cfdba42.png)

没有任何信息弹出来

**Comment by xlfjn** [comment]
@soimort-bot test http://www.fun.tv/vplay/c-100.s-175.a-451.g-117208

**Comment by soimort** [comment]
See https://github.com/soimort/you-get/issues/1004. Fun.tv support is still broken for now. So even if it prints out something, it's not the actual thing you want.

@soimort-bot please test http://www.fun.tv/vplay/c-100.s-175.a-451.g-117208
