### ISSUE TITLE
优酷列表问题

### ISSUE THREAD

**Issue by dou-bi** [soimort/you-get#1380]
在优酷网下载的视频列表超过18个就会只下18个。。
。可能它的列表分了两部分。。

**Comment by dou-bi** [comment]
@soimort-bot 
example:http://list.youku.com/albumlist/show/id_23464341.html?beta&&spm=0.0.Drama.5~5~H3~A.WlOLUN

**Comment by dou-bi** [comment]
如果正常打开网页。它先显示18个，用鼠标滑轮滚下。其他的才会出现。而已经下载的就是那18个。

**Comment by OwenChia** [comment]
一个临时的解决方案，打开[视频](http://v.youku.com/v_show/id_XODgxMzU3OTQ0.html)页，然后在浏览器控制台执行
```javascript
document.querySelectorAll(".A").forEach(x=>console.log(x.href))
```
把输出保存成文件，然后用 you-get -I 下载。

**Comment by rosynirvana** [comment]
dup #1596
