### ISSUE TITLE
PPTV视频下载失败

### ISSUE THREAD

**Issue by as7777071as** [soimort/you-get#1381]
是算法改了吗？

**Comment by as7777071as** [comment]
![p1 fknk 5l0dbf94iyfe c](https://cloud.githubusercontent.com/assets/17898853/18074479/6a44f204-6e9f-11e6-9b0b-e335e0b98d15.png)

**Comment by xlfjn** [comment]
@soimort-bot test http://v.pptv.com/show/GWCBicvZxe7kcmgI.html

**Comment by as7777071as** [comment]
It spends 3 minutes and download  failed  @soimort-bot 

![pp re9eh 52u b tca7 fm](https://cloud.githubusercontent.com/assets/17898853/18074897/e4435124-6ea2-11e6-9b5d-13a0fa75aec7.png)

**Comment by xlfjn** [comment]
@as7777071as It should be a duplicate of #447. Wireshark shows that the server gives HTTP 403 error.

**Comment by as7777071as** [comment]
I solve it.
just change cff.pptv.com.
for example:
![url](https://cloud.githubusercontent.com/assets/17898853/18079952/d480179a-6ec5-11e6-993a-a73f38fbb08f.png)
change to
![ip](https://cloud.githubusercontent.com/assets/17898853/18079959/e0598074-6ec5-11e6-9531-df2de66e785f.png)
the address is from
![host](https://cloud.githubusercontent.com/assets/17898853/18079964/e9b940c8-6ec5-11e6-8acd-9accb0ddaee4.png)

**Comment by xlfjn** [comment]
@soimort

**Comment by soimort** [comment]
Thanks for solving this long-standing issue! @as7777071as @xlfjn
