### ISSUE TITLE
ffmpeg_concat_flv_to_mp4: "flush" is not available in Python under 3.3

### ISSUE THREAD

**Issue by Cappuccin0** [soimort/you-get#1385]
version: 0.4.597
branch: develop
commit: 44c09c
os: ubuntu 12.04
python ver: 3.2.3
output:
>  youget --debug http://www.bilibili.com/video/av5917934/
[DEBUG] get_content: http://www.bilibili.com/video/av5917934/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=9608503&from=miniplay&player=1&sign=2a55fc8997ab2479c2cd1a3e3ddb5e73
Site:       bilibili.com
Title:      1、第一集：受困孤岛
Type:       Flash video (video/x-flv)
Size:       811.38 MiB (850795270 Bytes)

> Downloading 1、第一集：受困孤岛.flv ...
 100% (811.4/811.4MB) ├████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[10/10]  153 MB/s
you-get: version 0.4.597, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av5917934/']
Traceback (most recent call last):
  File "~/workspace/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "~/workspace/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "~/workspace/you-get/src/you_get/common.py", line 1332, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "~/workspace/you-get/src/you_get/common.py", line 1245, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "~/workspace/you-get/src/you_get/common.py", line 1061, in download_main
    download(url, **kwargs)
  File "~/workspace/you-get/src/you_get/common.py", line 1325, in any_download
    m.download(url, **kwargs)
  File "~/workspace/you-get/src/you_get/extractors/bilibili.py", line 175, in bilibili_download
    info_only=info_only)
  File "~/workspace/you-get/src/you_get/extractors/bilibili.py", line 107, in bilibili_download_by_cid
    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, merge=merge)
  File "~/workspace/you-get/src/you_get/common.py", line 761, in download_urls
    ffmpeg_concat_flv_to_mp4(parts, output_filepath)
  File "~/workspace/you-get/src/you_get/processor/ffmpeg.py", line 114, in ffmpeg_concat_flv_to_mp4
    print('Merging video parts... ', end="", flush=True)
TypeError: 'flush' is an invalid keyword argument for this function

workaround:
> diff --git a/src/you_get/processor/ffmpeg.py b/src/you_get/processor/ffmpeg.py
index c34f43c..7388402 100644
--- a/src/you_get/processor/ffmpeg.py
+++ b/src/you_get/processor/ffmpeg.py
@@ -111,7 +111,7 @@ def ffmpeg_concat_ts_to_mkv(files, output='output.mkv'):
         return False
>
 def ffmpeg_concat_flv_to_mp4(files, output='output.mp4'):
-    print('Merging video parts... ', end="", flush=True)
+    # print('Merging video parts... ', end="", flush=True)
     # Use concat demuxer on FFmpeg >= 1.1
     if FFMPEG == 'ffmpeg' and (FFMPEG_VERSION[0] >= 2 or (FFMPEG_VERSION[0] == 1 and FFMPEG_VERSION[1] >= 1)):
         concat_list = open(output + '.txt', 'w', encoding="utf-8")

也许只是python3的版本太低导致的？

**Comment by cnbeining** [comment]
您说的在理，就是因为Python版本太低了。

然而为什么一定要有这么个flush？

**Comment by Cappuccin0** [comment]
maybe the original idea is just to make sure something been output to console before the merge starts, but the print may break the whole merge/download procedure if python version is under 3.3.

**Comment by soimort** [comment]
Fixed by #1390.
