### ISSUE TITLE
iqiyi下载出错

### ISSUE THREAD

**Issue by yangaowei** [soimort/you-get#1386]
python3 you-get --debug http://www.iqiyi.com/dongman/20130109/4f4d62f0dd6ce862.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/351470/61dfa58e81c34881963e04a62b8a74e8/?t=1472625674959&sc=a1c31732428184d62a7b43eb55dc2af9&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/dongman/20130109/4f4d62f0dd6ce862.html']
Traceback (most recent call last):
    assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video

**Comment by soimort** [comment]
404 error.
