### ISSUE TITLE
YOUGET不支持爱奇艺VIP视频下载方式了吗

### ISSUE THREAD

**Issue by yangfan3333** [soimort/you-get#1388]
爱奇艺VIP导入COOK 也不行了？有什么办法下载爱奇艺VIP视频吗？

**Comment by yangfan3333** [comment]
URL:   http://www.iqiyi.com/v_19rrlywsk4.html

D:\yy>you-get.exe *******  http://www.iqiyi.com/v_19rrlywsk4.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/524548600/8e168c2f0778b800f80
e78a1ebb50529/?t=1472813506732&sc=f04ecd5ef44719006c4b15dfd2ddd0f6&src=76f90cbd9
2f94a2e925d83e8ccd22cb7
you-get: vd: 14 is not handled
you-get: info is {'m3u': 'http://cache.vip.iqiyi.com/m/u/0ae88cc3ffb8248ff448a89
1766c277f/afbe8fd3d73448c9/f3790733a61f505b6250c1f9b3805163/9d7ee27843cb53387d72
e4a7202d3454/1321081700.m3u8?t_sign=0-76f90cbd92f94a2e925d83e8ccd22cb7-524548600
_04022000001000000000_14-1472813494', 'm3utx': 'http://cache.vip.iqiyi.com/m/u/0
ae88cc3ffb8248ff448a891766c277f/afbe8fd3d73448c9/f3790733a61f505b6250c1f9b380516
3/9d7ee27843cb53387d72e4a7202d3454/text/1321081700.m3u8?t_sign=0-76f90cbd92f94a2
e925d83e8ccd22cb7-524548600_04022000001000000000_14-1472813494', 'vd': 14, 'vid'
: '0ae88cc3ffb8248ff448a891766c277f'}
site:                爱奇艺 (Iqiyi)
title:               僵尸世界
stream:
    - format:        4k
      container:     m3u8
      video-profile: 4k
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=4k [URL]

you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrlywsk4.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1331, in main
  File "src\you_get\common.py", line 1244, in script_main
  File "src\you_get\common.py", line 1060, in download_main
  File "src\you_get\common.py", line 1324, in any_download
  File "src\you_get\extractor.py", line 51, in download_by_url
  File "src\you_get\extractors\iqiyi.py", line 203, in download
  File "src\you_get\common.py", line 917, in download_url_ffmpeg
AssertionError: FFmpeg not installed.
you-get returned -1

**Comment by xf1** [comment]
报错是说没ffmpeg，去下个扔同目录，或者在环境变量里的目录。

**Comment by yangfan3333** [comment]
我下载了最新的 you-get-0.4.536-win32-full.7z  解压之后 deps 里面包含了 FFMPEG的呀。

@xf1  你可以下载爱奇艺VIP视频吗。。地址是 http://www.iqiyi.com/v_19rrlywsk4.html 

我导入了COOK 还是不行。。报错 就像上面一样。，

**Comment by yangfan3333** [comment]
URL：http://www.iqiyi.com/v_19rrlx32bc.html



D:\you-get>you-get.exe *****   http://www.iqiyi.com/v_19rrlx32bc.html
you-get: vd: 14 is not handled
you-get: info is {'vid': 'f356882796c131611264084bda686904', 'vd': 14, 'm3utx':
'http://cache.vip.iqiyi.com/m/u/f356882796c131611264084bda686904/afbe8fd3d73448c
9/8fb76109fb0aace7b8ad356f0aa044b2/729f0331a385c37c4d45702fcc4321e4/text/1321081
700.m3u8?t_sign=0-76f90cbd92f94a2e925d83e8ccd22cb7-527610900_0402200000100000000
0_14-1472838322', 'm3u': 'http://cache.vip.iqiyi.com/m/u/f356882796c131611264084
bda686904/afbe8fd3d73448c9/8fb76109fb0aace7b8ad356f0aa044b2/729f0331a385c37c4d45
702fcc4321e4/1321081700.m3u8?t_sign=0-76f90cbd92f94a2e925d83e8ccd22cb7-527610900
_04022000001000000000_14-1472838322'}
site:                爱奇艺 (Iqiyi)
title:               窃肤之爱
stream:
    - format:        4k
      container:     m3u8
      video-profile: 4k
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=4k [URL]

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by xf1** [comment]
我没有下载，只是看你第一个log，下面这个没加debug吧，看不见什么信息。

**Comment by rosynirvana** [comment]
in favor of #2117
