### ISSUE TITLE
乐视网调用播放器播放出错：“[WinError 206] 文件名或扩展名太长”

### ISSUE THREAD

**Issue by silver-zhao** [soimort/you-get#1389]
如题。不管是 MPC-HC 还是 WMPlayer 都有问题。日志如下：

    C:\you-get\you-get.exe -d -p "D:/Program Files/MPC-HC/mpc-hc.exe" http://www.le.com/ptv/vplay/21867033.html
    [DEBUG] get_content: http://www.le.com/ptv/vplay/21867033.html
    [DEBUG] get_content: http://api.letv.com/mms/out/video/playJson?id=21867033&platid=1&splatid=101&format=1&tkey=1323973782&domain=www.letv.com
    Current Video Supports:
            --format 350 <URL>
            --format 720p <URL>
            --format 1300 <URL>
            --format 1000 <URL>
            --format 1080p <URL>
    [DEBUG] get_content: http://play.g3proxy.lecloud.com/vod/v2/MTIxLzQ1LzM1L2xldHYtdXRzLzE0L3Zlcl8wMF8yMi0zMDQ2MjM5NTQtYXZjLTI5ODQ4OTEtYWFjLTEyODAwMS01NTk4MjkyLTIxODY2MTczMTEtZDc1MTc2MDNhNDllZDE1ZDU1MmRmMzAzM2FkNjIxMDYtMTQyMzAxODMyMjY2Ni5tcDQ=?b=3124&mmsid=26643227&tm=1472892443&key=2ea1ba7b2923d80df02b2ca319ca460d&platid=1&splatid=101&playid=0&tss=ios&vtype=52&cvid=1128348871549&payff=0&pip=78295e671486f64c5bd936d64ad0207e&ctv=pc&m3v=1&termid=1&format=1&hwtype=un&ostype=Linux&tag=letv&sign=letv&expect=3&tn=0.6755845507520513&pay=0&iscpn=f9051&rateid=1080p
    [DEBUG] get_content: http://124.14.18.15/121/45/35/letv-uts/14/ver_00_22-304623954-avc-2984891-aac-128001-5598292-2186617311-d7517603a49ed15d552df3033ad62106-1423018322666.m3u8?crypt=58aa7f2e2856&b=3124&nlh=4096&nlt=60&bf=73&p2p=1&video_type=mp4&termid=1&tss=ios&platid=1&splatid=101&its=0&qos=4&fcheck=0&amltag=100&mltag=100&proxy=2081295506,3550610147,2007471084&uid=1883362202.rp&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&ntm=1472910600&nkey=3bd56d26c86e44beba6fca5f3021b1e5&nkey2=e7f0294986ea859347de447dc3573e15&geo=CN-9-267-11&mmsid=26643227&tm=1472892443&key=2ea1ba7b2923d80df02b2ca319ca460d&playid=0&vtype=52&cvid=1128348871549&payff=0&ctv=pc&m3v=1&hwtype=un&ostype=Linux&tag=letv&sign=letv&tn=0.6755845507520513&pay=0&iscpn=f9051&rateid=1080p&errc=0&gn=387&vrtmcd=107&buss=100&cips=112.65.211.154
    Site:       Le.com
    Title:      机器纪元
    Type:       MPEG-4 video (video/mp4)
    Size:       2142.55 MiB (2246628200 Bytes)
    
    you-get: version 0.4.536, a tiny downloader that scrapes the web.
    you-get: ['http://www.le.com/ptv/vplay/21867033.html']
    Traceback (most recent call last):
      File "<string>", line 11, in <module>
      File "src\you_get\__main__.py", line 92, in main
      File "src\you_get\common.py", line 1332, in main
      File "src\you_get\common.py", line 1245, in script_main
      File "src\you_get\common.py", line 1061, in download_main
      File "src\you_get\common.py", line 1325, in any_download
      File "src\you_get\extractors\le.py", line 137, in letv_download
      File "src\you_get\extractors\le.py", line 98, in letv_download_by_vid
      File "src\you_get\common.py", line 699, in download_urls
      File "src\you_get\common.py", line 210, in launch_player
      File "subprocess.py", line 560, in call
      File "subprocess.py", line 950, in __init__
      File "subprocess.py", line 1220, in _execute_child
    FileNotFoundError: [WinError 206] 文件名或扩展名太长。
    you-get returned -1

**Comment by cnbeining** [comment]
因为调用播放器时需要将视频URL当argument丢进去 就会出现这种问题。

骂巨硬吧。。。。

![hff wa0d5 n u 6876 q2](https://cloud.githubusercontent.com/assets/1560962/18234298/b1cc8a42-72cd-11e6-93d9-fa7d8a94a2f4.jpg)

**Comment by soimort** [comment]
cmd单个命令行的上限是8191 [1]。Letv这个视频分了300多段，URL长度加起来超过250kB。要解决只有 #606。

[1] https://support.microsoft.com/en-us/kb/830473
