### ISSUE TITLE
能否支持cctv网站的视频，目前使用最新版无法下载

### ISSUE THREAD

**Issue by xiongyefeng** [soimort/you-get#1392]
Please make sure these boxes are checked before submitting your issue – thank you!
- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read https://github.com/soimort/you-get/wiki/FAQ and tried to do so.
- [x] The issue is not yet reported on https://github.com/soimort/you-get/issues or  https://github.com/soimort/you-get/wiki/Known-Bugs. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 https://github.com/soimort/you-get/wiki/FAQ 中的指引进行了操作.
- [x] 您的问题没有在https://github.com/soimort/you-get/issues , https://github.com/soimort/you-get/wiki/FAQ 或 https://github.com/soimort/you-get/wiki/Known-Bugs 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

you-get --debug http://tv.cctv.com/2016/09/06/VIDEqywzpZ0TBFGBWE0zSZMN160906.shtml
[在这里粘贴完整日志]
you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['http://tv.cctv.com/2016/09/06/VIDEqywzpZ0TBFGBWE0zSZMN160906.shtml']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get__main__.py", line 92, in main
  File "src\you_get\common.py", line 1331, in main
  File "src\you_get\common.py", line 1244, in script_main
  File "src\you_get\common.py", line 1060, in download_main
  File "src\you_get\common.py", line 1324, in any_download
  File "src\you_get\extractors\cntv.py", line 46, in cntv_download
  File "src\you_get\extractors\cntv.py", line 12, in cntv_download_by_id
AssertionError
you-get returned -1

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
```
you-get -di http://tv.cctv.com/2016/09/06/VIDEqywzpZ0TBFGBWE0zSZMN160906.shtml
[DEBUG] get_response: http://tv.cctv.com/2016/09/06/VIDEqywzpZ0TBFGBWE0zSZMN160906.shtml
[DEBUG] get_response: http://vdn.apps.cntv.cn/api/getHttpVideoInfo.do?pid=bc25aacc424442f9949ce2a687f4a130
[DEBUG] url_info: http://125.46.64.90/v.cctv.com/flash/mp4video55/TMS/2016/09/06/bc25aacc424442f9949ce2a687f4a130_h264418000nero_aac32-1.mp4
[DEBUG] url_info: http://125.46.64.90/v.cctv.com/flash/mp4video55/TMS/2016/09/06/bc25aacc424442f9949ce2a687f4a130_h264418000nero_aac32-2.mp4
[DEBUG] url_info: http://125.46.64.90/v.cctv.com/flash/mp4video55/TMS/2016/09/06/bc25aacc424442f9949ce2a687f4a130_h264418000nero_aac32-3.mp4
[DEBUG] url_info: http://125.46.64.90/v.cctv.com/flash/mp4video55/TMS/2016/09/06/bc25aacc424442f9949ce2a687f4a130_h264418000nero_aac32-4.mp4
[DEBUG] url_info: http://125.46.64.90/v.cctv.com/flash/mp4video55/TMS/2016/09/06/bc25aacc424442f9949ce2a687f4a130_h264418000nero_aac32-5.mp4
[DEBUG] url_info: http://125.46.64.90/v.cctv.com/flash/mp4video55/TMS/2016/09/06/bc25aacc424442f9949ce2a687f4a130_h264418000nero_aac32-6.mp4
Site:       CNTV.com
Title:      《今日说法》 20160906 红色手提包
Type:       MPEG-4 video (video/mp4)
Size:       93.13 MiB (97657587 Bytes)
```
