### ISSUE TITLE
Youku you-get: [Failed] Cannot extract video source.

### ISSUE THREAD

**Issue by lsycxyj** [soimort/you-get#1394]
python you-get --format=mp4 http://v.youku.com/v_show/id_XMTcxNDM3MjEwOA==.html

**Comment by cnbeining** [comment]
Please provide us with more detailed log with ```-d``` .

**Comment by lsycxyj** [comment]
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTcxNDM3MjEwOA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTcxNDM3MjEwOA==&ct=12
site:                优酷 (Youku)
title:               互联网没有颠覆什么 160905
stream:
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          269.4 MiB (282516275 bytes)
    # download-with: you-get --format=mp4 [URL]

you-get: [Failed] Cannot extract video source.

**Comment by soimort** [comment]
For obvious reasons, we don't support downloading paid videos from Youku. If you have a member account, please feel free to open an PR.
