### ISSUE TITLE
下载的都是同一个腾讯视频

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#1395]
这三个url
    # url = 'http://v.qq.com/x/cover/h54grqlop7kdg12/q0019f6eih2.html'
    # url = 'http://v.qq.com/x/cover/h54grqlop7kdg12/v0021ydtwot.html'
    # url = 'http://v.qq.com/x/cover/h54grqlop7kdg12/z0323bo5xr2.html'
解析出来的文件名都是同一个

**Comment by redstoneleo** [comment]
这个http://v.qq.com/page/d/6/d/d0013t1j56d.html?ptag=baidu_aladdin.tv
解析出来的文件名是字母

**Comment by snow930** [comment]
没遇到.不过我下载腾讯视频有时候特别慢只有几十kb, 下优酷视频却是满速

**Comment by redstoneleo** [comment]
我再次测试了一下，看样子是已经解决了

> C:\Users\i>you-get -V
> you-get: version 0.4.555, a tiny downloader that scrapes the web.
> 
> C:\Users\i>
