### ISSUE TITLE
error when trying to watch livestream videos on douyu.com, need manual check!

### ISSUE THREAD

**Issue by pthreadself** [soimort/you-get#1400]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```

you-get -d -p mpv http://douyu.com/534740
[DEBUG] get_content: http://douyu.com/534740
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=534740
Site:       douyu.com
Title:      【六神】救人一命，胜造七级浮屠！
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Playing: http://hdl3.douyucdn.cn/live/534740rzp3e4UL6z.flv?wsAuth=6e1f88abe691742726d8fcb7f6087392&token=web-douyu-0-534740-bbaea971597092d189bb733903e208a6&logo=0&expire=0&did=6AB58DB08BCA4A428B8BEC8F3715D65D
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[ytdl_hook] youtube-dl failed, trying to play URL directly ...
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://hdl3.douyucdn.cn/live/534740rzp3e4UL6z.flv?wsAuth=6e1f88abe691742726d8fcb7f6087392&token=web-douyu-0-534740-bbaea971597092d189bb733903e208a6&logo=0&expire=0&did=6AB58DB08BCA4A428B8BEC8F3715D65D.


Exiting... (Errors when loading file)
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by isbaseby** [comment]
我同样遇到了这个问题
