### ISSUE TITLE
下载爱奇艺后，播放视频时总会出现突然跳过10秒，20秒时间

### ISSUE THREAD

**Issue by xiongyefeng** [soimort/you-get#1401]
下载的是这个文件you-get-0.4.536-win32-full.7z

地址：http://www.iqiyi.com/v_19rrm3uay0.html

这个视频大概播放到8分30秒左右的时间，会自动跳到8分50秒。我只测试了这个地址，应该全部都存在这个问题，请作者有空能检查下。

**Comment by lamlam123tld3** [comment]
tmts is originally for tv broadcasting
the timestamp may not be promised to be correct
(obviously, it always get some problems in timestamp when video length getting longer)

different from vms
which split to file into flv

my temporary solution is
not to concat the ts segments directly, as timestamp may get wrong
but first convert all the single segments into mkv and finally merge the mkvs to a single file
before merging the mkvs
one should also remove all the mkv segments that may only have audio track

**Comment by cnbeining** [comment]
Actually this is the way I usually use when working with crappy video sources.

Can we just run a pipe of ffmpeg, first converting everything to MKV(since MKV is good to almost everything on the earth) then remux them to MP4? Is this worth trying?

**Comment by rosynirvana** [comment]
ori description should be a dup of #1270

``merging to mkv'' failed on http://www.iqiyi.com/v_19rr9nso74.html#curid=569810600_7aa03d6b0986063ff5ddd0d6885f6fda
ep 7

NOTE: opening the url directly only lead you to ep 1, NOT ep 7
