### ISSUE TITLE
bokecc 糖豆网无法下载视频

### ISSUE THREAD

**Issue by jackwu365** [soimort/you-get#1402]
```
$ ./you-get.exe --debug "http://www.tangdou.com/v83/dAOIMIOjwDxjyA2.html"
[DEBUG] get_content: http://www.tangdou.com/v83/dAOIMIOjwDxjyA2.html
Site:       tangdou.com
Title:      20160819000339_1268
Type:       JPEG Image (image/jpeg)
Size:       0.02 MiB (25653 Bytes)

Skipping .\20160819000339_1268.jpg: file already exists

Site:       tangdou.com
Title:      30bd2694b20e9d7a4a6349c0426180f7
Type:       MP3 (audio/mpeg)
Size:       8.37 MiB (8781391 Bytes)

Skipping .\30bd2694b20e9d7a4a6349c0426180f7.mp3: file already exists

Site:       tangdou.com
Title:      20160903102602_1715
Type:       JPEG Image (image/jpeg)
Size:       0.01 MiB (10311 Bytes)

Skipping .\20160903102602_1715.jpg: file already exists

Site:       tangdou.com
Title:      20150603092727_1710
Type:       JPEG Image (image/jpeg)
Size:       0.01 MiB (12477 Bytes)

Skipping .\20150603092727_1710.jpg: file already exists


Administrator@-PC /cygdrive/d/tools/视频下载

```

**Comment by cnbeining** [comment]
还没有这个站的解析器。

需要写一个。。。。。

**Comment by soimort** [comment]
Consider implementing this as part of `embed.py`.

**Comment by woyaojizhu8** [comment]
https://github.com/lcplj123/video-dl/commit/87ce358522efa671c0a4446a4d4d0dd78566dc15

**Comment by lki2019** [comment]
ize:       8.37 MiB (8781391 Bytes)

ownloading 30bd2694b20e9d7a4a6349c0426180f7.mp3 ...
0.0% (  0.0/  8.4MB) ├─────────────────────
3.0% (  0.2/  8.4MB) ├██───────────────────
6.0% (  0.5/  8.4MB) ├███──────────────────
9.0% (  0.8/  8.4MB) ├████─────────────────
1.9% (  1.0/  8.4MB) ├█████────────────────
4.9% (  1.2/  8.4MB) ├██████───────────────
7.9% (  1.5/  8.4MB) ├███████──────────────
0.9% (  1.8/  8.4MB) ├█████████────────────
3.9% (  2.0/  8.4MB) ├██████████───────────
6.9% (  2.2/  8.4MB) ├███████████──────────
9.9% (  2.5/  8.4MB) ├████████████─────────
2.8% (  2.8/  8.4MB) ├██████████████───────
─────────────┤[1/1]  379 kB/s


貌似现在可以正常下载的
可以关闭了

**Comment by lki2019** [comment]
现在已经支持啦，大神可以关闭啦

C:\Users\Administrator>you-get -di http://www.tangdou.com/v83/dAOIMIOjwDxjyA2.ht
ml
[DEBUG] get_head: http://www.tangdou.com/v83/dAOIMIOjwDxjyA2.html
[DEBUG] get_content: http://www.tangdou.com/v83/dAOIMIOjwDxjyA2.html
[DEBUG] get_response: http://www.tangdou.com/v83/dAOIMIOjwDxjyA2.html
[DEBUG] url_info: http://mp3.tangdouimg.com/wuqu/30bd2694b20e9d7a4a6349c0426180f
7.mp3?_upd=true
Site:       tangdou.com
Title:      30bd2694b20e9d7a4a6349c0426180f7
Type:       MP3 (audio/mpeg)
Size:       8.37 MiB (8781391 Bytes)

**Comment by lki2019** [comment]
奥 http://www.tangdou.com/v92/dAOENEMjwT2T3w2.html

这个不行 

http://www.tangdou.com/html/playlist/5318/9164265.html

看错了，解析出来的是MP3 
视频没解析出来，抱歉

**Comment by rosynirvana** [comment]
```http://www.tangdou.com/v83/dAOIMIOjwDxjyA2.html``` ->
```http://m.tangdou.com/v83/dAOIMIOjwDxjyA2.html``` with curl or mobile UA

get h5html from the page
```
curl http://m.tangdou.com/v83/dAOIMIOjwDxjyA2.html | grep 'h5html'
```

```
var h5html = "<script src='http:\/\/share.tangdou.com\/mp4.php?vid=8212228&img=http://images.tangdou.com/video/201609/20160908111753_4657.jpg&videourl=67BED6C90F9A156F9C33DC5901307461&siteid=21F4A787A918F3CE''><\/script>";
```

```
curl 'http://share.tangdou.com/mp4.php?vid=8212228&img=http://images.tangdou.com/video/201609/20160908111753_4657.jpg&videourl=67BED6C90F9A156F9C33DC5901307461&siteid=21F4A787A918F3CE'
```

```
document.write("<div id=\"ucloud_video\" style=\"width: 100%; position: relative;\"><video id=\"cc_67BED6C90F9A156F9C33DC5901307461\" preload=\"none\" webkit-playsinline=\"\" controls=\"\" x-webkit-airplay=\"allow\" poster=\"http://images.tangdou.com/video/201609/20160908111753_4657.jpg\" width=\"100%\" height=\"235\" src=\"https://aucshare.tangdou.com/67BED6C90F9A156F9C33DC5901307461-10.mp4?k=6bbc6f4baff2828f&t=1502682949\"></video></div>")
```


```
src=\"https://aucshare.tangdou.com/67BED6C90F9A156F9C33DC5901307461-10.mp4?k=6bbc6f4baff2828f&t=1502682949\"
```
is the final uri

**Comment by Irismoon** [comment]
...楼上大神，这个意思是自己在源码里加这段程序吗？还是在powershell命令行运行呢？

**Comment by ghxter** [comment]
@Irismoon 你直接在 命令行 输入 上面两行的 curl就明白了。

**Comment by rosynirvana** [comment]
OMG
写了半天还以为bokecc是tangdou.com原来的域名……

**Comment by rosynirvana** [comment]
with https://github.com/soimort/you-get/commit/0a00ff3c463e1f273862c1fba8bd85b729f6dd52 and https://github.com/soimort/you-get/commit/ca490abead2b4ac03d3c44b06477f948e2139a58

it works
```
./you-get -i http://www.tangdou.com/html/playlist/10250/7805977.html
site:                BokeCC
title:               D059009071B4F0719C33DC5901307461
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        0
      container:     flv
      video-profile: 普通
      size:          34.4 MiB (36097114 bytes)
    # download-with: you-get --format=0 [URL]

    - format:        1
      container:     flv
      video-profile: 清晰
      size:          61.6 MiB (64578120 bytes)
    # download-with: you-get --format=1 [URL]

    - format:        2
      container:     flv
      video-profile: 高清
      size:          115.9 MiB (121549790 bytes)
    # download-with: you-get --format=2 [URL]
```

but not good
