### ISSUE TITLE
爱奇艺下载电视剧，下载的全是第一集

### ISSUE THREAD

**Issue by bonecto** [soimort/you-get#1411]
测试地址
太阳的后裔 【第10集】http://www.iqiyi.com/v_19rrkxmiss.html?vfm=m_103_txsp#curid=463600800_92901d0910b5f9a0506e9d27bd080ec2
下载下来的确是第一集

**Comment by nuomi1** [comment]
你看一下 `view-source`，这就是第一集……
爱奇艺点击右侧列表选择集数的时候，只会刷新 Flash，不会刷新 URL。

**Comment by bonecto** [comment]
那有没有办法下载所有集数？

**Comment by Magikarp96** [comment]
你的下载速度可以嘛？其他视频下载速度都正常 只有爱奇艺100kb的下载速度
