### ISSUE TITLE
提两个小建议

### ISSUE THREAD

**Issue by luckykong** [soimort/you-get#1415]
首先谢谢你的工作，这个project太实用了。
另外，有两个小建议，看能否考虑实现一下：

一，现在使用you-get 下载网易上的歌单的时候，下载的文件是按照 专辑序号+歌曲名称 命名的。这样如果两首歌具有同样的歌名和序号，下载时会发生后者覆盖了前者的现象。
如歌单 `http://music.163.com/#/playlist?id=63212757` 中，The Promise 这首歌出现两次，并且恰好专辑序号都是1。这样子就会发生覆盖的现象。

因此能否修改一下下载文件的命名方法。在每首歌前面添加一个 下载顺序 的序号。比如第一首歌添加1，第二首歌添加2......，这样子就不会发生覆盖现象了。并且按照下载顺序，也就是歌单的原始排序进行命令，在播放有些精心排序后的歌单的时候更有感觉。

二，有时候下载网易歌单时，会因为某些歌曲无法下载从而中断的现象。能否考虑一下这种情况，遇到无法下载的歌曲，程序不是中断，而是跳过这首歌继续下载，在运行完毕之后显示哪些歌曲下载失败。。。

**Comment by Rokicto** [comment]
#1503 给第一个建议做了一个实现，看看效果如何？
