### ISSUE TITLE
爱奇艺使用cookie下VIP视频失效

### ISSUE THREAD

**Issue by v1-hermit** [soimort/you-get#1419]
you-get.exe -c cookies.sqlite --format=LD http://www.iqiyi.com/v_19rrkz5l70.html

一下完前6分钟就停

**Comment by v1-hermit** [comment]
开发者不理我们%>_<%，有什么办法让她关注？

**Comment by cnbeining** [comment]
贴详细log啊。

**Comment by v1-hermit** [comment]
@cnbeining 
>you-get.exe -c cookies.sqlite --format=LD --debug http://www.iqiyi.com/v_19rrkz5l70.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/468671200/9989f150f4e0eaf97df5f294eeb20bac/?t=1476028309460&sc=0244e08d1f2e3815a458a46ab8362013&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               电竞高校
stream:
    - format:        LD
      container:     m3u8
      video-profile: 210p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=LD [URL]

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://cache.vip.iqiyi.com/m/u/1e5efa985527b51ecb8431123edc9cb1/afbe8fd3d73448c9/c062667cdf3071329e380cf5622f5ec2/14b23eb8467924681b16fc93ba78b477/2388123842.m3u8?t_sign=0-76f90cbd92f
94a2e925d83e8ccd22cb7-468671200_04022000001000000000_96-1476028318 -c copy -bsf:a aac_adtstoasc 电竞高校.mp4
ffmpeg version N-79068-g6b7ce0e Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-icon
v --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmfx --en
able-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libsp
eex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enabl
e-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 19.100 / 55. 19.100
  libavcodec     57. 28.103 / 57. 28.103
  libavformat    57. 28.102 / 57. 28.102
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 39.102 /  6. 39.102
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, hls,applehttp, from 'http://cache.vip.iqiyi.com/m/u/1e5efa985527b51ecb8431123edc9cb1/afbe8fd3d73448c9/c062667cdf3071329e380cf5622f5ec2/14b23eb8467924681b16fc93ba78b477/2388123842.m3u8?t_sign
=0-76f90cbd92f94a2e925d83e8ccd22cb7-468671200_04022000001000000000_96-1476028318':
  Duration: 00:06:05.00, start: 0.133000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 496x216, 15 fps, 15 tbr, 90k tbn, 30 tbc
    Stream #0:1: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 67 kb/s
Output #0, mp4, to '鐢电珵楂樻牎.mp4':
  Metadata:
    encoder         : Lavf57.28.102
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 496x216, q=2-31, 15 fps, 15 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (HE-AAC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 67 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  795 fps= 15 q=-1.0 Lsize=    1141kB time=00:00:52.80 bitrate= 177.0kbits/s speed=   1x
video:712kB audio:404kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.208296%
Exiting normally, received signal 2.

**Comment by shibenli** [comment]
可以设置speed= 1x的参数吗

**Comment by rosynirvana** [comment]
in favor of #2117
