### ISSUE TITLE
建议添加从文件导入url,批量下载功能

### ISSUE THREAD

**Issue by ichenkaihua** [soimort/you-get#1427]
貌似还没发现导入功能
比如说我要下载多个视频,但不想一个一个输入命令行下载,能否把链接保持在文本中,然后给you-get添加一个option,比如`you-get -i urls.txt`.然后从文本读取自动下载.

**Comment by soimort** [comment]
Duplicate of #325.

**Comment by ad52825196** [comment]
我这里写了一个 Java 的小程序，你可以试试看：https://github.com/ad52825196/video-downloader
