### ISSUE TITLE
斗鱼一直返回403？

### ISSUE THREAD

**Issue by isbaseby** [soimort/you-get#1437]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get --debug -p mpv https://www.douyu.com/pis
[DEBUG] get_content: http://www.douyu.com/pis
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=532152
Site:       douyu.com
Title:      Pis直播间:被分上
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Playing: http://hdl1a.douyucdn.cn/live/532152r8bakrivZs.flv?wsAuth=50cd296ba4c84845133cf25f61d36879&token=web-douyu-0-532152-7b4ab1ec20ee27c069ac11b851caafb9&logo=0&expire=0&did=5CB4BCE41DAF406ABA8024C625EBDA3E
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://hdl1a.douyucdn.cn/live/532152r8bakrivZs.flv?wsAuth=50cd296ba4c84845133cf25f61d36879&token=web-douyu-0-532152-7b4ab1ec20ee27c069ac11b851caafb9&logo=0&expire=0&did=5CB4BCE41DAF406ABA8024C625EBDA3E.


Exiting... (Errors when loading file)
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get --debug -p mpv https://www.douyu.com/pis
[DEBUG] get_content: http://www.douyu.com/pis
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=532152
Site:       douyu.com
Title:      Pis直播间:被分上
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Playing: http://hdl1a.douyucdn.cn/live/532152r8bakrivZs.flv?wsAuth=50cd296ba4c84845133cf25f61d36879&token=web-douyu-0-532152-7b4ab1ec20ee27c069ac11b851caafb9&logo=0&expire=0&did=5CB4BCE41DAF406ABA8024C625EBDA3E
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://hdl1a.douyucdn.cn/live/532152r8bakrivZs.flv?wsAuth=50cd296ba4c84845133cf25f61d36879&token=web-douyu-0-532152-7b4ab1ec20ee27c069ac11b851caafb9&logo=0&expire=0&did=5CB4BCE41DAF406ABA8024C625EBDA3E.


Exiting... (Errors when loading file)
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by NCACN** [comment]
网络的问题吧，我这正常。

**Comment by isbaseby** [comment]
@NCACN 有同样遇到这个问题的人
https://github.com/soimort/you-get/issues/1400

**Comment by muxang** [comment]
我手动用ffmpeg去下载解析后的视频，也会一直403

**Comment by lexcn** [comment]
我用mpv播放也会403，但是用ffplay播放就不会。

**Comment by steven7851** [comment]
这是网宿CDN的问题，如果情况很频繁
可以自行修改连接的CDN
```python
payload = {'cdn': 'ws', 'rate': '0', 'tt': tt, 'did': did, 'sign': sign}
```
```js
{name: "主线路", cdn: "ws"}
{name: "备用线路5", cdn: "tct"}
{name: "备用线路2", cdn: "ws2"}
{name: "备用线路3", cdn: "dl"}
```

**Comment by isbaseby** [comment]
@steven7851 Thanks,修改为```payload = {'cdn': 'ws2', 'rate': '0', 'tt': tt, 'did': did, 'sign': sign}```没问题了
