### ISSUE TITLE
PPTV只能解析最低清晰度

### ISSUE THREAD

**Issue by ShekBoy** [soimort/you-get#1439]
Please make sure these boxes are checked before submitting your issue – thank you!
- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read https://github.com/soimort/you-get/wiki/FAQ and tried to do so.
- [x] The issue is not yet reported on https://github.com/soimort/you-get/issues or  https://github.com/soimort/you-get/wiki/Known-Bugs. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 https://github.com/soimort/you-get/wiki/FAQ 中的指引进行了操作.
- [x] 您的问题没有在https://github.com/soimort/you-get/issues , https://github.com/soimort/you-get/wiki/FAQ 或 https://github.com/soimort/you-get/wiki/Known-Bugs 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
root@SDS:~# you-get -y 124.88.67.32:81 -i --debug http://v.pptv.com/show/9UebGK2icpuRHxS0.html
Site:       PPTV.com
Title:      我太受欢迎了该怎么办(第01集)
Type:       MPEG-4 video (video/mp4)
Size:       84.780000000000001 MiB (88895350 Bytes)
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 在 http://www.flvurl.cn/ 这个网站可以解析全部清晰度，但you-get只能解析到最低的清晰度

**Comment by ilools** [comment]
通过使用 swf reader 对 Player4Player2.swf 进行脱壳内存抓取 swf，获得一个使用了 as3crypto 加密的 swf ，具体看 showmycode [反编译出的代码](http://www.showmycode.com/?9b6bd90bb76ecb4f86f52665f21af775)
swf 下载地址 （https://www.dropbox.com/s/roz3g67opqkq9qz/needtodecode1.swf?dl=1）
    新的 K 值应该是拿 xml 内获取到的 key 值内的 md5值进行加盐处理，其他解析代码解析部分都没有变化，所以将上面的 swf 破解获取 K 值算法即可修复。

**Comment by denobisipsis** [comment]
https://github.com/denobisipsis/adownloader/blob/master/pptv.php

k & key parameters

**Comment by huwenkai26** [comment]
@ilools  你的连接失效了
