### ISSUE TITLE
不支持中文名用户账户

### ISSUE THREAD

**Issue by jdfq** [soimort/you-get#1440]
我win10 32位，原来是中文名用户账户，运行显示：“MSVCR100.dll could not be extracted!”。新建英文名用户账户，正常工作。

**Comment by zhangn1985** [comment]
这个估计要报告问题给Pyinstaller或者微软了。

**Comment by Erk-** [comment]
Try to install [Microsoft Visual C++ 2010 Redistributable Package (x86)
](https://www.microsoft.com/en-us/download/details.aspx?id=5555)

**Comment by czc2004211** [comment]
自己改英文帐户名又不是什么特别难的事

**Comment by jdfq** [comment]
改英文名不行，要新建英文名用户账户才行，可能是要用户账户文件夹名称是英文。这个问题应该是这个软件系统的问题吧？
