### ISSUE TITLE
YOU-GET have problems when parsing IQIYI URLS!

### ISSUE THREAD

**Issue by EGBAR** [soimort/you-get#1442]
Please make sure these boxes are checked before submitting your issue – thank you!
- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read https://github.com/soimort/you-get/wiki/FAQ and tried to do so.
- [ ] The issue is not yet reported on https://github.com/soimort/you-get/issues or  https://github.com/soimort/you-get/wiki/Known-Bugs. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!
- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 https://github.com/soimort/you-get/wiki/FAQ 中的指引进行了操作.
- [ ] 您的问题没有在https://github.com/soimort/you-get/issues , https://github.com/soimort/you-get/wiki/FAQ 或 https://github.com/soimort/you-get/wiki/Known-Bugs 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

Why I can use 'you-get' to parse and download videos with url from youtube and youku. But I can't do the same thing with URL form "iqiyi"??

when I parse Url with youku:
➜  ~ you-get -i 'http://v.youku.com/v_show/id_XMTc0MTUxODEwNA==.html?spm=a2hmv.20009921.posterMovieGrid86981.5~5~5~1~3!2~A&from=y1.3-movie-grid-1095-9921.86981.1-2'
site:                优酷 (Youku)
title:               大鱼海棠
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          2118.5 MiB (2221419105 bytes)
    # download-with: you-get --format=hd3 [URL]

```
- format:        hd2
  container:     flv
  video-profile: 超清
  size:          1178.3 MiB (1235498209 bytes)
# download-with: you-get --format=hd2 [URL]

- format:        mp4
  container:     mp4
  video-profile: 高清
  size:          623.5 MiB (653817203 bytes)
# download-with: you-get --format=mp4 [URL]

- format:        flvhd
  container:     flv
  video-profile: 标清
  size:          301.7 MiB (316356353 bytes)
# download-with: you-get --format=flvhd [URL]
```

WHILE dealing with iqiyi:

➜  ~ you-get -di 'http://www.iqiyi.com/v_19rrmbt4do.html#vfrm=19-9-0-1'
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrmbt4do.html#vfrm=19-9-0-1']
Traceback (most recent call last):
  File "/home/egbar/.local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/home/egbar/.local/lib/python3.5/site-packages/you_get/**main**.py", line 92, in main
    main(**kwargs)
  File "/home/egbar/.local/lib/python3.5/site-packages/you_get/common.py", line 1348, in main
    script_main('you-get', any_download, any_download_playlist, *_kwargs)
  File "/home/egbar/.local/lib/python3.5/site-packages/you_get/common.py", line 1261, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/egbar/.local/lib/python3.5/site-packages/you_get/common.py", line 1077, in download_main
    download(url, *_kwargs)
  File "/home/egbar/.local/lib/python3.5/site-packages/you_get/common.py", line 1341, in any_download
    m.download(url, **kwargs)
  File "/home/egbar/.local/lib/python3.5/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/home/egbar/.local/lib/python3.5/site-packages/you_get/extractors/iqiyi.py", line 137, in prepare
    self.title = match1(html, '<title>([^<]+)').split('-')[0]
AttributeError: 'NoneType' object has no attribute 'split'.

???
Would anyone help me handle this problem?

Thanks!

**Comment by cnbeining** [comment]
视频无法播放，请考虑使用unblock-youku类软件。

2016年10月8日星期六，Mort the Bot <notifications@github.com> 写道：

**Comment by rosynirvana** [comment]
```
$ ./you-get -i 'http://www.iqiyi.com/v_19rrmbt4do.html#vfrm=19-9-0-1'
site:                爱奇艺 (Iqiyi)
title:               夜孔雀
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
      m3u8_url:      http://cache.m.iqiyi.com/mus/504121600/74efe0fe5e84071acb4d280c90018a9e/afbe8fd3d73448c9//20160914/3a/30/2129fe36e86845247b403966c5e6959f.m3u8?qd_originate=tmts_py&tvid=504121600&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1499916546451&qd_p=7d2db05d&qd_asc=fb6232d6c0a1567f0d948ca964c5fa2b&qypid=504121600_04022000001000000000_4&qd_k=46db07daf13d854b2aae8cb563acf69c&vf=86ca5e021e77665d7f128567d6e4dd99&np_tag=nginx_part_tag
    # download-with: you-get --format=TD [URL]
```
