### ISSUE TITLE
B站增加大会员1080P后的那些视频解析不了

### ISSUE THREAD

**Issue by sola97** [soimort/you-get#1449]
旧番那些最高超清的可以解析，新番有最高1080P的不行

**Comment by cnbeining** [comment]
我们有可能需要也挂上cookie了。

**Comment by minghu6** [comment]
bilibili.py 解析的时候就没有用cookie，大会员的1080p番剧、大会员抢先看等也是没有的，不知道哪位大人是贡献这个bilibili.py的，什么时候能修复这个大会员问题。。。

**Comment by rosynirvana** [comment]
closed via #1698 

paid bangumi movie... maybe someday
