### ISSUE TITLE
Chocolatey install not working due to failed checksum

### ISSUE THREAD

**Issue by bwegman** [soimort/you-get#1450]
When installing you-get using Chocolatey the following error is returned:

` Downloading you-get 32 bit
   from 'https://github.com/soimort/you-get/releases/download/v0.4.486/you-get-0.4.486-win32-full.7z'
Checksum for 'C:\Users\Benjamin\AppData\Local\Temp\chocolatey\you-get\you-getInstall.zip' did not meet 'DC1FCF62E8145ADD3B296298326B75F9E1B744D131AA39FC892F6E832BE19596' for check
 sum type 'md5'.`

It seems either the MD5 sum in Chocolatey is wrong or the downloaded 7z has changed after registering it with Chocolatey.

**Comment by soimort** [comment]
I don't maintain the Chocolatey package myself. Also it seems quite outdated there.
@chantisnake

**Comment by chantisnake** [comment]
sorry, I am quiet filled up with course work currently, so this is out-dated, I will update it very soon.

This issue can be moved to https://github.com/chantisnake/chocolateyPackage

**Comment by chantisnake** [comment]
I think is the choco team changed some grammar, because if you see my code, I requested check sum method to be `sha256`

https://github.com/chantisnake/chocolateyPackage/blob/master/you-get-choco/Versions/0.4.486/tools/chocolateyinstall.ps1

**Comment by chantisnake** [comment]
can you try update you choco to the latest version and then restart you computer and force reinstall you-get?

because I installed it fine:
```
Downloading you-get
  from 'https://github.com/soimort/you-get/releases/download/v0.4.486/you-get-0.4.486-win32-full.7z'
Progress: 100% - Saving 17.21 MB of 17.21 MB (18047551/18047569)
Download of you-get-0.4.486-win32-full.7z (17.21 MB) completed.
Hashes match.
```

**Comment by bwegman** [comment]
You are absolutely right. I was on an older version of chocolatey (0.9.9.8). It doesn't seem to indicate there is a new version and this older version seems to have a different hash check algorithm. Installing the package with the latest version works as expected. Thank you.

For those interested, upgrading chocolatey is as easy as running:
`choco upgrade chocolatey`
