### ISSUE TITLE
希望添加对“爱课程网”的支持

### ISSUE THREAD

**Issue by fanweiya** [soimort/you-get#1451]
这个网站好多好的课程，想离线下来寝室断网后看，希望能够支持，谢谢
视频链接：http://www.icourses.cn/jpk/viewCharacterDetail.action?sectionId=51267&courseId=3622
如果能支持下面这种整个科目下载，就最好不过啦
科目链接：http://www.icourses.cn/coursestatic/course_3622.html

**Comment by v1-hermit** [comment]
这么好的建议，为什么都不搭理？

**Comment by cnbeining** [comment]
@v1-hermit 没人用的解析器自然维护的少。

**Comment by liushuyu** [comment]
Seems like not very hard to implement... But not sure about whether is needed? Is this site frequently used?

**Comment by cnbeining** [comment]
Should anyone wants to implement this one, working on the mobile API is the easier way.

**Comment by liushuyu** [comment]
I think even desktop (Flash player) parse is easy though

**Comment by cnbeining** [comment]
@liushuyu How do you get the signature from the Player?

**Comment by liushuyu** [comment]
>@liushuyu How do you get the signature from the Player?

See the Flash parameters passed by the HTML elements

**Comment by cnbeining** [comment]
I am having a URL like

http://media3.icourses.cn/process7/campus/processres/flv/2016/6/2/ff808081-5505e47e-0155-0f0b8bae-000a.flv?lv=150606-1&lt=10-16/21:54:38&ls=play&h=6XJKAS064hurBwB8ZOEslA&r=1476712488&p=151020&start=0


Is the "h" parameter calculated within the player? It seems that I am missing something...

**Comment by liushuyu** [comment]
>Is the "h" parameter calculated within the player? It seems that I am missing something...

No, this URL is requested from the server. Seems like you think too much. This seems like just a small school-driven website. It can't use too complicated technology...

**Comment by liushuyu** [comment]
@cnbeining Do you want to try this out yourself, I tell you how it works or just I write the code?

**Comment by cnbeining** [comment]
Nah actually I've worked out the mobile API but is too busy to open a PR. The mobile API is returning a HLS link with AES, which would require ffmpeg being installed. 

Obviously your method is the better way. You can go ahead and finish your PR and I would be more than happy to review it.

-------


For future contributors:

You can find a ziped version of the video via the mobile API. However downloading a zip ball is hardly what ```you-get``` 's expected behaviour so I am not going to implement via this way.

**Comment by liushuyu** [comment]
@cnbeining I have completed the complete analysis of the player and website traffic. It was harder than I thought, but still managed to understand the mechanism. It is midnight in my timezone. I will complete the code tomorrow (MDT).

**Comment by fanweiya** [comment]
@liushuyu
 I am the author of this issue, if you can make a tool , I am very grateful to you.THX

**Comment by liushuyu** [comment]
@fanweiya I will give it a try.

**Comment by liushuyu** [comment]
Patch: #1472
