### ISSUE TITLE
从前天开始b站的番据用you-get下载被限速

### ISSUE THREAD

**Issue by lioliy** [soimort/you-get#1452]
you-get -d http://www.bilibili.com/video/av3997347/
地址：http://www.bilibili.com/video/av3997347/
解析到的cdn地址cn-zjjh18-dx.acgvideo.com:80
可以判断明显国内cdn
但使用you-get下载时被限速100k，没有使用代理，且更换了很多网络环境也不行。

**Comment by nuomi1** [comment]
`由于用户量增长太快，今年以来，b站服务器和带宽的负载越来越捉襟见肘。为了保证所有人的观看体验，我们从9月8日起进行了带宽的再次升级，并对高峰时期（晚上8点至12点）的视频离线缓存进行了限速。目前带宽升级工程已经完成，但在高峰时期我们依然优先保证在线观看。预计本周内将对高峰期的离线缓存限速进行提升。如您确有下载需要，请在非高峰期操作。今后我们也将继续优化带宽分配方案，为用户提供更好的观看体验。高峰时段（20:00-24:00）具体限速方案如下：LV6 不限｜LV5 不限｜LV4 1000kb/s｜LV3 800kb/s｜LV2 600kb/s｜LV1 400kb/s｜LV0 200kb/s｜非注册用户 100kb/s。 注：实际下载速度受用户网络环境、网络硬件、网络服务提供商等多方面影响 。`

还得传 Cookie。

**Comment by ShekBoy** [comment]
由于用户量增长太快，今年以来，b站服务器和带宽的负载越来越捉襟见肘。为了保证所有人的观看体验，我们从9月8日起进行了带宽的再次升级，并对高峰时期（晚上8点至12点）的视频离线缓存进行了限速。目前带宽升级工程已经完成，但在高峰时期我们依然优先保证在线观看。预计本周内将对高峰期的离线缓存限速进行提升。如您确有下载需要，请在非高峰期操作。今后我们也将继续优化带宽分配方案，为用户提供更好的观看体验。高峰时段（20:00-24:00）具体限速方案如下：LV6 不限｜LV5 不限｜LV4 1000kb/s｜LV3 800kb/s｜LV2 600kb/s｜LV1 400kb/s｜LV0 200kb/s｜非注册用户 100kb/s。 注：实际下载速度受用户网络环境、网络硬件、网络服务提供商等多方面影响 。
换个时间段下载或者看看导入cookies能不能解决吧

**Comment by cnbeining** [comment]
试了 传cookie都坑 单线程100K 我的aria2挂C3 LA的中转都不好使。

而且不是离线缓存限速吧。

**Comment by ShekBoy** [comment]
就是离线缓存限速啊

**Comment by ShekBoy** [comment]
话说其实怎样下载b站视频...怎么我用了proxy还是一直错误...
跟这个一样：https://github.com/soimort/you-get/issues/1436

**Comment by cnbeining** [comment]
我已经骂过去了。

和cookie没关系。

和Level没关系。

拆包看API很明显。

导出URL后用axel跑50线程可破。。。反正CDN不是我家开的。欧耶。

**Comment by lioliy** [comment]
现在好像不限速了，今天试了下下载速度3m/s左右
