### ISSUE TITLE
youtube video with high solution does not merged

### ISSUE THREAD

**Issue by kyan001** [soimort/you-get#1453]
youtube 解析度最大的 1920*1080 左右的视频，下载下来后会出现 [00].mp4 和 [01].mp4 两个文件，其中一个只有音频，另一个只有视频，不自动合并。用 debug 看似乎没有报错，显示也是 success。

**Comment by kyan001** [comment]
@soimort-bot 
the url which I med that problem is :
<https://www.youtube.com/watch?v=fsmKwdVOJFY&ab_channel=kobasolo>

I was using a http_proxy at that time, but under the same proxy, hd720 resolution is perfectly downloaded.

I set the itag=137 at that moment, which is the highest resolution 1920xsomething, and also it's the biggest video file in that --info prints.

I also set the output folder, but still, this option works perfectly in hd720 resolution.

**Comment by cnbeining** [comment]
@soimort-bot Sorry to bother you, but could you please kindly test this link for us:

https://www.youtube.com/watch?v=fsmKwdVOJFY

**Comment by soimort** [comment]
@kyan001 The auto-merge functionality of YouTube's high resolution formats (DASH playback) requires FFmpeg to work. You need to install that first. (see #704)

@cnbeining The bot will only go through the link you put in the same paragraph, like this:

@soimort-bot just test https://www.youtube.com/watch?v=fsmKwdVOJFY
