### ISSUE TITLE
安装后却找不到命令、pip顽固提示更新。

### ISSUE THREAD

**Issue by linux0ne** [soimort/you-get#1454]
$pip3 install you-get
Collecting you-get
  Using cached you_get-0.4.555-py3-none-any.whl
Installing collected packages: you-get
Successfully installed you-get-0.4.486
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

1、用命令安装后，在终端里却找不到命令。于是隔了几天用更新命令更新之，发现可以更新，说明软件已经安装成功了，只是没有找到位置。
$ echo $PATH
/home/cymode/perl5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/node-v6.3.1-linux-x64/bin/

上面是环境变量位置。

那么默认的you-get是安装到了哪个位置呢？？
pip3 install you-get --install-option="--install-scripts=/usr/bin"`    在上述命令方式后，用这条命令再安装，会覆盖么？

2、pip这个东西我用得很少，但最后两行的提示也太“顽固”了，总是提示我有新版本，我用它提示的命令去更新，却还是有这个提示。请大神赐教如何办？（我在网上就相应的问题查了帖子，可是居多都是顾左右而言它……）

3、更新之后pip3 list查看了一下you-get的命令版本，发现并不是最新的555,而是486，那么如何变成最新的？

**Comment by zhangn1985** [comment]
那是提示pip有更新。

**Comment by linux0ne** [comment]
@zhangn1985 朋友，可否告诉我怎么更新它，来解决这个问题呢？就像我描述的，我在网上找了一些方法，可能没找对，都不好用。

另外，如果找到那个you-get命令呢？

**Comment by linux0ne** [comment]
@zhangn1985 

我用下面的命令安装了一下，准备安装到/usr/bin的位置上，结果出现了下面的错误：
cymode@HPLinux:~$ sudo !!
sudo pip3 install you-get --install-option="--install-scripts=/usr/bin"
[sudo] cymode 的密码： 
/usr/lib/python3/dist-packages/pip/commands/install.py:198: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
The directory '/home/cymode/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/cymode/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): you-get in ./.local/lib/python3.5/site-packages
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
cymode@HPLinux:~$

**Comment by zhangn1985** [comment]
pip3 install --upgrade you-get --user

~/.local/bin/

**Comment by cnbeining** [comment]
pip 不能用sudo。


使用pip install后 你的binary应该就能使用。

默认我记得是在啥地方有个softlink来着。。。

**Comment by soimort** [comment]
1. 如果是通过Linux发行版的包管理器安装的pip，就让包管理器来升级pip。不要使用pip自己提示的那个更新命令。
2. 把 `~/.local/bin` 加到路径中。

**Comment by linux0ne** [comment]
@soimort 
谢谢，解决了，我学到很多，感谢。另外，我的apt源里关于pip的版本最高就是8.1.1的，没有办法用apt-get来升级了，看来只有找个稳当点儿的源来升级了。
