### ISSUE TITLE
openwrt 上移植  下载编码不支持unicode 

### ISSUE THREAD

**Issue by goubuntu** [soimort/you-get#1457]
openwrt 系统已按照提示设置了LC_CTYPE  且设置的输出重命名 -O  但是提示仍为错误

root@OpenWrt:~# you-get -o /mnt/tfcard/ -O RTZ.flv 'http://v.youku.com/v_show/id_XMTc1Nzk2Mzg2OA==.html' 
title:               Snooker English Open 2016 - R2 -Ding vs Meixiwen
stream:
    - format:        hd2
      container:     flv
      size:          713.6 MiB (748235383 bytes)
    # download-with: you-get --format=hd2 [URL]

Downloading Snooker English Open 2016 - R2 -Ding vs Meixiwen.flv ...
you-get: [error] oops, the current environment does not seem to support Unicode.
you-get: please set it to a UTF-8-aware locale first,
you-get: so as to save the video (with some Unicode characters) correctly.
you-get: you can do it like this:
you-get:     (Windows)    % chcp 65001 
you-get:     (Linux)      $ LC_CTYPE=en_US.UTF-8

**Comment by soimort** [comment]
先确认一下 `locale -a` 有没有支持 UTF-8 的编码。
