### ISSUE TITLE
搜狐视频连接无响应

### ISSUE THREAD

**Issue by lcdtyph** [soimort/you-get#1473]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:
$ you-get -i --debug http://tv.sohu.com/20161013/n470208193.shtml

我等了半个小时左右还是没有输出……

在搜狐首页随便点了几个视频都是一样的= =
跪求修复=￣ω￣=

**Comment by soimort** [comment]
@soimort-bot Test this: http://tv.sohu.com/20161013/n470208193.shtml

**Comment by lcdtyph** [comment]
抱歉……我更新了最新的python3然后就正常了
