### ISSUE TITLE
爱课程网解析出错

### ISSUE THREAD

**Issue by fanweiya** [soimort/you-get#1474]
解析成了图片

> 
> you-get http://www.icourses.cn/coursestatic/course_3622.html
> Site:       icourses.cn
> Title:      ff808081-3b65fbac-013b-6b39532f-1644
> Type:       JPEG Image (image/jpeg)
> Size:       0.01 MiB (6754 Bytes)
> 
> Downloading ff808081-3b65fbac-013b-6b39532f-1644.jpg ...
>  100% (  0.0/  0.0MB) ├█████████████████████████████████████████┤[1/1]  533  B/s
>

**Comment by liushuyu** [comment]
However, it works on mine
```
liushuyu@liushuyu ~/D/you-get (icourses) [1]> ./you-get -i "http://www.icourses.cn/coursestatic/course_3622.html"
[WARNING] Switching to playlist mode!
Site:       icourses.cn
Title:      生物化学 模块一 第1单元 绪论
Type:       Flash video (video/x-flv)
Size:       138.1 MiB (144812622 Bytes)

Site:       icourses.cn
Title:      生物化学 模块一 第1单元 蛋白质的化学-1
Type:       Flash video (video/x-flv)
Size:       190.8 MiB (200064731 Bytes)

Site:       icourses.cn
Title:      生物化学 模块一 第1单元 蛋白质的化学-2
Type:       Flash video (video/x-flv)
Size:       177.32 MiB (185933009 Bytes)
.......
```

**Comment by liushuyu** [comment]
@fanweiya If you want to identify the problem, please run `you-get` in debug mode like
```
you-get -d <url>
```
Otherwise, I won't know what is going on at your side

**Comment by fanweiya** [comment]
@liushuyu 
> you-get -d "http://www.icourses.cn/coursestatic/course_3622.html"
> [DEBUG] get_content: http://www.icourses.cn/coursestatic/course_3622.html
> Site:       icourses.cn
> Title:      ff808081-3b65fbac-013b-6b39532f-1644
> Type:       JPEG Image (image/jpeg)
> Size:       0.01 MiB (6754 Bytes)
> 
> Downloading ff808081-3b65fbac-013b-6b39532f-1644.jpg ...
>  0.0% (  0.0/  0.0MB) ├─────────────────────────────────────────┤[1/1]

**Comment by cnbeining** [comment]
@fanweiya 您是否正在使用本项目的最新Github版本的代码？对此网站的支持仅于最近添加，有可能还未在```PIP```上部署分发。

**Comment by liushuyu** [comment]
> @fanweiya 您是否正在使用本项目的最新Github版本的代码？对此网站的支持仅于最近添加，有可能还未在 `PIP` 上部署分发。

No, even Git `master` branch is not merged. It is still a PR ( #1472 ).

**Comment by fanweiya** [comment]
@liushuyu 明白啦！感谢

**Comment by gjjpkc** [comment]
@fanweiya 怎么下载啊，你Q是多少啊？

**Comment by cnbeining** [comment]
@gjjpkc 337845818  请勿挖坟。
