### ISSUE TITLE
爱奇艺彻底挂了

### ISSUE THREAD

**Issue by ztytian** [soimort/you-get#1475]
汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 https://github.com/soimort/you-get/wiki/FAQ 中的指引进行了操作.
- [x] 您的问题没有在https://github.com/soimort/you-get/issues , https://github.com/soimort/you-get/wiki/FAQ 或 https://github.com/soimort/you-get/wiki/Known-Bugs 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

-------debug logs------------
you-get http://www.iqiyi.com/v_19rr98nw00.html --debug
site:                爱奇艺 (Iqiyi)
title:               龙珠超第63集
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://cache.m.iqiyi.com/dc/dt/2669ebdx2f740c2fx777a6171/20161023/30/e8/68c086ea67df2410d19215eb3b47ff1c.m3u8?qd_sc=ad1b56eb89e90ef08e939716a08b4318&t_sign=-0-76f90cbd92f94a2e925d83e8ccd22cb7-555965100_04022000001000000000_17 -c copy -bsf:a aac_adtstoasc 龙珠超第63集.mp4
ffmpeg version 3.1.5 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.38)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.1.5 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --disable-lzma --enable-vda
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
[hls,applehttp @ 0x7fa259000000] No longer receiving playlist 0
[mpegts @ 0x7fa259801000] PES packet size mismatch
[hls,applehttp @ 0x7fa259000000] Now receiving playlist 0, segment 0
Input #0, hls,applehttp, from 'http://cache.m.iqiyi.com/dc/dt/2669ebdx2f740c2fx777a6171/20161023/30/e8/68c086ea67df2410d19215eb3b47ff1c.m3u8?qd_sc=ad1b56eb89e90ef08e939716a08b4318&t_sign=-0-76f90cbd92f94a2e925d83e8ccd22cb7-555965100_04022000001000000000_17':
  Duration: 00:23:21.00, start: 0.000000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv), 1280x720, 23 fps, 23.98 tbr, 90k tbn, 23 tbc
    Stream #0:1: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 62 kb/s
[mp4 @ 0x7fa258800600] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
    Last message repeated 1 times
Output #0, mp4, to '龙珠超第63集.mp4':
  Metadata:
    encoder         : Lavf57.41.100
    Stream #0:0: Video: hevc ([35][0][0][0] / 0x0023), yuv420p(tv), 1280x720, q=2-31, 23 fps, 23.98 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (HE-AAC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 62 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   13 fps=0.0 q=-1.0 size=      14kB time=00:00:00.55 bitrate= 206.5kbits/frame=   25 fps= 24 q=-1.0 size=      18kB time=00:00:01.11 bitrate= 134.5kbits/frame=   37 fps= 24 q=-1.0 size=      28kB time=00:00:01.57 bitrate= 144.0kbits/frame=   48 fps= 23 q=-1.0 size=      46kB time=00:00:02.13 bitrate= 177.8kbits/frame=   56 fps= 22 q=-1.0 size=      84kB time=00:00:02.64 bitrate= 258.8kbits/frame=   72 fps= 24 q=-1.0 size=     178kB time=00:00:03.11 bitrate= 468.0kbits/frame=   80 fps= 22 q=-1.0 size=     238kB time=00:00:03.62 bitrate= 537.4kbits/frame=   96 fps= 24 q=-1.0 size=     361kB time=00:00:04.13 bitrate= 716.2kbits/frame=  109 fps= 24 q=-1.0 size=     436kB time=00:00:04.64 bitrate= 769.6kbits/[mp4 @ 0x7fa258800600] Non-monotonous DTS in output stream 0:1; previous: 223232, current: 0; changing to 223233. This may result in incorrect timestamps in the output file.
frame=  121 fps= 24 q=-1.0 size=     492kB time=00:00:05.10 bitrate= 789.5kbits/[mp4 @ 0x7fa258800600] Non-monotonous DTS in output stream 0:1; previous: 223233, current: 2048; changing to 223234. This may result in incorrect timestamps in the output file.
frame=  121 fps= 19 q=-1.0 size=     492kB time=00:00:05.10 bitrate= 789.5kbits/[mp4 @ 0x7fa258800600] Non-monotonous DTS in output stream 0:1; previous: 223234, current: 4096; changing to 223235. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fa258800600] Non-monotonous DTS in output stream 0:0; previous: 450450, current: 0; changing to 450451. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fa258800600] Non-monotonous DTS in output stream 0:0; previous: 450451, current: 3753; changing to 450452. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fa258800600] Non-monotonous DTS in output stream 0:0; previous: 450452, current: 7507; changing to 450453. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fa258800600] Non-monotonous DTS in output stream 0:0; previous: 450453, current: 11261; changing to 450454. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fa258800600] Non-monotonous DTS in output stream 0:1; previous: 223235, current: 6144; changing to 223236. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fa258800600] Non-monotonous DTS in output stream 0:1; previous: 223236, current: 8192; changing to 223237. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fa258800600] Non-monotonous DTS in output stream 0:0; previous: 450454, current: 15015; changing to 450455. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fa258800600] Non-monotonous DTS in output stream 0:0; previous: 450455, current: 18768; changing to 450456. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fa258800600] Non-monotonous DTS in output stream 0:1; previous: 223237, current: 10240; changing to 223238. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fa258800600] Non-monotonous DTS in output stream 0:1; previous: 223238, current: 12288; changing to 223239. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7fa258800600] Non-monotonous DTS in output stream 0:0; previous: 450456, current: 22522; changing to 450457. This may result in incorrect timestamps in the output file.
[SOME OUTPUT OMITED]
current: 186368; changing to 15970396. This may result in incorrect timestamps in the output file.
然后无限循环，最终Control-C终止，只能下载到6分钟的视频。
而且只解析到了720P，1080P飞哪去了？

好，结论：爱奇艺那帮子人不知道干了什么导致ffmpeg无法正常录制视频流或者是you-get没有给ffmpeg输入正确的指令，我感觉是前者，他们现在用的是CrossBridge播放器，貌似很难搞的样子。。。

**Comment by ztytian** [comment]
。。。没人吗

**Comment by ztytian** [comment]
。。。没人吗

**Comment by cnbeining** [comment]
这种小事你要是见识过B站的后黑应该不会陌生吧。

反正害人害己呗。

**Comment by ztytian** [comment]
B站的sign api啊。。

**Comment by ztytian** [comment]
不是这个问题，这个是爱奇艺的版权视频，而且可以在网页上观看到26分钟，但是下载只能下载到6分钟

**Comment by ilools** [comment]
ffmpeg 3.2下这个 bug 消失，@soimort 更新下 ffmpeg 到最新 3.2即可

**Comment by ztytian** [comment]
那这个改为爱奇艺无法下载1080P好了

**Comment by v1-hermit** [comment]
iqiyi恐怕是遇到难关了，越来越多视频下不了，4个月没有进展

**Comment by nxtreaming** [comment]
这么执着下载视频干什么？ 国内的视频没有多少可以值得下载保存的。

**Comment by lzy0699** [comment]
我现在下载的办法是：用you-get获取real URL，然后用livestreamer下载成TS文件，最后再用ffmpeg封装成MKV格式(无法封装成MP4格式)。
此方法的好处是不需要重新编码视频（我感觉直接用you-get下载iqiyi是用ffmpeg重新编码了，我也不是很懂，如果说错了请指正），速度快。

**Comment by cnbeining** [comment]
本项目的ffmpeg使用仅为封装，并非进行编码转换。

**Comment by lzy0699** [comment]
@cnbeining
多谢指正。我用ffmpeg在线封装速度太慢了，用livestreamer可以全速，ffmpeg的速度约是livestreamer的1//5，不知道是不是我网络的原因。

**Comment by damoguyanzero** [comment]
@lzy0699
请教一下，如何用livestreamer把real URL下载为ts文件？

**Comment by lzy0699** [comment]
类似这样的：
livestreamer "hls://realURL" best -o x:\downloads\Downloads.TS
具体你可以看一下livestreamer个官方文档

**Comment by ztytian** [comment]
Reak URL就是m3u8咯？

**Comment by lzy0699** [comment]
@ztytian 
就是you-get加-u参数得出来的地址，比如：
http://cache.m.iqiyi.com/dc/dt/a9a3255bx2f41910ex777a6171/20161106/ff/4e/411d8317e93df7f3c628b6ebf656bb73.m3u8?np_tag=nginx_part_tag&qd_sc=58ad95ba9aef9976941a81202e765a17&t_sign=-0-76f90cbd92f94a2e925d83e8ccd22cb7-563565600_04022000001000000000_17

**Comment by cnbeining** [comment]
好像本issue被新的issue替代了。

暂时关闭，如果问题存在，再开。
