### ISSUE TITLE
想共享代码，请问有没有什么约定的规范？

### ISSUE THREAD

**Issue by magicsky** [soimort/you-get#1476]
比如能不能用第三方库什么的？等等这些方面有没有什么约定？

**Comment by cnbeining** [comment]
根据我粗浅的法律理解：

```You-get``` 按照MIT协议进行授权，授权协议文本可于 https://github.com/soimort/you-get/blob/develop/LICENSE.txt  进行查询。

在协议许可范围内，您可以对本项目进行您所希望的使用。如需其他许可，请向作者进行申请以获得更加宽松的许可。请注意您有可能需要问询多人以避免有可能出现的授权问题。

Yours,
