### ISSUE TITLE
请问用爬虫去下载YouTube视频会不会被ban？

### ISSUE THREAD

**Issue by ichenfujun** [soimort/you-get#1489]
我把you-get集成到scrapy中，用scrapy抓取YouTube网页链接，然后交给you-get进行分析并下载视频，这样会不会导致YouTube封掉IP？
谢谢！

**Comment by cnbeining** [comment]
会。而且封的很快。打码平台不一定能解决问题。

**Comment by ichenfujun** [comment]
请问有解决的办法或思路吗？ 谢谢！

**Comment by cnbeining** [comment]
多换点IP 多打码 这世界上还有钱解决不了的问题么。如果有 一定是钱没到位。

**Comment by ichenfujun** [comment]
多打码是什么意思，验证码？

**Comment by cnbeining** [comment]
我又想了下 Youtube封IP是封死的。

找各种代理服务平衡压力吧 当然绝大多数这种服务是禁止爬Google相关的。。。祝你好运。
