### ISSUE TITLE
you-get 无法下载 CNTV 视频了，包括最新版 0.4.555

### ISSUE THREAD

**Issue by fgdsgfghf** [soimort/you-get#1491]
请使用`--debug`运行，并将输出粘贴在下面:

C:\>you-get --debug http://tv.cntv.cn/video/C33921/a4e1997343f64e6ea4bbb68605211
d93
Site:       CNTV.com
Title:      《长江新闻号》 20151203
Type:       MPEG-4 video (video/mp4)
Size:       92.12 MiB (96596239 Bytes)

Downloading 《长江新闻号》 20151203.mp4 ...
 0.0% (  0.0/ 92.1MB) ├────────────────────────────
 0.3% (  0.2/ 92.1MB) ├────────────────────────────
 0.5% (  0.5/ 92.1MB) ├────────────────────────────
 0.8% (  0.8/ 92.1MB) ├────────────────────────────
 1.1% (  1.0/ 92.1MB) ├█───────────────────────────
 1.4% (  1.2/ 92.1MB) ├█───────────────────────────
 1.6% (  1.5/ 92.1MB) ├█───────────────────────────
 1.9% (  1.8/ 92.1MB) ├█───────────────────────────
 2.2% (  2.0/ 92.1MB) ├█───────────────────────────
 2.4% (  2.2/ 92.1MB) ├█───────────────────────────
 2.7% (  2.5/ 92.1MB) ├█───────────────────────────
 3.0% (  2.8/ 92.1MB) ├██──────────────────────────
 3.3% (  3.0/ 92.1MB) ├██──────────────────────────
 3.5% (  3.2/ 92.1MB) ├██──────────────────────────
 3.8% (  3.5/ 92.1MB) ├██──────────────────────────
 4.1% (  3.8/ 92.1MB) ├██──────────────────────────
 4.3% (  4.0/ 92.1MB) ├██──────────────────────────
 4.6% (  4.2/ 92.1MB) ├██──────────────────────────
 4.9% (  4.5/ 92.1MB) ├██──────────────────────────
 5.2% (  4.8/ 92.1MB) ├███─────────────────────────
 5.4% (  5.0/ 92.1MB) ├███─────────────────────────
 5.7% (  5.2/ 92.1MB) ├███─────────────────────────
 6.0% (  5.5/ 92.1MB) ├███─────────────────────────
 6.2% (  5.8/ 92.1MB) ├███─────────────────────────
 6.5% (  6.0/ 92.1MB) ├███─────────────────────────
 6.8% (  6.2/ 92.1MB) ├███─────────────────────────
 7.1% (  6.5/ 92.1MB) ├███─────────────────────────
 7.3% (  6.8/ 92.1MB) ├███─────────────────────────
 7.6% (  7.0/ 92.1MB) ├███─────────────────────────
 7.9% (  7.2/ 92.1MB) ├███─────────────────────────
 8.1% (  7.5/ 92.1MB) ├████────────────────────────
 8.4% (  7.8/ 92.1MB) ├████────────────────────────
 8.7% (  8.0/ 92.1MB) ├████────────────────────────
 9.0% (  8.2/ 92.1MB) ├████────────────────────────
 9.2% (  8.5/ 92.1MB) ├████────────────────────────
 9.5% (  8.8/ 92.1MB) ├████────────────────────────
 9.8% (  9.0/ 92.1MB) ├████────────────────────────
10.0% (  9.2/ 92.1MB) ├█████───────────────────────
10.3% (  9.5/ 92.1MB) ├█████───────────────────────
10.6% (  9.8/ 92.1MB) ├█████───────────────────────
10.9% ( 10.0/ 92.1MB) ├█████───────────────────────
11.1% ( 10.2/ 92.1MB) ├█████───────────────────────
11.4% ( 10.5/ 92.1MB) ├█████───────────────────────
11.7% ( 10.8/ 92.1MB) ├█████───────────────────────
11.9% ( 11.0/ 92.1MB) ├█████───────────────────────
12.2% ( 11.2/ 92.1MB) ├█████───────────────────────
12.5% ( 11.5/ 92.1MB) ├█████───────────────────────
12.8% ( 11.8/ 92.1MB) ├█████───────────────────────
13.0% ( 12.0/ 92.1MB) ├██████──────────────────────
13.3% ( 12.2/ 92.1MB) ├██████──────────────────────
13.6% ( 12.5/ 92.1MB) ├██████──────────────────────
13.8% ( 12.8/ 92.1MB) ├██████──────────────────────
14.1% ( 13.0/ 92.1MB) ├██████──────────────────────
14.4% ( 13.2/ 92.1MB) ├██████──────────────────────
14.7% ( 13.5/ 92.1MB) ├██████──────────────────────
14.9% ( 13.8/ 92.1MB) ├██████──────────────────────
15.2% ( 14.0/ 92.1MB) ├███████─────────────────────
15.5% ( 14.2/ 92.1MB) ├███████─────────────────────
15.7% ( 14.5/ 92.1MB) ├███████─────────────────────
16.0% ( 14.8/ 92.1MB) ├███████─────────────────────
16.3% ( 15.0/ 92.1MB) ├███████─────────────────────
16.6% ( 15.2/ 92.1MB) ├███████─────────────────────
16.8% ( 15.5/ 92.1MB) ├███████─────────────────────
17.1% ( 15.8/ 92.1MB) ├███████─────────────────────
17.4% ( 16.0/ 92.1MB) ├███████─────────────────────
17.6% ( 16.2/ 92.1MB) ├███████─────────────────────
17.9% ( 16.5/ 92.1MB) ├███████─────────────────────
18.2% ( 16.8/ 92.1MB) ├████████────────────────────
18.5% ( 17.0/ 92.1MB) ├████████────────────────────
18.6% ( 17.2/ 92.1MB) ├████████────────────────────
18.9% ( 17.4/ 92.1MB) ├████████────────────────────
19.2% ( 17.7/ 92.1MB) ├████████────────────────────
19.4% ( 17.9/ 92.1MB) ├████████────────────────────
19.7% ( 18.2/ 92.1MB) ├████████────────────────────
20.0% ( 18.4/ 92.1MB) ├█████████───────────────────
20.3% ( 18.7/ 92.1MB) ├█████████───────────────────
20.5% ( 18.9/ 92.1MB) ├█████████───────────────────
20.8% ( 19.2/ 92.1MB) ├█████████───────────────────
21.1% ( 19.4/ 92.1MB) ├█████████───────────────────
21.3% ( 19.7/ 92.1MB) ├█████████───────────────────
21.6% ( 19.9/ 92.1MB) ├█████████───────────────────
21.9% ( 20.2/ 92.1MB) ├█████████───────────────────
22.2% ( 20.4/ 92.1MB) ├██████████──────────────────
22.4% ( 20.7/ 92.1MB) ├██████████──────────────────
22.7% ( 20.9/ 92.1MB) ├██████████──────────────────
23.0% ( 21.2/ 92.1MB) ├██████████──────────────────
23.2% ( 21.4/ 92.1MB) ├██████████──────────────────
23.5% ( 21.7/ 92.1MB) ├██████████──────────────────
23.8% ( 21.9/ 92.1MB) ├██████████──────────────────
24.1% ( 22.2/ 92.1MB) ├██████████──────────────────
24.3% ( 22.4/ 92.1MB) ├██████████──────────────────
24.6% ( 22.7/ 92.1MB) ├██████████──────────────────
24.9% ( 22.9/ 92.1MB) ├██████████──────────────────
25.1% ( 23.2/ 92.1MB) ├███████████─────────────────
25.4% ( 23.4/ 92.1MB) ├███████████─────────────────
25.7% ( 23.7/ 92.1MB) ├███████████─────────────────
26.0% ( 23.9/ 92.1MB) ├███████████─────────────────
26.2% ( 24.2/ 92.1MB) ├███████████─────────────────
26.5% ( 24.4/ 92.1MB) ├███████████─────────────────
26.8% ( 24.7/ 92.1MB) ├███████████─────────────────
27.0% ( 24.9/ 92.1MB) ├████████████────────────────
27.3% ( 25.2/ 92.1MB) ├████████████────────────────
27.6% ( 25.4/ 92.1MB) ├████████████────────────────
27.9% ( 25.7/ 92.1MB) ├████████████────────────────
28.1% ( 25.9/ 92.1MB) ├████████████────────────────
28.4% ( 26.2/ 92.1MB) ├████████████────────────────
28.7% ( 26.4/ 92.1MB) ├████████████────────────────
28.9% ( 26.7/ 92.1MB) ├████████████────────────────
29.2% ( 26.9/ 92.1MB) ├████████████────────────────
29.5% ( 27.2/ 92.1MB) ├████████████────────────────
29.8% ( 27.4/ 92.1MB) ├████████████────────────────
30.0% ( 27.7/ 92.1MB) ├█████████████───────────────
30.3% ( 27.9/ 92.1MB) ├█████████████───────────────
30.6% ( 28.2/ 92.1MB) ├█████████████───────────────
30.8% ( 28.4/ 92.1MB) ├█████████████───────────────
─────────────┤[2/6]    2 MB/syou-get: version 0.4.555, a tiny down
loader that scrapes the web.
you-get: ['http://tv.cntv.cn/video/C33921/a4e1997343f64e6ea4bbb68605211d93']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1348, in main
  File "src\you_get\common.py", line 1261, in script_main
  File "src\you_get\common.py", line 1077, in download_main
  File "src\you_get\common.py", line 1341, in any_download
  File "src\you_get\extractors\cntv.py", line 46, in cntv_download
  File "src\you_get\extractors\cntv.py", line 30, in cntv_download_by_id
  File "src\you_get\common.py", line 740, in download_urls
  File "src\you_get\common.py", line 492, in url_save
  File "http\client.py", line 433, in read
  File "http\client.py", line 473, in readinto
  File "socket.py", line 571, in readinto
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
you-get returned -1
[在这里粘贴完整日志]
C:\>you-get http://tv.cntv.cn/video/C33921/a4e1997343f64e6ea4bbb68605211d93
Site:       CNTV.com
Title:      《长江新闻号》 20151203
Type:       MPEG-4 video (video/mp4)
Size:       92.12 MiB (96596239 Bytes)

Downloading 《长江新闻号》 20151203.mp4 ...
 0.0% (  0.0/ 92.1MB) ├────────────────────────────
18.6% ( 17.2/ 92.1MB) ├████████────────────────────
30.8% ( 28.4/ 92.1MB) ├█████████████───────────────
31.1% ( 28.7/ 92.1MB) ├█████████████───────────────
31.4% ( 28.9/ 92.1MB) ├█████████████───────────────
31.7% ( 29.2/ 92.1MB) ├█████████████───────────────
31.9% ( 29.4/ 92.1MB) ├█████████████───────────────
32.2% ( 29.7/ 92.1MB) ├██████████████──────────────
32.5% ( 29.9/ 92.1MB) ├██████████████──────────────
32.7% ( 30.2/ 92.1MB) ├██████████████──────────────
33.0% ( 30.4/ 92.1MB) ├██████████████──────────────
33.3% ( 30.7/ 92.1MB) ├██████████████──────────────
33.6% ( 30.9/ 92.1MB) ├██████████████──────────────
33.8% ( 31.2/ 92.1MB) ├██████████████──────────────
34.1% ( 31.4/ 92.1MB) ├██████████████──────────────
34.4% ( 31.7/ 92.1MB) ├██████████████──────────────
34.6% ( 31.9/ 92.1MB) ├██████████████──────────────
34.9% ( 32.2/ 92.1MB) ├██████████████──────────────
35.2% ( 32.4/ 92.1MB) ├███████████████─────────────
35.5% ( 32.7/ 92.1MB) ├███████████████─────────────
35.7% ( 32.9/ 92.1MB) ├███████████████─────────────
36.0% ( 33.2/ 92.1MB) ├███████████████─────────────
36.3% ( 33.4/ 92.1MB) ├███████████████─────────────
36.5% ( 33.7/ 92.1MB) ├███████████████─────────────
36.8% ( 33.9/ 92.1MB) ├███████████████─────────────
37.1% ( 34.2/ 92.1MB) ├████████████████────────────
37.4% ( 34.4/ 92.1MB) ├████████████████────────────
37.6% ( 34.7/ 92.1MB) ├████████████████────────────
37.9% ( 34.9/ 92.1MB) ├████████████████────────────
38.0% ( 35.0/ 92.1MB) ├████████████████────────────
38.2% ( 35.2/ 92.1MB) ├████████████████────────────
38.5% ( 35.5/ 92.1MB) ├████████████████────────────
38.8% ( 35.7/ 92.1MB) ├████████████████────────────
39.1% ( 36.0/ 92.1MB) ├████████████████────────────
39.3% ( 36.2/ 92.1MB) ├████████████████────────────
39.6% ( 36.5/ 92.1MB) ├████████████████────────────
39.9% ( 36.7/ 92.1MB) ├████████████████────────────
40.1% ( 37.0/ 92.1MB) ├█████████████████───────────
40.4% ( 37.2/ 92.1MB) ├█████████████████───────────
40.7% ( 37.5/ 92.1MB) ├█████████████████───────────
41.0% ( 37.7/ 92.1MB) ├█████████████████───────────
41.2% ( 38.0/ 92.1MB) ├█████████████████───────────
41.5% ( 38.2/ 92.1MB) ├█████████████████───────────
41.8% ( 38.5/ 92.1MB) ├█████████████████───────────
42.0% ( 38.7/ 92.1MB) ├██████████████████──────────
42.3% ( 39.0/ 92.1MB) ├██████████████████──────────
42.6% ( 39.2/ 92.1MB) ├██████████████████──────────
42.9% ( 39.5/ 92.1MB) ├██████████████████──────────
43.1% ( 39.7/ 92.1MB) ├██████████████████──────────
─────────────┤[3/6]    3 MB/syou-get: [error] oops, something went
 wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [用抓包工具截获的来看，CNTV 不在使用 mp4 格式了，全部改用 ts 格式了，而且每个 ts 文件非常小，数量又很多，使用 you-get -i 分析却依然显示 mp4 ，并且不能识别 流畅 标清 高清 3个清晰度]
C:\>you-get -i http://tv.cntv.cn/video/C33921/a4e1997343f64e6ea4bbb68605211d93
Site:       CNTV.com
Title:      《长江新闻号》 20151203
Type:       MPEG-4 video (video/mp4)
Size:       92.12 MiB (96596239 Bytes)

**Comment by gclsoft** [comment]
Youtube也是这样,`远程主机强迫关闭了一个现有的连接`,用的是最新版的代码,要怎么解决?

**Comment by gclsoft** [comment]
https://github.com/soimort/you-get/issues/1496

**Comment by rosynirvana** [comment]
```
you-get -d http://tv.cntv.cn/video/C33921/a4e1997343f64e6ea4bbb68605211d93
[DEBUG] get_response: http://vdn.apps.cntv.cn/api/getHttpVideoInfo.do?pid=a4e1997343f64e6ea4bbb68605211d93
[DEBUG] url_info: http://vod.cntv.lxdns.com/flash/mp4video47/TMS/2015/12/04/a4e1997343f64e6ea4bbb68605211d93_h264418000nero_aac32-1.mp4
[DEBUG] url_info: http://vod.cntv.lxdns.com/flash/mp4video47/TMS/2015/12/04/a4e1997343f64e6ea4bbb68605211d93_h264418000nero_aac32-2.mp4
[DEBUG] url_info: http://vod.cntv.lxdns.com/flash/mp4video47/TMS/2015/12/04/a4e1997343f64e6ea4bbb68605211d93_h264418000nero_aac32-3.mp4
[DEBUG] url_info: http://vod.cntv.lxdns.com/flash/mp4video47/TMS/2015/12/04/a4e1997343f64e6ea4bbb68605211d93_h264418000nero_aac32-4.mp4
[DEBUG] url_info: http://vod.cntv.lxdns.com/flash/mp4video47/TMS/2015/12/04/a4e1997343f64e6ea4bbb68605211d93_h264418000nero_aac32-5.mp4
[DEBUG] url_info: http://vod.cntv.lxdns.com/flash/mp4video47/TMS/2015/12/04/a4e1997343f64e6ea4bbb68605211d93_h264418000nero_aac32-6.mp4
Site:       CNTV.com
Title:      《长江新闻号》 20151203
Type:       MPEG-4 video (video/mp4)
Size:       92.12 MiB (96596239 Bytes)

Downloading 《长江新闻号》 20151203.mp4 ...
 100% ( 92.1/ 92.1MB) ├█████████████████████████████████████████┤[6/6]    3 MB/s
```
