### ISSUE TITLE
关于Bilibili的番剧无法下载的问题

### ISSUE THREAD

**Issue by woolen-sheep** [soimort/you-get#1499]
log：
```
get -d http://bangumi.bilibili.com/anime/v/96039
[DEBUG] get_content: http://bangumi.bilibili.com/anime/v/96039
[DEBUG] get_content: http://www.bilibili.com/video/av6922031/
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/v/96039']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1348, in main
  File "src\you_get\common.py", line 1261, in script_main
  File "src\you_get\common.py", line 1077, in download_main
  File "src\you_get\common.py", line 1341, in any_download
  File "src\you_get\extractors\bilibili.py", line 135, in bilibili_download
AssertionError
you-get returned -1
```

> 如log所示，在获取bilibili的番剧内容（如http://bangumi.bilibili.com/anime/v/96039【夏目友人帐】）时，会出现如上错误。求尽快解决。
> [舔 :icecream:!]

**Comment by soimort** [comment]
![screenshot from 2016-11-05 12-19-40](https://cloud.githubusercontent.com/assets/342945/20029650/48e11182-a352-11e6-9520-0c9e047ce2f6.png)
![screenshot from 2016-11-05 12-20-38](https://cloud.githubusercontent.com/assets/342945/20029651/48e29110-a352-11e6-94ac-b600a5a50db4.png)

**Comment by woolen-sheep** [comment]
http://bangumi.bilibili.com/anime/v/96039 这个网址是没有问题的，我可以观看
![image](https://cloud.githubusercontent.com/assets/16986942/20029663/774fd3c4-a38d-11e6-8a43-f7c4c5673307.png)

**Comment by woolen-sheep** [comment]
可能因为你在国外？

**Comment by soimort** [comment]
请尝试使用 0.4.575。

**Comment by woolen-sheep** [comment]
啊，那我还是算了，懒得编译。。。latest release没有预编译版本

**Comment by soimort** [comment]
> 啊抱歉，develop branch是？

请通过 pip 安装：

    $ pip3 install --upgrade git+https://github.com/soimort/you-get@develop

**Comment by shikkoku** [comment]
@soimort 

我用pip安装完运行you-get提示failed to create process.Windows 10 x64平台

**Comment by shikkoku** [comment]
> you-get-script -d http://bangumi.bilibili.com/anime/v/88835
> [DEBUG] get_content: http://bangumi.bilibili.com/anime/v/88835
> [DEBUG] get_content: http://www.bilibili.com/video/av4843977/
> you-get: version 0.4.575, a tiny downloader that scrapes the web.
> you-get: ['http://bangumi.bilibili.com/anime/v/88835']
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Python35-32\Scripts\you-get-script.py", line 9, in <module>
>     load_entry_point('you-get==0.4.575', 'console_scripts', 'you-get')()
>   File "C:\Program Files (x86)\Python35-32\Scripts\you_get\__main__.py", line 92, in main
>     main(**kwargs)

发现you-get-script可以运行，但是报错。
