### ISSUE TITLE
[Failed] YouTube

### ISSUE THREAD

**Issue by LarkinZero** [soimort/you-get#1502]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get -x http://127.0.0.1:9999 --debug https://www.youtube.com/watch?v=S63PKcrKLeI
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=S63PKcrKLeI
you-get: version 0.4.575, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=S63PKcrKLeI']
Traceback (most recent call last):
  File "c:\python3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python3\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python3\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python3\lib\site-packages\you_get\common.py", line 1388, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\python3\lib\site-packages\you_get\common.py", line 1301, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\python3\lib\site-packages\you_get\common.py", line 1117, in download_main
    download(url, **kwargs)
  File "c:\python3\lib\site-packages\you_get\common.py", line 1381, in any_download
    m.download(url, **kwargs)
  File "c:\python3\lib\site-packages\you_get\extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "c:\python3\lib\site-packages\you_get\extractors\youtube.py", line 151, in prepare
    stream_list = video_info['url_encoded_fmt_stream_map'][0].split(',')
KeyError: 'url_encoded_fmt_stream_map'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> 其他只有在下载这个视频的时候报错，https://www.youtube.com/watch?v=S63PKcrKLeI，其他视频页面正常

**Comment by soimort** [comment]
The interesting thing is that you will be able to download the video if you specify `--itag=137`:

```
$ you-get -di --itag=137 "https://www.youtube.com/watch?v=S63PKcrKLeI" 
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=S63PKcrKLeI
[DEBUG] get_content: https://www.youtube.com/watch?v=S63PKcrKLeI
[DEBUG] get_content: https://s.ytimg.com/yts/jsbin/player-da_DK-vfl_kDfmi/base.js
site:                YouTube
title:               INFINITE WARFARE ZOMBIES - MAIN EASTER EGG BOSS FIGHT GAMEPLAY WALKTHROUGH (ZOMBIES IN SPACELAND)
stream:
    - itag:          137
      container:     mp4
      quality:       1920x1080
      size:          6862.2 MiB (7195491278 bytes)
    # download-with: you-get --itag=137 [URL]
```

Somehow the decrypt algorithm generates an invalid signature for the default itag. I will look into this.
