### ISSUE TITLE
腾讯视频'output_json' is not defined

### ISSUE THREAD

**Issue by fan26a** [soimort/you-get#1506]
[root@iZ23ojwjlxgZ ~]#  you-get --debug --json http://v.qq.com/x/cover/yxfqt2th35m6kdb.html
{
    "site": "QQ.com",
    "streams": {
        "__default__": {
            "container": "mp4",
            "size": 415266909,
            "src": [
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.1.mp4?vkey=2ED3DDBB475F36A6BF039D788ED972815B7368948C5960BEDB8325AE7E30D44AC832F6E9B80EF7FD44FE0DAE58528EA2AB4BB45F14A58046D62C32B3499E9D2F475E86707377FFEE0078711E2B9948C4A58566DAEE3088B12F3EFBAE9124F4B9",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.2.mp4?vkey=67177CD966350566C019AA707D1612FB8BE812FDD88C7E6859F3088782B4C5347362EE47777E48391769AB6B6C8F1C4F13C8EC3EB603DCB0FD7F344D345704CDD1FF144514A702A34D4AE2C3C39827A956B104F2ADF17D5042303E2579C8C026",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.3.mp4?vkey=7FE0295324D36139B2DDC721552E4A06994C06EADFBDAF79D986DEFEF4924126963598E466F2E6ACC89511A0767A7980203C8C4EA088B27D602CA95AB5E1A4EDF7F51DD1E9B715966DEC711ABC99274820FF277087FF35043AB88D29E415F931",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.4.mp4?vkey=316ECFCFC080CAB4EDAB67393F6B8F49C314EBD7336D68FC69F3D35152A5F98B5B86873DED36438A4C393E2B30493F0F41F45D7CB2605CFD306059706E8307045FA7A6F6C31BC34B79A02112FA6E61B72BB6DDC039E83741C525FCECB52C02B0",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.5.mp4?vkey=BE791DD62A97AE558241C9E6AEABADA7AB37143EEBF8D341A1C0DEAA0E8756AA46353AD9B280D140960FC171E8E48350BB57A10CD0D4F2799D7E94B3D3E520A0FB5E9826BD800C80FFA5E38041BB7989C117C738A8DAD00B012FA026397266B9",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.6.mp4?vkey=3460C5088F321640F8471A7C11006CE2C6A58475BD3EA40AE516F25D6D23497E49924D1E805104211168D7FECF8A65BBFBCE2FC29CAD4FEEF8A62CC4CDD6CDE1826819AF4A6D14C40B6117796AAD8CD57FAC94B347111C30D0FF292BF8E5B001",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.7.mp4?vkey=5057B405C8664C1E05C197A2AEA8D935CBE9293078FEDFE1728E662821815E2D2137FD009B0AD41C7361D64A57A27ED36E2ED4662ACA0D52F7B36818DE4C4E3D8D91C2AA97D1DC3DD170D304056AB0A90F220E1C38BD998460DB54C40ED9E3F1",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.8.mp4?vkey=4CD9887E1E08CD62FEEAC4B5E65C421A6A267B1FF323C9157FEB63EEDA98DF3AE5A391E9FDB3DD0D1B2AC72EA98A3C7FC8EF244AB200FFB051726B228BD233F17A6AC96D3D6F29BF6671AFC4F9A2037EA8EE3467D65EC793EBE758384B36C877",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.9.mp4?vkey=DA92AA84271A9AFD92C1580081521078E928D2D34AA5E45BB7B9AE4B8092A1D0C8A49C4D7FFF651F4858EB96CF2B1984D9A46C2D628CA7E3CD0D8AB444DE05E88652CD6CD8A1D8E223135A36A65911A30CC28997F232108AB23A342BA52E12E2",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.10.mp4?vkey=5D3B4392964CFE5FF51BF5A1B5774FFB5DE3DE1C8A2CBB17566CF864784A3E4CDFFCE49DC7ACACC4F5D0C7A00EA6F0BEA3F684846CAD30AE15CA86B6325388F367D44D1629C4A3C10087D7C273B75F4B283FCEDBECD25E136B549E510DD85B89",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.11.mp4?vkey=1A4F1C5B95245E5FEC1ED0E67AE16573FDEF64EB8F20074A024A0DBB3662FD1000A9AD9776BB69997E3908950CC79B433E4A2A3B9D6B0616C35B77B4051DAEB86A4BB8FC2EFE0A8F3141EE9C941BD6B9972C279A9C347A102119FC4069D5E6DA",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.12.mp4?vkey=58CBF65B766EFCD7DDA2AB71F24BF04B728C9FF1E09B4A5BD1232F24CFE7F7B09FE7BC2449B335D6F5CE713ED0A6C86841F4A950DBD908DE8770953A7B53AA6152EE41C842CB4A7EC08E211E909FCC9386DCAE7F81B9113AD599803AE440CDF7",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.13.mp4?vkey=B50A570B9E5420D45B0FF06DAD7AFF890DF742431C40336C5D1D9D12DE66697C705E379C210A2ECAB5B4C10768B144C804705CCCA8BE626FCF671E95ECB34208419137D0A78BC0FE67DE1B33B6841C96DA13BD50705357A93E3AC54DEB03151F",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.14.mp4?vkey=7998E265CF756309ADC6E4B765BAF9A2C5143745D2E4721055024857BB46AAFBCC321F8A1D485AD996C1EA06CF68993CFFFB22189EEC91AAB174C12F9B58E03191F4CFEB0B193BC5DDBBD6C6ECD99DDC6B7DB2FEEC0491C4E6FD2A286F540ACC",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.15.mp4?vkey=648D2E47D70001A1B6886D3400817E61DAF9E95DCD91AC2CD132B777C80812B27285FACF58A6CEDE23DA415AC9296CD2DE2C1C4D659A977F8E4A745DCE7AF3680B0584C52A27303B57D6A10E686EEA64568EAD2F6F1C116A880F50ED52E7F803",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.16.mp4?vkey=3B9346A394CA40E2FA1C9793E8FDCDB0C37DC733695B25673496787575F1002E03DD1F258BA2AE2924BF5F346CA4FD78541CF186B559349899A64DC8E5DE416B814E9660117E9BAF226848BD37D057AA410BC6063F6ECFD76F4A7099B9075782",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.17.mp4?vkey=89B10A7C65BB96194422652AB3689598D532BB952D7DDA16E2DDBF415EA667EE715813EEF2B6EEB50479132A3FCF07AA46CE6E39E8865283457E7BB5552941A8537090CFFEFB63B838A6832AED713A41D4B78AE8D2C8F11984424D6A5BBB5C01",
                "http://183.131.48.145/vlive.qqvideo.tc.qq.com//G0010xtqHwp.p202.18.mp4?vkey=B5E83BD23C16315AED6C510C0538330E03555FE1BB7BF5BC74413ED50D499D1C3860B7E4D99C42557D3E311C2193E01908D70AD0024C9294541815FF97EE4F8E92ED372457A59B8A98AB5F55FAB4DC3979218EB18C7FD1F9D95C63E89EF9215B"
            ],
            "video_profile": "__default__"
        }
    },
    "title": "心魔",
    "url": null
}
you-get: version 0.4.575, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/x/cover/yxfqt2th35m6kdb.html']
Traceback (most recent call last):
  File "/usr/local/python3/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/common.py", line 1388, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/common.py", line 1301, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only,json_output=json_output, caption=caption)
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/common.py", line 1117, in download_main
    download(url, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/common.py", line 1381, in any_download
    m.download(url, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/extractors/qq.py", line 106, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/usr/local/python3/lib/python3.5/site-packages/you_get/extractors/qq.py", line 59, in qq_download_by_vid
    fvkey = output_json['vl']['vi'][0]['fvkey']
NameError: name 'output_json' is not defined

腾讯的视频，获取到之后又打印了一段，未定义？
ps：可以考虑加上分段视频每一段的时间吗？例如哔哩哔哩、腾讯和搜狐

**Comment by fan26a** [comment]
Bilibili每段视频时间：length = [durl.getElementsByTagName('length')[0].firstChild.nodeValue for durl in doc.getElementsByTagName('durl')]
腾讯每段视频时间： part_times.append(video_json['vl']['vi'][0]['cl']['ci'][part]['cd'])

**Comment by Sausky** [comment]
谁能拿到这个算法啊_clib.echo_ckeyv3（）

**Comment by cnbeining** [comment]
分段时间只有某些网站可能提供。

差不多就按经验算6分钟一段吧。

**Comment by nessusing** [comment]
Got the same exception while download from qq video:

`bash-3.2$ you-get --debug -i https://v.qq.com/x/cover/xdrlok2ce3ov6zi/m0022i2ohfz.html
Site:       QQ.com
Title:      香港黄金抢劫案细节：作案团伙手法纯熟，全程仅10秒
Type:       MPEG-4 video (video/mp4)
Size:       9.14 MiB (9583113 Bytes)

you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/cover/xdrlok2ce3ov6zi/m0022i2ohfz.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.595', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_o
utput, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1129, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/extractors/qq.py", line 106, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/usr/local/Cellar/you-get/0.4.595/libexec/lib/python3.5/site-packages/you_get/extractors/qq.py", line 59, in qq_download_by_vid
    fvkey = output_json['vl']['vi'][0]['fvkey']
NameError: name 'output_json' is not defined`

**Comment by rosynirvana** [comment]
outdated
