### ISSUE TITLE
斗鱼不知道啥时候出了个视频站--https://v.douyu.com/

### ISSUE THREAD

**Issue by daxiaxia** [soimort/you-get#1512]
主站:https://v.douyu.com/
示例视频地址:https://v.douyu.com/show/9kJmbBMkewv40XAQ
视频质量还不错,自己试着解析,发现视频都切成了一个个片段,搞不定...
只好提交一个issue给大佬们

**Comment by steven7851** [comment]
hls串流，m3u8 playlist用ffmpeg可以直接下载，扩展名.ts

**Comment by cnbeining** [comment]
但是API加密的够狠。。

**Comment by daxiaxia** [comment]
原来ffmpeg能用来下载啊, 学到了
ffmpeg.exe -i "http://videows1.douyucdn.cn/live/normal_3187135520161113151338/playlist.m3u8?k=853bbaa74a6a3e5ef26509aea4b596ef&t=582aec15&d=5AC496F667C7F 9FFEB9DC667E223059C&u=24531998&ct=web" -c copy video.ts
以上

**Comment by steven7851** [comment]
@cnbeining 
html5连接
https://vmobile.douyu.com/show/9kJmbBMkewv40XAQ
useragent要改成手机的 网页里就可以直接抓到m3u8 不用api

**Comment by Erk-** [comment]
I have tried to make a fix but it only works a 1/3 of the time.
