### ISSUE TITLE
有没有什么录制直播弹幕的好办法?

### ISSUE THREAD

**Issue by socialloser1** [soimort/you-get#1517]
you-get 录制直播很好用,但是直播中的弹幕也是乐趣的一大来源,有没有什么方法是可以记录在线弹幕的?不求合并到视频里,反而分开更好.也不要求时间上的完全对齐,只要相对时间正确就行,我可以录制完视频后手动调整. xml或者ass格式都可以.

**Comment by maxdance** [comment]
可以使用danmu这个库，手动添加一些外围的控制。

**Comment by yanetut** [comment]
用danmu做成xml再用bililocal播放就行，存储可以用百度云bypy ：）

**Comment by cnbeining** [comment]
Closed due to off topic.
