### ISSUE TITLE
优酷会员下载不了全部的了，只能下载试看部分，请问怎么回事？

### ISSUE THREAD

**Issue by WUZHIQIANGX** [soimort/you-get#1522]
>you-get -d http://v.youku.com/v_show/id_XMTgyNDM4Nzg5Ng==.html?spm=a2h03.816446
8.2069780.11
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTgyNDM4Nzg5Ng==&c
t=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTgyNDM4Nzg5Ng==&c
t=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/747990554084112ce7
9a3_00/st/flv/fileid/0300802800582F13639AF505CF07DD9E14B56A-4F4C-9B92-72B9-BA29C
7BA2007?ev=1&K=c9cb6ad24705bc83261f5d00&ep=dSaTE0CNU8sE5SvbiT8bNHnlfSYMXP4J9h%2B
NgdBqALshQOrJmD3XxJTBOPpCE4pvciVyZOKEqtSVb0ZlYfQ1rRsQ1jyhO%2Frn%2FILq5d8ixplzYWt
HcM3Xs1SdQDD4&token=3309&oip=1035870470&yxon=1&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/747990554084112ce7
9a3_00/st/flv/fileid/0300802801582F13639AF505CF07DD9E14B56A-4F4C-9B92-72B9-BA29C
7BA2007?ev=1&K=c987a5e1a5eee595261f5d00&ep=dSaTE0CNU8sE5SvbiT8bNHnlfSYMXP4J9h%2B
NgdBqALohQOrJmD3XxJTBOPpCE4pvciVyZOKEqtSVb0ZlYfQ1rRsQ1jyhO%2Frn%2FILq5d8ixplzYWt
HcM3Xs1SdQDD4&token=3309&oip=1035870470&yxon=1&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/747990554084112ce7
9a3_00/st/flv/fileid/0300802802582F13639AF505CF07DD9E14B56A-4F4C-9B92-72B9-BA29C
7BA2007?ev=1&K=4b3cba7662d3f6f22412d166&ep=dSaTE0CNU8sE5SvbiT8bNHnlfSYMXP4J9h%2B
NgdBqALkhQOrJmD3XxJTBOPpCE4pvciVyZOKEqtSVb0ZlYfQ1rRsQ1jyhO%2Frn%2FILq5d8ixplzYWt
HcM3Xs1SdQDD4&token=3309&oip=1035870470&yxon=1&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/747990554084112ce7
9a3_00/st/flv/fileid/0300802803582F13639AF505CF07DD9E14B56A-4F4C-9B92-72B9-BA29C
7BA2007?ev=1&K=ecc64dbc10c1ca14282be89a&ep=dSaTE0CNU8sE5SvbiT8bNHnlfSYMXP4J9h%2B
NgdBqALghQOrJmD3XxJTBOPpCE4pvciVyZOKEqtSVb0ZlYfQ1rRsQ1jyhO%2Frn%2FILq5d8ixplzYWt
HcM3Xs1SdQDD4&token=3309&oip=1035870470&yxon=1&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/747990554084112ce7
9a3_00/st/flv/fileid/0300802804582F13639AF505CF07DD9E14B56A-4F4C-9B92-72B9-BA29C
7BA2007?ev=1&K=2dba4661e124fa282412d166&ep=dSaTE0CNU8sE5SvbiT8bNHnlfSYMXP4J9h%2B
NgdBqAL8hQOrJmD3XxJTBOPpCE4pvciVyZOKEqtSVb0ZlYfQ1rRsQ1jyhO%2Frn%2FILq5d8ixplzYWt
HcM3Xs1SdQDD4&token=3309&oip=1035870470&yxon=1&ctype=12
site:                优酷 (Youku)
title:               巴黎危机
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          1887.0 MiB (1978711249 bytes)
    # download-with: you-get --format=hd3 [URL]

**Comment by ruiing** [comment]
you-get -c cookies.sqlite [URL]
cookies.sqlite用火狐浏览器获取.

**Comment by soimort** [comment]
同上。
