### ISSUE TITLE
腾讯长视频下载问题

### ISSUE THREAD

**Issue by yangaowei** [soimort/you-get#1523]
https://v.qq.com/x/cover/tu0kfx77pkwk3t6.html?vid=k00205g5xhk

腾讯的视频，时长大于5分钟的，鉴权方式应该不一样，下载超很慢，查看代码发现是在不停超时重试

**Comment by WaterClam** [comment]
+1，腾讯视频下载长视频速度只有31KB/s……望修复

**Comment by ilovesusu** [comment]
目测是人家服务器限制了！

**Comment by qwIvan** [comment]
https://github.com/soimort/you-get/issues/1506

**Comment by rosynirvana** [comment]
in favor of #1855
