### ISSUE TITLE
怎么下载视频超级慢啊？

### ISSUE THREAD

**Issue by latel** [soimort/you-get#1529]
已经更新到最新版；
浏览器里看加载速度很快，用you-get 下载超级慢。。。。。

**Comment by latel** [comment]
https://www.youtube.com/watch?v=3uljDhBfh9o   

any video from youtube is slow...

**Comment by xavierskip** [comment]
同样，下载 youtube 视频被限速了。
在本机下载以及在墙外 VPS 上下载都被限制在 50多 kB/s，看来不是线路的原因。

you-get  --itag=134 https://www.youtube.com/watch?v=kx6bzoCCPpA

**Comment by soimort** [comment]
也许是因为天气冷的原因吧。🤔

**Comment by cnbeining** [comment]
![image](https://cloud.githubusercontent.com/assets/1560962/20695072/7161d106-b5b7-11e6-9515-8ac2b4c2e489.png)

**Comment by yangyaofei** [comment]
同样遇到 

![](http://ww1.sinaimg.cn/large/005yPHtvgw1fblu5hoq65j30j00d7tgz.jpg)

用手机youtube看,3m/s

**Comment by Justsoos** [comment]
you-get.exe -x 127.0.0.1:28080 https://www.youtube.com/watch?v=3uljDhBfh9o
site:                YouTube
title:               《陈翔六点半》第75集
stream:
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          103.9 MiB (108941095 bytes)
    # download-with: you-get --itag=22 [URL]

Downloading 《陈翔六点半》第75集.mp4 ...
38.0% ( 39.5/103.9MB) ├████████████████─────────────────────────┤[1/1]    **1 MB/s**

天气好冷，随便找了个ss代理，都跑1M啊，呵呵，比国内视频站还快

**Comment by yangyaofei** [comment]
@Justsoos  你下一个1080p的视频试试,和下载别的的速度不一样

**Comment by soimort** [comment]
![you-get_youtube](https://cloud.githubusercontent.com/assets/342945/21812084/16ce7354-d752-11e6-9a41-806f13b1ae78.gif)

**Comment by yangyaofei** [comment]
@soimort  下载一个1080p的视频试试

**Comment by Justsoos** [comment]
you-get.exe --itag=248 -x 127.0.0.1:28080 https://www.youtube.com/watch?v=3uljDhBfh9o
site:                YouTube
title:               《陈翔六点半》第75集
stream:
    - itag:          248
      container:     webm
      quality:       1920x1080
      size:          189.4 MiB (198570848 bytes)
    # download-with: you-get --itag=248 [URL]

Downloading 《陈翔六点半》第75集.webm ...
11.7% ( 22.2/189.4MB) ├█████────────────────────────────────────┤[1/2]    2 MB/s

还是同一个代理。。。。我在国内啊

**Comment by soimort** [comment]
> @soimort  下载一个1080p的视频试试

同上。不想再截图了。
