### ISSUE TITLE
Cannot download from KhanAcademy

### ISSUE THREAD

**Issue by JahowChen** [soimort/you-get#1531]
Issue: cannot download videos from khanacademy.org
e.g. `you-get https://www.khanacademy.org/math/algebra-home/alg-two-var-inequalities/alg-graphing-inequalities/v/graphing-inequalities`
- you-get and python is up-to-date
- Internet Connection is fine
- able to watch directly or download using thunder
- no report comes out by running with --debug
- tried on various devices and networks

**Comment by Erk-** [comment]
I can not replicate it works for me. Can you try and download a video from youtube?
(as a side note it throws a error when the file has finished downloading)

**Comment by soimort** [comment]
@soimort-bot Test this: https://www.khanacademy.org/math/algebra-home/alg-two-var-inequalities/alg-graphing-inequalities/v/graphing-inequalities
