### ISSUE TITLE
求助，下载优酷中医诊断学视频，完了一直卡在Merging video parts... 

### ISSUE THREAD

**Issue by WeihuaGu** [soimort/you-get#1535]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]、
卡在合并：
```
site:                优酷 (Youku)
title:               03 中医诊断学
stream:
    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          78.6 MiB (82466153 bytes)
    # download-with: you-get --format=flvhd [URL]

Downloading 03 中医诊断学.flv ...
 0.0% (  0.0/ 78.6MB) ├────────────────────────────14.2% ( 11.1/ 78.6MB) ├██████──────────────────────29.2% ( 23.0/ 78.6MB) ├████████████────────────────45.5% ( 35.8/ 78.6MB) ├███████████████████─────────63.2% ( 49.7/ 78.6MB) ├██████████████████████████──76.9% ( 60.5/ 78.6MB) ├████████████████████████████87.3% ( 68.7/ 78.6MB) ├████████████████████████████ 100% ( 78.6/ 78.6MB) ├█████████████████████████████████████████┤[7/7]  118 MB/s
Merging video parts... 
```
我的 ffmpeg 与you-get版本
```
ffmpeg -version
ffmpeg version 2.7.6-0ubuntu0.15.10.1

you-get -V
you-get: version 0.4.595, a tiny downloader that scrapes the web.
```
下载文件夹权限：
`drwxrwxr-x  14 better better   20480 12月  1 14:33 下载`

测试了其它的视频，正常合并……

> [舔 :icecream:!]

**Comment by soimort** [comment]
请贴出视频地址。

**Comment by WeihuaGu** [comment]
@soimort  地址是http://v.youku.com/v_show/id_XMTEyNzExNjQ=.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0

**Comment by soimort** [comment]
无法复现。
请升级ffmpeg版本。

**Comment by soimort** [comment]
另：可以用`-u`打印出视频链接，尝试用`ffmpeg`手动合并。

**Comment by WeihuaGu** [comment]
@soimort  谢谢你。我用了cat ……
