### ISSUE TITLE
Please dont use unicode file name with argument -u

### ISSUE THREAD

**Issue by lucifekit** [soimort/you-get#1545]
Hi, i want to use the argument -u in my program, but if the filename is in chinese, you-get require an unicode environment by using "chcp 65001". 

Of course it work if i open a command line, enter "chcp 65001" then calling you-get, but it not work in my program environment ( vb.net ) because it doesnt treat my process as an unicode environment even i call "chcp 65001"

So i want if i use only the -u parameter, you-get will ignore the file name and print the Real URLs only.

**Comment by lucifekit** [comment]
Example link : 

you-get -u "http://v.youku.com/v_show/id_XMTg0NzM2MTY1Mg==.html"

**Comment by rosynirvana** [comment]
```
diff --git a/src/you_get/extractor.py b/src/you_get/extractor.py
index 8c7dcf7..be49603 100644
--- a/src/you_get/extractor.py
+++ b/src/you_get/extractor.py
@@ -161,7 +161,7 @@ class VideoExtractor():
         if self.audiolang:
             print("audio-languages:")
             for i in self.audiolang:
-                print("    - lang:          {}".format(i['lang']))
+                maybe_print("    - lang:          {}".format(i['lang']))
                 print("      download-url:  {}\n".format(i['url']))
 
     def p_playlist(self, stream_id=None):
```
Try this
