### ISSUE TITLE
支持芒果TV1080p

### ISSUE THREAD

**Issue by Hugo-Hui** [soimort/you-get#1554]
http://www.mgtv.com/b/298050/3734512.html
http://www.mgtv.com/b/305745/3735684.html
芒果tv開始新增了藍光1080P

**Comment by lamlam123tld3** [comment]
http://v.api.mgtv.com/player/video

this api is cannot retrieve any stream now

**Comment by lki2019** [comment]
目前还是没支持1080
不过好像蓝光是会员专享的吧？

**Comment by rosynirvana** [comment]
年初的时候mgtv的api会把1080p leak出来，现在没了
