### ISSUE TITLE
[需求]土豆或其他网站视频专辑检测

### ISSUE THREAD

**Issue by Rictusempra** [soimort/you-get#1556]
自动检测下载土豆或其他视频专辑列表下所有视频，如PPTV等

**Comment by EMLVIRUS** [comment]
English only here?
Actually, if you need any link sample, any animation album from tudou.com will fit this issue.
If you need anyone now, please try this: http://www.tudou.com/albumplay/vpMCwSvLbU4/qDsxTImEw_0.html

**Comment by rosynirvana** [comment]
#1542
