### ISSUE TITLE
不能下载vk视频

### ISSUE THREAD

**Issue by menshen** [soimort/you-get#1557]
you-get https://vk.com/alexgaudino?z=video-43046770_163866649

**Comment by cnbeining** [comment]
请给更多的log 谢谢。

**Comment by menshen** [comment]
好的


发自网易邮箱大师
在2016年12月16日 13:17，David Zhuang 写道:

请给更多的log 谢谢。

**Comment by menshen** [comment]
you-get https://vk.com/alexgaudino?z=video-43046770_163866649
Site:       VK.com
Title:      Alex Gaudino - Chinatown (Official Video)
Type:       Unknown type (None)
Size:       0.01 MiB (6081 Bytes)

Downloading Alex Gaudino - Chinatown (Official Video).None ...
 100% (  0.0/  0.0MB) ├███████████████████████████████████████████████████████████████████████████████████████████████┤[1/1]  535  B/s

**Comment by menshen** [comment]
哦，我发现那个视频是链接到youtube的，vk自身的视频是可以下载的。
