### ISSUE TITLE
you-get failed processing some url from tudou

### ISSUE THREAD

**Issue by zhuliting** [soimort/you-get#1562]
Hi, I can actually watch the video in Chrome browser,  but not download it with `you-get`.
sample url: http://www.tudou.com/albumplay/iFOk5w8--7Y/qp7ELCeh9zo.html

log:
```
$ ./you-get --debug  -u 'http://www.tudou.com/albumplay/iFOk5w8--7Y/qp7ELCeh9zo.html' 
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTAzNjE5MDcy&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTAzNjE5MDcy&ct=12
you-get: [Failed] 抱歉,因版权原因无法观看此视频!
```

**Comment by zhangn1985** [comment]
用美国IP可以看

**Comment by zhuliting** [comment]
@zhangn1985 国内也可以看，就是you-get不能下载

**Comment by soimort** [comment]
@soimort-bot Test this: http://www.tudou.com/albumplay/iFOk5w8--7Y/qp7ELCeh9zo.html
