### ISSUE TITLE
win10 下的 linux on windows环境下不能用？

### ISSUE THREAD

**Issue by ruijanlee** [soimort/you-get#1563]
win10 下的 linux on windows环境下不能用？

以前一直在cygwin上用的好好的，重装了win10试试发现不行。

是我自己的问题？

**Comment by j16180339887** [comment]
錯誤訊息是什麼

**Comment by j16180339887** [comment]
我用 cygwin 很正常

更新到 github 最新版試試

`pip install --upgrade git+https://github.com/soimort/you-get@develop`

**Comment by ruijanlee** [comment]
不是cygwin是Windows Subsystem for Linux

https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/

**Comment by j16180339887** [comment]
我用 Windows Subsystem for Linux 也是正常的

**Comment by 872517414** [comment]
@j16180339887 
`pip3 install --upgrade git+https://github.com/soimort/you-get@develop
Downloading/unpacking git+https://github.com/soimort/you-get@develop
  Cloning https://github.com/soimort/you-get (to develop) to /tmp/pip-i_dw0tjd-build
  Running setup.py (path:/tmp/pip-i_dw0tjd-build/setup.py) egg_info for package from git+https://github.com/soimort/you-get@develop

Installing collected packages: you-get
  Running setup.py install for you-get

    error: could not create '/usr/local/lib/python3.4/dist-packages/you_get': Permission denied
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-i_dw0tjd-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-td286y0v-record/install-record.txt --single-version-externally-managed --compile:
    warning: manifest_maker: standard file '-c' not found



error: could not create '/usr/local/lib/python3.4/dist-packages/you_get': Permission denied

----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-i_dw0tjd-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-td286y0v-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-i_dw0tjd-build
Storing debug log for failure in /home/ubuntu/.pip/pip.log`

`pip install --upgrade git+https://github.com/soimort/you-get@develop
Downloading/unpacking git+https://github.com/soimort/you-get@develop
  Cloning https://github.com/soimort/you-get (to develop) to /tmp/pip-gD_ryE-build
  Running setup.py (path:/tmp/pip-gD_ryE-build/setup.py) egg_info for package from git+https://github.com/soimort/you-get@develop
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-gD_ryE-build/setup.py", line 10, in <module>
        proj_info = json.loads(open(os.path.join(here, PROJ_METADATA), encoding='utf-8').read())
    TypeError: 'encoding' is an invalid keyword argument for this function
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-gD_ryE-build/setup.py", line 10, in <module>

    proj_info = json.loads(open(os.path.join(here, PROJ_METADATA), encoding='utf-8').read())

TypeError: 'encoding' is an invalid keyword argument for this function

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-gD_ryE-build
Storing debug log for failure in /home/ubuntu/.pip/pip.log`

**Comment by Justsoos** [comment]
你们可以试试 cmder http://cmder.net/ 足够用you-get了。 @ruijanlee @872517414

**Comment by j16180339887** [comment]
@872517414 

抱歉現在才看到

看到 Permission denied 就加 sudo 試試

`sudo pip3 install --upgrade git+https://github.com/soimort/you-get@develop`
