### ISSUE TITLE
为什么下载进度变成这样

### ISSUE THREAD

**Issue by DevilHandCC** [soimort/you-get#1572]
正常不是应该只有一行显示下载进度吗，为什么变成了这样？
> 94.6% (670.1/708.2MB) ├█████████████████████████████████████──┤[14/15]    1 MB/94.7% (670.3/708.2MB) ├█████████████████████████████████████──┤[14/15]    2 MB/94.7% (670.6/708.2MB) ├█████████████████████████████████████──┤[14/15]    1 MB/94.7% (670.8/708.2MB) ├█████████████████████████████████████──┤[14/15]    2 MB/94.8% (671.1/708.2MB) ├█████████████████████████████████████──┤[14/15]    2 MB/94.8% (671.3/708.2MB) ├█████████████████████████████████████──┤[14/15]    2 MB/94.8% (671.6/708.2MB) ├█████████████████████████████████████──┤[14/15]    2 MB/94.9% (671.8/708.2MB) ├█████████████████████████████████████──┤[14/15]    2 MB/94.9% (672.1/708.2MB) ├█████████████████████████████████████──┤[14/15]    2 MB/94.9% (672.3/708.2MB) ├█████████████████████████████████████──┤[14/15]    2 MB/95.0% (672.6/708.2MB) ├██████████████████████████████████████─┤[14/15]    2 MB/95.0% (672.8/708.2MB) ├██████████████████████████████████████─┤[14/15]    2 MB/95.0% (673.1/708.2MB) ├██████████████████████████████████████─┤[14/15]    2 MB/95.1% (673.3/708.2MB) ├██████████████████████████████████████─┤[14/15]    2 MB/95.1% (673.6/708.2MB) ├██████████████████████████████████████─┤[14/15]    2 MB/95.1% (673.8/708.2MB) ├██████████████████████████████████████─┤[14/15]    2 MB/95.2% (674.1/708.2MB) ├██████████████████████████████████████─┤[14/15]    2 MB/95.2% (674.3/708.2MB) ├██████████████████████████████████████─┤[14/15]    2 MB/95.3% (674.6/708.2MB) ├██████████████████████████████████████─┤[14/15]    2 MB/

**Comment by cnbeining** [comment]
![image](https://cloud.githubusercontent.com/assets/1560962/21465021/b4f3ad94-c95e-11e6-8a9c-978489387f42.png)

这是你的bash的问题，和本项目无关啦。
