### ISSUE TITLE
腾讯视频下载速度只有30K/S,有办法解决吗

### ISSUE THREAD

**Issue by taocwang** [soimort/you-get#1578]
腾讯视频下载速度只有30K/S,有办法解决吗

**Comment by doubleseoo** [comment]
腾讯的视频好像不能抓取了

**Comment by taocwang** [comment]
可以抓取，但是下载很慢……，我看前面的issue说是腾讯专门针对下载作了限速，不知有什么方法解决没

**Comment by mogu1121** [comment]
第22条婚规2下的我蛋疼

**Comment by fuzhuo** [comment]
Seems QQ limited the download speed.
./you-get http://v.qq.com/x/cover/i200hs4ip5a6u7a/w0022948t5m.html
Site:       QQ.com
Title:      鬼吹灯之精绝古城_01
Type:       MPEG-4 video (video/mp4)
Size:       680.54 MiB (713599940 Bytes)

Downloading 鬼吹灯之精绝古城_01.mp4 ...
 0.1% (  0.5/680.5MB) ├────────────────────┤[1/7]   31 kB/s

**Comment by missdeer** [comment]
@fuzhuo 我也是同样问题。精绝古城用播放器在线播放卡卡卡（电信100M）

**Comment by Justsoos** [comment]
用多线程下载软件，比如 IDM，可以到500k/s，不过看样子也做了ip限制。

**Comment by zhangn1985** [comment]
能达到4M/s只是恰巧而已。

**Comment by Justsoos** [comment]
不是腾讯问题，还是you-get解析器没有取到合适的url
比如下面两个，后面的速度飞快，前面的卡的要死。

http://vhoth.dnion.videocdn.qq.com/flv/78/17//r0022uyq1mi.p209.1.mp4?vkey=C772D3A7C462B1B4E61745D5583133B8F37592F210790AEAB56883C28FFB08E60E36AFF28027DF5466FE7FD4578B7B655DA076B388AC0BAF2F27CA56F0124B162C2D66B30A1DC4CF8AF1663B87C93EFB1528EEC2CBBC5876BC0469CA53A3B0F9

http://lmbsy.qq.com/flv/253/103/e0022udr8f5.p201.1.mp4?sdtfrom=v1010&guid=3d291942679e5c88d6ade7df25698479& vkey=3B74B5A09494946184BB5980F5DF3B100B89200B171B556A23B1A1CACF57F91F92D3FA6B6E3B397D799BEAC1AEC6F7B9812098359F95390D195B9BC1BF87ED36021B01AE7D088C7CE1DA46083E87CAE0F01578C2E711DB2CB0D1A8B066DB6213C18437AABF4F8907A6DE1A2A1A96AD68

**Comment by chengxianghe** [comment]
同样遇到这个问题了 可有什么解决方案么

**Comment by Justsoos** [comment]
用 @soimort 在master branch 上新改出来的 fake header https://github.com/soimort/you-get/commit/f299d30161f2017318211099979845192a891025 试了下。
前后取到两个不同服务器的qq视频地址，但用mpv播放情况下都很卡，推测：是不是腾讯加了mpv header的黑名单？

之前：
http://lmbsy.qq.com/flv/51/220//q0022tqbeoa.p209.6.mp4?vkey=8EE630271343A0F3AC34D838A198FED1723879523490B7E3DF2BAAB19326EC9C164C6700F05E099BC2577FD47A338A29064B2510CE26FE511CED18330C5F0B5F788F078AFD971B36E5F5C58DB257860E6F81C0A9FDBC768B69288D54A038FAF9

之后：
http://vhoth.dnion.videocdn.qq.com/flv/51/220//q0022tqbeoa.p209.6.mp4?vkey=D5C5E0C5CA7B5B1DBDEA9A871EBABAE1A815B594ED31AB69D52D88CDFB35905D07EDADCE0BD9871B24CBC311DD985BCD9802F00DDAA476EEB9B50FD991C90E8E4D5B5D5E9FE8463FE4776A8CE624A7E8AABC2A14F09040C5B554D798ED0E9092

**Comment by qwIvan** [comment]
问题是代码用了getkey接口去获取vkey，这样得到的vkey只有几十k，而用getvkey接口却很快。问题是getvkey接口需要一个名为Ckey的参数，而这个参数不知道怎么生成

**Comment by qwIvan** [comment]
刚刚已经被我找到了ckey的生成方法了，可以解决了

**Comment by chweiii** [comment]
@qwIvan 你的项目qq还有有一部分不能下载
./you-get http://v.qq.com/page/h/0/f/h0016zcdo2f.htm --debug
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by qwIvan** [comment]
@chweiii 你的視頻不存在

**Comment by rosynirvana** [comment]
in favor of #1855

**Comment by radisliou** [comment]
@rosynirvana 现在qq限速有破解办法吗？

**Comment by smilingdolphin** [comment]
楼主，我下载vip的视频，加上本地的cookie的时候，它为什么跑到 google.com去取内容啊？官方版本没这个问题呀。
然后你知道的，google被屏蔽了，然后一直卡在这里了。
python3 ./you-get/you-get --debug --cookies cookies.txt https://v.qq.com/x/cover/ei9w5141187ibo2/g0024wq70u1.html
[DEBUG] get_content: https://www.google.com/search?tbm=vid&q=cookies.txt
