### ISSUE TITLE
enter point not found

### ISSUE THREAD

**Issue by vipzrx** [soimort/you-get#1589]
在win 7 下使用的 you-get-0.4.595-win32-full.7z
运行出现：
![20170103_213127](https://cloud.githubusercontent.com/assets/5094958/21609235/3173f31a-d1fc-11e6-9b7f-587150ae529e.png)

**Comment by soimort** [comment]
https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/the-procedure-entry-point-ucrtbaseterminate-could/e45c2162-bb43-4082-a3dd-d715c7ea1f46
