### ISSUE TITLE
使用PotPlayer观看直播，熊猫可以，斗鱼失败。而vlc两者都可以

### ISSUE THREAD

**Issue by Justsoos** [soimort/you-get#1590]
![11](https://cloud.githubusercontent.com/assets/3480043/21624246/37ff9596-d241-11e6-9226-16d96f1f4b7a.png)

个人感觉PotPlayer的解码效果更好，但（公认）经过加密的斗鱼直播无法打开视频流，potplayer一直转圈，（公认）未加密的熊猫直播，用pp播放没问题。
而如果换成VLC播放器，两个网站都可以正常播放。

估计是
you-get -p 
输出的【斗鱼直播】流格式，potplayer不支持？

我用的potplayer最新版64位 1.6.63856 
系统win 10 1607 64位

**Comment by Justsoos** [comment]
补充一下debug信息（基本上没什么信息）
mpv, vlc 都可以播放斗鱼直播，都可以解析地址，但potplayer无法播放。没有更多debug信息

E:\Users\J
λ you-get --debug -p PotPlayerMini64 https://www.douyu.com/s1134
[DEBUG] get_content: http://www.douyu.com/s1134
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=248753
Site:       douyu.com
Title:      【s1134】经典 科幻 动作 灾难！~
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

E:\Users\J
λ you-get --debug -p vlc https://www.douyu.com/s1134
[DEBUG] get_content: http://www.douyu.com/s1134
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=248753
Site:       douyu.com
Title:      【s1134】经典 科幻 动作 灾难！~
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)


E:\Users\J
λ you-get --debug -p mpv https://www.douyu.com/s1134
[DEBUG] get_content: http://www.douyu.com/s1134
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=248753
Site:       douyu.com
Title:      【s1134】经典 科幻 动作 灾难！~
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

**Comment by soimort** [comment]
目测 PotPlayer 不支持 FLV 串流。

请移步 PotPlayer 的技术支持。

**Comment by Justsoos** [comment]
@soimort  不会吧，potplayer作为开发资历相当高的播放器，竟然会不支持flv ？？
我特地去找了个flv 下载来，完全可以播放啊。地址在 http://v.youku.com/v_show/id_XNjcxMDExOTQ0.html

文件信息：

General
Complete name                  : C:\Tools\you-get\you-get-develop\FLV测试视频.flv
Format                         : Flash Video
File size                      : 1.05 MiB
Duration                       : 30 s 231 ms
Overall bit rate               : 291 kb/s
Tagging application            : modified by youku.com in 20111202

Video
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L2.1
Format settings, CABAC         : Yes
Format settings, ReFrames      : 5 frames
Codec ID                       : 7
Duration                       : 30 s 67 ms
Width                          : 512 pixels
Height                         : 288 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 15.000 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive

Audio
Format                         : AAC
Format/Info                    : Advanced Audio Codec
Format profile                 : HE-AAC / LC
Codec ID                       : 10
Duration                       : 30 s 231 ms
Channel(s)                     : 2 channels
Channel positions              : Front: L R
Sampling rate                  : 44.1 kHz / 22.05 kHz
Frame rate                     : 21.533 FPS (1024 spf)
Compression mode               : Lossy

**Comment by Justsoos** [comment]
我估计这个问题来自 “斗鱼直播” 本身的加密措施，很多人之前提取斗鱼的HLS串流，复制URL到potplayer播放，都失败了，和其他直播网站不同，斗鱼加了校验。这就得看you-get的extractors如何输出这个URL给potplayer，或者vlc，mpv了。

**Comment by soimort** [comment]
> @soimort 不会吧，potplayer作为开发资历相当高的播放器，竟然会不支持flv ？？
> 我特地去找了个flv 下载来，完全可以播放啊。

flv串流 ≠ flv。

**Comment by Justsoos** [comment]
@soimort   我用you-get -u 提取了上面那个优酷的flv的地址：

http://175.22.3.182/youku/677804E46DF4076F713162E89/030002010052C0D94724D5052C0D7CC390B757-C55E-E3F9-EED5-7E80E0EC0689.flv

在potplayer 里用 ctrl+u 输入，播放，没问题。哈哈，这个是串流了吧？

**Comment by Justsoos** [comment]
另外我看了下，pandatv的串流都是flv的，用you-get + potplayer播放没问题。只有斗鱼直播不可以用potplayer，这非常奇怪。

**Comment by Justsoos** [comment]
@soimort 弄清楚怎么回事了。用wireshark 抓了包，potplayer行为很奇怪。

第一次连接get，user-agent是 potplayer，
但接收很少数据后主动 rst 断开连接，再用 winamp 的user-agent 去连服务器。

由于斗鱼的token 检查非常严格，一个token 只能用一次。所以，potplayer相当于用任何办法，都无法看斗鱼直播。

熊猫最近在大主播直播间实验token和expire，（you-get已经在这些房间失效了！） potplayer也有一些房间不能用。
