### ISSUE TITLE
一个月没人处理，不得以开新帖，求回复！

### ISSUE THREAD

**Issue by SeaHOH** [soimort/you-get#1597]
> 详见 #1546 #1548

**Comment by cnbeining** [comment]
You probably want to explain your changes for I really cannot notice the differences your PR would do.

**Comment by SeaHOH** [comment]
Just hope you fix the bug, no my changes.

**Comment by SeaHOH** [comment]
@soimort @cnbeining 
能不能不要拽外鸟语就关闭不管了！
汇报个错误有这么难么？？
又不是缠着要你用我的修改！
