### ISSUE TITLE
求支持最近新出的斗鱼视频（v.douyu.com）

### ISSUE THREAD

**Issue by F1uYu4n** [soimort/you-get#1598]
https://v.douyu.com/show/jworZv0e3mZ7JBk3
这样子的目前还不支持，谢谢

**Comment by F1uYu4n** [comment]
已知播放视频时候是加载一个这样的playlist：
http://videows1.douyucdn.cn/live/normal_4902920170104154408-upload-c349/playlist.m3u8?k=4a9b0ddca2911cae1bd4f977e7d90533&t=586fb716&d=6C094B01249F6051511E659B737101CE&u=35541278&ct=web&vid=99389

这个list是由连续的ts文件构成：
#EXTINF:16.120000,
2ab34d7f0db0470cb632df33dbaf8e2c_0000000.ts?k=4a9b0ddca2911cae1bd4f977e7d90533&t=586fb716&d=6C094B01249F6051511E659B737101CE&u=35541278&ct=web&vid=99389
#EXTINF:6.440000,
2ab34d7f0db0470cb632df33dbaf8e2c_0000001.ts?k=4a9b0ddca2911cae1bd4f977e7d90533&t=586fb716&d=6C094B01249F6051511E659B737101CE&u=35541278&ct=web&vid=99389

ts文件实际下载地址为：
http://videows1.douyucdn.cn/live/normal_4902920170104154408-upload-c349/2ab34d7f0db0470cb632df33dbaf8e2c_0000000.ts?k=ec5119c759a382ced6e57bb317cda8ee&t=586fb78d&d=6C094B01249F6051511E659B737101CE&u=35541278&ct=web&vid=99389

获取playlist的url的过程要通过douyu的一个签名，若该签名算法无法破解，可否加一个额外的参数指定实际的playlist的url，从而下载所有ts文件，最后拼成一个完整的视频？

**Comment by cnbeining** [comment]
这个是典型的HLS。

用ffmpeg可以下 有个这个函数可以调用。

但是怎么日出这个签名算法呢。。

**Comment by zhangn1985** [comment]
这个签名算法搞不出来。。

**Comment by cnbeining** [comment]
干脆以后我们内置一个JS引擎得了。

**Comment by Erk-** [comment]
Looks like it is possible to get the link to the m3u8 file by useing https://vmobile.douyu.com/getInfo?vid=id if you are useing the iPhone User-Agent. For example 
`curl 'https://vmobile.douyu.com/video/getInfo?vid=jworZv0e3mZ7JBk3' -H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/47.0.2526.70 Mobile/13C71 Safari/601.1.46'`
gives the output:
`{"error":0,"data":{"vid":"jworZv0e3mZ7JBk3","video_url":"http:\/\/vodhls1.douyucdn.cn\/live\/normal_live-557448r4eKL1UJr
C--20170103155437\/playlist.m3u8?k=bbedbc63f95e3b08b37a04fdfc7088f9&t=587562d5&d=&u=0&ct=h5&vid=101870"}}`.

**Comment by rosynirvana** [comment]
6f97cda
