### ISSUE TITLE
How to set default path

### ISSUE THREAD

**Issue by FateLight** [soimort/you-get#1602]
How to set default path?

**Comment by cnbeining** [comment]
Kindly check https://github.com/soimort/you-get#set-the-path-and-name-of-downloaded-file .

**Comment by FateLight** [comment]
大佬萌新求罩。我意思是设置一个自定义一个默认下载路径，每次加一个怪麻烦的（有配置文件可以改吗）嘻嘻，谢谢

**Comment by cnbeining** [comment]
没。

**Comment by ad52825196** [comment]
安装了 Java 的话欢迎尝试一下我写的 wrapper，可以实现你要的功能：https://github.com/ad52825196/video-downloader
