### ISSUE TITLE
acfun多P视频无法正确获取每P的标题名

### ISSUE THREAD

**Issue by mzhboy** [soimort/you-get#1617]
例如 [犬夜叉](http://www.acfun.cn/v/ac2230575_10)  
这里是第10话 `010--妖刀激突！雷击刃VS铁碎牙！`
`you-get -i http://www.acfun.cn/v/ac2230575_10`
得到的如下
![default](https://cloud.githubusercontent.com/assets/5281193/21904811/e1fff3e2-d93f-11e6-891c-b8d921b2e484.JPG)

**Comment by Nicksxs** [comment]
我记得以前好像可以多P自动下载全部的，现在为啥不行了 @soimort
