### ISSUE TITLE
youtube DASH parallel audio/video download

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [soimort/you-get#1618]
In my case, though audio size is much smaller than video, there seems to be a rate limit of the audio download(40KB/s~80KB/s).
So I think download video and audio parallelly might speed up.

**Comment by soimort** [comment]
The rate limiting issue should be gone b885c833b1bbfe52d1eb05c6e41b8d34f40a2a1f

Feel free to open another issue if it happens again.
