### ISSUE TITLE
some error with run command --json 

### ISSUE THREAD

**Issue by coderwangyu** [soimort/you-get#1625]
WangMacPro:~ huaxuezoo$ you-get --json 'https://www.bilibili.com/video/av7956677/'
{
    "site": "bilibili.com",
    "streams": {
        "__default__": {
            "container": "flv",
            "size": null,
            "src": [
                "http://cn-sdjn-cmcc-v-02.acgvideo.com/vg3/3/5e/13068743-1.flv?expires=1484639100&ssig=K7nPGU3QTJkD59NdCMhSCw&oi=1851803650&nfa=B2jsoD9cEoAmG7KPYo7s2g==&dynamic=1"
            ],
            "video_profile": "__default__"
        }
    },
    "title": "1、狼外婆+技能展示",
    "url": null
}
{
    "site": "bilibili.com",
    "streams": {
        "__default__": {
            "container": "flv",
            "size": null,
            "src": [
                "http://cn-sdjn-cmcc-v-05.acgvideo.com/vg3/9/3d/13095615-1.flv?expires=1484639100&ssig=rlFzRrXzXZPWziWt_Z9aCA&oi=1851803650&nfa=B2jsoD9cEoAmG7KPYo7s2g==&dynamic=1"
            ],
            "video_profile": "__default__"
        }
    },
    "title": "2、冰原狼+技能展示",
    "url": null
}
{
    "site": "bilibili.com",
    "streams": {
        "__default__": {
            "container": "flv",
            "size": null,
            "src": [
                "http://cn-sdjn-cmcc-v-03.acgvideo.com/vg2/9/93/13068861-1.flv?expires=1484639100&ssig=Etpgxd0LEMA9GS06BayNmA&oi=1851803650&nfa=B2jsoD9cEoAmG7KPYo7s2g==&dynamic=1"
            ],
            "video_profile": "__default__"
        }
    },
    "title": "3、火狼+技能展示",
    "url": null
}
{
    "site": "bilibili.com",
    "streams": {
        "__default__": {
            "container": "flv",
            "size": null,
            "src": [
                "http://cn-gdfs-cmcc-v-01.acgvideo.com/vg1/0/b5/13068745-1.flv?expires=1484639100&ssig=fZS6qKq9fHQQtYSPgX5_hQ&oi=1851803650&nfa=B2jsoD9cEoAmG7KPYo7s2g==&dynamic=1"
            ],
            "video_profile": "__default__"
        }
    },
    "title": "4、海牛皮肤+技能展示",
    "url": null
}
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by coderwangyu** [comment]
WangMacPro:~ huaxuezoo$ you-get --debug --json 'https://www.bilibili.com/video/av7956677/'
[DEBUG] get_content: http://www.bilibili.com/video/av7956677/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=13068743&from=miniplay&player=1&sign=b2416280884214a73af50f2ea3e566a8
{
    "site": "bilibili.com",
    "streams": {
        "__default__": {
            "container": "flv",
            "size": null,
            "src": [
                "http://cn-sdjn-cmcc-v-02.acgvideo.com/vg3/3/5e/13068743-1.flv?expires=1484640300&ssig=VmVYT5UBDlgoFn20b3PrLg&oi=1851803650&nfa=B2jsoD9cEoAmG7KPYo7s2g==&dynamic=1"
            ],
            "video_profile": "__default__"
        }
    },
    "title": "1、狼外婆+技能展示",
    "url": null
}
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=13095615&from=miniplay&player=1&sign=e98ad04948f60d417301f6d628c875e4
{
    "site": "bilibili.com",
    "streams": {
        "__default__": {
            "container": "flv",
            "size": null,
            "src": [
                "http://cn-sdjn-cmcc-v-05.acgvideo.com/vg3/9/3d/13095615-1.flv?expires=1484640300&ssig=T9hiHY8yeQ_3NRMgRPR3Qg&oi=1851803650&nfa=B2jsoD9cEoAmG7KPYo7s2g==&dynamic=1"
            ],
            "video_profile": "__default__"
        }
    },
    "title": "2、冰原狼+技能展示",
    "url": null
}
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=13068861&from=miniplay&player=1&sign=35f51f66a1ec003c44f1c62346203b4e
{
    "site": "bilibili.com",
    "streams": {
        "__default__": {
            "container": "flv",
            "size": null,
            "src": [
                "http://cn-sdjn-cmcc-v-03.acgvideo.com/vg2/9/93/13068861-1.flv?expires=1484640300&ssig=w-Pl-v6lkFc4ugAW-uqZzQ&oi=1851803650&nfa=B2jsoD9cEoAmG7KPYo7s2g==&dynamic=1"
            ],
            "video_profile": "__default__"
        }
    },
    "title": "3、火狼+技能展示",
    "url": null
}
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=13068745&from=miniplay&player=1&sign=03a7c276e29d92e2c3665e64434b7b4f
{
    "site": "bilibili.com",
    "streams": {
        "__default__": {
            "container": "flv",
            "size": null,
            "src": [
                "http://cn-gdfs-cmcc-v-01.acgvideo.com/vg1/0/b5/13068745-1.flv?expires=1484640300&ssig=TPFV3dy9tPHytBpkf7ObeA&oi=1851803650&nfa=B2jsoD9cEoAmG7KPYo7s2g==&dynamic=1"
            ],
            "video_profile": "__default__"
        }
    },
    "title": "4、海牛皮肤+技能展示",
    "url": null
}
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=13068744&from=miniplay&player=1&sign=a9ecce21c7095ccce2b9a901d7f3fa69
you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['https://www.bilibili.com/video/av7956677/']
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1410, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1323, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1139, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 1403, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 177, in bilibili_download
    info_only=info_only)
  File "/usr/local/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 99, in bilibili_download_by_cid
    _, type_, temp = url_info(url)
  File "/usr/local/lib/python3.6/site-packages/you_get/common.py", line 414, in url_info
    response = request.urlopen(request.Request(url))
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>

**Comment by coderwangyu** [comment]
Actually I only need the first video address, but the resolution to a certain position error, slowly

**Comment by ad52825196** [comment]
It works on my machine. It was a timeout error on your machine so could be a problem of your network. Just retry it after some days or check your network. Cheers.

> {
>     "site": "bilibili.com",
>     "streams": {
>         "__default__": {
>             "container": "flv",
>             "size": null,
>             "src": [
>                 "http://ws.acgvideo.com/c/ed/13068743-1.flv?wsTime=1484658767&wsSecret2=4808f6fe940e45d9cc57abe7e5089b0b&oi=2011181516&rate=1500"
>             ],
>             "video_profile": "__default__"
>         }
>     },
>     "title": "1、狼外婆+技能展示",
>     "url": null
> }
> {
>     "site": "bilibili.com",
>     "streams": {
>         "__default__": {
>             "container": "flv",
>             "size": null,
>             "src": [
>                 "http://ws.acgvideo.com/b/89/13095615-1.flv?wsTime=1484658770&wsSecret2=7c52f1b09fd9caf27a3598b5eca205ba&oi=2011181516&rate=1500"
>             ],
>             "video_profile": "__default__"
>         }
>     },
>     "title": "2、冰原狼+技能展示",
>     "url": null
> }
> {
>     "site": "bilibili.com",
>     "streams": {
>         "__default__": {
>             "container": "flv",
>             "size": null,
>             "src": [
>                 "http://ws.acgvideo.com/9/1f/13068861-1.flv?wsTime=1484658770&wsSecret2=32a5b5a94113c230a9dd17dc25a9fe71&oi=2011181516&rate=1500"
>             ],
>             "video_profile": "__default__"
>         }
>     },
>     "title": "3、火狼+技能展示",
>     "url": null
> }
> {
>     "site": "bilibili.com",
>     "streams": {
>         "__default__": {
>             "container": "flv",
>             "size": null,
>             "src": [
>                 "http://ws.acgvideo.com/c/2c/13068745-1.flv?wsTime=1484658771&wsSecret2=036fffd91877a544174b13e2bc842004&oi=2011181516&rate=1500"
>             ],
>             "video_profile": "__default__"
>         }
>     },
>     "title": "4、海牛皮肤+技能展示",
>     "url": null
> }
> {
>     "site": "bilibili.com",
>     "streams": {
>         "__default__": {
>             "container": "flv",
>             "size": null,
>             "src": [
>                 "http://ws.acgvideo.com/6/15/13068744-1.flv?wsTime=1484658772&wsSecret2=a1c3069fb4531d8a49a1d9cd3bf2a093&oi=2011181516&rate=1500"
>             ],
>             "video_profile": "__default__"
>         }
>     },
>     "title": "5、城市英雄+技能展示",
>     "url": null
> }
> {
>     "site": "bilibili.com",
>     "streams": {
>         "__default__": {
>             "container": "flv",
>             "size": null,
>             "src": [
>                 "http://ws.acgvideo.com/a/db/13068464-1.flv?wsTime=1484658774&wsSecret2=cb2413c57b666f8324f674a2e6c08809&oi=2011181516&rate=1500"
>             ],
>             "video_profile": "__default__"
>         }
>     },
>     "title": "6、黑暗骑士+技能展示",
>     "url": null
> }
> {
>     "site": "bilibili.com",
>     "streams": {
>         "__default__": {
>             "container": "flv",
>             "size": null,
>             "src": [
>                 "http://ws.acgvideo.com/9/e5/13068465-1.flv?wsTime=1484658775&wsSecret2=ba48dec7701811c9ce86e33b19b7d926&oi=2011181516&rate=1500"
>             ],
>             "video_profile": "__default__"
>         }
>     },
>     "title": "7、豺狼+技能展示",
>     "url": null
> }
> {
>     "site": "bilibili.com",
>     "streams": {
>         "__default__": {
>             "container": "flv",
>             "size": null,
>             "src": [
>                 "http://ws.acgvideo.com/0/b7/13069070-1.flv?wsTime=1484658777&wsSecret2=1f60160733b3dbbcc8910cf8373a54c5&oi=2011181516&rate=1500"
>             ],
>             "video_profile": "__default__"
>         }
>     },
>     "title": "8、原画+技能展示",
>     "url": null
> }
>

**Comment by cnbeining** [comment]
他们的小霸王服务器又炸了呗。
