### ISSUE TITLE
bilibili海外用户如何下载视频？

### ISSUE THREAD

**Issue by hanchen999** [soimort/you-get#1626]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
handeMacBook-Pro:Desktop hanchen$ you-get -y proxy.uku.im:8888 -di http://bangumi.bilibili.com/anime/5789/play#98652
[DEBUG] get_content: http://bangumi.bilibili.com/anime/5789/play#98652
[DEBUG] post_content: http://bangumi.bilibili.com/web_api/get_source
 post_data: {'episode_id': '98652'}
you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/5789/play#98652']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.626', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1410, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1325, in script_main
    download_main(download, download_playlist, args, playlist, extractor_proxy=extractor_proxy, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1139, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/common.py", line 1403, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.626/libexec/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 133, in bilibili_download
    cid = json.loads(cont)['result']['cid']
KeyError: 'result'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

看说明好像是用unblock-youku，但是好像是json的key不对？

> [您的内容]
> [舔 :icecream:!]

**Comment by zjuchenyuan** [comment]
I think this issue has no thing to do with you_get, and you_get can not fix this problem.
You can search a proxy to "get an IP of China mainland", and specify the proxy by add parameter:  `--http-proxy <HOST:PORT>` or `--socks-proxy <HOST:PORT>`

**Comment by cnbeining** [comment]
Please refer to: https://github.com/soimort/you-get/wiki/Region-Restrictions .
