### ISSUE TITLE
Multiple download errors

### ISSUE THREAD

**Issue by geopapyrus** [soimort/you-get#1633]
I was testing you-get on a list of a few hundred youku links.
It turns out 78% worked. But then I have the list below for which you-get fails.

The video plays in the browser but you-get can't download it.

I'm using the latest version on a mac.

http://v.youku.com/v_show/id_XMTc2ODAyNzY6Ng==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTc2ODAyNzY7Ng==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTc2ODAyNzY8Ng==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTc2ODAyNzY9Ng==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTcyNjQzMDg10MA==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTg0NDk4NDY6Ng==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTg0NDk4NDY7Ng==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTg0NDk4NDY8Ng==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTg5NjI0Mjc10NA==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTg5NjI0Mjc6NA==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTg5NjI0Mjc7NA==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTg5NjI0Mjc8NA==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTg5NjI0Mjc9NA==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTkxNjM10MjkzNg==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTkxNjM11MjkzNg==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTkxNjM12MjkzNg==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTkxNjM13MjkzNg==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTkxNjM14MjkzNg==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTkxNjM15MjkzNg==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTkxNjM16MjkzNg==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTkxNjM17MjkzNg==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTkxNjM18MjkzNg==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTkxNjM19MjkzNg==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTkxNjM6MjkzNg==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTkxNjM7MjkzNg==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTkxNjM8MjkzNg==.html
you-get: [Failed] vid参数错误
http://v.youku.com/v_show/id_XMTkxNjM9MjkzNg==.html
you-get: [Failed] vid参数错误

thanks!

**Comment by rosynirvana** [comment]
```
http://v.youku.com/v_show/id_XMTc2ODAyNzY6Ng==.html
videoId2:"XMTc2ODAyNzY="
```

```
XMTc2ODAyNzY=
XMTc2ODAyNzY6Ng==
```

so it's actually incorrect to get vid from the url...

**Comment by rosynirvana** [comment]
10a32e9

```
./you-get -i http://v.youku.com/v_show/id_XMTc2ODAyNzY6Ng\=\=.html
site:                优酷 (Youku)
title:               欧洲足坛精彩配合
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          6.2 MiB (6476473 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMTc2ODAyNzY%3D&type=flv&ups_client_netip=125.45.178.175&ups_ts=1502430398&utid=vjIUEpOwpFYCAX0tsq83aBX0&ccode=0401&psid=2d796174154a34487dc68b9d368f2aaf&duration=244&expire=18000&ups_key=87ac3750e7c57d31589b282d83d517a4
    # download-with: you-get --format=flvhd [URL]
```
