### ISSUE TITLE
爱奇艺的视频无法完整下载，下载下来的文件只有音频，没有视频

### ISSUE THREAD

**Issue by fishtangtang2014** [soimort/you-get#1636]
[root@localhost you-get-master]# ./you-get -o ../iqiyi  http://www.iqiyi.com/v_19rranmap8.html
site:                爱奇艺 (Iqiyi)
title:               国新办：2016年全年GDP同比增长6.7%
stream:
    - format:        HD
      container:     m3u8
      video-profile: 540p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=HD [URL]

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://cache.m.iqiyi.com/dc/dt/aa89245x2ffbd003x777a6171/20170120/88/29/d5e9ab0d7290f5938d51acd657b24a36.m3u8?np_tag=nginx_part_tag&qd_sc=fdb16736ed727db83b5e92c95b45135e&t_sign=-0-76f90cbd92f94a2e925d83e8ccd22cb7-605899200_04022000001000000000_21 -c copy -bsf:a aac_adtstoasc ../iqiyi/国新办：2016年全年GDP同比增长6.7%.mp4
ffmpeg version 2.0.1 Copyright (c) 2000-2013 the FFmpeg developers
  built on Feb 28 2014 17:20:38 with gcc 4.1.2 (GCC) 20080704 (Red Hat 4.1.2-54)
  configuration: --disable-yasm
  libavutil      52. 38.100 / 52. 38.100
  libavcodec     55. 18.102 / 55. 18.102
  libavformat    55. 12.100 / 55. 12.100
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 79.101 /  3. 79.101
  libswscale      2.  3.100 /  2.  3.100
  libswresample   0. 17.102 /  0. 17.102
[mpegts @ 0xb5c56e0] probed stream 0 failed
[mpegts @ 0xb5c56e0] Could not find codec parameters for stream 0 (Unknown: none ([36][0][0][0] / 0x0024)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[hls,applehttp @ 0xb5ba8a0] Could not find codec parameters for stream 0 (Unknown: none ([36][0][0][0] / 0x0024)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, hls,applehttp, from 'http://cache.m.iqiyi.com/dc/dt/aa89245x2ffbd003x777a6171/20170120/88/29/d5e9ab0d7290f5938d51acd657b24a36.m3u8?np_tag=nginx_part_tag&qd_sc=fdb16736ed727db83b5e92c95b45135e&t_sign=-0-76f90cbd92f94a2e925d83e8ccd22cb7-605899200_04022000001000000000_21':
  Duration: 00:01:43.00, start: 0.000000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Unknown: none ([36][0][0][0] / 0x0024)
    Stream #0:1: Audio: aac ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 62 kb/s
Output #0, mp4, to '../iqiyi/国新办：2016年全年GDP同比增长6.7%.mp4':
  Metadata:
    encoder         : Lavf55.12.100
    Stream #0:0: Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 62 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=     813kB time=00:01:43.00 bitrate=  64.7kbits/s    
video:0kB audio:808kB subtitle:0 global headers:0kB muxing overhead 0.664569%

遇到这个问题该如何解决

**Comment by fishtangtang2014** [comment]
-rw-r--r-- 1 root root 832498 Jan 20 14:43 国新办：2016年全年GDP同比增长6.7%.mp4

下载下来的mp4文件，只有音频，没有视频。

[root@localhost you-get-master]# ./you-get -V
you-get: version 0.4.626, a tiny downloader that scrapes the web.

**Comment by zhangn1985** [comment]
看来是你的ffmpeg太老了。

**Comment by fishtangtang2014** [comment]
你确定？fmpeg太老了 @zhangn1985

**Comment by fishtangtang2014** [comment]
you-get: version 0.4.626 配套ffmpeg版本是多少？

**Comment by zhangn1985** [comment]
ffmpeg version 2.0.1 Copyright (c) 2000-2013 the FFmpeg developers
built on Feb 28 2014 17:20:38 with gcc 4.1.2 (GCC) 20080704 (Red Hat 4.1.2-54)

最新的是3.2.2

老到掉渣了～～～

**Comment by EMLVIRUS** [comment]
@zhangn1985 可以自行下载替换吗

**Comment by zhangn1985** [comment]
可以。

**Comment by redstoneleo** [comment]
有可能是你的播放器问题，可以试试看potplayer播放看看

**Comment by rosynirvana** [comment]
not a you-get issue
