### ISSUE TITLE
[xiami] 不管给什么链接，都会下载到同一首歌

### ISSUE THREAD

**Issue by lilydjwg** [soimort/you-get#1650]
比如对于 URL：  http://www.xiami.com/song/8Gku9Ce360d
you-get 会下载一首叫 我 那一场恋爱 - 曾志中 - 我 那一场恋爱.mp3 的歌。
对其它 URL 也是如此。

版本： 0.4.626

**Comment by SimonFate** [comment]
couse you didnt find the right url of what you are trying to download.

**Comment by lilydjwg** [comment]
@SimonFate Isn't that what you-get is useful for? I give it the page URL, and you-get finds the correct link to the file. But it failed twice in a row.

I don't have a lot of bandwidth so I can't investigate deeper now.

**Comment by SimonFate** [comment]
![image](https://cloud.githubusercontent.com/assets/25078789/22404675/fdcc3d68-e670-11e6-95b7-03639ae1c765.png)

**Comment by SimonFate** [comment]
![image](https://cloud.githubusercontent.com/assets/25078789/22404706/915fb30c-e671-11e6-8b9c-eb0c2f49f87a.png)

step 1.open F12 developer tool.
step 2.find the link of 立即播放.
step 3.find the ID of the song.
step 4.paste the ID in step 3 to end of the page url.
step 5. download it with magic you-get

**Comment by zhangn1985** [comment]
if re.match('http://www.xiami.com/song/\d+', url):
        id = r1(r'http://www.xiami.com/song/(\d+)', url)
        xiami_download_song(id, output_dir, merge, info_only)

这个代码应该再判断得到的id是不是长度为10的数字字符串，如果不是，则采用楼主所提供的匹配方法。

**Comment by SimonFate** [comment]
@zhangn1985 
if the last part of url begins with number,your expression would get wrong

`import requests
import re
def gettt (string1):
	expr1 = re.compile(r'http://www.xiami.com/song/(\d{8,})')
	judge = expr1.match (string1)
	if judge:
		print (judge.group())
	else:
		html = requests.get(string1,headers={
			'User-Agent':r'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36'})
		cont = html.content.decode('utf-8')
		if html.status_code == 200 : #status is 200
			expr2 = re.compile('\<a\sonclick\=\"play\(\'(\d+)\'\,\s\'default\'\,\s0,\sthis\)')
			print (r'http://www.xiami.com/song/'+str(expr2.search(cont).group(1)))
		else :
			print("request.status_code is not 200 , fail")
	
def main():
	gettt('http://www.xiami.com/song/8Gku9Ce360d')      #put your url here
	
if __name__ == '__main__':
	main()`

my code would help to find the right url

**Comment by SimonFate** [comment]
`cc`

**Comment by lilydjwg** [comment]
咦，你这个 URL 是哪里来的？我的那个是从搜索结果点过去的。

2017年1月29日 22:19，"SimonFate" <notifications@github.com>写道：

**Comment by lilydjwg** [comment]
抱歉我回复的时候 Gmail 还没加载出来后边的邮件。

我知道问题所在了，谢谢你们。

2017年1月30日 14:48，"lilydjwg" <lilydjwg@gmail.com>写道：

**Comment by SimonFate** [comment]
@lilydjwg 
you coulde use my code , it would much easier than you use F12 tool.
