### ISSUE TITLE
Can not download video from facebook

### ISSUE THREAD

**Issue by tranvantu** [soimort/you-get#1651]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by MaggieNgWu** [comment]
maggie@maggie-HP-Compaq-Elite-8300-SFF:~/Desktop$ sudo you-get --debug 'https://www.facebook.com/siewlankongfu/videos/vl.1940892769479503/1249884905077307/?type=1'
[DEBUG] get_response: http://www.facebook.com/siewlankongfu/videos/vl.1940892769479503/1249884905077307/?type=1
[DEBUG] url_info: https://video.xx.fbcdn.net/v/t43.1792-2/15371128_203549333437132_3495926761298853888_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&oh=b7f83b3ff96f05ee96977acbf42cd219&oe=593FB9A4
Site:       Facebook.com
Title:      电影经典笑话 - 皇后大道東～
Type:       MPEG-4 video (video/mp4)
Size:       5.64 MiB (5914401 Bytes)

Downloading 电影经典笑话 - 皇后大道東～.mp4 ...
31.0% (  1.8/  5.6MB) ├██████████████████████████████──────────────────────────────────────────────────────────────────┤[1/1]    2 MB/syou-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['https://www.facebook.com/siewlankongfu/videos/vl.1940892769479503/1249884905077307/?type=1']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/facebook.py", line 27, in facebook_download
    download_urls(urls, title, ext, size, output_dir, merge=False)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 799, in download_urls
    url_save(url, output_filepath, bar, refer = refer, faker = faker, headers = headers, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 549, in url_save
    buffer = response.read(1024 * 256)
  File "/usr/lib/python3.4/http/client.py", line 529, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 568, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 769, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 641, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
