### ISSUE TITLE
变态的douyutv遇上了多此一举的神经病mpv和potplayer。。。结果是。。。

### ISSUE THREAD

**Issue by Justsoos** [soimort/you-get#1660]
目前这个问题不是you-get问题，可以变相解决。

#1590  在这里已经发现，potplayer 会去主动用掉token，试一次连接douyu 的play url，今天发现，mpv 也会用youtube-dl 去试一次，用掉token，返回 403 forbiden，这样就导致下面几个方法看斗鱼douyu.com 都会失败：

$you-get -p mpv http://DOUYU
$you-get -p potplayer http://DOUYU
$youtube-dl -g http://DOUYU | xargs mpv

下面几个方式，直接下载，或一次性使用token的就没问题：
$you-get -p vlc http://DOUYU
$youtube-dl http://DOUYU -o - | mpv -

真是变态的斗鱼，遇上了神经病播放器。。。

**Comment by Justsoos** [comment]
补充：如果你的电脑上的youtuble-dl 安装了独立版本，就会出现这个问题。目前看，还不是mpv 内置的youtube-dl 导致的问题，很是奇怪。

**Comment by Justsoos** [comment]
#1657  https://github.com/rg3/youtube-dl/pull/11931 因为今天斗鱼有个直播间 room_id\" 代码问题，让youtube-dl 和you-get 同时中招，发现了这个bug，
$mpv http://DOUYU
也是可以播放的。

**Comment by Justsoos** [comment]
找到了一个解决方法：

` you-get.exe -p "mpv --no-ytdl" https://www.douyu.com/xxx`

感觉好原始人啊。哈哈哈
另外测试了you-get -o 参数，和youtube-do -o 不是一回事啊，没法用来 stdout

**Comment by soimort** [comment]
非you-get问题。
