### ISSUE TITLE
no windows exe file in the latest release

### ISSUE THREAD

**Issue by chantisnake** [soimort/you-get#1664]
Hi, I am the maintainer of `you-get` chocolatey package, I notice that there is no windows exe in the latest 2 releases, will it be updated later?

**Comment by dajbd** [comment]
https://github.com/soimort/you-get/releases
0.4.652
there is no windows exe file?
pls add windows exe release version.
thanks!

**Comment by chantisnake** [comment]
exe added, thank you.
