### ISSUE TITLE
关于爱奇艺视频处理下载

### ISSUE THREAD

**Issue by mogu1121** [soimort/you-get#1669]
一个m3u8文件里有n个不同段的视频碎片
为什么不修改决定碎片大小的参数，直接用ffmpeg下载太慢了
start=0&end=761400&contentlength=761400

**Comment by rosynirvana** [comment]
试验过，结论是有些m3u8可以，有些不行
想要测试这个特性的可以 https://github.com/rosynirvana/you-get/tree/iqiyi_testing
