### ISSUE TITLE
URL Protocol协议实现调用you-get -p mpv URL命令  chrome中无法使用

### ISSUE THREAD

**Issue by liuhuancom** [soimort/you-get#1679]
我搞了一个书签脚本 类似收藏到有道云笔记 点击书签 通过URL Protocol协议来实现调用`you-get -p mpv URL`命令 但是在chrome中不行 360和Opera中可以正常使用 不知道能否有好的解决办法 望回复 

![mpvget1](https://cloud.githubusercontent.com/assets/3874638/22860722/7073d8d2-f141-11e6-9c5e-3c7da484ed7e.gif)

![mpvget](https://cloud.githubusercontent.com/assets/3874638/22860704/f910ca02-f140-11e6-94f8-a23b40d34a47.gif)

以下是代码

mpvget.reg
```reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\MPVYOUGET]
@="URL:MPVYOUGET Protocol Handler"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\MPVYOUGET\shell]

[HKEY_CLASSES_ROOT\MPVYOUGET\shell\open]

[HKEY_CLASSES_ROOT\MPVYOUGET\shell\open\command]
@="C:\\ProgramData\\Chocolatey\\lib\\you-get\\tools\\mpvget.bat %1"
```

mpvget.bat
```bat
@echo off
set str=%1%
set str2=%str:~12%
echo you-get -p mpv "%str2%"
you-get --debug -p mpv "%str2%"
pause
```

书签连接

```js
javascript: void((function() {	console.log('mpvyouget://' + window.location.href);window.open('mpvyouget://'+window.location.href);})())
```

**Comment by Erk-** [comment]
I do not have any problems like the one you describe it works for me in chrome, edge and firefox I think it was just a temporary problem. But you should change your mpvget.bat to
```bash
@echo off
set str=%*
set str2=%str:~12%
echo you-get -p "mpv --no-ytdl" "%str2%"
you-get --debug -p "mpv --no-ytdl" "%str2%"
pause
```
else it will not work with Youtube and other sites like Douyu.

**Comment by liuhuancom** [comment]
谢谢 我已经将这个软件推到choco上了 
可以用 ```choco install mpvget -version 1.0``` 来安装
