### ISSUE TITLE
Can't download all videos from naver

### ISSUE THREAD

**Issue by fanxy121** [soimort/you-get#1690]
Can't download all videos from naver

C:\Documents and Settings\Administrator>you-get --debug http://tv.naver.com/v/902951you-get: version 0.4.652, a tiny downloader that scrapes the web.you-get: ['http://tv.naver.com/v/902951']Traceback (most recent call last):  File "C:\Program Files\Python34\lib\runpy.py", line 170, in _run_module_as_main    "__main__", mod_spec)  File "C:\Program Files\Python34\lib\runpy.py", line 85, in _run_code    exec(code, run_globals)  File "C:\Program Files\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>  File "C:\Program Files\Python34\lib\site-packages\you_get\__main__.py", line 92, in main    main(**kwargs)  File "C:\Program Files\Python34\lib\site-packages\you_get\common.py", line 1407, in main    script_main('you-get', any_download, any_download_playlist, **kwargs)  File "C:\Program Files\Python34\lib\site-packages\you_get\common.py", line 1320, in script_main    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only,  File "C:\Program Files\Python34\lib\site-packages\you_get\common.py", line 1136, in download_main    download(url, **kwargs)  File "C:\Program Files\Python34\lib\site-packages\you_get\common.py", line 1400, in any_download    m.download(url, **kwargs)  File "C:\Program Files\Python34\lib\site-packages\you_get\extractors\naver.py", line 23, in naver_download    Subject = doc_info.getElementsByTagName('Subject')[0].firstChild

**Comment by lki2019** [comment]
加载不出来

**Comment by rosynirvana** [comment]
```
./you-get -di http://tv.naver.com/v/902951
[DEBUG] get_content: http://tv.naver.com/v/902951
[DEBUG] get_content: https://apis.naver.com/rmcnmv/rmcnmv/vod/play/v2.0/4B90933ED3D493A0BBE27E8069112B68E4BF?key=V126a05372e4760c99c93788b421cc78e66c624d2b2b701057e94788b421cc78e66c6
you-get: LOCATION_ISSUE
```
https://github.com/soimort/you-get/commit/ed0451016c515417cd201ebd53405aa96d44501e
cannot test further without a Korea proxy
