### ISSUE TITLE
希望支持PPTV高清下载。。。

### ISSUE THREAD

**Issue by ztytian** [soimort/you-get#1695]
#1655 中似乎说PPTV的TD视频可以通过api绕过限制直接获取。。不知道you-get是不是可以加上下载PPTV高清视频的功能（抱歉本人python水平实在太低不能完成这个）

In the closed issue mentioned above PPTV videos seem to be accessible via an api call even without VIP accounts. I wonder if you-get could add this functionality for downloading HD videos from PPTV. (Sorry but this task would be too hard for my current python abilities)

**Comment by soimort** [comment]
Closed via #2025.
