### ISSUE TITLE
爱奇艺无法下载了

### ISSUE THREAD

**Issue by weigeloveu** [soimort/you-get#1701]
you-get -d http://www.iqiyi.com/v_19rrangfjs.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/605644500/6fc2ec023a230b3f3fe4b1e401dcadc9/?t=1487587711973&sc=483d92eea472fd5cf34bf65fd1cd8f40&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               晓松奇谈_20170120期
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://cache.m.iqiyi.com/mus/200688101/eeb19446110408ce229055a5e414b066/afbe8fd3d73448c9//20170119/a9/27/edbd21c150ab97683c9d533fe9c7df80.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=605644500&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1487587733123&qd_sc=6f258883062bc59762bcac8e7f84277b&qypid=605644500_04022000001000000000_17&qd_k=483d92eea472fd5cf34bf65fd1cd8f40&other= -c copy -bsf:a aac_adtstoasc 晓松奇谈_20170120期.mp4
ffmpeg version N-79068-g6b7ce0e Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmfx --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 19.100 / 55. 19.100
  libavcodec     57. 28.103 / 57. 28.103
  libavformat    57. 28.102 / 57. 28.102
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 39.102 /  6. 39.102
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
[hls,applehttp @ 0353ee80] Failed to open segment of playlist 0
    Last message repeated 3 times

**Comment by rosynirvana** [comment]
```
you-get -d http://www.iqiyi.com/v_19rrangfjs.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/605644500/6fc2ec023a230b3f3fe4b1e401dcadc9/?t=1488037359284&sc=a78e6aee44a23d0471ed8979bcd252fc&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               晓松奇谈_20170120期
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://cache.m.iqiyi.com/mus/200688101/eeb19446110408ce229055a5e414b066/afbe8fd3d73448c9//20170119/a9/27/edbd21c150ab97683c9d533fe9c7df80.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=605644500&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1488037359338&qd_sc=80f82ade2fe060de39664ebad1812553&qypid=605644500_04022000001000000000_17&qd_k=a78e6aee44a23d0471ed8979bcd252fc&other= -c copy -bsf:a aac_adtstoasc 晓松奇谈_20170120期.mp4
ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.2.4 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, hls,applehttp, from 'http://cache.m.iqiyi.com/mus/200688101/eeb19446110408ce229055a5e414b066/afbe8fd3d73448c9//20170119/a9/27/edbd21c150ab97683c9d533fe9c7df80.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=605644500&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1488037359338&qd_sc=80f82ade2fe060de39664ebad1812553&qypid=605644500_04022000001000000000_17&qd_k=a78e6aee44a23d0471ed8979bcd252fc&other=':
  Duration: 00:46:34.00, start: 0.000000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv), 1280x720, 25 fps, 25 tbr, 90k tbn, 25 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to '晓松奇谈_20170120期.mp4':
  Metadata:
    encoder         : Lavf57.56.101
    Stream #0:0: Video: hevc (Main) ([35][0][0][0] / 0x0023), yuv420p(tv), 1280x720, q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   13 fps=0.0 q=-1.0 size=      11kB time=00:00:00.51 bitrate= 180.7kbits/frame=   25 fps= 25 q=-1.0 size=      17kB time=00:00:01.02 bitrate= 140.0kbits/
```
无法重复

**Comment by qusan2004** [comment]
爱奇艺确实无法下载了

**Comment by rosynirvana** [comment]
重复不了

我猜会不会是ffmpeg版本太老，去年3月修复过一个类似的bug
[ffmpeg trac url](https://trac.ffmpeg.org/ticket/5248)

请尝试用ffmpeg最新的stable release替换nightly build
