### ISSUE TITLE
如何更换下载文件夹? Change download location?

### ISSUE THREAD

**Issue by brlala** [soimort/you-get#1702]
I am using a SSD on my C: primary hard drive. The default download location for you-get is at C:\Users\User\AppData\Local\VirtualStore\Windows\SysWOW64
Since the space is limited, can I change the download location to my secondary D: drive?

电脑C:用了SSD硬盘。用you-get它直接就下载去C:\Users\User\AppData\Local\VirtualStore\Windows\SysWOW64。居于空间有限，有没有方法能更改下载去我的D: 硬盘?

谢谢

**Comment by Invok3r** [comment]
> Use the --output-dir/-o option to set the path

https://github.com/soimort/you-get#set-the-path-and-name-of-downloaded-file

**Comment by brlala** [comment]
Thanks! this works. Do you know how do I force stop a download? I'm downloading streams from douyu.com however if I turn the cmd off when the stream is not finished yet, I get an incomplete FLV file which cannot seek. (cannot fast forward or rewind)

**Comment by Invok3r** [comment]
Try `CTRL+C`

**Comment by brlala** [comment]
using that part results in a .flv.part extension file. When I renamed the extension to .flv and played the movie in MPC-HC/VLC, the video can play normally. However I am not able to seek(rewind or fast forward) the vide. Any other suggestion?

**Comment by Invok3r** [comment]
Maybe you should use another player like Potplayer or MPV.

**Comment by rosynirvana** [comment]
可以尝试用ffmpeg重新封装得到的不完整的flv
···
ffmpeg -i foo.flv.part -c copy -o out.mp4
···

**Comment by brlala** [comment]
@rosynirvana http://i.imgur.com/glRO8rv.png 显示这个说没有选择 'o'

和这个有相关吗? 

> Hyper fast Audio and Video encoder
> usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
>

**Comment by Erk-** [comment]
You should not have the -o it should be
`ffmpeg -i foo.flv.par -c copy out.mp4`

**Comment by brlala** [comment]
Wow it works now! Am able to close the part.flv files using the command 
> ffmpeg -i foo.flv.par -c copy out.mp4

Appreciate your help very much and much thanks! 成功了 谢谢！ @Invok3r  @rosynirvana  and @Erk-
