### ISSUE TITLE
you-get能否支持socks5代理？

### ISSUE THREAD

**Issue by sbw983** [soimort/you-get#1704]
看了说明，you-get只能用http代理，用socks5代理只能通过tsocks转，但是用tsocks转老是出错，能否直接支持socks5代理，谢谢

**Comment by rosynirvana** [comment]
-s | --socks-proxy <HOST:PORT>      Use an SOCKS5 proxy for downloading.

要在py环境下再装一个pysocks

**Comment by cnbeining** [comment]
Closed due to question solved and not moving forward. Please reopen if you need any more help.
