### ISSUE TITLE
下载pptv会员视频是否需要传入cookie文件？chrome浏览器的cookie文件是什么？

### ISSUE THREAD

**Issue by zky999** [soimort/you-get#1714]
you-get: v0.4.652
os: macOS v10.12
chrome version: 56

**Comment by rosynirvana** [comment]
会员视频应该需要
下插件导出cookie

**Comment by hwcj123** [comment]
我尝试过优酷的vip视频，只能下载一小部分，用插件导出优酷的cookie也试过，同样如此，测试视频地址：http://v.youku.com/v_show/id_XMjUyMTUyNjM4NA==.html?spm=a2h0j.8191423.item_XMjUyMTUyNjM4NA==.A   （目前为vip视频）

**Comment by hwcj123** [comment]
以解决问题 我是直接在浏览器下找的cookie

**Comment by cnbeining** [comment]
Refer to: https://github.com/soimort/you-get/wiki/%E4%B8%AD%E6%96%87%E8%AF%B4%E6%98%8E#%E5%8A%A0%E8%BD%BDcookie
