### ISSUE TITLE
Java execute your-get command prompt "[error] oops, the current environment does not seem to support Unicode."

### ISSUE THREAD

**Issue by geenquan** [soimort/you-get#1717]
I can execute your-get command succeful. But I can not execute the same your-get command in java. the java code like this
`String ss = "/usr/local/bin/you-get  http://v.youku.com/v_show/id_XMjUzMDY3NTY4OA==.html?spm=a2h1n.8251846.0.0";`
`Runtime.getRuntime().exec(ss);`

and the error is :"

> - you-get: [error] oops, the current environment does not seem to support Unicode.
> - you-get: please set it to a UTF-8-aware locale first,
> - you-get: so as to save the video (with some Unicode characters) correctly.
> - you-get: you can do it like this:
> - you-get:     (Windows)    % chcp 65001 
> - you-get:     (Linux)      $ LC_CTYPE=en_US.UTF-8
> "

**Comment by greydesolate** [comment]
Do you solve this problem?I meet this too.Could you help me with this problem?

**Comment by mouse1130** [comment]
Do you solve this problem?I meet this too.Could you help me with this problem?

**Comment by mouse1130** [comment]
@greydesolate 
You need to pay attention to the three lines have already told you the solution.
you-get: you can do it like this:
you-get: (Windows) % chcp 65001
you-get: (Linux) $ LC_CTYPE=en_US.UTF-8

**Comment by greydesolate** [comment]
@mouse1130 
Thx for your help!  I solve this problem.

**Comment by flixwito** [comment]
Newb here, i have this problem too and i don't get what the solution means.

**Comment by rosynirvana** [comment]
@flixwito failed in java or some other console?

**Comment by geenquan** [comment]
I have solved this problem. 
Change code in this way.

String ss = "/usr/local/bin/you-get http://v.youku.com/v_show/id_XMjUzMDY3NTY4OA==.html?spm=a2h1n.8251846.0.0";
String[] envp = new String[]{"LC_CTYPE=en_US.UTF-8"};
Runtime.getRuntime().exec(ss, envp);

**Comment by ad52825196** [comment]
@geenquan Thank you. It helps.
For people using ProcessBuilder, you can change the environment in the following way:
```java
ProcessBuilder pb = new ProcessBuilder(command); 
Map<String, String> env = pb.environment(); 
env.put("LC_CTYPE", "en_US.UTF-8"); 
```
