### ISSUE TITLE
希望支持www.yy.com上的直播视频下载

### ISSUE THREAD

**Issue by barnett2010** [soimort/you-get#1718]
www.yy.com
国内算是最早也是早大的直播平台了。上面资源丰富。保存起来不是很方便。

另外，微博视频全面更新了，变成了weibo.com/tv。已经无法下载了。

**Comment by ikzk** [comment]
An example link: http://www.yy.com/x/15012_1244573176_13739310_1491495025259

**Comment by rosynirvana** [comment]
please close this in favor of #1846

**Comment by lki2019** [comment]
1846 现在还没关闭
