### ISSUE TITLE
douyu失效！

### ISSUE THREAD

**Issue by chacha1024** [soimort/you-get#1720]
在提交前，请确保您已经检查了以下内容!

- [ √] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ √] 您的`you-get`为最新版.
- [ √] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ √] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ √] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
ou-get --debug -i http://douyutv.com/danche
[DEBUG] get_content: http://www.douyu.com/danche
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=339610
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://douyutv.com/danche']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/douyutv.py", line 40, in douyutv_download
    with urllib.request.urlopen(req) as response:
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
这个问题发生在今天[2017.2.28]下午，起因有可能是因为有人在斗鱼的开发者群里讨论了关于you-get的事情导致ytdl方法和you-get方法失效！目前ytdl方式和you-get方式解析斗鱼直播间均显示http 403 forbidden
> [舔 :icecream:!]

**Comment by yan12125** [comment]
我把youtube-dl修好了，挺簡單的 :D https://github.com/rg3/youtube-dl/commit/f4c68ba372655c8ff4d6b1cfecfa129796159afd

**Comment by chacha1024** [comment]
斗鱼修改了直播流文件格式 需要重新分析它的格式 似乎在每5分钟左右会有认证机制进行防盗链处理

**Comment by brlala** [comment]
用VLC完全加载不到直播
```
D:\>youtube-dl -o - "https://www.douyu.com/1516303" | vlc -
[DouyuTV] 1516303: Downloading room info
[DouyuTV] 1516303: Downloading video info
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

如果直接下载只能下载5分钟就出现HTTP Error 403 Forbidden
`youtube-dl -o - "https://www.douyu.com/1516303" | vlc -`

**Comment by mengmo** [comment]
@brlala
youtube-dl 看视频直接用 mpv 就好了

**Comment by spacemeowx2** [comment]
我逆了斗鱼 Flash 播放器的方法, 想抄的话可以翻译一下XD
spacemeowx2/DouyuHTML5Player@97c72a8f4e63f9b17c176d9c36d4841b5951e478

**Comment by brlala** [comment]
@mengmo VLC和MPV用法是一样的啊，现在每5分钟就出现HTTP403 error，除非有人用 @spacemeowx2 的方法更新you-get。可是好像因为 DouyuHTML5Player 没有license，youtube-dl和you-get都不能用他的方法。可惜啊 :(

> As that work has no license declaration, youtube-dl can't use it.

**Comment by brlala** [comment]
那其实逆向演算法可以被列为 clean room design 吧？毕竟都不是原一对一的抄袭，只是学习他的思路解析。

**Comment by cnbeining** [comment]
一般逆向都是违反EULA的。

**Comment by bupmc** [comment]
作者说“package.json 里写的是 MIT, 随便用吧”
https://github.com/spacemeowx2/DouyuHTML5Player/commit/97c72a8f4e63f9b17c176d9c36d4841b5951e478

**Comment by debugzxcv** [comment]
https://gist.github.com/debugzxcv/85bb2750d8a5e29803f2686c47dc236b
spacemeowx2/DouyuHTML5Player@5065e5e

**Comment by guest6379** [comment]
> https://gist.github.com/debugzxcv/85bb2750d8a5e29803f2686c47dc236b
spacemeowx2/DouyuHTML5Player@5065e5e
好人一生平安 @debugzxcv A nice man always has good luck, thanks for sharing.

**Comment by chacha1024** [comment]
各位 youtube-dl 已经使用新的api key成功解决403forbidden的问题 肯请翻译移植

**Comment by incharges** [comment]
感謝所有熱心提供協助的大神 確實已可使用. 還有個小問題:不知新版api是否可更改cdn,目前預設cnd為'ws'
,不知能否像之前一樣手動更改為'tct','ws2','dl',畢竟有時預設線路不穩,若能更改就更好了,謝謝

**Comment by Alphat-PC** [comment]
import hashlib
        import json
        import pprint
        import urllib.request

        roomid = xxxxxxxxxxxxxxxxxxxxxx

        tt = int(time.time())

        # 'cdns': ['ws', 'tct', 'ws2', 'dl']
        # opts = 'cdn=dl&rate=0'
        opts = 'rate=0'

        signContent = 'lapi/live/thirdPart/getPlay/{}?aid=pcclient&{}&time={}9TUk5fjjUjg9qIMH3sdnh'.format(roomid, opts, tt).encode('utf-8')
        sign = hashlib.md5(signContent).hexdigest()
        url = 'https://coapi.douyucdn.cn/lapi/live/thirdPart/getPlay/{}?{}'.format(roomid, opts)

        req = urllib.request.Request(url, headers = {'aid': 'pcclient', 'auth': sign, 'time': tt})
        content = json.loads(urllib.request.urlopen(req).read().decode('utf-8'))

        pprint.pprint(content, width = 9999)

你把rate=0改成cdn=ws2&rate=0之类的就可以控制线路啦。

**Comment by incharges** [comment]
@Alphat-PC
非常感謝您的協助 真的可以了

**Comment by wjm2038** [comment]
@Alphat-PC 请问完整的代码是哪一个啊

**Comment by 0772boy** [comment]
@Alphat-PC  想用易语言写出这个获取过程，能否请教一下？python的代码是没问题，可是转成易语言写出来尝试很多次总是获取失败。非常感谢。82441661#qq.com

**Comment by rosynirvana** [comment]
outdated
