### ISSUE TITLE
Flexible argument/switch order?

### ISSUE THREAD

**Issue by fireattack** [soimort/you-get#1726]
It it possible?

Like supporting `you-get https://www.youtube.com/watch?v=XHGKIzCcVa0 -i`

**Comment by rosynirvana** [comment]
should be trivial
'''
diff --git a/src/you_get/common.py b/src/you_get/common.py
index 2edbc42..3061c67 100755
--- a/src/you_get/common.py
+++ b/src/you_get/common.py
@@ -1192,7 +1192,7 @@ def script_main(script_name, download, download_playlist, **kwargs):
         opts = ['playlist'] + opts

     try:
-        opts, args = getopt.getopt(sys.argv[1:], short_opts, opts)
+        opts, args = getopt.gnu_getopt(sys.argv[1:], short_opts, opts)
     except getopt.GetoptError as err:
         log.e(err)
         log.e("try 'you-get --help' for more options")diff --git a/src/you_get/common.py b/src/you_get/common.py
index 2edbc42..3061c67 100755
--- a/src/you_get/common.py
+++ b/src/you_get/common.py
@@ -1192,7 +1192,7 @@ def script_main(script_name, download, download_playlist, **kwargs):
         opts = ['playlist'] + opts

     try:
-        opts, args = getopt.getopt(sys.argv[1:], short_opts, opts)
+        opts, args = getopt.gnu_getopt(sys.argv[1:], short_opts, opts)
     except getopt.GetoptError as err:
         log.e(err)
         log.e("try 'you-get --help' for more options")
'''

any bugs?

**Comment by rosynirvana** [comment]
close via #1736
