### ISSUE TITLE
Centos java调用 you-get 提示 the current environment does not seem to support Unicode.

### ISSUE THREAD

**Issue by greydesolate** [soimort/you-get#1727]
系统是centos 
Jdk 1.7
tomcat7
系统编码格式如下：
#  locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"

系统上Python3编码格式：
>>> import sys
>>> sys.getdefaultencoding() 
'utf-8'

java代码：
String command =“python3 /usr/local/python3/bin/you-get --debug --timeout 10 --json http://www.bilibili.com/video/av6234329/”
String[] envp = { "LANG=UTF-8" };
			p = Runtime.getRuntime().exec(command,envp);
			inputStream = p.getInputStream();

输入日志如下：
python3 /usr/local/python3/bin/you-get --debug --timeout 10 --json http://www.bilibili.com/video/av6234329/
java.lang.UNIXProcess$ProcessPipeInputStream@6e88ab64
lineError[DEBUG] get_content: http://www.bilibili.com/video/av6234329/
lineError[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=10127245&from=miniplay&player=1&sign=35630b987e6b836c19fd43a8a4ea6c53
lineErroryou-get: [error] oops, the current environment does not seem to support Unicode.
lineErroryou-get: please set it to a UTF-8-aware locale first,
lineErroryou-get: so as to save the video (with some Unicode characters) correctly.
lineErroryou-get: you can do it like this:
lineErroryou-get:     (Windows)    % chcp 65001 
lineErroryou-get:     (Linux)      $ LC_CTYPE=en_US.UTF-8

**Comment by rosynirvana** [comment]
trackback(calling stack)打印到stdout去了
总之去stdout看看calling stack是什么样的，哪里抛出的异常
或者改common.py 772行
```
traceback.print_exc(file=sys.stdout)
```
```sys.stdout```改成```sys.stderr```
看calling stack在哪里异常

**Comment by greydesolate** [comment]
十分感谢你的回复。我看了下Linux里的common.py文件。我这边在758行有
`traceback.print_exc(file=sys.stdout)`
我改成了你说的sys.stdout改成sys.stderr
但是输出内容没有变化，不知道是不是我改的地方不对？

**Comment by rosynirvana** [comment]
应该是``` except UnicodeEncodeError:```这一行后面加一行
```raise```

**Comment by greydesolate** [comment]
感谢~恩输出有变化了。最后 提示ascii无法转换的问题了。。但是不知道怎么处理 。。。
lineError[DEBUG] get_content: http://www.bilibili.com/video/av6234329/
lineError[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=10127245&from=miniplay&player=1&sign=35630b987e6b836c19fd43a8a4ea6c53
lineErrorTraceback (most recent call last):
lineError  File "/usr/local/python3/bin/you-get", line 11, in <module>
lineError    sys.exit(main())
lineError  File "/usr/local/python3/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
lineError    main(**kwargs)
lineError  File "/usr/local/python3/lib/python3.6/site-packages/you_get/common.py", line 1408, in main
lineError    script_main('you-get', any_download, any_download_playlist, **kwargs)
lineError  File "/usr/local/python3/lib/python3.6/site-packages/you_get/common.py", line 1320, in script_main
lineError    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
lineError  File "/usr/local/python3/lib/python3.6/site-packages/you_get/common.py", line 1136, in download_main
lineError    download(url, **kwargs)
lineError  File "/usr/local/python3/lib/python3.6/site-packages/you_get/common.py", line 1401, in any_download
lineError    m.download(url, **kwargs)
lineError  File "/usr/local/python3/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 181, in bilibili_download
lineError    info_only=info_only)
lineError  File "/usr/local/python3/lib/python3.6/site-packages/you_get/extractors/bilibili.py", line 104, in bilibili_download_by_cid
lineError    download_urls(urls, title, type_, total_size=None, output_dir=output_dir, merge=merge)
lineError  File "/usr/local/python3/lib/python3.6/site-packages/you_get/common.py", line 743, in download_urls
lineError    json_output_.download_urls(urls=urls, title=title, ext=ext, total_size=total_size, refer=refer)
lineError  File "/usr/local/python3/lib/python3.6/site-packages/you_get/json_output.py", line 44, in download_urls
lineError    output(ve)
lineError  File "/usr/local/python3/lib/python3.6/site-packages/you_get/json_output.py", line 15, in output
lineError    print(json.dumps(out, indent=4, sort_keys=True, ensure_ascii=False))
lineErrorUnicodeEncodeError: 'ascii' codec can't encode characters in position 395-411: ordinal not in range(128)

**Comment by rosynirvana** [comment]
common.py这里改一改，把default_encoding打印出来看看？
```
if sys.stdout.isatty():
    default_encoding = sys.stdout.encoding.lower()
else:
    default_encoding = locale.getpreferredencoding().lower()
```

比如
```python
if sys.stdout.isatty():
    default_encoding = sys.stdout.encoding.lower()
    print('isatty')
else:
    default_encoding = locale.getpreferredencoding().lower()
    print('not a tty')
print(default_encoding)
```

**Comment by greydesolate** [comment]
感谢你的协助。发现问题了。
输出的是**ascii**
我怀疑是centos上之前有python2我没有卸载。进去看这里面的编码是ascii的。
但是我很不明白为什么java调用命令的时候

python3 /usr/local/python3/bin/you-get --debug --timeout 10 --json http://www.bilibili.com/video/av6234329/

已经指认python3了。竟然还会获取使用到python2.6的属性。
直接在centos里使用you-get是可以的没有任何问题。就是java调用的时候感觉莫名用错了python环境。

# whereis python3
python3: /usr/bin/python3 /usr/local/python3
# whereis python
python: /usr/bin/python2.6 /usr/lib/python2.6 /usr/lib64/python2.6 /usr/include/python2.6 /usr/share/man/man1/python.1.gz

我怀疑难道我装Python3的时候漏了什么配置么，还在搜索Python3配置问题，又或许java调用难道还有默认的Python调用环境需要配置么？

**Comment by rosynirvana** [comment]
ascii上面应该还有一行打印信息，显示encoding是从哪里读取的

**Comment by greydesolate** [comment]
哦！这个家伙啊。。我去搜搜。。你回复真快。。太感谢了。。
java.lang.UNIXProcess$ProcessPipeInputStream@240afeb5
not a tty
ansi_x3.4-1968

**Comment by rosynirvana** [comment]
整个流程是这样的
首先，输出说明了```default_encoding```是从```locale.getperferredencoding()```读取的
(这个应该不重要，因为文档中说stdout在unix上也是从同一个方法里读的)

然后相关的标准库源码文件有三个
[lib/locale.py](https://github.com/python/cpython/blob/3.6/Lib/locale.py)
[lib/_bootlocale.py](https://github.com/python/cpython/blob/3.6/Lib/_bootlocale.py)
[Modules/_localmodule.c](https://github.com/python/cpython/blob/master/Modules/_localemodule.c)

按惯例lib里面是py，Modules里面是c
对于有langinfo.h的不太老的unix系统，入口在第一个文件的631行
做的事情是
1. 先保存setlocale的值
2. 然后按POSIX标准做法setlocale(LC_CTYPE, '')
3. 用```_bootlocale```里的```getperferredencoding```读取字符集信息
4. 再还原setlocale的值
setlocale是_setlocale的别名，相关branching在第三个文件的108行

所谓POSIX标准做法可以参考unix系统文档里的解释，例如
[setlocale](http://man7.org/linux/man-pages/man3/setlocale.3.html)
简单来说就是先setlocale(LC_CTYPE, '')然后再用nl_langinfo读标准值

其中第三步是交给Modules的C代码做的，在```locale.py```的上下文中捕获异常，如果失败了会silent fail。在OS X上fallback到UTF-8，在其他unix上似乎是返回空字符串

fallback到ansi的情况有点像没有setlocale(LC_CTYPE)但是直接读了nl_langinfo，例如可以试验下
```c
#include <stdio.h>
#include <langinfo.h>
#include <locale.h>

int main()
{
    /* setlocale(LC_CTYPE, ""); */
    printf("%s\n", nl_langinfo(CODESET));
    return 0;
}
```
把注释符号去掉，就能读到正确的字符集信息

可以试试在py 标准库locale.py里加debug信息继续找问题在哪里，Tomcat或者JDK都是复杂的庞然大物，我好多年不写java也猜不出问题在哪里

也可以试着直接在common.py手动指定字符集

**Comment by greydesolate** [comment]
感谢指导。

最终发现是我JAVA调用的问题。很抱歉。。。十分十分十分感谢rosynirvana积极的指导！

用JAVA调用Linux命令时，指定字符集用UTF-8不行,必须精确指认。


之前报错代码：
String[] envp = { "LANG=UTF-8" };
p = Runtime.getRuntime().exec(command,envp);
将第一行修改为
String[] envp = { "LANG=en_US.UTF-8" };

谢谢！
