### ISSUE TITLE
优酷会员视频没有下载地址

### ISSUE THREAD

**Issue by scegg** [soimort/you-get#1729]
优酷会员视频，主要是短视频，无法获取下载地址。

url可以正常播放。
但在you-get下载时，使用u开关提示无法获取到下载地址，json开关返回的数组中key为-1，没有path属性。如同多段会员视频的情况，但这个情况并不会发生在多段视频的首段。

例如：
>you-get -u -c cookies.txt http://v.youku.com/v_show/id_XMjU1MTg0MzUwNA==.html?from=zpdvip.001
site:                优酷 (Youku)
title:               梁文道谈宁波老虎伤人致死事件
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          52.8 MiB (55416732 bytes)
    # download-with: you-get --format=hd3 [URL]

you-get: [Failed] Cannot extract video source.
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

>you-get --json -c cookies.txt http://v.youku.com/v_show/id_XMjU1MTg0MzUwNA==.html?from=zpdvip.001
{
    "site": "优酷 (Youku)",
    "streams": {
        "flvhd": {
            "container": "flv",
            "pieces": [
                {
                    "fileid": "030002010058B68F06B4BD2BF36792819C526D-1881-3992-8F8B-3A3E15C1F8BD",
                    "segs": [
                        {
                            "fileid": "030002010058B68F06B4BD2BF36792819C526D-1881-3992-8F8B-3A3E15C1F8BD",
                            "key": -1,
                            "size": "7350689",
                            "total_milliseconds_audio": "142013",
                            "total_milliseconds_video": "141667"
                        }
                    ]
                }
            ],
            "size": 7350689,
            "video_profile": "标清"
        },
        "hd2": {
            "container": "flv",
            "pieces": [
                {
                    "fileid": "030001010058B690FAB4BD2BF36792819C526D-1881-3992-8F8B-3A3E15C1F8BD",
                    "segs": [
                        {
                            "fileid": "030001010058B690FAB4BD2BF36792819C526D-1881-3992-8F8B-3A3E15C1F8BD",
                            "key": -1,
                            "size": "28785426",
                            "total_milliseconds_audio": "141967",
                            "total_milliseconds_video": "141680"
                        }
                    ]
                }
            ],
            "size": 28785426,
            "video_profile": "超清"
        },
        "hd3": {
            "container": "flv",
            "pieces": [
                {
                    "fileid": "030080010058B6923FB4BD2BF36792819C526D-1881-3992-8F8B-3A3E15C1F8BD",
                    "segs": [
                        {
                            "fileid": "030080010058B6923FB4BD2BF36792819C526D-1881-3992-8F8B-3A3E15C1F8BD",
                            "key": -1,
                            "size": "55416732",
                            "total_milliseconds_audio": "141967",
                            "total_milliseconds_video": "141680"
                        }
                    ]
                }
            ],
            "size": 55416732,
            "src": [],
            "video_profile": "1080P"
        },
        "mp4": {
            "container": "mp4",
            "pieces": [
                {
                    "fileid": "030008010058B69072B4BD2BF36792819C526D-1881-3992-8F8B-3A3E15C1F8BD",
                    "segs": [
                        {
                            "fileid": "030008010058B69072B4BD2BF36792819C526D-1881-3992-8F8B-3A3E15C1F8BD",
                            "key": -1,
                            "size": "15244283",
                            "total_milliseconds_audio": "142013",
                            "total_milliseconds_video": "141680"
                        }
                    ]
                }
            ],
            "size": 15244283,
            "video_profile": "高清"
        }
    },
    "title": "梁文道谈宁波老虎伤人致死事件",
    "url": "http://v.youku.com/v_show/id_XMjU1MTg0MzUwNA==.html?from=zpdvip.001"
}

**Comment by scegg** [comment]
--debug provides nothing more.

**Comment by luhy118** [comment]
@scegg youget不支持会员视频资源，会员的请自已解决了
