### ISSUE TITLE
ImportError: No module named 'you_get.__main__'

### ISSUE THREAD

**Issue by amitbha** [soimort/you-get#1730]
you-get 运行失败。
环境：Ubuntu-gnome 16.10 x64，Python 3.5.2

$ sudo -H pip3 install you-get 
Collecting you-get
  Downloading you_get-0.4.652-py3-none-any.whl (163kB)
Installing collected packages: you-get
Successfully installed you-get-0.4.652

$ you-get -v
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 7, in <module>
    from you_get.__main__ import main
ImportError: No module named 'you_get.__main__'

**Comment by rosynirvana** [comment]
看包的位置在不在sys.path里
```
$python3 -c 'import sys; print(sys.path)'
```

另外注意权限，you-get安装的位置普通用户能不能读

**Comment by amitbha** [comment]
@rosynirvana 多谢！应该是权限问题，安装文件夹的执行权限没有。
估计是root的umask被搞坏了，执行结果是0027。不知哪里能恢复到默认？

**Comment by rosynirvana** [comment]
先看看sudoer里的umask策略是不是错了，再看root的.bashrc之类的文件
[参考](http://unix.stackexchange.com/questions/83056/setting-umask-for-su-root)
