### ISSUE TITLE
[Feature] Batch Download From Text File

### ISSUE THREAD

**Issue by dkl3** [soimort/you-get#1731]
Hi, is it possible to batch-download from a text file? I want to batch-download some v.qq.com videos, which cannot be downloaded with youtube-dl. If it's not possible, then can someone add this for a feature?

Thanks

**Comment by mengmo** [comment]
@@dkl3
写个批处理或者脚本不就行了

**Comment by rosynirvana** [comment]
```
you-get [url_1] [url_2] [url_3] .....
````

**Comment by ad52825196** [comment]
You can try my wrapper as well if you have Java installed: https://github.com/ad52825196/you-get-wrapper

**Comment by dkl3** [comment]
Also, from experience, when I downloaded this v.qq.com channel, I had to manually rename some files because they had duplicate filenames.

ad52825196, does your wrapper auto-rename?

**Comment by ad52825196** [comment]
I have not tried v.qq.com but you-get by default should use the video title as the filename. I think this is the duty of the engine not the wrapper.

**Comment by dkl3** [comment]
Yeah, well manually renaming files with duplicate titles can get inconvenient. It would be nice if it were (2), (3), etc.

**Comment by dkl3** [comment]
Also, this thing is confusing me--I don't know how to set this up or anything--the you-get wrapper.

**Comment by lamlam123tld3** [comment]
cli may have it limit on the length of single command
also import the links through the text file can ignore the annoying "" signs

**Comment by rosynirvana** [comment]
#1736 won't allow using -l flag (playlist) with --input-file flag. It's possible but could lead to a chaos in understanding.
possiblity
* -l flag has nothing to do with the urls from the input-file which are always treat as non-playlist
* -l flag will treat all urls from the input-file as playlist
* input-file has a little grammar to distinguish between playlist and non-playlist but this implies more typing so it won't make your life easier
* input-file has a little grammar but urls comes from command line do not and it's just absurd. So someone could believe -l flag override the playlist /non-playlist information from the input-file

---

#1736禁止混用-l (指定输入是一个播放列表) 和-I --input-file，因为可能导致理解上的混乱，有下面这些可能

* -l不会影响从input-file中读取的url，这些url总是非播放列表
* 如果有-l，从input-file中读取的所有url都被视为播放列表
* 给input-file设计一个微型的语法，让input-file中能标记是不是播放列表
* 但是有人会觉得，input-file可以区分，但是命令行上读取的都受到-l影响，这岂不是很奇怪，所以可能会认为-l是大开关，可以把input-file中指定的信息覆盖掉

**Comment by dkl3** [comment]
rosynirvana, can you please provide the files for your version that supports text-file download? Thanks

**Comment by rosynirvana** [comment]
[github raw](https://raw.githubusercontent.com/rosynirvana/you-get/gnu_getopt/src/you_get/common.py)

or you can clone the gnu_getopt branch

**Comment by dkl3** [comment]
Thank you--much appreciated.
