### ISSUE TITLE
[error] oops, something went wrong with youtube

### ISSUE THREAD

**Issue by CarlCCF** [soimort/you-get#1737]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get --debug https://www.youtube.com/watch?v=fczH85-0BDk
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=fczH85-0BDk
[DEBUG] get_content: https://www.youtube.com/watch?v=fczH85-0BDk
[DEBUG] get_content: https:/yts/jsbin/player-zh_HK-vflQC4kUL/base.js
you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=fczH85-0BDk']
Traceback (most recent call last):
  File "src\you_get\extractors\youtube.py", line 263, in prepare
KeyError: 'dashmpd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1410, in main
  File "src\you_get\common.py", line 1323, in script_main
  File "src\you_get\common.py", line 1139, in download_main
  File "src\you_get\common.py", line 1403, in any_download
  File "src\you_get\extractor.py", line 41, in download_by_url
  File "src\you_get\extractors\youtube.py", line 326, in prepare
  File "src\you_get\common.py", line 322, in get_content
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 463, in open
  File "urllib\request.py", line 1163, in do_request_
urllib.error.URLError: <urlopen error no host given>
you-get returned -1
]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by Paulswith** [comment]
I have a same issue in mac 10.12.3.
This my full link:
you-get https://www.youtube.com/embed/KYiZmTThgeo\?list\=PLO5e_-yXpYLBO6ZaDgV7YH4drssQCSw5n

none any prompt,  and after will prompt time out.

I try to use  other link both they spider from youtube. Amazing ! It can working,During i contrast they, this issue link has '_' in the url.  So i get rid of '_' ， it can working too. 

look：
you-get https://www.youtube.com/embed/KYiZmTThgeo\?list\=PLO5e-yXpYLBO6ZaDgV7YH4drssQCSw5n -O 13 抓取过程中的常见问题1—代理ip的使用
site:                YouTube
title:               Python网络爬虫实战 Scrapy Python网络爬虫实战 Scrapy 13 抓取过程中的常见问题1—代理ip的使用 mp4
stream:
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          37.0 MiB (38767581 bytes)
    # download-with: you-get --itag=22 [URL]

Downloading Python网络爬虫实战 Scrapy Python网络爬虫实战 Scrapy 13 抓取过程中的常见问题1—代理ip的使用 mp4.mp4 ...
 100% ( 37.0/ 37.0MB) ├██████████████████████████████████████████████████┤[1/1]  198 kB/s



Hope can't help yous,who meet with same issue like me /smile   -it's a funny issue
