### ISSUE TITLE
douyu TV  ！！！

### ISSUE THREAD

**Issue by lbcake** [soimort/you-get#1751]
I have installed you-get and the vision is up-to-date,but can't download through you-get. Please help me.

![default](https://cloud.githubusercontent.com/assets/26319880/23784991/367253b6-05a0-11e7-9f7e-90ec550c2ec3.png)

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

求解决。

**Comment by rosynirvana** [comment]
outdated
