### ISSUE TITLE
【新富媒体网站】申请添加对全民K歌的支持

### ISSUE THREAD

**Issue by 872517414** [soimort/you-get#1754]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get -di https://kg.qq.com/node/play?s=qqJuE9qtVcPPSqqL
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://kg.qq.com/node/play?s=qqJuE9qtVcPPSqqL']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1407, in main
  File "src\you_get\common.py", line 1320, in script_main
  File "src\you_get\common.py", line 1136, in download_main
  File "src\you_get\common.py", line 1400, in any_download
  File "src\you_get\extractors\qq.py", line 111, in qq_download
  File "src\you_get\extractors\qq.py", line 10, in qq_download_by_vid
TypeError: Can't convert 'NoneType' object to str implicitly
you-get returned -1
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> 全民K歌除了 kg.qq.com 还有 kg2.qq.com，用于(私密)分享的歌曲，但没有任何限制，通过链接即可访问：http://kg2.qq.com/share.html?s=qqJuE9qtVgx1IqzS
> :icecream:!

**Comment by rosynirvana** [comment]
close via #1755
