### ISSUE TITLE
使用-p时如何给播放器加参数？

### ISSUE THREAD

**Issue by chaosink** [soimort/you-get#1759]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```

```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 使用-p时如何给播放器加参数？我就想问这个。。。

> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
```
you-get -p 'player flag1 flag2' url
```

**Comment by chaosink** [comment]
原来是这样啊！

是我太蠢了还是应该在`GETTING STARTED`里加一个例子。

:ice_cream:

**Comment by lki2019** [comment]
可以关闭了
