### ISSUE TITLE
请问能否将socks5（shadowsocks）代理加入到

### ISSUE THREAD

**Issue by konvict** [soimort/you-get#1762]
Windows10 ,X64. 下载的是最新的7z包。当用socks代理代理时，提示 ```you-get: Error importing PySocks library, socks proxy ignored.In order to use use socks proxy, please install PySocks.``` 。 请问能否将PySocks加入到7z版的依赖当中?

**Comment by qwIvan** [comment]
PySocks只能作为可选依赖，请自行安装

**Comment by dshame** [comment]
pysocks 这个依赖安装完后并不能调用，
Ubuntu16.10 
通过Pip安装。
