### ISSUE TITLE
爱奇艺的一个视频解析失败（A Video of IQIYI Parsed Failed）

### ISSUE THREAD

**Issue by fogmoon** [soimort/you-get#1765]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get -u --debug http://www.iqiyi.com/v_19rrifue7z.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/164881900/664d106e869f4a12b167bdf44f1e06ac/?t=1489402614648&sc=ccb96a6d9b96fe48c9c2d00e2dd3bdf7&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrifue7z.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/iqiyi.py", line 140, in prepare
    assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video
```

> Just come into this video by chance which can not be parsed correctly.
> Thanks so much for your effort to make life more easier. :+1::+1::+1::beer::beer::beer:

**Comment by rosynirvana** [comment]
#1614 #1538 
有些爱奇艺的视频用现在这个接口不行

**Comment by fogmoon** [comment]
@rosynirvana 
Thanks for your information.

:wink:
Maybe adding a collection of iqiyi videos which have not been supported in wiki or other place is good for your team to fix this issue. Also for other not totally supported video site.

**Comment by rosynirvana** [comment]
爱奇艺的情况和网易云音乐差不多，有几个不同的接口，现在使用的接口都不是PC浏览器的接口，所以会碰到有些在浏览器里可以播放，但是用you-get拿不到信息。

至于哪些内容是PC上能播但是现在用的接口拿不到的，就不知道了。

**Comment by fogmoon** [comment]
@rosynirvana 
That is why I give my suggestion: add the collection, updated by the user.

Just suggestion, thanks anyway.

**Comment by rosynirvana** [comment]
#1861
