### ISSUE TITLE
[youku]http://play.youku.com/play/get.json返回结果延迟很严重啊

### ISSUE THREAD

**Issue by univert** [soimort/you-get#1780]
一般要等15-20秒才有response返回，有这样的问题么?

**Comment by univert** [comment]
这可能是因为在youku.py里面访问了两次play.youku.com, 一次是api_url，一次api12_url，这个其实没有必要啊。

**Comment by A-Circle-Zhang** [comment]
现在已经全部迁移到阿里云的服务器了，更新为 play-ali.youku.com 吧

**Comment by univert** [comment]
play-ali.youku.com  不work啊
