### ISSUE TITLE
在python中使用os.system调用you-get的速度很慢，有什么其他调用api吗？

### ISSUE THREAD

**Issue by ccxx2c2** [soimort/you-get#1781]
python3.5.2.

```
import threading,os
from time import sleep
def sleeping():
    for i in range(10):
        print(i)
        sleep(i)
    print('thread end')

t=threading.Thread(target=sleeping, name='aThread')
t.start()
os.system('you-get -h')        
t.join()
```
= =小白只会用 os.system('you-get xxxxx')  这种方式调用you-get，但是在多线程下实在是太……慢了。
上面的示例在本机上跑到6（1+..+6=21秒）的时候才能调用出来，如果解析地址的话，几乎只有等到其他线程执行完毕后才能轮到它运行。（大概是因为其他线程占用了you-get的资源。。？）

不知道有什么方便的API，能拥有如同分别开两个窗口般的速度运行you-get？或者使用多进程/使用pywin32执行……？
看到了讨论区的https://github.com/soimort/you-get/issues/851 但是这里似乎没找到封装好的main()。。
谢谢各位了（鞠躬
感谢作者。

**Comment by cnbeining** [comment]
这些API暂时不存在。

2017年3月19日 上午11:16，"ccxx2c2" <notifications@github.com>写道：

**Comment by mozbugbox** [comment]
可能是 windows `os.system` 太慢，用 `subprocess.call` 看看。尽量不要使用 shell ，直接调用。

`os.system` 在 windows 下要调用 `cmd.exe`，可能会拖慢速度

**Comment by rosynirvana** [comment]
common.py里那些入口选一个就行了，比如script_main

**Comment by lzy0699** [comment]
```
import sys
from you_get import common as you_get
sys.argv=['you-get','-h']
you_get.main()
```
我是这样使用的

**Comment by ccxx2c2** [comment]
多谢楼上各位~
