### ISSUE TITLE
优酷如何选择清晰度下载

### ISSUE THREAD

**Issue by omaidb** [soimort/you-get#1783]
下载youku的时候，默认是1080p的版本，我想下载标清版本，如何操作呢，
另外，有没有you-get的电报群啊。可以即时的在群里询问，会比较方便一点吧

**Comment by lzy0699** [comment]
首页，README.md

**Comment by batjoker** [comment]
加 -i 选清晰度

**Comment by omaidb** [comment]
嗯，我已经掌握了
batjoker <notifications@github.com>于2017年3月22日 周三20:25写道：
