### ISSUE TITLE
B站视频下载每次只能下载5M, ctrl-c之后再次下载，

### ISSUE THREAD

**Issue by weinix** [soimort/you-get#1784]
B站视频下载每次只能下载5M, ctrl-c之后再次下载，又让下载5M. 是怎么回事？

**Comment by weiwangblog** [comment]
Sorry about that.
Here is the sample output while I try to download a video from bilibili:
```
$ you-get -d  http://www.bilibili.com/video/av3020289/index_3.html
[DEBUG] get_content: http://www.bilibili.com/video/av3020289/index_3.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=4736800&from=miniplay&player=1&sign=643e54d086daa902537a0195114e16a7
Site:       bilibili.com
Title:      Insanity Max 30 疯狂极限体能训练(3)-3、α2.4' Tabata Strength
Type:       Flash video (video/x-flv)
Size:       394.79 MiB (413968948 Bytes)

Downloading Insanity Max 30 疯狂极限体能训练(3)-3、α2.4' Tabata Strength.flv ...
 1.3% (  5.0/394.8MB) ├██───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤[1/1]   14 MB/s

```
Each attempt stops after after 5MB.

Thanks for your work.

**Comment by g-plane** [comment]
我这里似乎有类似的情况，就是下载整个视频中的一小段后速度就掉到几十KB每秒，然后我也是按 Ctrl+C 继续下载

**Comment by g-plane** [comment]
感觉B站现在播放视频时不会一次性全部加载，而是播放一段然后加载一段。

**Comment by rosynirvana** [comment]
就是CDN的限速，一开始n MiB速度快，后面会限制到50KiBps甚至1KiBps

**Comment by g-plane** [comment]
应该不是CDN限速，而是API的原因。现在B站视频好像分段加载了。
![sp20170322_185243](https://cloud.githubusercontent.com/assets/17216317/24194577/8cae5e7e-0f31-11e7-8326-9856d739496e.png)

这个视频的长度是23分55秒，从 Chrome 的调试工具可以看出，XHR 中与加载视频有关的 JSON 信息中，有一个包含4个元素的数组（图中圈住的），而每个元素中存在视频链接（箭头所指）。

**Comment by rosynirvana** [comment]
bilibili从建站以来就有分段的视频，当年视频网站都是6分钟一段，不分段是前几年才有的。

**Comment by weiwangblog** [comment]
我目前用screen来解决，循环下载同一个东西，然后循环每20秒发一个ctrl-c给screen session

**Comment by zhangn1985** [comment]
you-get -t 20 就可以同样。。

**Comment by g-plane** [comment]
@rosynirvana 恕我无知，以前是怎样的我并不清楚。
但是这4个URL是不同的，而且下载回来这4个视频都不一样，但正好是原视频的4个部分。
![image](https://cloud.githubusercontent.com/assets/17216317/24201642/a3a9858a-0f4b-11e7-877e-9e90eb4fe717.png)

**Comment by rosynirvana** [comment]
我看错了，durl中每项的url和backup_url是同样的东西，durl有四项说明视频是四段。

flv大多数都是分段的，如果不是全都是。
一个文件的大多是mp4或hdmp4。

**Comment by weiwangblog** [comment]
试了一下 -t 项，等了3分钟还是没有动静，就算了

**Comment by rosynirvana** [comment]
-t是socket timeout，要若干秒内在socket层上超时才行，和每20秒发送一个SIGTERM的语义不同。

**Comment by weiwangblog** [comment]
谢谢回复。。
貌似有的视频有这个问题，有些没有。我下载到第5集才发现，现在不需要发ctrl-c了。
很喜欢这个工具，非常感谢！

**Comment by cnbeining** [comment]
请发一点API的详细返回以及运营商信息 我去骂骂直传的人。

**Comment by weiwangblog** [comment]
没有额外返回信息，就是下载会卡在5M times n(n=1,2,3...)处不动。这个bilibili的
you-get http://www.bilibili.com/video/av3020289

**Comment by g-plane** [comment]
有些第三方的解析网站可以解析出不分段的MP4格式

**Comment by cnbeining** [comment]
@g-plane 我故意不使用那个MP4 因为清晰度不够。

**Comment by rosynirvana** [comment]
api的返回信息看不出什么，就是限速更狠了。

和视频本身的分片没关系。

**Comment by weiwangblog** [comment]
问题在后面一集又开始了，我又开始发从ctrl-c 
还好还好，好过所有其他工具了：）


```
Downloading Insanity Max 30 疯狂极限体能训练-6、α5 Friday Fight Round 1.flv ...
11.4% ( 45.0/394.7MB) ├████████─────────────────────────────────────────────────────────┤[1/1]   14 MB/s
```

**Comment by lamlam123tld3** [comment]
have you test the downloading speed using different cookies from different level of users

**Comment by rosynirvana** [comment]
For any one who would like to bypass this 2 phase downloading speed limit: [gist](https://gist.github.com/rosynirvana/b7c61af2682459c0193f776e81b7f8d9)

The code is in public domain.

More test cases and bug reports are welcome.

**Comment by A-Circle-Zhang** [comment]
问题存在与 platform=pc 且不带 Referer 头的请求中。
两个随便修改一个即可解决问题。

**Comment by CyCle1024** [comment]
不知道是否有人和我同样的经历，每天下载b站的第一个视频速度极快，接着下载都会5M一卡，会是请求里header的问题吗？

**Comment by weinix** [comment]
Thanks again! The fix works very well!

**Comment by rosynirvana** [comment]
@weinix @cnbeining  @soimort 是不是应该把标题改成“bili限速讨论” ？

确认了一点，url中含有的```&rate=1350```不是有些人理解的限速标识
例如[这个]('http://ws.acgvideo.com/c/50/15762134-1.flv?wsTime=1491128057&platform=pc&wsSecret2=d99a08729cd02cacd410e00ac02b3cf2&oi=3060947670&rate=1350') ，很明显会两段限速。

另外也能确认，和header的cookies & referer应该没有关系，因为在浏览器播放也有明显的两段限速。

上面贴在gist的Script的处理方法还是可以的， log：
```
python3 bilibili.py 'http://ws.acgvideo.com/c/50/15762134-1.flv?wsTime=1491128057&platform=pc&wsSecret2=d99a08729cd02cacd410e00ac02b3cf2&oi=3060947670&rate=1350'
10233.553865120019 KiB/s  0.00%
10045.283162199697 KiB/s  9.67%
8862.334391731782 KiB/s  19.33%
10163.024425518543 KiB/s  29.00%
10001.153333867353 KiB/s  38.67%
10291.828384192206 KiB/s  48.34%
9932.567404372583 KiB/s  58.00%
10344.502983189514 KiB/s  67.67%
9872.584752015793 KiB/s  77.34%
10241.636003523436 KiB/s  87.01%
8754.383338487038 KiB/s  96.67%
```

**Comment by A-Circle-Zhang** [comment]
![查看图片](https://cloud.githubusercontent.com/assets/11173242/24585092/92b39fec-17b4-11e7-81f2-2ca47f4e6840.png)

@rosynirvana 
“问题存在与 platform=pc 且不带 Referer 头的请求中。
两个随便修改一个即可解决问题。”

浏览器直接打开正好满足 “platform=pc 且不带 Referer 头” 条件哦。

**Comment by rosynirvana** [comment]
浏览器不带referer头？

**Comment by A-Circle-Zhang** [comment]
@rosynirvana 你这个限速的原因是你使用的机房 IP（108.61.160.202，Vultr 的 VPS）已经被 B 站封了，你可以看到后面 &rate=5
rate=xxx 和这个主题讨论的 5M 后限速，是两种不同的机制，都会起作用。

downgrade 情况下你不会看到头信息中有 Referer。

**Comment by rosynirvana** [comment]
这是几件不同的事情

1. 浏览器若非downgrade，永远有referer。所以，一般的浏览器打开，不是“platform=pc且不带referer头”。遇到浏览器限速的是上面贴的第一个url，加的限速是&rate=1350。

2. bilibili cdn现在的两段限速，如果是ws.acgvideo.com ，不限速长度是5MiB，如果不是ws，不限速长度是10MiB。&rate作用于第二段，如果referer中不含bilibili，就会限制到 1KiBps (ws) 或50KiBps (非ws)

3. 问题是，偶发的浏览器遇到限速，是downgrade丢了referer还是cdn实现有问题。上面那个挂代理是因为当时静态资源加载不出来。

4. &dynamic指什么

**Comment by A-Circle-Zhang** [comment]
@rosynirvana 
可能我对你的“浏览器播放”有误解，我以为你说的是浏览器直接打开。
如果你指的“浏览器播放”是 B 站播放器直接播放，你浏览器播放限速原因是代理机房 IP 被封（很明显的 rate=5）。

**不管是 B 站官方的 Flash 播放器还是 HTML5 播放器都不存在协议降级！**
Flash 播放器：播放页、swf 和视频资源都是 HTTP。
HTML5 播放器：swf、视频资源都是 HTTPS，播放页是 HTTP，但是播放的 iframe 是 HTTPS，这就和播放页本身没关系了。

所以官方播放器不可能出现协议降级丢 Referer。

实测就是 platform=pc 的情况下，如果不带 Referer，就会 5M 后限速，带上**任意** Referer 都不会有限制。platform=其它 的情况下没有任何限制，**反驳请解释我发的 curl 截图**。

**Comment by fuzhuo** [comment]
我这边限速是10MB以后就降到很低的速度了，本来在做一个apple tvos的bili三方客户端，发现每次快进一点又能下10MB下来。

有可能是现在这个appkey和secret被限速了，加上Referer也没用，platform改成iphone或android也没有效果速度依然很慢。

另外一个key bilihelper得到的下载链接也一样，下载10MB就动不了了。但从ios和android官方app得到的链接完全没问题，appkey不一样但不知道secret是什么，反编译后只得到了非视频链接api的secret，视频链接的appkey还是单独的
http://interface.bilibili.com/playurl?platform=bilihelper&otype=json&appkey=95acd7f6cc3392f3&cid=9454413&quality=4&type=mp4

**Comment by rosynirvana** [comment]
@fuzhuo ws.acgvideo.com ，下10MiB，记住位置，重连；非ws，下5MiB，重连。

**Comment by e788b1** [comment]
开两个终端
```bash
while :; do you-get http://www.bilibili.com/video/av9620048 ; done
```
```bash
while :; do pkill -ef you-get ; sleep 20 ; done
```
下载完 ctrl+c
[doge]

**Comment by zpfsqzyl** [comment]
@e788b1 还是你这个办法好，虽然在win10的bash下会导致蓝屏。。。

**Comment by cnbeining** [comment]
这个问题我在沟通 但是效果不佳。

恐怕需要等一段时间了。

封杀是不可能的。

2017年4月17日 上午8:23，"zpfsqzyl" <notifications@github.com>写道：

**Comment by zpfsqzyl** [comment]
@cnbeining 纳尼。哔哩哔哩官方不主动封这种下载器？

**Comment by rosynirvana** [comment]
现在5MiB以后重连应该是最简单可行的策略
上面贴的gist实现了，用you-get输出url就能用
而且大概还可以用aria2c

**Comment by cnbeining** [comment]
都是一个圈子的 抬头不见低头见 真封了多尴尬。

虽然我觉得这玩意没意思。

**Comment by A-Circle-Zhang** [comment]
明明加个 Referer 头就能解决的问题，为什么你们各种方法都出来了...

**Comment by fuzhuo** [comment]
@rosynirvana 我是在写三方播放，解析出地址用来播放不是下载的，所以定时杀掉重来不现实额。不过强制跳进度时可以续命，只是体验就很差了…还是研究下新appkey或者带cookie之类的

**Comment by rosynirvana** [comment]
@fuzhuo 不是杀掉进程啊，是重新发一个Range header过去……

**Comment by zpfsqzyl** [comment]
@rosynirvana 请问用aria2，wget都出现403forbidden，而用迅雷却可以顺畅满速下载，可能是什么原因?

**Comment by rosynirvana** [comment]
@zpfsqzyl 
迅雷能满速 -> 迅雷不一定是从原始链接( bilibili cdn )下载的，可以从它自己的p2p网络或者cdn网络下载
403就不知道了，没见过bili的CDN403的，或许你遇到的不是acgvideo.com的？

**Comment by airdge** [comment]
@zpfsqzyl   == 链接限制ip访问 超过3个就失效了

**Comment by hu6360567** [comment]
我使用当前master下的extractors替换安装到lib下的文件，抓取到的url包含rate=1350或者rate=1280，但是仍然限速。

**Comment by rosynirvana** [comment]
more test:
```&hfa``` param
```
curl 'http://cn-hnjz-cu-v-03.acgvideo.com/vg5/c/f0/1176840-1.flv?expires=1494324300&platform=ios&ssig=0Z6MKZ9u57SSRk58-iQTpQ&oi=_&nfa=wlDtxXsviDxlwyuMdpT/gg==&dynamic=1&hfa=2065845841' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 79.0M  100 79.0M    0     0   225k      0  0:05:58  0:05:58 --:--:--  317k
```

```
curl 'http://cn-hnjz-cu-v-03.acgvideo.com/vg5/c/f0/1176840-1.flv?expires=1494326100&platform=ios&ssig=j9v3xXl3JJa4-0mpnSpzIQ&oi=_&nfa=ZNWJ/zcjVOYxD3Kxr8oFCA==&dynamic=1' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 79.0M  100 79.0M    0     0   540k      0  0:02:29  0:02:29 --:--:--  655k
```

**Comment by uimeet** [comment]
反正我是用Range头解决的~

**Comment by rosynirvana** [comment]
test case:
what if a lua key, platform is ios, otype is default(xml), without hfa?
```
curl "http://cn-hnjz-cu-v-03.acgvideo.com/vg5/c/f0/1176840-1.flv?expires=1494327900&platform=ios&ssig=OauRl1v7JZoHb173c-IEUw&oi=_&nfa=ZNWJ/zcjVOYxD3Kxr8oFCA==&dynamic=1" > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 79.0M  100 79.0M    0     0   510k      0  0:02:38  0:02:38 --:--:--  520k```

**Comment by rosynirvana** [comment]
test case:
miniloader key，platform is default(pc), otype is default(xml), with hfa
with referer:
```
curl 'http://cn-sdjn-cu-v-03.acgvideo.com/vg3/6/18/1176840-1.flv?expires=1494327300&platform=pc&ssig=PMsiT6ks8Mp2dnuq82geNg&oi=_&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1&hfa=2065847557' -H 'referer: bilibili.com' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 79.0M  100 79.0M    0     0   945k      0  0:01:25  0:01:25 --:--:-- 1484k
```
without referer
```
curl 'http://cn-sdjn-cu-v-03.acgvideo.com/vg3/6/18/1176840-1.flv?expires=1494327300&platform=pc&ssig=PMsiT6ks8Mp2dnuq82geNg&oi=_&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1&hfa=2065847557' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 79.0M  100 79.0M    0     0  56889      0  0:24:17  0:24:17 --:--:--  8120
```

miniloader key, platform is default(pc), otype is default(xml), without hfa:
```
curl 'http://cn-hnjz-cu-v-03.acgvideo.com/vg5/c/f0/1176840-1.flv?expires=1494330600&platform=pc&ssig=9KCHS5SP7KfA0d-UnMrNRQ&oi=_&nfa=JegTJDC+uC6hmp9MGMEVog==&dynamic=1' -H 'referer: bilibili.com' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 79.0M  100 79.0M    0     0   863k      0  0:01:33  0:01:33 --:--:-- 1194k
```
