### ISSUE TITLE
!!!solution!!! of weibo.com/tv/* video download without login 

### ISSUE THREAD

**Issue by demostars** [soimort/you-get#1789]
I know the **solution** to solve the problem, but i tryed, it does not working, but!!! it must be my mistake, the solution is ok! Please fix it!

## here is exactly where to fix it and almost the right code to fix it!

change from here, it is no longer http://video.weibo.com/ but http://weibo.com/tv/v/*
![2017-03-25_223529](https://cloud.githubusercontent.com/assets/20697190/24323111/e5f82dee-11ab-11e7-83d0-5f8ab2f75ccc.png)

and the video url is here ( need to decode and regex)
![2017-03-25_223327](https://cloud.githubusercontent.com/assets/20697190/24323125/0f807194-11ac-11e7-9448-e8694e9824eb.png)

the title changed as well
![2017-03-25_224205](https://cloud.githubusercontent.com/assets/20697190/24323146/50a2214a-11ac-11e7-90a4-ea41f4adec67.png)

https://github.com/soimort/you-get/blob/0984190f93bd0b5c55748c41ca657d1ba6bf5a6b/src/you_get/extractors/miaopai.py#L8

so url should be changed, as well as the content regex
https://github.com/soimort/you-get/blob/0984190f93bd0b5c55748c41ca657d1ba6bf5a6b/src/you_get/extractors/miaopai.py#L22

i try to fix it myself but failed

some key code is here. i guess it may caused by my regex.
```
url = match1(a, r'video_src="(.*?)\"&playerType')

title = match1(b, r'<div class="info_txt W_f14">"([\s\S]*?)\"\W')

if re.match(r'http://weibo.com/tv/v/(\w*)\?fid=(\d{4}:\w{32})\w*', url):
        miaopai_download_by_url(url, output_dir, merge, info_only)
```

**Comment by rosynirvana** [comment]
You-get access weibo.com/tv pages with a ua of mobile devices so the html is different from what you can get with non-mobile browser.

#1775 may work for you.

**Comment by demostars** [comment]
@rosynirvana actually i have tried to open the webpage with mobile UA, the html is the same

well just the same URL . 

while open the video.weibo.com/ with mibile UA may redirect to m.miaopai.com/ , this is not under my consideration.
