### ISSUE TITLE
How to get output filename while import you-get as a moudle in python code？

### ISSUE THREAD

**Issue by demostars** [soimort/you-get#1793]
I hava try some ways to get the output filename,

`from you_get import common as you_get`

but the common.get_output_filename needs more the just url,

alos i can not get the consle print through subprocess, since i use the reply of @lzy0699  at #1781

-- json seems has no output .json file? -u can not get content as well.

please tell me is there any other way i did not know?

Alse,
`sys.argv=['you-get', '-o', './download',url]`
`you_get.main()` 

works great.

But
`sys.argv=['you-get','-x', '127.0.0.1:4411', '-o', './download',url]`
`you_get.main()` 

does not work!

i know i must be my problem since i do not know python that well

So,where is my problem? Any advise?

**Comment by rosynirvana** [comment]
what does
> does not work!
implies?

Code crashes? or which flag does not work?

**Comment by demostars** [comment]
@rosynirvana 
Sorry for not giving the error.

SO SORRY,

After carefully debug,i find it is my url wrong! Since i use bottle as server, the youtube url turns into 'https://www.youtube.com/watch' string after '?' are gone, that is where problem is, but i still can not fix it. i mean, with bottle,can i get full url with '?',my code now is

`@route('/YouGet/<url:re:.+>', method=['GET']) `

any advice?

SO SORRY, MY BAD!

Problem 2 solved, Still , Problem 1 unsolved~

**Comment by lzy0699** [comment]
show your code.

**Comment by demostars** [comment]
@lzy0699 


``` python

import os
import time
from bottle import * 
from you_get import common as you_get

@route('/favicon.ico')
def favicon():
    return static_file('favicon.ico', root='./')
@route('/YouGet/<url:re:.+>', method=['GET'])   #定义路由，即浏览器访问的地址
def hello(url):#函数名

    start_time = time.time()
    print(url)
    if 'youtube.com' in url:
        ys.argv=['you-get', '-o', './download','-x','127.0.0.1:4411',url]
    else:
        sys.argv=['you-get', '-o', './download',url]
    you_get.main()
    # 希望这里可以获取文件名返回
    return "下载网址===" + url + "===" + "耗时:" + str(int(time.time()-start_time)) + "秒"   #浏览器返回的内容

```

**Comment by lzy0699** [comment]
```
def hello(url):#函数名
    if request.request.query_string:
        url+='?'+request.query_string
```

**Comment by demostars** [comment]
@lzy0699

Yeah, I have solved this problem nearly the same way.

Thanks.

**Comment by demostars** [comment]
@soimort-bot Hi, any advice about how to get output filename?

**Comment by rosynirvana** [comment]
AFAIK output filenames are decided in the function ```url_save``` (in ```common.py```) and won't be returned to those caller functions. Perhaps you will have to hack in the ```url_save``` or monkey-patching some std library functions, ```open``` for instance.

**Comment by zhangn1985** [comment]
you can try my fork: https://github.com/zhangn1985/ykdl

**Comment by lzy0699** [comment]
如果你一定要获取输出文件名的话，可以参照下面代码：
```
#coding utf-8
import os
from bottle import request,run,route 
from you_get import common as you_get
import re

from io import StringIO
import sys
class Capturing(list):
	def __enter__(self):
		self._stdout = sys.stdout
		sys.stdout = self._stringio = StringIO()
		return self
	def __exit__(self, *args):
		self.extend(self._stringio.getvalue().splitlines())
		del self._stringio	# free up some memory
		sys.stdout = self._stdout


@route('/YouGet/<url:re:.+>', method=['GET'])   #定义路由，即浏览器访问的地址
def hello(url):#函数名
	if request.query_string:
		url+='?'+request.query_string
	#print(url)
	sys.argv=['you-get','-o',r'x:\downloads',url]
	with Capturing() as output:
		you_get.main()
	for i in output:
		m=re.findall(r'Downloading (.+) \.\.\.',i)
		if m:
			filename=m[0]
			break
	# 希望这里可以获取文件名返回
	return filename

run(host='127.0.0.1',port=8080)
```
副作用就是后台不会显示you-get的执行过程。
如果要在后台显示you-get执行过程，可以在下载前先执行一遍 you-get --json url，片段如下：
```
	sys.argv=['you-get','--json',url]
	with Capturing() as output:
		you_get.main()
	text=''
	for i in output:
		text+=i
	info_dict=eval(text)
	title=info_dict['title']
```
得到视频信息的字典，可使用you_get/util/string.py文件中的get_filename(title)函数得到输出文件名(不带扩展名)，扩展名可根据info_dict字典中的视频信息筛选出来默认下载的格式对应的扩展名(这个我没有去研究)，然后两者组合即是完整的输出文件名。

**Comment by demostars** [comment]
@rosynirvana Oops, I am not that PRO enough, but i will study on it! Thanks!

@zhangn1985 Yeah, great job too, I will give it a try.

@lzy0699 嗯，取消救国的好办法~ 谢谢~

我这么做的目的是给you-get 加上一个更方便调用的办法，由于不是很懂，一直都是半摸索半前进。

目前通过命令行的形式，通过一些搜索发现了@mozbugbox 做的非常棒的 webUI 
https://github.com/mozbugbox/you-get/tree/gui-web

因为时隔有点久，修改部分代码仍然可以基本正常运行。从他的代码中，可以学习到如何获取诸如 进度条，文件名等。但是，依然由于我个人水平很菜，不是很理解，所以才自己按照自己的思路，写简单的东西，通过bottle 搭建本地服务监听，实现点击书签直接下载当前网址的视频。当然，除了下载，我后续还有一些想法，所以，需要文件名作为参数，一般只实现下载，这样应该是基本可以的了。

期间我也了解了一下 youtube-dl,  那个项目有较为直接的官方hook例子，所以能够实现获取文件名，但是我感觉使用起来不如you-get好。刚刚了解到yk-dl，一会去了解一下，感谢各位。

同时希望这也能作为一个 pr 提交给各位，当然我自己也会尽力做好，不过代码很丑就不好意思加在原项目中了。

再次感谢各位~
