### ISSUE TITLE
土豆tudou不能使用-p参数在线播放

### ISSUE THREAD

**Issue by liuxb** [soimort/you-get#1802]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.
请使用`--debug`运行，并将输出粘贴在下面:
```
[在这里粘贴完整日志]
```
如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

土豆的视频可以下载，但是不能使用-p参数播放了。
举例you-get.exe -p mpv.exe "http://www.tudou.com/programs/view/W07oSkOp7is"
程序可以得到正确地址比如下面这样的地址，但是不能播放。提示“服务器已关闭或地址错误”。请问是土豆自己的问题，还是you-get的问题。其他站点正常。

http://111.206.132.81/f4v/11/63897611.h264_1_seg_0.0400120B0055397F987691674C3F4C438D9F9E-827E-8BFF-1BB4-000104821806.f4v?key=a813a8624d5a7a168ffb8558da03fd00115d0f8975&qrs=1367658095&p=17892215270972392948&playtype=12&tk=76469978195564963810933260&brt=12&bc=0&xid=0400120B0055397F987691674C3F4C438D9F9E-827E-8BFF-1BB4-000104821806&nt=0&nw=1&bs=0&ispid=106&rc=200&inf=12&si=un&npc=4265&pp=0&ul=0&mt=0&sid=0&pc=0&cip=113.200.29.11&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=305034426&fi=0&sz=13568042 
http://111.206.132.74/f4v/11/63897611.h264_1_seg_1.0400120B0155397F98D6B57909298F42A8A503-10B1-F63E-D415-000104821806.f4v?key=8bb1699594a7b684f619dd58da03fe00115d0f8975&qrs=1250217583&p=7289914266768717981&playtype=12&tk=75749424245418239980179952&brt=12&bc=0&xid=0400120B0155397F98D6B57909298F42A8A503-10B1-F63E-D415-000104821806&nt=0&nw=1&bs=0&ispid=106&rc=200&inf=12&si=un&npc=4274&pp=0&ul=0&mt=0&sid=0&pc=0&cip=113.200.29.11&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=305034427&fi=0&sz=14994216 

> [您的内容]
> [舔 :icecream:!]

**Comment by zhangn1985** [comment]
mpv的UA要为空。否则就会出现这个问题

**Comment by liuxb** [comment]
谢谢，you-get好像不能指定播放器的ua。
然后我编辑mpv.conf文件，添加
user-agent=
（UA为空）
或
user-agent=Python-urllib/3.3
（UA为you-get的ua）
但是都不行。
版本0.4.652，ua是Python-urllib/3.3吗？
请帮忙看看谢谢。

**Comment by rosynirvana** [comment]
我这里测试结果是ua为空不行，会403。设定为python的ua能正常工作。

但是有个问题，mpv的依赖库可能会忽略传过去的ua，比如：[issues](https://github.com/mpv-player/mpv/issues/4155)

ua有没有正确传过去好像只能抓包确认了。
基于ffmpeg 3.2.4的mpv builds正常
```
mpv --version
mpv 0.17.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Jun  2 23:09:12 CST 2016
ffmpeg library versions:
   libavutil       55.17.103 (runtime 55.34.101)
   libavcodec      57.24.102 (runtime 57.64.101)
   libavformat     57.25.100 (runtime 57.56.101)
   libswscale      4.0.100 (runtime 4.2.100)
   libavfilter     6.31.100 (runtime 6.65.100)
   libswresample   2.0.101 (runtime 2.3.100)
ffmpeg version: 3.2.4
```

**Comment by rosynirvana** [comment]
另外直接从you-get传ua过去是可能的：
假设py版本号是3.5

```
you-get -p 'mpv --user-agent Python-urllib/3.5' 'http://www.tudou.com/programs/view/W07oSkOp7is'
```

**Comment by liuxb** [comment]
谢谢rosynirvana，问题解决。
