### ISSUE TITLE
stream到mpv看的时候，像youku那种分段的视频，怎么预读啊？

### ISSUE THREAD

**Issue by cottonty** [soimort/you-get#1803]
现在是播完一段卡一下，再播下一段，很痛苦

**Comment by lzy0699** [comment]
在于播放器吧，貌似不能，习惯就好。。。哈哈

**Comment by rosynirvana** [comment]
这是一个关于mpv的问题

**Comment by vyette** [comment]
看一下 mpv 的 [merge-files](https://mpv.io/manual/master/#options-merge-files) 选项。
针对你的问题，可以用 `you-get -p 'mpv --merge-files' URL`。

**Comment by Erk-** [comment]
You should also have the `--no-ytdl` agument on mpv.

**Comment by wnpllrzodiac** [comment]
try ffplay concate？support segment file list play

**Comment by rosynirvana** [comment]
not a you-get issue
