### ISSUE TITLE
Cannot download music video on Youtube

### ISSUE THREAD

**Issue by MuJJus** [soimort/you-get#1804]
the you-get installed from pip3 and latest version

# you-get -V
you-get: version 0.4.652, a tiny downloader that scrapes the web.

It cannot download some music video like this:

# you-get --debug https://www.youtube.com/watch?v=_jGVpKPcAWQ
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=_jGVpKPcAWQ
[DEBUG] get_content: https://www.youtube.com/watch?v=_jGVpKPcAWQ
[DEBUG] get_content: https://www.youtube.com/yts/jsbin/player-en_US-vflwkOLTK/base.js
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=_jGVpKPcAWQ']
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/youtube.py", line 263, in prepare
    dashmpd = ytplayer_config['args']['dashmpd']
KeyError: 'dashmpd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1136, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 41, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/youtube.py", line 336, in prepare
    sig = self.__class__.decipher(self.js, stream['s'])
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/youtube.py", line 56, in decipher
    f1def = match1(js, r'function %s(\(\w+\)\{[^\{]+\})' % re.escape(f1)) or \
  File "/usr/lib/python3.4/re.py", line 253, in escape
    for c in pattern:
TypeError: 'NoneType' object is not iterable

**Comment by rosynirvana** [comment]
also works for me.
It could have something to do with CDN. 

```KeyError: 'dashmpd'``` hints no dash info returned. Current impl doesn't handle it properly enough, like in #1777 .

**Comment by MuJJus** [comment]
this is anti-spider?
```
# curl https://www.youtube.com/get_video_info?video_id=_jGVpKPcAWQ -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H "Accept-Charset: UTF-8,*;q=0.5" -H "Accept-Language: en-US,en;q=0.8" -A "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
errorcode=150&errordetail=0&status=fail&reason=This+video+contains+content+from+linfair_records.+It+is+restricted+from+playback+on+certain+sites+or+applications.%0A%3Ca+href%3D%27http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D_jGVpKPcAWQ%26feature%3Dplayer_embedded%27+target%3D%27_blank%27%3EWatch+on+YouTube%3C%2Fa%3E
```

**Comment by MuJJus** [comment]
change another video is normal
```
# curl https://www.youtube.com/get_video_info?video_id=qbiJkzPV4ms -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H "Accept-Charset: UTF-8,*;q=0.5" -H "Accept-Language: en-US,en;q=0.8" -A "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
pltype=content&ptchn=dp5pYDJCpl5WFk3jFEjWHw&c=WEB&vm=CAEQARgE&ldpj=-9&is_listed=1&iv3_module=1&apiary_host_firstparty=&enablecsi=1&cos=Windows&ti...........
```

**Comment by rosynirvana** [comment]
前面说了，你那里的log出现```dashmpd = ytplayer_config['args']['dashmpd']```说明返回的页面信息里没有dash流，但是另外两个log的结果是有dash的
```
 [ DASH ] ____________________________________
    - itag:          137
      container:     mp4
      quality:       1920x1080
      size:          95.0 MiB (99596566 bytes)
    # download-with: you-get --itag=137 [URL]
```
这可能和CDN有关。
bot用的是develop branch，我测试用的是release，都没遇到反爬虫的结果。

现在的代码处理没有dash不够小心，整个包在一个try except里了，对只有default的处理可能出问题。
处理方法就像#1777 ，在dash的try branch里检测``` ytplayer_config['args']['dashmpd']```，如果没有dashmpd这个key，直接early return用default流。
