### ISSUE TITLE
搜的到，就是下不了 （IQIYI）求助

### ISSUE THREAD

**Issue by XyaoX** [soimort/you-get#1806]
Please make sure these boxes are checked before submitting your issue – thank you!

- [-] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [y Your `you-get` is up-to-date.
- [y] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [y ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [y ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get: vd: 14 is not handled
you-get: info is {'vd': 14, 'vid': 'b2f448d831639e6ac9eb89b24a821230', 'm3utx': 'http://cache.m.iqiyi.com/mus/text/204466001/b2f448d831639e6ac9eb89b24a821230/afbe8fd3d73448c9//20170321/0e/48/369e1557b9704ba065d4ff1cc7f257eb.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=637791200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1490798748813&qypid=637791200_04022000001000000000_14&qd_k=37a7c370217291d00dc20dd4af75b918&qd_ip=199.227.4.67&qd_nsc=8566b60dac3f5913decfddc6572244b2&other=', 'm3u': 'http://cache.m.iqiyi.com/mus/204466001/b2f448d831639e6ac9eb89b24a821230/afbe8fd3d73448c9//20170321/0e/48/369e1557b9704ba065d4ff1cc7f257eb.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=637791200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1490798748813&qypid=637791200_04022000001000000000_14&qd_k=37a7c370217291d00dc20dd4af75b918&qd_ip=199.227.4.67&qd_nsc=8566b60dac3f5913decfddc6572244b2&other='}
site:                爱奇艺 (Iqiyi)
title:               射雕英雄传第43集
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
    # download-with: you-get --format=LD [URL]

```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by mengmo** [comment]
```
you-get -di http://www.iqiyi.com/v_19rrb7uff0.html
[DEBUG] get_html: http://www.iqiyi.com/v_19rrb7uff0.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rrb7uff0.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/637791200/153ea625fcef39e13845c92301f0c745/?t=1490811824387&sc=9b59917c13cb1af663b34b2c65608e29&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: vd: 14 is not handled
you-get: info is {'vd': 14, 'vid': 'b2f448d831639e6ac9eb89b24a821230', 'm3u': 'http://cache.m.iqiyi.com/mus/204466001/b2f448d831639e6ac9eb89b24a821230/afbe8fd3d73448c9//20170321/0e/48/369e1557b9704ba065d4ff1cc7f257eb.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=637791200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1490811827363&qypid=637791200_04022000001000000000_14&qd_k=9b59917c13cb1af663b34b2c65608e29&qd_ip=42.236.224.96&qd_nsc=fd113f859031442219b7cdf46297b568&other=', 'm3utx': 'http://cache.m.iqiyi.com/mus/text/204466001/b2f448d831639e6ac9eb89b24a821230/afbe8fd3d73448c9//20170321/0e/48/369e1557b9704ba065d4ff1cc7f257eb.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=637791200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1490811827363&qypid=637791200_04022000001000000000_14&qd_k=9b59917c13cb1af663b34b2c65608e29&qd_ip=42.236.224.96&qd_nsc=fd113f859031442219b7cdf46297b568&other='}
site:                爱奇艺 (Iqiyi)
title:               射雕英雄传第43集
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
    # download-with: you-get --format=LD [URL]
```
实测下载下来的时长只有`07:11`。看来 iqiyi 也开始在移动端上动手段了

**Comment by rosynirvana** [comment]
vd是流分辨率的id
```vd_2_id = {10: '4k', 19: '4k', 5:'BD', 18: 'BD', 21: 'HD', 2: 'HD', 4: 'TD', 17: 'TD', 96: 'LD', 1: 'SD'}```
```vd: 14 is not handled```是说不知道这是什么分辨率

主要问题是拿到的m3u8是别的东西，不知道是什么的试看片段

**Comment by mengmo** [comment]
当时我另外做了个测试。先用 aria2 把 m3u8 给下载了下来，而后
`aria2c -i 369e1557b9704ba065d4ff1cc7f257eb.m3u8`
500多个 segments 中只有 2个报错，而且速度相当快，随便打开一个都能看，就是文件顺序是个问题。
以上是在联通 50M 的环境下
后来在一个移动 10M 左右的环境下，反复试了几次
`aria2c -c -i 369e1557b9704ba065d4ff1cc7f257eb.m3u8`
一次最多能下载下来 100 多个 segments，往后只能下到大概 10个以下。
当然，也有可能是缓存或者 CDN 的问题

**Comment by mengmo** [comment]
还有，至少当时我拿到的 m3u8 和下载下来的 segments 都是正常的

**Comment by rosynirvana** [comment]
能拿到正确的m3u8其实是可以拿ffmpeg输出的

**Comment by mengmo** [comment]
把 m3u8 下载下来然后喂给 ffmpeg，结果是速度上是没问题了，但是最后得到的视频文件还是一样

大部分的内容是这样的
`[mp4 @ 0000000003413d80] Non-monotonous DTS in output stream 0:1; previous: 15926710, current: 15894513; changing to 15926711. This may result in incorrect timestamps in the output file.`

感觉应该和 m3u8 里的这一行有关
`#EXT-X-DISCONTINUITY`
> 4.3.2.3.  EXT-X-DISCONTINUITY
> https://tools.ietf.org/html/draft-pantos-http-live-streaming-21#section-4.3.2.3

> 6.3.3.  Playing the Media Playlist file
> https://tools.ietf.org/html/draft-pantos-http-live-streaming-21#section-6.3.3
> The client MUST be prepared to reset its parser(s) and decoder(s)
>    before playing a Media Segment that has an EXT-X-DISCONTINUITY tag
>    applied to it, otherwise playback errors can occur.

**Comment by rosynirvana** [comment]
我猜ffmpeg处理HLS实现得没问题，是视频分段的时间戳有错。
把分段视频合并并不是件简单的事情。

出现```Non-monotonous DTS```时候的最好办法是把所有分段重新封装，然后再用concat demuxer合并。但对于m3u8那么多分段处理起来要小心。

**Comment by mengmo** [comment]
刚我仔细看了看，确实所有内容都下载下来了，就是在6分钟左右的位置时间戳出了问题，而这也恰好在第一个`#EXT-X-DISCONTINUITY`之后，最后正常的60多秒片尾离最后一个`#EXT-X-DISCONTINUITY`也挺远的

**Comment by mengmo** [comment]
刚才又试了试44集，结果跟43集基本一致
我感觉这一点儿也不像巧合

**Comment by rosynirvana** [comment]
```#EXT-X-DISCONTINUITY``` 就是所谓“视频分段”了，不同于直觉上的文件分段，从上面的返回信息里也可以看出，两段之间的DTS也就是解码时间戳是有重叠的。

我这里ffmpeg 3.2.4在6分钟附近没有报warning，看来3.2.4能正确处理这个分段。

问题也是有的，1:1的下载速度和比较糟糕的错误回复。看到过有人去ffmpeg项目里提issue，得到的回复是ffmpeg又不是给你们下载用的。

**Comment by mengmo** [comment]
我感觉这和 ffmpeg 之间的关系好像不大，刚又试了一下，确实正常了，但是至少我倒数第二条回复的时候43集拿到的 m3u8 里的视频编码是`HEVC`，刚才却是`AVC`了。而且现在44集还是`HEVC`
当前43集拿到的第一个 segment
`http://data.video.iqiyi.com/videos/v0/20170321/80/89/dad1828e7b4b6634c7bb81496670c3c7.ts?qypid=637791200_04022000001000000000_4&start=0&end=3221101&hsize=43231&tag=0&v=&contentlength=2955924&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1491140190232&qd_ip=&qd_k=51e919fa1b11324c849ea764e6f1ca57&qd_sc=257e31bc348b2d185410969494900ed0`
当前44集拿到的第一个 segment
`http://data.video.iqiyi.com/videos/v0/20170321/b5/11/2ea89046cd177d2fad40bf47c27807e0.265ts?qypid=637796200_04022000001000000000_17&start=0&end=1073480&contentlength=1073480&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1491140557706&qd_ip=&qd_k=d2982b448c0205ba72636bea5311a96c&qd_sc=0678ae3787eba6b25aa70f89f4ac853e`

**Comment by mengmo** [comment]
44集
http://www.iqiyi.com/v_19rrb7uhok.html
问题依旧
```
ffmpeg -version
ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 6.3.0 (GCC)
configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
libavutil      55. 34.101 / 55. 34.101
libavcodec     57. 64.101 / 57. 64.101
libavformat    57. 56.101 / 57. 56.101
libavdevice    57.  1.100 / 57.  1.100
libavfilter     6. 65.100 /  6. 65.100
libswscale      4.  2.100 /  4.  2.100
libswresample   2.  3.100 /  2.  3.100
libpostproc    54.  1.100 / 54.  1.100
```

**Comment by rosynirvana** [comment]
好像还是错误恢复的问题
如果是```grep http foo.m3u8``` 生成的aria2c下载列表，下载的时候要用-j 1
默认的5个worker会被踢掉一些，所以有这些log:
```
 -> [RequestGroup.cc:751] errorCode=1 Download aborted.
  -> [DefaultBtProgressInfoFile.cc:281] errorCode=1 total length mismatch. expected: 983052, actual: 884164
```

或者写一个script扫m3u8文件，用url生成.sh和concat文件，然后运行.sh让aria2逐个下载，再用ffmpeg的concat filter合并。

**Comment by mengmo** [comment]
貌似当前只能如此了，不过这么一来门槛儿就高了不少，直接隔绝了大部分的 Windows 用户，特别是新手。(这儿放什么表情合适呢？)

**Comment by rosynirvana** [comment]
其实不比原来糟糕多少，下载m3u8基本上没法去掉对于独立的ffmpeg的依赖，其他的6分钟一段的视频用播放器直接看也无妨，m3u8里面的分段一个文件可以只有1秒。

感觉现在的处理方向应该是让py处理下载，然后再让ffmpeg合并。合并出来的视频不如ffmpeg直接处理m3u8那么正确，但应该已经达到人分辨不出的程度了。

**Comment by mengmo** [comment]
https://github.com/globocom/m3u8

**Comment by cnbeining** [comment]
See #1838 for M3U.
