### ISSUE TITLE
优酷-p vlc 不能打开vlc

### ISSUE THREAD

**Issue by zqfzera** [soimort/you-get#1814]
you-get -p vlc 'http://v.youku.com/v_show/id_XMjI3NzIwMDA0MA\=\=.html\?spm\=a2hww.20023042.md223500.1\~3\!3\~5\~5\~A\&from\=y1.3-idx-beta-1519-23042.234502-223499-223500.3-1'
![image](https://cloud.githubusercontent.com/assets/22131505/24545452/c362b64a-1639-11e7-9469-c42999cd6bac.png)

**Comment by rosynirvana** [comment]
这和vlc应该没有关系。

跑一遍 ```you-get -di  'http://v.youku.com/v_show/id_XMjI3NzIwMDA0MA\=\=.html\?spm\=a2hww.20023042.md223500.1\~3\!3\~5\~5\~A\&from\=y1.3-idx-beta-1519-23042.234502-223499-223500.3-1'```
看看log是什么
