### ISSUE TITLE
B站视频能否返回hd mp4格式的，目前只有flv

### ISSUE THREAD

**Issue by jianghua** [soimort/you-get#1817]
B站视频能否返回hd mp4格式的，目前只有flv格式的

**Comment by Zhenyu-Yang** [comment]
@jianghua 虽然视频格式是flv的，但是视频编码都是H264的，只需要使用ffmpeg -c copy把视频封装成mp4的扩展名就行，这个过程没有视频转码的操作，所以速度很快，几百兆的视频一两秒就好了，这样转出来的mp4，使用苹果自带的播放器也一样能播了。

**Comment by rosynirvana** [comment]
closed via #1698
