### ISSUE TITLE
i Cant download from iqiyi, QQ & letv

### ISSUE THREAD

**Issue by tmhvnn** [soimort/you-get#1819]
#1 With Letv.
Link: you-get http://www.le.com/ptv/vplay/28383167.html
only download 10 minutes video.
and i used you-get -c cookies.sqlite http://www.le.com/ptv/vplay/28383167.html. But nothing change.

#2 With iQiyi
Link: http://www.iqiyi.com/v_19rrb5mpbs.html
No size extracted.  
D:\>you-get -di http://www.iqiyi.com/v_19rrb5mpbs.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/642297300/ebe3e542e16eed2ce763a9952f55b2b2/?t=1490985040869&sc=2125226d95b46e0d8d58630ba28d59e8&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: vd: 14 is not handled
you-get: info is {'vid': '9ba5ada1b3862779a78b17ea0453d0e6', 'vd': 14, 'm3utx': 'http://cache.m.iqiyi.com/mus/text/206182401/9ba5ada1b3862779a78b17ea0453d0e6/afbe8fd3d73448c9/1023108576/20170329/f0/ae/60641cb7c732e5d6d3a64c64ca309f6d.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=642297300&bossStatus=2&qd_vip=0&px=&qd_src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1490985043343&qypid=642297300_04022000001000000000_14&qd_k=2125226d95b46e0d8d58630ba28d59e8&qd_ip=27.72.57.75&qd_nsc=d4e5e0fd9e2da33a1f3d1ee6550e4795&other=', 'm3u': 'http://cache.m.iqiyi.com/mus/206182401/9ba5ada1b3862779a78b17ea0453d0e6/afbe8fd3d73448c9/1023108576/20170329/f0/ae/60641cb7c732e5d6d3a64c64ca309f6d.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=642297300&bossStatus=2&qd_vip=0&px=&qd_src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1490985043343&qypid=642297300_04022000001000000000_14&qd_k=2125226d95b46e0d8d58630ba28d59e8&qd_ip=27.72.57.75&qd_nsc=d4e5e0fd9e2da33a1f3d1ee6550e4795&other='}
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        BD
      container:     m3u8
      video-profile: 1080p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=BD [URL]

    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=LD [URL]

#3 With Youku
D:\>you-get --debug http://v.youku.com/v_show/id_XMjY1NDkzNzEzMg==.html?spm=a2h0j.8191423.item_XMjY1NDkzNzEzMg==.A
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjY1NDkzNzEzMg==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjY1NDkzNzEzMg==&ct=12
you-get: [Failed] \u670d\u52a1\u5668\u53d1\u751f\u81f4\u547d\u9519\u8bef
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjY1NDkzNzEzMg==.html?spm=a2h0j.8191423.item_XMjY1NDkzNzEzMg==.A']
Traceback (most recent call last):
  File "src\you_get\extractors\youku.py", line 184, in prepare
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1407, in main
  File "src\you_get\common.py", line 1320, in script_main
  File "src\you_get\common.py", line 1136, in download_main
  File "src\you_get\common.py", line 1400, in any_download
  File "src\you_get\extractor.py", line 41, in download_by_url
  File "src\you_get\extractors\youku.py", line 204, in prepare
  File "src\you_get\util\log.py", line 98, in wtf
NameError: name 'exit' is not defined
you-get returned -1

**Comment by rosynirvana** [comment]
1我没法测试

2那个vd 14是个爱奇艺新增的分辨率代号，不知道是什么，只是不会出现在下面的下载项中。m3u(8)不会打印大小，本来已经patch过了，但是iqiyi.py的打印信息函数是自己写的，所以还是打印file size 0MiB。

m3u(8)在metadata里不包含文件大小，只有视频长度。想要获取大小必须遍历所有分段的url，一个分段大概5-10s的长度，那么一集40min的电视剧会有240+的分段。分段的url可能会301/302，必须发送两次HEAD。所以获取一个m3u(8)的实际文件大小需要发送500个左右的http请求，可能会卡很长时间，不值。

另外那个链接在网页端上看起来都是vip视频

3的提示信息'\u670d\u52a1\u5668\u53d1\u751f\u81f4\u547d\u9519\u8bef'，就是服务器发生致命错误，我这里重现不了。

```
ou-get -di 'http://v.youku.com/v_show/id_XMjY1NDkzNzEzMg==.html?spm=a2h0j.8191423.item_XMjY1NDkzNzEzMg==.A'
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjY1NDkzNzEzMg==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjY1NDkzNzEzMg==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049100699258312c67890_00/st/flv/fileid/0300802F0058D169B43013011BA6A9E838A7EF-31FD-3E3B-6DB1-7D727C5DCF0D?K=f96e5a9c77eb32d2261f993b%26sign%3D38731e404aa6ef6145a60ad304da262e&ep=ciadG0mNUMcJ5ybXiz8bNCrlfH4PXP4J9h%2BNgdAUALshQJy%2Bnzejw56wT%2FxCF%2FhrAyR3GZ75qNiWbTViYfNC3xwQ3DurS%2FrmioLi5aonw5IHFRxCAbvXwFSeRjH4&ev=1&ctype=12&yxon=1&oip=2100146498&token=0519
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049100699258312c67890_00/st/flv/fileid/0300802F0158D169B43013011BA6A9E838A7EF-31FD-3E3B-6DB1-7D727C5DCF0D?K=9fec835d9ae5de392412f589%26sign%3D7323e3e767099c44136282304bd8a4c2&ep=ciadG0mNUMcJ5ybXiz8bNCrlfH4PXP4J9h%2BNgdAUALohQJy%2Bnzejw56wT%2FxCF%2FhrAyR3GZ75qNiWbTViYfNC3xwQ3DurS%2FrmioLi5aonw5IHFRxCAbvXwFSeRjH4&ev=1&ctype=12&yxon=1&oip=2100146498&token=0519
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049100699258312c67890_00/st/flv/fileid/0300802F0258D169B43013011BA6A9E838A7EF-31FD-3E3B-6DB1-7D727C5DCF0D?K=141e2fb6749574f52412f589%26sign%3D7da7511e51030c9790af045a95d3fd30&ep=ciadG0mNUMcJ5ybXiz8bNCrlfH4PXP4J9h%2BNgdAUALkhQJy%2Bnzejw56wT%2FxCF%2FhrAyR3GZ75qNiWbTViYfNC3xwQ3DurS%2FrmioLi5aonw5IHFRxCAbvXwFSeRjH4&ev=1&ctype=12&yxon=1&oip=2100146498&token=0519
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049100699258312c67890_00/st/flv/fileid/0300802F0358D169B43013011BA6A9E838A7EF-31FD-3E3B-6DB1-7D727C5DCF0D?K=5a9d317d5ebfee102412f589%26sign%3Dbe074ac63f5a4f6b4ff9051759a58780&ep=ciadG0mNUMcJ5ybXiz8bNCrlfH4PXP4J9h%2BNgdAUALghQJy%2Bnzejw56wT%2FxCF%2FhrAyR3GZ75qNiWbTViYfNC3xwQ3DurS%2FrmioLi5aonw5IHFRxCAbvXwFSeRjH4&ev=1&ctype=12&yxon=1&oip=2100146498&token=0519
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049100699258312c67890_00/st/flv/fileid/0300802F0458D169B43013011BA6A9E838A7EF-31FD-3E3B-6DB1-7D727C5DCF0D?K=b9fe57b8cb074c71282c3cec%26sign%3D032457520d79d2ef6527e27820bc1698&ep=ciadG0mNUMcJ5ybXiz8bNCrlfH4PXP4J9h%2BNgdAUAL8hQJy%2Bnzejw56wT%2FxCF%2FhrAyR3GZ75qNiWbTViYfNC3xwQ3DurS%2FrmioLi5aonw5IHFRxCAbvXwFSeRjH4&ev=1&ctype=12&yxon=1&oip=2100146498&token=0519
site:                优酷 (Youku)
title:               功夫瑜伽
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          1821.1 MiB (1909521322 bytes)
    # download-with: you-get --format=hd3 [URL]

    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          963.8 MiB (1010604156 bytes)
    # download-with: you-get --format=hd2 [URL]

    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          505.3 MiB (529854966 bytes)
    # download-with: you-get --format=mp4 [URL]

    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          252.3 MiB (264598748 bytes)
    # download-with: you-get --format=flvhd [URL]
```

**Comment by tmhvnn** [comment]
for Letv. i can download only 10m of video.
How to export cookies from Firefox and load to you-get? 
Someone said: U must log-in to view/extract private video
