### ISSUE TITLE
DiliDili的解析似乎又挂了

### ISSUE THREAD

**Issue by QShen3** [soimort/you-get#1821]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[DEBUG] get_content: http://www.dilidili.wang/watch3/55800/
[DEBUG] dilidili_download: https://newplayer.jfrft.com/index.php?vid=800262b7da:d955239f11&v=yun&sign=bce74efb76a2b0b6341ca7be47a5b852
[DEBUG] get_content: https://newplayer.jfrft.com/index.php?vid=800262b7da:d955239f11&v=yun&sign=bce74efb76a2b0b6341ca7be47a5b852
[DEBUG] get_content: https://newplayer.jfrft.com/parse.php?xmlurl=null&type=None&vid=None&hd=None&sign=None&tmsign=None&userlink=None
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.dilidili.wang/watch3/55800/']
Traceback (most recent call last):
  File "C:\Users\qazxd\AppData\Local\Programs\Python\Python35\Scripts\you-get-script.py", line 9, in <module>
    load_entry_point('you-get==0.4.652', 'console_scripts', 'you-get')()
  File "c:\users\qazxd\appdata\local\programs\python\python35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\qazxd\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1422, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\qazxd\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1335, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\qazxd\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1151, in download_main
    download(url, **kwargs)
  File "c:\users\qazxd\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1415, in any_download
    m.download(url, **kwargs)
  File "c:\users\qazxd\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\dilidili.py", line 68, in dilidili_download
    stream_types = dilidili_parser_data_to_stream_types(typ, vid, hd2, sign, tmsign, ulk)
  File "c:\users\qazxd\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\dilidili.py", line 28, in dilidili_parser_data_to_stream_types
    info = re.search(r'(\{[^{]+\})(\{[^{]+\})(\{[^{]+\})(\{[^{]+\})(\{[^{]+\})', html).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [看了一下，似乎是升级了播放器]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
```
<script type="text/javascript">
    $("#k").val(md5($("#k").val() + "1491063958" + "None"));
    eval(function(p, a, c, k, e, d) {
        e = function(c) {
            return c
        };
        if (!''.replace(/^/, String)) {
            while (c--) {
                d[c] = k[c] || c
            }
            k = [function(e) {
                return d[e]
            }];
            e = function() {
                return '\\w+'
            };
            c = 1
        };
        while (c--) {
            if (k[c]) {
                p = p.replace(new RegExp('\\b' + e(c) + '\\b', 'g'), k[c])
            }
        }
        return p
    }('13=37 28();13[12(("\\24").7())]=(17.18(((12(-6)+12(11))).7()*("\\21").7()+16)).7();13[12(((12((19("%34")).7())+12(0))).7())]=(4).7();13[12(((12((19("%36")).7())+12(-3))).7())]=("\\27").7();13[12((0).7())]=(17.18(((12(-5)+12(10))).7()*(19("%38")).7()+9)).7();13[12((17.18((5).7()*((12(((12(("\\23").7())+12(((12(-8)+12((19("%39")).7()))).7()))).7())+12(("\\22").7()))).7()+14)).7())]=(17.18(("\\20").7()*("\\21").7()+16)).7();13[12((19("%32")).7())]=((12((17.18(("\\20").7()*(17.18(((12(-9)+12(14))).7()*(17.18(((12(("\\22").7())+12((1).7()))).7()*(8).7()+16)).7()+16)).7()+15)).7())+12(0))).7();13[12(("\\20").7())]=(19("%35")).7();25("29"+"43"+"44"+"45.47"+"46"+"41"+"31"+"33(\'40\'+\'2\').30"+"42=13.26(\'\')");', 10, 48, '|||||||toString|||||parseInt|e1r||||String|fromCharCode|decodeURIComponent|u0035|u0038|u0034|u0033|u0031|eval|join|u0030|Array|do|va|tB||yId||||new|||k|men|lue|cum|en|t|tEle|ge'.split('|'), 0, {}))
    var oversea = (typeof videoUrl != "undefined" && videoUrl.data.t.indexOf("OVERSEA") > -1) ? 1 : 0;
    var type = 'None';
    var vid = 'None';
    var m3u8 = 0;
    var tm = 1491063958;
    var sign = '15d046a40b8df4cd8569fd5e42afae44';
    var userlink = 'http%3A%2F%2Fwww.dilidili.wang%2F';
    var k = $("#k").val();
    var k2 = md5($("#k2").val());
    var k3 = 'you_can_guess';
    var ip = '108.61.160.202';
    var ipsign = '6da2adb48ae50aa8f636ff8a5c72a3e0';
    var playInfo = {
        type: type,
        vid: vid,
        tm: tm,
        sign: sign,
        k: k,
        k2: k2,
        k3: k3,
        ip: ip,
        ipsign: ipsign,
        userlink: userlink,
        oversea: oversea
    };
    var params = {
        bgcolor: '#FFF',
        allowFullScreen: true,
        allowScriptAccess: 'always'
    };
    var video = [''];
    var flashvars = {
        f: '/api/parse.php?' + $.param($.extend({
            xmlurl: 'null',
            m3u8: m3u8
        }, playInfo)),
        s: 2,
        c: 0,
        p: 1
    };
```
这接口是一定要人用node的意思吗？

**Comment by denobisipsis** [comment]
the call is in the form

https://newplayer.jfrft.com/api/parse.php?xmlurl=null&m3u8=0&type=yun&vid=800262b7da:d955239f11&tm=1491078329&sign=db249627d9a307a785714ccc2f0f0754&k=7f56dbacdb400979fff06180467f69d8&k2=d9c546d096d0d18c09770d9361945793&k3=you_can_guess&ip=x.x.x.x&ipsign=&userlink=urlencode()&oversea=1

you need the value

<input type="hidden" id="k" value="64911312f5039abb95acd88dd3709222">


for k script makes md5($k.$tm.$vid)

for k2 you need to eval packed to get another k2 value, and then k2=md5(k2)

But the used md5 is something different. It has the state values changed, and maybe more. Its not the standard md5 (check http://www.myersdaily.org/joseph/javascript/md5.js for a standard implementation)

For example:

- classic md5(46744376d80e2c8f1a4cbbc4a295910ad0d5f47)=75b3e9ee15592a129b61dee915307f0e
- dilidili md5 = 15307f0e9b61dee915592a1275b3e9ee

**Comment by A-Circle-Zhang** [comment]
是的，用 Node 难度会比较小。

**Comment by QShen3** [comment]
几年前用过D站现在用的那个CKPlayer，他们论坛里面有人好像也是自己在做解析……当时感觉还没有you-get稳定……现在是商业化了还是怎么了，竟然能如此稳定……

**Comment by rosynirvana** [comment]
是把salting放进了function md5里，然后把hex dump的顺序（每32bits）反了过来
```
string = string + "6d80e2c8f1a4cbbc4a295910ad0d5f47";
```

```
return (md5_WordToHex(d)+md5_WordToHex(c)+md5_WordToHex(b)+md5_WordToHex(a)).toLowerCase();
```

验证：
```python
salt =  "6d80e2c8f1a4cbbc4a295910ad0d5f47"

def rev_hexdump(s32):
    return s32[24:32] + s32[16:24] + s32[8:16] +s32[:8]

def salt_md5(data, salt):
    import hashlib
    return hashlib.md5((data+salt).encode('utf8')).hexdigest()

rev_hexdump(salt_md5('12345', salt))
```

from py3 ```a062fbeb6a45e2afe2ef59702bf4bb3a```
from node ```a062fbeb6a45e2afe2ef59702bf4bb3a```

**Comment by rosynirvana** [comment]
另外这个utf8编码的函数
```
function md5_Utf8Encode(string){
        string = string.replace(/\r\n/g,"\n");
        var utftext = "";
        for (var n = 0; n < string.length; n++) {
            var c = string.charCodeAt(n);
            if (c < 128) {
                utftext += String.fromCharCode(c);
            }else if((c > 127) && (c < 2048)) {
                utftext += String.fromCharCode((c >> 6) | 192);
                utftext += String.fromCharCode((c & 63) | 128);
            } else {
                utftext += String.fromCharCode((c >> 12) | 224);
                utftext += String.fromCharCode(((c >> 6) & 63) | 128);
                utftext += String.fromCharCode((c & 63) | 128);
            }
        }
        return utftext;
    };
```
line sep的处理，应该不是unicode normalization
另外只考虑了3 bytes的utf8
应该是在输入为没有\r\n的3 bytes(or less) utf8行为和 ```somebytes.encode('utf8')```相同

**Comment by A-Circle-Zhang** [comment]
我建议你们放弃直接解析 Dilidili 本身。
现在视频源类型和视频 id 都已经明文给出来了（比如 vid=298458500&v=iqiyi 或 vid=fTEamQFn1xV49l4&v=pptv 之类的），为什么不直接用 you-get 现有的解析器（如 iqiyi 或 pptv）去解析呢？
Dilidili 现在优酷、腾讯、爱奇艺、PPTV 都已经采取的是本地 Flash 或者 JS 解析，不久其它资源也都将解析转向本地，也就是说你们请求 parse.php 将变得毫无意义... 得到的只有 id 之类的解析信息，不会再有直接的视频源地址。

**Comment by denobisipsis** [comment]
Sorry, thats funny.

The only change is the word order

you must array reverse the normal md5 in word chunks, adding first the salt 

6d80e2c8f1a4cbbc4a295910ad0d5f47

implode(array_reverse(str_split(md5("46744376d80e2c8f1a4cbbc4a295910ad0d5f47"),8)));

or

r="46744376d80e2c8f1a4cbbc4a295910ad0d5f47";

import md5

def str_split(s, n):
    ret = []
    for i in range(0, len(s), n):
        ret.append(s[i:i+n])
    return ret

r=str_split(md5.new(str(r)).hexdigest(),8)

print("".join(r[::-1]))

**Comment by QShen3** [comment]
也不能说完全没有意义，比如一些VIP视频

**Comment by rosynirvana** [comment]
现在看来dilidili api server本身快挂了，HTTP 561 ……

要不dili用户收集一些iframe里的url，试了两个，type=yun是爱奇艺云

**Comment by A-Circle-Zhang** [comment]
@rosynirvana 
yun 是乐视云
你能抓到爱奇艺的链接是因为所有来源都用了爱奇艺的一个链接（https://data.video.iqiyi.com/v.mp4）用于本地判断 IP。

**Comment by kang0024** [comment]
我这边也挂了。。。

**Comment by rosynirvana** [comment]
dilidili tucao这两个站的支持可以去掉了吧
另外还有miomio

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/commit/a30d822cee71a75b928b61195cb7dc879a61ccaa
https://github.com/zhangn1985/ykdl/commit/61368cf4a853fc0135fc8d8ef362cf3a19007aea

**Comment by rosynirvana** [comment]
dilidili changes days ago so info here is outdated.
in favor of #2143
