### ISSUE TITLE
如果我通过shadowsocks访问youtube，应该如何输入以下载youtube的视频？

### ISSUE THREAD

**Issue by HinGitHub** [soimort/you-get#1824]
如果我通过shadowsocks访问youtube，应该如何输入以下载youtube的视频？

**Comment by lihongjie0209** [comment]
你可以设置一个alias:

`alias youtube='you-get -s 127.0.0.1:1080 -o ~/Videos/YouTube'`

>     -s | --socks-proxy <HOST:PORT>      Use an SOCKS5 proxy for  download

>    -o | --output-dir <PATH>            Set output directory.
