### ISSUE TITLE
优酷只能下一个片段

### ISSUE THREAD

**Issue by xuyuanfang** [soimort/you-get#1827]
21.8% (142.0/651.6MB) ├█████████────────────────────
21.8% (142.3/651.6MB) ├█████████────────────────────
21.9% (142.5/651.6MB) ├█████████────────────────────
21.9% (142.7/651.6MB) ├█████████────────────────────
────────────┤[3/3]    2 MB/s
Merging video parts... Merged into 鲜肉老师 07.mp4

优酷只能下一个片段

**Comment by firectrl** [comment]
you-get --format=hd3 "http://v.youku.com/v_show/id_XMjY3MDkzNjA2NA==.html?from=y1.3-movie-index-11791-24595.236952.6-1&spm=a2hmv.20024595.yk-slide-236952.5~5!6~5~5!2~A"

11.5% ( 192.7/1681.7MB) ├█████──────────────────────────────────┤[5/5]    4 MB/11.5% ( 192.7/1681.7MB) ├█████──────────────────────────────────┤[5/5]    4 MB/s
Merging video parts...
Merged into 大闹天竺.flv

只能下载到一个片段

**Comment by rosynirvana** [comment]
vip视频只能下试看片段
