### ISSUE TITLE
Is it possible to invoke you-get inside python?

### ISSUE THREAD

**Issue by liuzhen2008** [soimort/you-get#1829]
Is there a way such that I can invoke you-get within a python script.

So that the return results are stored in memory.

For example, I am imagining invoking you-get -i "someURL" inside a python script. Then, the returned result in a simple list of dictionaries. Which i am then able to check the available resolutions and stuff.

Is that something can be easily done?

**Comment by lzy0699** [comment]
--json可以返回相关信息的，json格式字典，可以通过接管系统I/O来捕获you-get的输出(详见我在https://github.com/soimort/you-get/issues/1793中的回复)，然后可以用eval()或者json.loads()函数来转换成python字典。不过有些网站的用--json参数返回的不是所有视频的信息字典，比如乐视和youtube的。。。我的做法比较麻烦：
一、接管系统I/O捕获you-get -i的输出信息。
二、用正则等方式从捕获的信息中提取视频格式信息存入自定义字典，打印输出成自己的视频信息格式以供选择。
三、根据上面选择的格式调用相应参数进行下载或者播放或者输出详细视频格式信息再捕获用于自己的下一步操作。
