### ISSUE TITLE
关于bilibili和PPTV清晰度的讨论

### ISSUE THREAD

**Issue by QShen3** [soimort/you-get#1831]
目前这两个网站you-get是不支持多清晰度的，自己看了一下代码，然后猜了一下。

首先是B站，you-get中B站获取包含播放地址的XML的那个接口返回的XML数据中有一个标签是accept_quality，比如

`<accept_quality>3,2,1</accept_quality>`

然后就猜测加上quality参数是否可以获取到其它清晰度，然后试了一下，是可以的。
自己python的代码能力比较差，提PR的话不知道要怎么改比较合适，所以自己写了一个单独的文件，放在附件demo.zip里面，用法就是python bilibili.py url [format]，会输出包含播放地址的json。其中format是可选参数，对应不同的清晰度，可选的数据放在返回的available数组里面。比如：
python bilibili.py http://bangumi.bilibili.com/anime/5563/play#100353 hdmp4

之后是PPTV，PPTV接口返回的json里面同样提到了多个分辨率，然后去抓包，发现有一个参数是version，version=1的时候返回一种清晰度的信息，version=4的时候会返回四种清晰度信息。之后的处理方法和you-get中的处理方法完全相同，甚至需要会员的1080P也可以。同样，在demo.zip里面放了一个pptv.py，使用方法和上面一样。

[demo.zip](https://github.com/soimort/you-get/files/893059/demo.zip)

可能大家已经发现了，只是没有来得及加上。自己python编码太弱，所以只开了一个issue

**Comment by rosynirvana** [comment]
其实不用parse那个xml，加&otype=json会返回json，sign的时候params要按key来排序

**Comment by Realmyname** [comment]
PPTV 清晰度：
eg:
http://web-play.pptv.com/webplay3-0-17285316.xml?type=&version=4
http://web-play.pptv.com/webplay3-0-17285316.xml?type=atv&version=4

url 组合：<file cur="0">b91c747539bb3b49f8c17f3918daa5a2.mp4"........</file>
<dt ft="0"><sh>111.7.164.204</sh>
<st>Fri May 26 10:37:49 2017 UTC</st>
<id>fd6023497bbfebe750101795dc8eb6cb</id>
<bwt>0</bwt>
<bh>122.72.27.250</bh>
<key expire="Fri May 26 14:38:49 2017 UTC">
be2c75a5f77a08138f3119b5bafce48a-5b1e-1495809529%26bppcataid%3D9

url = 122.72.27.250/b91c747539bb3b49f8c17f3918daa5a2.mp4?type=atv&w=1&k=be2c75a5f77a08138f3119b5bafce48a-5b1e-1495809529%26bppcataid%3D9

url = 【对应】/【对应】?type=【对应】&w=1&k=【对应】

**Comment by soimort** [comment]
Closed via #2025.
