### ISSUE TITLE
How to make You-get to auto set file extension?

### ISSUE THREAD

**Issue by liuzhen2008** [soimort/you-get#1836]
I would like to specify my own file name. But i want you-get to append the correct extension automatically. 

Does file extension influence the way you-get fetches the video? I just tried to use -O with .flv and .mp4 for the same youku video. But it appears that one of these extensions causes the video to be completely unplayable?

**Comment by rosynirvana** [comment]
简而言之，是想让-O不指定扩展名对吧？

**Comment by liuzhen2008** [comment]
@rosynirvana 是的是的，就是这意思。

而且我发现 同一个视频，如果命名为xxx.fly 和 xxx.mp4，我在mac上播放器其中一个视频就播放不了。不知道这跟扩展名有没有任何关系？

谢谢

**Comment by rosynirvana** [comment]
哪个视频还能找到吗？用的哪个播放器？

**Comment by liuzhen2008** [comment]
@rosynirvana 
you-get -O what.mp4 http://v.youku.com/v_show/id_XMjY5MTQ1MDg2OA==.html
you-get -O what.flv http://v.youku.com/v_show/id_XMjY5MTQ1MDg2OA==.html

我使用的quicktime, .flv的那个视频无法播放。

**Comment by rosynirvana** [comment]
```common.py line 740```
```if output_filename: return output_filename```
把这行patch为 ```return output_filename + ext``` 就行了 

quicktime应该本身不怎么支持flv，所以改成flv会被拒
如果是基于ffmpeg的播放器，例如mpv mplayerx这些，会忽略扩展名改什么都一样

```
$mpv test.flv
Playing: test.flv
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
AO: [coreaudio] 44100Hz stereo 2ch floatp
VO: [opengl] 720x540 yuv420p
AV: 00:00:02 / 00:02:00 (1%) A-V:  0.000


Exiting... (Quit)
```
$mv test.flv test.123
$ mpv test.123
Playing: test.123
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
AO: [coreaudio] 44100Hz stereo 2ch floatp
VO: [opengl] 720x540 yuv420p
AV: 00:00:04 / 00:02:00 (3%) A-V:  0.000


Exiting... (Quit)
```

**Comment by liuzhen2008** [comment]
多谢帮忙。

**Comment by nqzhang** [comment]
mark
