### ISSUE TITLE
[Request] Change about m3u8

### ISSUE THREAD

**Issue by jack980517** [soimort/you-get#1838]
现在对m3u8（”streaming content“？）的处理是`-y -re`，但这样会导致下载速度为播放速度的1.0~1.1倍，跟绝大多数人现在的物理带宽相比十分缓慢。我刚好遇到了另外一个[使用m3u8的网站](http://v.gdtv.cn)，自己使用了截取m3u8内url、用requests库下载（urllib应该也行？）、最后再调用ffmpeg进行合并（`-f concat -safe 0 -i list.txt -c copy`，list.txt为若干行`file xxx.ts`）的方法，比`-y -re`快上不少。在下载大于十分钟的视频的时候优点尤为明显。
我合并视频的方法取自[ffmpeg官方wiki](https://trac.ffmpeg.org/wiki/Concatenate)。望采纳，谢谢！

**Comment by mengmo** [comment]
https://github.com/soimort/you-get/issues/1806
这两个问题差不多

**Comment by cnbeining** [comment]
之所以我当时用了ffmpeg 是因为我要支持**HLS** 的下载，以及应对**加密M3U/HLS** ，还有一些**胡乱切片** 的情况。

对于不需专门处理的网站 我建议直接**解析M3U 提取所有分片** 链接。ffmpeg**不应该** 作为**主要**
 的下载方式。

#1806 同理。

**Comment by lamlam123tld3** [comment]
comparing to using ffmpeg to concat ts stream
i prefer using copy /b

**Comment by cnbeining** [comment]
By using byte concat you are risking corrupting the file.

2017年4月8日 下午1:58，"lamlam123tld3" <notifications@github.com>写道：

**Comment by mengmo** [comment]
> comparing to using ffmpeg to concat ts stream
i prefer using copy /b

I've tried `wget -O xxx.ts ***.m3u8` before
the target file `xxx.ts` did not play properly

**Comment by rosynirvana** [comment]
https://trac.ffmpeg.org/raw-attachment/wiki/Concatenate/pipe-friendly-formats.png

**Comment by cnbeining** [comment]
I personally would use ```aria2``` with ```-L``` to download all the segments and run ```ffmpeg``` on them. 

But this hack should not be included in this project.

Again, contributors, please ONLY use ffmpeg when you really need this: if you are dealing M3U file without encryption, try extract all the segments as "part of video" and call ffmpeg to concat them. 

And, if dealing with 

- Live HLS/RTMP(try rtmpdump)

- M3U with encryption

- other circumstances when ffmpeg shall not behave if M3U not being fed in directly

Do not hesitate to use ffmpeg to assist you.
