### ISSUE TITLE
为什么下载的youku视频不能自动合并？

### ISSUE THREAD

**Issue by wangx2** [soimort/you-get#1840]
我已经下载并且安装好了FF，为什么还是一段一段的

**Comment by rosynirvana** [comment]
贴链接

**Comment by wangx2** [comment]
我试了好几个都不行，是不是我的FF弄错了？

**Comment by rosynirvana** [comment]
ffmpeg的可执行文件不在path里？

**Comment by wangx2** [comment]
在啊，不过我是在http://bbs.eeworld.com.cn/forum.php?mod=viewthread&tid=505971&extra=page%3D1&page=1 这里下载的配置文件安装的

**Comment by rosynirvana** [comment]
猜一下吧…… ffmpeg的path和you-get (也就是python3）的path是不是同一个账户的？

**Comment by wangx2** [comment]
在终端下输入ffmpeg输出内容如下，应该是同一个账户，因为我都没有启用root账户，都是使用sudo pi这个账户安装的

ffmpeg version N-85386-gd14a1bd Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: --enable-gpl --enable-version3 --enable-nonfree --enable-static --disable-shared --prefix=/usr/local --disable-opencl --disable-thumb --disable-pic --disable-stripping --enable-small --enable-ffmpeg --enable-ffplay --enable-ffserver --enable-ffprobe --disable-doc --disable-htmlpages --disable-podpages --disable-txtpages --disable-manpages --disable-everything --enable-libx264 --enable-encoder=libx264 --enable-decoder=h264 --enable-encoder=aac --enable-decoder=aac --enable-encoder=ac3 --enable-decoder=ac3 --enable-encoder=rawvideo --enable-decoder=rawvideo --enable-encoder=mjpeg --enable-decoder=mjpeg --enable-muxer=flv --enable-demuxer=flv --enable-muxer=mp4 --enable-demuxer=mpegvideo --enable-muxer=matroska --enable-demuxer=matroska --enable-muxer=wav --enable-demuxer=wav --enable-muxer='pcm*' --enable-demuxer='pcm*' --enable-muxer=rawvideo --enable-demuxer=rawvideo --enable-parser=h264 --enable-parser=aac --enable-protocol=file --enable-protocol=tcp --enable-protocol=rtmp --enable-protocol=cache --enable-protocol=pipe --enable-filter=aresample --enable-filter=allyuv --enable-filter=scale --enable-indev=v4l2 --enable-indev=alsa --enable-omx --enable-omx-rpi --enable-encoder=h264_omx --enable-mmal --enable-hwaccel=h264_mmal --enable-decoder=h264_mmal
  libavutil      55. 60.100 / 55. 60.100
  libavcodec     57. 92.100 / 57. 92.100
  libavformat    57. 72.100 / 57. 72.100
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 84.100 /  6. 84.100
  libswscale      4.  7.100 /  4.  7.100
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**Comment by rosynirvana** [comment]
pi$ sudo ... 还是 sudo -u pi 啊
前者是root用户，后者是pi用户

**Comment by wangx2** [comment]
不是这个问题吧，即使我使用sudo you-get 他还是不能合并呢，
Merging video parts... you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by rosynirvana** [comment]
看到log里有Merging video parts那说明这时候python3能找到ffmpeg了
大概是因为这个自编译的ffmpeg缺东西
