### ISSUE TITLE
Cannot download Youku VIP video even with valid cookies

### ISSUE THREAD

**Issue by ztytian** [soimort/you-get#1842]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

you-get -c /PATH/cookies.txt --debug http://v.youku.com/v_show/id_XMjY4MDE4NjM5Mg==.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjY4MDE4NjM5Mg==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjY4MDE4NjM5Mg==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049173556455712bbfc91_00/st/flv/fileid/0300800B0058DE7432F92F011BA6A92F66A944-7F69-A68A-003A-B44B9BD0B719?ctype=12&ev=1&K=904bcd011179860e2412f7e8%26sign%3Da8bfb7fdff33c133d289ac6276815d24&ep=ciadG06OU8sG4Sbajz8bNX60J34OXP4J9h%2BNgdIQALshQJzKnjrSxeu5TIlCF%2FhrAyR3GemHrdaWY0QQYfc1r2EQrkigSPrg%2FvOS5d9XwOIJFG02AMrWvVSeRjP4&oip=3727199824&token=0539&yxon=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049173556455712bbfc91_00/st/flv/fileid/0300800B0158DE7432F92F011BA6A92F66A944-7F69-A68A-003A-B44B9BD0B719?ctype=12&ev=1&K=50480be2d405b5ff282c4274%26sign%3D8c515d1551e30affb491cf0c8d676373&ep=ciadG06OU8sG4Sbajz8bNX60J34OXP4J9h%2BNgdIQALohQJzKnjrSxeu5TIlCF%2FhrAyR3GemHrdaWY0QQYfc1r2EQrkigSPrg%2FvOS5d9XwOIJFG02AMrWvVSeRjP4&oip=3727199824&token=0539&yxon=1
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049173556455712bbfc91_00/st/flv/fileid/0300800B0258DE7432F92F011BA6A92F66A944-7F69-A68A-003A-B44B9BD0B719?ctype=12&ev=1&K=aedf3eb9afda058d261f9d2e%26sign%3Da76f193166000927a5c53ae1820addb1&ep=ciadG06OU8sG4Sbajz8bNX60J34OXP4J9h%2BNgdIQALkhQJzKnjrSxeu5TIlCF%2FhrAyR3GemHrdaWY0QQYfc1r2EQrkigSPrg%2FvOS5d9XwOIJFG02AMrWvVSeRjP4&oip=3727199824&token=0539&yxon=1
site:                优酷 (Youku)
title:               第12话 胜利的使用方式
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          533.0 MiB (558873525 bytes)
    # download-with: you-get --format=hd3 [URL]

audio-languages:
    - lang:          日语
      download-url:  http://v.youku.com/v_show/id_XMjY4MDE4NjM5Mg==

Downloading 第12话 胜利的使用方式.flv ...
 0.0% (  0.0/533.0MB) ├─────────────────────────────────────────┤[1/3] ^C

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

Video URL: http://v.youku.com/v_show/id_XMjY4MDE4NjM5Mg==.html
Same thing happens to youtube-dl. Seems that Youku did something...

**Comment by ztytian** [comment]
Note: Should have 11 segments

**Comment by rosynirvana** [comment]
我觉得作者应该考虑下对vip视频的支持了，现在新issues大多是关于vip视频的。

如果you-get项目要支持vip视频，好像大多数开发者没有大陆各视频网站的vip账号，所以无法测试……
另外，对于vip视频没账号的，是下载5，6分钟试看片段，还是直接不要，从issues来看似乎是有分歧的。

**Comment by ztytian** [comment]
之前挂cookies.txt可以下载，现在不行了

**Comment by 472818652** [comment]
使用cookie.sqlite文件可以下载youku的vip视频

**Comment by ztytian** [comment]
cookies.sqlite确实可以使用
我觉得可能是youku的鉴定机制改变的，涉及到非youku.com的cookies数据了

**Comment by 472818652** [comment]
弱弱问句，letv（乐视）的VIP会员视频下载不了完整的，你们有人能下么？

**Comment by ztytian** [comment]
@472818652 貌似cookies.sqlite也不行了
