### ISSUE TITLE
Unable to download from Tudou

### ISSUE THREAD

**Issue by ztytian** [soimort/you-get#1847]
you-get --debug http://www.tudou.com/albumplay/hM6Tgwe9SEg/S_wEJpmcXWA.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTM3OTE1NzMzNg==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTM3OTE1NzMzNg==&ct=12
you-get: [Failed] 抱歉，因版权原因无法观看此视频！

Cannot download videos from Tudou. It can be played online.

**Comment by rosynirvana** [comment]
用优酷云端口返回的版权问题

**Comment by ztytian** [comment]
然而我挂了cookies并且在线可以正常观看。YouTube-dl反馈仅中国大陆可观看。

**Comment by rosynirvana** [comment]
意思是从优酷的接口看不了，会显示版权，页面下面的回复也说明这一点。
土豆用的可能是别的接口。

**Comment by rosynirvana** [comment]
用的接口是```ct=60```，time是```1000 * epoch```
```http://play-ali.youku.com/play/get.json?vid=XMTM3OTE1NzMzNg==&ct=60&time=1492213193183```

**Comment by rosynirvana** [comment]
```ct60```的返回的encrypt_string过base64 decode之后长度是32，其他接口是26；
另外生成的```ep```在没有过b64encode和urlencode之前，长度是96，其他接口是93。

仅仅对于这个SD的土豆视频而言，用```ct62```可以拿到一样的视频。但这个```ct60```的```getSize```和```setSize```做了什么我还是很好奇的。

**Comment by zhangn1985** [comment]
可以参考我的youkujs.py，但我不知道Acode是什么。。。

**Comment by zhangn1985** [comment]
@rosynirvana ct60对应哪个swf？

**Comment by rosynirvana** [comment]
@zhangn1985 
现在的的PortalPlayer.swf，也就是PortalPlayer_199.swf
里面youku的versionInfo时间是
```as3
 public static function ver() : String
 {
     return "17-01-10 12:23";
}
```

**Comment by rosynirvana** [comment]
刚发现我没理解项目里现有的代码……

现在对于优酷的视频，虽然是```ct=10 ct=12```做两次解析，但是算```ep```用的都是```ct=12```的算法？生成的链接也都带```ct=12```

**Comment by zhangn1985** [comment]
因为ct=12视频不完整，而ct=10 ep算法破不了。

**Comment by zhangn1985** [comment]
这里的也可以采用这个思路，但是我发现ep算法和之前youku的不太一样。

**Comment by rosynirvana** [comment]
是\0 padding DES ECB，key_pair是```b'22988644' b'e5769c44'```

**Comment by rosynirvana** [comment]
close via #2015
