### ISSUE TITLE
iqiyi视频下载不了

### ISSUE THREAD

**Issue by MrLYU** [soimort/you-get#1854]
you-get --debug http://www.iqiyi.com/v_19rrb59or4.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/641851900/ddee4cdc350fc22412616611395fd5d3/?t=1492235247339&sc=fa37c5559d0c6766bec3fe3f6df62d9c&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               人民的名义第1集
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrb59or4.html']
Traceback (most recent call last):
  File "d:\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\python\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\python\python36\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\python\python36\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\python\python36\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "d:\python\python36\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "d:\python\python36\lib\site-packages\you_get\extractor.py", line 52, in download_by_url
    self.download(**kwargs)
  File "d:\python\python36\lib\site-packages\you_get\extractors\iqiyi.py", line 204, in download
    merge=kwargs['merge'],)
  File "d:\python\python36\lib\site-packages\you_get\common.py", line 968, in download_url_ffmpeg
    assert has_ffmpeg_installed(), "FFmpeg not installed."
AssertionError: FFmpeg not installed.

**Comment by rosynirvana** [comment]
看提示，```FFmpeg not installed```
装ffmpeg

**Comment by denobisipsis** [comment]
Hi,

iqiyi vf/ibt cmd5x is a normal md5 with salt

3sj8xof48xof4tk9f4tk9ypgk9ypg5ul


i.e., for http://www.iqiyi.com/v_19rrb59or4.html

vf=md5("/vms?key=fvip&src=01010031010010000000&tvId=641851900&vid=ddee4cdc350fc22412616611395fd5d3&vinfo=1&tm=506&qyid=&puid=&authKey=ba17dd4f20ff7ac45d548529e6a4d6c5&um=1&pf=b6c13e26323c537d&thdk=&thdt=&rs=1&k_tag=1&qdv=2"."3sj8xof48xof4tk9f4tk9ypgk9ypg5ul");

http://cache.video.qiyi.com/vms?key=fvip&src=01010031010010000000&tvId=641851900&vid=ddee4cdc350fc22412616611395fd5d3&vinfo=1&tm=506&qyid=&puid=&authKey=ba17dd4f20ff7ac45d548529e6a4d6c5&um=1&pf=b6c13e26323c537d&thdk=&thdt=&rs=1&k_tag=1&qdv=2&vf=b3c8f77bfda7a0887d996b9d4ee6981e

and you get 1080p

**Comment by MrLYU** [comment]
多谢，iqiyi可以下载了，但是优酷的视频还是不能下载

**Comment by rosynirvana** [comment]
youku你换到现在的develop branch估计就能下了

```
pip3 install --upgrade git+https://github.com/soimort/you-get@develop
```

**Comment by MrLYU** [comment]
Error [WinError 2] 系统找不到指定的文件。 while executing command git clone -q https://github.com/soimort/you-get C:\Users\LYANG\AppDat
a\Local\Temp\pip-exbz7tq4-build
Cannot find command 'git'

**Comment by MrLYU** [comment]
是不是运行pip3 install --upgrade git+https://github.com/soimort/you-get@develop就可以下载youku视频了？

**Comment by rosynirvana** [comment]
就是说要把you-get升级到develop分支

首先要明白，you-get是python3的一个库，python3的库通常是用pip3来安装/管理的

个人只推荐非py开发者用 安装python3(如果不自带pip3，安装pip3) -> 用pip3安装you-get 这种安装方式
其他安装方式，省一时的事情，而you-get项目又不可能stable，又免不了用命令行

**Comment by zglzw** [comment]
输入pip3 install --upgrade git+https://github.com/soimort/you-get@develop 但是提示
Collecting git+https://github.com/soimort/you-get@develop
  Cloning https://github.com/soimort/you-get (to develop) to c:\users\zglzw\appd
ata\local\temp\pip-z6tcfi3z-build
  Error [WinError 2] 系统找不到指定的文件。 while executing command git clone -q
 https://github.com/soimort/you-get C:\Users\zglzw\AppData\Local\Temp\pip-z6tcfi
3z-build
Cannot find command 'git'

**Comment by rosynirvana** [comment]
```Cannot find command 'git'```
装git

**Comment by zglzw** [comment]
安装git后运行pip3 install --upgrade git+https://github.com/soimort/you-get@develop，还是无法下载优酷视频
