### ISSUE TITLE
加载爱奇艺cookies（包括火狐的sqlite格式和从http包里的txt格式）无效怎么解决 ? Why the cookies（Contains: "sqlite" from FireFox and txt for general browsers） of  IQiYi doesn't work ?

### ISSUE THREAD

**Issue by Akaishyichi** [soimort/you-get#1869]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[site:                爱奇艺 (Iqiyi)
title:               千术2千王之战
stream:
    - format:        4k
      container:     m3u8
      video-profile: 4k
    # download-with: you-get --format=4k [URL]

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i 
http://cache.m.iqiyi.com/mus/634274300/1de5a5b97806528a1460e933af447e8f/afbe8fd3d73448c9/1262804111/20170407/ae/7c/71ba9a904d2e77478025e0b1ec819d49.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=634274300&bossStatus=2&qd_vip=0&px=18ne043YB3eaZeQgfYm2t1c3IaDGm3wYuYi2nfdvMUfhjJihtm3XBUR0Z0CiPm1rBMisTZ06&qd_src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1492430359535&qd_sc=70e869911dda6fec3a4650b6f9113c1c&qypid=634274300_04022000001000000000_19&qd_k=87fb377c7ae59022913d13afa001317c&qd_ip=222.24.128.203&other= -c copy -bsf:a aac_adtstoasc I:\/千术2千王之战.mp4

http://cache.m.iqiyi.com/mus/645814000/76e788090ac9ce5b62352e14a82b4d03/afbe8fd3d73448c9/1395099175/20170405/da/1b/0517bddcd2d37b17cbcd3dab5e47b1d5.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=645814000&bossStatus=2&qd_vip=1&px=c5nJm246ZhJm3BoJDh2FqrWm1ZKe6rZYEm11WZ2rTnJOuwC3CATfm1yzUhXPhDbgihfXrBm222&qd_src=2_20_201&prv=0&previewType=1&previewTime=6&from=&qd_time=1492430043669&qd_sc=842ce8c78c7a72b29e0a5789a090306d&qypid=645814000_04022000001000000000_10&qd_k=b39ac2a1c85df289c9ca77d4d2d886ba&qd_ip=111.73.46.222&sgti=13_5821d09846675f6c6e1582106a0b46e0_1488944275990&other=]

上面也是debug的结果，很明显下载没有问题，但是在解析加载了cookies的地址上有问题，第二段是同一个视频的解析地址，m3u8之后代表的身份里面vip=1是从别的地方得到的解析地址，vip=0是you-get的结果。
如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [优酷的cookies可用，是火狐浏览器的sqlite格式。但是爱奇艺的并不可以，无论是火狐的还是普通的txt 
 Cookies extracted from Firefox does work in YouKu ，but no use in IQiYi.]
> [舔 :icecream:!]

**Comment by ztytian** [comment]
爱奇艺有毒咯。。。我之前在youtube-dl说过结果就是爱奇艺不能挂cookies

**Comment by rosynirvana** [comment]
#2117
