### ISSUE TITLE
爱课程无法下载

### ISSUE THREAD

**Issue by 121786404** [soimort/you-get#1871]
you-get --debug "http://www.icourses.cn/jpk/changeforVideo.action?resId=144405&courseId=3266"

log如下，
 100% (123.6/ 86.9MB) ├█████████████████████████████████████████┤[1/1]    2 MB/s
最后出现filesize已经超过了还一直不停止下载
类似的URL还有
"http://www.icourses.cn/jpk/changeforVideo.action?resId=147960&courseId=3269"       
"http://www.icourses.cn/jpk/changeforVideo.action?resId=908178&courseId=2199"       
"http://www.icourses.cn/jpk/changeforVideo.action?resId=908284&courseId=2199"       
"http://www.icourses.cn/jpk/changeforVideo.action?resId=206787&courseId=4393"       
"http://www.icourses.cn/jpk/changeforVideo.action?resId=1191997&courseId=3220"      
"http://www.icourses.cn/jpk/changeforVideo.action?resId=1192081&courseId=3220"      

[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=144405&courseId=3266
[DEBUG] Requesting video resource location...
[DEBUG] get_html: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492448048230
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492448048230
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_html: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] get_response: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process5/campus/processres/flv/2012/12/14/ff808081-3b95811d-013b-96d5f64d-0012.flv?start=0&ls=play&p=151020&lv=150606-1&lt=04-17%2F09%3A54%3A18&h=uUd15SLoFHCnN4aH_JrNoQ&r=1492501849
[DEBUG] url_info: http://media1.icourses.cn:8080/process5/campus/processres/flv/2012/12/14/ff808081-3b95811d-013b-96d5f64d-0012.flv?start=0&ls=play&p=151020&lv=150606-1&lt=04-17%2F09%3A54%3A18&h=uUd15SLoFHCnN4aH_JrNoQ&r=1492501849
Site:       icourses.cn
Title:      计算机体系结构 第六章 第2讲 I/O系统分析与评价、RAID
Type:       Flash video (video/x-flv)
Size:       86.89 MiB (91110712 Bytes)

Downloading 计算机体系结构 第六章 第2讲 I-O系统分析与评价、RAID.flv ...
16.4% ( 14.2/ 86.9MB) ├███████──────────────────────────────────┤[1/1]    1 MB/s[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=144405&courseId=3266
[DEBUG] Requesting video resource location...
[DEBUG] get_html: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492447837041
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492447837041
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_html: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] get_response: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process5/campus/processres/flv/2012/12/14/ff808081-3b95811d-013b-96d5f64d-0012.flv?start=15204353&ls=seek&p=151020&lv=150606-1&lt=04-17%2F09%3A54%3A32&h=Kxys8CmaTc7LKJWGwiRHjg&r=1492502212
33.1% ( 28.8/ 86.9MB) ├██████████████───────────────────────────┤[1/1]    1 MB/s[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=144405&courseId=3266
[DEBUG] Requesting video resource location...
[DEBUG] get_html: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492447850120
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492447850120
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_html: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] get_response: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process5/campus/processres/flv/2012/12/14/ff808081-3b95811d-013b-96d5f64d-0012.flv?start=30408705&ls=seek&p=151020&lv=150606-1&lt=04-17%2F09%3A54%3A46&h=9teXCvJ4F5f_NCHKY60qvg&r=1492502227
49.8% ( 43.2/ 86.9MB) ├█████████████████████────────────────────┤[1/1]    1 MB/s[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=144405&courseId=3266
[DEBUG] Requesting video resource location...
[DEBUG] get_html: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492448530311
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492448530311
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_html: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] get_response: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process5/campus/processres/flv/2012/12/14/ff808081-3b95811d-013b-96d5f64d-0012.flv?start=45613057&ls=seek&p=151020&lv=150606-1&lt=04-17%2F09%3A54%3A58&h=isVDMeh4_p60LXSkicfBsA&r=1492532186
66.5% ( 57.8/ 86.9MB) ├████████████████████████████─────────────┤[1/1]    1 MB/s[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=144405&courseId=3266
[DEBUG] Requesting video resource location...
[DEBUG] get_html: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492448100666
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492448100666
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_html: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] get_response: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process5/campus/processres/flv/2012/12/14/ff808081-3b95811d-013b-96d5f64d-0012.flv?start=60817409&ls=seek&p=151020&lv=150606-1&lt=04-17%2F09%3A55%3A11&h=azJCtOr9fTWh4E5-MZOIUg&r=1492532198
83.2% ( 72.2/ 86.9MB) ├███████████████████████████████████──────┤[1/1]    1 MB/s[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=144405&courseId=3266
[DEBUG] Requesting video resource location...
[DEBUG] get_html: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492448554827
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492448554827
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_html: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] get_response: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process5/campus/processres/flv/2012/12/14/ff808081-3b95811d-013b-96d5f64d-0012.flv?start=76021761&ls=seek&p=151020&lv=150606-1&lt=04-17%2F09%3A55%3A23&h=dKAJKIa0xvWZa9n7Po_MlA&r=1492502263
99.8% ( 86.8/ 86.9MB) ├█████████████████████████████████████████┤[1/1]    1 MB/s[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=144405&courseId=3266
[DEBUG] Requesting video resource location...
[DEBUG] get_html: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492447814773
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492447814773
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_html: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] get_response: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process5/campus/processres/flv/2012/12/14/ff808081-3b95811d-013b-96d5f64d-0012.flv?start=91110725&ls=seek&p=151020&lv=150606-1&lt=04-17%2F09%3A55%3A37&h=ONjLmR9ZgeqczzzVgdjlBQ&r=1492502277
 100% (101.1/ 86.9MB) ├█████████████████████████████████████████┤[1/1]    1 MB/s[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=144405&courseId=3266
[DEBUG] Requesting video resource location...
[DEBUG] get_html: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492447915021
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492447915021
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_html: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] get_response: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process5/campus/processres/flv/2012/12/14/ff808081-3b95811d-013b-96d5f64d-0012.flv?start=106315077&ls=seek&p=151020&lv=150606-1&lt=04-17%2F09%3A55%3A50&h=oQW8mO6jzGF0K4apRYQMTQ&r=1492532238
 100% (115.6/ 86.9MB) ├█████████████████████████████████████████┤[1/1]    1 MB/s[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=144405&courseId=3266
[DEBUG] Requesting video resource location...
[DEBUG] get_html: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492448593630
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1492448593630
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_html: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] get_response: http://media1.icourses.cn:8080/process5/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process5/campus/processres/flv/2012/12/14/ff808081-3b95811d-013b-96d5f64d-0012.flv?start=121519429&ls=seek&p=151020&lv=150606-1&lt=04-17%2F09%3A56%3A02&h=3o0TAAzBkYCm--ANgM-PLg&r=1492532249
 100% (123.6/ 86.9MB) ├█████████████████████████████████████████┤[1/1]    2 MB/s

**Comment by rosynirvana** [comment]
fixed with 87fb357

./you-get -d http://www.icourses.cn/jpk/changeforVideo.action\?resId\=144405\&courseId\=3266 -o /tmp
[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=144405&courseId=3266
[DEBUG] get_content: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=144405&other=&v=1502375029272&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action
[DEBUG] get_content: http://media1.icourses.cn:8080/process5/campus//ssl/host.shtml
[DEBUG] get_content: http://media3.icourses.cn/ssl/ssl.shtml?r=8002851
[DEBUG] url_info: http://media3.icourses.cn/process5/campus/processres/flv/2012/12/14/ff808081-3b95811d-013b-96d5f64d-0012.flv?start=0&ls=play&h=YiKBU0cmQqVeuGss3k7wOQ&lv=150606-1&p=151020&lt=8-10%2F22%3A25%3A51&r=1502375210
Site:       icourses.cn
Title:      计算机体系结构 第六章 第2讲 I/O系统分析与评价、RAID
Type:       Flash video (video/x-flv)
Size:       86.89 MiB (91110712 Bytes)

[DEBUG] get_content: http://media3.icourses.cn/ssl/ssl.shtml?r=8383272
Downloading 计算机体系结构 第六章 第2讲 I-O系统分析与评价、RAID.flv ...
16.7% ( 14.5/ 86.9MB) ├███████──────────────────────────────────┤[1/1]  194 kB/s[DEBUG] Calling callback update_url for new URL from 15204352
[DEBUG] get_content: http://media3.icourses.cn/ssl/ssl.shtml?r=148972
33.4% ( 29.0/ 86.9MB) ├██████████████───────────────────────────┤[1/1]  126 kB/s[DEBUG] Calling callback update_url for new URL from 30408704
[DEBUG] get_content: http://media3.icourses.cn/ssl/ssl.shtml?r=4248313
50.1% ( 43.5/ 86.9MB) ├█████████████████████────────────────────┤[1/1]  431 kB/s[DEBUG] Calling callback update_url for new URL from 45613056
[DEBUG] get_content: http://media3.icourses.cn/ssl/ssl.shtml?r=4081602
66.8% ( 58.0/ 86.9MB) ├████████████████████████████─────────────┤[1/1]  306 kB/s[DEBUG] Calling callback update_url for new URL from 60817408
[DEBUG] get_content: http://media3.icourses.cn/ssl/ssl.shtml?r=4782964
83.4% ( 72.5/ 86.9MB) ├███████████████████████████████████──────┤[1/1]  301 kB/s[DEBUG] Calling callback update_url for new URL from 76021760
[DEBUG] get_content: http://media3.icourses.cn/ssl/ssl.shtml?r=1871101
 100% ( 86.9/ 86.9MB) ├█████████████████████████████████████████┤[1/1]  157 kB/s

**Comment by gjjpkc** [comment]
@rosynirvana 现在爱课程还能下载吗，我试了都不行了。
