### ISSUE TITLE
You-Get是怎么使用ffmpeg merge优酷分段视频的。。。

### ISSUE THREAD

**Issue by ztytian** [soimort/you-get#1874]
这不是issue，只是一个问题。。。
前两天优酷挂了，用youtube-dl下载之后手动merge
翻了一下源代码，似乎是ffmpeg -y -f concat -safe -1 -i ./mergelist.txt -c copy -bsf:a aac_adtstoasc output.mp4，不过每次用这个（mergelist.txt编辑过的），都提示找不到文件，用了绝对路径也是。。。
比如这个link，http://v.youku.com/v_show/id_XMjY5OTI1MzQ2MA==.html，下载下来之后是两个1:45左右的flv，Google了半天找到ffmpeg -i concat:'file1.flv|file2.flv' -vcodec copy -acodec copy  -y output.mp4，不过merge出来各种乱码没法看。。。所以求教you-get是怎么掉用ffmpeg来merge优酷flv的，用的什么perimeter。。。「捂脸」

**Comment by cnbeining** [comment]
txt必须单引号。

concat不能这么用。

2017年4月18日 上午7:11，"ztytian" <notifications@github.com>写道：

**Comment by rosynirvana** [comment]
[ffmpeg trac about concat](https://trac.ffmpeg.org/wiki/Concatenate)

**Comment by ztytian** [comment]
按ffmpeg官网的方法合并出来会有乱码…

**Comment by rosynirvana** [comment]
视频又不是文本，怎么叫乱码
官网那几种方法你用的哪一种

**Comment by ztytian** [comment]
![vlcsnap-2017-04-19-11h24m46s211](https://cloud.githubusercontent.com/assets/21170940/25157036/d70816c8-24f2-11e7-9167-3a5acb94013a.png)
如图。。。
就是这个ffmpeg -f concat -safe 0 -i mylist.txt -c copy output

**Comment by rosynirvana** [comment]
大概是这个附近？重复不了
http://wx4.sinaimg.cn/mw690/005ElEqUly1fernznf2fkj312e0ln1kx.jpg

ffmpeg 3.2.4，命令行参数
```
ffmpeg -f concat -safe 0 -i file.txt -c copy out.mp4
```

两个分片的sha1
```
6632ecdcbc8adc14030f14a92f3bac389218e819  1.flv
dc4bd6945fa0b39eb6a2013661f2f9856444a8ec  2.flv
```

合并的临时文本
```
file 1.flv
file 2.flv
```

**Comment by ztytian** [comment]
嗯。那我猜大概是我的ffmpeg有问题。。。我试试重新装一下（要么就是VLC的有问题）

**Comment by rosynirvana** [comment]
播放器是
```
 mpv --version
mpv 0.17.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Jun  2 23:09:12 CST 2016
ffmpeg library versions:
   libavutil       55.17.103 (runtime 55.34.101)
   libavcodec      57.24.102 (runtime 57.64.101)
   libavformat     57.25.100 (runtime 57.56.101)
   libswscale      4.0.100 (runtime 4.2.100)
   libavfilter     6.31.100 (runtime 6.65.100)
   libswresample   2.0.101 (runtime 2.3.100)
ffmpeg version: 3.2.4
```

**Comment by ztytian** [comment]
brew uninstall ffmpeg && brew install ffmpeg解决。。。
MD5 (output.mp4) = 1b1f19a5668b587daf333175a082c943
MD5 (第28话 松永台风登陆.mp4) = 1b1f19a5668b587daf333175a082c943
谢谢了
