### ISSUE TITLE
youtube 视频版本明明有1080p版本, 为什么默认下载720p, 怎么更改默认?

### ISSUE THREAD

**Issue by hkyuei** [soimort/you-get#1878]
比如说这个: https://www.youtube.com/watch?v=6v2L2UGZJAM

**Comment by rosynirvana** [comment]
```
you-get -di 'https://www.youtube.com/watch?v=6v2L2UGZJAM'
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=6v2L2UGZJAM
[DEBUG] get_content: https://www.youtube.com/watch?v=6v2L2UGZJAM
[DEBUG] get_content: https://www.youtube.com/yts/jsbin/player-pt_BR-vflBsKKun/base.js
site:                YouTube
title:               ► Planet Earth: Amazing nature scenery (1080p HD)
streams:             # Available quality and codecs
    [ DASH ] ____________________________________
    - itag:          137
      container:     mp4
      quality:       1920x1080
      size:          281.3 MiB (294999646 bytes)
    # download-with: you-get --itag=137 [URL]

    - itag:          248
      container:     webm
      quality:       1920x1080
      size:          230.1 MiB (241319946 bytes)
    # download-with: you-get --itag=248 [URL]
```

默认不会下载的啊，只会打印不同清晰度的信息，你用的是不是最新的release版？

**Comment by hkyuei** [comment]
@rosynirvana `you-get https://www.youtube.com/watch?v=6v2L2UGZJAM` 这样就直接下载了

**Comment by rosynirvana** [comment]
先用-i 看流信息

**Comment by hkyuei** [comment]
@rosynirvana 
`site:                YouTube
title:               ► Planet Earth: Amazing nature scenery (1080p HD)
streams:             # Available quality and codecs
    [ DASH ] ____________________________________
    - itag:          137
      container:     mp4
      quality:       1920x1080
      size:          281.3 MiB (294999646 bytes)
    # download-with: you-get --itag=137 [URL]

    - itag:          248
      container:     webm
      quality:       1920x1080
      size:          230.1 MiB (241319946 bytes)
    # download-with: you-get --itag=248 [URL]

    - itag:          136
      container:     mp4
      quality:       1280x720
      size:          156.5 MiB (164076280 bytes)
    # download-with: you-get --itag=136 [URL]

    - itag:          247
      container:     webm
      quality:       1280x720
      size:          127.9 MiB (134089814 bytes)
    # download-with: you-get --itag=247 [URL]

    - itag:          135
      container:     mp4
      quality:       854x480
      size:          86.6 MiB (90839405 bytes)
    # download-with: you-get --itag=135 [URL]

    - itag:          244
      container:     webm
      quality:       854x480
      size:          69.7 MiB (73065765 bytes)
    # download-with: you-get --itag=244 [URL]

    - itag:          134
      container:     mp4
      quality:       640x360
      size:          49.0 MiB (51354326 bytes)
    # download-with: you-get --itag=134 [URL]

    - itag:          243
      container:     webm
      quality:       640x360
      size:          44.2 MiB (46306191 bytes)
    # download-with: you-get --itag=243 [URL]

    - itag:          133
      container:     mp4
      quality:       426x240
      size:          35.9 MiB (37658964 bytes)
    # download-with: you-get --itag=133 [URL]

    - itag:          242
      container:     webm
      quality:       426x240
      size:          29.6 MiB (31033397 bytes)
    # download-with: you-get --itag=242 [URL]

    - itag:          160
      container:     mp4
      quality:       256x144
      size:          22.8 MiB (23957996 bytes)
    # download-with: you-get --itag=160 [URL]

    - itag:          278
      container:     webm
      quality:       256x144
      size:          22.5 MiB (23626854 bytes)
    # download-with: you-get --itag=278 [URL]

    [ DEFAULT ] _________________________________
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          156.4 MiB (164019254 bytes)
    # download-with: you-get --itag=22 [URL]

    - itag:          43
      container:     webm
      quality:       medium
    # download-with: you-get --itag=43 [URL]

    - itag:          18
      container:     mp4
      quality:       medium
    # download-with: you-get --itag=18 [URL]

    - itag:          36
      container:     3gp
      quality:       small
    # download-with: you-get --itag=36 [URL]

    - itag:          17
      container:     3gp
      quality:       small
    # download-with: you-get --itag=17 [URL]`

-i 这个url里面有1080p 但是可以看到代码里面 [ DEFAULT ]标签在hd720里面.为什么不是默认1080p?

**Comment by hkyuei** [comment]
```
quality:       1920x1080
      size:          281.3 MiB (294999646 bytes)
```
```
[ DEFAULT ] _________________________________
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          156.4 MiB (164019254 bytes)
```
为什么默认不是文件大的1920*1080

**Comment by rosynirvana** [comment]
因为1080p那个是dash，现在的实现里default不会考虑dash

**Comment by hkyuei** [comment]
@rosynirvana dash是什么意思? 我用--format 指定这个1080版本是可以下载并且播放的.

**Comment by rosynirvana** [comment]
Dynamic Adaptive Streaming over HTTP
为什么默认没考虑dash要问作者

**Comment by hkyuei** [comment]
@rosynirvana 在哪个地方能改掉默认吗, 如果像我这样的人要想下载一个专辑的所有视频1080p DASH, 就得一个一个 -i 然后 一个一个-format 下载所有.太麻烦了.

**Comment by yangyang6** [comment]
@rosynirvana  这个是什么问题啊，挂了VPN都下载不了，网页是可以看视频的
`you-get https://www.youtube.com/watch?v=HzWe4iuP-7w`

`you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.`

**Comment by yangyang6** [comment]
@rosynirvana  这个是什么问题啊？  浏览器挂VPN是可以查看到视频的，但是命令下载不了；、

- you-get https://www.youtube.com/watch?v=HzWe4iuP-7w
系统提示：
> you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by rosynirvana** [comment]
@hkyuei 应该是要动```extractor.py```
@yangyang6 用--debug 跑，看log

**Comment by hkyuei** [comment]
@yangyang6 `you-get -x 127.0.0.1:1080` 用-x 设置通过代理下载

**Comment by hkyuei** [comment]
@rosynirvana  非常感谢您回答我的问题.
