### ISSUE TITLE
Iqiyi视频的文件名错误而且会覆盖同名文件 Iqiyi File is right but filename is wrong & overwrite the file with the same name

### ISSUE THREAD

**Issue by WooLawRen** [soimort/you-get#1894]
Please make sure these boxes are checked before submitting your issue – thank you!

- [√] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [√] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [√] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [√] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
site:                爱奇艺 (Iqiyi)
title:               魔力美食_20170104期
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      size:          0.0 MiB (0 bytes)
    # download-with: you-get --format=TD [URL]

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://cache.m.iqiyi.com/mus/204044801/846929bb472e8ffa36f9b8e35dd703d7/afbe8fd3d73448c9//20170211/30/69/3dccde025a1f001fb547bcb0ffc5bec1.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=598026100&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1493006218578&qd_sc=2833526cefdfd46ef2ab037ab9cf95b0&qypid=598026100_04022000001000000000_4&qd_k=f5775e7080188e849c7f9a0ab8ec3ec2&qd_ip=23.105.219.198&other= -c copy -bsf:a aac_adtstoasc 魔力美食_20170104期.mp4
Google Videos search:
- video:  Google Home --TEST--debug - YouTube [0:14]
# you-get https://www.youtube.com/watch?v=nieVmZkpVeI

- video:  Debug U-SQL jobs | Microsoft Docs [13:12]
# you-get https://docs.microsoft.com/en-us/azure/data-lake-analytics/data-lake-analytics-debug-u-sql-jobs

- video:  Use Chrome's inspector to debug an addon - EmberMap | Video ... [3:31]
# you-get https://embermap.com/video/use-chrome-s-inspector-to-debug-an-addon

- video:  Lesson 1---- - Lecture 1.2: Debug Environments ... - Coursera [12:46]
# you-get https://www.coursera.org/learn/arduino-platform/lecture/OUwQX/lecture-1-2-debug-environments

- video:  Debugging Tips and Tricks - WWDC 2016 - Videos - Apple Developer [?]
# you-get https://developer.apple.com/videos/play/wwdc2016/417/

- video:  DEBUG - TeacherTube [1:54]
# you-get http://www.teachertube.com/video/debug-88362

- video:  The Witcher 3 -- Enabling Debug Console (v1.31) - YouTube [2:26]
# you-get https://www.youtube.com/watch?v=WX1wQME2qDM

- video:  Post-Implementation Debug Using ECO Flow - Xilinx [?]
# you-get https://www.xilinx.com/video/hardware/post-implementation-debug-using-eco-flow.html

- video:  Ionic iOS Debug Tutorial - YouTube [4:54]
# you-get https://www.youtube.com/watch?v=DXzezPHUhUM

- video:  How to Debug a Linux Application using Xilinx SDK [?]
# you-get https://www.xilinx.com/video/soc/debug-linux-application-using-xilinx-sdk.html

Best matched result:
site:                YouTube
title:               Google Home --TEST--debug
stream:
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          1.7 MiB (1810230 bytes)
    # download-with: you-get --itag=22 [URL]

Downloading Google Home --TEST--debug.mp4 ...

 0.0% (  0.0/  1.7MB) ├─────────────────────────────────────────┤[1/1] 
14.5% (  0.2/  1.7MB) ├██████───────────────────────────────────┤[1/1]   89 kB/s
29.0% (  0.5/  1.7MB) ├████████████─────────────────────────────┤[1/1]  410 kB/s
43.4% (  0.8/  1.7MB) ├██████████████████───────────────────────┤[1/1]  412 kB/s
57.9% (  1.0/  1.7MB) ├████████████████████████─────────────────┤[1/1]  487 kB/s
72.4% (  1.2/  1.7MB) ├██████████████████████████████───────────┤[1/1]  493 kB/s
86.9% (  1.5/  1.7MB) ├████████████████████████████████████─────┤[1/1]   16 MB/s
 100% (  1.7/  1.7MB) ├█████████████████████████████████████████┤[1/1]  362 kB/s

Saving Google Home --TEST--debug.a.en.srt ... Done.

```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
你输入的是什么？看上去不对，有一部分东西被认成google搜索了

**Comment by WooLawRen** [comment]
我用的是Windows的Powershell，输入内容如下：
PS Q:\魔力美食> you-get http://www.iqiyi.com/v_19rr9y7d7s.html?vfm=m_103_txsp#curid=598026100_0bf7ea3bed1c77c42590927fba73d3d8 --debug > debug.txt

**Comment by WooLawRen** [comment]
对了，我开了ss的全局代理，然后是不是有点影响？但是我报告的这个问题，在不是全局代理的情况下也是发生了……

**Comment by rosynirvana** [comment]
url里面有个?，你输入时候没转义，后面那部分被认成另一个部分了。如果不开代理会在google搜索上卡住。

你说的 
> Iqiyi File is right but filename is wrong”，
从log来看ffmpeg的输出文件名应该是```魔力美食_20170104期.mp4```

这个哪里不对吗？还是说你想下的是别的？iqyi的url很容易搞错

**Comment by WooLawRen** [comment]
原来如此……
是这样的，http://www.iqiyi.com/v_19rr9y7d7s.html这个链接对应的是0104期，也就是那个文件名
但是我用浏览器点进去以后，点侧边的其它视频，它跳转过去以后，那个网址变成了
http://www.iqiyi.com/v_19rr9y7d7s.html?vfm=m_103_txsp#curid=598026100_0bf7ea3bed1c77c42590927fba73d3d8
也就是前面的内容没变，后面的参数表示新的视频，对应的是“魔力美食 20170106期 白菜的几种做法”
然后我用you-get下载的时候，确实是得到了"20170106期"的视频，但是文件名还是原来的“0104期”
大致就是这样，抱歉说的有点啰嗦，不知道是不是解释清楚了……

**Comment by rosynirvana** [comment]
果然是iqyi的这个问题，你再打开那个链接看看，还是0104的视频……
用you-get去抓，还是0104的
```
you-get -i 'http://www.iqiyi.com/v_19rr9y7d7s.html?vfm=m_103_txsp#curid=598026100_0bf7ea3bed1c77c42590927fba73d3d8'
site:                爱奇艺 (Iqiyi)
title:               魔力美食_20170104期
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
    # download-with: you-get --format=LD [URL]
```

**Comment by rosynirvana** [comment]
留一个note
对于iqiyi js生成的播放列表内切换的url，例如
```http://www.iqiyi.com/v_19rr9y7d7s.html?vfm=m_103_txsp#curid=598026100_0bf7ea3bed1c77c42590927fba73d3d8```

正确的处理方法是，抓取fragment identifier，在上面的例子里是```curid=598026100_0bf7ea3bed1c77c42590927fba73d3d8```

处理frag id：
```
aid, vid = frag_id.split('=')[1].split('_')
```

获取一般信息：
```
url = 'http://cache.video.qiyi.com/jp/vi/{aid}/{vid}/'.format(aid=aid, vid=vid)
```

拿到的json中```vu```就是实际url（iqiyi服务器能正确识别集数的url），这个url只用来获取统一格式的title，下载可以直接用前面拿到的```aid vid```

**Comment by WooLawRen** [comment]
您好，我又试了一下，
http://www.iqiyi.com/v_19rr9y7d7s.html#curid=598026100_0bf7ea3bed1c77c42590927fba73d3d8
还是这个链接，确实用浏览器打开的话会跳转到原来的0104期
但是用you-get下载完以后，文件名虽然是0104期，但是内容却是0106期
这也是很神奇的地方……因为文件内容是正确的，所以我才觉得文件名可能也是能get到正确的

另外多谢您注释的那个方法，我已经从那个json文件中找到真实的地址了，非常感谢

**Comment by rosynirvana** [comment]
This IS a bug, thank you for your issue.

**Comment by WooLawRen** [comment]
感谢您的帮助，然后再多说一句，这个文件名错了这个不是很急，毕竟内容是正确的，我手动改名就好了，关键是它会覆盖同名的文件，如果能在后面加上(2)，(3)就好了，多谢了

**Comment by WooLawRen** [comment]
抱歉，可能不是覆盖，而是因为已经存在同名文件就跳过了吧，不太清楚，不过像iqiyi的视频是不是没法一开始就得到视频的大小啊，那样的话，看来还是得改文件名吧，不然没法分辨两个同名的文件吧。

**Comment by rosynirvana** [comment]
如果有人要修这里，应该是在processor/ffmpeg.py，ffmpeg -y会直接覆盖，在调用ffmpeg前检查文件是否存在即可

**Comment by rosynirvana** [comment]
close via #1895
