### ISSUE TITLE
bilibili会下载两种清晰度的视频

### ISSUE THREAD

**Issue by 7654** [soimort/you-get#1897]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get http://www.bilibili.com/video/av9954010/
Site:       bilibili.com
Title:      【西瓜新】一个小小的八音盒【有一点花絮】
Type:       Flash video (video/x-flv)
Size:       41.05 MiB (43044992 Bytes)

Downloading 【西瓜新】一个小小的八音盒【有一点花絮】.flv ...
24.4% ( 10.0/ 41.1MB) ├██████████───────────────────────────────┤[1/1]    3 MB/s
Site:       bilibili.com
Title:      【西瓜新】一个小小的八音盒【有一点花絮】
Type:       Flash video (video/x-flv)
Size:       41.05 MiB (43044992 Bytes)

Downloading 【西瓜新】一个小小的八音盒【有一点花絮】.flv ...
48.7% ( 20.0/ 41.1MB) ├████████████████████─────────────────────┤[1/1]    4 MB/s
Site:       bilibili.com
Title:      【西瓜新】一个小小的八音盒【有一点花絮】
Type:       MPEG-4 video (video/mp4)
Size:       25.6 MiB (26847580 Bytes)

Downloading 【西瓜新】一个小小的八音盒【有一点花絮】.mp4 ...
39.1% ( 10.0/ 25.6MB) ├████████████████─────────────────────────┤[1/1]    5 MB/s
Site:       bilibili.com
Title:      【西瓜新】一个小小的八音盒【有一点花絮】
Type:       MPEG-4 video (video/mp4)
Size:       25.6 MiB (26847580 Bytes)

Downloading 【西瓜新】一个小小的八音盒【有一点花絮】.mp4 ...
78.1% ( 20.0/ 25.6MB) ├████████████████████████████████─────────┤[1/1]    6 MB/s
Site:       bilibili.com
Title:      【西瓜新】一个小小的八音盒【有一点花絮】
Type:       Flash video (video/x-flv)
Size:       41.05 MiB (43044992 Bytes)

Downloading 【西瓜新】一个小小的八音盒【有一点花絮】.flv ...
73.1% ( 30.0/ 41.1MB) ├██████████████████████████████───────────┤[1/1]    3 MB/s
Site:       bilibili.com
Title:      【西瓜新】一个小小的八音盒【有一点花絮】
Type:       Flash video (video/x-flv)
Size:       41.05 MiB (43044992 Bytes)

Downloading 【西瓜新】一个小小的八音盒【有一点花絮】.flv ...
97.4% ( 40.0/ 41.1MB) ├████████████████████████████████████████─┤[1/1]    5 MB/s
Site:       bilibili.com
Title:      【西瓜新】一个小小的八音盒【有一点花絮】
Type:       Flash video (video/x-flv)
Size:       41.05 MiB (43044992 Bytes)

Downloading 【西瓜新】一个小小的八音盒【有一点花絮】.flv ...
 100% ( 41.1/ 41.1MB) ├█████████████████████████████████████████┤[1/1]   10 MB/s

Downloading 【西瓜新】一个小小的八音盒【有一点花絮】.xml ...
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> 自从B站有限速，you-get每隔10M重新下载，有时会遇到超清flv格式和mp4高清格式轮流下载，谁先下载OK完全靠运气，不得不删掉其中一个，或者Ctrl+C 中断高清下载
> [OR HAVE SOME :icecream:!]

**Comment by rosynirvana** [comment]
还是放这里了 #1698
