### ISSUE TITLE
微博中的视频，主要是秒拍的，抓不了

### ISSUE THREAD

**Issue by maris205** [soimort/you-get#1900]
sina微博中的视频，类似
http://weibo.com/tv/v/d052ec5abf86de2354f8ac21f1defe88?fid=1034:d052ec5abf86de2354f8ac21f1defe88
抓不了，好像是认证问题，用cookie也不行

**Comment by rosynirvana** [comment]
#1901

**Comment by maris205** [comment]
sina微博中，有一部分视频，像热门视频中的，链接形式如：http://weibo.com/tv/v/EFubDmaTJ
没有fid的，这些还有问题

**Comment by rosynirvana** [comment]
点回weibo再点秒拍视频就有了
这种死活想让你登录的网站无从下手
