### ISSUE TITLE
a problem about v.qq.com (部分腾讯视频地址无法解析）

### ISSUE THREAD

**Issue by 1203813323** [soimort/you-get#1902]
[DEBUG] get_html: http://v.qq.com/x/cover/ipmc5u3dwb48mv2/x0021fdkqsu.html
[DEBUG] get_response: http://v.qq.com/x/cover/ipmc5u3dwb48mv2/x0021fdkqsu.html
[DEBUG] get_html: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=x0021fdkqsu
[DEBUG] get_response: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=x0021fdkqsu
[DEBUG] get_html: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10209&vid=x0021fdkqsu&filename=x0021fdkqsu.p209.1.mp4
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10209&vid=x0021fdkqsu&filename=x0021fdkqsu.p209.1.mp4
[DEBUG] url_info: http://vhotlx.video.qq.com/flv/7/42/x0021fdkqsu.p209.1.mp4?vkey=21406BFAA6D90B850E9AD98CEF3247BD13CAEE59E1CFB1C309EFCE9C9D040A29CA1AC374787CA6935F137BB68ECFE7D6F0F5960EE6DFBB8DE7942F5BFAFA2BADA29299813DAC4391BBE47D498D8E28B83657731303757642D48D182B275427BE
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/x/cover/ipmc5u3dwb48mv2/x0021fdkqsu.html']
Traceback (most recent call last):
  File "G:\you-get-master\you-get.py", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "G:\you-get-master/src\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "G:\you-get-master/src\you_get\common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "G:\you-get-master/src\you_get\common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "G:\you-get-master/src\you_get\common.py", line 1158, in download_main
    download(url, **kwargs)
  File "G:\you-get-master/src\you_get\common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "G:\you-get-master/src\you_get\extractors\qq.py", line 158, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "G:\you-get-master/src\you_get\extractors\qq.py", line 57, in qq_download_by_vid
    print_info(site_info, parts_ti, ext, total_size)
UnboundLocalError: local variable 'ext' referenced before assignment

**Comment by dkl3** [comment]
https://github.com/soimort/you-get/issues/1908

In addition, this happens when I try to download QQ videos. I just realized that this also happens when I do v.qq.com videos individually.

**Comment by rosynirvana** [comment]
```
$ ./you-get -i 'http://v.qq.com/x/cover/ipmc5u3dwb48mv2/x0021fdkqsu.html'
Site:       QQ.com
Title:      武庚纪_06
Type:       MPEG-4 video (video/mp4)
Size:       325.75 MiB (341574725 Bytes)
```
