### ISSUE TITLE
you-get -O works not as expected

### ISSUE THREAD

**Issue by liudanking** [soimort/you-get#1912]
I like `you-get -O` option.
But after I update to 0.4.715, `you-get -O` save file to another file name.
For example:

`you-get -O test.mp4 'http://v.youku.com/v_show/id_XMjY0OTk1Mjc4NA==.html'`

What I want is saving youku video to `test.mp4`, what I get is saving the video to `test.mp4.flv`.

**Comment by rosynirvana** [comment]
#1836
#1886

Incorrect ext names could confuse the players.  You can rename the file after downloading if you really want to override them.
