### ISSUE TITLE
iqiyi can't download

### ISSUE THREAD

**Issue by dajbd** [soimort/you-get#1918]
http://www.iqiyi.com/v_19rrazgc64.html

windows 7 64bit
cmd:
you-get.exe http://www.iqiyi.com/v_19rrazgc64.html

result:
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

you-get: [error] oops, something went wrong.

**Comment by rosynirvana** [comment]
是不是没装ffmpeg

**Comment by dajbd** [comment]
Got it.
I installed ffmpeg now, it work now.
thank you.

**Comment by cnbeining** [comment]
Closed due to issue solved.
