### ISSUE TITLE
B站视频下载一段时间后，显示正常的下载速度，但是下载文件的的字节没有增加。十几分钟之后就是几百B/S

### ISSUE THREAD

**Issue by skyuniv** [soimort/you-get#1919]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
URL  http://www.bilibili.com/video/av8994940/index_1.html
DEBUG  >you-get --debug http://www.bilibili.com/video/av8994940/index_1.html
[DEBUG] get_content: http://www.bilibili.com/video/av8994940/index_1.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=14851399&from=miniplay&player=1&sign=125cc252d2bcc30079b850ac71b79503
Site:       bilibili.com
Title:      1、1-1 课程介绍_Course Introduction
Type:       Flash video (video/x-flv)
Size:       40.8 MiB (42778098 Bytes)

Downloading 1、1-1 课程介绍_Course Introduction.flv ...
 0.0% (  0.0/ 40.8MB) ├──────────────────────────── 0.6% (  0.2/ 40.8MB) ├──────────────────────────── 1.2% (  0.5/ 40.8MB) ├█─────────────────────────── 1.8% (  0.8/ 40.8MB) ├█─────────────────────────── 2.5% (  1.0/ 40.8MB) ├█─────────────────────────── 3.1% (  1.2/ 40.8MB) ├██────────────────────────── 3.7% (  1.5/ 40.8MB) ├██────────────────────────── 4.3% (  1.8/ 40.8MB) ├██────────────────────────── 4.9% (  2.0/ 40.8MB) ├██────────────────────────── 5.5% (  2.2/ 40.8MB) ├███───────────────────────── 6.1% (  2.5/ 40.8MB) ├███───────────────────────── 6.7% (  2.8/ 40.8MB) ├███───────────────────────── 7.4% (  3.0/ 40.8MB) ├███───────────────────────── 8.0% (  3.2/ 40.8MB) ├████──────────────────────── 8.6% (  3.5/ 40.8MB) ├████──────────────────────── 9.2% (  3.8/ 40.8MB) ├████──────────────────────── 9.8% (  4.0/ 40.8MB) ├████────────────────────────10.4% (  4.2/ 40.8MB) ├█████───────────────────────11.0% (  4.5/ 40.8MB) ├█████───────────────────────11.6% (  4.8/ 40.8MB) ├█████───────────────────────12.3% (  5.0/ 40.8MB) ├█████────────────────────────────────────┤[1/2]    1 MB/s
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [[您的内容]]
这种现象在B站上我测试过3个视频下载，都是出现了这种问题，并且同一视频出现这种现象的时间也不相同。
> [舔 :icecream:!]

**Comment by Zhenyu-Yang** [comment]
@skyuniv B站下载的请求头中，需要加个Referer=http://www.bilibili.com/video/av8994940/index_1.html
否则下载速度就会被限制。
你可以使用you-get -u http://www.bilibili.com/video/av8994940/index_1.html 来获取B站的实际下载地址，是个数组。然后自己发送http请求，获取视频的body，在请求的时候，记得请求头中添加Referer属性，值就是你要下载的视频播放页地址。最后如果有多个视频地址，用ffmpeg合并下就好了。

**Comment by rosynirvana** [comment]
这是哪个版本，现在遇到严重限速会整个重新解析的，当然个人比较推荐用 #1698 不会出重新解析的问题

另外，突然发现
'http://interface.bilibili.com/playurl**?&**cid='

**Comment by skyuniv** [comment]
我用的是0.4.593.
多谢你的回复，抱歉之前没有看到[#1698](https://github.com/soimort/you-get/pull/1698)的问题。
现在升级到最新版本问题就解决了。
多谢。
