### ISSUE TITLE
爱奇艺视频下载视频

### ISSUE THREAD

**Issue by yangaowei** [soimort/you-get#1920]
python3 you-get --debug http://www.iqiyi.com/v_19rrgy4y1w.html

   assert info['code'] == 'A00000', 'can\'t play this video'
AssertionError: can't play this video

**Comment by rosynirvana** [comment]
```
platforms":["PHONE","PAD","PC","PC_APP","PHONE_WEB_IQIYI","PAD_WEB_IQIYI"]
```

没TV，所以现在的接口拿不到

**Comment by yangaowei** [comment]
@rosynirvana   没Tv  是什么意思

**Comment by rosynirvana** [comment]
现在用的接口是爱奇艺TV应用的接口，这个视频在爱奇艺TV上没有，所以就访问不到

**Comment by dajbd** [comment]
https://github.com/EvilCult/Video-Downloader 这款下载器好像不错。 iqiyi 也能解析出地址。

**Comment by rosynirvana** [comment]
in favor of #1861
