### ISSUE TITLE
iqiyi 下载速度、与视频格式问题

### ISSUE THREAD

**Issue by dajbd** [soimort/you-get#1923]
我有时候下载速度是1MB/s，有时候下载却是 200KB/s。
能优化吗？
谢谢你们。

iqiyi 下载，感觉没有 youku 这些稳定。
不知道问题是 ffmpeg 的问题，还是下载的问题，或者是服务端被限速？

另外，提一下另一款下载器，
https://github.com/EvilCult/Video-Downloader
他解析出的下载路径，拿着迅雷去下载，速度是：1MB/s。
下载得到的格式是 .TS ，能否借鉴一下这款软件？
我主要的想法，还是希望优化 you get 的下载速度，200KB 的速度不太够。

辛苦你们了。
谢谢。

**Comment by rosynirvana** [comment]
ffmpeg直接抓m3u8的时长就是视频的时长，40分钟的视频需要40分钟
改进要等人愿意写一个独立的m3u8处理器了

**Comment by cnbeining** [comment]
再次重申一下我对ffmpeg解析器的态度：

如果你的确需要ffmpeg对，例如，加密M3U进行处理，那么用就是了；

如果你不真正需要ffmpeg，手写个M3U解析也没什么大不了的。

**Comment by dajbd** [comment]
https://github.com/EvilCult/Video-Downloader ，这款下载器是否有借鉴意义？
他下载出来的东西是分段的，每段都是 .ts 文件。
也是能播放的。
我不懂视频这块，额……
还请大神分析。
他解析出的地址，拿着地址下载真的好快。

**Comment by cnbeining** [comment]
除非用户指定 我们默认用户需要完整合并后的文件 而不是单个分段。

**Comment by rosynirvana** [comment]
@dajbd

iqiyi的视频是m3u8，m3u8是一个纯文本，里面有视频文件分片的url，你说的ts就是直接把m3u8中的url拿出来了。

处理iqiyi这种不加密的m3u8其实很简单，只是暂时没人愿意去写。

**Comment by cnbeining** [comment]
这涉及到是不是要加一个M3U的依赖。改动较大，所以慎重，

**Comment by skywang00** [comment]
其实能拿到M3U8就可以了，有很多软件可以导入M3U8列表后自动下载合并的

**Comment by zoubei** [comment]
我发现把ffmpeg的-re(在ffmpeg.py中)参数去掉，下载爱奇艺的速度就和youtube-dl一样飞快了，最后下载的文件没发现有问题，请问这样处理是正确的，当初为什么要加-re参数？

**Comment by rosynirvana** [comment]
#2082
