### ISSUE TITLE
为什么优酷的vip收费视频下载不了了，之前还可以下载的？

### ISSUE THREAD

**Issue by sd6644773** [soimort/you-get#1927]
原来下载视频可以下载完整的，现在只能下载官网看的前十分钟就自己停了，然后自动合成，合成完一看只有试看的十分钟，文件大小也根原文件不一样

**Comment by nhpok** [comment]
这两天是下载不了，例如这两个链接：http://v.youku.com/v_show/id_XMjc1MjI3OTc0OA==.html

http://v.youku.com/v_show/id_XMjc0NDU4OTMyOA==.html

**Comment by rosynirvana** [comment]
outdated
