### ISSUE TITLE
Tudou

### ISSUE THREAD

**Issue by Ere-Eye** [soimort/you-get#1935]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get-0.4.715-win32.exe --debug http://video.tudou.com/v/XMjc0NDMwMTgxMg==.html
[DEBUG] get_decoded_html: http://video.tudou.com/v/XMjc0NDMwMTgxMg==.html
[DEBUG] get_response: http://video.tudou.com/v/XMjc0NDMwMTgxMg==.html
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://video.tudou.com/v/XMjc0NDMwMTgxMg==.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1429, in main
  File "src\you_get\common.py", line 1342, in script_main
  File "src\you_get\common.py", line 1158, in download_main
  File "src\you_get\common.py", line 1422, in any_download
  File "src\you_get\extractors\tudou.py", line 47, in tudou_download
AttributeError: 'NoneType' object has no attribute 'replace'
you-get returned -1
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> I've seen some open issues about Tudou but they're either in Chinese or posted when there wasn't a new UI and changes to Tudou. I couldn't find similarity in the debug logs with those either.

**Comment by Ere-Eye** [comment]
`抱歉，因版权原因无法观看此视频`

Bot, you're drunk.

**Comment by rosynirvana** [comment]
抓title的问题在develop branch里修正了
版权问题类似于 #1847 ，土豆用的不是ct10 ct12的接口
要重构```youku.py```

**Comment by Ere-Eye** [comment]
@rosynirvana 可是我看不懂呀…… 有没有英文的？

**Comment by rosynirvana** [comment]
@Ere-Eye 
Bug you runned into has been fixed in the ```develop``` branch with pull requests #1708. But that's probably not what you need.

Current impl tries to fetch tudou video with youku api ```ct10 ct12```, which doesn't work for some Tudou videos. To fix this, ```youku.py``` must be refactored.

In short, I've some ideas about how to fix but refactoring ```youku.py``` must come first.

**Comment by Ere-Eye** [comment]
@rosynirvana Thank you.
