### ISSUE TITLE
开个贴，就问//japanhub.net/怎么下。试过，能看不能下！

### ISSUE THREAD

**Issue by johncc007** [soimort/you-get#1936]
1、打开一个视频进行播放，使用 you-get -o 直接粘贴地址，不行，下载不了。
2、打开一个视频进行播放，右键-检查-network-F5-得到一个timer地址（当然这个地址直接you-get也下不了）-copy as a link-用IDM下载这个地址（没速度）-在IDM手动停止下载-右键刷新下载地址-得到一个只带播放控件窗口的网页-复制这个网页的地址（这个地址很奇怪，直接右键另存为可以下载，但是一般下了50~60MB之间就停止下载了，试了很多变都这样）- you-get -o - 哒哒 ，还是下载不了！！！！！

大大！帮帮！

**Comment by johncc007** [comment]
http://japanhub.net/

**Comment by johncc007** [comment]
C:\Users\hu2n>you-get -o G:/123 http://144.217.70.227:8089/v3/6dd61d494753f79053
79184e852a443b.mp4?st=WDO8gAMdUDMUhqhnBTdqQg&e=1494001004
Site:       217.70.227:8089
Title:      6dd61d494753f7905379184e852a443b
Type:       Unknown type (mp4?st=wdo8gamdudmuhqhnbtdqqg)
Size:       207.74 MiB (217833230 Bytes)

Downloading 6dd61d494753f7905379184e852a443b.mp4?st=WDO8gAMdUDMUhqhnBTdqQg ...
 0.0% (  0.0/207.7MB) ├────────────────────────────
─────────────┤[1/1] you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
'e' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by 280634157** [comment]
你的QQ多少我加你 交流
