### ISSUE TITLE
bugs in common.py

### ISSUE THREAD

**Issue by rosynirvana** [soimort/you-get#1942]
```py
def url_save(url, filepath, bar, refer = None, is_part = False, faker = False, headers = {}, timeout = None, **kwargs):
    file_size = url_size(url, faker = faker, headers = headers)
```

If refer is set, it will be ignored in calling url_size.

**Comment by soimort** [comment]
`url_size()` doesn't take `refer` as a parameter. I guess 683a475904e373db9b04d2a06d595a1818d5bbb0 is responsible for this...
