### ISSUE TITLE
爱奇艺下载30分钟后停止

### ISSUE THREAD

**Issue by xyuanmu** [soimort/you-get#1948]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.

- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 爱奇艺视频每次只能下载30分钟，然后就卡住不动，换了好几个版本的ffmpeg都是如此，请问要如何解决？
![20170507085209](https://cloud.githubusercontent.com/assets/12442896/25777036/d12ed0fc-3302-11e7-9b9b-9a99dedda1b9.png)

**Comment by rosynirvana** [comment]
请给链接
请不要截图

**Comment by xyuanmu** [comment]
@rosynirvana 奔跑吧，所有的视频都是30分钟就不动了，截图里的是第三年期的：http://www.iqiyi.com/v_19rrb063r8.html

**Comment by rosynirvana** [comment]
重复不了, ffmpeg 3.2.4

**Comment by rosynirvana** [comment]
然后在75min左右停了
看来爱奇艺必须要有不用ffmpeg的方法了

**Comment by rosynirvana** [comment]
大概知道testing里面的失败例子怎么来的了

爱奇艺换分片有时候不标```EXT-X-DISCONTINUITY```，这合不合标准不知道，但总感觉不太对

**Comment by rosynirvana** [comment]
@xyuanmu 
可以考虑试验这个branch
https://github.com/rosynirvana/you-get/tree/iqiyi_testing

**Comment by cnbeining** [comment]
如果不需要AES 就直接抓分片link 还简单。

2017年5月7日 下午1:14，"rosynirvana" <notifications@github.com>写道：

**Comment by xyuanmu** [comment]
@rosynirvana 用你那个分支可以正常下载了，第一次下载的时候不知道出现什么问题，下载02就是第三段视频的时候文件一直增大可是却没有完成下载，所以下载的时候会出现已经100%还是继续下载，强制终止后打开02那段视频只能播放2分钟。第二次下载就正常了，但是合并时出现Unsafe file name ... Operation not permitted，按网上的方法添加 -safe 0 成功合并，谢谢！
第一次失败的截图：
![20170508200424](https://cloud.githubusercontent.com/assets/12442896/25803609/4264c7ae-342a-11e7-99ec-afab38e9c3d3.png)

**Comment by rosynirvana** [comment]
你看那句提示
> It seems that your ffmpeg is a nightly build.
> Please switch to the latest stable if merging failed.

nightly build不好判断版本所以默认当成老版本，不用新特性

**Comment by xyuanmu** [comment]
@rosynirvana 原来如此，谢谢解答

**Comment by xyuanmu** [comment]
@rosynirvana 我将ffmpeg.py第30行改成 version = [9, 0]，暂时先用着，这个分支不错 :thumbsup:。
