### ISSUE TITLE
通过iqiyi HTML5可免VIP获取1080P视频资源F4V

### ISSUE THREAD

**Issue by skywang00** [soimort/you-get#1953]
chrome 58配合脚本 （https://greasyfork.org/zh-CN/scripts/28356-iqiyi-player-switch） ，  可以直接解析得到iqiyi的1080P资源

> 简述：爱奇艺flash播放器与html5播放器随意切换，html5播放器广告和谐与免vip看1080p、4k。

you-get可以考虑使用这种方式获取iqiyi 1 080P资源

**Comment by skywang00** [comment]
目前iqiyi对于chrome 58会直接默认启用HTML5替代Flash，但没有这个脚本的情况下非VIP还是只能看720P的，而且解析速度很慢...

**Comment by rosynirvana** [comment]
Iqiyi's algo is not hard to reserve at all. Much easier than youku or bilibili, let along tecent.
But they have a reputation of being quite agreesive on DMCA issues.

**Comment by redstoneleo** [comment]
@rosynirvana 要是你能解析你提到的那些站的VIP的话我每月至少愿意捐赠你20元：）

**Comment by rosynirvana** [comment]
：）
But if you mean downloading already paid item in bilibili, just bypass web browser or their client. I believe I've already done that.

**Comment by redstoneleo** [comment]
@rosynirvana 我是说国内那些主流站的VIP，不只是bilibili

**Comment by rosynirvana** [comment]
#2117
