### ISSUE TITLE
README.md 中的 Option 4: Download from GitHub 应该修改下了吧

### ISSUE THREAD

**Issue by skywang00** [soimort/you-get#1954]
README.md 似乎应该更新了

我在win10 x64上安装了python 3.6.1 x32
尝试使用`Option 4: Download from GitHub` 安装you-get时，发现python3 开头的命令行全部无效，使用python就一切正常了
> https://github.com/soimort/you-get#option-4-download-from-github

> PS C:\Users\XXX> python -h
usage: C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\python.exe [option] ... [-c cmd | -m mod | file | -] [arg]
 ...
Options and arguments (and corresponding environment variables):
-b     : issue warnings about str(bytes_instance), str(bytearray_instance)
         and comparing bytes/bytearray with str. (-bb: issue errors)
-B     : don't write .py[co] files on import; also PYTHONDONTWRITEBYTECODE=x
-c cmd : program passed in as string (terminates option list)
-d     : debug output from parser; also PYTHONDEBUG=x
-E     : ignore PYTHON* environment variables (such as PYTHONPATH)
-h     : print this help message and exit (also --help)
-i     : inspect interactively after running script; forces a prompt even
         if stdin does not appear to be a terminal; also PYTHONINSPECT=x
-I     : isolate Python from the user's environment (implies -E and -s)
-m mod : run library module as a script (terminates option list)
-O     : optimize generated bytecode slightly; also PYTHONOPTIMIZE=x
-OO    : remove doc-strings in addition to the -O optimizations
-q     : don't print version and copyright messages on interactive startup
-s     : don't add user site directory to sys.path; also PYTHONNOUSERSITE
-S     : don't imply 'import site' on initialization
-u     : unbuffered binary stdout and stderr, stdin always buffered;
         also PYTHONUNBUFFERED=x
         see man page for details on internal buffering relating to '-u'
-v     : verbose (trace import statements); also PYTHONVERBOSE=x
         can be supplied multiple times to increase verbosity
-V     : print the Python version number and exit (also --version)
         when given twice, print more information about the build
-W arg : warning control; arg is action:message:category:module:lineno
         also PYTHONWARNINGS=arg
-x     : skip first line of source, allowing use of non-Unix forms of #!cmd
-X opt : set implementation-specific option
file   : program read from script file
      : program read from stdin (default; interactive mode if a tty)
arg  : arguments passed to program in sys.argv[1:]
Other environment variables:
PYTHONSTARTUP: file executed on interactive startup (no default)
PYTHONPATH   : ';'-separated list of directories prefixed to the
               default module search path.  The result is sys.path.
PYTHONHOME   : alternate <prefix> directory (or <prefix>;<exec_prefix>).
               The default module search path uses <prefix>\lib.
PYTHONCASEOK : ignore case in 'import' statements (Windows).
PYTHONIOENCODING: Encoding[:errors] used for stdin/stdout/stderr.
PYTHONFAULTHANDLER: dump the Python traceback on fatal errors.
PYTHONHASHSEED: if this variable is set to 'random', a random value is used
   to seed the hashes of str, bytes and datetime objects.  It can also be
   set to an integer in the range [0,4294967295] to get hash values with a
   predictable seed.
PYTHONMALLOC: set the Python memory allocators and/or install debug hooks
   on Python memory allocators. Use PYTHONMALLOC=debug to install debug
   hooks.

> PS C:\Users\XXX> python3 -h
python3 : 无法将“python3”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路
径正确，然后再试一次。
所在位置 行:1 字符: 1
 python3 -h
    CategoryInfo          : ObjectNotFound: (python3:String) [], CommandNotFoundException
     FullyQualifiedErrorId : CommandNotFoundException

**Comment by skywang00** [comment]
使用cmd也是一样的结果 

> Microsoft Windows [版本 10.0.15063]
(c) 2017 Microsoft Corporation。保留所有权利。
C:\Users\XXX>python -V
Python 3.6.1
C:\Users\XXX>python3 -V
'python3' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by rosynirvana** [comment]
你要知道这项目活跃的开发者应该是没有用windows的……

**Comment by skywang00** [comment]
我想的是，是否Python 3.6之后就统一使用python命令，不支持python3命令了....

**Comment by skywang00** [comment]
@rosynirvana 
pip不能自己改extractors再安装了呀，而且pip上应该是stable 版，不是dev版吧

**Comment by rosynirvana** [comment]
一般的环境下python是mapping到python2，python3 mapping到python3，这个不会轻易改的。
至于win安装包具体怎么设置这个不知道。

页面上对于升级到develop branch的说明是
> In order to get the latest develop branch without messing up the PIP, you can try:

> ```$ pip3 install --upgrade git+https://github.com/soimort/you-get@develop```

**Comment by j16180339887** [comment]
> $ pip3 install --upgrade git+https://github.com/soimort/you-get@develop

比較大的專案，從 zip 安裝會比 git 快一些
`$ pip install --upgrade https://github.com/soimort/you-get/archive/develop.zip`

**Comment by skywang00** [comment]
@j16180339887 
看你给的命令，从zip安装的话就不需要安装git了？

**Comment by j16180339887** [comment]
應該是吧，不過這年頭誰會不裝 git 呢
