### ISSUE TITLE
'spm' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by mumuxizzz** [soimort/you-get#1960]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:
>you-get -i --debug http://v.youku.com/v_show/id_XMTU4MzIwMjE2OA==.html?from=s1.
8-1-1.2&spm=a2h0k.8191407.0.0
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTU4MzIwMjE2OA==&c
t=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTU4MzIwMjE2OA==&c
t=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049438184633012490
2ec_00/st/mp4/fileid/03000802005744FD9A9D563067583410EEDC05-F7AD-8C47-B10A-345FA
DF63EF7?ctype=12&oip=1897556702&ev=1&K=e193f85515a31e11282c568e%26sign%3D824bffe
7f6f05ce8f929e7ea7873f32f&yxon=1&ep=ciadHkqFV8YE4yDciD8bYyXidiJcXP4J9h%2BFidJgAL
shT%2By770rYtpTES%2FlBFv8edyoFFOrx3qWTGUARYYZE2BwQ1z2sPvqS%2F%2FCS5a5XweZxEm8wcb
ihs1SeRjD1&token=0504
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/049438184633012490
2ec_00/st/mp4/fileid/03000802015744FD9A9D563067583410EEDC05-F7AD-8C47-B10A-345FA
DF63EF7?ctype=12&oip=1897556702&ev=1&K=791b60509e647c4b24130086%26sign%3D3d0acc8
8a6e3ae664df8b2ce90a65ee7&yxon=1&ep=ciadHkqFV8YE4yDciD8bYyXidiJcXP4J9h%2BFidJgAL
ohT%2By770rYtpTES%2FlBFv8edyoFFOrx3qWTGUARYYZE2BwQ1z2sPvqS%2F%2FCS5a5XweZxEm8wcb
ihs1SeRjD1&token=0504
site:                优酷 (Youku)
title:               畅游中原：历史文化名城—商丘古城
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          47.8 MiB (50070753 bytes)
    # download-with: you-get --format=mp4 [URL]

    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          23.7 MiB (24856059 bytes)
    # download-with: you-get --format=flvhd [URL]

'spm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
```you-get -i --debug "http://v.youku.com/v_show/id_XMTU4MzIwMjE2OA==.html?from=s1.
8-1-1.2&spm=a2h0k.8191407.0.0" ```
或者手动去掉不必要的
```you-get -i --debug http://v.youku.com/v_show/id_XMTU4MzIwMjE2OA==.html```

**Comment by cnbeining** [comment]
You need to quote the URL.
