### ISSUE TITLE
you-get 问题 运力了之后发现 -bash: you-get: command not found 想问问 怎么解决

### ISSUE THREAD

**Issue by Ritahong** [soimort/you-get#1963]
RT

**Comment by cnbeining** [comment]
请提供详细安装方法和平台。

**Comment by Ritahong** [comment]
我是用python3安装的 装的是mac ox版本 下载了python3之后 在桌面安装 接着打开终端 安装you-get 但是提示我用的是python 6.0版本 希望我提升到9.0 我就输入 pip3 --upgrade 升级 接着安装了you-get 但由于之前安装过 便显示所需请求已存在 就无法安装 接着输入 you-get 都显示-bash: you-get: command not found

**Comment by rosynirvana** [comment]
可能性最大的还是你搞错安装账户了……

试试下面三条命令，看输出是什么
```
pip3 show you-get
echo $PATH | tr ':' '\n'
which you-get
```
注意账户

**Comment by Ritahong** [comment]
weiliqideMacBook-Pro:~ weiliqi$ pip3 show you-get
Name: you-get
Version: 0.4.715
Summary: Dumb downloader that scrapes the web
Home-page: https://you-get.org/
Author: Mort Yao
Author-email: mort.yao@gmail.com
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: 
weiliqideMacBook-Pro:~ weiliqi$ echo $PATH | tr ':' '\n'
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
输入which you-get发现没有反映

**Comment by rosynirvana** [comment]
```grep 'you-get' /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get-0.4.715.dist-info/RECORD```
输出是？

**Comment by Ritahong** [comment]
weiliqideMacBook-Pro:~ weiliqi$ grep 'you-get' /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get-0.4.715.dist-info/RECORD
../../../bin/you-get,sha256=OcC_cp3HBGfQ2QhBo31hDdbUMT9EzvVSaSNHpnKXNIM,266 是这个吗

**Comment by rosynirvana** [comment]
那```/Library/Frameworks/Python.framework/Versions/3.6/bin```下面有you-get这个文件吗？

**Comment by Ritahong** [comment]
有哦 找到了 有you-get这个文件

**Comment by rosynirvana** [comment]
那把```/Library/Frameworks/Python.framework/Versions/3.6/bin```加入到PATH里试试？参考
http://osxdaily.com/2014/08/14/add-new-path-to-path-command-line/

**Comment by Ritahong** [comment]
!!! 可以用了 感恩啊～
