### ISSUE TITLE
python -m you_get --debug

### ISSUE THREAD

**Issue by erlinux** [soimort/you-get#1971]
为啥python -m运行会报错？

C:\Users\rabbit>python -m you_get --debug
C:\Users\rabbit\AppData\Local\Programs\Python\Python36-32\lib\runpy.py:125: Runt
imeWarning: 'you_get.__main__' found in sys.modules after import of package 'you
_get', but prior to execution of 'you_get.__main__'; this may result in unpredic
table behaviour
  warn(RuntimeWarning(msg))
Usage: you-get [OPTION]... [URL]...

Startup options:
    -V | --version                      Print version and exit.
    -h | --help                         Print help and exit.

Dry-run options: (no actual downloading)
    -i | --info                         Print extracted information.
    -u | --url                          Print extracted information with URLs.
         --json                         Print extracted URLs in JSON format.

Download options:
    -n | --no-merge                     Do not merge video parts.
         --no-caption                   Do not download captions.
                                        (subtitles, lyrics, danmaku, ...)
    -f | --force                        Force overwriting existed files.
    -F | --format <STREAM_ID>           Set video format to STREAM_ID.
    -O | --output-filename <FILE>       Set output filename.
    -o | --output-dir <PATH>            Set output directory.
    -p | --player <PLAYER [OPTIONS]>    Stream extracted URL to a PLAYER.
    -c | --cookies <COOKIES_FILE>       Load cookies.txt or cookies.sqlite.
    -x | --http-proxy <HOST:PORT>       Use an HTTP proxy for downloading.
    -y | --extractor-proxy <HOST:PORT>  Use an HTTP proxy for extracting only.
         --no-proxy                     Never use a proxy.
    -s | --socks-proxy <HOST:PORT>      Use an SOCKS5 proxy for downloading.
    -t | --timeout <SECONDS>            Set socket timeout.
    -d | --debug                        Show traceback and other debug info.

**Comment by rosynirvana** [comment]
用-m要达到什么目的？
