### ISSUE TITLE
b站付费视频加载了火狐浏览器cookies.txt仍然无法下载

### ISSUE THREAD

**Issue by 614567264** [soimort/you-get#1974]
http://bangumi.bilibili.com/anime/6023/play#103087  我的账号已经买了这个番   但是用提取的cookies文件仍然无法下载   但是用这个cookies文件可以下载优酷的付费视频   显示错误的代码跟没加载cookies文件的代码一模一样  这个cookies不支持b站还是代码输错了   求大神帮忙看看

C:\Users\zheng\Desktop\you-get>C:\Users\zheng\Desktop\you-get\you-get.exe -c C:\
Users\zheng\Desktop\you-get\cookies.txt http://bangumi.bilibili.com/anime/6023/p
lay#103087
Site:       bilibili.com
Title:      霹雳天命之仙魔鏖锋Ⅱ斩魔录 [103087]
Type:       Unknown type ()
Size:       0.0 MiB (0 Bytes)

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
[cookies.txt](https://github.com/soimort/you-get/files/998759/cookies.txt)

**Comment by 614567264** [comment]
--debug选项是怎么操作啊？   you-get.exe --debug cookies.txt http://bangumi.bilibili.com/anime/6023/play#103087   是这样操作？  得到的是下面的输出报告

C:\Users\zheng\Desktop\you-get>C:\Users\zheng\Desktop\you-get\you-get.exe  --deb
ug -c C:\Users\zheng\Desktop\you-get\cookies.txt http://bangumi.bilibili.com/ani
me/6023/play#103087
[DEBUG] get_content: http://bangumi.bilibili.com/anime/6023/play#103087
[DEBUG] post_content: http://bangumi.bilibili.com/web_api/get_source
 post_data: {'episode_id': '103087'}
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=15709910&from=mi
niplay&player=1&sign=b399e114c671a44331e11a773677cf50
Site:       bilibili.com
Title:      霹雳天命之仙魔鏖锋Ⅱ斩魔录 [103087]
Type:       Unknown type ()
Size:       0.0 MiB (0 Bytes)

you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://bangumi.bilibili.com/anime/6023/play#103087']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1429, in main
  File "src\you_get\common.py", line 1342, in script_main
  File "src\you_get\common.py", line 1158, in download_main
  File "src\you_get\common.py", line 1422, in any_download
  File "src\you_get\extractors\bilibili.py", line 141, in bilibili_download
  File "src\you_get\extractors\bilibili.py", line 106, in bilibili_download_by_c
id
  File "src\you_get\common.py", line 763, in download_urls
AssertionError
you-get returned -1

**Comment by rosynirvana** [comment]
用你的cookies看了一眼，付费的不是现在用的这个接口，先等等吧，patch写好要点时间的

**Comment by rosynirvana** [comment]
#1698
要支持付费bangumi看来需要再加一个key进去，不然就要用js里的主key
另外这个接口还要验证cookie里的sid项

```
./you-get -i -c ~/Downloads/cookies.txt 'http://bangumi.bilibili.com/anime/6023/play#103501'
you-get: It's a paid item
Site:       bilibili.com
Title:      霹雳天命之仙魔鏖锋Ⅱ斩魔录 [4 生死交错]
Type:       Flash video (video/x-flv)
Size:       2186.83 MiB (2293055671 Bytes)
```

**Comment by 614567264** [comment]
大概要多久能下载b站付费视频?   还有百度云链接里面的视频是用什么命令行下载的?

**Comment by rosynirvana** [comment]
在#1698的commit

**Comment by 614567264** [comment]
什么意思啊？

**Comment by rosynirvana** [comment]
如果完全不明白git或别的vcs的基本概念
用这个 https://raw.githubusercontent.com/rosynirvana/you-get/fix-bilibili-redirect/src/you_get/extractors/bilibili.py

替换you_get下的同名文件

如果是打包成一个exe的就没办法了，只能按正常方式装一遍you-get然后再替换

**Comment by shikkoku** [comment]
我也试着替换了Scripts目录下的bilibili.py，不过尝试下载承包过的番还是只能下载到720p的源。cookies.tet是firefox导出的Netscape格式。不知道为什么chrome 59用那个cookies.txt扩展用不了。

**Comment by rosynirvana** [comment]
现在的patch只支持了付费的，非付费的bangumi还是老接口没改
如果想要添加支持请像楼主一样提供一个cookie和bangumi的url

现在的代码不支持chrome的Cookie （参考#1898）

**Comment by shikkoku** [comment]
[http://bangumi.bilibili.com/anime/6001/play#103887](url)
[cookies.txt](https://github.com/soimort/you-get/files/1004286/cookies.txt)

之前我是替换错路径了。我不是直接使用chorme的文件，而是想通过插件转换成Netscape格式。不过那个插件不知道为什么没有工作……只好用firefox的插件导出来。

**Comment by shikkoku** [comment]
post主那个连接我替换了bilibili.py后测试结果倒是和你的一样了。

**Comment by rosynirvana** [comment]
现在没时间写，把
```
bilibili_download_by_cid(str(cid), title, output_dir=output_dir, merge=merge, info_only=info_only, paid=paid)
```
改成
```
bilibili_download_by_cid(str(cid), title, output_dir=output_dir, merge=merge, info_only=info_only, paid=True)
```
就行了

```diff
diff --git a/src/you_get/extractors/bilibili.py b/src/you_get/extractors/bilibili.py
index 1bb3a77..96e27d4 100644
--- a/src/you_get/extractors/bilibili.py
+++ b/src/you_get/extractors/bilibili.py
@@ -218,7 +218,7 @@ def bilibili_download(url, output_dir='.', merge=True, info_only=False, **kwargs
         while ep_ids[idx] != episode_id:
             idx += 1
         title = '%s [%s %s]' % (title, idx+1, long_title)
-        bilibili_download_by_cid(str(cid), title, output_dir=output_dir, merge=merge, info_only=info_only, paid=paid)
+        bilibili_download_by_cid(str(cid), title, output_dir=output_dir, merge=merge, info_only=info_only, paid=True)

     else:
         tc_flashvars = match1(html, r'"bili-cid=\d+&bili-aid=\d+&vid=([^"]+)"')
```

但问题是必须带cookies，不然下载bangumi和movie都会报错
common.py里好像没提供什么方便的接口可以处理```Set-Cookie``的

测试
```
./you-get -di -c '~/Downloads/c.txt'  'http://bangumi.bilibili.com/anime/6001/play#103887'
[DEBUG] url_locations: http://bangumi.bilibili.com/anime/6001/play#103887
[DEBUG] get_content: http://bangumi.bilibili.com/anime/6001/play#103887
[DEBUG] get_content: http://bangumi.bilibili.com/jsonp/seasoninfo/6001.ver?callback=seasonListCallback&jsonp=jsonp&_=1494937700838
[DEBUG] post_content: http://bangumi.bilibili.com/web_api/get_source
 post_data: {'episode_id': '103887'}
[DEBUG] get_content: http://bangumi.bilibili.com/web_api/episode/103887.json
[DEBUG] get_content: http://bangumi.bilibili.com/player/web_api/playurl?cid=17479267&module=bangumi&player=1&quality=4&ts=1494937701&sign=34eb00406a911b4d3f1d839c2a5f031e
[DEBUG] url_info: http://cn-sdjn-cu-v-04.acgvideo.com/vg4/1/88/17479267-1-hd.flv?expires=1494950100&platform=pc&ssig=N-eujV-7Hp5r2G2J2DVqYA&oi=_&nfa=bis14H4eAMzDbQqu90Ft2w==&dynamic=1
Site:       bilibili.com
Title:      从零开始的魔法书 [6 十三号]
Type:       Flash video (video/x-flv)
Size:       462.23 MiB (484682246 Bytes)
```
这是一个1080p的视频，可以ffprobe抓信息
```
Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, 24.42 fps, 23.98 tbr, 1k tbn, 47.95 tbc
```

**Comment by shikkoku** [comment]
目前测试可行，期待以后有可能改进。辛苦了。

**Comment by rosynirvana** [comment]
现在#1698使用新接口访问所有bangumi内容

如果不带cookie，会试图获取一个sid
我不知道现在的实现和直接catch HTTPError然后fallback到老接口上的做法哪个更干净一点
但现在这种实现代码量估计是多一点……

**Comment by shikkoku** [comment]
几时合并到develop分支？

**Comment by rosynirvana** [comment]
这个要问作者或维护者了

**Comment by lioArthur** [comment]
关键是付费的是怎么下载的呢？只是知道用 cookies.txt  但是不知道具体怎么操作的。求解呢。

**Comment by rosynirvana** [comment]
@lioArthur 看 #1970 最后

**Comment by rosynirvana** [comment]
close via #1698
