### ISSUE TITLE
改进算法机制，不再和加密机制作斗争？

### ISSUE THREAD

**Issue by internalG** [soimort/you-get#1983]
目前的机制都需要不断的根据视频网站的版本改进python算法，而我见到好多视频聚合app是直接可以跳过各种网站的广告在客户端直接播放的。其实不管是下载还是不下载，只要客户端能够获得视频的真实地址就可以了，所以应该有种思路可以模仿浏览器的解析机制获得视频的链接，从而实现统一的解决机制。

**Comment by cnbeining** [comment]
您猜猜他们是怎么得到地址的？

不能直接吃最后一个烧饼是不是。




当然我是赞成考虑使用headless Chrome的。这应该是未来。

**Comment by rosynirvana** [comment]
总体上不会简单很多，而且大概不会存在统一的解决机制。
只是对付emscripten会变简单。

**Comment by internalG** [comment]
浏览器机器人->video tag->source url，我试试。

**Comment by cnbeining** [comment]
@internalG 这个已经有了。

**Comment by rosynirvana** [comment]
现状是国内大多数大站的好东西不会放在js里，例如优酷的```ct=12```和腾讯的多少分钟试看

**Comment by internalG** [comment]
@cnbeining url?

**Comment by internalG** [comment]
@rosynirvana 只拿免费的说，不管加密算法如何复杂，他最终返回给用户浏览器的还是一个MP4或者视频列表，真正有用的只是video tag的source url。

**Comment by fstar** [comment]
要是真那么简单就好了..... @internalG

**Comment by rosynirvana** [comment]
说的是免费视频
腾讯有不少html5只能播几分钟，但是用flash播放器可以播全部的
优酷在用```ct 10 12```接口的年代也一样

**Comment by yfang1644** [comment]
移植一个web浏览器可以终极解决，不过广告也躲不开了

**Comment by fuzhuo** [comment]
以国内视频站的风格，h5的video tag拿的src url要么限时，要么清晰度不行，广告也会有。不然直接上phantomjs模拟抓就好。大站flash版本的才会支持多清晰度选择…
在iOS上用webview打开bili多次之后似乎会被提示该视频仅在手机客户端上可用

**Comment by Cphilo** [comment]
too young too native

**Comment by internalG** [comment]
我比较关注直播视频，目前看没什么限制，而且对ios/android来说mp4是唯一选择。

**Comment by rosynirvana** [comment]
斗鱼移动端网页 960x540
现在develop branch的you-get拿到的(应该是flash的接口) 1092x614

极端一点的可以参考afreeca

mp4对于iOS或Android不是唯一选择，在直播上来说也不是主流选择，主流是m3u8切片的ts

**Comment by internalG** [comment]
进一步看了iphone上视频流的地址，乐视、cntv基本都是一个m3u8了，像下面这样，直接可以在播放器里看，清晰度不理想但对手机足够了，似乎后面还有加速地址和秘钥信息。

http://36.110.226.60/249/15/83/letv-uts/14/ver_00_22-1101139959-avc-568603-aac-48000-295496-23299270-4a377336892388a99fc9d56e5812752d-1494783714667.m3u8?crypt=47aa7f2e551&b=630&nlh=4096&nlt=60&bf=70&p2p=1&video_type=mp4&termid=2&tss=ios&platid=3&splatid=304&its=0&qos=4&fcheck=0&amltag=4701&mltag=4701&proxy=611247579,3550143194,1786224551&uid=1786271010.rp&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&ntm=1495118400&nkey=1190428caa96a6ec591671e36531682f&nkey2=b18174b550e5e52a27424e12b8fe9895&geo=CN-1-0-1&mmsid=64824523&tm=1495099865&key=acd6ada56cc6baf65d54f8fe4df99fb4&playid=0&vtype=13&cvid=278097095742&payff=0&p1=0&p2=14&ostype=macos&hwtype=un&uuid=1099865441617785&vid=29457771&errc=0&gn=1218&vrtmcd=108&buss=4701&cips=106.120.85.34

**Comment by QShen3** [comment]
分段的话只能拿到当前播放的这一段吧……

**Comment by soimort** [comment]
Duplicate of #26.
