### ISSUE TITLE
是否可以在代码中使用you-get？

### ISSUE THREAD

**Issue by DoraJDJ** [soimort/you-get#1987]
最近想弄个下载B站视频然后转码成 mp3 最后发送到 Telegram 的小程序，然后想到用 you-get 来下载视频。

不过简单看了下 README 后发现好像没有以模块的形式在代码中使用 you-get 的例子（恐怕连功能都没有弄？）。

而功能与本项目相关的 [youtube-dl 有提供在代码中直接调用的功能](https://github.com/rg3/youtube-dl#embedding-youtube-dl)，这样在进行自动化操作时会有些方便。

不知道 you-get 的开发者们能否为其提供这样的一种功能，提供一种便利？

谢谢！

**Comment by cnbeining** [comment]
这个东西一直是planned 但是一直没有人写出来。

一个办法是考虑用subprocess call一下 用```--json``` 取JSON输出 并解析。

**Comment by soimort** [comment]
See #851.
