### ISSUE TITLE
you-get 将ffmpeg x64 稳定版识别为nightly版

### ISSUE THREAD

**Issue by skywang00** [soimort/you-get#1989]
同时下载了ffmpeg x86和x64的稳定版，修改系统path为x64版ffmpeg时，you-get总是提示ffmpeg为nightly版，修改path为x86版ffmpeg时，就没有这个提示了
![default](https://cloud.githubusercontent.com/assets/25704322/26280861/91555e0a-3e16-11e7-981e-e407b7fa0622.PNG)

**Comment by rosynirvana** [comment]
看文件名这个就是nightly啊
不然在终端里输入```ffmpeg```看第一行输出的是什么

**Comment by skywang00** [comment]
又去ffmpeg官网看了下，这个确实是nightly版，我看到有个dev就想当然的以为static是稳定版了。。。

![2](https://cloud.githubusercontent.com/assets/25704322/26280907/43be8958-3e18-11e7-946f-f09ee533c107.PNG)


不过为什么 win32版的那个就不提示了

**Comment by rosynirvana** [comment]
或许是32-bit版本的输出信息不对，或许是别的什么地方搞错了
