### ISSUE TITLE
喜马拉雅，下载失败

### ISSUE THREAD

**Issue by Delectate** [soimort/you-get#1991]
win10 creator+py3+最新版you-get

> 
> >>> import sys
> >>> print(sys.version)
> 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]

> Microsoft Windows [Version 10.0.15063]
> (c) 2017 Microsoft Corporation. All rights reserved.
> 
> C:\Users\Delectate>pip install you-get
> Collecting you-get
>   Downloading you_get-0.4.715-py3-none-any.whl (167kB)
>     100% |████████████████████████████████| 174kB 348kB/s
> Installing collected packages: you-get
> Successfully installed you-get-0.4.715
> 
> C:\Users\Delectate>you-get
> Usage: you-get [OPTION]... [URL]...
> 
> Startup options:
>     -V | --version                      Print version and exit.
>     -h | --help                         Print help and exit.

浏览器可以正常播放，网络+资源没有问题。测试地址如下：
http://www.ximalaya.com/38154100/album/6232638
http://www.ximalaya.com/38154100/sound/27591063

日志如下：

> 
> C:\Users\Delectate>you-get http://www.ximalaya.com/38154100/album/6232638
> you-get: [error] oops, something went wrong.
> you-get: don't panic, c'est la vie. please try the following steps:
> you-get:   (1) Rule out any network problem.
> you-get:   (2) Make sure you-get is up-to-date.
> you-get:   (3) Check if the issue is already known, on
> you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
> you-get:         https://github.com/soimort/you-get/issues
> you-get:   (4) Run the command with '--debug' option,
> you-get:       and report this issue with the full output.
> 
> C:\Users\Delectate>you-get http://www.ximalaya.com/38154100/sound/27591063
> you-get: [error] oops, something went wrong.
> you-get: don't panic, c'est la vie. please try the following steps:
> you-get:   (1) Rule out any network problem.
> you-get:   (2) Make sure you-get is up-to-date.
> you-get:   (3) Check if the issue is already known, on
> you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
> you-get:         https://github.com/soimort/you-get/issues
> you-get:   (4) Run the command with '--debug' option,
> you-get:       and report this issue with the full output.
> 
> C:\Users\Delectate>

输出如下：

> C:\Users\Delectate>you-get --debug http://www.ximalaya.com/38154100/sound/27591063
> [DEBUG] get_content: http://www.ximalaya.com/tracks/27591063.json
> you-get: version 0.4.715, a tiny downloader that scrapes the web.
> you-get: ['http://www.ximalaya.com/38154100/sound/27591063']
> Traceback (most recent call last):
>   File "c:\python3\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\python3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Python3\Scripts\you-get.exe\__main__.py", line 9, in <module>
>   File "c:\python3\lib\site-packages\you_get\__main__.py", line 92, in main
>     main(**kwargs)
>   File "c:\python3\lib\site-packages\you_get\common.py", line 1429, in main
>     script_main('you-get', any_download, any_download_playlist, **kwargs)
>   File "c:\python3\lib\site-packages\you_get\common.py", line 1342, in script_main
>     download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
>   File "c:\python3\lib\site-packages\you_get\common.py", line 1158, in download_main
>     download(url, **kwargs)
>   File "c:\python3\lib\site-packages\you_get\common.py", line 1422, in any_download
>     m.download(url, **kwargs)
>   File "c:\python3\lib\site-packages\you_get\extractors\ximalaya.py", line 56, in ximalaya_download
>     ximalaya_download_by_id(id, output_dir = output_dir, info_only = info_only, stream_id = stream_id)
>   File "c:\python3\lib\site-packages\you_get\extractors\ximalaya.py", line 18, in ximalaya_download_by_id
>     json_data = json.loads(get_content(BASE_URL + id + '.json'))
>   File "c:\python3\lib\json\__init__.py", line 354, in loads
>     return _default_decoder.decode(s)
>   File "c:\python3\lib\json\decoder.py", line 339, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "c:\python3\lib\json\decoder.py", line 357, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> C:\Users\Delectate>

**Comment by rosynirvana** [comment]
#1956 
develop branch已经patch了
