### ISSUE TITLE
Manage referer

### ISSUE THREAD

**Issue by BobPeterson** [soimort/you-get#1992]
It's not really an issue but on vimeo player the referer is necessary to download a video. You know it because it's written on the source code [here](https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/vimeo.py#L39).

I had to modify the source code to hardcode the good referer in order to download the video. 
Is there a solution to not hardcode the referer or if not, it could be great to add an option to add it from command line. 

Thanks a lot and great work.

**Comment by rosynirvana** [comment]
I can't quite follow this.

Which page containing a vimeo player you've tried with ```you-get```?
If a referer is necessary, it should be handled automatically.

I tried [this](https://vimeo.com/105733079) vimeo video. The core part of embeded is ```"https://player.vimeo.com/video/105733079"```.  
```curl https://player.vimeo.com/video/105733079``` without a referer can fetch all we need.

**Comment by rosynirvana** [comment]
https://github.com/soimort/you-get/commit/b6b53d0d2ae01589b4197c08127fcb101a712617

now VimeoExtractor will send the ```Referer``` header if comes from embed.py
I believe the problem has been solved.
