### ISSUE TITLE
请教下爱奇艺的vip的1080P解析问题

### ISSUE THREAD

**Issue by wuchixian** [soimort/you-get#1995]
```
[C:\>you-get --debug -c C:\Users\宪\Documents\cookies.txt -i http://www.iqiyi.com/v_19rravhvks.html
[DEBUG] get_html: http://www.iqiyi.com/v_19rravhvks.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rravhvks.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/658994800/91e544b042d94220f81722570215cbcb/?t=1495395697949&sc=04e03a95cab58a4d5a443701171634dc&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               吃光全宇宙_20170420期
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
    # download-with: you-get --format=LD [URL]]
```

win系统
已买vip（不含tv版）挂了cookies还是解析不到1080P
PS：能解析到没有logo的视频吗？是不是需要接口什么的，感觉我问的问题略白痴/(ㄒoㄒ)/~~
能不能详细说说因为我连门都没摸到，平时只用you-get解析油管

> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
国内很多站点不是挂cookie就行的，```you-get```在可预见的未来会不会支持……看运气了

大多数站点的logo是压在视频里的，不是动态渲染上去的，所以大概不行，不过可以试试，下载到没logo的就算运气好

**Comment by wuchixian** [comment]
主要是我看之前有人是成功的，所以有没有具体的方法可以实现下载，按理说iqiyi应该也不算难吧
可是我也不能用下yahoo视频的方法找到m3u8

**Comment by rosynirvana** [comment]
不难啊，但是现在没人愿意去惹在版权问题上最激进的爱奇艺呗

**Comment by shikkoku** [comment]
我倒是有个付费用户才能用的批处理下载脚本……

**Comment by wuchixian** [comment]
求指路~~

**Comment by shikkoku** [comment]
@wuchixian 留下邮箱吧，如rosynirvana所说，爱奇艺官方本身就不提供版权物下载的。

**Comment by wuchixian** [comment]
@shikkoku wuchixian@qq.com，多谢

**Comment by shikkoku** [comment]
@wuchixian 检查邮件吧。

**Comment by lyrric** [comment]
@shikkoku
能发我一份么?xx20510@163.com
谢谢

**Comment by wuchixian** [comment]
@shikkoku 谢谢收到了，十分完备好用
麻烦再查收一下邮件

**Comment by batjoker** [comment]
@shikkoku 能发我一份么  jokerb6@yeah.net

**Comment by Akaishyichi** [comment]
@shikkoku  能发一份脚本吗？谢谢 tellmewhy19950606@vip.qq.com

**Comment by dcln78** [comment]
@shikkoku 麻烦可以发给我一份吗？ 844352163@qq.com  谢谢啊

**Comment by a137235** [comment]
@shikkoku 能发给我一份吗？ 651895809@qq.com 谢谢啊

**Comment by ShiGuoTao** [comment]
@shikkoku 能发给我一份吗？ 372415892@qq.com 谢谢啊

**Comment by microka** [comment]
@shikkoku 能发给我一份吗？microka@gmail.com 感谢。

**Comment by luckyzwei** [comment]
@shikkoku  能发给我一份吗？ luckyzwei@gmail.com 非常感谢

**Comment by unkleboby** [comment]
@shikkoku 还可以发我一份吗？买了vip还是无法下载爱奇艺的视频！xiezhendl@qq.com 谢谢

**Comment by benhong** [comment]
@shikkoku 可以發一份給我嗎
emset306@gmail.com
非常感謝

**Comment by evelynzl** [comment]
@shikkoku  请问可以发给我一份吗？evelzw@gmail.com 非常感谢！

**Comment by ssswang** [comment]
@shikkoku 请问可以发给我一份吗？swxyzabc@gmail.com 谢谢

**Comment by danny740211** [comment]
@shikkoku 請問可以給我一份教學嗎?? danny740211@gmail.com 謝謝您

**Comment by hnliyuan** [comment]
@shikkoku 请问可以发我一份吗？ accom@live.cn

**Comment by x28622930** [comment]
@shikkoki 能发一份么 谢谢 tinggewang@yao96.com

**Comment by rosynirvana** [comment]
in favor of #2117

**Comment by Mr-LiuDC** [comment]
@shikkoku  请问你是怎么解决的？可以分享一下吗？ mr.liudc@gmail.com 非常感谢。

**Comment by cp-yuan** [comment]
请怎么不收到此类邮件啊？ 能退出吗？


2017-08-11 10:46 GMT+08:00 Mr-LiuDC <notifications@github.com>:

**Comment by Mr-LiuDC** [comment]
@cp-yuan  在你的GitHub里面可以设置。

**Comment by cp-yuan** [comment]
我不想收到这个信息。我想知道到当初我是怎么进来的，一直收到邮件很烦。

**Comment by Mr-LiuDC** [comment]
你Watch了这个项目？不想收到邮件 Settings  -->  Notifications  去掉mail勾选。

**Comment by Thisisnotgoingpublished** [comment]
能不能分享一下呢，求求你了 rubbishcar@qq.com
