### ISSUE TITLE
请问如何设置shadowsocks的代理？

### ISSUE THREAD

**Issue by kappakoala** [soimort/you-get#2005]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
主页上有说明，程序自带的help里也有
这问题主要是你部署的shadowsocks是怎么样的

**Comment by shikkoku** [comment]
记得如果要用到socks5要用pip装个PySocks来着？win版客户端倒是可以直接用http代理。话说你什么信息都没写。

**Comment by rosynirvana** [comment]
应该说自带privoxy的ss client可以用http代理

**Comment by shikkoku** [comment]
@rosynirvana 话说QT5那个比较不好用。

**Comment by ytzhang0925** [comment]
推荐一个命令行工具叫proxychains4

**Comment by iVanilla** [comment]
```
sudo pip3 install pysocks
you-get -s 127.0.0.1:1080 -i youtube链接  # 这里只是查询视频信息
```

**Comment by cnbeining** [comment]
Closed due to issue not moving forward.

Please read the FAQ, which contains instructions about using SOCKS proxy with ```you-get``` .
