### ISSUE TITLE
-I选项批量解析文件时,有一个报错后面就不继续了

### ISSUE THREAD

**Issue by gasry1989** [soimort/you-get#2008]
root@iZ94pfayo5aZ:/gary/you-get# python3 you-get -t 2 -o youku-videos -I web_parser2.txt
site: 优酷 (Youku)
title: 我的宠物是老虎
stream:
- format: hd2
container: flv
video-profile: 超清
size: 8.6 MiB (9012056 bytes)
# download-with: you-get --format=hd2 [URL]

Skipping youku-videos/我的宠物是老虎.flv: file already exists

Downloading 我的宠物是老虎 - ▇▇▇▇▇▇.cmt.json ...

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get: (1) Rule out any network problem.
you-get: (2) Make sure you-get is up-to-date.
you-get: (3) Check if the issue is already known, on
you-get: https://github.com/soimort/you-get/wiki/Known-Bugs
you-get: https://github.com/soimort/you-get/issues
you-get: (4) Run the command with '--debug' option,
you-get: and report this issue with the full output.

**Comment by gasry1989** [comment]
root@iZ94pfayo5aZ:/gary/you-get# python3 you-get -t 2 -o youku-videos --debug -I site.txt
[DEBUG] you are trying to load urls from site.txt
[DEBUG] get_response: http://www.acfun.cn/v/ac3498708
[DEBUG] get_response: http://www.acfun.tv/video/getVideo.aspx?id=4902926
[DEBUG] get_content: http://api.aixifan.com/plays/4902926
[DEBUG] get_content: https://api.youku.com/players/custom.json?client_id=908a519d032263f8&video_id=58afc8370cf2edf0aecff76b&embsig=1_1495553934_0b0d51e81dace6a3ac4e13e5445fa365
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8&vid=58afc8370cf2edf0aecff76b&ct=85&sign=MXwxNDk1NTUzOTkwfDJiMGZlYTkzOGEyMDY0NzYxMzhhZDFhNzgwZGQ3Yzc5
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.cn/v/ac3498708', 'http://www.acfun.cn/v/ac2678901', 'http://www.acfun.cn/v/ac19657', 'http://www.acfun.cn/v/ac318070', 'http://www.acfun.cn/v/ac2454830']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/gary/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/gary/you-get/src/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/gary/you-get/src/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/gary/you-get/src/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/gary/you-get/src/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/gary/you-get/src/you_get/extractors/acfun.py", line 90, in acfun_download
    **kwargs)
  File "/gary/you-get/src/you_get/extractors/acfun.py", line 55, in acfun_download_by_vid
    youku_open_download_by_vid(client_id='908a519d032263f8', vid=sourceId, title=title, output_dir=output_dir,merge=merge, info_only=info_only, embsig = embsig, **kwargs)
  File "/gary/you-get/src/you_get/extractors/youku.py", line 375, in open_download_by_vid
    self.prepare(api_url = api85_url, api12_url = api86_url, ctype = 86, **kwargs)
  File "/gary/you-get/src/you_get/extractors/youku.py", line 172, in prepare
    headers={'Referer': 'http://static.youku.com/'}
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 2 column 1 (char 2)
root@iZ94pfayo5aZ:/gary/you-get# cat site.txt
http://www.acfun.cn/v/ac3498708
http://www.acfun.cn/v/ac2678901
http://www.acfun.cn/v/ac19657
http://www.acfun.cn/v/ac318070
http://www.acfun.cn/v/ac2454830

**Comment by rosynirvana** [comment]
要报告的是标题里描述的，还是“我的宠物是老虎”这个报错，还是两者？

前者是预期中的行为，因为这时候的信息不足以进行错误恢复
例如哪个extractor的key失效了，继续跑下去是白费力，而且会让控制台输出很混乱难以debug

**Comment by gasry1989** [comment]
懂了，谢谢
