### ISSUE TITLE
you-get v0.4.750 没有单独的exe吗？

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#2017]
前面的版本都还有单独的exe，为什么这个版本就没有呢？
https://github.com/soimort/you-get/releases
据说以前的exe是用pyinstaller打包的，但是我一直未成功，谁能传授下打包方法，谢谢！

**Comment by skywang00** [comment]
因为you-get v0.4.750是dev版不是stable，所以不提供pre-built package

windows系统的话，下载 https://github.com/soimort/you-get/archive/develop.zip 后解压，对you-get-develop 文件夹 shift+右键 ，点击 在此处打开powershell 窗口 ，输入
` python .\setup.py install` 
回车执行即可

其实这样安装有好处的，可以随时改某个解析py，比如最近youku解析出问题，将youku.py修改后再执行该操作即可立刻生效，不需要等待github发布更新后的dev版

**Comment by redstoneleo** [comment]
谢谢回复，我是要打包成单独的exe方法，安装的话我用这个命令就搞定了
`pip3 install  --upgrade git+https://github.com/redstoneleo/you-get.git`

**Comment by rosynirvana** [comment]
v0.4.750是release不是dev

**Comment by skywang00** [comment]
@redstoneleo 
试下这个呗 https://github.com/pyinstaller/pyinstaller/

**Comment by redstoneleo** [comment]
我用pyinstaller打包的，但是我一直未成功

**Comment by StLym** [comment]
之前一直用exe，省事儿。这次一直没出只好用pip3装了

**Comment by soimort** [comment]
Updated.
