### ISSUE TITLE
All CDNs failed so You Can NOT Advance

### ISSUE THREAD

**Issue by kang0024** [soimort/you-get#2018]
这个列表下的所有视频都是这个问题：

you-get --debug http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] url_locations: http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] get_content: http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] get_response: http://www.bilibili.com/video/av2783167/index_1.html
[DEBUG] get_response: http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=4346931&from=miniplay&player=1&sign=35ee420d8598cca6d79c75c020338d12
[DEBUG] url_info: http://ws.acgvideo.com/c/eb/4346931-1.flv?wsTime=1495713635&platform=pc&wsSecret2=1c06bc574731bc0925cf273c63dc5543&oi=1938160829&rate=1280
you-get: HTTPError with url http://ws.acgvideo.com/c/eb/4346931-1.flv?wsTime=1495713635&platform=pc&wsSecret2=1c06bc574731bc0925cf273c63dc5543&oi=1938160829&rate=1280
[DEBUG] url_info: http://ws.acgvideo.com/c/eb/4346931-1hd.mp4?wsTime=1495713635&platform=pc&wsSecret2=5e73bf9b4f0a9fafc3e1b9c309c4591c&oi=1938160829&rate=1280
you-get: HTTPError with url http://ws.acgvideo.com/c/eb/4346931-1hd.mp4?wsTime=1495713635&platform=pc&wsSecret2=5e73bf9b4f0a9fafc3e1b9c309c4591c&oi=1938160829&rate=1280
[DEBUG] url_info: http://ws.acgvideo.com/c/eb/4346931-1.mp4?wsTime=1495713635&platform=pc&wsSecret2=2953f6bf804764eb31f124756a1a1909&oi=1938160829&rate=1280
you-get: HTTPError with url http://ws.acgvideo.com/c/eb/4346931-1.mp4?wsTime=1495713635&platform=pc&wsSecret2=2953f6bf804764eb31f124756a1a1909&oi=1938160829&rate=1280
you-get: All CDNs failed so You Can NOT Advance

**Comment by rosynirvana** [comment]
这个错误提示是我的一个branch才有的
你更新到最新的了吗？

**Comment by kang0024** [comment]
对，v0.4.750了。
因为发现这个错误才更新的。更新后还没覆盖#1698也试了一次，以上是覆盖后的debug。

**Comment by kang0024** [comment]
我是删除所有you-get文件重新下的。

**Comment by rosynirvana** [comment]
我重复不了
如果你确定没搞错什么就只能怪bilibili的CDN了

**Comment by kang0024** [comment]
或者你用那个branch试一试？
刚卸载又试了还是一样。和python版本有关吗？我的是3.6.1

**Comment by kang0024** [comment]
更新一下，我用youtube-dl能够下载。

**Comment by rosynirvana** [comment]
现在 #1698 会像官方html5播放器一样在所有CDN失败时fallback到quality=2
或许能帮到你

**Comment by kang0024** [comment]
哦是刚更新了吗？能不能给个可覆盖的文件，不好意思我小白不会用git。。。

**Comment by rosynirvana** [comment]
https://raw.githubusercontent.com/rosynirvana/you-get/f77d2692b27ccc0396faed1a05884fc4a8e31150/src/you_get/extractors/bilibili.py

**Comment by kang0024** [comment]
出现了错误：

you-get --debug http://www.bilibili.com/video/av2783167/index_1.html
[DEBUG] url_locations: http://www.bilibili.com/video/av2783167/index_1.html
[DEBUG] get_content: http://www.bilibili.com/video/av2783167/index_1.html
[DEBUG] get_response: http://www.bilibili.com/video/av2783167/index_1.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=4348265&from=miniplay&player=1&sign=2d59e72d41412236b1cfb58660d2d8f0
[DEBUG] url_info: http://ws.acgvideo.com/d/eb/4348265-1.flv?wsTime=1495716482&platform=pc&wsSecret2=232fe4fd49e76d836b14e73cf1a9175b&oi=1938160829&rate=1280
you-get: HTTPError with url http://ws.acgvideo.com/d/eb/4348265-1.flv?wsTime=1495716482&platform=pc&wsSecret2=232fe4fd49e76d836b14e73cf1a9175b&oi=1938160829&rate=1280
[DEBUG] url_info: http://ws.acgvideo.com/d/eb/4348265-1hd.mp4?wsTime=1495716482&platform=pc&wsSecret2=8542e86b454420e0156c254678854279&oi=1938160829&rate=1280
you-get: HTTPError with url http://ws.acgvideo.com/d/eb/4348265-1hd.mp4?wsTime=1495716482&platform=pc&wsSecret2=8542e86b454420e0156c254678854279&oi=1938160829&rate=1280
[DEBUG] url_info: http://ws.acgvideo.com/d/eb/4348265-1.mp4?wsTime=1495716482&platform=pc&wsSecret2=dc887639e18e093640312ea337440736&oi=1938160829&rate=1280
you-get: HTTPError with url http://ws.acgvideo.com/d/eb/4348265-1.mp4?wsTime=1495716482&platform=pc&wsSecret2=dc887639e18e093640312ea337440736&oi=1938160829&rate=1280
you-get: CDNs failed. Trying fallback
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=4348265&from=miniplay&player=1&quality=2&sign=a9e227ca4e4e96fb5a82d51573264db7
[DEBUG] url_info: http://ws.acgvideo.com/d/eb/4348265-1hd.mp4?wsTime=1495716484&platform=pc&wsSecret2=892c9b98b5a3419ec228ed1c107923a0&oi=1938160829&rate=700
you-get: HTTPError with url http://ws.acgvideo.com/d/eb/4348265-1hd.mp4?wsTime=1495716484&platform=pc&wsSecret2=892c9b98b5a3419ec228ed1c107923a0&oi=1938160829&rate=700
[DEBUG] url_info: http://ws.acgvideo.com/d/eb/4348265-1.mp4?wsTime=1495716484&platform=pc&wsSecret2=3fbac8ddc1f43372428a4f0bd060afe8&oi=1938160829&rate=700
you-get: HTTPError with url http://ws.acgvideo.com/d/eb/4348265-1.mp4?wsTime=1495716484&platform=pc&wsSecret2=3fbac8ddc1f43372428a4f0bd060afe8&oi=1938160829&rate=700
you-get: Fallback tried but no luck

**Comment by rosynirvana** [comment]
呃quality=2也失败还是第一次见到

在你那里用html5播放器能播这个视频吗？
如果控制台挂了代理，浏览器应该挂一样的代理

**Comment by kang0024** [comment]
我用chrome能正常打开。没挂代理啊。

**Comment by rosynirvana** [comment]
那devtool -> network 最后一次的interface.bilibili.com/playurl的整个request是什么？
注意是最后一次，可能有fallback

**Comment by kang0024** [comment]
呃什么意思？没看懂。

**Comment by rosynirvana** [comment]
那就算了

最后可以试试把代码里的http://interface改成https://interface

**Comment by kang0024** [comment]
所有http://interface吗？

**Comment by rosynirvana** [comment]
https://raw.githubusercontent.com/rosynirvana/you-get/fix-bilibili-redirect/src/you_get/extractors/bilibili.py

**Comment by kang0024** [comment]
出现了一样的错误：

you-get --debug http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] url_locations: http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] get_content: http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] get_response: http://www.bilibili.com/video/av2783167/index_1.html
[DEBUG] get_response: http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] get_content: https://interface.bilibili.com/playurl?cid=4346931&from=miniplay&player=1&sign=35ee420d8598cca6d79c75c020338d12
[DEBUG] url_info: http://ws.acgvideo.com/c/eb/4346931-1.flv?wsTime=1495718286&platform=pc&wsSecret2=15b04244468216c5af03d8a76cb1850e&oi=1938160829&rate=1280
you-get: HTTPError with url http://ws.acgvideo.com/c/eb/4346931-1.flv?wsTime=1495718286&platform=pc&wsSecret2=15b04244468216c5af03d8a76cb1850e&oi=1938160829&rate=1280
[DEBUG] url_info: http://ws.acgvideo.com/c/eb/4346931-1hd.mp4?wsTime=1495718286&platform=pc&wsSecret2=e7391b3f10680d517445cc940e1b7abe&oi=1938160829&rate=1280
you-get: HTTPError with url http://ws.acgvideo.com/c/eb/4346931-1hd.mp4?wsTime=1495718286&platform=pc&wsSecret2=e7391b3f10680d517445cc940e1b7abe&oi=1938160829&rate=1280
[DEBUG] url_info: http://ws.acgvideo.com/c/eb/4346931-1.mp4?wsTime=1495718286&platform=pc&wsSecret2=7ce207d1d683f0485e75435da60c24f6&oi=1938160829&rate=1280
you-get: HTTPError with url http://ws.acgvideo.com/c/eb/4346931-1.mp4?wsTime=1495718286&platform=pc&wsSecret2=7ce207d1d683f0485e75435da60c24f6&oi=1938160829&rate=1280
you-get: CDNs failed. Trying fallback
[DEBUG] get_content: https://interface.bilibili.com/playurl?cid=4346931&from=miniplay&player=1&quality=2&sign=5f7eb9cc8db2c9bbd4c8bb9547bfbac1
[DEBUG] url_info: http://ws.acgvideo.com/c/eb/4346931-1hd.mp4?wsTime=1495718290&platform=pc&wsSecret2=5c0ace4b790d8410f1d879a7093699d6&oi=1938160829&rate=700
you-get: HTTPError with url http://ws.acgvideo.com/c/eb/4346931-1hd.mp4?wsTime=1495718290&platform=pc&wsSecret2=5c0ace4b790d8410f1d879a7093699d6&oi=1938160829&rate=700
[DEBUG] url_info: http://ws.acgvideo.com/c/eb/4346931-1.mp4?wsTime=1495718290&platform=pc&wsSecret2=2a9c5c85d9aa3c4f166ad4ed91fdb87f&oi=1938160829&rate=700
you-get: HTTPError with url http://ws.acgvideo.com/c/eb/4346931-1.mp4?wsTime=1495718290&platform=pc&wsSecret2=2a9c5c85d9aa3c4f166ad4ed91fdb87f&oi=1938160829&rate=700
you-get: Fallback tried but no luck

**Comment by rosynirvana** [comment]
那就没办法了

或许你可以试着学习看chrome devtools里的network

**Comment by kang0024** [comment]
现在任何视频都是同个问题。。。

**Comment by rosynirvana** [comment]
我这里一次CDN失败都重复不出来
所以建议学着自己debug吧

**Comment by kang0024** [comment]
是不是这个？我copy了request header：

GET /rec?playtime=168395&cid=4346931 HTTP/1.1
Host: interface.bilibili.com
Connection: keep-alive
X-Requested-With: ShockwaveFlash/25.0.0.171
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Accept: */*
Referer: http://www.bilibili.com/video/av2783167/index_2.html
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,zh-CN;q=0.6,zh-TW;q=0.4
Cookie: fts=1479561135; pgv_pvi=5095536640; pgv_si=s33729536; sid=b5r131lp; _ga=GA1.2.1638233295.1479958224; buvid3=C313733F-49AF-4B4A-8A6D-BB540D530F8F19749infoc; UM_distinctid=15ab8e14d03355-03bc65c8fc34d8-57e1b3c-1fa400-15ab8e14d04a7b; finger=7360d3c2; DedeUserID=51236520; DedeUserID__ckMd5=7523df6927854174; SESSDATA=48462f22%2C1497529654%2C2e795385; bili_jct=5a7a259ed243169e12e18e43a760cffa; LIVE_BUVID=e083411b5782a83a393c9e2cfd653f41; LIVE_BUVID__ckMd5=2ce5d268b3ab4cf3; _cnt_dyn=null; uTZ=-480; purl_token=bilibili_1495679513; _cnt_pm=0; _cnt_notify=0; LIVE_LOGIN_DATA=1a4793ac0d8e08d8aacb03431d571b9b63281d0f; LIVE_LOGIN_DATA__ckMd5=f663b864486fdcdb; _dfcaptcha=c4d8a02f2a56d1ca1a0ede343bdc13f1

**Comment by zhangn1985** [comment]
ws cdn就是会出现这样的问题。除非加Referer

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/ykdl/commit/24807f430edd20b2449defefd957967d812e479a

**Comment by rosynirvana** [comment]
不是，url是```https://interface.bilibili.com/playurl```

**Comment by kang0024** [comment]
找到了，不知道为什么第一次没有出现：

GET /playurl?player=1&ts=1495710634&accel=1&sign=df09ab6ed75ed39da37bd0cfd1092e48&cid=4346931 HTTP/1.1
Host: interface.bilibili.com
Connection: keep-alive
X-Requested-With: ShockwaveFlash/25.0.0.171
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Accept: */*
Referer: http://www.bilibili.com/video/av2783167/index_2.html
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,zh-CN;q=0.6,zh-TW;q=0.4
Cookie: fts=1479561135; pgv_pvi=5095536640; pgv_si=s33729536; sid=b5r131lp; _ga=GA1.2.1638233295.1479958224; buvid3=C313733F-49AF-4B4A-8A6D-BB540D530F8F19749infoc; UM_distinctid=15ab8e14d03355-03bc65c8fc34d8-57e1b3c-1fa400-15ab8e14d04a7b; finger=7360d3c2; DedeUserID=51236520; DedeUserID__ckMd5=7523df6927854174; SESSDATA=48462f22%2C1497529654%2C2e795385; bili_jct=5a7a259ed243169e12e18e43a760cffa; LIVE_BUVID=e083411b5782a83a393c9e2cfd653f41; LIVE_BUVID__ckMd5=2ce5d268b3ab4cf3; _cnt_dyn=null; uTZ=-480; _cnt_pm=0; _cnt_notify=0; LIVE_LOGIN_DATA=1a4793ac0d8e08d8aacb03431d571b9b63281d0f; LIVE_LOGIN_DATA__ckMd5=f663b864486fdcdb; purl_token=bilibili_1495710325; _dfcaptcha=c4d8a02f2a56d1ca1a0ede343bdc13f1

**Comment by airdge** [comment]
platform=pc挂了  换成platform=html5就行  现在bilibili手机端的就是platform=html5
```
http://ws.acgvideo.com/c/eb/4346931-1.mp4?wsTime=1495713635&platform=pc&wsSecret2=2953f6bf804764eb31f124756a1a1909&oi=1938160829&rate=1280

http://ws.acgvideo.com/c/eb/4346931-1.mp4?wsTime=1495713635&platform=html5&wsSecret2=2953f6bf804764eb31f124756a1a1909&oi=1938160829&rate=1280
```

**Comment by rosynirvana** [comment]
区别在于有个海外加速的accel=1
这个不怎么好实现

**Comment by airdge** [comment]
应该和api无关
播放器解析出来的数据是platform=pc,   这个地址来源限制  放到浏览器直接打开是403  
`http://api.bilibili.com/playurl?callback=callbackfunction&aid=10759546&page=1&platform=html5&quality=1&vtype=mp4&type=jsonp&token=d52bac4b7a62ae0dd9b9fb95b454608e`
`callbackfunction({"from":"local","result":"suee","format":"mp4","timelength":144900,"accept_format":"flv,hdmp4,mp4","accept_quality":[3,2,1],"seek_param":"start","seek_type":"second","durl":[{"order":1,"length":144900,"size":10483165,"url":"http:\/\/tx.acgvideo.com\/6\/9b\/17751470-1.mp4?txTime=1495717130&platform=html5&txSecret=4dc3e07e9ace660940594a6b42f4eaec&oi=1871845788&rate=110000"}],"img":"https:\/\/i0.hdslb.com\/bfs\/archive\/1e2bfac63afb46ab396f9e7078be3a9f017c76df.jpg","cid":"http:\/\/comment.bilibili.com\/17751470.xml","fromview":null});`
可以参考下手机端的api  解析出的数据是platform=html5

**Comment by denobisipsis** [comment]
without miniplay

$sign_this = md5("accel=1&cid=$cid&player=1&ts=$ts$secret");

**Comment by rosynirvana** [comment]
也不知道是禁止miniplay的外链还是海外加速的accel=1
只能等出问题的人自己debug

**Comment by kang0024** [comment]
@rosynirvana 能分别提供两种情况可覆盖文件吗？我自己试试再回来报告。不好意思麻烦你了。

**Comment by rosynirvana** [comment]
明白了，是ua

**Comment by rosynirvana** [comment]
https://raw.githubusercontent.com/rosynirvana/you-get/fix-bilibili-redirect/src/you_get/extractors/bilibili.py

应该可以了

**Comment by kang0024** [comment]
oversea没定义？

you-get --debug http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] url_locations: http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] get_content: http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] get_response: http://www.bilibili.com/video/av2783167/index_1.html
[DEBUG] get_response: http://www.bilibili.com/video/av2783167/index_2.html
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av2783167/index_2.html']
Traceback (most recent call last):
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kang0024\AppData\Local\Programs\Python\Python36-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1157, in download_main
    download(url, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\bilibili.py", line 334, in bilibili_download
    oversea=oversea)
NameError: name 'oversea' is not defined

**Comment by rosynirvana** [comment]
现在应该好了……

**Comment by kang0024** [comment]
能够下载了，谢谢大神。是user agent出什么问题吗？

**Comment by rosynirvana** [comment]
curl和python的user-agent都被ws.acgvideo.com给封了

**Comment by kang0024** [comment]
哦明白了，谢谢大神费神费时解决问题！

**Comment by denobisipsis** [comment]
to get more speed

	$time=time();
	$ctoken="bilibili_".$time;
	$purltoken=md5($ctoken);

get mp4 with cookie purl_token=$purltoken (testing it)

**Comment by liuzhen2008** [comment]
I get this error even after I replaced the bilibili.py with yours.

```
./you-get -di http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] url_locations: http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] get_content: http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] get_response: http://www.bilibili.com/video/av2783167/index_1.html
[DEBUG] get_response: http://www.bilibili.com/video/av2783167/index_2.html
[DEBUG] get_content: https://interface.bilibili.com/playurl?cid=4346931&player=1&ts=1495726114&sign=a5f3bdea9bdb1da91c58eb71cef1f11d
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av2783167/index_2.html']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)
```

**Comment by rosynirvana** [comment]
@liuzhen2008

```
cd /Applications/Python\ 3.6/
./Install\ Certificates.command
```

**Comment by liuzhen2008** [comment]
@rosynirvana Thanks it works now!

**Comment by liuzhen2008** [comment]
@denobisipsis Where Do I put these 3 lines of code so that I get normal speed? For some reason my video is stuck with 6kb/s after 5% download

**Comment by rosynirvana** [comment]
@liuzhen2008

change the timeout to a smaller value as describe in #1698 replies

**Comment by liuzhen2008** [comment]
@rosynirvana 不知道跟timeout又没有直接关系，改成1秒后下载很快，但是偶尔会中断。

改成2秒后又变成下载5%就变成6kb/s了。。

**Comment by rosynirvana** [comment]
@liuzhen2008 你的aws IP被bili api限制了，如果看拿到的cdn url，应该有个&rate=6
timeout=1就是自动替你做下5MiB中断重来这件事情

**Comment by liuzhen2008** [comment]
懂了。

我把这里的timeout

`
download_urls(urls, title, type_, total_size=size, output_dir=output_dir, merge=merge, timeout=1, headers=headers)
`

设置成1，虽然偶尔他会自己中断，我自己写逻辑让他不停的retry就好了。

**Comment by rosynirvana** [comment]
把抛出的异常补在这里就行了
```except socket.timeout```

比如
```except (socket.timeout, urllib.error.URLError)``` 这类
