### ISSUE TITLE
土豆视频无法下载 http://www.tudou.com/listplay/UNbTqZ2eATU/ZYYdBMfLinE.html

### ISSUE THREAD

**Issue by zhaoff2015** [soimort/you-get#2019]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
#2015 

```
./you-get -di 'http://www.tudou.com/listplay/UNbTqZ2eATU/ZYYdBMfLinE.html'
[DEBUG] get_content: http://www.tudou.com/listplay/UNbTqZ2eATU/ZYYdBMfLinE.html
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMTc4NTg2ODY2NA==&ccode=0402&client_ip=192.168.1.1&utid=CY6tETtLoTQCAbZyXYnGPdrA&client_ts=1495703561
site:                优酷 (Youku)
title:               田馥甄Hebe巡迴演唱會-小幸運官方live版
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          100.3 MiB (105193049 bytes)
    # download-with: you-get --format=hd3 [URL]

    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          52.4 MiB (54904813 bytes)
    # download-with: you-get --format=hd2 [URL]

    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          27.7 MiB (29042305 bytes)
    # download-with: you-get --format=mp4 [URL]

    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          13.4 MiB (14010470 bytes)
    # download-with: you-get --format=flvhd [URL]

    - format:        3gphd
      container:     3gp
      video-profile: 标清（3GP）
      size:          9.6 MiB (10070087 bytes)
    # download-with: you-get --format=3gphd [URL]
```

**Comment by zhaoff2015** [comment]
报如下错误：
pydev debugger: starting (pid: 3500)
[DEBUG] get_content: http://www.tudou.com/listplay/UNbTqZ2eATU/ZYYdBMfLinE.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTc4NTg2ODY2NA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTc4NTg2ODY2NA==&ct=12
you-get: [Failed] 抱歉，因版权原因无法观看此视频！
