### ISSUE TITLE
优酷视频下载提示：you-get: [Failed] 客户端无权播放,603

### ISSUE THREAD

**Issue by UesugiErii** [soimort/you-get#2030]
pi@raspberrypi:~ $ you-get --debug 'http://v.youku.com/v_show/id_XMjc4MzU3NDE1Ng==.html'
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjc4MzU3NDE1Ng==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjc4MzU3NDE1Ng==&ct=12
you-get: [Failed] 客户端无权播放,603

我知道这个问题已经有了，但是每次都导向了别的问题，在别的问题中没有给出有效的具体解决方案。

请回复的人麻烦给出一个具体的解决方案，而不是导向那些我无法理解的问题编号中。

谢谢

**Comment by rosynirvana** [comment]
#2015 
回复里有

**Comment by UesugiErii** [comment]
我无法理解那些评论，能直接告诉我吗，方便我，也方便别人可以直接通过这个问题找到答案，谢谢

**Comment by rosynirvana** [comment]
可选的方法：
1. git clone https://github.com/rosynirvana/you-get/tree/youku 然后用这个branch
2. 用下面三个文件替换you-get中的三个文件
```
https://raw.githubusercontent.com/rosynirvana/you-get/youku/src/you_get/extractors/youku.py
https://raw.githubusercontent.com/rosynirvana/you-get/youku/src/you_get/extractors/tudou.py
https://raw.githubusercontent.com/rosynirvana/you-get/youku/src/you_get/extractor.py
```

查看you-get的安装位置:
```
pip3 show you-get | grep Location
```

还不理解就等着merge release吧

**Comment by UesugiErii** [comment]
谢谢，我希望如果有人再提出相似问题时请导向到这个问题，方便他人解决

**Comment by baktbd** [comment]
大哥，你说话能不能简单点？你知不知道你最不适做的职业就是老师？

什么叫做 "git clone https://github.com/rosynirvana/you-get/tree/youku 然后用这个branch"？什么叫做branch，我打了git clone，在cmd里显示'git' is not recognized as an internal or external command,
operable program or batch file.

**Comment by UesugiErii** [comment]
@baktbd 
你不适合当程序员，github也不适合你

**Comment by cnbeining** [comment]
I hereby request a respectful manner toward all the members within this community.

Conversation locked due to inappropriate language used towards the community.
