### ISSUE TITLE
优酷的视频都无法下载了

### ISSUE THREAD

**Issue by 614567264** [soimort/you-get#2033]
这周开始优酷视频都是错误603了   看到大神回复说要带cna   但是小白实在不知道怎样操作  求个大神能qq上教一下，有偿教学也能接受！！我qq1052602016  添加请备注youget

**Comment by 614567264** [comment]
E:\youget>E:\youget\you-get.exe -c E:\youget\cookies.txt http://v.youku.com/v_sh
ow/id_XMjc4NjIxMTY4MA==.html?from=s1.8-1-1.1&spm=a2h0k.8191407.0.0
you-get: [Failed] 客户端无权播放,603
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
'spm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by 614567264** [comment]
http://v.youku.com/v_show/id_XMjc4NjIxMTY4MA==.html?from=s1.8-1-1.1&spm=a2h0k.8191407.0.0下载的链接是这个

**Comment by redstoneleo** [comment]
道友，貌似加了cna也不行，我来这边已经报告这个问题了，可以关注下我的乐影音下载器
https://github.com/soimort/you-get/issues/2034

**Comment by 614567264** [comment]
道友  你就是乐影音的作者么  我喊你都不在线

**Comment by soimort** [comment]
Closed via #2015.
