### ISSUE TITLE
优酷you-get: [Failed] 客户端无权播放,603

### ISSUE THREAD

**Issue by 774619774** [soimort/you-get#2037]
you-get -i http://v.youku.com/v_show/id_XMTcyNzY2OTg0.html?tpa=dW5pb25faWQ9MTAzNjY3XzEwMDAwMV8wMV8wMQ
you-get: [Failed] 客户端无权播放,603

**Comment by shikkoku** [comment]
dup #2012

**Comment by 774619774** [comment]
用了master分支还是不行

**Comment by rosynirvana** [comment]
you-get没有master分支

**Comment by iamggs** [comment]
同样问题，无论0.4.715还是0.4.750，下载youku都报错：[Failed] 客户端无权播放,603

**Comment by sevensky** [comment]
http://play-ali.youku.com/play/get.json?vid=XMTQyODc1MzcyMA==&ct=12&callback= callback 错误是这里报出来的。

**Comment by tulip33** [comment]
优酷挂了，全都不能下载【客户端无权播放】

**Comment by dkl3** [comment]
you-get http://v.youku.com/v_show/id_XMTM2OTk3MjQ=.html --debug
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTM2OTk3MjQ=&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTM2OTk3MjQ=&ct=12
you-get: [Failed] 客户端无权播放,603

I get the same error.

**Comment by zzzzzm80** [comment]
C:\Users\PD>you-get --debug http://v.youku.com/v_show/id_XMTIzNzA4NDQw.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTIzNzA4NDQw&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTIzNzA4NDQw&ct=12
you-get: [Failed] 客户端无权播放,603
'spm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by Pianya** [comment]
似乎是优酷对flash的dll插件有冲突。火狐和chrome浏览器直接访问视频页面也无法加载视频，而IE却能正常打开。

**Comment by xuyuanfang** [comment]
同样的问题，mark

**Comment by iamggs** [comment]
看这个：https://github.com/soimort/you-get/issues/2030

重点是@rosynirvana 的解答，实际覆盖本地三个py后就正常了。

**Comment by hnliyuan** [comment]
@rosynirvana 
 你好。 
 我读了你写的关于Youku的代码。
 我用javascript实现相关功能。
 但是我在实现fetch_cna时出现了问题。
 `                let cookie_url = 'http://log.mmstat.com/eg.js'
                fetch(cookie_url).then( (res) => {
                    let url = 'https://ups.youku.com/ups/get.json?vid='+ this.vid +'&ccode=0401';
                    url += '&client_ip=192.168.1.1';
                    url += '&utid=' + this._quote_cna(res.cna);
                    url += '&client_ts=' + (new Date).getTime();
                    fetch(url, {
                        headers: {
                            'userAgent':this.userAgent
                        }
                    }).then((i)=>{
                        var a = JSON.parse(i._bodyInit);
                        var streams = a.data.stream;
                        if(streams && streams.length > 0){
                            callback(streams[0].m3u8_url)
                        }
                    })
                })`
我同样也可以拿到cna.
但是我通过这个cna值去请求，[Failed] 客户端无权播放,603。
希望你能帮助一下我

**Comment by rosynirvana** [comment]
```(new Date).getTime()```是毫秒，这里要的是秒

**Comment by soimort** [comment]
Closed via #2015.
