### ISSUE TITLE
you-get下载不了搜狐视频 youtube-dl可以 -f high ，不知道是不是参数用错

### ISSUE THREAD

**Issue by 774619774** [soimort/you-get#2038]
python3 you-get     http://my.tv.sohu.com/us/311162910/89147551.shtml
Site:       Sohu.com
Title:      上海人眼里的九寨沟，这位退休老教师拍出了不一样的感觉！
Type:       MPEG-4 video (video/mp4)
Size:       21.3 MiB (22332168 Bytes)

 you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

youtube-dl -F http://my.tv.sohu.com/us/311162910/89147551.shtml
[Sohu] 89147551: Downloading webpage
[Sohu] 89147551: Downloading JSON data for 89147551
[Sohu] 89147551: Downloading JSON data for 89147551_2
[Sohu] 89147551: Downloading JSON data for 89147551_1
[Sohu] 89147551: Downloading JSON data for 89147551_21
[Sohu] 89147551: Downloading JSON data for 89147551_31
[Sohu] 89147551: Downloading ori video URL part 1 of 1
[Sohu] 89147551: Downloading super video URL part 1 of 1
[Sohu] 89147551: Downloading high video URL part 1 of 1
[Sohu] 89147551: Downloading nor video URL part 1 of 1
[info] Available formats for 89147551:
format code  extension  resolution note
nor          mp4        0x0        fps, 11.79MiB
high         mp4        0x0        fps, 21.30MiB
super        mp4        0x0        fps, 38.45MiB
ori          mp4        0x0        fps, 85.44MiB (best)

**Comment by 774619774** [comment]
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/usr/local/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/you-get/src/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/you-get/src/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/you-get/src/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/usr/local/you-get/src/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/usr/local/you-get/src/you_get/extractors/sohu.py", line 75, in sohu_download
    download_urls(urls, title, 'mp4', size, output_dir, refer = url, merge = merge)
  File "/usr/local/you-get/src/you_get/common.py", line 799, in download_urls
    url_save(url, output_filepath, bar, refer = refer, faker = faker, headers = headers, **kwargs)
  File "/usr/local/you-get/src/you_get/common.py", line 532, in url_save
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "/usr/local/you-get/src/you_get/common.py", line 307, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/lib64/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 470, in open
    response = meth(req, response)
  File "/usr/lib64/python3.4/urllib/request.py", line 580, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.4/urllib/request.py", line 508, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 588, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by rosynirvana** [comment]
#1979 

搜狐的CDN有问题，对```range: x-```这种完全正常的HTTP header抛403
但是对```range: x-y```是正常的（虽说有时候206有时候200）

**Comment by maonx** [comment]
最近我下载sohu的也出现这个 403错误了，但用youtube-dl下载正常

**Comment by einverne** [comment]
测试 you-get: version 0.4.715  这个版本是可以的， develop 最新却是不行的。

**Comment by rosynirvana** [comment]
因为是 #1940 引入的

**Comment by demonluo** [comment]
测试 you-get: version 0.4.775 这个最新版本下载不了搜狐视频...
```
http://tv.sohu.com/20140820/n403626737.shtml
```

**Comment by rosynirvana** [comment]
```
$ ./you-get -d http://my.tv.sohu.com/us/311162910/89147551.shtml
[DEBUG] get_response: http://my.tv.sohu.com/us/311162910/89147551.shtml
[DEBUG] get_response: http://my.tv.sohu.com/play/videonew.do?vid=89147551&referer=http://my.tv.sohu.com
[DEBUG] get_response: http://data.vod.itc.cn/?prot=9&prod=flash&pt=1&file=&new=/4/73/4lH885K00shtQ49GYN5FQX.mp4&key=7f9a0GT6QcncRLMh4vi5QuXxZ01xoXcC&vid=89147551&uid=1499604778873&t=0.9032690972319777&rb=1
Site:       Sohu.com
Title:      上海人眼里的九寨沟，这位退休老教师拍出了不一样的感觉！
Type:       MPEG-4 video (video/mp4)
Size:       21.3 MiB (22332168 Bytes)

Downloading 上海人眼里的九寨沟，这位退休老教师拍出了不一样的感觉！.mp4 ...
 100% ( 21.3/ 21.3MB) ├██████████████████████████████████████████████┤[1/1]    2 MB/s
```

fixed via https://github.com/soimort/you-get/commit/dbe272a8af363544e7fc45a68aa86045e91d66be
