### ISSUE TITLE
谁能帮我探测下这个音频节目的下载地址

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#2045]
http://www.appledaily.com.tw/realtimenews/article/new/20161101/979694/
谁能帮我探测下这个文章末尾的音频节目的下载地址，谢谢啦

希望简单讲下你的探测方法并贴出下载地址，谢谢

**Comment by rosynirvana** [comment]
分析html
发现flashvars是```autostart=false&file=vod156/record/1_20161009_2300_594.mp4&streamer=rtmp://flv.ccdntech.com/vod/_definst_/```

然后wireshark抓包看到确实有rtmp
那么很容易猜到是
```rtmp://flv.ccdntech.com/vod/_definst_/vod156/record/1_20161009_2300_594.mp4```

下载
```
ffmpeg -i 'rtmp://flv.ccdntech.com/vod/_definst_/vod156/record/1_20161009_2300_594.mp4' -c copy out.mp4
```

rtmpdump的命令行前段做得不如ffmpeg好用
