### ISSUE TITLE
bili 随机出现 HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by skywang00** [soimort/you-get#2046]
bili 随机出现 HTTP Error 403: Forbidden，而且一旦出现这个错误立刻重试下载也会一直报错，必须等几分钟后才可以继续下载
感觉和这个好像  #2026 

> PS C:\Users\XXX> you-get -d http://www.bilibili.com/video/av2214612
> [DEBUG] get_content: http://www.bilibili.com/video/av2214612
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_1.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_2.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_3.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_4.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_5.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_6.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_7.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_8.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_9.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_10.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_11.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_12.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_13.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_14.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_15.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_16.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_17.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_18.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_19.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_20.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_21.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_22.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_23.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_24.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_25.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_26.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_27.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_28.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_29.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_30.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_31.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_32.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_33.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_34.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_35.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_36.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_37.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_38.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_39.html
> [DEBUG] get_response: http://www.bilibili.com/video/av2214612/index_40.html
> [DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=3439203&from=miniplay&player=1&sign=0d7944b02c24339ebf94
> 9ee162b0c40a
> [DEBUG] url_info: http://cn-jsyz3-dx.acgvideo.com/vg8/5/8b/3439203-1.flv?expires=1495959300&platform=pc&ssig=LflipPZ78on
> ytfpfZIVgYA&oi=976337467&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1&hfa=2065267732
> Site:       bilibili.com
> Title:      【新加坡版】 笑傲江湖 40集全 【2000】-1、01
> Type:       Flash video (video/x-flv)
> Size:       215.45 MiB (225911342 Bytes)

此处省略

> [DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=3439204&from=miniplay&player=1&sign=100ce3bc62e1e18e549a
> 641de2443bea
> [DEBUG] url_info: http://cn-zjhz5-dx.acgvideo.com/vg19/9/c7/3439204-1-hd.mp4?expires=1495959300&platform=pc&ssig=K1sBkth
> hy0PUAojyUWR06Q&oi=976337467&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1&hfa=2065267893
> Site:       bilibili.com
> Title:      【新加坡版】 笑傲江湖 40集全 【2000】-2、02
> Type:       MPEG-4 video (video/mp4)
> Size:       217.73 MiB (228307550 Bytes)
> 
> Downloading 【新加坡版】 笑傲江湖 40集全 【2000】-2、02.mp4 ...
>  0.1% (  0.2/217.7MB) ├─────────────────────────────────────────┤[1/1]    1 MB/

此处省略

>  6.2% ( 13.5/217.7MB) ├███──────────────────────────────────────┤[1/1]   11 MB/
> s[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=3439204&from=miniplay&player=1&sign=100ce3bc62e1e18e549
> a641de2443bea
> [DEBUG] url_info: http://ws.acgvideo.com/6/13/3439204-1.flv?wsTime=1495959437&platform=pc&wsSecret2=2c0cd2b7cb8c065494fb
> daa5d058a66b&oi=976337467&rate=1280
> you-get: version 0.4.750, a tiny downloader that scrapes the web.
> you-get: ['http://www.bilibili.com/video/av2214612']
> Traceback (most recent call last):
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\Scripts\you-get-script.py", line 11, in <module>
>     load_entry_point('you-get==0.4.750', 'console_scripts', 'you-get')()
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\__mai
> n__.py", line 92, in main
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
> n.py", line 1444, in main
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
> n.py", line 1355, in script_main
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
> n.py", line 1157, in download_main
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
> n.py", line 1437, in any_download
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\extra
> ctors\bilibili.py", line 187, in bilibili_download
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\extra
> ctors\bilibili.py", line 101, in bilibili_download_by_cid
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
> n.py", line 420, in url_info
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
> n.py", line 307, in urlopen_with_retry
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 223, in urlopen
>     return opener.open(url, data, timeout)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
>     response = meth(req, response)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 564, in error
>     result = self._call_chain(*args)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
>     result = func(*args)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 756, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
>     response = meth(req, response)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 570, in error
>     return self._call_chain(*args)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
>     result = func(*args)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 650, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 403: Forbidden
> 

# 如果立刻重试下载，会出现同样的错误

> Skipping  .\【新加坡版】 笑傲江湖 40集全 【2000】-2、02.mp4: file already exists
> [DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=3439205&from=miniplay&player=1&sign=03a92842ac62bafb33ff
> 4704cc18656c
> [DEBUG] url_info: http://ws.acgvideo.com/6/fe/3439205-1.flv?wsTime=1495959874&platform=pc&wsSecret2=a81b6385decdde9f7539
> 63130e3ac3f2&oi=976337467&rate=1280
> you-get: version 0.4.750, a tiny downloader that scrapes the web.
> you-get: ['http://www.bilibili.com/video/av2214612']
> Traceback (most recent call last):
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\Scripts\you-get-script.py", line 11, in <module>
>     load_entry_point('you-get==0.4.750', 'console_scripts', 'you-get')()
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\__mai
> n__.py", line 92, in main
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
> n.py", line 1444, in main
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
> n.py", line 1355, in script_main
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
> n.py", line 1157, in download_main
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
> n.py", line 1437, in any_download
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\extra
> ctors\bilibili.py", line 187, in bilibili_download
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\extra
> ctors\bilibili.py", line 101, in bilibili_download_by_cid
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
> n.py", line 420, in url_info
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\commo
> n.py", line 307, in urlopen_with_retry
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 223, in urlopen
>     return opener.open(url, data, timeout)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
>     response = meth(req, response)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 564, in error
>     result = self._call_chain(*args)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
>     result = func(*args)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 756, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
>     response = meth(req, response)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 570, in error
>     return self._call_chain(*args)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
>     result = func(*args)
>   File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 650, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by rosynirvana** [comment]
ws.acgvideo.com现在检查UA

first reported in #2018
dedicated issue #2021
dup #2022 
fixed in #1698

**Comment by skywang00** [comment]
@rosynirvana 
之前下载前3集必定出现403，应用 #1698 后，现在已经下载到第6集了，但这个bili的视频怎么还是会重新打印 print_info？

**Comment by rosynirvana** [comment]
没看明白
是下载到一半在中间打印```print_info```
还是一集下载完了，然后第二集会打印```print_info``` ?

**Comment by skywang00** [comment]
@rosynirvana 

> 87.0% (188.2/216.4MB) ├████████████████████████████████████─────┤[1/1]   12 MB/
87.1% (188.5/216.4MB) ├████████████████████████████████████─────┤[1/1]   11 MB/
87.2% (188.8/216.4MB) ├████████████████████████████████████─────┤[1/1]  370 kB/
87.4% (189.0/216.4MB) ├████████████████████████████████████─────┤[1/1]   11 MB/
87.5% (189.2/216.4MB) ├████████████████████████████████████─────┤[1/1]   11 MB/
87.6% (189.5/216.4MB) ├████████████████████████████████████─────┤[1/1]   12 MB/
87.7% (189.8/216.4MB) ├████████████████████████████████████─────┤[1/1]   11 MB/
87.8% (190.0/216.4MB) ├████████████████████████████████████─────┤[1/1]  131 kB/
87.9% (190.2/216.4MB) ├████████████████████████████████████─────┤[1/1]    5 MB/
88.0% (190.5/216.4MB) ├█████████████████████████████████████────┤[1/1]    8 MB/
88.2% (190.8/216.4MB) ├█████████████████████████████████████────┤[1/1]   12 MB/
88.3% (191.0/216.4MB) ├█████████████████████████████████████────┤[1/1]   11 MB/
88.4% (191.2/216.4MB) ├█████████████████████████████████████────┤[1/1]   11 MB/
88.5% (191.5/216.4MB) ├█████████████████████████████████████────┤[1/1]   12 MB/
88.6% (191.8/216.4MB) ├█████████████████████████████████████────┤[1/1]   11 MB/
88.7% (192.0/216.4MB) ├█████████████████████████████████████────┤[1/1]   11 MB/
88.9% (192.2/216.4MB) ├█████████████████████████████████████────┤[1/1]   11 MB/
89.0% (192.5/216.4MB) ├█████████████████████████████████████────┤[1/1]   10 MB/
89.1% (192.8/216.4MB) ├█████████████████████████████████████────┤[1/1]  373 kB/
89.2% (193.0/216.4MB) ├█████████████████████████████████████────┤[1/1]   11 MB/
89.3% (193.2/216.4MB) ├█████████████████████████████████████────┤[1/1]    8 MB/
89.4% (193.5/216.4MB) ├█████████████████████████████████████────┤[1/1]   11 MB/
89.5% (193.8/216.4MB) ├█████████████████████████████████████────┤[1/1]   11 MB/
89.7% (194.0/216.4MB) ├█████████████████████████████████████────┤[1/1]   11 MB/

**Comment by rosynirvana** [comment]
每集都打印不是正常的吗？

**Comment by skywang00** [comment]
#1698  不是说已经不会重新打印print_info了吗？我认为是不会再进度条刷屏了，难道我理解错了？


> 
> > ./you-get http://www.bilibili.com/video/av9954010/
> > Site:       bilibili.com
> > Title:      【西瓜新】一个小小的八音盒【有一点花絮】
> > Type:       MPEG-4 video (video/mp4)
> > Size:       25.6 MiB (26847580 Bytes)
> > 
> > Downloading 【西瓜新】一个小小的八音盒【有一点花絮】.mp4 ...
> >  100% ( 25.6/ 25.6MB) ├█████████████████████████████████████████┤[1/1]    9 MB/s
> > 
> > Downloading 【西瓜新】一个小小的八音盒【有一点花絮】.cmt.xml ...
> >  ./you-get http://bangumi.bilibili.com/anime/1660/play
> > Site:       bilibili.com
> > Title:      夏目友人帐 [1 猫和友人帐]
> > Type:       Flash video (video/x-flv)
> > Size:       143.16 MiB (150117218 Bytes)
> > 
> > Downloading 夏目友人帐 [1 猫和友人帐].flv ...
> >  100% (143.2/143.2MB) ├█████████████████████████████████████████┤[1/1]  566 kB/s
> > 
> > Downloading 夏目友人帐 [1 猫和友人帐].cmt.xml ...
> > ./you-get http://www.bilibili.com/video/av10199346
> > Site:       bilibili.com
> > Title:      【GNZ48王盈】20170429 出道一周年联合特别公演《糖》王盈 陈桂君 农燕萍
> > Type:       Flash video (video/x-flv)
> > Size:       85.81 MiB (89977095 Bytes)
> > 
> > Downloading 【GNZ48王盈】20170429 出道一周年联合特别公演《糖》王盈 陈桂君 农燕萍.flv ...
> >  100% ( 85.8/ 85.8MB) ├█████████████████████████████████████████┤[1/1]    5 MB/s
> > 
> > Downloading 【GNZ48王盈】20170429 出道一周年联合特别公演《糖》王盈 陈桂君 农燕萍.cmt.xml ...
> 
> 现在不会重新打印print_info

**Comment by rosynirvana** [comment]
这个要说明白话就有点多了

1. ```print_info```打印的不是进度条，是site title type size那几行
2. 现在develop branch里的实现，如果在下载时超时，会从访问api重来，所以会重复用```print_info```打印一个视频的信息
3. 这个例子里下载的是很多视频，每一集都会打印信息
4. 进度条刷屏是因为win console里难以正常实现进度条（之前issues里作者说和难以获得console的宽度有关）

**Comment by skywang00** [comment]
@rosynirvana 

很奇怪的是有些视频下载的时候没有进度条刷屏，有些又会刷屏，比如这个就不刷屏
> PS C:\Users\XXX> you-get http://v.youku.com/v_show/id_XMjc1MDg4NzgyNA==.html?spm=a2h1n.8261147.reload_1.1~3~A
> site:                优酷 (Youku)
> title:               寒武纪 01
> stream:
>     - format:        hd3
>       container:     flv
>       video-profile: 1080P
>       size:          499.3 MiB (523521823 bytes)
>     # download-with: you-get --format=hd3 [URL]
> 
> audio-languages:
>     - lang:          国语
>       download-url:  http://v.youku.com/v_show/id_XMjc1MDg4NzgyNA==
> 
> Downloading 寒武纪 01.flv ...
> 15.2% ( 75.7/499.3MB) ├██████─────────────────────────────────┤[ 2/15]   10 MB/s

其实像ykdl那样直接用 百分比 代替 进度条 也可以呀，或者固定一个较短的win console宽度，自动换行都行

**Comment by skywang00** [comment]
WIN10 1080p分辨率下默认的powershell 窗口大小会导致进度条刷屏，略微拉宽下窗口就不刷屏了

> Downloading 【新加坡版】 笑傲江湖 40集全 【2000】-17、17.flv ...
 0.1% (  0.2/214.9MB) ├─────────────────────────────────────────┤[1/1]  595 kB/
 0.2% (  0.5/214.9MB) ├─────────────────────────────────────────┤[1/1]    1 MB/
 0.3% (  0.8/214.9MB) ├─────────────────────────────────────────┤[1/1]    2 MB/
 0.5% (  1.0/214.9MB) ├─────────────────────────────────────────┤[1/1]    2 MB/
 0.6% (  1.2/214.9MB) ├─────────────────────────────────────────┤[1/1]    3 MB/
 0.7% (  1.5/214.9MB) ├─────────────────────────────────────────┤[1/1]    3 MB/
 0.8% (  1.8/214.9MB) ├─────────────────────────────────────────┤[1/1]    4 MB/
 0.9% (  2.0/214.9MB) ├─────────────────────────────────────────┤[1/1]    4 MB/
 1.0% (  2.2/214.9MB) ├█────────────────────────────────────────┤[1/1]    5 MB/
 1.2% (  2.5/214.9MB) ├█────────────────────────────────────────┤[1/1]    5 MB/
 1.3% (  2.8/214.9MB) ├█────────────────────────────────────────┤[1/1]    6 MB/
 1.4% (  3.0/214.9MB) ├█────────────────────────────────────────┤[1/1]    6 MB/
 1.5% (  3.2/214.9MB) ├█────────────────────────────────────────┤[1/1]    7 MB/
 1.6% (  3.5/214.9MB) ├█────────────────────────────────────────┤[1/1]    7 MB/
 1.7% (  3.8/214.9MB) ├█────────────────────────────────────────┤[1/1]    8 MB/
 1.9% (  4.0/214.9MB) ├█────────────────────────────────────────┤[1/1]    8 MB/
 2.0% (  4.2/214.9MB) ├█────────────────────────────────────────┤[1/1]    9 MB/
 2.1% (  4.5/214.9MB) ├█────────────────────────────────────────┤[1/1]    9 MB/
 2.2% (  4.8/214.9MB) ├█────────────────────────────────────────┤[1/1]   10 MB/
 2.3% (  5.0/214.9MB) ├█────────────────────────────────────────┤[1/1]   10 MB/
 2.4% (  5.2/214.9MB) ├█────────────────────────────────────────┤[1/1]   10 MB/
 2.6% (  5.5/214.9MB) ├█────────────────────────────────────────┤[1/1]   11 MB/
 2.7% (  5.8/214.9MB) ├█────────────────────────────────────────┤[1/1]   11 MB/
 2.8% (  6.0/214.9MB) ├█────────────────────────────────────────┤[1/1]   10 MB/
 2.9% (  6.2/214.9MB) ├█────────────────────────────────────────┤[1/1]   11 MB/
 3.0% (  6.5/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 3.1% (  6.8/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 3.3% (  7.0/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 3.4% (  7.2/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 3.5% (  7.5/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 3.6% (  7.8/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 3.7% (  8.0/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 3.8% (  8.2/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 4.0% (  8.5/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 4.1% (  8.8/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 4.2% (  9.0/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 4.3% (  9.2/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 4.4% (  9.5/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 4.5% (  9.8/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 4.7% ( 10.0/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 4.8% ( 10.2/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 4.9% ( 10.5/214.9MB) ├██───────────────────────────────────────┤[1/1]   11 MB/
 5.0% ( 10.8/214.9MB) ├███──────────────────────────────────────┤[1/1]  790 kB/
 5.1% ( 11.0/214.9MB) ├███──────────────────────────────────────┤[1/1]   11 MB/
 5.2% ( 11.2/214.9MB) ├███──────────────────────────────────────┤[1/1]   11 MB/
 5.4% ( 11.5/214.9MB) ├███──────────────────────────────────────┤[1/1]   11 MB/
 5.5% ( 11.8/214.9MB) ├███──────────────────────────────────────┤[1/1]   11 MB/
 5.6% ( 12.0/214.9MB) ├███──────────────────────────────────────┤[1/1]   11 MB/
 5.7% ( 12.2/214.9MB) ├███──────────────────────────────────────┤[1/1]   11 MB/
 5.8% ( 12.5/214.9MB) ├███──────────────────────────────────────┤[1/1]   11 MB/
 5.9% ( 12.8/214.9MB) ├███──────────────────────────────────────┤[1/1]   10 MB/
82.8% (178.0/214.9MB) ├██████████████████████████████████───────┤[1/1]    5 MB/s

**Comment by rosynirvana** [comment]
这个是已知问题，没必要贴这么多次

我感觉一点也不奇怪，毕竟python在win console上的问题有10年修不好的……

**Comment by lamlam123tld3** [comment]
if one ws cdn server blocks your ip address
simply switch to another known ws cdn server :)

**Comment by Invok3r** [comment]
@skywang00 关于进度条刷屏的问题，一个简单粗暴的方法是将 `you-get/src/you_get/common.py` 中的 `class SimpleProgressBar()` 里的 `self.bar_size` 的大小减小，在后面加个 `- 10` 好了。
