### ISSUE TITLE
是否可以实现下载同时转码？

### ISSUE THREAD

**Issue by sczhg** [soimort/you-get#2054]
请问有没有办法实现设置输出格式，如分辨率等，在录制直播视频的同时进行简单的转码？
我的想法是，在下载到硬盘的同时，开启另一个转码器进程，转码器每次发现视频有补充即对其转码。考虑到直播视频下载速度与转码器速度不一定哪个更快，不确定这种思路是否可以实现。
另一种思路是，假设转码速度大于下载速度，下载之后先在内存中实现转码，再保存到硬盘中，因此可能需要在程序内部添加中间件，请问这样是否可行？

**Comment by sczhg** [comment]
学习了一下相关部分的代码实现，看起来添加中间件的形式不实际，可能需要用其他方法实现了，

**Comment by rosynirvana** [comment]
可以啊
```you-get -u```然后交给```ffmpeg```就行了

**Comment by zywzyw1234567** [comment]
@rosynirvana 
说起来，有一个原理我不太明白诶。我看猎影还有apowersoft，包括优酷客户端这类的下载软件，一旦设置下载MP4格式，明明原始解析是FLV格式，最高的分辨率无损的，居然都是瞬间转码完成！而且下载时都不吃cpu和内存，风扇转动正常，说明不是下载同时转码的，那是什么原理啊，可以做到瞬间转码完成

**Comment by zywzyw1234567** [comment]
@rosynirvana
如何操作，能不能说得详细一点。
说起来，有一个原理我不太明白诶。我看猎影还有apowersoft，包括优酷客户端这类的下载软件，一旦设置下载MP4格式，明明原始解析是FLV格式，最高的分辨率无损的，居然都是瞬间转码完成！而且下载时都不吃cpu和内存，风扇转动正常，说明不是下载同时转码的，那是什么原理啊，可以做到瞬间转码完成

**Comment by rosynirvana** [comment]
@zywzyw1234567 因为不是转码啊(re-encode)，是再封装(remux)

**Comment by zywzyw1234567** [comment]
@rosynirvana 
嘻嘻，如果简单只是cmd几条公式命令的话，能不能教教我呀。

**Comment by rosynirvana** [comment]
用```ffmpeg``` remux还是别的？

```
ffmpeg -i INPUT_FILE -c copy OUT
```
INPUT_FILE是输入的文件，OUT是输出，要有扩展名

**Comment by zywzyw1234567** [comment]
@rosynirvana 
对，就是你说的再封装，不吃cpu那种。
也就是说，分段下载的文件，每一个都来用这条命令再封装，带扩展名，比如ffmpeg -i INPUT_FILE.flv -c copy OUT.mp4，对吧。如果是的话，有没批处理的命令

**Comment by rosynirvana** [comment]
没怎么看懂，分段下载的不一般是合并吗？为什么要每段都再封装？

**Comment by zywzyw1234567** [comment]
@rosynirvana 
原来如此，恍然大悟，是先合并再封装。我试了一下，很OK。不过文件名好像不能有空格，书名号之类的，否则会检测出非法字符。但那些软件封装后命名都不变的……是封装后程序再把原文件名加上去的么

**Comment by rosynirvana** [comment]
文件名可以有空格，```you-get```的重命名规则里就有，大概是你没处理好
不过为了最好的兼容性，文件名应该只用英文大小写、数字和下划线

**Comment by zywzyw1234567** [comment]
@rosynirvana 
了解了解。多谢了哈。
我还有一个问题，腾讯视频的lnk怎么嗅探到啊。你说的platform 11的getinfo getkey又是什么呀。

**Comment by rosynirvana** [comment]
嗅探？这个词是sniff翻译过来的，用相关工具抓包分析(browser devtools, charles, wireshark...)
getinfo getkey是腾讯视频的接口，platform 11是参数

**Comment by zywzyw1234567** [comment]
@rosynirvana 
哦，谢谢。Chrome用F12点network就能看getinfo，getvkey，里面有显示lnk。
不过那个视频，用lnk代替vid加入地址，打开一看另一个视频了。
lnk是o0023ndi9kh，vid是g0506r4ca9a，
https://v.qq.com/x/cover/e4th0v7bfha4rrf/g0506r4ca9a.html
https://v.qq.com/x/cover/e4th0v7bfha4rrf/o0023ndi9kh.html
看来这代码另有门道估计……

**Comment by rosynirvana** [comment]
qq的代码量非常大，不太像随便看看能解决的
如果你只是想下那个视频不在乎速度，把这个patch打上就行了
```diff
diff --git a/src/you_get/extractors/qq.py b/src/you_get/extractors/qq.py
index 4a9d5f8..6ea4747 100644
--- a/src/you_get/extractors/qq.py
+++ b/src/you_get/extractors/qq.py
@@ -7,9 +7,10 @@ from .qie import download as qieDownload
 from urllib.parse import urlparse,parse_qs
 
 def qq_download_by_vid(vid, title, output_dir='.', merge=True, info_only=False):
-    info_api = 'http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=' + vid
-    info = get_html(info_api)
+    info_api = 'http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=11&defnpayver=1&vid={}&cKey='.format(vid)
+    info = get_content(info_api)
     video_json = json.loads(match1(info, r'QZOutputJson=(.*)')[:-1])
+    fn_pre = video_json['vl']['vi'][0]['lnk']
     parts_vid = video_json['vl']['vi'][0]['vid']
     parts_ti = video_json['vl']['vi'][0]['ti']
     parts_prefix = video_json['vl']['vi'][0]['ul']['ui'][0]['url']
@@ -40,15 +41,13 @@ def qq_download_by_vid(vid, title, output_dir='.', merge=True, info_only=False):
                 # For fhd(1080p), every part is about 100M and 6 minutes
                 # try 100 parts here limited download longest single video of 10 hours.
                 for part in range(1,100):
-                    filename = vid + '.p' + str(part_format_id % 10000) + '.' + str(part) + '.mp4'
-                    key_api = "http://vv.video.qq.com/getkey?otype=json&platform=11&format=%s&vid=%s&filename=%s" % (part_format_id, parts_vid, filename)
-                    #print(filename)
-                    #print(key_api)
+                    filename = fn_pre + '.p' + str(part_format_id % 10000) + '.' + str(part) + '.mp4'
+                    key_api = "http://vv.video.qq.com/getkey?otype=json&platform=11&format=%s&vid=%s&filename=%s&cKey=&appver=3.2.19.333" % (part_format_id, parts_vid, filename)
                     part_info = get_html(key_api)
                     key_json = json.loads(match1(part_info, r'QZOutputJson=(.*)')[:-1])
                     #print(key_json)
                     vkey = key_json['key']
-                    url = '%s/%s?vkey=%s' % (parts_prefix, filename, vkey)
+                    url = '{}/{}?vkey={}'.format(parts_prefix, filename, vkey)
                     part_urls.append(url)
                     _, ext, size = url_info(url, faker=True)
                     total_size += size
```

**Comment by zywzyw1234567** [comment]
@rosynirvana 
这个补丁怎么打呀，diff这个命令是pip3的么，还是git的呀，哪里可以下载这个py替换也好

**Comment by rosynirvana** [comment]
https://raw.githubusercontent.com/rosynirvana/you-get/qq/src/you_get/extractors/qq.py

另：diff的用法是 git apply，或者照着改

**Comment by scegg** [comment]
缺点是这个下载到的清晰度很low。

**Comment by rosynirvana** [comment]
@scegg 你说哪个？

**Comment by scegg** [comment]
@rosynirvana 嗯？是你提供的代码。下载到的文件的码率是比较低的。

**Comment by rosynirvana** [comment]
你说码率还是分辨率？
```
Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1072, 717 kb/s, 25 fps, 25 tbr, 25k tbn, 50 tbc (default)
```

**Comment by scegg** [comment]
码率吧。分辨率还是那么大。文件尺寸不到200M。这个视频通常尺寸是600M+。

**Comment by scegg** [comment]
用你提供代码下载下来的文件：视频698kbps，音频63kbps。
原始代码下载到下一个文件：视频2493kbps，音频95kbps。

**Comment by rosynirvana** [comment]
AFAIK 腾讯视频的1080p不过1200K，而且国内视频网站只有pptv有所谓的高码视频

600MiB+ 大概是根据非在线的尺寸推算的吧

**Comment by scegg** [comment]
可自行尝试用原始版本下载：https://v.qq.com/x/cover/e4th0v7bfha4rrf/m0509jtzhrc.html

**Comment by rosynirvana** [comment]
YP

```
 $./you-get -u 'https://v.qq.com/x/cover/e4th0v7bfha4rrf/m0509jtzhrc.html'
Site:       QQ.com
Title:      【科技相对论】脑洞大？让漫威超级英雄们走进现实
Type:       MPEG-4 video (video/mp4)
Size:       541.91 MiB (568237215 Bytes)
```

**Comment by zywzyw1234567** [comment]
@rosynirvana 
谢谢啦。不过貌似只有这个qq视频的容量比较小，不到200M，同系列其它视频都是500M以上。分辨率都是1080P，好神奇。

**Comment by rosynirvana** [comment]
这个issue下面的问题应该都解决了
