### ISSUE TITLE
不能下载视频，为什么？

### ISSUE THREAD

**Issue by kof0012** [soimort/you-get#2055]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>you-get --debug http://video.tudou.com/v/XMjc5Nzg3MjQxMg=
=.html?t=1&recoid=12702833870023098204&itemid=14444850907559818066&seccateId=100
16&spm=a2h28.8313475.c1.dimg1
[DEBUG] get_content: http://video.tudou.com/v/XMjc5Nzg3MjQxMg==.html?t=1
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjc5Nzg3MjQxMg==&c
t=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjc5Nzg3MjQxMg==&c
t=12
you-get: [Failed] 客户端无权播放,201
'recoid' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'itemid' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'seccateId' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'spm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Administrator>

**Comment by andronoob** [comment]
你忘了加英文双引号，就是这个：
""
命令应该是这样：
you-get --debug **"**http://video.tudou.com/v/XMjc5Nzg3MjQxMg==.html?t=1&recoid=12702833870023098204&itemid=14444850907559818066&seccateId=10016&spm=a2h28.8313475.c1.dimg1**"**
注意，网址开头结尾加了英文双引号""
不能是中文的双引号“”

**Comment by kof0012** [comment]
谢谢！

在 2017-06-27 17:22:32，"andronoob" <notifications@github.com> 写道：


你忘了加英文双引号，就是这个：
""
命令应该是这样：
you-get --debug "http://video.tudou.com/v/XMjc5Nzg3MjQxMg==.html?t=1&recoid=12702833870023098204&itemid=14444850907559818066&seccateId=10016&spm=a2h28.8313475.c1.dimg1"
注意，网址开头结尾加了英文双引号""
不能是中文的双引号“”
