### ISSUE TITLE
Youku 客户端无权播放, 201

### ISSUE THREAD

**Issue by RogerFederer03** [soimort/you-get#2059]
@rosynirvana
I used lasted commits from https://github.com/soimort/you-get/pull/2015/commits, but I still have this error.

debug结果如下：

you-get -di http://v.youku.com/v_show/id_XMjc5ODQyMTQzNg==.html?spm=a2h0z.8244218.2371631.5
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjc5ODQyMTQzNg==&ccode=0401&client_ip=192.168.1.1&utid=1065c94f&client_ts=1496450673

you-get: 客户端无权播放,201

**Comment by RogerFederer03** [comment]
Actually I found using if I the snapshot of https://github.com/soimort/you-get/pull/2015/commits/413c39e1a40866af1231edd89ab0b3a6c9c586bb, the problem is fixed.

**Comment by rosynirvana** [comment]
I don't quite get it.
You mean which is fixed and which is still there?

**Comment by RogerFederer03** [comment]
@rosynirvana #2057 is still there, mine is fix by 413c39e. Sorry for the confusion.

**Comment by rosynirvana** [comment]
by > #2057 is still there

you mean that you've test that url and failed with code 201?

**Comment by RogerFederer03** [comment]
Yes

you-get -di http://v.youku.com/v_show/id_XMjc5Nzg2MzQ4MA==.html?spm=a2hzp.8253869.0.0
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjc5Nzg2MzQ4MA==&ccode=0401&client_ip=192.168.1.1&utid=0fe5c456&client_ts=1496451625
you-get: 客户端无权播放,201

**Comment by rosynirvana** [comment]
This problem has nothing to do with a specific url.
Under certain network env the client could fail to fetch a correct a ```cna``` cookie, which is a 24 bytes b64 string. 

But this should never happen with the latest commit. You sure that you tested it with the correct commit?

**Comment by RogerFederer03** [comment]
Sorry, I messed it up. I was running old python when testing #2057 , it should be fix by using 413c39e.

./you-get http://v.youku.com/v_show/id_XMjc5Nzg2MzQ4MA==.html?spm=a2hzp.8253869.0.0
site:                优酷 (Youku)
title:               袁视角 第48期.太平洋战争的导火索
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          196.0 MiB (205480661 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjc5Nzg2MzQ4MA%3D%3D&type=hd3&ups_client_netip=69.123.143.155&ups_ts=1496453769&utid=DOG4EdW4qzsCAbZyXbU%2Bt7Jt&ccode=0401&psid=7a0877d79aa28985addefe1199ef2c9d&ckey=&duration=1144&expire=18000&ups_key=f6b430e3161b3c5c16953a78c9ec2f0d
    # download-with: you-get --format=hd3 [URL]

Downloading 袁视角 第48期.太平洋战争的导火索.flv ...

**Comment by rosynirvana** [comment]
Then perhaps this issue can be closed?

**Comment by RogerFederer03** [comment]
Sure, closed.

**Comment by RogerFederer03** [comment]
Sure, closed.

**Comment by StLym** [comment]
有没有大佬解决了这个问题，换了几个youku.py也没用啊

**Comment by zeroxia** [comment]
Do you think this problem is fixed?

```
C:\Users\cece\sh\you-get>python you-get -di "http://v.youku.com/v_show/id_XMjgyNDIwNDUzMg==.html"
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjgyNDIwNDUzMg==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjgyNDIwNDUzMg==&ct=12
you-get: [Failed] 客户端无权播放,201

C:\Users\cece\sh\you-get>python you-get --version
you-get: version 0.4.750, a tiny downloader that scrapes the web.
```

The network is CNC in Shanghai.
