### ISSUE TITLE
有没有办法下载被youku屏蔽的视频

### ISSUE THREAD

**Issue by t785l4y** [soimort/you-get#2060]
C:\Users\Administrator>you-get http://v.youku.com/v_show/id_XMjUyMDQ3NDYwMA==.ht
ml
you-get: 该视频已被屏蔽，您可以尝试<a href="%s"><font color="#22B8FE"><u>搜索</u
></font></a>操作。

C:\Users\Administrator>

地址 http://v.youku.com/v_show/id_XMjUyMDQ3NDYwMA==.ht
ml

**Comment by zhangn1985** [comment]
高！！！

**Comment by soimort** [comment]
Closed via #2015.
