### ISSUE TITLE
Youtube下载限速？

### ISSUE THREAD

**Issue by mc2re4sa** [soimort/you-get#2068]
现在用you-get下载youtube视频的速度都是750 KB/s 左右
但我平时观看视频都是几MB/s
还有以前用的另外一个工具 当时用的时候也是全速下载 X MB/s
但是因为那个工具不是开源也不是很有名的 我比较担心安全性所以就没再继续用
所以我想请问 是you-get本身进行了限速 还是获取下载源的时候选择的路径不是最优的 还是说现在youtube进行了限制？
还有我想请问有手动限速的参数吗？

**Comment by rosynirvana** [comment]
```you-get```本身不限速也没有主动限速的参数

至于测速比较建议用-u输出url后然后用curl来做

**Comment by mc2re4sa** [comment]
@rosynirvana
谢谢
刚测试完-u发现DASH的视频源都好像都有限速 无论是用curl还是浏览器 都会一直降下去到700KB/s左右
相反 DEFAULT的就可以全速下载
不过我用aria2下载DASH的视频虽然降速了但也有3.55 MB/s的速度
不太懂网络 不清楚原因 希望大神可以解释下
最后想请问是不是要修改代码才能把下载方式改成第三方的下载工具？

**Comment by rosynirvana** [comment]
```aria2```默认是5个worker，和```curl```也是不应该直接比的

应该是用```you-get```输出的url和浏览器正常播放，然后抓包的url比，看看速度是不是一样的
如果UA referer都加上了还是比浏览器抓包的慢，那就是```you-get```找错了CDN

用第三方下载工具，最简单的情况下可以用```-p```传给下游。不过不一定实用，例如分段，再比如DASH的音画下载下来是两个文件还要另外合并一次。

**Comment by mc2re4sa** [comment]
@rosynirvana
`curl -o v.mp4 DASH_URL -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" -H "Referer: https://www.youtube.com"`
`Referer` 我试过加上 `/watch?v=` 一样被限速了
浏览器正常播放速度是 5 MB/s 左右

至于 `you-get` 应该没有找错CDN 因为我下载的时候是确切看到下载速度从全速一直降到 700 KB/s

不过看Youtube的 debug info 加载完了当前时间段的Buffer以后是没有网络活动的 只有到了没有Buffer的时间段才会全速 5 MB/s的下载该部分的Buffer
会不会是CDN对下载有"时间限制" 因为这才符合一个浏览器正常播放时加载Buffer的情况？

**Comment by rosynirvana** [comment]
要注意，不同软件的显示的速度是不能直接比较的。虽说这个速度指的一般都是拷贝到进程自己缓冲区的速度，但是实现细节不一样。例如```you-get```是读了一定字节数然后重新计算速度，大多数软件应该是在一定时间流逝后重新计算速度，但是这个时间片长度不一样。

速度下降如果特征不明显（例如下载了n MiB后速度明显下降），基本属于正常，因为一开始的几个时间片长度是不精确的，进程有更重要的事情要做，处理时间信号被延迟一些是很正常的。

正确的比较方法是从浏览器里抓出url，或者```copy as cURL```，再用curl来测速。

另外还有一个常见误区，就是瞬时速度是几乎没有任何意义的，如果一个进程唤醒得晚了一些瞬时速度就会暴涨，现代的桌面操作系统里进程调度很复杂所以是很常见的，浏览器这么复杂的应用更是如此。

**Comment by mc2re4sa** [comment]
@rosynirvana
我现在从`Chrome`的 `copy as cURL` 抓到的片段 我删掉 `&range=1759371-3696833` 以后 下载完整视频的速度是没有限制的
我尝试用同样的 `Header` 给 `you-get` 抓到的URL 就会出现限速的情况
`Chrome`抓到的和 `you-get` 是同一个CDN服务器 但多了不同的参数
最后我给 `you-get` 抓到的 URL 加上 `&ratebypass=yes` 然后速度就正常了 其他UA Referer的头不加也不影响
不知道后续更新会修复这个问题吗 毕竟抓完加上参数下载再分段合并那些还是挺麻烦的

**Comment by rosynirvana** [comment]
这要问作者soimort了，```youtube.py```应该是他一直在维护
