### ISSUE TITLE
iqiyi无法下载视频，求大神帮忙

### ISSUE THREAD

**Issue by t785l4y** [soimort/you-get#2069]
C:\Users\Administrator>you-get http://www.iqiyi.com/v_19rr6z5yl8.html
site:                爱奇艺 (Iqiyi)
title:               大胃王密子君_20170606期
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>

视频地址   http://www.iqiyi.com/v_19rr6z5yl8.html

**Comment by rosynirvana** [comment]
十有八九你没装ffmpeg

**Comment by t785l4y** [comment]
@soimort-bot 
C:\Users\Administrator>you-get --debug http://www.iqiyi.com/v_19rr6z5yl8.html
[DEBUG] get_html: http://www.iqiyi.com/v_19rr6z5yl8.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rr6z5yl8.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/693694000/bcc9b91c0e93a3f30a0
b9e0cb41036cb/?t=1496997679552&sc=7fab391a46591cf497e0af85b8911564&src=76f90cbd9
2f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               大胃王密子君_20170606期
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rr6z5yl8.html']
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\runpy.
py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\runpy.
py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\yo
u-get.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\you_get\common.py", line 1429, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\you_get\common.py", line 1342, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\you_get\common.py", line 1158, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\you_get\common.py", line 1422, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\you_get\extractor.py", line 52, in download_by_url
    self.download(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\you_get\extractors\iqiyi.py", line 204, in download
    merge=kwargs['merge'],)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\you_get\common.py", line 990, in download_url_ffmpeg
    assert has_ffmpeg_installed(), "FFmpeg not installed."
AssertionError: FFmpeg not installed.

C:\Users\Administrator>

**Comment by t785l4y** [comment]
@rosynirvana 
如何安装 ffmpeg

**Comment by zhangn1985** [comment]
https://ffmpeg.zeranoe.com/builds/

下载static  build，然后解压缩到 c:/windows/system32/

ffmpeg的路径是c:/windows/system32/ffmpeg.exe
