### ISSUE TITLE
爱奇异的视频ggmpeg nightly build 是什么意思？

### ISSUE THREAD

**Issue by kof0012** [soimort/you-get#2070]
C:\Users\Administrator>you-get --debug http://www.iqiyi.com/w_19ru5tb5lp.html
[DEBUG] get_response: http://www.iqiyi.com/w_19ru5tb5lp.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/7118218609/219f7922996e2a53c2
28afa2999926f6/?t=1497000528058&sc=bf257b308df4c4cb114c999e10cfa506&src=76f90cbd
92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               实拍：接到家门口的新娘 为弟弟的8800红包拒绝下车
stream:
    - format:        HD
      container:     m3u8
      video-profile: 540p
    # download-with: you-get --format=HD [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://cache.m.iqiyi.com/mus/7118218609/219f7922996e2a53c228afa
2999926f6/afbe8fd3d73448c9//20170101/65/3e/a2c61d53281206e3522e3b10512dbdc1.m3u8
?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=7118218609&bossStatus=0&qd_vip=
0&px=&qd_src=null&prv=&previewType=&previewTime=&from=&qd_time=1497000537867&qyp
id=7118218609_04022000001000000000_2&qd_k=bf257b308df4c4cb114c999e10cfa506&qd_hi
p=df49425b&qd_nsc=f79beba252a5c0aa0aab65aca5fba524&other= -c copy -bsf:a aac_adt
stoasc 实拍：接到家门口的新娘 为弟弟的8800红包拒绝下车.mp4
ffmpeg version N-86330-gbd1179e Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --e
nable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --
enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv
--enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-li
bfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug -
-enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enabl
e-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-li
bsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolam
e --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx
 --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable
-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 63.100 / 55. 63.100
  libavcodec     57. 96.101 / 57. 96.101
  libavformat    57. 72.101 / 57. 72.101
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 90.100 /  6. 90.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Input #0, hls,applehttp, from 'http://cache.m.iqiyi.com/mus/7118218609/219f79229
96e2a53c228afa2999926f6/afbe8fd3d73448c9//20170101/65/3e/a2c61d53281206e3522e3b1
0512dbdc1.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=7118218609&bossSt
atus=0&qd_vip=0&px=&qd_src=null&prv=&previewType=&previewTime=&from=&qd_time=149
7000537867&qypid=7118218609_04022000001000000000_2&qd_k=bf257b308df4c4cb114c999e
10cfa506&qd_hip=df49425b&qd_nsc=f79beba252a5c0aa0aab65aca5fba524&other=':
  Duration: 00:01:01.00, start: 0.000000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709)
, 896x504, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo,
 fltp
    Metadata:
      variant_bitrate : 0
瀹炴媿锛氭帴鍒板闂ㄥ彛鐨勬柊濞?涓哄紵寮熺殑8800绾㈠寘鎷掔粷涓嬭溅.mp4: Permiss
ion denied

C:\Users\Administrator>

**Comment by rosynirvana** [comment]
用nightly version的ffmpeg会强制用concat filter合并
和你遇到的permission denied关系不大
