### ISSUE TITLE
谁能帮我探测下这部视频的真实下载地址？

### ISSUE THREAD

**Issue by haoxuedezaza** [soimort/you-get#2071]
http://indavideo.hu/video/Szindbad_nyolcadik_utazasa_04_1985_Rajnai
谁能帮我探测下其真实地址，如果可以的话再告诉我具体怎么弄得，谢谢
@rosynirvana 希望这位大神能帮我

**Comment by cnbeining** [comment]
Please open this as feature request.

2017年6月9日 下午1:43，"haoxuedezaza" <notifications@github.com>写道：

**Comment by rosynirvana** [comment]
这视频失效被被网站删了吧？

**Comment by rosynirvana** [comment]
```
var a = "";
t && ($("#videopassword").val(""), a = md5(t));
var i = userdata && "undefined" != typeof userdata ? userdata.psid : "",
    o = service_host + "SYm0json.php/player.playerHandler.getVideoData/" + hash + "/12/" + a + "/" + i + "//?" + encodeURIComponent(hosted) + "&callback=?";
```

例如
```'http://amfphp.indavideo.hu/SYm0json.php/player.playerHandler.getVideoData/286f2df97b/12////?directlink&callback=jQuery31005001476233843347_1497049918783&_=1497049918784'```

访问这个url拿到一个json，里面有视频地址

**Comment by cracksuperstar** [comment]
@

**Comment by fendou2015** [comment]
@rosynirvana 请问o = service_host + "SYm0json.php/player.playerHandler.getVideoData/" + hash + "/12/
这段信息哪里能找到？

**Comment by rosynirvana** [comment]
一个叫```loadDatas```的函数，上面也贴出了一部分了，搜文本就是了

**Comment by airdge** [comment]
`http://assets.indavideo.hu/js/src/vplayer.6.js?d=5218694`

**Comment by fendou2015** [comment]
@rosynirvana查看网页源代码没找到loadDatas的东西

**Comment by fendou2015** [comment]
@airdge 你这连接是干嘛的

**Comment by rosynirvana** [comment]
一个eval出来的js，查看网页源代码当然看不到

**Comment by fendou2015** [comment]
@airdge 你的链接就是rosy说的eval吧，但是那一堆代码怎么提炼出o = service_host + "SYm0json.php/player.playerHandler.getVideoData/" + hash + "/12/这段信息

**Comment by airdge** [comment]
如果没编辑器 就到下面的地址
`http://tool.lu/js/`
解密美化下

**Comment by fendou2015** [comment]
@airdge 把http://assets.indavideo.hu/js/src/vplayer.6.js?d=5218694这里的丢进去解密美化好像也弄不出那段信息

**Comment by airdge** [comment]
@fendou2015 .... 是丢js里的源码进去

**Comment by fendou2015** [comment]
@airdge 找到了，感谢，解密美化后清楚多了，
话说抓地址找js拿去解密通用的吧
