### ISSUE TITLE
爱奇艺视频下载太慢的解决方法

### ISSUE THREAD

**Issue by zoubei** [soimort/you-get#2082]
我发现把ffmpeg的-re(在ffmpeg.py中)参数去掉，下载爱奇艺的速度就和youtube-dl一样飞快了，最后下载的文件没发现有问题，请问这样处理是正确的，当初为什么要加-re参数？

**Comment by rosynirvana** [comment]
作者应该是 @cnbeining ?
```-re```好像是推流用的

**Comment by caryyu** [comment]
# Description
It is extremely slow while i'm downloading this link (http://www.iqiyi.com/v_19rr74yels.html), it seems like that it is just downloading by playing i guess, so provide the related info below.

# Command Line Info
## you-get -V
```
you-get: version 0.4.750, a tiny downloader that scrapes the web.
```
## you-get -i http://www.iqiyi.com/v_19rr74yels.html 
```
site:                爱奇艺 (Iqiyi)
title:               奇葩说第4季_20170616期
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
    # download-with: you-get --format=TD [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
    # download-with: you-get --format=LD [URL]
```

## you-get --format=LD http://www.iqiyi.com/v_19rr74yels.html --debug
```
[DEBUG] get_response: http://www.iqiyi.com/v_19rr74yels.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/701270300/cb1e2d2c3969c39b2132f70a0b1e1a00/?t=1497622237058&sc=c2b3b9005c1b68744169e99b8914978f&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               奇葩说第4季_20170616期
stream:
    - format:        LD
      container:     m3u8
      video-profile: 210p
    # download-with: you-get --format=LD [URL]

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://cache.m.iqiyi.com/mus/206033301/6772e9ae65604e42d4f7c8c31c5b0d70/afbe8fd3d73448c9//20170616/81/5f/4285e02d87a2b730250bd63737140fca.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=701270300&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1497622237943&qypid=701270300_04022000001000000000_96&qd_k=c2b3b9005c1b68744169e99b8914978f&qd_hip=3d81b8d4&qd_nsc=d742ac29ff4f5085450c2acc1403826b&other= -c copy -bsf:a aac_adtstoasc 奇葩说第4季_20170616期.mp4
ffmpeg version 3.1.3 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.38)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.1.3 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --disable-lzma --enable-vda
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, hls,applehttp, from 'http://cache.m.iqiyi.com/mus/206033301/6772e9ae65604e42d4f7c8c31c5b0d70/afbe8fd3d73448c9//20170616/81/5f/4285e02d87a2b730250bd63737140fca.m3u8?np_tag=nginx_part_tag&qd_originate=tmts_py&tvid=701270300&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1497622237943&qypid=701270300_04022000001000000000_96&qd_k=c2b3b9005c1b68744169e99b8914978f&qd_hip=3d81b8d4&qd_nsc=d742ac29ff4f5085450c2acc1403826b&other=':
  Duration: 01:46:49.00, start: 0.000000, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 384x216, 15 fps, 15 tbr, 90k tbn, 30 tbc
    Stream #0:1: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 52 kb/s
[mp4 @ 0x7f8c8680bc00] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
    Last message repeated 1 times
Output #0, mp4, to '奇葩说第4季_20170616期.mp4':
  Metadata:
    encoder         : Lavf57.41.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p(tv, bt709), 384x216, q=2-31, 15 fps, 15 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (HE-AAC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 52 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
^Cframe=   69 fps= 15 q=-1.0 Lsize=      43kB time=00:00:04.53 bitrate=  78.6kbits/s speed=   1x    
video:13kB audio:27kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 8.405346%
Exiting normally, received signal 2.
```

**Comment by rosynirvana** [comment]
Expected behavior

**Comment by zoubei** [comment]
查看了ffmpeg的文档，-re参数似乎只是模拟直播流使用，没有其他的用处了。commit记录里cnbeining，在Jun 30, 2016的提交"Fix stream corrupted if Ctrl+C"加入了该参数，还请@cnbeining确认下这个参数是否有必要。

PS,这个仓库已经近一个月没更新了，很多网站已经失灵，作者太忙了吗？我用的是@rosynirvana的仓库了

**Comment by rosynirvana** [comment]
https://github.com/rosynirvana/you-get/commit/c2a6b30154b0e6cd409f4e7e21af2f197e9cb42c

改了一下，input是直播时候加```-re```，不然不加
另外这个branch里iqiyi的m3u8大多数时候应该不用ffmpeg下了

**Comment by BruceChen2017** [comment]
请问那个ffmpeg.py在哪？我在那个安装文件中找不到

**Comment by rosynirvana** [comment]
```src/you_get/processor/ffmpeg.py```

**Comment by cnbeining** [comment]
@zoubei ffmpeg在引入时是为了录制直播视频。的确可以加一个不同的function或argument。

**Comment by rosynirvana** [comment]
now https://github.com/rosynirvana/you-get/commit/c2a6b30154b0e6cd409f4e7e21af2f197e9cb42c is in the develop branch

**Comment by yuanchongfu** [comment]
Microsoft Windows [版本 10.0.15063]
(c) 2017 Microsoft Corporation。保留所有权利。

C:\Users\Administrator\Desktop>you-get http://www.iqiyi.com/v_19rr910u4s.html?list=19rrl4tiyu
site:                爱奇艺 (Iqiyi)
title:               中国新歌声第2季_20170915期
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      m3u8_url:      http://cache.m.iqiyi.com/mus/207600401/60a35f44fb4b0cd8e94e838857e9aa61/afbe8fd3d73448c9//20170914/40/ad/be3332e1a5f611cb0a6aea660dbb36d1.m3u8?qd_originate=tmts_py&tvid=788466400&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1505371122432&qd_p=7c58bd71&qd_asc=4546eca7c31ff4b92d6ba93d06887d0d&qypid=788466400_04022000001000000000_14&qd_k=b14929dc707992c2d5ecd69eebc9a278&vf=26d3b4307c23608b41effb3ca68b00b6&np_tag=nginx_part_tag
    # download-with: you-get --format=TD [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -i http://cache.m.iqiyi.com/mus/207600401/60a35f44fb4b0cd8e94e838857e9aa61/afbe8fd3d73448c9//20170914/40/ad/be3332e1a5f611cb0a6aea660dbb36d1.m3u8?qd_originate=tmts_py&tvid=788466400&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1505371122432&qd_p=7c58bd71&qd_asc=4546eca7c31ff4b92d6ba93d06887d0d&qypid=788466400_04022000001000000000_14&qd_k=b14929dc707992c2d5ecd69eebc9a278&vf=26d3b4307c23608b41effb3ca68b00b6&np_tag=nginx_part_tag -c copy -bsf:a aac_adtstoasc 中国新歌声第2季_20170915期.mp4
ffmpeg version N-87294-gec1573f Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 75.100 / 55. 75.100
  libavcodec     57.106.101 / 57.106.101
  libavformat    57. 82.100 / 57. 82.100
  libavdevice    57.  8.101 / 57.  8.101
  libavfilter     6.105.100 /  6.105.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
[hls,applehttp @ 00000000006c24a0] Opening 'http://data.video.qiyi.com/videos/v0/20170914/40/ad/4f30aa098b1df2e974a8ab37846d333e.dbts?qdv=1&qypid=788466400_04022000001000000000_14&start=0&end=1779420&contentlength=1779420&sd=1400&durr=8200&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1505371123816&qd_ip=7c58bd71&qd_p=7c58bd71&qd_k=b14929dc707992c2d5ecd69eebc9a278&qd_sc=85ec054d9e0e0741cfa1b3a36f36fb24' for reading
Input #0, hls,applehttp, from 'http://cache.m.iqiyi.com/mus/207600401/60a35f44fb4b0cd8e94e838857e9aa61/afbe8fd3d73448c9//20170914/40/ad/be3332e1a5f611cb0a6aea660dbb36d1.m3u8?qd_originate=tmts_py&tvid=788466400&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1505371122432&qd_p=7c58bd71&qd_asc=4546eca7c31ff4b92d6ba93d06887d0d&qypid=788466400_04022000001000000000_14&qd_k=b14929dc707992c2d5ecd69eebc9a278&vf=26d3b4307c23608b41effb3ca68b00b6&np_tag=nginx_part_tag':
  Duration: 00:11:55.00, start: 1.400000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1280x720, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: eac3 ([135][0][0][0] / 0x0087), 48000 Hz, stereo, fltp, 96 kb/s
    Metadata:
      variant_bitrate : 0
[AVBSFContext @ 00000000006d4480] Codec 'eac3' (86057) is not supported by the bitstream filter 'aac_adtstoasc'. Supported codecs are: aac (86018)
Error initializing bitstream filter: aac_adtstoasc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times

C:\Users\Administrator\Desktop>
