### ISSUE TITLE
在youtube里you-get默认下载的视频有肯能有MP4和wemb两种格式，我怎么指定一直下载MP4格式的呢

### ISSUE THREAD

**Issue by xiaoyuzhou** [soimort/you-get#2087]
请问在youtube里you-get默认下载的视频有肯能有MP4和wemb两种格式，我怎么指定一直下载MP4格式的呢

**Comment by xiaoyuzhou** [comment]
不要告诉我用you-get -i来看，然后选，我就想指定默认一直下MP4的，如果没有MP4格式视频，我选择不下载

**Comment by lirener** [comment]
写个bat...固定参数 然后+取剪切板url
路径也固定 每次就无脑 运行运行运行

**Comment by rosynirvana** [comment]
itag是固定的

**Comment by xiaoyuzhou** [comment]
讲的好，谢谢你们，加个微信多交流：微信号duanran
