### ISSUE TITLE
There was a problem with using you-get on the Ubuntu system.

### ISSUE THREAD

**Issue by pczhang93** [soimort/you-get#2089]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```

    
ubuntu@ubuntu-All-Series:~$ you-get -d http://www.56.com/w77/play_album-aid-14414684_vid-MTQ1MjE2MDk2.html
[DEBUG] get_content: http://www.56.com/w77/play_album-aid-14414684_vid-MTQ1MjE2MDk2.html
[DEBUG] get_response: http://my.tv.sohu.com/us/295869126/89898403.shtml
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.56.com/w77/play_album-aid-14414684_vid-MTQ1MjE2MDk2.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/w56.py", line 33, in w56_download
    sohu_download(sohu_url, output_dir, merge=merge, info_only=info_only, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/sohu.py", line 28, in sohu_download
    assert vid
AssertionError
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
这和你用ubuntu没关系

问题是你那里访问```http://my.tv.sohu.com/us/295869126/89898403.shtml```拿到的页面上找不到vid

```
$ curl 'http://my.tv.sohu.com/us/295869126/89898403.shtml' | grep vid
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0   	<meta property="og:videosrc" content="http://share.vrs.sohu.com/my/v.swf&topBar=1&id=89898403" />
    <meta property="og:type" content="video"/>
    <meta property="og:video" content="http://tv.sohu.com/upload/swf/20121030/PlayerShell.swf?autoplay=true&topBar=1&shareBtn=1&likeBtn=1&topBar=1&sogouBtn=0&id=89898403"/>
    <meta property="og:video:type" content="application/x-shockwave-flash"/>
		var vid = '89898403';
		var _videoInfo = {
	            ,vid: '89898403'
```

```
$ ./you-get -di 'http://www.56.com/w77/play_album-aid-14414684_vid-MTQ1MjE2MDk2.html'
[DEBUG] get_content: http://www.56.com/w77/play_album-aid-14414684_vid-MTQ1MjE2MDk2.html
[DEBUG] get_response: http://my.tv.sohu.com/us/295869126/89898403.shtml
[DEBUG] get_response: http://my.tv.sohu.com/play/videonew.do?vid=89898403&referer=http://my.tv.sohu.com
[DEBUG] get_response: http://data.vod.itc.cn/?prot=9&prod=flash&pt=1&file=&new=/181/152/37LROFkTSg6gti52DPAkLB.mp4&key=XTFG2I4c4GI_xLq_Ja9vsQuMpY6aaZQz&vid=89898403&uid=1497625986180&t=0.8295433413774221&rb=1
Site:       Sohu.com
Title:      《电影麦克疯之观影报告》60 重新审视张国荣最后一部作品，原来《异度空间》满满都是正能量
Type:       MPEG-4 video (video/mp4)
Size:       20.49 MiB (21480500 Bytes)
```

**Comment by pczhang93** [comment]
非常感谢您的帮助。




发自网易邮箱大师
在2017年06月16日 23:13，rosynirvana 写道：

这和你用ubuntu没关系

问题是你那里访问http://my.tv.sohu.com/us/295869126/89898403.shtml拿到的页面上找不到vid

$ curl 'http://my.tv.sohu.com/us/295869126/89898403.shtml' | grep vid
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0   	<meta property="og:videosrc" content="http://share.vrs.sohu.com/my/v.swf&topBar=1&id=89898403" />
    <meta property="og:type" content="video"/>
    <meta property="og:video" content="http://tv.sohu.com/upload/swf/20121030/PlayerShell.swf?autoplay=true&topBar=1&shareBtn=1&likeBtn=1&topBar=1&sogouBtn=0&id=89898403"/>
    <meta property="og:video:type" content="application/x-shockwave-flash"/>
		var vid = '89898403';
		var _videoInfo = {
	            ,vid: '89898403'

$ ./you-get -di 'http://www.56.com/w77/play_album-aid-14414684_vid-MTQ1MjE2MDk2.html'
[DEBUG] get_content: http://www.56.com/w77/play_album-aid-14414684_vid-MTQ1MjE2MDk2.html
[DEBUG] get_response: http://my.tv.sohu.com/us/295869126/89898403.shtml
[DEBUG] get_response: http://my.tv.sohu.com/play/videonew.do?vid=89898403&referer=http://my.tv.sohu.com
[DEBUG] get_response: http://data.vod.itc.cn/?prot=9&prod=flash&pt=1&file=&new=/181/152/37LROFkTSg6gti52DPAkLB.mp4&key=XTFG2I4c4GI_xLq_Ja9vsQuMpY6aaZQz&vid=89898403&uid=1497625986180&t=0.8295433413774221&rb=1
Site:       Sohu.com
Title:      《电影麦克疯之观影报告》60 重新审视张国荣最后一部作品，原来《异度空间》满满都是正能量
Type:       MPEG-4 video (video/mp4)
Size:       20.49 MiB (21480500 Bytes)

**Comment by cnbeining** [comment]
Closed due to issue not moving forward.
