### ISSUE TITLE
下载视频以后，会提示几个命令不存在。。'width' 'height' 'auto' 

### ISSUE THREAD

**Issue by wujiang9100** [soimort/you-get#2092]
'width' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'height' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'auto' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

我之前用过you-get，但是昨天在新电脑上安装，然后下载视频以后会出现这3条命令不存在，以前是不出现的。。

**Comment by rosynirvana** [comment]
把url加上引号……

**Comment by lamlam123tld3** [comment]
why not add this to wiki

**Comment by cnbeining** [comment]
Closed due to added to Wiki.
