### ISSUE TITLE
douyu失效

### ISSUE THREAD

**Issue by chacha1024** [soimort/you-get#2093]
- [ ] Please

 make sure these boxes are checked before submitting your issue – thank you!

- [√ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [√ ] Your `you-get` is up-to-date.
- [√ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [√ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [√ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get -p mpv http://douyu.com/danche --debug
[DEBUG] get_content: http://douyu.com/danche
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=339610
[DEBUG] get_content: http://coapi.douyucdn.cn/lapi/live/thirdPart/getPlay/339610?rate=0
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://douyu.com/danche']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1157, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/douyutv.py", line 37, in douyutv_download
    server_status = data.get('error',0)
AttributeError: 'list' object has no attribute 'get'
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

**Comment by rosynirvana** [comment]
看来要换到三月份被挖出来那个api了

**Comment by junges521** [comment]
斗鱼暂时被失效了吗？

**Comment by johnson-gc** [comment]
上礼拜五还能抓直播流的。。。斗鱼变的这么积极！！！有解决办法吗 @rosynirvana

**Comment by lamlam123tld3** [comment]
thirdPart 掛了唄
換回原始 lapi 吧

**Comment by jamiewq** [comment]
@lamlam123tld3 原始lapi是什么呀?

**Comment by rosynirvana** [comment]
一个700行的算法暂且还没看出是什么
要是有人急着用从issues里翻出来就是了，反正一时半会儿develop branch不会更新，没差别

**Comment by chacha1024** [comment]
斗鱼最近好像搞了很多的事情 弹幕协议变更 cdn改变 增加各种头衔礼物

**Comment by jamiewq** [comment]
@rosynirvana 求问大神是哪个issue呢？

**Comment by rosynirvana** [comment]
issues里搜斗鱼

**Comment by rosynirvana** [comment]
https://github.com/rosynirvana/douyu_cli

等哪天改到满意了再给其他项目写patch

**Comment by jamiewq** [comment]
@rosynirvana  douyu_cli 显示403错误，不知道有没有用对

**Comment by junges521** [comment]
斗鱼h5还能用

在 2017-06-19 23:41:19，rosynirvana <notifications@github.com> 写道：


https://github.com/rosynirvana/douyu_cli

等哪天改到满意了再给其他项目写patch

**Comment by rosynirvana** [comment]
403? 我没遇到过403

如果url里没有room id，比如```douyu.com/scboy```，也不会403吧

**Comment by jamiewq** [comment]
Oh, it works! @rosynirvana

**Comment by chacha1024** [comment]
@rosynirvana 我好像也是403 
贴个输出吧
Playing: http://hdl3.douyucdn.cn/live/52876rpx541uUfbR_900.flv?wsAuth=198bc28e058d9d7cbe6e66a66cb173fc
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://hdl3.douyucdn.cn/live/52876rpx541uUfbR_900.flv?wsAuth=198bc28e058d9d7cbe6e66a66cb173fc.
大概是这样

**Comment by rosynirvana** [comment]
script输出的url是这样的？

**Comment by chacha1024** [comment]
抱歉 好像是mpv的问题 自动会把后面一段给截断掉

**Comment by chacha1024** [comment]
用了其他方法似乎可以了 另外我想问一下这个api key是怎么申请到的？ 还是逆出来的？谢谢 @rosynirvana

**Comment by rosynirvana** [comment]
不是mpv的问题啊，是你的console会处理```&```这种特殊字符，url就变成几段了

比如
```
http://hdla.douyucdn.cn/live/56040rn4IgT2svpa_900.flv?wsAuth=be801d8ea5c7b9b02ecc0efc41879867&token=web-douyu-0-56040-43218feb8c13cfa443f71b8bdbb1bc5d&logo=0&expire=0&did=61CC1492419966624CE89F1521D25290&ver=2017061511
```

url整个作为数据的时候要引用，或者escape其中的特殊字符
```
mpv "http://hdla.douyucdn.cn/live/56040rn4IgT2svpa_900.flv?wsAuth=be801d8ea5c7b9b02ecc0efc41879867&token=web-douyu-0-56040-43218feb8c13cfa443f71b8bdbb1bc5d&logo=0&expire=0&did=61CC1492419966624CE89F1521D25290&ver=2017061511"
```

**Comment by chacha1024** [comment]
@rosynirvana 非常感谢 确实是这个问题 后来注意到了就解决了。

**Comment by rosynirvana** [comment]
https://github.com/rosynirvana/you-get/tree/master
现在用html5接口

**Comment by Alphat-PC** [comment]
stupidMD5加盐获取json的那段代码可用。。里面貌似有很多冗余。

**Comment by guest6379** [comment]
> https://github.com/rosynirvana/you-get/tree/master
现在用html5接口

@rosynirvana 从3月起，html5接口每5分钟好像就会失效

**Comment by TomatoFryEggs** [comment]
用iina的怎么解决？

**Comment by MagnifierSun** [comment]
用hls_url取到的视频AV画质啊。。用办法获取高清的地址吗

**Comment by rosynirvana** [comment]
项目地址上面贴了啊

https://github.com/rosynirvana/douyu_cli

**Comment by qiaokeke** [comment]
@rosynirvana 这个斗鱼api项目还没写完吗

**Comment by rosynirvana** [comment]
怎么定义写完？

现在能用

**Comment by zhangn1985** [comment]
@rosynirvana 我可以把你的code以MIT 协议集成在我的项目吗？

**Comment by rosynirvana** [comment]
@zhangn1985 可，那个项目也是MIT协议的，随便用吧

**Comment by notpaper** [comment]
@rosynirvana 请问douyu_cli里面的rate改成多少才能得到超清的地址，改成0的话和浏览器观看效果还是有差距，[效果对比](http://i.imgur.com/hJz9P8K.png)。

**Comment by rosynirvana** [comment]
1. 你改的是哪里
2. 打印出来的url是什么

**Comment by notpaper** [comment]
@rosynirvana `def douyu_api(rid, cdn='ws', rate='2'):
` 这里的rate值。
不改：
http://hdl3.douyucdn.cn/live/339610rB6lBtj2bQ_900.flv?wsAuth=355374a69648d048b4538399a6fa5e3f&token=web-douyu-0-339610-940c24d1b194e23cdeaba7bca16274e7&logo=0&expire=0&did=5E135A1831EA51A48CD6ECFD68588F04&ver=2017061511

改0：
http://hdl3.douyucdn.cn/live/339610rB6lBtj2bQ.flv?wsAuth=b5dda7efe70d9b29c422c9c034612b1f&token=web-douyu-0-339610-b8ed48c3502d11fb2f7467ec9462771a&logo=0&expire=0&did=FB4933B8D561B89724C60ECDC771842C&ver=2017061511

**Comment by rosynirvana** [comment]
那一行是默认值，不传rate的时候才有用

不过url看上去没什么问题

**Comment by notpaper** [comment]
@rosynirvana 昨天看Dota 2比赛才发现画质跟之前有差，不知道你那边有没有这个情况。

**Comment by rosynirvana** [comment]
你用的是哪个commit，还是你重写过处理cli的代码？

**Comment by notpaper** [comment]
@rosynirvana 最新的，没有重写。比如房间号60937，不妨试一下。

**Comment by rosynirvana** [comment]
试恐怕不能带来什么新的信息
斗鱼的 超清 高清 标清 分别对应的rate是0 2 1，抓包和反向flash都容易验证
直播的CDN在某些时候降码率也不是什么罕见的事情

**Comment by kira1928** [comment]
https://github.com/rosynirvana/douyu_cli/tree/12061e7bd871a25ed94e10dfc6203999c7256651
这个方法取到的url只能用不到10分钟，之后服务器会关闭连接。

**Comment by kira1928** [comment]
https://github.com/streamlink/streamlink/pull/1015
streamlink 也改成了这个只能下10分钟方法。

https://github.com/rg3/youtube-dl/issues/13419
youtube-dl也准备用这个只能下10分钟方法。

现在能找到的库都没有办法像以前一样录制无限长度的直播视频了。

**Comment by kira1928** [comment]
最新记录一个url撑了15分钟。。。

**Comment by rosynirvana** [comment]
我猜那个fish2是心跳包

**Comment by Justsoos** [comment]
用这个命令行来测 @rosynirvana 的api，不会出错。 --no-ytdl 是必须加的，防止mpv 偷偷用youtube_dl 去访问，用掉了斗鱼的token

`py douyu_api.py https://www.douyu.com/XXX | xargs mpv --no-ytdl`

另，斗鱼技术团队好变态啊，从来没安分超过3个月，一直在折腾。

**Comment by Justsoos** [comment]
@rosynirvana  刚测试你的api 看斗鱼直播，40分钟，没有断流。更长时间估计也没问题吧？

**Comment by Justsoos** [comment]
@rosynirvana  部分房间出问题：
douyu_api.py https://www.douyu.com/qianjia2015

返回的 json_data 为：
 {'data': [], 'error': -4}
程序输出为：
API returned with error -4

**Comment by rosynirvana** [comment]
修了

**Comment by hnliyuan** [comment]
@rosynirvana
 我将解析出来的地址用浏览器访问，返回403、

**Comment by hnliyuan** [comment]
@rosynirvana

https://www.douyu.com/fengtimo

解析出来的地址是 

[http://hdl3a.douyucdn.cn/live/71017rXvrKYDMGPc.flv?wsAuth=da28ae67431ec1fe5127c89b06381b3a&token=web-douyu-0-71017-e0114878169256bac4a56e29fcec6e0b&logo=0&expire=0&did=C67F5E1BF10EFE42F98D275ABCEEC2B1&ver=2017063001](url)

访问403

**Comment by rosynirvana** [comment]
注意地址只能访问一次

**Comment by hnliyuan** [comment]
@rosynirvana 
谢谢你，真专业。 确实如你所说

**Comment by Justsoos** [comment]
@rosynirvana 
这个api 是不是html5 斗鱼插件作者 @spacemeowx2 反向工程了斗鱼flash 出来的？https://github.com/spacemeowx2/DouyuHTML5Player

**Comment by rosynirvana** [comment]
是，```dy_prvt.py```文件开头有说明

**Comment by Justsoos** [comment]
@rosynirvana  斗鱼这个疯子网站，在这个活动页面里 
https://www.douyu.com/lolrr 加了一步跳转，又隐藏了所有 room_id ，用了
online_id":["288016","424559"]
其中 288016 是房间 id

**Comment by rosynirvana** [comment]
现在可以了
-r 424559 可以选第二页的房间

**Comment by Justsoos** [comment]
你这个 cli 越来越复杂了。哈哈，建议整理用法到 douyu_cli/README.md，普通观众都不会用了。
@rosynirvana

**Comment by rosynirvana** [comment]
本来只想堆代码的，最后还真成了个cli了

**Comment by hnliyuan** [comment]
@rosynirvana
能拿到斗鱼的m3u8地址吗？  
- - 为什么只有5分钟的。。 
    还不是高清

**Comment by rosynirvana** [comment]
抓包看到的api就是
```
GET 'https://m.douyu.com/html5/live?roomId={}'.format(room_id)
```

移动web端限时降质逼迫用户用app很常见

**Comment by Justsoos** [comment]
@rosynirvana 
说句现实却不太中听的话，you-get 不如合并到 youtube_dl 里去，那边每天都有版本更新，跟进bug速度更快，人也多 …… 这里作者貌似是现实事务繁重，无暇顾及

**Comment by spacemeowx2** [comment]
其实我在写一个 avm2 (直接执行 ActionScript bytecode)准备用来应对以后的算法更变, 3月的时候已经能执行简单的 abc 了, 后来在准备读取 swf 的文件时遇到了一些困难(主要是 flascc 生成的类似 ELF 的二进制数据)准备重构, 但是因为拖延症一直没重构完成, 后来又有一堆事拖到现在(现在还是没空...).

我觉得写一个简单的执行器也是个方案吧.

btw. @Justsoos 这两个许可不一样, 比如我那堆代码 you-get 就能用, youtube-dl 因为是 Unlicense 所以不能直接用 MIT 许可的代码

**Comment by Justsoos** [comment]
@spacemeowx2 斗鱼未必会一直这么变态下去，比如5分钟一变 key 的 m3u8 ，为了防盗链和录播等等。
至少曾经比如相当变态的自制协议的 YY 旗下的 huya，现在都是页面上随便可以扒出来的 flv 流，也基本没有防盗播设置了。

斗鱼全面 html5 的趋势应该正在进行中。哈哈，你抓swf 的未来可能暗淡ing

BTW，不知道谁实现了 yy.com 的直播流抓取。呵呵

**Comment by Justsoos** [comment]
@spacemeowx2  当然不是说直接搬代码过去。实际上，youtube_dl 也就是加这些网站的 extractors 的算法，其他下载和流媒体播放功能，you-get 和 youtube_dl 其实是同质化的。另外，把 you-get 这些人力搬运过去，合力搞一个。

总不至于，从各个视频网站上扒下来的取流算法也是要 MIT 许可的吧，呵呵

**Comment by rosynirvana** [comment]
从开发者的角度来看，you-get代码比youtube-dl简单很多，另外自己控制代码也比给别的项目提pull request有效多了

yy的hls很容易抓，但是连麦会出问题，不知道yy web端是怎么实现的
另外yy这flash播放器连个暂停都没有谁想出来的

**Comment by rosynirvana** [comment]
写一个flash的vm是不是工程量太大了些
redtamarin这种开发了有些年头的项目都感觉不行……

**Comment by Justsoos** [comment]
YY 才是中国最早最大的在线秀场，不加暂停键也有它的道理，直播不需要缓存。我没记错半年前虎牙还用的是 websocket 作的流，抓起来很麻烦，最近改成了flv 。比起作 swf 模拟器来说，ws 还简单点。
@rosynirvana 

you-get 还是算一个地区化（中文用户）作品，简单是简单，但能走向世界，稍微复杂点也有优势。还是有很多日本，韩国老外，看不懂中文you-get，能看懂youtube_dl 的啊

**Comment by rosynirvana** [comment]
结果就是想暂停的时候只能关页面了
也许只是因为私有协议的缘故没有去做

复杂的框架对于hobby project恐怕没什么优势
而且提取视频的主要工作是前端调试和flash逆向，you-get和youtube-dl却都是用py写的。对于一个前端而言，py可能会写但是没那么熟，如果py部分复杂那能参与进来的就少了
理想状态下可以前端公布算法，然后熟悉py的人来实现然后整合到项目里去，但现实情况下却经常是一两人一肩挑

**Comment by Justsoos** [comment]
是啊，私有协议很少有高手愿意跟进破解并公开的。
第一是，黑产那边如果想破，肯定早破了，私下卖钱。公开出来就不值钱了。
第二是，反向工程前端的活儿，很多人看不上这工作。

但很多普通用户还是希望有这些工具的，比如用 flv 流在 mpv 播放，比起网页带弹幕带广告播放卡的要死，能降低200%的cpu 。还有很多人下载收费vip的视频内容，放到自己mp4 上随身看，甚至还有人下载了存起来，卖硬盘 …… 

理想状态下，前端也不会公开算法，这涉及到太多网站的利益所在。现在比如斗鱼这些网站在疯狂制造算法难度，增加token，设置极短的失效期，其实，也就是为了保证自己的利益一点点不损失。

**Comment by rosynirvana** [comment]
具体到私有协议上，问题是“工作量大”，但“回报不够”吧

给普通用户用主要问题在于部署，典型例子是用emscripten的，提供一个能用的方案，工作时间大概是逆向算法的几十分之一都不到吧

**Comment by Justsoos** [comment]
其实 youtube_dl 和 you-get 能成立的基础是，众多视频网站用的都是差不多的解决方案。目前是 flv 向 html5 转型期。而且，基本都不算是收费视频，都是免费可看的。

私有协议有些回报太高，只能算黑产，比如 edusoho 的视频教学，据说收益相当高，呵呵。

这两者算是开发者，与网站的两个极端成本平衡区间。目前you-get主要工作量，其实就是一直在爱折腾的几个厂商，比如腾讯视频，斗鱼直播几个，他们在不断的修改播放锁定细节来禁录制和盗播。这已经玩到了上文提到的两者的中间地带。呵呵，比如反向工程斗鱼 flash，这已经算 “私有协议” 地区了。

**Comment by rosynirvana** [comment]
用差不多的解决方案是必然的，协议和底层控制在大厂商手里，例如Apple HLS，Adobe RMTP…… 网站不想太高的研发成本就要在上面实现。真正的私有协议只有yy当年的遗产。

**Comment by lki2019** [comment]
各位大神，在这里我求教大家一个问题啊，
斗鱼看的那幕的工具你们都用的哪款啊？
我用的这个https://github.com/littlecodersh/danmu  

在github找了几款 都不是很好用，就这款还可以，不过也不显示用户的等级 也不标记是电脑用户还是手机用户，

【电脑or手机】【用户等级】【昵称】内容

自动保存开始到关闭的弹幕记录到txt里，

这些小细节目前好像没有Python语言写的成品吧？
-----

另外有斗鱼直播间房管禁言查询记录的工具么？没找到

**Comment by hnliyuan** [comment]
@rosynirvana 
你好，请教一个问题。

我解析出来的斗鱼地址如下

http://hdl3a.douyucdn.cn/live/6540rm4aObC3KhRW.flv?wsAuth=2e316a3bb0530d5a8a6af597ea7f219d&token=web-douyu-0-6540-ce75cecba1796ee51ae64ac94b158192&logo=0&expire=0&did=E46BC6C8F05F3A3333837175CF2ADD25&ver=2017063001

访问后的地址如下

http://111.178.234.23/hdla.douyucdn.cn/live/940080rYbByyBJTv.flv?wsAuth=d14dfd0673da431a69f830cbc2ee8740&token=web-douyu-9814328-940080-5430ba0d8fd95fa93de69d2ae99644b4&logo=0&expire=0&did=FE33DAC8991C948EE013DCAF9EA81777&ver=2017071351&wshc_tag=0&wsts_tag=596b25aa&wsid_tag=af00777d&wsiphost=ipdbm


前一个地址有这样的设置：
Access-Control-Allow-Origin: https://www.douyu.com

后一个是 Access-Control-Allow-Origin: “*”

我把前一个地址放在浏览器中访问，浏览器会返回一个下载弹出框。 我可以点击下载。

但是把前一个地址放在ajax中访问，爆同源策略的错误。 

我如何才能拿到后一个地址呢？

**Comment by Justsoos** [comment]
@spacemeowx2  https://www.douyu.com/lapi/live/getPlay/  这个api 今天返回500了，哈，不知道是斗鱼抽风出错，还是改算法，封堵开始了。没想到你的swf 模拟器这么快就能用上了。

**Comment by lki2019** [comment]
是啊 好几个录像软件全部GG了，streamlink也挂了

**Comment by lki2019** [comment]
@Justsoos 现在录像或者本地播放用什么方法呢？

**Comment by amonker0** [comment]
@rosynirvana 好像搜狗浏览器可以录，他是什么原理

**Comment by rosynirvana** [comment]
用浏览器或者有一个flash rt怎么都行
从浏览器里面把api request copy as curl，然后用curl跑一遍再拿一个地址，至少前天测试的时候还是可以的
或者在随便哪个层面把斗鱼cdn的请求block掉，把浏览器api request返回的地址直接拿出来

web前端的事情总归不难，难的只是部署

**Comment by lamlam123tld3** [comment]
Use SlimmerJS or PhantonJS to get the request headers!

**Comment by soimort** [comment]
Closed via #2142.

**Comment by Justsoos** [comment]
https://gist.github.com/ERioK/d73f76dbb0334618ff905f1bf3363401

这个安卓 api 好用的，取出的是完整 flv，要合并就合并这个。 @soimort
