### ISSUE TITLE
无法下载腾讯视频~

### ISSUE THREAD

**Issue by liguge** [soimort/you-get#2098]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>you-get -i https://v.qq.com/x/cover/knxt06ujd9t8yai/d0023gnhqec.html
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>you-get -i http://v.qq.com/x/cover/knxt06ujd9t8yai/d0023gnhqec.html
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>you-get -i --debug http://v.qq.com/x/cover/knxt06ujd9t8yai/d0023ggnhqec.html
[DEBUG] get_response: http://v.qq.com/x/cover/knxt06ujd9t8yai/d0023ggnhqec.html
[DEBUG] get_response: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E1
9%2E333&platform=11&defnpayver=1&vid=k0023lkwp14
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&forma
t=10409&vid=k0023lkwp14&filename=k0023lkwp14.p409.1.mp4
[DEBUG] url_info: http://120.192.69.144/music.qqvideo.tc.qq.com/k0023lkwp14.p409
.1.mp4?vkey=F27478BBB50BDFA0ED7A293499E1D81AED0C11435F28096911FDF92AD9E4C7375E01
D423E0A3BB79470D4653FA7742ABB60F2DEF554AF4E16E39C4C86E2DB7BE789ECCDD8AE2174C97E0
7CFE975A04C130CF3F3681AF1E22CA70B0783E7C197A
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/x/cover/knxt06ujd9t8yai/d0023ggnhqec.html']
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\run
py.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\run
py.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts
\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1157, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\qq.py", line 163, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\qq.py", line 57, in qq_download_by_vid
    print_info(site_info, parts_ti, ext, total_size)
UnboundLocalError: local variable 'ext' referenced before assignment

C:\Users\Administrator>

**Comment by liguge** [comment]
@soimort-bot    I have updated，please~

**Comment by rosynirvana** [comment]
https://github.com/rosynirvana/you-get/tree/master

**Comment by hnliyuan** [comment]
@rosynirvana 
 能否支持腾讯视频的m3u8地址？ 
 我看到腾讯给出的是mp4 list列表，然后再合并
 能否拿到不需要合并的mp4地址？

**Comment by rosynirvana** [comment]
都可以
但是腾讯的网站分区太复杂了没人测试

**Comment by zhangn1985** [comment]
@rosynirvana 可以试试我的撞大运算法。

**Comment by rosynirvana** [comment]
@zhangn1985 我把web htm5 (platform 10901)的接口扒出来过，大概没什么问题，只是用的时候要从浏览器里面找guid

但是估计很多人会不看提示一直抱怨速度慢，所以不想提pr :(

**Comment by hnliyuan** [comment]
@rosynirvana 
  shit~  我听不懂你们在聊什么。

**Comment by hnliyuan** [comment]
@rosynirvana
我现在想学解析还有救吗？ 需要看哪些书打基础？ 烦请阁下指点迷途

**Comment by rosynirvana** [comment]
主要是web前端调试的技巧和经验

**Comment by rosynirvana** [comment]
```
$ ./you-get -i 'https://v.qq.com/x/cover/knxt06ujd9t8yai/d0023gnhqec.html'
Site:       QQ.com
Title:      李宗盛《第三者》（原唱：梁静茹）（超级版大事发声·李宗盛李剑青专场）
Type:       MPEG-4 video (video/mp4)
Size:       106.98 MiB (112181603 Bytes)
```
