### ISSUE TITLE
如何使用下载的：you-get-develop.zip

### ISSUE THREAD

**Issue by shanmm** [soimort/you-get#2103]
下载下来不知该如何使用，电脑安装了Python3.5。
安装步骤也没有看懂到底该如何安装，有人愿意教我一下吗？
https://github.com/soimort/you-get/archive/develop.zip

**Comment by shanmm** [comment]
哪个.py是主要运行文件？

**Comment by rosynirvana** [comment]
用pip3装，和现在的develop分支是一个版本

**Comment by shanmm** [comment]
只需要执行pip3 install you-get后就可以使用了？

**Comment by shanmm** [comment]
只需要执行pip3 install you-get后就可以使用了？ @rosynirvana

**Comment by shanmm** [comment]
执行python you-get后可以使用，谢谢你！
