### ISSUE TITLE
you-get: 客户端无权播放,201

### ISSUE THREAD

**Issue by geopapyrus** [soimort/you-get#2104]
I'm getting this error message a lot:
you-get: 客户端无权播放,201

I using you-get version 0.4.750

Example video link I'm trying to download: http://v.youku.com/v_show/id_XMTcyNDE2MDQxNg==.html?spm=a2h0j.8191423.item_XMTcyNDE13MDQxNg==.A

I was able to fix this problem a few days ago with this solution https://github.com/soimort/you-get/commit/413c39e1a40866af1231edd89ab0b3a6c9c586bb .

But now it broken again!

Anybody has been experiencing this?

thanks

**Comment by Six-wingedFallenAngel** [comment]
我前天正常，昨天遇到这个问题，用rosynirvana的修改版解决了问题。
首先git clone https://github.com/rosynirvana/you-get.git（如果之前没有clone过）或git remote set-url origin https://github.com/rosynirvana/you-get.git（之前clone过，在you-get目录下执行）
然后 git checkout youku
最后./you-get <URL>就行了

**Comment by yangxiang92** [comment]
Wow, it really works! @Six-wingedFallenAngel

**Comment by jyuan15** [comment]
@Six-wingedFallenAngel 请问这是怎么回事？

![2017-07-01_165746](https://user-images.githubusercontent.com/12642186/27760611-8e74d944-5e7e-11e7-985a-8f7f443118db.jpg)

**Comment by rosynirvana** [comment]
因为路径上存在一个非空的you-get文件夹啊

**Comment by jyuan15** [comment]
@rosynirvana 把那个文件夹删了重新git，但第二步貌似没成功啊。

![2017-07-01_173216](https://user-images.githubusercontent.com/12642186/27760840-79e21e56-5e83-11e7-8344-18e2d20efaab.jpg)

还有个问题，在Python34文件夹下还有个原版you-get，那用的时候究竟是调用的哪个？

**Comment by rosynirvana** [comment]
```
cd you-get
git checkout youku
```

和py的import path有关
2楼说的是在~/you-get目录下运行 ```./you-get```，不是直接运行```you-get```

**Comment by jyuan15** [comment]
@rosynirvana 多谢解答，我还是等原版更新解决吧

**Comment by rosynirvana** [comment]
上面还专门说了一遍
```
./you-get URL
```
不是
```
you-get URL
```

**Comment by jyuan15** [comment]
@rosynirvana 简直不明觉厉，问题是在那个路径下有evn.exe啊

![2017-07-01_185847](https://user-images.githubusercontent.com/12642186/27761563-de752e00-5e90-11e7-8137-3695e44b523b.jpg)

**Comment by rosynirvana** [comment]
mingw环境好多毛病
把入口脚本里的```/usr/bin/env python3```改成```/usr/bin/env python``` 不知道行不行

**Comment by jyuan15** [comment]
@rosynirvana 好像是这样，目录下只有个patch.exe，入口脚本是什么名字？哪个目录下？

**Comment by rosynirvana** [comment]
文件名就是```you-get```

mingw环境惹麻烦，```#!/usr/bin/env python3```这是标准的unix-like启动方法，但是win中的py3可执行文件名不是python3而是python

总而言之还是建议直接用win下面的python3，不要mingw这个间接层

**Comment by jyuan15** [comment]
@rosynirvana 成功了！非常感谢耐心解答~ 这个好，能封装成mp4，ykdl只是合并flv。

![2017-07-01_211505](https://user-images.githubusercontent.com/12642186/27762371-66907aa8-5ea3-11e7-9919-1fa5619b743c.jpg)

另外再请教一点：git不显示中文，我搜索过相关解决方法，说是把某个文件中加一行代码，但在ect目录下并没有那个文件，请问如何解决？

**Comment by rosynirvana** [comment]
不是git不显示中文啊，是你在用mingw……

**Comment by jyuan15** [comment]
@rosynirvana 不好意思，小白一枚。。。这个能显示中文吗？或者能把这个修改版用cmd来操作吗？

**Comment by rosynirvana** [comment]
用cmd，找对路径就行了

**Comment by jyuan15** [comment]
@rosynirvana 我去，正在兴头上，突然停电了(●—●)

**Comment by jyuan15** [comment]
@rosynirvana 谢谢，成功

**Comment by dvhhhh** [comment]
@Six-wingedFallenAngel   我用了你说的方法，但是显示是这个样子的，请问是哪里出错了吗？C:\Users\Administrator.PC-201612101328>git clone https://github.com/rosynirvana/you-get.git
'git' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by rosynirvana** [comment]
git是一个外部软件，不装git当然不行啊

**Comment by soimort** [comment]
Closed via #2015.
