### ISSUE TITLE
Bilibili 重写

### ISSUE THREAD

**Issue by rosynirvana** [soimort/you-get#2105]
https://github.com/rosynirvana/you-get/tree/master

实现了很多人一直想要的选择画质
虽说其实bilibili很多视频flv和hdmp4是同一画质区别只有容器

改了一个默认行为
下载某个aid内的所有视频必须加上```-l```，否则只下载一个cid的视频

```
$ ./you-get -il 'http://www.bilibili.com/video/av11580198/'
site:                Bilibili
title:               【虾玩】死期欲—人鱼事件【完结】 P1
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        flv
      container:     flv
      size:          188.1 MiB (197232837 bytes)
    # download-with: you-get --format=flv [URL]

    - format:        hdmp4
      container:     mp4
      size:          187.8 MiB (196898768 bytes)
    # download-with: you-get --format=hdmp4 [URL]

    - format:        mp4
      container:     mp4
      size:          190.8 MiB (200041870 bytes)
    # download-with: you-get --format=mp4 [URL]

site:                Bilibili
title:               【虾玩】死期欲—人鱼事件【完结】(2) P2
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        flv
      container:     flv
      size:          215.4 MiB (225847108 bytes)
    # download-with: you-get --format=flv [URL]

    - format:        hdmp4
      container:     mp4
      size:          215.1 MiB (225548152 bytes)
    # download-with: you-get --format=hdmp4 [URL]

    - format:        mp4
      container:     mp4
      size:          170.8 MiB (179075442 bytes)
    # download-with: you-get --format=mp4 [URL]

site:                Bilibili
title:               【虾玩】死期欲—人鱼事件【完结】(3) 补录的结局
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        flv
      container:     flv
      size:          43.8 MiB (45961971 bytes)
    # download-with: you-get --format=flv [URL]

    - format:        hdmp4
      container:     mp4
      size:          39.8 MiB (41700789 bytes)
    # download-with: you-get --format=hdmp4 [URL]

    - format:        mp4
      container:     mp4
      size:          20.0 MiB (20998958 bytes)
    # download-with: you-get --format=mp4 [URL]
```

```
$ ./you-get -i 'http://www.bilibili.com/video/av11580198/'
site:                Bilibili
title:               【虾玩】死期欲—人鱼事件【完结】
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        flv
      container:     flv
      size:          188.1 MiB (197232837 bytes)
    # download-with: you-get --format=flv [URL]

    - format:        hdmp4
      container:     mp4
      size:          187.8 MiB (196898768 bytes)
    # download-with: you-get --format=hdmp4 [URL]

    - format:        mp4
      container:     mp4
      size:          190.8 MiB (200041870 bytes)
    # download-with: you-get --format=mp4 [URL]
```

欢迎报告bugs

**Comment by shikkoku** [comment]
这个分支其他几个大站也合并到最新实验版本了？如果是 我直接全部覆盖原版凑合一下了。

**Comment by rosynirvana** [comment]
是
https://github.com/rosynirvana/you-get/commit/0b2d20aa13f72f4a97dbd4ce208c5368c8cb09cc
```Merge branches 'fix-bilibili-redirect', 'fix_acfun', 'fix_youtube_non_dash', 'iqiyi_testing', 'le_t', 'pptv', 'weibo' and 'youku'```
https://github.com/rosynirvana/you-get/commit/32e918e87b0b9b7d88955cda38da109a87b130a4
```Merge branch 'qq'```

乐视的文件头可能不对，别的应该没什么问题

**Comment by shikkoku** [comment]
`PS D:\Videos> you-get -il -c "D:\Downloads\cookies.txt" "http://www.bilibili.com/video/av11550004
12
site:                Bilibili
title:               时钟机关之星 [1 命运的齿轮]
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hdflv
      container:     flv
      size:          471.0 MiB (493855078 bytes)
    # download-with: you-get --format=hdflv [URL]

    - format:        flv
      container:     flv
      size:          320.9 MiB (336511787 bytes)
    # download-with: you-get --format=flv [URL]

    - format:        hdmp4
      container:     mp4
      size:          212.3 MiB (222652202 bytes)
    # download-with: you-get --format=hdmp4 [URL]

    - format:        mp4
      container:     mp4
      size:          100.6 MiB (105507303 bytes)
    # download-with: you-get --format=mp4 [URL]

12
site:                Bilibili
title:               时钟机关之星 [2 大支柱崩落]
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hdflv
      container:     flv
      size:          474.1 MiB (497165161 bytes)
    # download-with: you-get --format=hdflv [URL]

    - format:        flv
      container:     flv
      size:          320.5 MiB (336099756 bytes)
    # download-with: you-get --format=flv [URL]

    - format:        hdmp4
      container:     mp4
      size:          211.9 MiB (222197374 bytes)
    # download-with: you-get --format=hdmp4 [URL]

    - format:        mp4
      container:     mp4
      size:          100.3 MiB (105124790 bytes)
    # download-with: you-get --format=mp4 [URL]`

我指定了一个完结的12话新番的其中一话的链接，site上面的12是什么意思？是统计出这个番一共12个视频？

**Comment by rosynirvana** [comment]
一个debug输出忘了清了
现在好了

**Comment by saccohuo** [comment]
@rosynirvana 我试了一下您的repo，发现对于bilibili的专辑（按照“#page=[number]”来分页），只能下载到第一页的视频，请问这个是有没有办法解决呢？

**Comment by rosynirvana** [comment]
请先告诉我bilibili的专辑是什么

**Comment by saccohuo** [comment]
不好意思，我表达的可能不对，就是一系列视频的合集。比如这个：http://m.bilibili.com/video/av3141144/。

**Comment by rosynirvana** [comment]
现在好了
```
$ ./you-get -i --format=flv 'http://www.bilibili.com/video/av3141144/index_2.html#page=3'
site:                Bilibili
title:               【北师大精品课程】赵峥：广义相对论基础(3)
stream:
    - format:        flv
      container:     flv
      size:          57.0 MiB (59816607 bytes)
    # download-with: you-get --format=flv [URL]
```

**Comment by cnbeining** [comment]
推一个PR来吧 这个适合merge。

**Comment by RunningMatt** [comment]
1、l傻傻分不清 我不是一个人吧 [捂脸]

**Comment by rosynirvana** [comment]
#1698
cherry-pick出来的，估计有错，等人试试看

**Comment by saccohuo** [comment]
@rosynirvana 试过了，没有问题，太感谢了

**Comment by soimort** [comment]
Closed via #1698.
