### ISSUE TITLE
如何只拉取音频流

### ISSUE THREAD

**Issue by seyrenhe** [soimort/you-get#2106]
youtube-dl 有个audio only 选项,我都是用这个配合mpv晚上听某些直播入睡的,不过最近斗鱼换api了,导致youtube-dl用不了了,于是搜到了这个,并找到了一个可用的api,播放是可以播放了,现在的问题是用you-get -p mpv 会同时播放视频....能否在终端下只播放音频呢?

**Comment by rosynirvana** [comment]
你说
```
-x, --extract-audio              Convert video files to audio-only files (requires ffmpeg or avconv and ffprobe or avprobe)
```
这个flag? 后面的解释已经告诉你是怎么做的了
