### ISSUE TITLE
爱课程解析出来的URL能下载，但下回来的文件不完整

### ISSUE THREAD

**Issue by andronoob** [soimort/you-get#2108]
用-di参数能看到一个URL，但下载到15MB的时候就会停住。
直接用you-get下载，可以下载，但会报错。重复几次能下载完，但视频是损坏的，只能播放前几分钟。
C:\Users\user>C:\Python34\Scripts\you-get.exe --debug "http://www.icourses.cn/jpk/changeforVideo.action?resId=698762&courseId=6093"
[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=698762&courseId=6093
[DEBUG] Requesting video resource location...
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1498556540989&uuid=698762&other=
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_response: http://media1.icourses.cn:8080/process6/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process6/campus/processres/flv/2013/10/14/ff808081-41a53ee0-0141-b67bf8ed-00ec.flv?r=1498556696&h=Ihnuvtx9uQsxcC-AvafynA&lt=06-27%2F17%3A44%3A06&start=0&p=151020&lv=150606-1&ls=play
[DEBUG] url_info: http://media1.icourses.cn:8080/process6/campus/processres/flv/2013/10/14/ff808081-41a53ee0-0141-b67bf8ed-00ec.flv?r=1498556696&h=Ihnuvtx9uQsxcC-AvafynA&lt=06-27%2F17%3A44%3A06&start=0&p=151020&lv=150606-1&ls=play
[WARNING] Failed to fetch the video file! Retrying...
[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=698762&courseId=6093
[DEBUG] Requesting video resource location...
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1498556627081&uuid=698762&other=
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_response: http://media1.icourses.cn:8080/process6/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process6/campus/processres/flv/2013/10/14/ff808081-41a53ee0-0141-b67bf8ed-00ec.flv?r=1498586786&h=UjwD4zHt9MDE3cLzQodB4Q&lt=06-27%2F17%3A44%3A15&start=0&p=151020&lv=150606-1&ls=play
[DEBUG] url_info: http://media1.icourses.cn:8080/process6/campus/processres/flv/2013/10/14/ff808081-41a53ee0-0141-b67bf8ed-00ec.flv?r=1498586786&h=UjwD4zHt9MDE3cLzQodB4Q&lt=06-27%2F17%3A44%3A15&start=0&p=151020&lv=150606-1&ls=play
Site:       icourses.cn
Title:      生药学 第一讲 第1节 生药学的性质和任务
Type:       Flash video (video/x-flv)
Size:       104.56 MiB (109635741 Bytes)

Downloading 生药学 第一讲 第1节 生药学的性质和任务.flv ...
13.6% ( 14.2/104.6MB) ├██████───────────────────────────────────┤[1/1]  620 kB/s[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=698762&courseId=6093
[DEBUG] Requesting video resource location...
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1498556627388&uuid=698762&other=
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_response: http://media1.icourses.cn:8080/process6/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process6/campus/processres/flv/2013/10/14/ff808081-41a53ee0-0141-b67bf8ed-00ec.flv?r=1498556797&h=Jc0-voFNhUsckOcg51n7lA&lt=06-27%2F17%3A45%3A53&start=15204353&p=151020&lv=150606-1&ls=seek
27.5% ( 28.8/104.6MB) ├████████████─────────────────────────────┤[1/1]  245 kB/s[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=698762&courseId=6093
[DEBUG] Requesting video resource location...
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1498556760452&uuid=698762&other=
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_response: http://media1.icourses.cn:8080/process6/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process6/campus/processres/flv/2013/10/14/ff808081-41a53ee0-0141-b67bf8ed-00ec.flv?r=1498586997&h=nOqRT06M5r79kM42z9KZPA&lt=06-27%2F17%3A47%3A46&start=30408705&p=151020&lv=150606-1&ls=seek
41.4% ( 43.2/104.6MB) ├█████████████████────────────────────────┤[1/1]  821 kB/s[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=698762&courseId=6093
[DEBUG] Requesting video resource location...
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1498556766119&uuid=698762&other=
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_response: http://media1.icourses.cn:8080/process6/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process6/campus/processres/flv/2013/10/14/ff808081-41a53ee0-0141-b67bf8ed-00ec.flv?r=1498556936&h=kTv02rG8acqlb-rHC7iEdQ&lt=06-27%2F17%3A48%3A11&start=45613057&p=151020&lv=150606-1&ls=seek
55.2% ( 57.8/104.6MB) ├███████████████████████──────────────────┤[1/1]  443 kB/s[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=698762&courseId=6093
[DEBUG] Requesting video resource location...
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1498556834991&uuid=698762&other=
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_response: http://media1.icourses.cn:8080/process6/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process6/campus/processres/flv/2013/10/14/ff808081-41a53ee0-0141-b67bf8ed-00ec.flv?r=1498587091&h=XKh15QVBDpwKk0weJFZHXg&lt=06-27%2F17%3A49%3A20&start=60817409&p=151020&lv=150606-1&ls=seek
69.1% ( 72.2/104.6MB) ├█████████████████████████████────────────┤[1/1]  256 kB/s[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=698762&courseId=6093
[DEBUG] Requesting video resource location...
[DEBUG] get_response: http://www.icourses.cn/jpk/getResPlayInfo.action?IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&v=1498556920842&uuid=698762&other=
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] get_response: http://media1.icourses.cn:8080/process6/campus//ssl/ssl.shtml
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process6/campus/processres/flv/2013/10/14/ff808081-41a53ee0-0141-b67bf8ed-00ec.flv?r=1498556696&h=Ihnuvtx9uQsxcC-AvafynA&lt=06-27%2F17%3A50%3A26&start=76021761&p=151020&lv=150606-1&ls=seek
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.icourses.cn/jpk/changeforVideo.action?resId=698762&courseId=6093']
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1157, in download_main
    download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\extractors\icourses.py", line 34, in icourses_download
    total_size=size, output_dir=output_dir, refer=url, merge=merge, faker=True, ignore_range=True, chunk_size=15000000, dyn_callback=icourses_parser.icourses_cn_url_parser)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 909, in download_urls_chunked
    url_save_chunked(url, filepath, bar, refer = refer, faker = faker, headers = headers, **kwargs)
  File "C:\Python34\lib\site-packages\you_get\common.py", line 628, in url_save_chunked
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "C:\Python34\lib\site-packages\you_get\common.py", line 307, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by rosynirvana** [comment]
这个站就是在赌运气

**Comment by andronoob** [comment]
好像每次下回来都会卡在一个地方。如果每一次下回来的文件都一样，估计是这个站又搞了什么防下载的幺蛾子。
有空再试试……

**Comment by rosynirvana** [comment]
问题在于这个站点用的不是标准的HTTP协议
可以看```icourses.py```，可以说是整个项目里我见过的最漂亮的工作了
只是每个生成的url都要重试5次没有实现进去

**Comment by rosynirvana** [comment]
我的fork似乎更稳定一些
补了之前没实现的pinghost，修正了本地时间和请求服务器时间的随机值
清掉了不必要的代码

https://github.com/rosynirvana/you-get/tree/master

**Comment by rosynirvana** [comment]
用上面的fork还不行的请继续报告
客户端用的接口挖出来了，那个用不着私有协议

P.S. 据说爱课程的下载器一份卖400RMB ?

**Comment by rosynirvana** [comment]
比我想象中要稳定
网络不繁忙的时候连续下载几十个视频也没发生一次异常

87fb357
