### ISSUE TITLE
rosynirvana/you-get/master，某些bili视频无法下载

### ISSUE THREAD

**Issue by skywang00** [soimort/you-get#2109]
https://github.com/rosynirvana/you-get.git
某些bili视频无法下载，同时其他大部分bili视频都可以正常下载

> PS C:\Users\xx> you-get -id https://www.bilibili.com/video/av2884730/
> [DEBUG] url_locations: http://www.bilibili.com/video/av2884730/
> [DEBUG] get_content: http://www.bilibili.com/video/av2884730/
> you-get: version 0.4.750, a tiny downloader that scrapes the web.
> you-get: ['https://www.bilibili.com/video/av2884730/']
> Traceback (most recent call last):
>   File "C:\Users\xx\AppData\Local\Programs\Python\Python36-32\Scripts\you-get-script.py", line 11, in <module>
>     load_entry_point('you-get==0.4.750', 'console_scripts', 'you-get')()
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
>     main(**kwargs)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1478, in main
>     script_main('you-get', any_download, any_download_playlist, **kwargs)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1389, in scrip
> t_main
>     download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only,
> json_output=json_output, caption=caption)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1191, in downl
> oad_main
>     download(url, **kwargs)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1471, in any_d
> ownload
>     m.download(url, **kwargs)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractor.py", line 50, in down
> load_by_url
>     self.prepare(**kwargs)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\bilibili.py", line 1
> 23, in prepare
>     self.entry(**kwargs)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\bilibili.py", line 1
> 40, in entry
>     raise Exception('Unsupported page {}'.format(self.url))
> Exception: Unsupported page http://www.bilibili.com/video/av2884730/
> PS C:\Users\xx>

**Comment by rosynirvana** [comment]
因为要登录才能看

这个不是you-get已merge代码的问题，请不要新开issue

**Comment by skywang00** [comment]
@rosynirvana 

加载cookeis后，可以解析，但无法下载

> PS C:\Users\xx> you-get -c cookies.txt -d https://www.bilibili.com/video/av2884730/index_8.html
> [DEBUG] url_locations: https://www.bilibili.com/video/av2884730/index_8.html
> [DEBUG] get_content: https://www.bilibili.com/video/av2884730/index_8.html
> [DEBUG] get_content: http://interface.bilibili.com/playurl?cid=4507314&player=1&quality=3&ts=1498704721&sign=8211ab906d5
> dad44da8fe33bf97d87db
> [DEBUG] get_content: http://comment.bilibili.com/4507314.xml
> site:                Bilibili
> title:               【高清日剧】【木村拓哉】霸道总裁爱上我 月之恋人 MOON LOVERS【人人双语】(8)
> stream:
>     - format:        flv
>       container:     flv
>       size:          1236.4 MiB (1296452562 bytes)
>     # download-with: you-get --format=flv [URL]
> 
> Downloading 【高清日剧】【木村拓哉】霸道总裁爱上我 月之恋人 MOON LOVERS【人人双语】(8).flv ...
>  0.0% (   0.0/1236.4MB) ├───────────────────────────────────────────────
> ────────────────────────────────┤[1/1] you-get: version 0.4.750-testing, a tiny download
> er that scrapes the web.
> you-get: ['https://www.bilibili.com/video/av2884730/index_8.html']
> Traceback (most recent call last):
>   File "C:\Users\xx\AppData\Local\Programs\Python\Python36-32\Scripts\you-get-script.py", line 11, in <module>
>     load_entry_point('you-get==0.4.750', 'console_scripts', 'you-get')()
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
>     main(**kwargs)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1510, in main
>     script_main('you-get', any_download, any_download_playlist, **kwargs)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1394, in scrip
> t_main
>     download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only,
> json_output=json_output, caption=caption)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1178, in downl
> oad_main
>     download(url, **kwargs)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1498, in any_d
> ownload
>     m.download(url, **kwargs)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractor.py", line 86, in down
> load_by_url
>     self.download(**kwargs)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractor.py", line 281, in dow
> nload
>     av=stream_id in self.dash_streams)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 834, in downlo
> ad_urls
>     url_save(url, output_filepath, bar, headers=headers, **kwargs)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 587, in url_sa
> ve
>     assert received == os.path.getsize(temp_filepath), '%s == %s == %s' % (received, os.path.getsize(temp_filepath), tem
> p_filepath)
>   File "c:\users\xx\appdata\local\programs\python\python36-32\lib\genericpath.py", line 50, in getsize
>     return os.stat(filename).st_size
> FileNotFoundError: [WinError 2] 系统找不到指定的文件。: '.\\【高清日剧】【木村拓哉】霸道总裁爱上我 月之恋人 MOON LOVERS
> 【人人双语】(8).flv.download'
>

**Comment by rosynirvana** [comment]
https://github.com/rosynirvana/you-get/commit/6ce24ae0f1647a1867c745759554c37f818e269e

清url_size引入的bug

**Comment by skywang00** [comment]
OK，upgrade到最新的 rosynirvana/you-get/master 已经解决这个问题
