### ISSUE TITLE
bilibili获取到地址直接播放无法播放

### ISSUE THREAD

**Issue by zackzjc** [soimort/you-get#2110]
通过youget拿到地址后直接在播放器中播放，设置过header  Referer-bilibili.com,User-Agent-Mozilla/5.0,无法播放，怎么解决，不想下载看

**Comment by zackzjc** [comment]
C:\Users\zack>you-get http://www.bilibili.com/video/av8273152/ --json
{
    "site": "Bilibili",
    "streams": {
        "flv": {
            "container": "flv",
            "size": 143257957,
            "src": [
                "http://cn-zjwz2-dx-v-03.acgvideo.com/vg5/e/59/13609960-1.flv?expires=1498712700&platform=pc&ssig=O9d1IqJmtYoMbJQvjUn0VQ&oi=1927090218&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1&hfa=2070364331",
                "http://cn-zjwz2-dx-v-03.acgvideo.com/vg5/e/59/13609960-2.flv?expires=1498712700&platform=pc&ssig=2_96LK1_epiAB3oMRmnlSw&oi=1927090218&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1",
                "http://cn-zjwz2-dx-v-03.acgvideo.com/vg5/e/59/13609960-3.flv?expires=1498712700&platform=pc&ssig=wDJ56uowaYyuzsl0JjCWWw&oi=1927090218&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1",
                "http://cn-zjwz2-dx-v-03.acgvideo.com/vg5/e/59/13609960-4.flv?expires=1498712700&platform=pc&ssig=rkghDLZErpgKkKotJxVz3A&oi=1927090218&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1",
                "http://cn-zjwz2-dx-v-03.acgvideo.com/vg5/e/59/13609960-5.flv?expires=1498712700&platform=pc&ssig=79c4qIjc_S5mx9em4KmDyQ&oi=1927090218&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1",
                "http://cn-zjwz2-dx-v-03.acgvideo.com/vg5/e/59/13609960-6.flv?expires=1498712700&platform=pc&ssig=IqD4JSYgG9M7yU_c7jdzfw&oi=1927090218&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1",
                "http://cn-zjwz2-dx-v-03.acgvideo.com/vg5/e/59/13609960-7.flv?expires=1498712700&platform=pc&ssig=N1tKSwWMZqL9E71WmUpc_A&oi=1927090218&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1"
            ]
        }
    },
    "title": "【国产】亮剑 36集完整版【2005】",
    "url": "http://www.bilibili.com/video/av8273152/"

拿到网址直接播放播放不了

**Comment by rosynirvana** [comment]
抓包看看播放器送出去的http头对不对

**Comment by cnbeining** [comment]
Closed due to seems not moving forward?
