### ISSUE TITLE
[建议] 如何获取bilibili直接视频地址，而不进行不下载

### ISSUE THREAD

**Issue by fredhdx** [soimort/you-get#2113]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 用了最新的rosynirvana/you-get的更新，bilibili下载403问题解决。现在想知道有没有办法不下载视频，而是得到视频文件地址(可以外链至自己的网站，bilibili embed播放器太难看了)。
> 地区：美中，解析地址　http://ws.acgvideo.com 
> 一个蠢萌的问题：为什么一定要安装才能使用啊。不能直接./you-get吗(出现403问题)？ [舔 :icecream:!]

**Comment by rosynirvana** [comment]
```-u --json```都输出地址
只是访问要有正常的ua和referer

**Comment by fredhdx** [comment]
谢谢！请问怎么设置ua和referer呢？需要修改extractor*.py文件然后重新安装吗？

另外问一下正常的ua和referer指什么啊？

**Comment by fredhdx** [comment]
解析出来的都是ws.acgvideo.com的源，无法直接访问的。请问有什么办法么？下载时是怎么规避的啊？

**Comment by rosynirvana** [comment]
user-agent(ua for short)和referer都是http标准的东西
怎么设置取决于后端，和extractor没多大关系

ws.acgvideo.com和bilibili其他CDN现在没什么区别了，只是要转跳一次

建议去学一点http协议，不然就是绕圈子

**Comment by shikkoku** [comment]
@rosynirvana 话说你两天前更新的那个bilibili，进度条又刷屏了。

**Comment by rosynirvana** [comment]
@shikkoku 
我的fork把py3.0 - 3.2的支持去掉了，现在读控制台宽度是标准库的函数
win下面的刷屏我测试不了

**Comment by mogu1121** [comment]
@rosynirvana 
进度条更新慢，改哪个文件加快

**Comment by rosynirvana** [comment]
这一行
```
buffer = response.read(1024 * 1024)
```

数字改小了更新快

**Comment by soimort** [comment]
Closed via #1698.
