### ISSUE TITLE
乐视又改解析了。。。无法正确解析乐视的不同清晰度

### ISSUE THREAD

**Issue by skywang00** [soimort/you-get#2116]
昨天同一个视频还可以正确解析到大概1G的1080p版本的，现在解析到的是 960x544分辨率的

> PS C:\Users\XX> you-get -id http://www.le.com/ptv/vplay/30207022.html
> [DEBUG] url_locations: http://www.le.com/ptv/vplay/30207022.html
> [DEBUG] get_content: http://www.le.com/ptv/vplay/30207022.html
> [DEBUG] get_content: http://player-pc.le.com/mms/out/video/playJson?id=30207022&platid=1&splatid=101&format=1&tkey=24891
> 93839&domain=www.le.com&region=cn&source=1000&accesyx=1
> Current Video Supports:
>         --format 350 <URL>
>         --format 1000 <URL>
>         --format 1300 <URL>
>         --format 720p <URL>
>         --format 1080p <URL>
> [DEBUG] get_content: http://play.g3proxy.lecloud.com/vod/v2/MjQ5LzMxLzc0L2xldHYtdXRzLzE0L3Zlcl8wMF8yMi0xMTA3OTMyODc2LWF2
> Yy00MTkzMTYtYWFjLTQ4MDAwLTI3NDQxNjAtMTY0NDQxODQ3LTBlZWU1ODU0YWQ1NDUxNmM4MmRiZjM1NGM3MGUyZjBiLTE0OTg3MzI1NjI0OTUubXA0?b=4
> 79&mmsid=65597164&tm=1498838686&key=32a2ff41f2083b3a9c1f7b66246cfb70&platid=1&splatid=101&playid=0&tss=ios&vtype=13&cvid
> =1519759645005&payff=0&pip=dab7193150a9710fd083b667d64a7328&m3v=1&termid=1&format=1&hwtype=un&ostype=MacOS10.12.4&p1=1&p
> 2=10&p3=-&expect=3&tn=0.04916502879267781&vid=30207022&uuid=1791b720c43f3845079e4a1d3c5eb63d24aef941_0&sign=letv
> [DEBUG] get_content: http://115.238.243.40/249/31/74/letv-uts/14/ver_00_22-1107932876-avc-419316-aac-48000-2744160-16444
> 1847-0eee5854ad54516c82dbf354c70e2f0b-1498732562495.m3u8?crypt=28aa7f2e375&b=479&nlh=4096&nlt=60&bf=63&p2p=1&video_type=
> mp4&termid=1&tss=ios&platid=1&splatid=101&its=0&qos=3&fcheck=0&amltag=100&mltag=100&proxy=1945040403,3078878496,61124757
> 9&uid=1001343162.rp&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&ntm=1498857000&nkey=b89c49625e1d5b2
> 07f1581fdbc03007d&nkey2=dea8071e8e19537f0c0f463407fd7ee5&geo=CN-17-220-1&mmsid=65597164&tm=1498838686&key=32a2ff41f2083b
> 3a9c1f7b66246cfb70&playid=0&vtype=13&cvid=1519759645005&payff=0&m3v=1&hwtype=un&ostype=MacOS10.12.4&p1=1&p2=10&p3=-&tn=0
> .04916502879267781&vid=30207022&uuid=1791b720c43f3845079e4a1d3c5eb63d24aef941_0&sign=letv&uidx=0&errc=0&gn=1232&ndtype=0
> &vrtmcd=108&buss=100&cips=59.175.72.186&r=1498838687734&appid=500
> [DEBUG] url_info: http://115.238.243.40:80/249/31/74/letv-uts/14/ver_00_22-1107932876-avc-419316-aac-48000-2744160-16444
> 1847-0eee5854ad54516c82dbf354c70e2f0b-1498732562495_mp4/ver_00_22_0_0_794_138932_0_0.ts?mltag=100&platid=1&splatid=101&p
> layid=0&geo=CN-17-220-1&tag=-&ch=&p1=1&p2=10&p3=-&tss=ios&b=479&bf=63&nlh=4096&path=&sign=letv&proxy=1945040403,30788784
> 96,611247579&uuid=1791b720c43f3845079e4a1d3c5eb63d24aef941_0&ntm=1498857000&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVq
> e5bsXQpaGNn3T1-vhw..&its=0&nkey2=dea8071e8e19537f0c0f463407fd7ee5&uid=1001343162.rp&qos=3&enckit=&m3v=1&token=&vid=30207
> 022&liveid=&station=&app_name=&app_ver=&fcheck=0&pantm=&panuid=&pantoken=&cips=59.175.72.186&vod_live_path=&ledituid=&le
> ditcid=&leditcip=&leditfl=&leditafl=&ajax=&lsbv=
> Site:       Le.com
> Title:      一粒红尘31
> Type:       MPEG-4 video (video/mp4)
> Size:       169.68 MiB (177923952 Bytes)

**Comment by rosynirvana** [comment]
浏览器里面一样，返回的json里除了350之外都是一个链接，估计乐视视频要跑路了

**Comment by 602383883** [comment]
乐视分段的视频太多，一整个页面显示不下，最后把开始的地址覆盖掉了，想看到完整的怎么弄？

**Comment by rosynirvana** [comment]
@602383883 查“控制台重定向”

**Comment by 602383883** [comment]
@rosynirvana  意思就是说无法实现在cmd窗口内看到完整的，只能重定向到文件是吧。O(∩_∩)O谢谢

**Comment by rosynirvana** [comment]
cmd的最大缓存行数可以设置的
但是不如输出到文件里

**Comment by tulip33** [comment]
乐视只能下载960x540视频了

**Comment by rosynirvana** [comment]
乐视实际上只提供960x544了
除了350之外，其他都是960x544

**Comment by graminc** [comment]
贾跃亭要玩完了吗？
曾经输血过乐视的孙宏斌与范冰冰互撩了，
同为晋商山西帮的两位大佬，擅长PPT造势的贾跃亭牛B吹得震天响，家族套现100多亿，
目前来看还是孙大圣段位高

**Comment by nilaoda** [comment]
@rosynirvana 350口是什么平台的？

**Comment by rosynirvana** [comment]
350不是接口参数，是接口返回数据里的stream type
350 1000 1300 720p 1080p

**Comment by nilaoda** [comment]
@rosynirvana 这样啊 那我看到他们说的602 206 347什么的是什么呀？

**Comment by rosynirvana** [comment]
@soimort-bot test  http://www.le.com/ptv/vplay/30207022.html

**Comment by rosynirvana** [comment]
用美国ip依然有1080p
国内没了
我想当前的结论就是这样
