### ISSUE TITLE
youtube no sound

### ISSUE THREAD

**Issue by MaggieNgWu** [soimort/you-get#2125]
I can download vedios from youtube, but no sound.
you-get 'https://www.youtube.com/watch?v=rSevNnwmxPc'

**Comment by kidozh** [comment]
I use `you-get` to download this video and it actually have sounds. 

Yesterday I used it to download sources in u2b and no sound was finded. 

Maybe there are some tricks...

**Comment by soimort** [comment]
Please install `ffmpeg` so that DASH audio/video can be joined automatically.
