### ISSUE TITLE
[feature request] 网易云课堂（study.163.com）

### ISSUE THREAD

**Issue by lilydjwg** [soimort/you-get#213]
至少下面这个链接就是一堆优酷视频而已，不过不知道字幕在哪里：

http://study.163.com/plan/planLearn.htm?id=1270000

**Comment by cnbeining** [comment]
这个example很复杂，但是其他自行host的很简单。

还有多种source的例子吗？

**Comment by lilydjwg** [comment]
「多种source的例子」是指的什么呀？我应该没有遇到，因为我遇到 you-get 不了的视频都会来这里报告的。

**Comment by lki2019** [comment]
http://study.163.com/course/courseLearn.htm?courseId=681004#/learn/video?lessonId=833013&courseId=681004


http://study.163.com/course/introduction.htm?courseId=681004#/courseDetail?tab=1


貌似网易云课堂需要登陆，我随便用QQ登陆下看了下视频，好像没说明加密，直接可以下载的
http://study.163.com/course/introduction.htm?courseId=1040038#/courseDetail?tab=1
