### ISSUE TITLE
You-get on Homebrew is out-dated

### ISSUE THREAD

**Issue by ztytian** [soimort/you-get#2130]
$ brew install you-get
==> Using the sandbox
==> Downloading https://github.com/soimort/you-get/releases/download/v0.4.715/yo
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/5c/79/5dae7494b9f5ed061c
######################################################################## 100.0%
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/you-get-
==> python3 -s /tmp/you-get--homebrew-virtualenv-20170708-4032-11deyfj/target/bi
==> /usr/local/Cellar/you-get/0.4.715/libexec/bin/pip install -v --no-deps --no-
==> Caveats
To use post-processing options, `brew install ffmpeg` or `brew install libav`.
==> Summary
🍺  /usr/local/Cellar/you-get/0.4.715: 1,122 files, 9.9MB, built in 35 seconds

As shown, the latest version available on Homebrew is 0.4.715, while the most recent version, 0.4.750, is not.

Changing two lines in you-get.rb solves the issue.
  url "https://github.com/soimort/you-get/archive/v0.4.750.tar.gz"
  sha256 "8e10d8cd0442edef0345973404e37854db103954e784b78f95c8a1ce1b8690c1"

$ brew reinstall you-get
==> Reinstalling you-get 
==> Using the sandbox
==> Downloading https://github.com/soimort/you-get/archive/v0.4.750.tar.gz
==> Downloading from https://codeload.github.com/soimort/you-get/tar.gz/v0.4.750
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/5c/79/5dae7494b9f5ed061c
Already downloaded: /Users/Peter/Library/Caches/Homebrew/you-get--homebrew-virtualenv-15.0.2.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/you-get-
==> python3 -s /tmp/you-get--homebrew-virtualenv-20170708-5360-1qtrs88/target/bi
==> /usr/local/Cellar/you-get/0.4.750/libexec/bin/pip install -v --no-deps --no-
==> Caveats
To use post-processing options, `brew install ffmpeg` or `brew install libav`.
==> Summary
🍺  /usr/local/Cellar/you-get/0.4.750: 1,102 files, 9.9MB, built in 26 seconds
$ you-get --version
you-get: version 0.4.750, a tiny downloader that scrapes the web.

**Comment by ztytian** [comment]
Note that I'm using High Sierra beta so instead of using the bottled binary everything builds from scratch. Changing the two lines doesn't work on Sierra or below as the binaries are downloaded rather than built from source code.

**Comment by rosynirvana** [comment]
Please consider installing python3 with homebrew, then installing you-get with pip3.

you-get is a python 3 package without any native binaries so it should be managed with pip3 only. Homebrew should never touch it.

And more, a brew upgrade could ruin everything.

**Comment by ztytian** [comment]
Totally agree. Brew upgrade ruins everything. I have pip3 and python installed but I'm kinda used to Homebrew. Need some time to switch.

**Comment by soimort** [comment]
I believe it's updated now.

**Comment by ztytian** [comment]
Yes it is. Thx
