### ISSUE TITLE
QQ video wrong

### ISSUE THREAD

**Issue by dyz1996dyz** [soimort/you-get#2132]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[you-get -d https://v.qq.com/x/cover/hzgtnf6tbvfekfv/n0018iyaitl.html >1.txt
[DEBUG] get_response: http://v.qq.com/x/cover/hzgtnf6tbvfekfv/n0018iyaitl.html
[DEBUG] get_response: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=n0018iyaitl
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10209&vid=n0018iyaitl&filename=n0018iyaitl.p209.1.mp4
[DEBUG] url_info: http://182.254.110.27/vlive.qqvideo.tc.qq.com/n0018iyaitl.p209.1.mp4?vkey=AD5AEC45F64E89C1AC4BB6F77445DB15899FD91C2F01DA6192AD917A521DF66BD7657969FE4FBDF199D89E45214FA7E455FD1DBDAEDA2D708FF3B38E19C93B12F3F083AC5088EDCD8B97827B82F7073D07C4BE57D33B4B13E90A8E97663B0432
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/cover/hzgtnf6tbvfekfv/n0018iyaitl.html']
Traceback (most recent call last):
  File "c:\users\dyz_toga\appdata\local\programs\python\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dyz_toga\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\DYZ_TOGA\AppData\Local\Programs\Python\Python35\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\dyz_toga\appdata\local\programs\python\python35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\dyz_toga\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\dyz_toga\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\dyz_toga\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1180, in download_main
    download(url, **kwargs)
  File "c:\users\dyz_toga\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "c:\users\dyz_toga\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\qq.py", line 163, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "c:\users\dyz_toga\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\qq.py", line 57, in qq_download_by_vid
    print_info(site_info, parts_ti, ext, total_size)
UnboundLocalError: local variable 'ext' referenced before assignment]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by nobadboy** [comment]
这个问题我今天也发现了  然后去看了下代码 发现有一个问题 就是43行的这个 filename = vid + '.p' + str(part_format_id % 10000) + '.' + str(part) + '.mp4'
这个命名规则有问题不是所有的腾讯视频都是这样命名的所以产生这个问题，希望大神解决,应该从getinfo的那个json中获取filename，但是不会写代码
@rosynirvana

**Comment by rosynirvana** [comment]
原因是这个
```
$ curl 'http://vv.video.qq.com/getinfo?otype=json&appver=2E2%2E19%2E333&platform=11&defnpayver=1&vid=n0018iyaitl' | js-beautify | grep lnk
            "lnk": "h0020ulcdq2",
```

修腾讯要不代码量太大不值得，要不不好部署一堆人抱怨，所以我个人不会优先去修

**Comment by nobadboy** [comment]
希望 有能力的大神来修改吧

**Comment by lamlam123tld3** [comment]
get lnk from getinfo api
use lnk to fetch getvkey || getkey

**Comment by rosynirvana** [comment]
```
$ ./you-get -i 'https://v.qq.com/x/cover/hzgtnf6tbvfekfv/n0018iyaitl.html'
Site:       QQ.com
Title:      小兰也昏倒的浴室（前篇）_790
Type:       MPEG-4 video (video/mp4)
Size:       194.28 MiB (203717124 Bytes)
```
