### ISSUE TITLE
dailymotion download issue...

### ISSUE THREAD

**Issue by demonluo** [soimort/you-get#2134]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]
can't download age-restricted video...
http://www.dailymotion.com/video/x297zgk_%E8%8B%8D%E4%BA%95%E7%A9%BA%E6%98%AF%E8%B6%85%E7%BA%A7%E6%98%8E%E6%98%9F%E5%9C%A8%E4%B8%AD%E5%9B%BD_redband

**Comment by rosynirvana** [comment]
1. ```http://www.dailymotion.com/video/x297zgk_%E8%8B%8D%E4%BA%95%E7%A9%BA%E6%98%AF%E8%B6%85%E7%BA%A7%E6%98%8E%E6%98%9F%E5%9C%A8%E4%B8%AD%E5%9B%BD_redband``` -> ```x297zgk```

2. ```x297zgk``` -> ```http://www.dailymotion.com/embed/video/x297zgk?autoplay=1```

3. get the qualities JSON from the html

**Comment by rosynirvana** [comment]
```
$ ./you-get -di 'http://www.dailymotion.com/video/x297zgk_苍井空是超级明星在中国_redband'
[DEBUG] get_content: http://www.dailymotion.com/embed/video/x297zgk?autoplay=1
[DEBUG] url_info: http://www.dailymotion.com/cdn/H264-848x480/video/x297zgk.mp4?auth=1499845607-2562-qa2d3bqb-a4eebc772002530783b19392536085ac
Site:       Dailymotion.com
Title:      苍井空是超级明星在中国
Type:       MPEG-4 video (video/mp4)
Size:       31.75 MiB (33291132 Bytes)
```

fixed via https://github.com/soimort/you-get/commit/6d96300c732a1a7051c8d9c118104dfcecb5997a
