### ISSUE TITLE
香港无线电视TVB的优酷/土豆视频无法下载...

### ISSUE THREAD

**Issue by demonluo** [soimort/you-get#2135]
汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]
```
我测试了中港台日韩美的电视剧, 结果只有香港无线电视TVB的优酷/土豆视频无法下载...
eg,
EU超时任务
http://v.youku.com/v_show/id_XMTUwNzYwNzczMg==.html?lang=%E5%9B%BD%E8%AF%AD&from=s1.8-1-1.1
城寨英雄
http://v.youku.com/v_show/id_XMTY2NzU1MzM4NA==.html?lang=%E5%9B%BD%E8%AF%AD&from=s1.8-1-1.1
天眼
http://v.youku.com/v_show/id_XOTAzNDk2Mzgw.html?lang=%E5%9B%BD%E8%AF%AD&from=s1.8-1-1.1
鬼同你OT
http://v.youku.com/v_show/id_XMTI4NDIwMTQwMA==.html?lang=%E5%9B%BD%E8%AF%AD&from=s1.8-1-1.1
```

**Comment by rosynirvana** [comment]
dup #1249
