### ISSUE TITLE
这个视频能解析吗

### ISSUE THREAD

**Issue by zfl241** [soimort/you-get#2137]
http://www.med66.com/demo/zhiyeyaoshi/c706995-v101/#div_NODE70428900010100000101

C:\Users\zfl>you-get --debug "http://www.med66.com/demo/zhiyeyaoshi/c706995-v101/#div_NODE70428900010100000101"
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.med66.com/demo/zhiyeyaoshi/c706995-v101/#div_NODE70428900010100000101']
Traceback (most recent call last):
  File "C:\Users\zfl\AppData\Local\Programs\Python\Python36-32\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.750', 'console_scripts', 'you-get')()
  File "c:\users\zfl\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\zfl\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\zfl\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\zfl\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1157, in download_main
    download(url, **kwargs)
  File "c:\users\zfl\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1436, in any_download
    m, url = url_to_module(url)
  File "c:\users\zfl\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1428, in url_to_module
    res = conn.getresponse()
  File "c:\users\zfl\appdata\local\programs\python\python36-32\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "c:\users\zfl\appdata\local\programs\python\python36-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "c:\users\zfl\appdata\local\programs\python\python36-32\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "c:\users\zfl\appdata\local\programs\python\python36-32\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by rosynirvana** [comment]
写起来好麻烦

**Comment by rosynirvana** [comment]
白费力气 :<

```http://www.med66.com/demo/zhiyeyaoshi/c706995-v101/#div_NODE70428900010100000101``` -> 
```http://m.med66.com/demo/zhiyeyaoshi/c706995-v101/#div_NODE70428900010100000101``` 

然后直接从静态页里面找m3u8就行了

**Comment by zfl241** [comment]
静态页里面找的m3u8，下载不下来

**Comment by rosynirvana** [comment]
key很快会失效，如果中间哪里手动操作了，记得要快

**Comment by zfl241** [comment]
好像手不够快，可要怎么操作呢 @rosynirvana

**Comment by rosynirvana** [comment]
用上面贴出来的script

**Comment by zfl241** [comment]
>med66.py -d "http://www.med66.com/demo/zhongyaoshi/c705526-v1011/#div_NODE70385300101100000101"
ffmpeg version N-79068-g6b7ce0e Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmfx --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 19.100 / 55. 19.100
  libavcodec     57. 28.103 / 57. 28.103
  libavformat    57. 28.102 / 57. 28.102
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 39.102 /  6. 39.102
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, hls,applehttp, from 'http://117.41.244.14/ssec.chinaacc.com/1499666390691/5oI.AJUbrzvgmmjijHS.4TtelodNwSBNZCH.LerjDXJHQnk7IiKM7.dDHoCjV6I2MTikCB-cI4s_.mp4/index.m3u8?cwareID=705526&videoID=1011&userID=null&time=1499666390691&code=5bb6d72333f7ce30f87fe5e5d84a1a69&host=elearning.med66.com&sid=':
  Duration: 00:37:01.08, start: 0.181000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 760x428 [SAR 856:855 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 27 kb/s
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
Output #0, mp4, to '0.mp4':
  Metadata:
    encoder         : Lavf57.28.102
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 760x428 [SAR 856:855 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 27 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 034a8620] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
av_interleaved_write_frame(): Operation not permitted
frame=   10 fps=0.0 q=-1.0 Lsize=       2kB time=00:00:00.28 bitrate=  61.6kbits/s speed=N/A
video:1kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 50.069637%
Conversion failed!

**Comment by rosynirvana** [comment]
> [mp4 @ 034a8620] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)

这个应该在新版的ffmpeg里已经修了，升ffmpeg吧

**Comment by redstoneleo** [comment]
bc

**Comment by zfl241** [comment]
从静态页里面找m3u8后可以直接下载吗

**Comment by rosynirvana** [comment]
问题怎么绕回去了，怎么定义直接下载？总要找个实现了HLS协议的工具吧

**Comment by lki2019** [comment]
这个站，丝毫没难度，你只需要装个浏览器嗅探插件或者F12 搜m3u8 抓出M3U8地址，然后随便找个m3u8下载工具就可以了
他的收费课程理论上也没难度，不是什么AES加密之类的。

http://www.med66.com/zhuanti/2012ysysgqkc/index.shtml 反正免费试听课 都可以下载

**Comment by rosynirvana** [comment]
Inactive for more than one month
