### ISSUE TITLE
如何生成cookies.txt以便于you-get下载vip视频

### ISSUE THREAD

**Issue by BruceChen2017** [soimort/you-get#2148]
比如说我有优酷vip，打开vip视频，如果没加相应cookie的话就只能下载试看片段。

**Comment by shikkoku** [comment]
Chrome装上这个扩展https://chrome.google.com/webstore/detail/njabckikapfpffapmjgojcnbfjonfjfg，然后点击图标。其中有一段To download this content click here。点击download字样的超链接下载文件。Firefox也有相应的扩展。

**Comment by BruceChen2017** [comment]
@shikkoku 我确实用过这个插件，也确实可行。但是我是只想要当前网页的cookies，这个插件却是把所有网站的cookie都包含在内。我也尝试过`editthiscookie`这个插件，但是它生成的cookie文件对you-get无效

**Comment by lamlam123tld3** [comment]
用F12 dev took 把request header 里面的cookie抄出來就行

**Comment by BruceChen2017** [comment]
@lamlam123tld3 不行啊 那不是标准格式啊 你试过没？

**Comment by rosynirvana** [comment]
手动删
用```http.cookiejar```把匹配的cookie找出来也要不了几行

**Comment by shikkoku** [comment]
@rosynirvana 话说进度条刷屏的解决方案有进展了吗。

**Comment by rosynirvana** [comment]
@shikkoku 

我重复不了这个，所以不能指望我去解决……

**Comment by BruceChen2017** [comment]
@rosynirvana 求教用http.cookiejar怎么生成？我看了官方文档也搞不懂...平时要获取登陆后的页面，我也就是把chrome 开发者工具中看到的request header的cookie添加到python的request header中
