### ISSUE TITLE
zhanqi 战旗失效了

### ISSUE THREAD

**Issue by guest6379** [soimort/you-get#2152]
最新版本的you-get
`you-get: version 0.4.775`

error message shown as below, 错误信息如下：
`http://wshdl.load.cdn.zhanqi.tv/zqlive/211017_1tAeE.flv?wshc_tag=0&wsiphost=ipdbm: Server returned 403 Forbidden (access denied)`

战旗最近也加了key验证，以前的方法直接获取VideoId拼接VideoUrl的方法失效了。

**Comment by rosynirvana** [comment]
试试这个
#2153

**Comment by guest6379** [comment]
@rosynirvana

谢谢，我现在暂时在用m3u8的方式，但是m3u8的流地址容易出现50X的错误，解析是能得到地址，但不是每次都能请求成功。

所以如果能够得到flv的地址加key就最好了

```
m3u8 = "xxxxxxxxxxxxxxxxxxxx"
ffplay -i ${m3u8_url} 
```

**Comment by rosynirvana** [comment]
50x是什么？

**Comment by guest6379** [comment]
ffplay -i ${m3u8_url} 的时候，明显感觉比原来的flv地址获取视频慢，有时候还会出现 502 错误，无法播放视频。
我在手机上的浏览器抓包试了下，也是默认的m3u8地址，但也会出现视频无法播放的情况，出现50X错误，猜测m3u8的服务器比flv的不稳定，所以想如果能破解flv的地址和key就好了。
