### ISSUE TITLE
希望能支持twitcasting

### ISSUE THREAD

**Issue by jyuan15** [soimort/you-get#2155]
http://twitcasting.tv

一个直播网站

**Comment by lki2019** [comment]
额，网页版也没？

**Comment by lki2019** [comment]
http://twitcasting.tv/fm_yokote

测试了下，还行
![qq 20170812110645](https://user-images.githubusercontent.com/30022431/29237322-88a04044-7f4e-11e7-8021-7a4d01318498.png)

**Comment by jyuan15** [comment]
@lki2019 能加到you-get里面吗？

**Comment by lki2019** [comment]
得有人写extractors才可以

**Comment by jyuan15** [comment]
@rosynirvana 来看看。。。

**Comment by rosynirvana** [comment]
要知道，对于单个stream抓包，和提供通用的解决方案差别还是很大的

**Comment by lki2019** [comment]
https://github.com/soimort/you-get/issues/198

重复的请求
