### ISSUE TITLE
freebsd mac os x 安装出错 

### ISSUE THREAD

**Issue by flfq** [soimort/you-get#2159]
freebsd mac os x 
python 2.7
pip install you-get 
均出现
` pip install you-get
Collecting you-get
  Downloading you-get-0.4.775.tar.gz (125kB)
    100% |████████████████████████████████| 133kB 120kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vF9AUF/you-get/setup.py", line 10, in <module>
        proj_info = json.loads(open(os.path.join(here, PROJ_METADATA), encoding='utf-8').read())
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vF9AUF/you-get/
`

**Comment by gonejack** [comment]
不要用pip install you-get，用brew install you-get

**Comment by rosynirvana** [comment]
在一个能用brew的环境里pip根本装不了，因为pip指的是pip2但you-get是python3 only的
用brew装是不推荐的
