### ISSUE TITLE
优酷视频又无法下载了。

### ISSUE THREAD

**Issue by 614567264** [soimort/you-get#2175]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]优酷网所有视频都无法下载，跟上个月那次错误603一样，这次失败的代码是错误201。上次是将#2015的youku.py和extractor.py替换同名文件解决了，现在失效了，能否请大神再修复下接口？
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
升级到develop branch

**Comment by 614567264** [comment]
升级是要怎样操作呢，小白不懂，能说一下么 拜托了

**Comment by rosynirvana** [comment]
首先，确保你现在环境中的you-get是正确安装的

正确安装指的是：
1. 用pip3安装
2. 没有多份python环境

然后
```pip3 install --upgrade https://github.com/soimort/you-get/archive/develop.zip```

注意在某些环境中，pip3不存在，要把pip改成pip

如果你一定要像之前一样换文件，地址是
```
https://raw.githubusercontent.com/soimort/you-get/develop/src/you_get/extractors/youku.py
```
替换you-get本地位置的```extractors/youku.py```

**Comment by 614567264** [comment]
解决了    把压缩包里面的文件换过去就成了  谢谢
