### ISSUE TITLE
优酷下载错误

### ISSUE THREAD

**Issue by saku1119** [soimort/you-get#2176]
汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [X ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [X ] 您的`you-get`为最新版.
- [ X] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [X ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ X] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get: version 0.4.775, a tiny downloader that scrapes the web.

>you-get -i -c cookies.txt http://v.youku.com/v_show/id_XMjkwNzMxMjIyNA==.html
you-get: Found cna in imported cookies. Use it
you-get: 客户端无权播放,201
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

>you-get -i -d -c cookies.txt http://v.youku.com/v_show/id_XMjkwNzMxMjIyNA==.htm
l
you-get: Found cna in imported cookies. Use it
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjkwNzMxMjIyNA==&cc
ode=0401&client_ip=192.168.1.1&utid=AaCcEaqtywgCAXDtEqM%2B%2BCFP&client_ts=15006
39335
you-get: 客户端无权播放,201
you-get: version 0.4.775, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjkwNzMxMjIyNA==.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1467, in main
  File "src\you_get\common.py", line 1378, in script_main
  File "src\you_get\common.py", line 1180, in download_main
  File "src\you_get\common.py", line 1460, in any_download
  File "src\you_get\extractor.py", line 45, in download_by_url
  File "src\you_get\extractors\youku.py", line 196, in prepare
  File "src\you_get\util\log.py", line 98, in wtf
NameError: name 'exit' is not defined
you-get returned -1

>
```

以前是直接吧you-get 放入用户文件夹下，可直接从cmd下运行，但这周突然用不了了……
试了下pip3安装 之前都安装成功了 但you-get运行时一直提示这样……

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>you-get
  File "C:\安装软件\PYTHON3.6.3\Scripts\you-get-script.py", line 1
SyntaxError: Non-UTF-8 code starting with '\xb0' in file C:\安装软件\PYTHON3.6.3
\Scripts\you-get-script.py on line 1, but no encoding declared; see http://pytho
n.org/dev/peps/pep-0263/ for details

C:\Users\Administrator>

感谢！
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
#2175

**Comment by rosynirvana** [comment]
至于那个直接报错的问题，是不是原来路径上面没中文，现在有了？

**Comment by saku1119** [comment]
感谢回复，看了那个连接……研究到现在没研究明白才来问的QWQ
不好意思这里比较小白……
pip3 install --upgrade https://github.com/soimort/you-get/archive/develop.zip 这个已经运行过，运行正常，然后还是出现如下提示
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>you-get -i -c cookies.txt http://v.youku.com/v_show/id_XM
jkwNzMxMjIyNA==.html
  File "C:\安装软件\PYTHON3.6.3\Scripts\you-get-script.py", line 1
SyntaxError: Non-UTF-8 code starting with '\xb0' in file C:\安装软件\PYTHON3.6.3
\Scripts\you-get-script.py on line 1, but no encoding declared; see http://pytho
n.org/dev/peps/pep-0263/ for details

C:\Users\Administrator>

另外这里……extractors/youku.py 不知道具体是在哪个文件夹下？因为我曾经用的是直接把you-get.exe 放在了C:\Users\Administrator 这个文件夹之下 所以不知道该如何做……
感谢回复~

**Comment by saku1119** [comment]
TO：soimort-bot
道友~？

**Comment by rosynirvana** [comment]
原来的you-get.exe删掉吧

**Comment by saku1119** [comment]
TO：rosynirvana
那个已经删掉了……但现在新下的压缩包解压之后下载，依旧是提示客户端无权播放201
QWQ

**Comment by rosynirvana** [comment]
你装了好几份you-get，都删掉然后重来一遍

**Comment by saku1119** [comment]
好的！我试试~待会儿再来~

**Comment by saku1119** [comment]
变成这样了……
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>pip3 install you-get
Collecting you-get
  Using cached you_get-0.4.775-py3-none-any.whl
Installing collected packages: you-get
Successfully installed you-get-0.4.775

C:\Users\Administrator>you-get
Usage: you-get [OPTION]... [URL]...

Startup options:
    -V | --version                      Print version and exit.
    -h | --help                         Print help and exit.

Dry-run options: (no actual downloading)
    -i | --info                         Print extracted information.
    -u | --url                          Print extracted information with URLs.
         --json                         Print extracted URLs in JSON format.

Download options:
    -n | --no-merge                     Do not merge video parts.
         --no-caption                   Do not download captions.
                                        (subtitles, lyrics, danmaku, ...)
    -f | --force                        Force overwriting existed files.
    -F | --format <STREAM_ID>           Set video format to STREAM_ID.
    -O | --output-filename <FILE>       Set output filename.
    -o | --output-dir <PATH>            Set output directory.
    -p | --player <PLAYER [OPTIONS]>    Stream extracted URL to a PLAYER.
    -c | --cookies <COOKIES_FILE>       Load cookies.txt or cookies.sqlite.
    -x | --http-proxy <HOST:PORT>       Use an HTTP proxy for downloading.
    -y | --extractor-proxy <HOST:PORT>  Use an HTTP proxy for extracting only.
         --no-proxy                     Never use a proxy.
    -s | --socks-proxy <HOST:PORT>      Use an SOCKS5 proxy for downloading.
    -t | --timeout <SECONDS>            Set socket timeout.
    -d | --debug                        Show traceback and other debug info.
    -I | --input-file                   Read non-playlist urls from file.


C:\Users\Administrator>you-get -i -c cookies.txt http://v.youku.com/v_show/id_XM
jkwNzMxMjIyNA==.html
you-get: Found cna in imported cookies. Use it
you-get: 客户端无权播放,201

C:\Users\Administrator>pip3 install --upgrade https://github.com/soimort/you-get
/archive/develop.zip
Collecting https://github.com/soimort/you-get/archive/develop.zip
  Downloading https://github.com/soimort/you-get/archive/develop.zip
     \ 184kB 255kB/s
Installing collected packages: you-get
  Found existing installation: you-get 0.4.775
    Uninstalling you-get-0.4.775:
      Successfully uninstalled you-get-0.4.775
  Running setup.py install for you-get ... done
Successfully installed you-get-0.4.775

C:\Users\Administrator>you-get -i -c cookies.txt http://v.youku.com/v_show/id_XM
jkwNzMxMjIyNA==.html
  File "C:\安装软件\Python3.6.2\Scripts\you-get-script.py", line 1
SyntaxError: Non-UTF-8 code starting with '\xb0' in file C:\安装软件\Python3.6.2
\Scripts\you-get-script.py on line 1, but no encoding declared; see http://pytho
n.org/dev/peps/pep-0263/ for details

C:\Users\Administrator>

第一次安装完成后，还是201错误…… 第二遍是安装了pip3 install --upgrade https://github.com/soimort/you-get/archive/develop.zip 之后，提示Non-UTF-8 code starting with '\xb0' in file C:\安装软件\Python3.6.2
\Scripts\you-get-script.py on line 1, but no encoding declared; see http://pytho
n.org/dev/peps/pep-0263/ for details 
我是不是应该用全英文的安装路径试试？

**Comment by rosynirvana** [comment]
我觉得还是你没把该删的都删掉

那个Non-UTF-8 code的错误提示，是安装了用pyinstaller打包的exe，然后路径里有中文
下载的那个you-get.exe，或是直接用pip3安装（因为binary优先）都是这种
如果是upgrade到```https://github.com/soimort/you-get/archive/develop.zip```是没有这个问题的

所以单纯从debug log果上来看，你还在运行一个之前的打包过的exe
刚才找了台win10 python36-32的机器装了一下没发现什么问题

**Comment by saku1119** [comment]
呃，想问一下怎么才能删干净……我是直接连Python一起删掉的来着……之前直接放在用户文件夹里的那个也删掉了……我重启下试试吧先QWQ

**Comment by saku1119** [comment]
感谢亲！！！好了！重启了一下问题解决了~已经可以用了！谢谢耐心帮忙！！！！ QWQ太感谢了~~~
