### ISSUE TITLE
在英文版Windows系统中使用Git BASH运行You-get有问题

### ISSUE THREAD

**Issue by shikkoku** [soimort/you-get#2179]
feiyu@DESKTOP-G69JCOR MINGW64 ~
$ chcp.com 65001
Active code page: 65001

feiyu@DESKTOP-G69JCOR MINGW64 ~
$ you-get -c cookies.txt "https://www.bilibili.com/video/av12358142/" -o Videos/
you-get: [error] oops, the current environment does not seem to support Unicode.
you-get: please set it to a UTF-8-aware locale first,
you-get: so as to save the video (with some Unicode characters) correctly.
you-get: you can do it like this:
you-get:     (Windows)    % chcp 65001
you-get:     (Linux)      $ LC_CTYPE=en_US.UTF-8
site:                Bilibili
stream:
    - format:        flv
      container:     flv
      size:          336.2 MiB (352512587 bytes)
    # download-with: you-get --format=flv [URL]

feiyu@DESKTOP-G69JCOR MINGW64 /d/Documents
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=

有解决方案吗？powershell倒是没问题……不过进度条容易刷屏。

**Comment by rosynirvana** [comment]
https://github.com/soimort/you-get/wiki/FAQ

**Comment by soimort** [comment]
这是通过何种方式安装的？

**Comment by shikkoku** [comment]
Q: UnicodeDecodeError in Windows mintty (such as cygwin, git-for-windows, msys2 and git-sdk)

A:

Find a folder called site-packages under python3, for example:
$ python3
>>> import site; site.getsitepackages()
It should print something like ['C:/git-sdk-64/mingw64/lib/python3.5/site-packages']
Create a new file sitecustomize.py
import sys
sys.stdout = open(sys.stdout.fileno(), mode='w', encoding='utf8', buffering=1)
Save it to C:/git-sdk-64/mingw64/lib/python3.5/site-packages/sitecustomize.py

由于我的python是Windows下安装的，所以我的目录应该是在Python的安装目录C:\Program Files\Python36\Lib\site-packages下。问题解决。
