### ISSUE TITLE
Youku 201

### ISSUE THREAD

**Issue by pxia** [soimort/you-get#2183]
Seems like a new server-side restriction from Youku

```
$ you-get -d http://v.youku.com/v_show/id_XMjkwNjQ0NzMyOA\=\=.html\?spm\=a2hzp.8253869.0.0
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjkwNjQ0NzMyOA==&ccode=0401&client_ip=192.168.1.1&utid=NaX6EbSQSj8CAWzJufqBhnIb&client_ts=1500755769
you-get: 客户端无权播放,201
```

**Comment by soimort** [comment]
@soimort-bot Test: http://v.youku.com/v_show/id_XMjkwNjQ0NzMyOA==.html?spm=a2hzp.8253869.0.0

**Comment by ztytian** [comment]
you-get -di http://v.youku.com/v_show/id_XMjkxMTcxNDU0NA==.html
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjkxMTcxNDU0NA==&ccode=0401&client_ip=192.168.1.1&utid=Y8b6EUeH/V4CAbZ2CCp4b1ti&client_ts=1500764260
you-get: 客户端无权播放,201


Not for me

**Comment by ztytian** [comment]
@soimort-bot Test: http://v.youku.com/v_show/id_XMjkxMTcxNDU0NA==.html

**Comment by ztytian** [comment]
@soimort-bot Test: http://v.youku.com/v_show/id_XMjgxOTQ2MDE3Mg==

**Comment by ztytian** [comment]
curl "https://ups.youku.com/ups/get.json?vid=XMjkxMTcxNDU0NA==&ccode=0401&client_ip=192.168.1.1&utid=ydD6EUatSj4CAbZ2CCp6ji0n&client_ts=1500766921"
{"cost":0.003000000026077032,"data":{"error":{"note":"客户端无权播放,201","code":-6004}},"e":{"code":0,"provider":"hsfprovider","desc":""}}

**Comment by rosynirvana** [comment]
```
curl "https://ups.youku.com/ups/get.json?vid=XMjkxMTcxNDU0NA==&ccode=0401&client_ip=192.168.1.1&utid=ydD6EUatSj4CAbZ2CCp6ji0n&client_ts=1500766921" -H 'referer: http://v.youku.com'
```

https://github.com/soimort/you-get/commit/6c0e4b796397a2b2ca2f26bbb865c03cce59b99a
