### ISSUE TITLE
请问you-get 是否有仅下载视频中指定时间段的功能，比如仅下载02~03这一分钟的视频。

### ISSUE THREAD

**Issue by cwcw** [soimort/you-get#2184]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
没有

**Comment by cwcw** [comment]
嗯好的，谢谢热心解答

**Comment by einverne** [comment]
ffmpeg 可以做视频切片操作 @cwcw 

对视频切片操作

比如需要从视频第1分45秒地方，剪10秒画面，-ss 表示开始位置，-t 表示延长时间

    ffmpeg -i input.mp4 -ss 00:01:45 -t 10 output.mp4

**Comment by cnbeining** [comment]
逻辑上说这是不大可能的。下载后切片来的好点。

**Comment by cwcw** [comment]
抱歉现在才上线，谢谢各位的热心解答，其实用ffmpeg处理下载后的视频这个我会用，而且一直用它来在视频中截图什么的，我之所以提问是因为我要下载的视频列表有600多集，而我只是需要截其三分钟内的固定某一帧出来，之后不再需要视频。为了截一图而将视频全下下来，花的时间很长，所以才想偷懒的。当然现在也早就下下来处理好了。
