### ISSUE TITLE
优酷视频无法下载（you-get已更新至0.4.775）

### ISSUE THREAD

**Issue by luanmajun** [soimort/you-get#2186]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
$ you-get -d http://v.youku.com/v_show/id_XMTgyMDA2NDcyMA==.html?spm=a2h0k.8191407.0.0&from=s1.8-1-1.2&debug=flv
[1] 83561
[2] 83562
[2]+  Done                    from=s1.8-1-1.2
$ [DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMTgyMDA2NDcyMA==&ccode=0401&client_ip=192.168.1.1&utid=euL7EZ6nkigCAYcAulM%2B7zK1&client_ts=1500836987
you-get: 客户端无权播放,201

```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> 明明可以在网页，客户端以及移动端播放，但是使用you-get下载时却显示因为客户端无权播放而无法下载。在使用you-get -d URL之后，上面已经是full output了。
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
$ you-get -d http://v.youku.com/v_show/id_XMTgyMDA2NDcyMA==.html?spm=a2h0k.8191407.0.0&from=s1.8-1-1.2&debug=flv
[1] 83561
[2] 83562
[2]+  Done                    from=s1.8-1-1.2
$ [DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMTgyMDA2NDcyMA==&ccode=0401&client_ip=192.168.1.1&utid=euL7EZ6nkigCAYcAulM%2B7zK1&client_ts=1500836987
you-get: 客户端无权播放,201
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 明明可以在网页，客户端以及移动端播放，但是使用you-get下载时却显示因为客户端无权播放而无法下载。在使用you-get -d URL之后，上面已经是full output了。
> [舔 :icecream:!]

**Comment by soimort** [comment]
@soimort-bot Test: http://v.youku.com/v_show/id_XMTgyMDA2NDcyMA==.html?spm=a2h0k.8191407.0.0&from=s1.8-1-1.2&debug=flv

**Comment by luanmajun** [comment]
@soimort-bot Sorry, how could I get this? It still doesn't work for me.

**Comment by soimort** [comment]
Please update to the `develop` branch first.
