### ISSUE TITLE
bilibili限速问题

### ISSUE THREAD

**Issue by xiiatuuo** [soimort/you-get#2193]
请教各位大神，b站的视频在本机下载ok，但是放在阿里云机器上面就限速了，这个有没有办法控制you-get的下载速度？或者别的方法来解决？

**Comment by rosynirvana** [comment]
你翻一翻issue能找到
http header range 每次下载5MiB即可

如果不想另外写东西，download_urls里timeout设置成1

**Comment by jianxiyan2017** [comment]
大牛，能再写清楚一点吗，非常感谢，限制速度timeout怎么写

**Comment by rosynirvana** [comment]
bilibili的extractor继承自extractor.py中的VideoExtractor
VideoExtractor有个方法是download
download里会调用定义在common.py中的download_urls
download_urls会调用url_save，而url_save接受一个参数timeout

给bilibili的extractor实现一个download，调用download_urls时timeout=1，并且包裹在一个try except中，捕获到timeout就重启download_urls

其实不比每次建立连接都下载5MiB简单多少

**Comment by xiiatuuo** [comment]
明白了，用you-get -t 1就能实现超时控制，后续自行判断是否成功就行了。感谢@rosynirvana

**Comment by jianxiyan2017** [comment]
@rosynirvana非常感谢
