### ISSUE TITLE
能不能把下载进度条设计成一条？

### ISSUE THREAD

**Issue by jyuan15** [soimort/you-get#2198]
现在的进度条刷屏太可怕了
![13](https://user-images.githubusercontent.com/12642186/28613851-38e6a44c-7226-11e7-866d-897afae02d96.gif)

├████──────────────────────── 9.3% ( 26.8/287.5MB) ├████──────────────────────── 9.4% ( 27.0/287.5MB) ├████──────────────────────── 9.5% ( 27.2/287.5MB) ├████──────────────────────── 9.6% ( 27.5/287.5MB) ├████──────────────────────── 9.7% ( 27.8/287.5MB) ├████──────────────────────── 9.7% ( 28.0/287.5MB) ├████──────────────────────── 9.8% ( 28.2/287.5MB) ├████──────────────────────── 9.9% ( 28.5/287.5MB) ├████────────────────────────10.0% ( 28.8/287.5MB) ├████────────────────────────10.1% ( 29.0/287.5MB) ├████────────────────────────10.2% ( 29.2/287.5MB) ├████────────────────────────10.3% ( 29.5/287.5MB) ├████────────────────────────10.3% ( 29.8/287.5MB) ├████────────────────────────10.4% ( 30.0/287.5MB) ├████────────────────────────10.5% ( 30.2/287.5MB) ├████────────────────────────10.6% ( 30.5/287.5MB) ├████────────────────────────10.7% ( 30.8/287.5MB) ├████────────────────────────10.8% ( 31.0/287.5MB) ├████────────────────────────10.9% ( 31.2/287.5MB) ├████────────────────────────11.0% ( 31.5/287.5MB) ├█████───────────────────────11.0% ( 31.8/287.5MB) ├█████───────────────────────11.1% ( 32.0/287.5MB) ├█████───────────────────────11.2% ( 32.2/287.5MB) ├█████───────────────────────11.3% ( 32.5/287.5MB) ├█████───────────────────────11.4% ( 32.7/287.5MB) ├█████───────────────────────11.5% ( 33.0/287.5MB) ├█████───────────────────────11.6% ( 33.2/287.5MB) ├█████───────────────────────11.6% ( 33.5/287.5MB) ├█████───────────────────────11.7% ( 33.7/287.5MB) ├█████───────────────────────11.8% ( 34.0/287.5MB) ├█████───────────────────────11.9% ( 34.2/287.5MB) ├█████───────────────────────12.0% ( 34.5/287.5MB) ├█████───────────────────────12.1% ( 34.7/287.5MB) ├█████───────────────────────12.2% ( 35.0/287.5MB) ├█████───────────────────────12.3% ( 35.2/287.5MB) ├█████───────────────────────12.3% ( 35.5/287.5MB) ├█████───────────────────────

能不能设置成这样：

Downloading 04.flv ...
30.8% ( 88.4/287.5MB) ├█████─────────┤[ 4/13]    4 MB/s

**Comment by jxon** [comment]
把命令行窗口拉宽点下载进度条就是一行了。

**Comment by rosynirvana** [comment]
首先，项目要有个win的开发者

**Comment by demonluo** [comment]
或者干脆把下载进度条去掉就变成这样了...

Downloading 04.flv ...
30.8% ( 88.4/287.5MB)

**Comment by mogu1121** [comment]
self.bar_size = self.term_size - 27 - 2*total_pieces_len - 2*total_str_width
common.py  把27的数字加大

**Comment by jyuan15** [comment]
@mogu1121 有效，谢谢~ 

但又有个问题，在Termux中改了就无法下载，不知怎么回事？

**Comment by BruceChen2017** [comment]
自从安装了git之后，用cmd或者git-bash执行都是一条进度，当然需要用到ffmpeg下载的除外

**Comment by rosynirvana** [comment]
check [this](https://github.com/soimort/you-get/wiki/Window-Console-Problems) for more info
