### ISSUE TITLE
支持酷米——专门为15岁以下的中国孩子提供绿色健康、积极向上的动画、儿童剧、儿童游戏及相关服务的专业网站！

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#22]
这个好萌 ![tsk](http://static.tieba.baidu.com/tb/editor/images/jd/j_0013.gif)
http://www.kumi.cn/

**Comment by cnbeining** [comment]
orz

全是合(dao)作(lian)

 起码有个自己的上传平台 也好抓取是不是。。。
