### ISSUE TITLE
下载 CNTV 视频并未自动合并

### ISSUE THREAD

**Issue by jayan2358** [soimort/you-get#2201]
无报错信息，已测试下载优酷视频合并正常
比如这个 url：[http://tv.cctv.com/2017/07/24/VIDEQSiNEpJRKyXmhLT4VdoC170724.shtml](http://tv.cctv.com/2017/07/24/VIDEQSiNEpJRKyXmhLT4VdoC170724.shtml)

**Comment by rosynirvana** [comment]
cntv有些分片有错误，合并会造成文件损坏

**Comment by demonluo** [comment]
@rosynirvana 因为一小部分的旧视频有问题就不合并. 这不太合理吧...
而且明明有 --no-merge/-n 的指令...

**Comment by hobmgcode** [comment]
项目已放弃

**Comment by rosynirvana** [comment]
从开发者角度来说
首先无法总计多少视频是有问题的，所以也无法断言是“一小部分的旧视频”
然后各用户用来合并的后端是不一样的，ffmpeg合并失败返回依然是0（和成功一样），python code检查不到合并错误，然后会把分段全部删除，整个下载就白下了
最后cntv下载得到的分段数目比较少，分段也能用，和m3u8不一样
所以在我看来没允许cntv的分段合并，没什么明显的优势

从用户角度来说，学习一下怎么用ffmpeg合并片段基本就不会抱怨这个了

**Comment by einverne** [comment]
@jayan2358 你可以试试我这个分支 https://github.com/einverne/you-get , cntv 并没有完全测试，但你那个视频我测试是可以合并的

**Comment by wangyupeng** [comment]
我下载的一个视频也无法合并视频，并且无法下载其它清晰度版本。能帮我看下吗？谢谢
视频链接如下：
http://tv.cctv.com/2017/08/07/VIDEChimB9OmiClYKGra8V0O170807.shtml

以下是运行输出
you-get -i 'http://tv.cctv.com/2017/08/07/VIDEChimB9OmiClYKGra8V0O170807.shtml'
Site:       CNTV.com
Title:      《远方的家》 20170807 一带一路（206）坦桑尼亚 生活在维多利亚湖畔
Type:       MPEG-4 video (video/mp4)
Size:       137.83 MiB (144522929 Bytes)

**Comment by lki2019** [comment]
@wangyupeng http://tv.cctv.com/2017/08/07/VIDEChimB9OmiClYKGra8V0O170807.shtml

我试了下好像是没合并，

推荐你用ykdl  我试了 可以合并，

工具嘛，搭配着用，比如用you-get下载优酷会经常断开，ykdl则不会，我试过
工具之间各有侧重，搭配用比较好·

**Comment by rosynirvana** [comment]
两位至少看看上面的回复吧
cntv不合并，因为有些视频分段本来有问题，合并整个文件就坏掉了，下载的全白下了

我下youku没遇到过断开，因为我除了测试之外都不用啊

**Comment by lki2019** [comment]
<pre><code>我下载的一个视频也无法合并视频，并且无法下载其它清晰度版本。能帮我看下吗？谢谢
视频链接如下：
http://tv.cctv.com/2017/08/07/VIDEChimB9OmiClYKGra8V0O170807.shtml

以下是运行输出
you-get -i 'http://tv.cctv.com/2017/08/07/VIDEChimB9OmiClYKGra8V0O170807.shtml'
Site: CNTV.com
Title: 《远方的家》 20170807 一带一路（206）坦桑尼亚 生活在维多利亚湖畔
Type: MPEG-4 video (video/mp4)
Size: 137.83 MiB (144522929 Bytes)<pre><code>


我是回复我楼上的这位，他说这个地址合并不了，我也试了下的确没合并··
按照大神的说法，cntv不合并，因为有些视频分段本来有问题，合并整个文件就坏掉了，下载的全白下了

1，说明这个地址分段有问题，所以程序不执行合并命令，
2，CNTV不是所有的视频都无法合并，只是部分，目前只是部分的无法合并，其他的还是可以合并的

3.CNTV的视频 都无法合并·

那么我可以理解为是指3吧？都无法合并，因为有部分会有分段有问题的现象，所以砍掉了合并这一块，也就是说所有的CNTV视频都无法合并了

**Comment by wangyupeng** [comment]
合并视频的问题，我是采纳以上各位大神的建议，通过ffmpeg进行合并的，视频可以正常观看。谢谢各位的支持。

**Comment by wangyupeng** [comment]
@lki2019 前辈，我通过执行以下命令，只得到一种视频的清晰度，原视频播放页存在三种清晰度选择。这个有办法解决吗？
`you-get -i 'http://tv.cctv.com/2017/08/07/VIDEChimB9OmiClYKGra8V0O170807.shtml'`

**Comment by lki2019** [comment]
@wangyupeng 你好，我也是个普通使用者

you-get -d http://tv.cctv.com/2017/08/07/VIDEChimB9OmiClYKGra8V0O170807.shtml

我是用-d命令

**Comment by rosynirvana** [comment]
```
./you-get -i 'http://tv.cctv.com/2017/08/07/VIDEChimB9OmiClYKGra8V0O170807.shtml'
site:                CNTV.com
title:               《远方的家》 20170807 一带一路（206）坦桑尼亚 生活在维多利亚湖畔
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        1
      container:     mp4
      video-profile: 1280x720_2000kb/s
    # download-with: you-get --format=1 [URL]

    - format:        2
      container:     mp4
      video-profile: 1280x720_1200kb/s
    # download-with: you-get --format=2 [URL]

    - format:        3
      container:     mp4
      video-profile: 640x360_850kb/s
    # download-with: you-get --format=3 [URL]

    - format:        4
      container:     mp4
      video-profile: 480x270_450kb/s
    # download-with: you-get --format=4 [URL]

    - format:        5
      container:     mp4
      video-profile: 320x180_200kb/s
    # download-with: you-get --format=5 [URL]
```

And it auto-merges now.
