### ISSUE TITLE
爱课程下载专辑时能不能选择下载某一节课

### ISSUE THREAD

**Issue by aa315572260** [soimort/you-get#2203]
爱课程的视频只能专辑下载，不支持单个下载，而且下载到一般就停了，重新启动下载每次都要监测前面已经下载的，一门课几十个视频，经常监测到一部分就出现失败了得重新开始，导致后半部分课程下载花的时间很长，谢谢

**Comment by aa315572260** [comment]
@soimort-bot   eg   http://www.icourses.cn/coursestatic/course_5929.html
Skipping 儿科学   儿童生长发育.flv: file already exists

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

E:\教程\儿科>you-get http://www.icourses.cn/coursestatic/course_5929.html
[WARNING] Switching to playlist mode!
[WARNING] Failed to fetch the video file! Retrying...

**Comment by aa315572260** [comment]
E:\教程\儿科>you-get http://www.icourses.cn/coursestatic/course_5929.html
[WARNING] Switching to playlist mode!
[WARNING] Failed to fetch the video file! Retrying...
Site:       icourses.cn
Title:      儿科学   儿科学绪论
Type:       Flash video (video/x-flv)
Size:       142.91 MiB (149850327 Bytes)

Downloading 儿科学   儿科学绪论.flv ...
Skipping 儿科学   儿科学绪论.flv: file already exists

Site:       icourses.cn
Title:      儿科学   儿童生长发育
Type:       Flash video (video/x-flv)
Size:       158.4 MiB (166090211 Bytes)

Downloading 儿科学   儿童生长发育.flv ...

Site:       icourses.cn
Title:      儿科学   儿科学绪论
Type:       Flash video (video/x-flv)
Size:       142.91 MiB (149850327 Bytes)

Downloading 儿科学   儿科学绪论.flv ...
Skipping 儿科学   儿科学绪论.flv: file already exists

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

E:\教程\儿科>you-get http://www.icourses.cn/coursestatic/course_5929.html
[WARNING] Switching to playlist mode!

**Comment by rosynirvana** [comment]
传给you-get的url是具体的某堂课，下载的就是某堂课了
http://www.icourses.cn/jpk/changeforVideo.action?resId=722918&courseId=5929&firstShowFlag=2

**Comment by aa315572260** [comment]
@rosynirvana 我·试过，但传具体某堂课时下载不了，出现这个：是我的问题还是？谢谢回答
C:\Users\Administrator>you-get http://www.icourses.cn/jpk/changeforVideo.action?resId=722918&courseId=5929&firstShowFlag=2
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
'courseId' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'firstShowFlag' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by rosynirvana** [comment]
```
you-get ''http://www.icourses.cn/jpk/changeforVideo.actionresId=722918&courseId=5929&firstShowFlag=2''
```

**Comment by aa315572260** [comment]
@rosynirvana 谢谢你明白了

**Comment by lki2019** [comment]
奥，原来是同样的站
https://github.com/soimort/you-get/issues/2241

我下载了15M就下载不动了，从新开始也是，最多下载到百分11 也就是15M左右
不知道什么原因··

**Comment by lki2019** [comment]
<pre><code>you-get http://www.icourses.cn/coursestatic/course_5929.html

这样下载专辑页面是可以下载的，

you-get "http://www.icourses.cn/jpk/changeforVideo.actionresId=722918&courseId=5929&firstShowFlag=2"

这样下载单节课 就无法下载了<pre><code>

**Comment by lki2019** [comment]
<pre><code>you-get http://www.icourses.cn/viewVCourse.action?courseC
ode=10026V005
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

<pre><code>

同样的站，不同的视频 我这个用youget无法下载

**Comment by rosynirvana** [comment]
这个站就是下大概15MiB就停住
下载剩余的要重新生成一个URI

修改了一点HTTP协议

**Comment by lki2019** [comment]
http://www.icourses.cn/jpk/changeforVideo.action?resId=722918&courseId=5929&firstShowFlag=2

我有个想法，上面是大神之前贴出来的指定的某1几节课的地址

那么我这个http://www.icourses.cn/viewVCourse.action?courseCode=10026V005

显然格式和大神你贴出来的格式不一样，

需要2个值 resId 值还有courseId

我查看源代码 看到了 但是不是数字的
viewVCourse.action?courseId=ff8080815001e3ff015016f49bc31469&resId=ff8080815001e3ff01501813e7d816bb'"

如果能对应了数字

在组合成这样的，youget或许可以下载
http://www.icourses.cn/jpk/changeforVideo.action?resId=722918&courseId=5929&firstShowFlag=2



<pre><code>C:\Users\Administrator>you-get "http://www.icourses.cn/jpk/changeforVideo.action
?resId=722918&courseId=5929&firstShowFlag=2"
Site:       icourses.cn
Title:      儿科学 第五章 第1节 总论（上）
Type:       Flash video (video/x-flv)
Size:       147.6 MiB (154774385 Bytes)

Downloading 儿科学 第五章 第1节 总论（上）.flv ...
98.2% (145.0/147.6MB) ├████████████████████████████
98.4% (145.2/147.6MB) ├████████████████████████████
98.6% (145.5/147.6MB) ├████████████████████████████
98.7% (145.8/147.6MB) ├████████████████████████████
98.9% (146.0/147.6MB) ├████████████████████████████
99.1% (146.2/147.6MB) ├████████████████████████████
99.3% (146.5/147.6MB) ├████████████████████████████
99.4% (146.8/147.6MB) ├████████████████████████████
99.6% (147.0/147.6MB) ├████████████████████████████
99.8% (147.2/147.6MB) ├████████████████████████████
99.9% (147.5/147.6MB) ├████████████████████████████
 100% (147.6/147.6MB) ├████████████████████████████
█████████████┤[1/1]  357 kB/s
Can't convert flv files<pre><code>

虽然中途断开了好多次，不过可以用我那个超大视频批处理自动循环去下载就好
直到下载完成

you-get最起码还可以下载，虽然会断开几次，

我手动放到IDM里面试验几次还得在从新去获取新的地址，试验了几次都是下了15M就下不动了

**Comment by lki2019** [comment]
https://you-get.org/#supported-sites

我看支持列表里没有爱课程这个站啊

但是却可以下载部分爱课程的
说明解析脚本里有相关的？

**Comment by rosynirvana** [comment]
请不要用这个issue，和你的不是同一个问题

**Comment by rosynirvana** [comment]
现在的实现和其他extractor一样
必须用-l才可以下载coursestatic地址

87fb357
