### ISSUE TITLE
无法关闭 debug 模式

### ISSUE THREAD

**Issue by jayan2358** [soimort/you-get#2207]
上次cntv下载不正常，加了debug参数运行了下。今天下爱奇艺的视频也跳出刷刷刷的日志，明明没debug参数啊

如果我贴日志的话，可能要几十页。。。

**Comment by rosynirvana** [comment]
ffmpeg默认就是输出大量的log

**Comment by jayan2358** [comment]
@rosynirvana 可是以前没有啊，只有进度条

**Comment by rosynirvana** [comment]
你说的“以前” 不是近一年下爱奇艺吧

**Comment by rosynirvana** [comment]
iqiyi用ffmpeg下载
ffmpeg会不断输出log来显示当前进度
这不是debug模式
