### ISSUE TITLE
新发现 https://api.youku.com/videos/player/file?data=

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#2214]
微博上贴youku或tudou短视频的时候如果视频网址以html结束，就会得到HTML5播放器播放

比如发 http://video.tudou.com/v/XMjUwNzMzNTQ3Mg==.html 到微博，接下来你会看到微博上直接用HTML5播放器播放（如果没看到HTML5播放器，请重新刷新加载这条微博），而不是土豆的播放器，我看了下视频源地址是
`https://api.youku.com/videos/player/file?data=WcEl1oquVdXdOek16TlRRM01nPT18MXwxfDEwMDM2MTcO0O0O`
**谁能告诉我下data=后面的这一串是怎么来的？**

微博似乎有这个功能 ，请看介绍http://t.cn/RSPfSjp

**Comment by rosynirvana** [comment]
你注意一下，优酷或者土豆有个分享到微博的功能
所以大可能是微博没做什么特别的事情，只是让优土豆生成了一个分享地址

**Comment by redstoneleo** [comment]
极有可能是新浪微博和视频网站间有什么协议吧，很多爱奇艺、腾讯视频分享到新浪微博都可以无广告观看
