### ISSUE TITLE
使用you-get解析youku的地址时，出现错误。

### ISSUE THREAD

**Issue by xiaohucoding** [soimort/you-get#2216]
you-get --debug --json http://v.youku.com/v_show/id_XNTIwNzUyNDgw.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XNTIwNzUyNDgw&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XNTIwNzUyNDgw&ct=12
you-get: [Failed] 客户端无权播放,201

**Comment by rosynirvana** [comment]
升级

**Comment by HarukaMa** [comment]
升级无效。从 develop branch 代码 pip3 install 无效。

咋手工召唤机器人自动测试（

**Comment by rosynirvana** [comment]
不要翻老issues
顶楼这代码是几个月前的了

**Comment by HarukaMa** [comment]
？？？ issue template 让我翻的老 issue 啊（

算了我开新的

**Comment by rosynirvana** [comment]
先升级到这个
https://github.com/soimort/you-get/commit/9488ce1cff492fafe1e13aaf5ea384ea387a15ea

**Comment by HarukaMa** [comment]
issue template:
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.

如果不想让人翻老 issue 请考虑模板里的这行要怎么改。

**Comment by rosynirvana** [comment]
准确来说，确定是一个问题的应该用老issue
不确定的应该开新issue
关掉一个多余的issue比不同问题放在同一个issue下面要好处理很多

**Comment by HarukaMa** [comment]
在错误外观完全一样的时候，不能指望用户仅通过现象判断代码层面是否是同一个问题。

用户并不懂一个工具的内部结构，更不知道具体到每个 extractor 的实现方式。对用户来说，能看懂的只有一个 “客户端无权播放,201”。

不能仅仅从非常熟悉代码结构和工作原理的开发者角度来看待 issue 的问题。

**Comment by rosynirvana** [comment]
You're overreacting
我个人并不指望用户什么

另外
```
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XNTIwNzUyNDgw&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XNTIwNzUyNDgw&ct=12
```
这两行是只有5月份以及之前的代码才会出现的
如果如你所言升级到了develop branch，那你遇到的不是同一个问题，所以说不该翻这个老issue

**Comment by HarukaMa** [comment]
这不是 overreacting，而是实际作法和指引有出入。我只是在提出问题。

既然不指望用户什么，那么用户怎么知道这两行是因为只有老代码才会出现的错误？用户能看的懂的只有一个无权播放，根本不知道这两行到底是什么东西，怎么就能判断出来不是同一个问题？

> 这两行是只有5月份以及之前的代码才会出现的

**Comment by rosynirvana** [comment]
emmm...

能先明确一下“实际做法” “指引” 指什么吗？
“用户怎么知道这两行” 这个“用户” 是指你自己，还是任意用户？

我没有指望用户能看出log的区别，所以直接告诉你那是老代码，不要翻这个issue了啊

此外，实际操作和指引上有差别是必然的啊，指引更理想化，假设用户是耐心的开发者（github用户以开发者为主）；而实际操作就要考虑更为复杂的情况，以及可操作性。如果你确定你现在提出的问题，或是引起的“讨论”并非显而易见的，那确实可以说自己不是在overreacting。
