### ISSUE TITLE
yupptv.com 下载和调用播放器观看

### ISSUE THREAD

**Issue by lki2019** [soimort/you-get#2219]
在提交前，请确保您已经检查了以下内容!

 (√)你可以在浏览器或移动端中观看视频，但不能使用you-get下载.
(√) 您的you-get为最新版.
(√) 我已经阅读并按 https://github.com/soimort/you-get/wiki/FAQ 中的指引进行了操作.
(√) 您的问题没有在https://github.com/soimort/you-get/issues , https://github.com/soimort/you-get/wiki/FAQ 或 https://github.com/soimort/you-get/wiki/Known-Bugs 报告，否则请在原有issue下报告.
 (√)本问题确实关于you-get, 而不是其他项目.
请使用--debug运行，并将输出粘贴在下面:

<pre><code>$ you-get "http://streams.yupptv.com/freechannelplayer.aspx?id=144" --debug
[DEBUG] get_head: http://streams.yupptv.com/freechannelplayer.aspx?id=144
[DEBUG] get_content: http://streams.yupptv.com/freechannelplayer.aspx?id=144
[DEBUG] get_response: http://streams.yupptv.com/freechannelplayer.aspx?id=144
[DEBUG] url_info: https://ind3-lh.akamaihd.net/i/ind3_asianetnews@393763/master.
m3u8?hdnea=st=1501821173~exp=1501821533~acl=/i/ind3_asianetnews@393763/*~hmac=f9
4ffd575232f1ac60a65f672700825b5718ba619cd42e07cbf35f28d0344a94
Site:       yupptv.com
Title:      \r\n\r\n
Type:       Unknown type (None)
Size:       0.0 MiB (1338 Bytes)

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i https://ind3-lh.akamaihd.net/i/ind3_asianetnews@393763/master.m
3u8?hdnea=st=1501821173~exp=1501821533~acl=/i/ind3_asianetnews@393763/*~hmac=f94
ffd575232f1ac60a65f672700825b5718ba619cd42e07cbf35f28d0344a94 -c copy -bsf:a aac
_adtstoasc -r-n-r-n.mp4
ffmpeg version N-86755-g0780ad9 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --e
nable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --
enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv
--enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-li
bfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug -
-enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enabl
e-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-li
bsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolam
e --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx
 --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable
-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 67.100 / 55. 67.100
  libavcodec     57.100.104 / 57.100.104
  libavformat    57. 75.100 / 57. 75.100
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 95.100 /  6. 95.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Unrecognized option 'r-n-r-n.mp4'.
Error splitting the argument list: Option not found
[DEBUG] url_info: http://ind3-lh.akamaihd.net/i/ind3_asianetnews@393763/master.m
3u8
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://streams.yupptv.com/freechannelplayer.aspx?id=144']
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\run
py.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\run
py.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts
\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\universal.py", line 36, in universal_download
    type_, ext, size = url_info(hls_url)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 445, in url_info
    response = urlopen_with_retry(request.Request(url))
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 570, in error
    return self._call_chain(*args)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\url
lib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

</code></pre>

对这样HLS流的视频，如何下载和调用本地播放器观看，没什么经验，能不能提供下思路让我尝试下,
 不知道发到这里合适不合适，先感谢了！

**Comment by rosynirvana** [comment]
这个其实大体上是work的
（居然是universal extractor）
只是这个页面抓不到title，拿到一个\r\n\r\n，escape成了-r-n-r-n，然后ffmpeg把-r-n-r-n理解成了flag，误以为不是文件名……

```diff
diff --git a/src/you_get/extractors/universal.py b/src/you_get/extractors/universal.py
index 3168c48..c321f1f 100644
--- a/src/you_get/extractors/universal.py
+++ b/src/you_get/extractors/universal.py
@@ -33,8 +33,9 @@ def universal_download(url, output_dir='.', merge=True, info_only=False, **kwarg
                               r'[^;"\'\\]*)', page)
         if hls_urls:
             for hls_url in hls_urls:
-                type_, ext, size = url_info(hls_url)
-                print_info(site_info, page_title, type_, size)
+                #type_, ext, size = url_info(hls_url)
+                #print_info(site_info, page_title, type_, size)
+                print(hls_url)
                 if not info_only:
                     download_url_ffmpeg(url=hls_url, title=page_title,
                                         ext='mp4', output_dir=output_dir)
```
然后会打印出一个master m3u8
akamaihd标准的HLS
用下游工具处理就行了

**Comment by lki2019** [comment]
streamlink.exe -ldebug HLS://https://ind3-lh.akamaihd.net
/i/ind3_asianetnews@393763/master.m3u8?hdnea=st=1501824915~exp=1501825275~acl=/i
/ind3_asianetnews@393763/*~hmac=de88e074a61909981d97cfea1d82aed3cfd3f80492af9c98
5cf91eca984dd205 best -o 19119.MP4
[cli][info] Found matching plugin stream for URL HLS://https://ind3-lh.akamaihd.
net/i/ind3_asianetnews@393763/master.m3u8?hdnea=st=1501824915~exp=1501825275~acl
=/i/ind3_asianetnews@393763/*~hmac=de88e074a61909981d97cfea1d82aed3cfd3f80492af9
c985cf91eca984dd205
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[stream.hls][debug] Reloading playlist
[cli][error] Try 1/1: Could not open stream <HLSStream('https://ind3-lh.akamaihd
.net/i/ind3_asianetnews@393763/master.m3u8?hdnea=st=1501824915~exp=1501825275~ac
l=/i/ind3_asianetnews@393763/*~hmac=de88e074a61909981d97cfea1d82aed3cfd3f80492af
9c985cf91eca984dd205')> (Could not open stream: Unable to open URL: https://ind3
-lh.akamaihd.net/i/ind3_asianetnews@393763/master.m3u8?hdnea=st=1501824915~exp=1
501825275~acl=/i/ind3_asianetnews@393763/*~hmac=de88e074a61909981d97cfea1d82aed3
cfd3f80492af9c985cf91eca984dd205 (403 Client Error: Forbidden for url: https://i
nd3-lh.akamaihd.net/i/ind3_asianetnews@393763/master.m3u8?hdnea=st=1501824915~ex
p=1501825275~acl=/i/ind3_asianetnews@393763/*~hmac=de88e074a61909981d97cfea1d82a
ed3cfd3f80492af9c985cf91eca984dd205))
error: Could not open stream <HLSStream('https://ind3-lh.akamaihd.net/i/ind3_asi
anetnews@393763/master.m3u8?hdnea=st=1501824915~exp=1501825275~acl=/i/ind3_asian
etnews@393763/*~hmac=de88e074a61909981d97cfea1d82aed3cfd3f80492af9c985cf91eca984
dd205')>, tried 1 times, exiting

**Comment by lki2019** [comment]
![qq 20170804140825](https://user-images.githubusercontent.com/30022431/28956307-98f38dba-791e-11e7-9f16-8c7daa9bc789.png)

**Comment by rosynirvana** [comment]
不知道streamlink是什么样子的
首先要确定你那里可以访问akamaihd.net

```
curl 'https://ind3-lh.akamaihd.net/i/ind3_asianetnews@393763/master.m3u8?hdnea=st=1501827159~exp=1501827519~acl=/i/ind3_asianetnews@393763/*~hmac=e68ea862f1c029de8c1c7e70ca0184dd24a218c6ff88b7eb249146ce2309c315'

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=257000,RESOLUTION=384x216,CODECS="avc1.66.30, mp4a.40.2"
https://ind3-lh.akamaihd.net/i/ind3_asianetnews@393763/index_200_av-p.m3u8?sd=10&rebase=on&hdntl=exp=1501913700~acl=%2fi%2find3_asianetnews%40393763%2f*~data=hdntl~hmac=7b43a16c5712a23cb45446d016596e8b2fa393c8079e50cc111856d3315c6092
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=403000,RESOLUTION=480x270,CODECS="avc1.66.30, mp4a.40.2"
https://ind3-lh.akamaihd.net/i/ind3_asianetnews@393763/index_400_av-p.m3u8?sd=10&rebase=on&hdntl=exp=1501913700~acl=%2fi%2find3_asianetnews%40393763%2f*~data=hdntl~hmac=7b43a16c5712a23cb45446d016596e8b2fa393c8079e50cc111856d3315c6092
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=647000,RESOLUTION=512x288,CODECS="avc1.77.30, mp4a.40.2"
https://ind3-lh.akamaihd.net/i/ind3_asianetnews@393763/index_800_av-p.m3u8?sd=10&rebase=on&hdntl=exp=1501913700~acl=%2fi%2find3_asianetnews%40393763%2f*~data=hdntl~hmac=7b43a16c5712a23cb45446d016596e8b2fa393c8079e50cc111856d3315c6092
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1233000,RESOLUTION=704x396,CODECS="avc1.77.30, mp4a.40.2"
https://ind3-lh.akamaihd.net/i/ind3_asianetnews@393763/index_1100_av-p.m3u8?sd=10&rebase=on&hdntl=exp=1501913700~acl=%2fi%2find3_asianetnews%40393763%2f*~data=hdntl~hmac=7b43a16c5712a23cb45446d016596e8b2fa393c8079e50cc111856d3315c6092
```

**Comment by lki2019** [comment]
![qq 20170804141810](https://user-images.githubusercontent.com/30022431/28956487-d0d23b04-791f-11e7-89ee-c1d072615285.png)

奥 那就是说由于地理位置限制，所以我无法下载，必须使用代理才可以？

**Comment by rosynirvana** [comment]
这个看上去是能访问，但是url失效了之类的

**Comment by lki2019** [comment]
![3](https://user-images.githubusercontent.com/30022431/28956730-0ee4b772-7921-11e7-9105-910ab9324417.png)
![1](https://user-images.githubusercontent.com/30022431/28956731-0ef48120-7921-11e7-9754-cbfebecf498d.png)
![2](https://user-images.githubusercontent.com/30022431/28956732-0ef7ad1e-7921-11e7-9737-b76186a6eacf.png)

你用的什么工具下载的？

我还是无法下载

**Comment by rosynirvana** [comment]
用ffmpeg

这和工具没什么关系，akamaihd我手动实现过，就是标准的HLS
问题出在其他地方

**Comment by lki2019** [comment]
最近看了些相关的帖子，本以为HLS+TS流 要么就是AES+128 加密的 要么就是不加密的

这个yupptv.com也不是AES加密的啊

这2个视频是HLS AES加密的流，我现在还没研究明白，怎么解密
<pre><code>http://www.musicheng.com/Video/Index/223

http://gkk.xsteach.com/course/view?gid=17
</code></pre>

**Comment by rosynirvana** [comment]
如果感兴趣，建议好好学学基础
和视频流本身的加密没有关系，是服务器会踢掉带有某些UA的请求
ffmpeg默认的Lavf会被踢
```
curl http://ind3-lh.akamaihd.net/i/ind3_asianetnews@393763/index_1100_av-p.m3u8\?sd\=10\&rebase\=on\&hdntl\=exp\=1501916047\~acl\=%2fi%2find3_asianetnews%40393763%2f\*\~data\=hdntl\~hmac\=83bd3f3bfba9b8fc3aa1f80c55e0c9358ac2c9dede5ee78f8e852027ce1a5a30  -H 'User-Agent: Lavf' -I
HTTP/1.1 403 Forbidden
```

但是curl 7.51.0的不会
```
ffmpeg -user_agent 'curl/7.51.0' -i http://ind3-lh.akamaihd.net/i/ind3_asianetnews@393763/index_1100_av-p.m3u8\?sd\=10\&rebase\=on\&hdntl\=exp\=1501916047\~acl\=%2fi%2find3_asianetnews%40393763%2f\*\~data\=hdntl\~hmac\=83bd3f3bfba9b8fc3aa1f80c55e0c9358ac2c9dede5ee78f8e852027ce1a5a30 -c copy oooo.mp4
```

**Comment by lki2019** [comment]
<pre><code>C:\Users\Administrator>ffmpeg -user_agent 'curl/7.54.1' -i https://ind3-lh.akamaihd.net/i/ind3_asianetnews@393763/master.m3u8?hdnea=st=1501831774~exp=1501832134~acl=/i/ind3_asianetnews@393763/*~hmac=ac16e4d802b8f257c919d391521e042540757f6c0563299355b23d76a874eb47 -c copy oooo.mp4
ffmpeg version N-86755-g0780ad9 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 67.100 / 55. 67.100
  libavcodec     57.100.104 / 57.100.104
  libavformat    57. 75.100 / 57. 75.100
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 95.100 /  6. 95.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
[https @ 04b58140] HTTP error 403 Forbidden
https://ind3-lh.akamaihd.net/i/ind3_asianetnews@393763/master.m3u8?hdnea=st=1501831774~exp=1501832134~acl=/i/ind3_asianetnews@393763/*~hmac=ac16e4d802b8f257c919d391521e042540757f6c0563299355b23d76a874eb47: Server returned 403 Forbidden (access denied)<pre><code>

**Comment by rosynirvana** [comment]
7.51.0可以不代表7.54.1也可以
例如7.52.0是不可以的

**Comment by lki2019** [comment]
这就尴尬了，找了半天没有WIN32的 7.51.0

**Comment by rosynirvana** [comment]
那是个字符串，表示ffmpeg送出去的user-agent，不用你装什么软件的

**Comment by lki2019** [comment]
如果调用本地播放器观看是什么命令呢？刚才查了下，没弄清楚到底用哪个命令
>ffplay -user_agent 'curl/7.51.0' 地址

这样的？

**Comment by lki2019** [comment]
已经有其他办法可以看了，
绕了一圈，youtube-dl 直接可以下载和播放的
youtube-dl http://streams.yupptv.com/freechannelplayer.aspx?id=144

mpv http://streams.yupptv.com/freechannelplayer.aspx?id=144

但是我看他支持的网站大全里，没有这个站啊

===============
好了，这个issues可以关啦，谢谢大神给予的讲解，也学到了新的东西！

那我就关闭啦，
