### ISSUE TITLE
又发现凤凰视频一种you-get未能解析的视频

### ISSUE THREAD

**Issue by lki2019** [soimort/you-get#2223]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

<pre><code>
you-get -di http://v.ifeng.com/program/special/sdzhjt/index.shtml

[DEBUG] get_content: http://v.ifeng.com/program/special/sdzhjt/index.shtml
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://v.ifeng.com/program/special/sdzhjt/index.shtml']
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\run
py.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\run
py.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts
\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\ifeng.py", line 36, in ifeng_download
    assert id, "can't find video info"
AssertionError: can't find video info
</code></pre>

===============
上一贴所反馈的全民 ted 凤凰视频 都已经下载新的脚本覆盖，测试正常！

**Comment by rosynirvana** [comment]
```

<li name="01f62b3e-eba5-44c5-ab09-7cdb8c637f1a">中国境界第五期对话胡海泉：天使目光</li>
--
  |  
  |  
  | <li name="01988bed-f423-495e-bf5f-5e51e90bdc21">中国境界第四期对话胡海泉：跨界之路</li>
  |  
  | <li name="0154c8d8-643b-4e9f-82f7-fcbc2c4f8e26">中国境界第三期对话许成钢：繁华背后</li>
  |  
  | <li name="01d717d7-3642-4a8c-97cc-385aae6a84a5">中国境界第二期对话梁锦松：香港未来</li>
  |  
  | <li name="016b52f0-7137-4f3d-ba8b-d66dae122b22">中国境界第一期对话梁锦松：守望香港</li>


```
一样是uuid
但是从url是看不出具体指向哪个视频的
只能当做playlist处理

**Comment by lki2019** [comment]
应该没什么人会找到凤凰这类视频去下载吧，比较偏，容易修就修，麻烦就忽略就好了
凤凰视频绝大部分能解析就行了

**Comment by rosynirvana** [comment]
不是麻烦，是这个url指向的不是一个视频，而是很多个

**Comment by lki2019** [comment]
第1期
 http://survey.news.ifeng.com/accumulator.php?key=016b52f0-7137-4f3d-ba8b-d66dae122b22&tm=1501911478706

第2期
 http://survey.news.ifeng.com/accumulator.php?key=01d717d7-3642-4a8c-97cc-385aae6a84a5&tm=1501911469181


第3期
GET http://survey.news.ifeng.com/accumulator.php?key=0154c8d8-643b-4e9f-82f7-fcbc2c4f8e26&tm=1501911458722



第4期
GET http://survey.news.ifeng.com/accumulator.php?key=01988bed-f423-495e-bf5f-5e51e90bdc21&tm=1501911448775



第5期
GET http://survey.news.ifeng.com/accumulator.php?key=01f62b3e-eba5-44c5-ab09-7cdb8c637f1a&tm=1501911433736





<pre><code>http://video19.ifeng.com/video09/2017/07/31/4712350-102-86987624-1158.mp4?gid=XC1LgV2w5cIi


http://video19.ifeng.com/video09/2017/07/26/4709979-102-086-1104.mp4?time=1501911449295&gid=NJKJwV2w5fzg


http://video19.ifeng.com/video09/2017/07/21/4708376-102-86987624-1729.mp4?time=1501911459854&gid=un-zsV2w5iPK


http://video19.ifeng.com/video09/2017/07/13/4706783-102-86987624-1050.mp4?time=1501911469797&gid=nkORUV2w5kyc


http://video19.ifeng.com/video09/2017/07/07/4704668-102-86987624-1955.mp4?time=1501911479650&gid=2lmo4V2w5nHT
</code></pre>

依次是5 4 3 2 1期

**Comment by lki2019** [comment]
http://v.ifeng.com/program/special/sdzhjt/index.shtml
打开默认播放是第5期的

回分配一个key值

然后点下面的4  3 2 1期就在分配对应的key值
然后每一期开始播放后，回分成5段

是么
