### ISSUE TITLE
8月5号晚，Bibili 小视频解析失效

### ISSUE THREAD

**Issue by lki2019** [soimort/you-get#2228]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

<pre><code>
C:\Users\Administrator>you-get -di https://vc.bilibili.com/video/430519
[DEBUG] url_locations: http://vc.bilibili.com/video/430519
[DEBUG] get_content: http://vc.bilibili.com/video/430519
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://vc.bilibili.com/video/430519']
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\run
py.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\run
py.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts
\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\bilibili.py", line 131, in prepare
    self.entry(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\bilibili.py", line 151, in entry
    cid = re.search(r'cid=(\d+)', self.page).group(1)
AttributeError: 'NoneType' object has no attribute 'group'</code></pre>

B站直播和B站大视频都正常

```

**Comment by rosynirvana** [comment]
这个子域名没人写过

**Comment by rosynirvana** [comment]
```
./you-get -di http://vc.bilibili.com/video/430519
[DEBUG] url_locations: http://vc.bilibili.com/video/430519
[DEBUG] get_content: http://vc.bilibili.com/video/430519
[DEBUG] get_content: http://api.vc.bilibili.com/clip/v1/video/detail?video_id=430519&need_playurl=1
site:                Bilibili
title:               德国骨科，某群老司机逼我的
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        vc
      container:     mp4
      size:          3.5 MiB (3686386 bytes)
    # download-with: you-get --format=vc [URL]

./you-get -di http://vc.bilibili.com/h5/vcdetail\?vc\=430519
[DEBUG] url_locations: http://vc.bilibili.com/h5/vcdetail?vc=430519
[DEBUG] get_content: http://vc.bilibili.com/h5/vcdetail?vc=430519
[DEBUG] get_content: http://api.vc.bilibili.com/clip/v1/video/detail?video_id=430519&need_playurl=1
site:                Bilibili
title:               德国骨科，某群老司机逼我的
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        vc
      container:     mp4
      size:          3.5 MiB (3686386 bytes)
    # download-with: you-get --format=vc [URL]

./you-get -d http://vc.bilibili.com/h5/vcdetail\?vc\=430519
[DEBUG] url_locations: http://vc.bilibili.com/h5/vcdetail?vc=430519
[DEBUG] get_content: http://vc.bilibili.com/h5/vcdetail?vc=430519
[DEBUG] get_content: http://api.vc.bilibili.com/clip/v1/video/detail?video_id=430519&need_playurl=1
site:                Bilibili
title:               德国骨科，某群老司机逼我的
stream:
    - format:        vc
      container:     mp4
      size:          3.5 MiB (3686386 bytes)
    # download-with: you-get --format=vc [URL]

Downloading 德国骨科，某群老司机逼我的.mp4 ...
 100% (  3.5/  3.5MB) ├█████████████████████████████████████████┤[1/1]  821 kB/s
```
