### ISSUE TITLE
在youtube上下载视频音频和视频分开了

### ISSUE THREAD

**Issue by llyzot** [soimort/you-get#2234]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

之前在youtube上下载视频没出现过这种情况，突然出现一例，试问一下是因为FFmepg的问题吗？
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by shikkoku** [comment]
视频链接呢？不贴出来怎么测？

**Comment by llyzot** [comment]
不好意思，忘了
感谢您的回复

发自我的 iPhone

在 2017年8月6日，12:29，Felix <notifications@github.com<mailto:notifications@github.com>> 写道：


视频链接呢？不贴出来怎么测？

**Comment by rosynirvana** [comment]
https://github.com/soimort/you-get/wiki/YouTube
