### ISSUE TITLE
Unable to download video from https://v.qq.com

### ISSUE THREAD

**Issue by waynelimt** [soimort/you-get#2235]
Please make sure these boxes are checked before submitting your issue – thank you!

- [/] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [/] Your `you-get` is up-to-date.
- [/] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [/] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [/] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
C:\Users\Wayne>you-get --debug https://v.qq.com/x/page/9ElXVEly1bx.html
[DEBUG] get_content: http://v.qq.com/x/page/9ElXVEly1bx.html
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=11&defnpayver=1&vid=9ElXVEly1bx
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10202&vid=9ElXVEly1bx&filename=9ElXVEly1bx.p202.1.mp4&appver=3.2.19.333
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/page/9ElXVEly1bx.html']
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1472, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1383, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1181, in download_main
    download(url, **kwargs)
  File "c:\python36\lib\site-packages\you_get\common.py", line 1465, in any_download
    m.download(url, **kwargs)
  File "c:\python36\lib\site-packages\you_get\extractors\qq.py", line 133, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "c:\python36\lib\site-packages\you_get\extractors\qq.py", line 31, in qq_download_by_vid
    part_info = get_content(key_api)
  File "c:\python36\lib\site-packages\you_get\common.py", line 353, in get_content
    response = urlopen_with_retry(req)
  File "c:\python36\lib\site-packages\you_get\common.py", line 330, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "c:\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

**Comment by lki2019** [comment]
<pre><code>
you-get -di https://v.qq.com/x/page/9ElXVEly1bx.html
[DEBUG] get_content: http://v.qq.com/x/page/9ElXVEly1bx.html
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333
&platform=11&defnpayver=1&vid=9ElXVEly1bx
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format
=10202&vid=9ElXVEly1bx&filename=9ElXVEly1bx.p202.1.mp4&appver=3.2.19.333
[DEBUG] url_info: http://42.236.95.145/vlive.qqvideo.tc.qq.com/AR5GP_RWXGJC8gmEH
efmBQ7lAeEJASYwu4pcbwr-jQqU/9ElXVEly1bx.p202.1.mp4?vkey=E9388A3201AECF6F89BE0164
EBBA762433DC5585E7CDC7D116905471D53AC56B8ADEC5A87A134610BA49FAE39BC81A7A66EB354D
FF0CBBC8FC70D81BCD123E076230E4BD5105CE49B5BACDB0F0E6CF222646D3E494F70B24BED5A302
60CB1730
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format
=10202&vid=9ElXVEly1bx&filename=9ElXVEly1bx.p202.2.mp4&appver=3.2.19.333
[DEBUG] url_info: http://42.236.95.145/vlive.qqvideo.tc.qq.com/AR5GP_RWXGJC8gmEH
efmBQ7lAeEJASYwu4pcbwr-jQqU/9ElXVEly1bx.p202.2.mp4?vkey=3E88157C7950C47A3EBDFF49
6B1A2A5EA3A0F4659D5BA0F280A63F627015D94B422CB09E06B29FE9F02EBC593B4D9FCC90878C1F
CD8555404D61C95E1C6F75A2CB291AEB180ED0BF1C9191E2DC6449532FA5D4629290CE2446D15CCE
33B96FAC
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format
=10202&vid=9ElXVEly1bx&filename=9ElXVEly1bx.p202.3.mp4&appver=3.2.19.333
[DEBUG] url_info: http://42.236.95.145/vlive.qqvideo.tc.qq.com/AR5GP_RWXGJC8gmEH
efmBQ7lAeEJASYwu4pcbwr-jQqU/9ElXVEly1bx.p202.3.mp4?vkey=BD6059672DCAC468D93AB6A4
459F29BB207223C0729B16D0E93C5C1BF8ECBA47731DD344FD941FCD28507785507895FB1EC46CA1
2499001AFEA3B9E60AB8884B8AE712199BDF10B4F68A91E4B9BE1A07BF6BFD545AA03910C5608901
B99E0E45
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format
=10202&vid=9ElXVEly1bx&filename=9ElXVEly1bx.p202.4.mp4&appver=3.2.19.333
[DEBUG] url_info: http://42.236.95.145/vlive.qqvideo.tc.qq.com/AR5GP_RWXGJC8gmEH
efmBQ7lAeEJASYwu4pcbwr-jQqU/9ElXVEly1bx.p202.4.mp4?vkey=BD6059672DCAC468D93AB6A4
459F29BB207223C0729B16D00B10F28833FF2F4148DCB5DD5D374028374412E5E7CD8270FF5FB9A1
79F260ACEA5748E10C2A4225B5CB61E24B286D39856869C180EB147679E52B8F7D54150E99D32D84
90428A37
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format
=10202&vid=9ElXVEly1bx&filename=9ElXVEly1bx.p202.5.mp4&appver=3.2.19.333
[DEBUG] url_info: http://42.236.95.145/vlive.qqvideo.tc.qq.com/AR5GP_RWXGJC8gmEH
efmBQ7lAeEJASYwu4pcbwr-jQqU/9ElXVEly1bx.p202.5.mp4?vkey=B0E90EC4F1FE2833ADE1ABB6
EE5EA05060CD182841AB30BE3427F13327B61A40168E4A66620024C5B053194E5CF3A3FDECA5EA61
A17E086E8BDC3EEFD15CCE50DF82211BAA96445006E486EC0D744FC7D9AEFBBD370E0E3FFE6DC251
D01BDF4C
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format
=10202&vid=9ElXVEly1bx&filename=9ElXVEly1bx.p202.6.mp4&appver=3.2.19.333
[DEBUG] url_info: http://42.236.95.145/vlive.qqvideo.tc.qq.com/AR5GP_RWXGJC8gmEH
efmBQ7lAeEJASYwu4pcbwr-jQqU/9ElXVEly1bx.p202.6.mp4?vkey=8A220CD4800D130D7C656381
BD552CDB4E7ABB101B86E8C03A8CFBCBAC467DF7937E52D92F243C5054AD3FE4F8973F1EF18C39BB
0FAD1A23010C851995669E877B49C3667199D338A75C7E4D58FA0DFAE14EA6C2E8853A16C54AB087
88A6F678
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format
=10202&vid=9ElXVEly1bx&filename=9ElXVEly1bx.p202.7.mp4&appver=3.2.19.333
[DEBUG] url_info: http://42.236.95.145/vlive.qqvideo.tc.qq.com/AR5GP_RWXGJC8gmEH
efmBQ7lAeEJASYwu4pcbwr-jQqU/9ElXVEly1bx.p202.7.mp4?vkey=98D45BB80266C2844DBB7211
9F44FFD53F7A8FBE02271E73175A46B50995FA4DFABECBC6E81B44DD15C187A4C8C5AAA7E44DCB59
125AA95E32A4B10ADB18AF9AB470730D840AE553ACB421D29D107FA26DA36B608B92758D299CCB84
ACF73EB4
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format
=10202&vid=9ElXVEly1bx&filename=9ElXVEly1bx.p202.8.mp4&appver=3.2.19.333
[DEBUG] url_info: http://42.236.95.145/vlive.qqvideo.tc.qq.com/AR5GP_RWXGJC8gmEH
efmBQ7lAeEJASYwu4pcbwr-jQqU/9ElXVEly1bx.p202.8.mp4?vkey=C38F8F776B9390D6EDB0F6DF
1E542560FBBFF8B272FF3DD69B846DA7FA6E42347A663C67D7AD20AEB13949AA78173D3C0CE1255B
F54001A181550057042B32A32E5EB2B7B4040226C57AF6B97ABCD2FF1F5870A6D1113135EDEC1E9F
69E86F6C
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format
=10202&vid=9ElXVEly1bx&filename=9ElXVEly1bx.p202.9.mp4&appver=3.2.19.333
[DEBUG] url_info: http://42.236.95.145/vlive.qqvideo.tc.qq.com/AR5GP_RWXGJC8gmEH
efmBQ7lAeEJASYwu4pcbwr-jQqU/9ElXVEly1bx.p202.9.mp4?vkey=98D45BB80266C2844DBB7211
9F44FFD53F7A8FBE02271E73C944911035BBE7BED192DF59056C74947C72F79C68F3CB0A9E19F576
4340F3A53975C9EFE723E35AC96A3FF5A9FBA94A5F66A3B7D87953BCEDEB17D16C5E0DF55ADA3120
90B377CD
Site:       QQ.com
Title:      新包青天_02
Type:       MPEG-4 video (video/mp4)
Size:       195.15 MiB (204633109 Bytes)
</code></pre>

**Comment by lki2019** [comment]
<pre><code>you-get https://v.qq.com/x/page/9ElXVEly1bx.html
Site:       QQ.com
Title:      新包青天_02
Type:       MPEG-4 video (video/mp4)
Size:       195.15 MiB (204633109 Bytes)

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 新包青天_02.mp4 ...
 0.0% (  0.0/195.2MB) ├────────────────────────────
 0.1% (  0.2/195.2MB) ├────────────────────────────
─────────────┤[1/9]    8 kB/s<pre><code>
