### ISSUE TITLE
问一个关于直播源抓取的问题

### ISSUE THREAD

**Issue by lki2019** [soimort/you-get#2237]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

<pre><code>http://v.iqilu.com/live/sdtv/

一个爱齐鲁的网络台，
我的目标是想抓取到直播源，添加到potplayer上观看，
主要是想研究下这类网络台直播源的抓取办法，

GET http://video.iqilu.com/channelInfo?op=get&p=player&fields=sname,lastSplitTime,cname,width,height&cid=sdtv&version=1.0.0.0&num=812938.092276454&home=false&from=http://v.iqilu.com/live/sdtv/ HTTP/1.1

GET http://sourcenode.iqilu.com/live/sdtv.idx?key1=662063bbd8c6019732e373eeac5ad7a5&key2=5985a6c3&r=0.26455404656007886 HTTP/1.1

GET http://sourcenode.iqilu.com/live/sdtv.idx?key1=662063bbd8c6019732e373eeac5ad7a5&key2=5985a6c3&r=0.0567965367808938 HTTP/1.1

GET http://sourcenode.iqilu.com/live/sdtv.idx?key1=662063bbd8c6019732e373eeac5ad7a5&key2=5985a6c3&r=0.23150311689823866 HTTP/1.1

GET http://sourcenode.iqilu.com/live/sdtv.idx?key1=662063bbd8c6019732e373eeac5ad7a5&key2=5985a6c3&r=0.8972740769386292 HTTP/1.1

浏览器嗅探插件  Wireshark  FD URLSnoope 我电脑上有的这几个抓包工具，我都看了下，
没发现相关的真实地址，应该是我不会用，

求大神们给予指点，这类网络台常规办法应该如何抓取直播源？

在某Q群询问后，有人抓出地址是这样 http://hlsgs.iqilu.com/live/sdtv/index.m3u8?sign=b5bc987afcda7cd188ec41039a0608d9&t=15db2eb0c58

但是应该是有时效性，我添加的时候已经看不了了

请问他是怎么抓取到这个地址的？</code></pre>

先感谢了

**Comment by rosynirvana** [comment]
学会用改user-agent的插件
m3u8是移动端的
默认的浏览器UA抓到的不是m3u8

**Comment by lki2019** [comment]
User-Agent Switcher？
我我切换到Chrome on Android Mobile
F12看看去

**Comment by lki2019** [comment]
搞定，谢谢大神指点·

**Comment by rosynirvana** [comment]
```
curl "http://liveauth.iqilu.com/nc_gs?channel=$ch_name"  -H "Referer: http://v.iqilu.com/live/$cn_name/" | js-beautify
```
to get cw and qq, m3u8 url is
```
http://hlsgs.iqilu.com/live/{ch_name}/index.m3u8?sign={cw}&t={qq}
```

you can get all channel names from the static page
```js
var channels = {
    "sdtv": {
        "id": 24,
        "live": "sdtv",
        "m3u8": "sdtv",
        "catname": "山东卫视"
    },
     "qlpd": {
        "id": 25,
        "live": "qilu",
        "m3u8": "qlpd",
        "catname": "齐鲁频道"
    },
     "ggpd": {
        "id": 31,
        "live": "gonggong",
        "m3u8": "ggpd",
        "catname": "公共频道"
    },
     "typd": {
        "id": 26,
        "live": "tiyu",
        "m3u8": "typd",
        "catname": "体育频道"
    },
     "shpd": {
        "id": 29,
        "live": "shenghuo",
        "m3u8": "shpd",
        "catname": "生活频道"
    },
     "zypd": {
        "id": 28,
        "live": "zongyi",
        "m3u8": "zypd",
        "catname": "综艺频道"
    },
     "nkpd": {
        "id": 30,
        "live": "nongke",
        "m3u8": "nkpd",
        "catname": "农科频道"
    },
     "yspd": {
        "id": 27,
        "live": "yingshi",
        "m3u8": "yspd",
        "catname": "影视频道"
    },
     "sepd": {
        "id": 32,
        "live": "shaoer",
        "m3u8": "sepd",
        "catname": "少儿频道"
    },
     "gjpd": {
        "id": 33,
        "live": "guoji",
        "m3u8": "gjpd",
        "catname": "国际频道"
    },
     "gwpd": {
        "id": 0,
        "live": "jjgw",
        "m3u8": "gwpd",
        "catname": "居家购物频道"
    }
};
```

**Comment by lki2019** [comment]
恩

其实还有一个配套的问题

http://v.iqilu.com/radio/main/yinyue.html

音频电台

我知道是RTMP流 用RTMPhelper 可以下载也可以播放
但是好像无法组合出一个真实地址 可以放到播放器里看，但是好像可以用RTMPDumpHelper+rtmpsrv-vlc 调用出VLC看

但是手动添加好像没用
===============================================
广播直播流地址 一个9个频道，直播流地址如下

http://newlive.iqilu.com:1935/ksd_radio/sdradio01/playlist.m3u8
http://newlive.iqilu.com:1935/ksd_radio/sdradio02/playlist.m3u8
http://newlive.iqilu.com:1935/ksd_radio/sdradio03/playlist.m3u8
...................
http://newlive.iqilu.com:1935/ksd_radio/sdradio08/playlist.m3u8
http://newlive.iqilu.com:1935/ksd_radio/sdradio09/playlist.m3u8

这几个地址 也是Q群甩出来的，我切换UA也没用 ，
这样的M3U8地址 我也不知道他咋搞出来的

**Comment by rosynirvana** [comment]
```js
//from http://v.iqilu.com/radioplay/js/channel.js

	xinwen:'sdradio01',
	jingji:'sdradio02',
	nvzhubo:'sdradio03',
	shenghuo:'sdradio04',
	jiaotong:'sdradio05',
	xiangcun:'sdradio06',
	yinyue:'sdradio07',
	tiyu:'sdradio08',
	jingjifm96:'sdradio09',
	shuzi:'sdradio10',
	fm106:'bz'
};

var channel_names = {
	xinwen:'山东人民广播电台',
	jingji:'山东广播经济频道',
	nvzhubo:'文艺频道Fashion Radio',
	shenghuo:'山东广播生活频道',
	jiaotong:'山东广播交通频道',
	xiangcun:'山东乡村广播',
	yinyue:'山东广播音乐频道',
	tiyu:'山东广播体育频道',
	jingjifm96:'山东广播经济FM96频道',
	shuzi:'山东广播数字频道',
	fm106:'滨州FM106.9私家车广播电台'
};

//节目单和频道映射
var channel_program = {
	xinwen:'1',
	jingji:'2',
	nvzhubo:'3',
	shenghuo:'4',
	jiaotong:'5',
	xiangcun:'6',
	yinyue:'7',
	tiyu:'8',
	jingjifm96:'9',
	shuzi:'10',
	fm106:'11'
};
```

server: ```rtmp://newlive.iqilu.com:1935/live_edge```

example: ```rtmpdump -r 'rtmp://newlive.iqilu.com:1935/live_edge' -y 'sdradio07' -o out.mp4```

**Comment by lki2019** [comment]
<pre><code>C:\Program Files\Livestreamer\rtmpdump\rtmpdumphelper121>rtmpdump -r 'rtmp://new
live.iqilu.com:1935/live_edge' -y 'sdradio07' -o out.mp4
RTMPDump v2.4 GIT-2015-12-14 (Compiled by KSV)
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
WARNING: Unknown protocol!

Connecting ...
INFO: Connected...
ERROR: rtmp server sent error
ERROR: rtmp server requested close
<pre><code>
C:\Program Files\Livestreamer\rtmpdump\rtmpdumphelper121>

**Comment by rosynirvana** [comment]
```
rtmpdump -r 'rtmp://newlive.iqilu.com:1935/live_edge' -y 'sdradio07' -o out.mp4
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting download at: 0.000 kB
INFO: Metadata:
INFO:   author                PowerSmart
INFO:   datarate              48.00
INFO:   livetime              0.00
INFO:   timeshift             0.00
INFO:   cyclebasetime         1501091069952
INFO:   audiosamplerate       48000.00
INFO:   audiosamplesize       0.00
INFO:   stereo                TRUE
INFO:   audiocodecid          10.00
INFO:   filesize              0.00
25.105 kB / 3.92 sec^C
Caught signal: 2, cleaning up, just a second...
35.628 kB / 5.59 sec
Download may be incomplete (downloaded about 0.00%), try resuming
```
这个 compiled by KSV的版本是不是有什么问题，为什么会报```WARNING: Unknown protocol!```

**Comment by lki2019** [comment]
https://github.com/K-S-V/Scripts/releases

应该不会吧··很多人在用的

**Comment by rosynirvana** [comment]
那抓包看看失败在协议的哪一步了

**Comment by lki2019** [comment]
rtmpdump -r rtmp://newlive.iqilu.com:1935/live_edge -y sdradio07 -o out.mp4

正常了，还是大神稳啊

**Comment by rosynirvana** [comment]
mpv播音频的时候不会弹出图形界面的

**Comment by lki2019** [comment]
切换UA这招真的太好用了
比如http://www.1tv.ru/live 这个是HDS流  DRM保护的


<pre><code>
C:\php>php AdobeHDS.php --manifest "http://edge4.1internet.tv/phds-live11/livepk
gr/_definst_/1tv-hd.f4m?e=1502110475" --delete --quality high

                            KSV Adobe HDS Downloader

Processing manifest info....
Quality Selection:
 Available: 2400 1250 950 650 350
 Selected : 2400
Fragments Total: 633382, First: 615061, Start: 633381, Parallel: 8
This stream is encrypted with FlashAccess DRM. Decryption of such streams isn't
currently possible with this script.

然后我切换了安卓UA

就成了HLS了

http://mobdrm.1tv.ru/hls-live10/streams/1tv/1tv.m3u8?cdn=http://cdn9.1internet.tv&e=1502110583&s=mAFKPsW9o45SuKAzYSUD5gS1f0maBN7PHekAXumsm2YlTnMoguxF7tc%2B16dU7PTgavOR3jssXqqMjNAr9rXZtweJbqU0cZlUgEDjsnGI%2BwJ4quCao7CP3ElXS0L92TItba68VfIV7uB20CDvwT6eqtU3iDK6X7yjLAl9%2FUIRIFHCVnFilZDD%2FHpiaqOESoD8k2KN5lZiEbnIqDcIURrkonHPUJ%2BtBRx0FOauN8UmCi5TfU%2B7UDgn37kbHk%2B9Be5hvMRWDDxIIt10YlCJSDsqXw%3D%3D

= 4548 fps= 30 q=-1.0 size=   29530kB time=00:03:01.84 bitrate=1330.3kbits/
= 4574 fps= 30 q=-1.0 size=   29754kB time=00:03:02.88 bitrate=1332.8kbits/
= 4610 fps= 31 q=-1.0 size=   30015kB time=00:03:04.32 bitrate=1334.0kbits/
= 4650 fps= 31 q=-1.0 size=   30275kB time=00:03:05.92 bitrate=1334.0kbits/
= 4686 fps= 31 q=-1.0 size=   30470kB time=00:03:07.36 bitrate=1332.2kbits/
= 4747 fps= 31 q=-1.0 size=   30964kB time=00:03:09.80 bitrate=1336.5kbits/
= 4748 fps= 31 q=-1.0 size=   31159kB time=00:03:10.01 bitrate=1343.3kbits/
= 4750 fps= 31 q=-1.0 size=   31166kB time=00:03:10.01 bitrate=1343.6kbits/
= 4756 fps= 31 q=-1.0 size=   31193kB time=00:03:10.16 bitrate=1343.8kbits/
= 4776 fps= 31 q=-1.0 size=   31193kB time=00:03:10.96 bitrate=1338.2kbits/
= 4811 fps= 31 q=-1.0 size=   31364kB time=00:03:12.36 bitrate=1335.7kbits/
= 4842 fps= 31 q=-1.0 size=   31572kB time=00:03:13.60 bitrate=1335.9kbits/
= 4897 fps= 31 q=-1.0 size=   31983kB time=00:03:15.80 bitrate=1338.1kbits/
= 4969 fps= 31 q=-1.0 size=   32369kB time=00:03:18.68 bitrate=1334.7kbits/
= 4998 fps= 31 q=-1.0 size=   32796kB time=00:03:20.02 bitrate=1343.2kbits/
= 5000 fps= 31 q=-1.0 size=   32808kB time=00:03:20.02 bitrate=1343.7kbits/
= 5002 fps= 31 q=-1.0 size=   32830kB time=00:03:20.02 bitrate=1344.6kbits/
= 5025 fps= 31 q=-1.0 size=   32830kB time=00:03:20.92 bitrate=1338.6kbits/
= 5063 fps= 31 q=-1.0 size=   32984kB time=00:03:22.44 bitrate=1334.7kbits/
= 5097 fps= 31 q=-1.0 size=   33242kB time=00:03:23.80 bitrate=1336.2kbits/
= 5175 fps= 31 q=-1.0 size=   33740kB time=00:03:26.92 bitrate=1335.8kbits/
<pre><code>
正常下载

**Comment by lki2019** [comment]
![qq 20170807210415](https://user-images.githubusercontent.com/30022431/29027675-3b3766fe-7bb4-11e7-8202-a975a2cee6a1.png)

前几天我还头疼这样DRM保护的咋弄，
现在播放和下载都搞定了
