### ISSUE TITLE
怎么添加给you-get的的所有请求加上一个动态的header

### ISSUE THREAD

**Issue by tcsp** [soimort/you-get#2238]
由于短时间大批量的爬取会造成封ip情况，所以选择了挂动态代理，但是需要对应的动态header来进行验证，目前没有发现可以通过命令选项来动态添加header的功能，看了源码，建议可以在common中的get_content,post_content中添加钩子来支持下该功能。还是我没有以正确的姿势查看文档，其实有动态添加header的选项。望解答

这个是动态代理需要的动态header验证文档：http://www.mayidaili.com/dynamic

目前希望能对应的设置上去。其实就是在header中添加类似这样的东西：```Proxy-Authorization:MYH-AUTH-MD5 sign=83EAA31C85F9DDE368F5266A90087488&app_key=12345678&timestamp=2015-12-02 15:32:58```

**Comment by rosynirvana** [comment]
一个get_content或post_content只是一次网络请求，为什么要hook
只是实现加一条header，在get_content外面包另一个函数就行了，或者monkey patching

还是说要在command line option里加一个``headers added to every network request'' ?  从命令行读函数然后```eval```？

**Comment by tcsp** [comment]
@rosynirvana 我目前是直接在python代码里面调用you-get命令，所以期望是你所说的在command line option中添加一个，由于最近才搞python和爬虫，所以深层次的东西不是懂太多，monkey patching如果可以Hot patch的话就可以解决我的问题了，本来我是想先改源码的，但是那样不太通用。先去研究下monkey patching。

**Comment by rosynirvana** [comment]
用cmdline opt传一个函数进去很不好用的吧，无论是语法上还是可复用性上

如果是scripting over you-get，那确实应该monkey patch, F. I.
```
old_get_content = common.get_content
def get_content_with_gnrt(url, headers, faker, gnrt_fn, gnrt_args):
    key, val = gnrt_fn(gnrt_args)
    headers[key] = val
    old_get_content(url, headers=headers, faker=faker)
common.get_content = get_content_with_gnrt
```
或者写个decorator也行

**Comment by tcsp** [comment]
@rosynirvana 加函数当然不至于
类似
`
you-get -header {"Proxy-Authorization": "MYH-AUTH-MD5 sign=83EAA31C85F9DDE368F5266A90087488&app_key=12345678&timestamp=2015-12-02 15:32:58"} http://v.xxx.com
`
至于这个header我会通过代码每次动态生成去调用命令就是了。
然后就是在get_content中获取这个header dic 进行merge。本来的想法是这样的。

monkey patch会参考你的意见，谢啦

**Comment by rosynirvana** [comment]
外部生成sign，那其实就是custom header了

https://github.com/soimort/you-get/issues/424

**Comment by tcsp** [comment]
是的，可是现在没有这个option吧

**Comment by rosynirvana** [comment]
现在没有，只是说这个问题之前被提出过

**Comment by tcsp** [comment]
感觉是可以添加一个的，这个个人理解还是比较通用的一个功能。

**Comment by rosynirvana** [comment]
除了这个私有的代理验证，没有其他适用环境
除非是用来测试，但测试都用curl测试

**Comment by yAnXImIN** [comment]
期待加上这个功能

**Comment by rosynirvana** [comment]
1. custom header的含义不明确，是适用于第一次网络请求还是所有？
1.1 如果是所有，除了主楼提出的proxy custom auth之外，是用来添加什么header的？ user-agent, referer, cookie都不应在此范围内，因为user-agent和referer的处理是交给extractor的实现的，cookie是另外用cookieJar来实现的。
1.2 如果是第一次，那么用户在不阅读源代码的前提下，知道第一次网络请求是什么吗？例如优酷第一次网络请求是访问阿里云的统计服务器来获取一个cookie，在debug log中是看不到的。

2. 实现这个并不是一件简单的事情，必须修改所有extractor。
extractor可以自由使用py标准库中所有的方法，简单修改common.py中的几个网络相关的函数是不能达到预期目的。此外还有一部分工作是交给外部进程的，例如ffmpeg和rtmpdump。但事实上没人需要you-get提供的所有extractor，修改所有其中大部分难免是无用功。

所以在我看来，真正需要这个功能的不如考虑手动修改自己需要的几个extractor。

本issue关闭，因为#424已经提出了这个问题，可以去#424发表意见

close for it dup #424
