### ISSUE TITLE
youku cann't download?

### ISSUE THREAD

**Issue by luhy118** [soimort/you-get#2239]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[root@easub-hz7 cache]# you-get --json --debug http://v.youku.com/v_show/id_XMjk0MjY3MjQ5Mg==.html?spm=a2hzp.8253869.0.0 
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk0MjY3MjQ5Mg==&ccode=0401&client_ip=192.168.1.1&utid=Tx4QErVZeFkCAXI3QCDBnrPQ&client_ts=1502163023
you-get: 客户端无权播放,201
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
>  
[root@easub-hz7 cache]# you-get --version
you-get: version 0.4.803, a tiny downloader that scrapes the web.
我的也是最新版了，

**Comment by rosynirvana** [comment]
```
you-get -di http://v.youku.com/v_show/id_XMjk0MjY3MjQ5Mg\=\=.html
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk0MjY3MjQ5Mg==&ccode=0401&client_ip=192.168.1.1&utid=px8QEumrjxUCAbZyAmHFJ3cD&client_ts=1502163367
site:                优酷 (Youku)
title:               曹焱兵托付曹玄亮 这条街你说了算
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          16.9 MiB (17678981 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjk0MjY3MjQ5Mg%3D%3D&type=hd3&ups_client_netip=182.114.2.97&ups_ts=1502163369&utid=px8QEumrjxUCAbZyAmHFJ3cD&ccode=0401&psid=b045c5e17e6e2584d0451d9dc697f31f&duration=112&expire=18000&ups_key=8aadbac841434b6fef36f6d89db0d57a
    # download-with: you-get --format=hd3 [URL]

    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          8.9 MiB (9316377 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjk0MjY3MjQ5Mg%3D%3D&type=hd2&ups_client_netip=182.114.2.97&ups_ts=1502163369&utid=px8QEumrjxUCAbZyAmHFJ3cD&ccode=0401&psid=b045c5e17e6e2584d0451d9dc697f31f&duration=112&expire=18000&ups_key=8aadbac841434b6fef36f6d89db0d57a
    # download-with: you-get --format=hd2 [URL]

    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          5.3 MiB (5597801 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjk0MjY3MjQ5Mg%3D%3D&type=mp4&ups_client_netip=182.114.2.97&ups_ts=1502163369&utid=px8QEumrjxUCAbZyAmHFJ3cD&ccode=0401&psid=b045c5e17e6e2584d0451d9dc697f31f&duration=112&expire=18000&ups_key=8aadbac841434b6fef36f6d89db0d57a
    # download-with: you-get --format=mp4 [URL]

    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          3.3 MiB (3499115 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjk0MjY3MjQ5Mg%3D%3D&type=flv&ups_client_netip=182.114.2.97&ups_ts=1502163369&utid=px8QEumrjxUCAbZyAmHFJ3cD&ccode=0401&psid=b045c5e17e6e2584d0451d9dc697f31f&duration=112&expire=18000&ups_key=8aadbac841434b6fef36f6d89db0d57a
    # download-with: you-get --format=flvhd [URL]
```

**Comment by luhy118** [comment]
应该是我的IP给YOUKU禁了？

**Comment by rosynirvana** [comment]
另外找个环境试试看就知道是不是了

**Comment by luhy118** [comment]
哦，好像真是禁了，想问下you-get如何添加headers,格式是什么

**Comment by rosynirvana** [comment]
那这个issue应该算是结束了
