### ISSUE TITLE
you-get如何添加header？

### ISSUE THREAD

**Issue by luhy118** [soimort/you-get#2240]
小弟初学，实在找不到资料，主要是支持不支持，还有格式的问题，因为我发现有个网站必须添加头部，主要是 headers=dict(Referer=referer)

**Comment by lki2019** [comment]
<pre><code>启动选项：
    -V | --version打印版本并退出。
    -h | --help打印帮助并退出。

干运行选项：（无实际下载）
    -i | --info打印提取的信息。
    -u | --url使用URL打印提取的信息。
         --json以JSON格式打印提取的URL。

下载选项：
    -n | --no-merge不合并视频部分。
         --no-caption不要下载字幕。
                                        （字幕，歌词，danmaku，...）
    -f | - 强制重写存在的文件。
    -F | - 格式<STREAM_ID>将视频格式设置为STREAM_ID。
    -O | --output-filename <FILE>设置输出文件名。
    -o | --output-dir <PATH>设置输出目录。
    -p | - 玩家<PLAYER [OPTIONS]>将提取的URL流式提取到播放器。
    -c | --cookies <COOKIES_FILE>加载cookies.txt或cookies.sqlite。
    -x | --http-proxy <HOST：PORT>使用HTTP代理进行下载。
    -y | --extractor-proxy <HOST：PORT>仅使用HTTP代理进行提取。
         --no-proxy不使用代理。
    -s | --socks-proxy <HOST：PORT>使用SOCKS5代理进行下载。
    -t | --timeout <SECONDS>设置套接字超时。
    -d | --debug显示追溯和其他调试信息。
    -I | - 输入文件从文件中读取非播放列表URL。
    -P | - 密码<PASSWORD>将视频访问密码设置为PASSWORD。<pre><code>

**Comment by luhy118** [comment]
you-get --help 里没有说怎么添加header阿

**Comment by lki2019** [comment]
好像可以理解为 那就是没有吧

**Comment by rosynirvana** [comment]
问题是什么叫“添加header”
一个完整的任务需要不止一次网络访问，那么添加的header要作用于哪一次？
这是特定extractor实现者需要考虑的事情

还是说你在用universal extractor

**Comment by luhy118** [comment]
就是在命令行时怎么加h，类似：you-get -c  xx http:xx  这种加载cookie一样，就第一次，我要在这条命令加个h，但不知怎么加：
you-get http://v.youku.com/v_show/id_XMjk0MjY3MjQ5Mg==.html

**Comment by rosynirvana** [comment]
当然不是说你提出的特定问题中，header要作用于哪次网络请求
而是没法知道作用于哪次，所以实现一个通用的cli option是不合理的

如果是挂代理有专门的option

**Comment by luhy118** [comment]
那就是添加不了h
