### ISSUE TITLE
尝试HLS+ AES128加密的流视频下载

### ISSUE THREAD

**Issue by lki2019** [soimort/you-get#2242]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

<pre><code>https://zeniusenglish.com/article-track/1661/Modals_Should/      2分51秒长度 HLS流

浏览器插件抓包
https://fable.vzaar.com/uspaes/vzaar/vzb/456/target/vzb4569d2abb964306b8a32f5198f3877c_aes.ism/.m3u8?uspak=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2emI0NTY5ZDJhYmI5NjQzMDZiOGEzMmY1MTk4ZjM4NzdjIiwiZXhwIjoxNTAyMjA2ODEwLCJnZXhwIjoxNTAyMTY3MjEwLCJpc20iOiIvdXNwYWVzL3Z6YWFyL3Z6Yi80NTYvdGFyZ2V0L3Z6YjQ1NjlkMmFiYjk2NDMwNmI4YTMyZjUxOThmMzg3N2NfYWVzLmlzbSIsImNuZSI6InZpZXcudnphYXIuY29tIn0.XP-XFeGVaB3wg63uNCJKY58iTitqe3lI0PCB9JdSxm4  

https://fable.vzaar.com/uspaes/vzaar/vzb/fbf/target/vzbfbfc90ffa9043c2a0c3e789b418eb51_aes.ism/.m3u8?uspak=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2emJmYmZjOTBmZmE5MDQzYzJhMGMzZTc4OWI0MThlYjUxIiwiZXhwIjoxNTAyMjA2ODE0LCJnZXhwIjoxNTAyMTY3MjE0LCJpc20iOiIvdXNwYWVzL3Z6YWFyL3Z6Yi9mYmYvdGFyZ2V0L3Z6YmZiZmM5MGZmYTkwNDNjMmEwYzNlNzg5YjQxOGViNTFfYWVzLmlzbSIsImNuZSI6InZpZXcudnphYXIuY29tIn0.d5-r-DdiglKd86xl6MAy0t4FJPIUOG3mUNPRth-ndFk  

FD抓包

GET https://view.vzaar.com/1571668/player HTTP/1.1

GET https://view.vzaar.com/v2/manifests/1571668.json HTTP/1.1

从json得出地址

m3u8_url=https://fable.vzaar.com/uspaes/vzaar/vzb/456/target/vzb4569d2abb964306b8a32f5198f3877c_aes.ism/.m3u8?uspak=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2emI0NTY5ZDJhYmI5NjQzMDZiOGEzMmY1MTk4ZjM4NzdjIiwiZXhwIjoxNTAyMjA3MzI4LCJnZXhwIjoxNTAyMTY3NzI4LCJpc20iOiIvdXNwYWVzL3Z6YWFyL3Z6Yi80NTYvdGFyZ2V0L3Z6YjQ1NjlkMmFiYjk2NDMwNmI4YTMyZjUxOThmMzg3N2NfYWVzLmlzbSIsImNuZSI6InZpZXcudnphYXIuY29tIn0.JhXs6-aQkmPvp6SlZc3knZxpDz3fqcApwuTD-NSMyDg

下载后打开：

#EXTM3U
#EXT-X-VERSION:3
## Created with Unified Streaming Platform(version=1.7.25)
#EXT-X-SESSION-KEY:METHOD=AES-128,URI="//goose.vzaar.com/keys?uspak=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2emI0NTY5ZDJhYmI5NjQzMDZiOGEzMmY1MTk4ZjM4NzdjIiwiZXhwIjoxNTAyMjA3MzI4LCJnZXhwIjoxNTAyMTY3NzI4LCJpc20iOiIvdXNwYWVzL3Z6YWFyL3Z6Yi80NTYvdGFyZ2V0L3Z6YjQ1NjlkMmFiYjk2NDMwNmI4YTMyZjUxOThmMzg3N2NfYWVzLmlzbSIsImNuZSI6InZpZXcudnphYXIuY29tIn0.JhXs6-aQkmPvp6SlZc3knZxpDz3fqcApwuTD-NSMyDg"

# variants
#EXT-X-STREAM-INF:BANDWIDTH=289000,CODECS="mp4a.40.2,avc1.42C00D",RESOLUTION=800x600
vzb4569d2abb964306b8a32f5198f3877c_aes-audio=84463-video=188000.m3u8?uspak=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2emI0NTY5ZDJhYmI5NjQzMDZiOGEzMmY1MTk4ZjM4NzdjIiwiZXhwIjoxNTAyMjA3MzI4LCJnZXhwIjoxNTAyMTY3NzI4LCJpc20iOiIvdXNwYWVzL3Z6YWFyL3Z6Yi80NTYvdGFyZ2V0L3Z6YjQ1NjlkMmFiYjk2NDMwNmI4YTMyZjUxOThmMzg3N2NfYWVzLmlzbSIsImNuZSI6InZpZXcudnphYXIuY29tIn0.JhXs6-aQkmPvp6SlZc3knZxpDz3fqcApwuTD-NSMyDg

# variants
#EXT-X-STREAM-INF:BANDWIDTH=90000,CODECS="mp4a.40.2"
vzb4569d2abb964306b8a32f5198f3877c_aes-audio=84463.m3u8?uspak=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2emI0NTY5ZDJhYmI5NjQzMDZiOGEzMmY1MTk4ZjM4NzdjIiwiZXhwIjoxNTAyMjA3MzI4LCJnZXhwIjoxNTAyMTY3NzI4LCJpc20iOiIvdXNwYWVzL3Z6YWFyL3Z6Yi80NTYvdGFyZ2V0L3Z6YjQ1NjlkMmFiYjk2NDMwNmI4YTMyZjUxOThmMzg3N2NfYWVzLmlzbSIsImNuZSI6InZpZXcudnphYXIuY29tIn0.JhXs6-aQkmPvp6SlZc3knZxpDz3fqcApwuTD-NSMyDg</code></pre>

搞不定，好像先要下载key文件 但是我下载 提示我要输入账号密码·

**Comment by rosynirvana** [comment]
访问key的时候要referer

**Comment by lki2019** [comment]
referer：https://view.vzaar.com/1571694/player

**Comment by lki2019** [comment]
<pre><code>如果m3u8文件中包含#EXT-X-KEY字段，那么可以断定这个HLS中的ts文件是被加密的，如：
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="https://drm.fptplay.net/secure/vod_decrypt2?token=eyJoYXNoX3ZhbHVlIjogImRiMGM3YjExNmVkNjRhMmE4ZGQ0NTg4NWEwMDc1M2VkIiwgInZpZGVvX2lkIjogIjU1NzgyZTgzMTdkYzEzMjg2NzljZjJkMCIsICJzZXJ2ZXJfdGltZSI6IDE0NTYyMTc2ODUsICJ2YWxpZF9taW51dGVzIjogNzIwfQ"
#EXTINF:10.0,
media_0.ts?token=eyJoYXNoX3ZhbHVlIjogImRiMGM3YjExNmVkNjRhMmE4ZGQ0NTg4NWEwMDc1M2VkIiwgInZpZGVvX2lkIjogIjU1NzgyZTgzMTdkYzEzMjg2NzljZjJkMCIsICJzZXJ2ZXJfdGltZSI6IDE0NTYyMTc2ODUsICJ2YWxpZF9taW51dGVzIjogNzIwfQ
#EXTINF:10.0,
media_1.ts?token=eyJoYXNoX3ZhbHVlIjogImRiMGM3YjExNmVkNjRhMmE4ZGQ0NTg4NWEwMDc1M2VkIiwgInZpZGVvX2lkIjogIjU1NzgyZTgzMTdkYzEzMjg2NzljZjJkMCIsICJzZXJ2ZXJfdGltZSI6IDE0NTYyMTc2ODUsICJ2YWxpZF9taW51dGVzIjogNzIwfQ
每个HLS文件都被使用AES-128方法加密，而解密的key文件可以通过URI指定的方式获得。
解密步骤如下：
1. 获取key文件，在HLS文件中找到#EXT-X-KEY，有一个uri，下载下来是16个字节的密钥
[ruby] view plain copy print?
<span class="variable">$ </span>strkey=<span class="variable">$(</span>hexdump -v -e <span class="string">'16/1 "%02x"'</span> key)  
2. 下载ts文件，针对每个ts文件（media_0.ts），从0开始按顺序编号（变量index）3. 将编号格式化成32字节长的字符串作为iv
[ruby] view plain copy print?
<span class="variable">$ </span>iv=<span class="variable">$(</span>printf <span class="string">'%032x'</span> <span class="variable">$index</span>)  
4. 解密ts文件：
$ openssl aes-128-cbc -d -in media_0.ts -out media_decryptd_0.ts -nosalt -iv $iv -K $strkey
另外，通过FFmpeg接收该HLS，则会自动完成解密操作。</code></pre>

找了找资料，貌似流程是这样

现在的任务是先把key搞下来

**Comment by rosynirvana** [comment]
不是，你学学用curl吧
浏览器不适合搞这种测试

key的URI加上referer就能正常拿到16bytes的key
如果没有referer，服务器会返回HTTP 401，HTTP 401表示未授权，浏览器只能弹出那个HTTP basic auth的框让你输入username:password。但实际上这和basic auth没什么关系，服务器只是要返回一个错误信息

**Comment by lki2019** [comment]
<pre><code>attempt to call a nil value
C:\Users\Administrator>curl --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36" --referer 'https://view.vzaar.com/1571694/player' -o E:\keys_2 http://goose.vzaar.com/keys?uspak=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2emJmYmZjOTBmZmE5MDQzYzJhMGMzZTc4OWI0MThlYjUxIiwiZXhwIjoxNTAyMjIwMDQ5LCJnZXhwIjoxNTAyMTgwNDQ5LCJpc20iOiIvdXNwYWVzL3Z6YWFyL3Z6Yi9mYmYvdGFyZ2V0L3Z6YmZiZmM5MGZmYTkwNDNjMmEwYzNlNzg5YjQxOGViNTFfYWVzLmlzbSIsImNuZSI6InZpZXcudnphYXIuY29tIn0.VwpHm5CZRKvgTprjyMxylkHBS55pWwcNK62b49TWBgs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    16  100    16    0     0      5      0  0:00:03  0:00:02  0:00:01    17

attempt to call a nil value
C:\Users\Administrator></code></pre>

**Comment by rosynirvana** [comment]
16bytes没错

**Comment by lki2019** [comment]
1. 获取key文件，在HLS文件中找到#EXT-X-KEY，有一个uri，下载下来是16个字节的密钥
[ruby] view plain copy print?
$ strkey=$(hexdump -v -e '16/1 "%02x"' key)  
2. 下载ts文件，针对每个ts文件（media_0.ts），从0开始按顺序编号（变量index）3. 将编号格式化成32字节长的字符串作为iv
[ruby] view plain copy print?
$ iv=$(printf '%032x' $index)  
4. 解密ts文件：
$ openssl aes-128-cbc -d -in media_0.ts -out media_decryptd_0.ts -nosalt -iv $iv -K $strkey
另外，通过FFmpeg接收该HLS，则会自动完成解密操作。

=========================


折腾了半天
1.我查看那个key文件 乱码 嫴&H`?Q-+紌+怷

UltraEdit和Notepad++ 我都试了 乱码啊

2.2. 下载ts文件，针对每个ts文件（media_0.ts），从0开始按顺序编号（变量index）3. 将编号格式化成32字节长的字符串作为iv
[ruby] view plain copy print?
$ iv=$(printf '%032x' $index)  

TS分段我都下载了，上面这句话是在什么环境下执行的？我是WIN7 32位

我有点看不懂他这个命令 

3.4. 解密ts文件：
$ openssl aes-128-cbc -d -in media_0.ts -out media_decryptd_0.ts -nosalt -iv $iv -K $strkey
另外，通过FFmpeg接收该HLS，则会自动完成解密操作。

这个命令是在什么环境下

openssl 这是什么

不知道有py环境下的脚本不，或者相关工具··

看的我头大，

现在key可以下载下来了，TS分段也可以下载下来

现在就差解密了

**Comment by rosynirvana** [comment]
就是乱码啊，二进制，不是文本，当成文本做字符映射一般都是乱码
那些是sh script，你试试cmder行不行

**Comment by lki2019** [comment]
C:\Users\Administrator\Desktop\解析电视案例\HLS AES解密>curl key_2
curl: (6) Couldn't resolve host 'key_2'

attempt to call a nil value
C:\Users\Administrator\Desktop\解析电视案例\HLS AES解密>type key_2
嫴&H`?Q-+紌+怷?
attempt to call a nil value

**Comment by rosynirvana** [comment]
打个比方，图片用文本编辑器打开，大概率出很多乱码，但是这图片本身没有问题
你熟悉的口令(password)不乱码是因为它本身也是纯文本，需要键盘输入的
这种不用键盘输入的key，不用做文本映射，所以也大概率乱码

**Comment by lki2019** [comment]
![1](https://user-images.githubusercontent.com/30022431/29067138-12e802c0-7c64-11e7-9f4d-d79c72952ea2.png)

OK了 右边的应该正确的

**Comment by lki2019** [comment]
![qq 20170809104840](https://user-images.githubusercontent.com/30022431/29103153-718e069e-7cf0-11e7-99ec-ad05de36d9b0.png)

搞定！！！

**Comment by wangqq335** [comment]
求教一下，最后咋解密成功得？？？

**Comment by wangqq335** [comment]
求教一下，最后咋解密成功得？？？
