### ISSUE TITLE
Can't download youku playlist

### ISSUE THREAD

**Issue by Romerhyr** [soimort/you-get#2244]
I can't download youku playlist. and there is the fuul output with '--debug'

you-get http://list.youku.com/albumlist/show/id_2336634.html?spm=a2h0k.8191403.0.0 --debug
[DEBUG] get_content: http://list.youku.com/albumlist/show/id_2336634.html?spm=a2h0k.8191403.0.0
site:                优酷 (Youku)
playlist:            头文字D国语版-中国领先视频网站,提供视频播放,视频发布,视频搜索 - 优酷播单 - 优酷视频
videos:

you-get http://list.youku.com/albumlist/show/id_27827644.html?spm=a2h0k.8191403.0.0 --debug
[DEBUG] get_content: http://list.youku.com/albumlist/show/id_27827644.html?spm=a2h0k.8191403.0.0
site:                优酷 (Youku)
playlist:            233-中国领先视频网站,提供视频播放,视频发布,视频搜索 - 优酷播单 - 优酷视频
videos:

Please help me solve this problem! THANKS!

**Comment by lki2019** [comment]
<pre><code>C:\Users\Administrator>you-get -di http://v.youku.com/v_show/id_XMjk0Mjg1ODczNg=
=.html?spm=a2hww.20023042.m_223465.5~5~5~5!4~5!2~5~5~A
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk0Mjg1ODczNg==&cc
ode=0401&client_ip=192.168.1.1&utid=gbQQErm9EkwCAToSQOxOLVSv&client_ts=150220143
9
you-get: 客户端无权播放,201<pre><code>

貌似优酷解析挂了···

**Comment by huixiangdou** [comment]
you-get -di http://v.youku.com/v_show/id_XMjgxNzA1OTAwOA\=\=.html\?spm\=a2h0k.8191407.0.0\&from\=s1.8-1-1.2
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjgxNzA1OTAwOA==&ccode=0401&client_ip=192.168.1.1&utid=wpkREjTkbgsCAbfMEMUBiTwx&client_ts=1502260162
you-get: 客户端无权播放,201

**Comment by lki2019** [comment]
@huixiangdou 昨晚开发者已经更新啦，

你更新一下就可以了pip3 install --upgrade https://github.com/soimort/you-get/archive/develop.zip
<pre><code>you-get -di http://v.youku.com/v_show/id_XMjgxNzA1OTAwOA\
=\=.html\?spm\=a2h0k.8191407.0.0\&from\=s1.8-1-1.2
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjgxNzA1OTAwOA&ccod
e=0401&client_ip=192.168.1.1&utid=uJoREqHPriUCAToSQOxFqv5X&client_ts=1502260372
site:                优酷 (Youku)
title:               豫剧《贺后骂殿》下集 洪先礼
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          94.1 MiB (98723341 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjgxNzA1OTAwOA%3
D%3D&type=flv&ups_client_netip=58.18.64.236&ups_ts=1502260409&utid=uJoREqHPriUCA
ToSQOxFqv5X&ccode=0401&psid=6965410d19a5b0929d4e7a6d05ebef80&duration=2962&expir
e=18000&ups_key=f1378a69496ce8b7b7d2c22602c9f46b
    # download-with: you-get --format=flvhd [URL]

'from\' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
</code></pre>

**Comment by lki2019** [comment]
@rosynirvana 大神，解析或者下载的时候会有部分错误

<pre><code>99.9% ( 94.1/ 94.1MB) ├██████████████████████████
 100% ( 94.1/ 94.1MB) ├██████████████████████████
█████████████┤[8/8]    8 MB/s
Merging video parts... Merged into 豫剧《贺后骂殿》下集 洪先礼.mp4

'from%5C' 不是内部或外部命令，也不是可运行的程序
或批处理文件。<pre><code>

**Comment by rosynirvana** [comment]
url或者转义，或者引用

```
http://v.youku.com/v_show/id_XMTE4NjQ2OTI4.html\?spm\=a2h1n.8251843.playList.5\!2\~5\~A\&f\=2336634\&o\=0
```

```
''http://v.youku.com/v_show/id_XMTE4NjQ2OTI4.html?spm=a2h1n.8251843.playList.5!2~5~A&f=2336634&o=0''
```

**Comment by rosynirvana** [comment]
dup #1596
