### ISSUE TITLE
优酷客户端无权播放,201 错误，下载不了

### ISSUE THREAD

**Issue by jianxiyan2017** [soimort/you-get#2247]
you-get -i http://v.youku.com/v_show/id_XNjI1MDA2Nzgw.html
you-get: 客户端无权播放,201 ,

**Comment by lki2019** [comment]
https://github.com/soimort/you-get/issues/2244  看这个 你这个主题关闭吧··

**Comment by jianxiyan2017** [comment]
好的，谢谢

**Comment by wzhb** [comment]
能解释下什么意思吗？萌新看不懂
