### ISSUE TITLE
youku好像真出问题了？

### ISSUE THREAD

**Issue by luhy118** [soimort/you-get#2248]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
 D:\workspace\clip-spider>you-get -di http://v.youku.com/v_show/id_XOTE0MTUzNTA4.html?spm=a2h1n.8251843.playList.5~5~A&f=28021623&o=0
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XOTE0MTUzNTA4&ccode=0401&client_ip=192.168.1.1&utid=j78RErkiwBECAbcOHfYm1oha&client_ts=1502269786
you-get: 客户端无权播放,201
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
D:\workspace\clip-spider>you-get --version
you-get: version 0.4.803, a tiny downloader that scrapes the web.

本人是最新版本，帖子里是我本机上测试的，然后我又在其它其它四五台机器上，主要是阿里云也测试了，都是同样的结果。

**Comment by einverne** [comment]
你有大规模下载吗？ IP 被察觉了？

**Comment by luhy118** [comment]
可以证实的是我这次测试中有两台机子昨天正常，今天在我测试之前并没有下载过优酷网视频或网页

**Comment by lki2019** [comment]
<pre><code>you-get -di "http://v.youku.com/v_show/id_XOTE0MTUzNTA4.h
tml?spm=a2h1n.8251843.playList.5~5~A&f=28021623&o=0"
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XOTE0MTUzNTA4&ccode=
0401&client_ip=192.168.1.1&utid=58gREnowwTsCAToSQOwE7ijK&client_ts=1502272194
site:                优酷 (Youku)
title:               先别管光圈快门了 9个必学的简单摄影构图技巧
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          27.0 MiB (28269551 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XOTE0MTUzNTA4&typ
e=hd2&ups_client_netip=58.18.64.236&ups_ts=1502272231&utid=58gREnowwTsCAToSQOwE7
ijK&ccode=0401&psid=d56613203195e058eae8b93612d116f8&duration=188&expire=18000&u
ps_key=2a4f1f1561bb1c8fc6dbff1e7344db3d
    # download-with: you-get --format=hd2 [URL]

    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          12.3 MiB (12906578 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XOTE0MTUzNTA4&typ
e=mp4&ups_client_netip=58.18.64.236&ups_ts=1502272231&utid=58gREnowwTsCAToSQOwE7
ijK&ccode=0401&psid=d56613203195e058eae8b93612d116f8&duration=188&expire=18000&u
ps_key=2a4f1f1561bb1c8fc6dbff1e7344db3d
    # download-with: you-get --format=mp4 [URL]

    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          6.4 MiB (6733003 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XOTE0MTUzNTA4&typ
e=flv&ups_client_netip=58.18.64.236&ups_ts=1502272231&utid=58gREnowwTsCAToSQOwE7
ijK&ccode=0401&psid=d56613203195e058eae8b93612d116f8&duration=188&expire=18000&u
ps_key=2a4f1f1561bb1c8fc6dbff1e7344db3d
    # download-with: you-get --format=flvhd [URL]<pre><code>

**Comment by lki2019** [comment]
https://github.com/soimort/you-get/issues/2244 这个问题里面的回复你看过了么？
更新到最新了没啊

**Comment by luhy118** [comment]
@lki2019 按你发我重新安装了，版本号一样的，不过重装后都正常了，3Q。

**Comment by lki2019** [comment]
和版本号没啥关系 你那版本号24号发布的成品·

到今天新增和改动了不少地方，
所以pip3 install --upgrade https://github.com/soimort/you-get/archive/develop.zip
这样更新能把所有的改动都更新上，虽然你现在去看版本号一样是之前的版本号

**Comment by luhy118** [comment]
@lki2019 哦，经验不多，那我每次出现这类问题不是得先重装一下？

**Comment by lki2019** [comment]
反正我没事就pip3 install --upgrade https://github.com/soimort/you-get/archive/develop.zip

就这样更新一下····能确保把此时此刻之前的改动都更新上··
