### ISSUE TITLE
youku and tudou 201

### ISSUE THREAD

**Issue by chuiniu** [soimort/you-get#2249]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ x] Your `you-get` is up-to-date.
- [ x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x ] 您的`you-get`为最新版.
- [x ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
you-get --debug http://v.youku.com/v_show/id_XMjkyNTU3MTIyOA==.html
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjkyNTU3MTIyOA==&ccode=0401&client_ip=192.168.1.1&utid=D/gSEt91aC0CAS9cdSqVJ%2Btw&client_ts=1502349839
you-get: 客户端无权播放,201
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by lki2019** [comment]
请看这个 https://github.com/soimort/you-get/issues/2244

**Comment by chuiniu** [comment]
收到，多谢 @lki2019

**Comment by williamhezh** [comment]
似乎是有这个问题

**Comment by chuiniu** [comment]
按照 pip3 install --upgrade https://github.com/soimort/you-get/archive/develop.zip  更新之后短暂ok，现在有不行了，还是客户端无权播放，201

**Comment by chuiniu** [comment]
@lki2019 短暂ok之后，现在又201了。。。

**Comment by lki2019** [comment]
地址  什么的贴上来看看
我这里正常

**Comment by chuiniu** [comment]
换了一台机器发现没事，怀疑是不是封IP了。。。

**Comment by chuiniu** [comment]
you-get --debug http://v.youku.com/v_show/id_XMjkyNTU3MTIyOA==.html
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjkyNTU3MTIyOA==&ccode=0401&client_ip=192.168.1.1&utid=ZfgSEpv0xUACAS9cdSrUaO1r&client_ts=1502349925
you-get: 客户端无权播放,201

**Comment by lki2019** [comment]
如果你频繁的下载优酷的视频，
比如下了几十级 上百什么的
也许会有短暂封禁这个IP连接优酷服务器的可能吧

如果你是ADSL拨号的 重新拨号换个IP就好了

**Comment by lki2019** [comment]
<pre><code>
you-get --debug http://v.youku.com/v_show/id_XMjkyNTU3MTI
yOA==.html
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjkyNTU3MTIyOA==&cc
ode=0401&client_ip=192.168.1.1&utid=gPoSEn%2BnElMCAToSQOzeKTtc&client_ts=1502350
424
site:                优酷 (Youku)
title:               《无限逆境之末班地铁》优酷独家上线 实景还原末班地铁揭秘离奇
失踪案 170727
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          39.8 MiB (41686123 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjkyNTU3MTIyOA%3
D%3D&type=hd2&ups_client_netip=58.18.64.236&ups_ts=1502350464&utid=gPoSEn%2BnElM
CAToSQOzeKTtc&ccode=0401&psid=a006ae014b51da876f273fd02484800c&duration=234&expi
re=18000&ups_key=3dcb28ec0eb1a28a1ef2a6d83ead333d
    # download-with: you-get --format=hd2 [URL]

Downloading 《无限逆境之末班地铁》优酷独家上线 实景还原末班地铁揭秘离奇失踪案 17
0727.flv ...
 0.0% (  0.0/ 39.8MB) ├────────────────────────────
 0.6% (  0.2/ 39.8MB) ├────────────────────────────
 1.3% (  0.5/ 39.8MB) ├█───────────────────────────
 1.9% (  0.8/ 39.8MB) ├█───────────────────────────
 2.5% (  1.0/ 39.8MB) ├█───────────────────────────
 3.1% (  1.2/ 39.8MB) ├██──────────────────────────
 3.8% (  1.5/ 39.8MB) ├██──────────────────────────
 4.4% (  1.8/ 39.8MB) ├██──────────────────────────
 5.0% (  2.0/ 39.8MB) ├███─────────────────────────
 5.7% (  2.2/ 39.8MB) ├███─────────────────────────
 6.3% (  2.5/ 39.8MB) ├███─────────────────────────
 6.9% (  2.8/ 39.8MB) ├███─────────────────────────
 7.5% (  3.0/ 39.8MB) ├███─────────────────────────
 8.2% (  3.2/ 39.8MB) ├████────────────────────────
 8.8% (  3.5/ 39.8MB) ├████────────────────────────
 9.4% (  3.8/ 39.8MB) ├████────────────────────────
10.1% (  4.0/ 39.8MB) ├█████───────────────────────
10.7% (  4.2/ 39.8MB) ├█████───────────────────────
11.3% (  4.5/ 39.8MB) ├█████───────────────────────
11.9% (  4.8/ 39.8MB) ├█████───────────────────────
12.6% (  5.0/ 39.8MB) ├█████───────────────────────
13.2% (  5.2/ 39.8MB) ├██████──────────────────────
13.8% (  5.5/ 39.8MB) ├██████──────────────────────
14.5% (  5.8/ 39.8MB) ├██████──────────────────────
15.1% (  6.0/ 39.8MB) ├███████─────────────────────
15.7% (  6.2/ 39.8MB) ├███████─────────────────────
16.4% (  6.5/ 39.8MB) ├███████─────────────────────
17.0% (  6.8/ 39.8MB) ├███████─────────────────────
17.6% (  7.0/ 39.8MB) ├███████─────────────────────
18.2% (  7.2/ 39.8MB) ├████████────────────────────
18.9% (  7.5/ 39.8MB) ├████████────────────────────
19.5% (  7.8/ 39.8MB) ├████████────────────────────
20.1% (  8.0/ 39.8MB) ├█████████───────────────────
─────────────┤[1/1]    4 MB/sTraceback (most recent call last):<pre><code>

**Comment by chuiniu** [comment]
好的，那我过段时间再试试。  感谢。 @lki2019
