### ISSUE TITLE
8月11号 CNTV部分视频未能解析

### ISSUE THREAD

**Issue by lki2019** [soimort/you-get#2251]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

<pre><code>you-get -di http://tv.cctv.com/special/CCTV4jianjun90/index.shtml
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://tv.cctv.com/special/CCTV4jianjun90/index.shtml']
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts
\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1352, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1259, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1057, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1345, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\cntv.py", line 50, in cntv_download
    raise NotImplementedError(url)
NotImplementedError: http://tv.cctv.com/special/CCTV4jianjun90/index.shtml</code></pre>

我初步看了下，好像和我上次说的那个凤凰视频的类似，
是个列表形式的，列表里每个视频地址都是一样

**Comment by rosynirvana** [comment]
这又是个播放列表
```
loading_video('1','fcbf75796825478db594804de7ebafc6');
loading_video('2','78f0a8a947d84c6eb1e941b689786d1f');
loading_video('3','a5cc2b1f9cec41489c7352fdb2cb94ce');
loading_video('4','25c2de2c77ba4cea9f0509a6ccec7477');
loading_video('5','6146d00f11b54fefbd4c15df34d3c5aa');
```
