### ISSUE TITLE
优酷已加载cookies但错误201

### ISSUE THREAD

**Issue by saku1119** [soimort/you-get#2252]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [X] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [X] 您的`you-get`为最新版.
- [X] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [X] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [X] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>you-get -i -c cookies.txt http://v.youku.com/v_show/id_XM
jk2MDA3Mjk2OA==.html
you-get: Found cna in imported cookies. Use it
you-get: 客户端无权播放,201

C:\Users\Administrator>you-get -i --debug -c cookies.txt http://v.youku.com/v_sh
ow/id_XMjk2MDA3Mjk2OA==.html
you-get: Found cna in imported cookies. Use it
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk2MDA3Mjk2OA==&cc
ode=0401&client_ip=192.168.1.1&utid=AaCcEaqtywgCAXDtEqM%2B%2BCFP&client_ts=15024
46859
you-get: 客户端无权播放,201

C:\Users\Administrator>
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

>今天发现又不好用了0.0 已更新到最新版本 依然无效……cookies也是最新的，放在C:\Users\Administrator 处 

> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
release版本不行，要升级到develop branch

**Comment by saku1119** [comment]
好了~谢谢~我以为那个develop branch装过一次就不用管了~~噗~已经可以了~再次谢谢~~~o(∩_∩)o ~
