### ISSUE TITLE
优酷的vip视频又无法下载了 

### ISSUE THREAD

**Issue by 614567264** [soimort/you-get#2253]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]优酷普通的视频可以下载 但是vip视频加载cookies无法下载了，软件升级到了0.4.803最新版  还要怎样才能解决？
> [舔 :icecream:!]C:\Users\zheng\Desktop\PILI>you-get -c C:\Users\zheng\Desktop\PILI\cookies.txt http://v.youku.com/v_show/id_XMjk2MDA3Mjk2OA==.html?spm=a2h0k.8191407.0.0&from=s1.8-1-1.1
you-get: flvhd is a preview
you-get: mp4 is a preview
you-get: hd3 is a preview
you-get: hd2 is a preview
site:                优酷 (Youku)
title:               39 八歧邪神
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          1921.8 MiB (2015132134 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjk2MDA3Mjk2OA%3D%3D&type=hd3&ups_client_netip=119.39.156.216&ups_ts=1502449601&utid=wH0UEiei0UECAXcnnNjCHj6P&ccode=0401&psid=c1d30276b8891a74fb041a2f5d24fb8b&duration=4397&expire=18000&ups_key=d53e1cdbe19970ae92a20d247da659f1
    # download-with: you-get --format=hd3 [URL]

you-get: [Failed] Cannot extract video source.
'from' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by lki2019** [comment]
这个视频好像你得开通了频道VIP观看视频，然后在抓取COOKIES 才可以用you-get下载的吧？
你现在是黄金账号么？还是白银

**Comment by lki2019** [comment]
我看了下，好像目前市面上例如旋风解析 ck47之类的解析接口都不能解析这类需要开通频道VIP才可以看的视频吧？

**Comment by 614567264** [comment]
之前我用cookies下了几个月了  就是今天应该优酷又加密了  可能需要升级什么插件

**Comment by rosynirvana** [comment]
你用的哪个commit?

**Comment by 614567264** [comment]
不懂  我就是按以前的方法you-get -c cookies +网址

**Comment by rosynirvana** [comment]
那换个说法，你什么时候更新的you-get
是0.4.803 release还是develop branch

**Comment by 614567264** [comment]
就是我刚刚用pip3升级了一下 
pip3 install --upgrade https://github.com/soimort/you-get/archive/develop.zip
然后就升级到0.4.803 这样升级对吗？

**Comment by lki2019** [comment]
听说优酷换了加密商了，现在和深造合作了http://www.shenzaokeji.com/

@614567264  对了你上一次升级是什么时候呢？用的什么命令升级的？

**Comment by rosynirvana** [comment]
pip3 install --upgrade https://github.com/soimort/you-get/archive/94739f5b462a22f54bee396428ec19ee1f1b4ae2.zip
呢?

**Comment by rosynirvana** [comment]
和那个shenzaokeji的没关系，那个就是用优酷CDN(现在是阿里CDN了)，然后shenzao提供别的，建卖教程视频的平台，不相干的

**Comment by 614567264** [comment]
仍然是这个结果 我记得上次是上个月27号左右优酷加密了  然后我用pip3 install --upgrade https://github.com/soimort/you-get/archive/develop.zip升级了一下就可以下载了   到今天又不行了 用pip3 install --upgrade https://github.com/soimort/you-get/archive/94739f5b462a22f54bee396428ec19ee1f1b4ae2.zip也无法下载
C:\Users\zheng\Desktop\PILI>you-get -c C:\Users\zheng\Desktop\PILI\cookies.txt http://v.youku.com/v_show/id_XMjk2MDA3Mjk2OA==.html?spm=a2h0k.8191407.0.0&from=s1.8-1-1.1
you-get: flvhd is a preview
you-get: mp4 is a preview
you-get: hd3 is a preview
you-get: hd2 is a preview
site:                优酷 (Youku)
title:               39 八歧邪神
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          1921.8 MiB (2015132134 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjk2MDA3Mjk2OA%3D%3D&type=hd3&ups_client_netip=119.39.156.216&ups_ts=1502453560&utid=N40UEsUsmRYCAXcnnNhZW7EN&ccode=0401&psid=7891cc386775d60a086f036e9b048c9a&duration=4397&expire=18000&ups_key=dc701a3d186b0b51fd6ebd44894760f2
    # download-with: you-get --format=hd3 [URL]

you-get: [Failed] Cannot extract video source.
'from' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by rosynirvana** [comment]
你的log不对，贴全了吗？
cookie是一直用的一个文件？

**Comment by 614567264** [comment]
先前一直都是这样使用的啊

**Comment by rosynirvana** [comment]
从什么时候开始，到什么时候发现不能用呢？
还有这个cookie.txt是什么时候导出的?

**Comment by 614567264** [comment]
就是今天发现不能下载的  cookies是5月份导出的 一直用到现在

**Comment by rosynirvana** [comment]
没试过重新导一个cookie吗？

**Comment by 614567264** [comment]
ok了 谢谢

**Comment by lki2019** [comment]
@614567264  你是优酷会员么？
我是白银 我那会试验了下 好像不行··
