### ISSUE TITLE
优酷下载中断较多，自动合并后时长不对

### ISSUE THREAD

**Issue by saku1119** [soimort/you-get#2254]
汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [1] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [1] 您的`you-get`为最新版.
- [1] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [1] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [1] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [优酷下载的视频，中途中断很多，因为单个视频平均30+小短的flv，以前自动合并没有问题，今天自动合并出来的时长不对，并提示错误。另外发现，下载中断后重新下载时，原先的那个临时文件会直接变成已下载完的视频flv文件，但此flv通常无法播放。]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
我猜你下的是不是游戏分区的视频

**Comment by saku1119** [comment]
不是不是~和之前问你的那个一样~是自频道会员的布袋戏剧集~每周五更新新剧的那个~

**Comment by saku1119** [comment]
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>you-get -c cookies.txt -o C:\Users\Administrator\Desktop\
1 --format=hd3 http://v.youku.com/v_show/id_XMjk2MDAzMTQ1Ng==.html?spm=a2hzp.825
3869.0.0
you-get: Found cna in imported cookies. Use it
site:                优酷 (Youku)
title:               40 殉道之眼
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          1887.5 MiB (1979156140 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjk2MDAzMTQ1Ng%3
D%3D&type=hd3&ups_client_netip=119.180.53.104&ups_ts=1502463553&utid=AaCcEaqtywg
CAXDtEqM%2B%2BCFP&ccode=0401&psid=b16f7e783f93709a533f35f12827dc99&ups_userid=10
9718254&ups_ytid=402702319&duration=4250&expire=18000&ups_key=ac12198dd2a5542302
a7d65ba2594414
    # download-with: you-get --format=hd3 [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 40 殉道之眼.flv ...
 0.0% (   0.0/1887.5MB) ├───────────────────────────
 4.5% (  85.8/1887.5MB) ├██─────────────────────────
 8.3% ( 156.2/1887.5MB) ├███────────────────────────
11.5% ( 217.5/1887.5MB) ├█████──────────────────────
15.1% ( 284.6/1887.5MB) ├██████─────────────────────
18.9% ( 356.0/1887.5MB) ├███████────────────────────
22.6% ( 426.6/1887.5MB) ├█████████──────────────────
25.4% ( 478.5/1887.5MB) ├██████████─────────────────
28.7% ( 541.5/1887.5MB) ├███████████────────────────
31.8% ( 600.4/1887.5MB) ├████████████───────────────
34.2% ( 645.2/1887.5MB) ├█████████████──────────────
36.4% ( 686.9/1887.5MB) ├██████████████─────────────
39.4% ( 743.5/1887.5MB) ├███████████████────────────
42.7% ( 806.6/1887.5MB) ├████████████████───────────
46.2% ( 872.0/1887.5MB) ├██████████████████─────────
49.5% ( 933.4/1887.5MB) ├███████████████████────────
52.6% ( 992.0/1887.5MB) ├████████████████████───────
55.9% (1056.0/1887.5MB) ├█████████████████████──────
59.9% (1131.2/1887.5MB) ├██████████████████████─────
62.5% (1179.1/1887.5MB) ├███████████████████████────
65.5% (1236.2/1887.5MB) ├█████████████████████████──
68.0% (1283.1/1887.5MB) ├██████████████████████████─
71.4% (1348.6/1887.5MB) ├███████████████████████████
74.8% (1411.4/1887.5MB) ├███████████████████████████
74.8% (1411.6/1887.5MB) ├███████████████████████████
74.8% (1411.9/1887.5MB) ├███████████████████████████
74.8% (1412.1/1887.5MB) ├███████████████████████████
74.8% (1412.4/1887.5MB) ├███████████████████████████
74.8% (1412.6/1887.5MB) ├███████████████████████████
74.9% (1412.9/1887.5MB) ├███████████████████████████
74.9% (1413.1/1887.5MB) ├███████████████████████████
74.9% (1413.4/1887.5MB) ├███████████████████████████
74.9% (1413.6/1887.5MB) ├███████████████████████████
74.9% (1413.9/1887.5MB) ├███████████████████████████
74.9% (1414.1/1887.5MB) ├███████████████████████████
74.9% (1414.4/1887.5MB) ├███████████████████████████
74.9% (1414.6/1887.5MB) ├███████████████████████████
75.0% (1414.9/1887.5MB) ├███████████████████████████
75.0% (1415.1/1887.5MB) ├███████████████████████████
75.0% (1415.4/1887.5MB) ├███████████████████████████
75.0% (1415.6/1887.5MB) ├███████████████████████████
75.0% (1415.9/1887.5MB) ├███████████████████████████
75.0% (1416.1/1887.5MB) ├███████████████████████████
75.0% (1416.4/1887.5MB) ├███████████████████████████
75.1% (1416.6/1887.5MB) ├███████████████████████████
75.1% (1416.9/1887.5MB) ├███████████████████████████
75.1% (1417.1/1887.5MB) ├███████████████████████████
75.1% (1417.4/1887.5MB) ├███████████████████████████
75.1% (1417.6/1887.5MB) ├███████████████████████████
75.1% (1417.9/1887.5MB) ├███████████████████████████
75.1% (1418.1/1887.5MB) ├███████████████████████████
75.1% (1418.4/1887.5MB) ├███████████████████████████
75.2% (1418.6/1887.5MB) ├███████████████████████████
75.2% (1418.9/1887.5MB) ├███████████████████████████
75.2% (1419.1/1887.5MB) ├███████████████████████████
75.2% (1419.4/1887.5MB) ├███████████████████████████
75.2% (1419.6/1887.5MB) ├███████████████████████████
75.2% (1419.9/1887.5MB) ├███████████████████████████
75.2% (1420.1/1887.5MB) ├███████████████████████████
75.3% (1420.4/1887.5MB) ├███████████████████████████
75.3% (1420.6/1887.5MB) ├███████████████████████████
75.3% (1420.9/1887.5MB) ├███████████████████████████
75.3% (1421.1/1887.5MB) ├███████████████████████████
75.3% (1421.4/1887.5MB) ├███████████████████████████
75.3% (1421.6/1887.5MB) ├███████████████████████████
75.3% (1421.9/1887.5MB) ├███████████████████████████
75.3% (1422.1/1887.5MB) ├███████████████████████████
75.4% (1422.4/1887.5MB) ├███████████████████████████
75.4% (1422.6/1887.5MB) ├███████████████████████████
75.4% (1422.9/1887.5MB) ├███████████████████████████
75.4% (1423.1/1887.5MB) ├███████████████████████████
75.4% (1423.4/1887.5MB) ├███████████████████████████
75.4% (1423.6/1887.5MB) ├███████████████████████████
75.4% (1423.9/1887.5MB) ├███████████████████████████
75.5% (1424.1/1887.5MB) ├███████████████████████████
75.5% (1424.4/1887.5MB) ├███████████████████████████
75.5% (1424.6/1887.5MB) ├███████████████████████████
75.5% (1424.9/1887.5MB) ├███████████████████████████
75.5% (1425.1/1887.5MB) ├███████████████████████████
75.5% (1425.4/1887.5MB) ├███████████████████████████
75.5% (1425.6/1887.5MB) ├███████████████████████████
75.5% (1425.9/1887.5MB) ├███████████████████████████
75.6% (1426.1/1887.5MB) ├███████████████████████████
75.6% (1426.4/1887.5MB) ├███████████████████████████
75.6% (1426.6/1887.5MB) ├███████████████████████████
75.6% (1426.9/1887.5MB) ├███████████████████████████
75.6% (1427.1/1887.5MB) ├███████████████████████████
75.6% (1427.4/1887.5MB) ├███████████████████████████
75.6% (1427.6/1887.5MB) ├███████████████████████████
75.6% (1427.9/1887.5MB) ├███████████████████████████
75.7% (1428.1/1887.5MB) ├███████████████████████████
75.7% (1428.4/1887.5MB) ├███████████████████████████
75.7% (1428.6/1887.5MB) ├███████████████████████████
75.7% (1428.9/1887.5MB) ├███████████████████████████
75.7% (1429.1/1887.5MB) ├███████████████████████████
75.7% (1429.4/1887.5MB) ├███████████████████████████
75.7% (1429.6/1887.5MB) ├███████████████████████████
75.8% (1429.9/1887.5MB) ├███████████████████████████
75.8% (1430.1/1887.5MB) ├███████████████████████████
75.8% (1430.4/1887.5MB) ├███████████████████████████
75.8% (1430.6/1887.5MB) ├███████████████████████████
75.8% (1430.9/1887.5MB) ├███████████████████████████
75.8% (1431.1/1887.5MB) ├███████████████████████████
75.8% (1431.4/1887.5MB) ├███████████████████████████
75.8% (1431.6/1887.5MB) ├███████████████████████████
75.9% (1431.9/1887.5MB) ├███████████████████████████
75.9% (1432.1/1887.5MB) ├███████████████████████████
75.9% (1432.4/1887.5MB) ├███████████████████████████
75.9% (1432.6/1887.5MB) ├███████████████████████████
75.9% (1432.9/1887.5MB) ├███████████████████████████
75.9% (1433.1/1887.5MB) ├███████████████████████████
75.9% (1433.4/1887.5MB) ├███████████████████████████
76.0% (1433.6/1887.5MB) ├███████████████████████████
76.0% (1433.9/1887.5MB) ├███████████████████████████
76.0% (1434.1/1887.5MB) ├███████████████████████████
76.0% (1434.4/1887.5MB) ├███████████████████████████
76.0% (1434.6/1887.5MB) ├███████████████████████████
76.0% (1434.9/1887.5MB) ├███████████████████████████
76.0% (1435.1/1887.5MB) ├███████████████████████████
76.0% (1435.4/1887.5MB) ├███████████████████████████
76.1% (1435.6/1887.5MB) ├███████████████████████████
76.1% (1435.9/1887.5MB) ├███████████████████████████
76.1% (1436.1/1887.5MB) ├███████████████████████████
76.1% (1436.4/1887.5MB) ├███████████████████████████
76.1% (1436.6/1887.5MB) ├███████████████████████████
76.1% (1436.9/1887.5MB) ├███████████████████████████
76.1% (1437.1/1887.5MB) ├███████████████████████████
76.2% (1437.4/1887.5MB) ├███████████████████████████
76.2% (1437.6/1887.5MB) ├███████████████████████████
76.2% (1437.9/1887.5MB) ├███████████████████████████
76.2% (1438.1/1887.5MB) ├███████████████████████████
76.2% (1438.4/1887.5MB) ├███████████████████████████
76.2% (1438.6/1887.5MB) ├███████████████████████████
76.2% (1438.9/1887.5MB) ├███████████████████████████
76.2% (1439.1/1887.5MB) ├███████████████████████████
76.3% (1439.4/1887.5MB) ├███████████████████████████
76.3% (1439.6/1887.5MB) ├███████████████████████████
76.3% (1439.9/1887.5MB) ├███████████████████████████
76.3% (1440.1/1887.5MB) ├███████████████████████████
76.3% (1440.4/1887.5MB) ├███████████████████████████
76.3% (1440.6/1887.5MB) ├███████████████████████████
76.3% (1440.9/1887.5MB) ├███████████████████████████
76.4% (1441.1/1887.5MB) ├███████████████████████████
76.4% (1441.4/1887.5MB) ├███████████████████████████
76.4% (1441.6/1887.5MB) ├███████████████████████████
76.4% (1441.9/1887.5MB) ├███████████████████████████
76.4% (1442.1/1887.5MB) ├███████████████████████████
76.4% (1442.4/1887.5MB) ├███████████████████████████
76.4% (1442.6/1887.5MB) ├███████████████████████████
76.4% (1442.9/1887.5MB) ├███████████████████████████
76.5% (1443.1/1887.5MB) ├███████████████████████████
76.5% (1443.4/1887.5MB) ├███████████████████████████
76.5% (1443.6/1887.5MB) ├███████████████████████████
76.5% (1443.9/1887.5MB) ├███████████████████████████
76.5% (1444.1/1887.5MB) ├███████████████████████████
76.5% (1444.4/1887.5MB) ├███████████████████████████
76.5% (1444.6/1887.5MB) ├███████████████████████████
76.5% (1444.9/1887.5MB) ├███████████████████████████
76.6% (1445.1/1887.5MB) ├███████████████████████████
76.6% (1445.4/1887.5MB) ├███████████████████████████
76.6% (1445.6/1887.5MB) ├███████████████████████████
76.6% (1445.9/1887.5MB) ├███████████████████████████
76.6% (1446.1/1887.5MB) ├███████████████████████████
76.6% (1446.4/1887.5MB) ├███████████████████████████
76.6% (1446.6/1887.5MB) ├███████████████████████████
76.7% (1446.9/1887.5MB) ├███████████████████████████
76.7% (1447.1/1887.5MB) ├███████████████████████████
76.7% (1447.4/1887.5MB) ├███████████████████████████
76.7% (1447.6/1887.5MB) ├███████████████████████████
76.7% (1447.9/1887.5MB) ├███████████████████████████
76.7% (1448.1/1887.5MB) ├███████████████████████████
76.7% (1448.4/1887.5MB) ├███████████████████████████
76.7% (1448.6/1887.5MB) ├███████████████████████████
76.8% (1448.9/1887.5MB) ├███████████████████████████
76.8% (1449.1/1887.5MB) ├███████████████████████████
76.8% (1449.4/1887.5MB) ├███████████████████████████
76.8% (1449.6/1887.5MB) ├███████████████████████████
76.8% (1449.9/1887.5MB) ├███████████████████████████
76.8% (1450.1/1887.5MB) ├███████████████████████████
76.8% (1450.4/1887.5MB) ├███████████████████████████
76.9% (1450.6/1887.5MB) ├███████████████████████████
76.9% (1450.9/1887.5MB) ├███████████████████████████
76.9% (1451.1/1887.5MB) ├███████████████████████████
76.9% (1451.4/1887.5MB) ├███████████████████████████
76.9% (1451.6/1887.5MB) ├███████████████████████████
76.9% (1451.9/1887.5MB) ├███████████████████████████
76.9% (1452.1/1887.5MB) ├███████████████████████████
76.9% (1452.4/1887.5MB) ├███████████████████████████
77.0% (1452.6/1887.5MB) ├███████████████████████████
77.0% (1452.9/1887.5MB) ├███████████████████████████
77.0% (1453.1/1887.5MB) ├███████████████████████████
77.0% (1453.4/1887.5MB) ├███████████████████████████
77.0% (1453.6/1887.5MB) ├███████████████████████████
77.0% (1453.9/1887.5MB) ├███████████████████████████
77.0% (1454.1/1887.5MB) ├███████████████████████████
77.1% (1454.4/1887.5MB) ├███████████████████████████
77.1% (1454.6/1887.5MB) ├███████████████████████████
77.1% (1454.9/1887.5MB) ├███████████████████████████
77.1% (1455.1/1887.5MB) ├███████████████████████████
77.1% (1455.4/1887.5MB) ├███████████████████████████
77.1% (1455.6/1887.5MB) ├███████████████████████████
77.1% (1455.9/1887.5MB) ├███████████████████████████
77.1% (1456.1/1887.5MB) ├███████████████████████████
77.2% (1456.4/1887.5MB) ├███████████████████████████
77.2% (1456.6/1887.5MB) ├███████████████████████████
77.2% (1456.9/1887.5MB) ├███████████████████████████
77.2% (1457.1/1887.5MB) ├███████████████████████████
77.2% (1457.4/1887.5MB) ├███████████████████████████
77.2% (1457.6/1887.5MB) ├███████████████████████████
77.2% (1457.9/1887.5MB) ├███████████████████████████
77.3% (1458.1/1887.5MB) ├███████████████████████████
77.3% (1458.4/1887.5MB) ├███████████████████████████
77.3% (1458.6/1887.5MB) ├███████████████████████████
77.3% (1458.9/1887.5MB) ├███████████████████████████
77.3% (1459.1/1887.5MB) ├███████████████████████████
77.3% (1459.4/1887.5MB) ├███████████████████████████
77.3% (1459.6/1887.5MB) ├███████████████████████████
77.3% (1459.9/1887.5MB) ├███████████████████████████
77.4% (1460.1/1887.5MB) ├███████████████████████████
77.4% (1460.4/1887.5MB) ├███████████████████████████
77.4% (1460.6/1887.5MB) ├███████████████████████████
77.4% (1460.9/1887.5MB) ├███████████████████████████
77.4% (1461.1/1887.5MB) ├███████████████████████████
77.4% (1461.4/1887.5MB) ├███████████████████████████
77.4% (1461.6/1887.5MB) ├███████████████████████████
77.5% (1461.9/1887.5MB) ├███████████████████████████
77.5% (1462.1/1887.5MB) ├███████████████████████████
77.5% (1462.4/1887.5MB) ├███████████████████████████
77.5% (1462.6/1887.5MB) ├███████████████████████████
77.5% (1462.9/1887.5MB) ├███████████████████████████
77.5% (1463.1/1887.5MB) ├███████████████████████████
77.5% (1463.4/1887.5MB) ├███████████████████████████
77.5% (1463.6/1887.5MB) ├███████████████████████████
77.6% (1463.9/1887.5MB) ├███████████████████████████
77.6% (1464.1/1887.5MB) ├███████████████████████████
77.6% (1464.4/1887.5MB) ├███████████████████████████
77.6% (1464.6/1887.5MB) ├███████████████████████████
77.6% (1464.9/1887.5MB) ├███████████████████████████
77.6% (1465.1/1887.5MB) ├███████████████████████████
77.6% (1465.4/1887.5MB) ├███████████████████████████
77.6% (1465.6/1887.5MB) ├███████████████████████████
77.7% (1465.9/1887.5MB) ├███████████████████████████
77.7% (1466.1/1887.5MB) ├███████████████████████████
77.7% (1466.4/1887.5MB) ├███████████████████████████
77.7% (1466.6/1887.5MB) ├███████████████████████████
77.7% (1466.9/1887.5MB) ├███████████████████████████
77.7% (1467.1/1887.5MB) ├███████████████████████████
77.7% (1467.4/1887.5MB) ├███████████████████████████
77.8% (1467.6/1887.5MB) ├███████████████████████████
77.8% (1467.9/1887.5MB) ├███████████████████████████
77.8% (1468.1/1887.5MB) ├███████████████████████████
77.8% (1468.4/1887.5MB) ├███████████████████████████
77.8% (1468.6/1887.5MB) ├███████████████████████████
77.8% (1468.9/1887.5MB) ├███████████████████████████
77.8% (1469.0/1887.5MB) ├███████████████████████████
81.3% (1533.9/1887.5MB) ├███████████████████████████
84.4% (1593.2/1887.5MB) ├███████████████████████████
86.8% (1637.7/1887.5MB) ├███████████████████████████
90.0% (1699.5/1887.5MB) ├███████████████████████████
93.7% (1768.8/1887.5MB) ├███████████████████████████
96.3% (1818.2/1887.5MB) ├███████████████████████████
99.1% (1870.7/1887.5MB) ├███████████████████████████
 100% (1887.5/1887.5MB) ├███████████████████████████
██████████┤[32/32]  212 MB/s
Merging video parts... you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>

**Comment by rosynirvana** [comment]
把你用的ffmpeg换成stable release

https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-3.3.3-win64-static.zip
如果是32位系统
https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-3.3.3-win32-static.zip

**Comment by saku1119** [comment]
呃……那个下载挺慢 还没下完。
不过刚试着把不能播放的flv全删了，重下了一遍，再筛选，再重下，循环好几次，一直到没有不能播放的，然后终于合并成功了……不过这是为啥QWQ

**Comment by rosynirvana** [comment]
CDN存的文件不一样
或者给的http content-length错了，就可能出现重新下载.download文件突然被标记成完成
youku的CDN现在真是一团糟

**Comment by saku1119** [comment]
这个只能等youku自己修复是咩QWQ
说起来，youku现在的画质真是渣到不行……不如b站了……

**Comment by lki2019** [comment]
额，下的视频和那会的是一样子的

**Comment by rosynirvana** [comment]
从5月底优酷就有些片段下载下来是损毁的了
一个电视剧第一集能下，第39集能下，只有35集中间有一个短片怎么下都是损坏的
过一天后自己恢复了……
