### ISSUE TITLE
B站会员下载

### ISSUE THREAD

**Issue by saku1119** [soimort/you-get#2255]
汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>you-get -i https://bangumi.bilibili.com/anime/6023/play#1
13952
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>you-get -i -c cookies.txt https://bangumi.bilibili.com/an
ime/6023/play#113952
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>you-get -i -c cookies.txt https://bangumi.bilibili.com/an
ime/6023/play#113952
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>you-get -i -c cookies.txt https://bangumi.bilibili.com/an
ime/5720/play#99083
site:                Bilibili
title:               霹雳天启 [2 恩仇结]
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        flv
      container:     flv
      size:          783.5 MiB (821523061 bytes)
    # download-with: you-get --format=flv [URL]

    - format:        hdmp4
      container:     mp4
      size:          633.7 MiB (664432137 bytes)
    # download-with: you-get --format=hdmp4 [URL]

    - format:        mp4
      container:     mp4
      size:          288.3 MiB (302330903 bytes)
    # download-with: you-get --format=mp4 [URL]


C:\Users\Administrator>you-get -i -c cookies.txt https://bangumi.bilibili.com/an
ime/6023/play#113952
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>you-get -i -c cookies.txt https://bangumi.bilibili.com/an
ime/6023/play#113952
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [我又来了QWQ 早上试了一下b站的会员下载 不知道为何不好用……是挂载了cookies的，中途试了一下不需要会员的，运行正常……好像就那个会员的不好下了QWQ]
> [舔 :icecream:!]

**Comment by saku1119** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>you-get --debug -c cookies.txt -i https://bangumi.bilibil
i.com/anime/6023/play#113952
[DEBUG] url_locations: https://bangumi.bilibili.com/anime/6023/play#113952
[DEBUG] get_content: https://bangumi.bilibili.com/anime/6023/play#113952
[DEBUG] get_content: http://bangumi.bilibili.com/jsonp/seasoninfo/6023.ver?callb
ack=seasonListCallback&jsonp=jsonp&_=1502495371985
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://bangumi.bilibili.com/anime/6023/play#113952']
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts
\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1352, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1259, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1057, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1345, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\bilibili.py", line 128, in prepare
    self.bangumi_entry(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\bilibili.py", line 212, in bangumi_entry
    ep_ids = collect_bangumi_epids(bangumi_data)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\bilibili.py", line 269, in collect_bangumi_epids
    eps = sorted(eps, key=lambda item: float(item['index'].split('-')[0].split('
+')[0]))
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\bilibili.py", line 269, in <lambda>
    eps = sorted(eps, key=lambda item: float(item['index'].split('-')[0].split('
+')[0]))
ValueError: could not convert string to float: '第四十章(国语)'

C:\Users\Administrator>you-get --debug -c cookies.txt -i https://bangumi.bilibil
i.com/anime/6023/play#113954
[DEBUG] url_locations: https://bangumi.bilibili.com/anime/6023/play#113954
[DEBUG] get_content: https://bangumi.bilibili.com/anime/6023/play#113954
[DEBUG] get_content: http://bangumi.bilibili.com/jsonp/seasoninfo/6023.ver?callb
ack=seasonListCallback&jsonp=jsonp&_=1502495418424
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://bangumi.bilibili.com/anime/6023/play#113954']
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts
\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1352, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1259, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1057, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1345, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\bilibili.py", line 128, in prepare
    self.bangumi_entry(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\bilibili.py", line 212, in bangumi_entry
    ep_ids = collect_bangumi_epids(bangumi_data)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\bilibili.py", line 269, in collect_bangumi_epids
    eps = sorted(eps, key=lambda item: float(item['index'].split('-')[0].split('
+')[0]))
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\bilibili.py", line 269, in <lambda>
    eps = sorted(eps, key=lambda item: float(item['index'].split('-')[0].split('
+')[0]))
ValueError: could not convert string to float: '第四十章(国语)'

C:\Users\Administrator>




QWQ 我是直接用的地址栏的地址 第一次用的37集的 第二次用的38集的 不知道为何出来的都是40………………

**Comment by lki2019** [comment]
你是会员账号么？好像你用会员账号登陆看这个才可以吧

**Comment by saku1119** [comment]
是会员，看的话没问题，已挂载了cookies

**Comment by lki2019** [comment]
本番需付费(300B币)观看
每周更新两集，所有用户均需付费观看本剧

他这个是不是你开了B站会员也是要扣掉300B 才可以看的吧

还有昨天那个优酷的，需要开通频道VIP才可以看的吧？就算你开了优酷黄金账号也看不了

**Comment by saku1119** [comment]
昨天那个优酷的我也是会员，b站的这个也是……而且在线看的时候都没问题
昨天优酷那个我下下来了，只不过中间会总断，最后是手动删选掉错误的片段重复下载才得到完整的。
今天B站这个……怎么也下不来了……会员绝对没问题，因为我这边在线看1080P无障碍 只是用you-get下载有问题

**Comment by saku1119** [comment]
我开的是频道会员，两个网站的视频都是在线看没问题的，如果不是频道会员，在线看也是看不了的。

**Comment by rosynirvana** [comment]
和会员没关系，只是现在用的代码无法确定这是哪一集，所以挂掉了……

**Comment by saku1119** [comment]
呃……有解决办法咩QWQ ……

**Comment by rosynirvana** [comment]
现在应该好了

**Comment by lki2019** [comment]
我在想：别人导出来的cookies.txt 我是不是也可以用？

**Comment by rosynirvana** [comment]
可以用

**Comment by saku1119** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>you-get -c cookies.txt -i https://bangumi.bilibili.com/an
ime/6023/play#113952
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>you-get -d -c cookies.txt -i https://bangumi.bilibili.com
/anime/6023/play#113952
[DEBUG] url_locations: https://bangumi.bilibili.com/anime/6023/play#113952
[DEBUG] get_content: https://bangumi.bilibili.com/anime/6023/play#113952
[DEBUG] get_content: http://bangumi.bilibili.com/jsonp/seasoninfo/6023.ver?callb
ack=seasonListCallback&jsonp=jsonp&_=1502509319200
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['https://bangumi.bilibili.com/anime/6023/play#113952']
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts
\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1352, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1259, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1057, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1345, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\bilibili.py", line 128, in prepare
    self.bangumi_entry(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\bilibili.py", line 212, in bangumi_entry
    ep_ids = collect_bangumi_epids(bangumi_data)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\bilibili.py", line 269, in collect_bangumi_epids
    eps = sorted(eps, key=lambda item: float(item['index'].split('-')[0].split('
+')[0]))
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\bilibili.py", line 269, in <lambda>
    eps = sorted(eps, key=lambda item: float(item['index'].split('-')[0].split('
+')[0]))
ValueError: could not convert string to float: '第四十章(国语)'

C:\Users\Administrator>


还是不好用QWQ 我需要更新一下咩~

**Comment by lki2019** [comment]
pip3 install --upgrade https://github.com/soimort/you-get/archive/develop.zip

**Comment by rosynirvana** [comment]
要更新，不然还是原来的代码

**Comment by lki2019** [comment]
@saku1119  能否把你导出的cookies.txt传到网盘 我下载试验一下 在我电脑上看能用么？
只为测试，完了等会你删除就好

**Comment by saku1119** [comment]
好用了~！谢谢大神~！
to lki2019 
能用的 我的这个就是借的一个朋友的， 因为是别人的不太方便给你，不好意思哈QWQ请见谅……
