### ISSUE TITLE
网校的课程一个比一个难搞啊

### ISSUE THREAD

**Issue by lki2019** [soimort/you-get#2257]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

http://www.51zxw.net/list.aspx?cid=554  我要自学网的  公开课

http://www.51zxw.net/show.aspx?id=49965&cid=554

看了半天，没有头绪，都不知道是什么流·

受打击了，不懂编程就是不行啊
我已经到了瓶颈了，
```

**Comment by Soilvue** [comment]
我也遇到了同样的问题，网址:
http://www.shenlanxueyuan.com/course/34/activity/59/replay/21/entry

**Comment by lki2019** [comment]
@Soilvue 你这个地址应该是收费课程吧

我专门注册了下，看了看免费公开课

比如 http://www.shenlanxueyuan.com/course/49/activity/120/replay/20/entry

是不好下载，HLS流，m3u8文件加密了，下载下载后是乱码

<pre><code>http://124.165.206.104/260/4/69/bcloud/645568/ver_00_22-1111486326-avc-193237-aac-48000-7098134-225886136-4116760d29800fc230b233fdcd131e33-1501338542316.m3u8?crypt=34aa7f2e236&b=254&nlh=4096&nlt=60&bf=75&p2p=1&video_type=mp4&termid=1&tss=ios&platid=2&splatid=207&its=0&qos=5&fcheck=0&amltag=59889&mltag=59889&proxy=2091241062,2007470935,467476918&uid=974274796.rp&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&ntm=1502607000&nkey=51a8f0ad83872657ee73216e82bc476f&nkey2=f40c6ce33d7a45c0c75ba0730beacda5&auth_key=1502607000-1-0-2-207-0fc688304cb2beff441c55ff24ce91e9&geo=CN-5-61-2&mmsid=241611948&tm=1502588569&key=653a00cb62d71691763e655934b007e6&payff=0&cuid=645568&vtype=21&dur=7098&p1=3&p2=30&p3=300&cf=flash&p=101&playid=0&tag=flash&sign=bcloud_645568&pay=0&ostype=windows&hwtype=un&ctv=pc&m3v=1&ch=645568&tn=0.015932604670524597&uuid=B8BCF4AC0525F77E8C2A73576248E75AA42B57FF&vid=46728988&rateid=1&uidx=0&errc=0&gn=1169&ndtype=0&vrtmcd=108&buss=59889&cips=58.18.64.236&r=1502588522745&appid=500<pre><code>

TS分段下载下载倒是直接看，

**Comment by rosynirvana** [comment]
这不乐视云吗……

**Comment by lki2019** [comment]
感谢大神指点，
![qq 20170813112137](https://user-images.githubusercontent.com/30022431/29245862-c0ba9c7e-8019-11e7-96ab-6f8acf052bdc.png)

**Comment by Soilvue** [comment]
是收费课程，已经购买过了的。 在2017年08月13日 09:46 ，lki2019写道： @Soilvue 你这个地址应该是收费课程吧 我专门注册了下，看了看免费公开课 比如 http://www.shenlanxueyuan.com/course/49/activity/120/replay/20/entry 是不好下载，HLS流，m3u8文件加密了，下载下载后是乱码 http://124.165.206.104/260/4/69/bcloud/645568/ver_00_22-1111486326-avc-193237-aac-48000-7098134-225886136-4116760d29800fc230b233fdcd131e33-1501338542316.m3u8?crypt=34aa7f2e236&b=254&nlh=4096&nlt=60&bf=75&p2p=1&video_type=mp4&termid=1&tss=ios&platid=2&splatid=207&its=0&qos=5&fcheck=0&amltag=59889&mltag=59889&proxy=2091241062,2007470935,467476918&uid=974274796.rp&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&ntm=1502607000&nkey=51a8f0ad83872657ee73216e82bc476f&nkey2=f40c6ce33d7a45c0c75ba0730beacda5&auth_key=1502607000-1-0-2-207-0fc688304cb2beff441c55ff24ce91e9&geo=CN-5-61-2&mmsid=241611948&tm=1502588569&key=653a00cb62d71691763e655934b007e6&payff=0&cuid=645568&vtype=21&dur=7098&p1=3&p2=30&p3=300&cf=flash&p=101&playid=0&tag=flash&sign=bcloud_645568&pay=0&ostype=windows&hwtype=un&ctv=pc&m3v=1&ch=645568&tn=0.015932604670524597&uuid=B8BCF4AC0525F77E8C2A73576248E75AA42B57FF&vid=46728988&rateid=1&uidx=0&errc=0&gn=1169&ndtype=0&vrtmcd=108&buss=59889&cips=58.18.64.236&r=1502588522745&appid=500 

TS分段下载下载倒是直接看，

**Comment by Soilvue** [comment]
@lki2019 @rosynirvana 十分感谢两位的帮忙，但是不是很懂具体怎么操作，刚接触you-get，只知道用“you-get -c cookie 网址”来下载视频……两位能再说具体点吗？万分感谢！

**Comment by lki2019** [comment]
you-get -c cookie 网址
好像只能下载you-get支持的网站里的吧？

你这个网址深蓝学院不在youget支持的列表里，所以you-get -c cookie 好像无法下载

我是这么理解的，
---------至于用you-get之外的怎么下载，首先你得抓你这个课程的m3u8的地址，你抓到了在用上面大神的方法解密 就行了
如果你第一步抓m3u8地址都没解决，可能我也就不好说什么了，这个得你自己研究了
大致就这么个流程，我们也不能说太细，一步步都列出来，

**Comment by zhuoquanzhou** [comment]
@lki2019 请问具体如何解密m3u8，用了大神的代码之后输出结果没有变化（解密时将m3u8地址放入txt文本中并在open函数中打开）。查了le.py文件中的decode函数，发现需要“version.lower() == b'vc_01'”才能进行解密，是需要对m3u8地址进行处理吗？

抓取的m3u8地址如下：
                        
    http://124.192.145.238/260/4/69/bcloud/645568/ver_00_22-1111486326-avc-193237-aac-48000-7098134-225886136-4116760d29800fc230b233fdcd131e33-1501338542316.m3u8?crypt=34aa7f2e285&b=254&nlh=4096&nlt=60&bf=90&p2p=1&video_type=mp4&termid=2&tss=ios&platid=2&splatid=209&its=0&qos=5&fcheck=0&amltag=59889&mltag=59889&path=123.59.122.169&proxy=611246661,2071799758,467476918&uid=1020259695.rp&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&ntm=1502647200&nkey=695602bfb9309c39a041714013b7beda&nkey2=332153ffc89c846bb3be1119bd990735&auth_key=1502647200-1-0-2-209-f7ce527e00db0b8ab194bbabe6f7a943&geo=CN-1-12-16&mmsid=241611948&tm=1502628762&key=0623783d92d8834934d90319573059b4&payff=0&cuid=645568&vtype=21&dur=7098&p1=3&p2=31&p3=311&cf=h5-ios&p=101&playid=0&tag=mobile&sign=bcloud_645568&pay=0&ostype=ios&hwtype=un&uuid=63196DD012319EA5648903E15A43756D_0&vid=46728988&ajax=1&_r=jsonp&uidx=0&errc=0&gn=149&ndtype=0&vrtmcd=107&buss=59889&cips=60.207.237.111

**Comment by Soilvue** [comment]
感谢大神指点 : )
