### ISSUE TITLE
rc4解密中的密钥问题

### ISSUE THREAD

**Issue by mhearttzw** [soimort/you-get#2258]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

### 在源码的AcFun部分当视频源为主站的解析代码时，有用到rc4解密算法，其中秘钥设为b'8bdc7e1a'，请问这是如何得来的？
**这是代码位置链接：**
[https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/acfun.py#L27](https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/acfun.py#L27)
**这是所述代码部分:**

```
def youku_acfun_proxy(vid, sign, ref):
    endpoint = 'http://player.acfun.cn/flash_data?vid={}&ct=85&ev=3&sign={}&time={}'
    url = endpoint.format(vid, sign, str(int(time.time() * 1000)))
    json_data = json.loads(get_content(url, headers=dict(referer=ref)))['data']
    enc_text = base64.b64decode(json_data)
    **dec_text = rc4(b'8bdc7e1a', enc_text).decode('utf8')**
    youku_json = json.loads(dec_text)
```

**Comment by mhearttzw** [comment]
@soimort-bot 
Could you help me solve this problem? I am so eager to know the answer!

**Comment by rosynirvana** [comment]
播放器里

**Comment by airdge** [comment]
反编译swf就能找到
```
      public static const SPECIAL_TYPE_KEY_ACFUN:String = "8bdc7e1a";
      
      public static const CTYPE:int = 85;
      
      public static const EV:int = 3;
```
函数
```
      protected function decrypt(param1:String) : String
      {
         var _loc2_:ByteArray = Base64.decodeToByteArray(param1);
         var _loc3_:* = PlayerConstant.SPECIAL_TYPE_KEY_ACFUN + "3c" + "a9e";
         var _loc4_:ByteArray = Hex.toArray(Hex.fromString(_loc3_.substr(0,8)));
         var _loc5_:EncryptRC4 = new EncryptRC4(_loc4_);
         _loc5_.encrypt(_loc2_);
         return Hex.toString(Hex.fromArray(_loc2_));
      }
```

**Comment by mhearttzw** [comment]
谢谢大家！
