### ISSUE TITLE
优酷涉及国语和粤语两个版本的电视剧，解析下载好像有问题

### ISSUE THREAD

**Issue by lki2019** [soimort/you-get#2261]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.

<pre><code>Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>you-get -di http://v.youku.com/v_show/id_XNDkwMjM4MzI4.ht
ml?spm=a2h0k.8191407.0.0&lang=%E5%9B%BD%E8%AF%AD&from=s1.8-1-1.1
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XNDkwMjM4MzI4&ccode=
0401&client_ip=192.168.1.1&utid=f7oWEvjcJl8CAToSQOwlJJuQ&client_ts=1502596174
you-get: hd2 is a preview
you-get: flvhd is a preview
you-get: mp4 is a preview
site:                优酷 (Youku)
title:               法网狙击 01
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          373.0 MiB (391139250 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XNDkwMjM4MzI4&typ
e=hd2&ups_client_netip=1.180.132.36&ups_ts=1502596224&utid=f7oWEvjcJl8CAToSQOwlJ
JuQ&ccode=0401&psid=75388c5faa771e5cbb4548087be4121c&duration=2600&expire=18000&
ups_key=77671a8a8fe233e4d89396d82733b4a0
    # download-with: you-get --format=hd2 [URL]

    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          170.8 MiB (179063259 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XNDkwMjM4MzI4&typ
e=mp4&ups_client_netip=1.180.132.36&ups_ts=1502596224&utid=f7oWEvjcJl8CAToSQOwlJ
JuQ&ccode=0401&psid=75388c5faa771e5cbb4548087be4121c&duration=2600&expire=18000&
ups_key=77671a8a8fe233e4d89396d82733b4a0
    # download-with: you-get --format=mp4 [URL]

    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          89.0 MiB (93346010 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XNDkwMjM4MzI4&typ
e=flv&ups_client_netip=1.180.132.36&ups_ts=1502596224&utid=f7oWEvjcJl8CAToSQOwlJ
JuQ&ccode=0401&psid=75388c5faa771e5cbb4548087be4121c&duration=2600&expire=18000&
ups_key=77671a8a8fe233e4d89396d82733b4a0
    # download-with: you-get --format=flvhd [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XNDkwMjM4MzI4

    - lang:          粤语
      download-url:  http://v.youku.com/v_show/id_XNDkwMjQxODAw

'lang' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'from' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Administrator>you-get -d http://v.youku.com/v_show/id_XNDkwMjM4MzI4.htm
l?spm=a2h0k.8191407.0.0&lang=%E5%9B%BD%E8%AF%AD&from=s1.8-1-1.1
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XNDkwMjM4MzI4&ccode=
0401&client_ip=192.168.1.1&utid=mboWEkxE0D4CAToSQOyge4m1&client_ts=1502596200
you-get: hd2 is a preview
you-get: flvhd is a preview
you-get: mp4 is a preview
site:                优酷 (Youku)
title:               法网狙击 01
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          373.0 MiB (391139250 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XNDkwMjM4MzI4&typ
e=hd2&ups_client_netip=1.180.132.36&ups_ts=1502596250&utid=mboWEkxE0D4CAToSQOyge
4m1&ccode=0401&psid=69dc8474bb343f58204e7aa3b248bb4b&duration=2600&expire=18000&
ups_key=6f1c7f9704e4461a1f1627b15e00c0b4
    # download-with: you-get --format=hd2 [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XNDkwMjM4MzI4

    - lang:          粤语
      download-url:  http://v.youku.com/v_show/id_XNDkwMjQxODAw

you-get: [Failed] Cannot extract video source.
'lang' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'from' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Administrator>you-get -d http://v.youku.com/v_show/id_XNDkwMjM4MzI4
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XNDkwMjM4MzI4&ccode=
0401&client_ip=192.168.1.1&utid=qLoWEmlpdF0CAToSQOxHyUCT&client_ts=1502596215
you-get: hd2 is a preview
you-get: flvhd is a preview
you-get: mp4 is a preview
site:                优酷 (Youku)
title:               法网狙击 01
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          373.0 MiB (391139250 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XNDkwMjM4MzI4&typ
e=hd2&ups_client_netip=1.180.132.36&ups_ts=1502596265&utid=qLoWEmlpdF0CAToSQOxHy
UCT&ccode=0401&psid=023b29eb7930959c4dbc96c638f0ddbb&duration=2600&expire=18000&
ups_key=2125a18d6731840fba50d2f2679dba5f
    # download-with: you-get --format=hd2 [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XNDkwMjM4MzI4

    - lang:          粤语
      download-url:  http://v.youku.com/v_show/id_XNDkwMjQxODAw

you-get: [Failed] Cannot extract video source.<pre><code>

我用ykdl正常下载但是，下载下来后音轨还是粤语的
可能这电视剧没国语音轨？反正在线看是有国语的

**Comment by rosynirvana** [comment]
dup #1249

**Comment by lki2019** [comment]
C:\Users\Administrator>youtube-dl http://v.youku.com/v_show/id_XNDkwMjM4MzI4.htm
l?spm=a2h0k.8191407.0.0&lang=%E5%9B%BD%E8%AF%AD&from=s1.8-1-1.1
[youku] XNDkwMjM4MzI4: Retrieving cna info
[youku] XNDkwMjM4MzI4: Downloading JSON metadata
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 257
[download] Destination: 法网狙击 01-XNDkwMjM4MzI4.mp4
[download] 100% of 386.86MiB in 02:51
[ffmpeg] Fixing malformed AAC bitstream in "法网狙击 01-XNDkwMjM4MzI4.mp4"



youtube下载下来的有国语音轨

不是我要看的，是一个群里说you-get下载下来没国语音轨·
无所谓的，我只是帮别人提一下，改动大直接忽略就好，反正我也不看这些·

**Comment by rosynirvana** [comment]
这个问题是已知的所以直接关了

不是没国语音轨，是国语和粤语在优酷那里其实是两套视频
```
audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XNDkwMjM4MzI4

    - lang:          粤语
      download-url:  http://v.youku.com/v_show/id_XNDkwMjQxODAw
```

国语和粤语实际的url是不一样的，如果要国语
```
./you-get -di http://v.youku.com/v_show/id_XNDkwMjM4MzI4
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XNDkwMjM4MzI4&ccode=0401&client_ip=192.168.1.1&utid=NcQWEs7Y8zACAX0tsqEivTZl&client_ts=1502598708
you-get: hd2 is a preview
you-get: flvhd is a preview
you-get: mp4 is a preview
site:                优酷 (Youku)
title:               法网狙击 01
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          373.0 MiB (391139250 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XNDkwMjM4MzI4&type=hd2&ups_client_netip=125.45.178.161&ups_ts=1502598709&utid=NcQWEs7Y8zACAX0tsqEivTZl&ccode=0401&psid=c1cda4bab280bf6e22b3088f0ab22d50&duration=2600&expire=18000&ups_key=07cd5ff2e396bd80b2ef0e6ba01e3ae9
    # download-with: you-get --format=hd2 [URL]
```

这个m3u8_url直接拿去下或者播放就行了

**Comment by lki2019** [comment]
其实我最上面贴出来了you-get -d http://v.youku.com/v_show/id_XNDkwMjM4MzI4

无法下载的，

国语的我按照你说的复制m3u8地址去下载 是无法下载的
所以我感觉是解析脚本问题，你可以试下

**Comment by rosynirvana** [comment]
当然不能直接下，因为没人去写

m3u8当然是试过的
有人碰上CDN失效时间问题，那也没办法

**Comment by lki2019** [comment]
我可能没描述完整
我没有复制大神贴出来的m3u8地址，因为知道可能有时效性问题

所以我是自己又you-get -di http://v.youku.com/v_show/id_XNDkwMjM4MzI4

解析出来的地址

3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XNDkwMjM4MzI4&type=hd2&ups_client_netip=58.18.64.236&ups_ts=1502600337&utid=kMoWEuACIh4CAToSQOwjDjQC&ccode=0401&psid=223a059cf4c03d86b87ab54fde475530&duration=2600&expire=18000&ups_key=144be9ecef291e54db09da6b28f1ef0e

然后放到下载器里下载

urrent: 3960; changing to 4040. This may result in incorrect timestamps in the o
utput file.
[matroska @ 03f406e0] Non-monotonous DTS in output stream 0:0; previous: 4040, c
urrent: 4000; changing to 4040. This may result in incorrect timestamps in the o
utput file.
frame=  203 fps= 42 q=-1.0 size=    1343kB time=00:00:04.04 bitrate=2722.7kbits/
[matroska @ 03f406e0] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
frame=  203 fps= 42 q=-1.0 Lsize=    2641kB time=00:00:04.08 bitrate=5294.6kbits
/s speed=0.845x
video:2557kB audio:84kB subtitle:0kB other streams:0kB global headers:0kB muxing
 overhead: unknown
Conversion failed!

所有任务完成！

请按任意键继续. . .

很明显时长不对

所以我才说也是无法下载的··

**Comment by rosynirvana** [comment]
真的建议你多学点东西，学着看懂log，就不会反复说一个问题了，比如这是从m3u8里找出来的一个分片

```
curl -I http://vali.cp31.ott.cibntv.net/677AE71479C317131B4882EC1/030001070650D0D48AEDE704CB019FE60B6DC8-EE1E-4C04-495F-B23F1548B41A.flv.ts\?ccode\=0401\&duration\=2600\&expire\=18000\&psid\=1f565c5ba2c3285c188832b4f98607aa\&ups_client_netip\=_\&ups_ts\=1502602214\&ups_userid\=\&utid\=5tEWEiJBQy8CAX0tsqGZruGk\&vid\=XNDkwMjM4MzI4\&vkey\=Af631abc31d9708ec8d5863c8d6500a94\&ts_start\=287.02\&ts_end\=298.5\&ts_seg_no\=256\&ts_keyframe\=1
HTTP/1.1 200 OK
Server: Tengine
Content-Type: video/x-flv
Content-Length: 1540472
Connection: keep-alive
Date: Mon, 03 Jul 2017 02:45:38 GMT
Last-Modified: Tue, 18 Dec 2012 20:39:45 GMT
ETag: "1702061294"
Via: u14.squid.nanning.yoqoo[0,200-0,H], u14.squid.nanning.yoqoo[16,200613], cache26.l2nu16[0,206-0,H], cache7.l2nu16[0,0], vcache3.cn635[0,206-0,H], vcache5.cn635[1,0]
Age: 3552969
X-Cache: HIT TCP_MEM_HIT dirn:8:380353816
X-Swift-SaveTime: Thu, 06 Jul 2017 14:46:50 GMT
X-Swift-CacheTime: 8640000
Timing-Allow-Origin: *
EagleId: 7b0608cd15026029078061335e
```

```
curl -I http://vali.cp31.ott.cibntv.net/677AE71479C317131B4882EC1/030001070650D0D48AEDE704CB019FE60B6DC8-EE1E-4C04-495F-B23F1548B41A.flv.ts\?ccode\=0401\&duration\=2600\&expire\=18000\&psid\=1f565c5ba2c3285c188832b4f98607aa\&ups_client_netip\=_\&ups_ts\=1502602214\&ups_userid\=\&utid\=5tEWEiJBQy8CAX0tsqGZruGk\&vid\=XNDkwMjM4MzI4\&vkey\=Af631abc31d9708ec8d5863c8d6500a94\&ts_start\=287.02\&ts_end\=298.5\&ts_seg_no\=256\&ts_keyframe\=1
HTTP/1.1 200 OK
Server: Tengine
Content-Type: video/x-flv
Content-Length: 1540472
Connection: keep-alive
Date: Tue, 25 Jul 2017 09:23:13 GMT
Last-Modified: Tue, 18 Dec 2012 20:39:47 GMT
ETag: "1761634237"
Via: q01.squid.jilin.yoqoo[0,200-0,H], q01.squid.jilin.yoqoo[27,200613], cache26.l2nu16[0,206-0,H], cache64.l2nu16[1,0], vcache6.cn666[0,206-0,H], vcache4.cn666[1,0]
Age: 1628340
X-Cache: HIT TCP_MEM_HIT dirn:9:78336359
X-Swift-SaveTime: Fri, 28 Jul 2017 10:41:00 GMT
X-Swift-CacheTime: 8640000
Timing-Allow-Origin: *
EagleId: 7b060ad515026029333915563e
```

```
curl -I http://vali.cp31.ott.cibntv.net/677AE71479C317131B4882EC1/030001070650D0D48AEDE704CB019FE60B6DC8-EE1E-4C04-495F-B23F1548B41A.flv.ts\?ccode\=0401\&duration\=2600\&expire\=18000\&psid\=1f565c5ba2c3285c188832b4f98607aa\&ups_client_netip\=_\&ups_ts\=1502602214\&ups_userid\=\&utid\=5tEWEiJBQy8CAX0tsqGZruGk\&vid\=XNDkwMjM4MzI4\&vkey\=Af631abc31d9708ec8d5863c8d6500a94\&ts_start\=287.02\&ts_end\=298.5\&ts_seg_no\=256\&ts_keyframe\=1
HTTP/1.1 403 Forbidden
Server: Tengine
Date: Sun, 13 Aug 2017 05:42:18 GMT
Content-Type: text/html
Content-Length: 161
Connection: keep-alive
Via: vcache4.cn666[,403201]
Timing-Allow-Origin: *
EagleId: 7b060ad515026029387616563e
```

```
curl -I http://vali.cp31.ott.cibntv.net/677AE71479C317131B4882EC1/030001070650D0D48AEDE704CB019FE60B6DC8-EE1E-4C04-495F-B23F1548B41A.flv.ts\?ccode\=0401\&duration\=2600\&expire\=18000\&psid\=1f565c5ba2c3285c188832b4f98607aa\&ups_client_netip\=_\&ups_ts\=1502602214\&ups_userid\=\&utid\=5tEWEiJBQy8CAX0tsqGZruGk\&vid\=XNDkwMjM4MzI4\&vkey\=Af631abc31d9708ec8d5863c8d6500a94\&ts_start\=287.02\&ts_end\=298.5\&ts_seg_no\=256\&ts_keyframe\=1
HTTP/1.1 403 Forbidden
Server: Tengine
Date: Sun, 13 Aug 2017 05:42:31 GMT
Content-Type: text/html
Content-Length: 161
Connection: keep-alive
Via: vcache1.cn696[,403201]
Timing-Allow-Origin: *
EagleId: 3d9e909515026029519125506e
```

```
D48AEDE704CB019FE60B6DC8-EE1E-4C04-495F-B23F1548B41A.flv.ts\?ccode\=0401\&duration\=2600\&expire\=18000\&psid\=1f565c5ba2c3285c188832b4f98607aa\&ups_client_netip\=_\&ups_ts\=1502602214\&ups_userid\=\&utid\=5tEWEiJBQy8CAX0tsqGZruGk\&vid\=XNDkwMjM4MzI4\&vkey\=Af631abc31d9708ec8d5863c8d6500a94\&ts_start\=287.02\&ts_end\=298.5\&ts_seg_no\=256\&ts_keyframe\=1
HTTP/1.1 200 OK
Server: Tengine
Content-Type: video/x-flv
Content-Length: 1540472
Connection: keep-alive
Date: Mon, 07 Aug 2017 04:49:10 GMT
Last-Modified: Tue, 18 Dec 2012 20:39:47 GMT
ETag: "1761634237"
Via: q01.squid.jilin.yoqoo[0,200-0,H], q01.squid.jilin.yoqoo[39,200613], cache26.l2nu16[0,206-0,H], cache56.l2nu16[1,0], vcache1.cn696[0,206-0,H], vcache5.cn696[0,0]
Age: 521617
X-Cache: HIT TCP_MEM_HIT dirn:-2:-2
X-Swift-SaveTime: Sun, 13 Aug 2017 05:37:42 GMT
X-Swift-CacheTime: 8640000
Timing-Allow-Origin: *
EagleId: 3d9e909915026029676975097e
```

这是连续的五次请求，顺序没有调整过
这就是我一直说的CDN问题
如果不关心就罢了
