### ISSUE TITLE
rc4解密中的密钥问题

### ISSUE THREAD

**Issue by mhearttzw** [soimort/you-get#2263]
Please make sure these boxes are checked before submitting your issue – thank you!

- [] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

### 抱歉我又重开了这个问题，这是之前的关闭的问题地址：
**[https://github.com/soimort/you-get/issues/2258](https://github.com/soimort/you-get/issues/2258)**
### 在源码的AcFun部分当视频源为主站的解析代码时，有用到rc4解密算法，其中秘钥设为b'8bdc7e1a'，请问这是如何得来的？

**这是代码位置链接：**
https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/acfun.py#L27
**这是所述代码部分:**

```
def youku_acfun_proxy(vid, sign, ref):
    endpoint = 'http://player.acfun.cn/flash_data?vid={}&ct=85&ev=3&sign={}&time={}'
    url = endpoint.format(vid, sign, str(int(time.time() * 1000)))
    json_data = json.loads(get_content(url, headers=dict(referer=ref)))['data']
    enc_text = base64.b64decode(json_data)
    **dec_text = rc4(b'8bdc7e1a', enc_text).decode('utf8')**
    youku_json = json.loads(dec_text)
```

### 我现在仍存的疑问是：
**如果要反编译swf文件，那么具体是哪个swf文件？ 从哪里获取？**

**Comment by rosynirvana** [comment]
BinaryData

**Comment by mhearttzw** [comment]
啊，BinaryData是什么意思，具体是从哪个地址获取得到这个swf呢？我不是太清楚这个获取地址。

**Comment by mhearttzw** [comment]
@airdge

**Comment by rosynirvana** [comment]
不知道关键部分在哪里，一般是抓所有swf来看，然后按文件体积一个个看；或者按加载顺序去读
另外flash可以从DefineBinaryData Tag里读swf

**Comment by airdge** [comment]
上面讲的很明白了 
比如用FFDec反编译
从进程(内存)里面搜索已加载的swf   
读取swf  
文本查找关键字段
