### ISSUE TITLE
youtube下载突然不行

### ISSUE THREAD

**Issue by jianxiyan2017** [soimort/you-get#2267]
youtube-dl --proxy 127.0.0.1:8118 -f 136+139 -o  /mnt/dl/video/aada598a6ab46ca1463dab74fb614ae7.mp4  https://www.youtube.com/watch?v=mGR3FixGDZ4

 报下面的错误，造成下载中断

[download]  89.5% of 19.35MiB at 15.92KiB/s ETA 02:11ERROR: content too short (expected 20291292 bytes and served 18153344)

**Comment by rosynirvana** [comment]
这是youtube-dl的问题

**Comment by jianxiyan2017** [comment]
好的，谢谢
