### ISSUE TITLE
Youku download failed (HTTP 502, manually restart required) and file output is shorten

### ISSUE THREAD

**Issue by scegg** [soimort/you-get#2277]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get http://v.youku.com/v_show/id_XMjk3Mjc0NjEzNg==.html?spm=a2hzp.8253869.0.0 -d
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk3Mjc0NjEzNg==&ccode=0401&client_ip=192.168.1.1&utid=SboaEhyp6w4CAXQZ8wuPdUmK&client_ts=1502858303
site:                优酷 (Youku)
title:               因为热 我们一错三千年 170816
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          258.6 MiB (271114274 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjk3Mjc0NjEzNg%3D%3D&type=hd3&ups_client_netip=116.25.243.11&ups_ts=1502858314&utid=SboaEhyp6w4CAXQZ8wuPdUmK&ccode=0401&psid=73cae930d65fcf9b460c199ba2f64501&duration=1544&expire=18000&ups_key=6564338385d74345716f5be28748db0f
    # download-with: you-get --format=hd3 [URL]

Downloading 因为热 我们一错三千年 170816.flv ...
18.6% ( 48.1/258.6MB) ├████████───────────────────────────────┤[ 2/11]   10 MB/s[DEBUG] HTTP Error with code502
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMjk3Mjc0NjEzNg==.html?spm=a2hzp.8253869.0.0']
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1355, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1262, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1060, in download_main
    download(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 1348, in any_download
    m.download(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\extractors\youku.py", line 263, in youku_download_by_url
    Youku().download_by_url(url, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\extractor.py", line 227, in download
    av=stream_id in self.dash_streams)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 785, in download_urls
    url_save(url, filepath, bar, refer = refer, is_part = True, faker = faker, headers = headers, **kwargs)
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 599, in url_save
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "c:\program files\python36\lib\site-packages\you_get\common.py", line 344, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\program files\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\program files\python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "c:\program files\python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "c:\program files\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\program files\python36\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "c:\program files\python36\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "c:\program files\python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "c:\program files\python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "c:\program files\python36\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response



```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by scegg** [comment]
After fully downloaded, the output file contains only first several parts.

**Comment by scegg** [comment]
Error in merge:

you-get http://v.youku.com/v_show/id_XMjk3Mjc0NjEzNg==.html?spm=a2hzp.8253869.0.0 -d
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk3Mjc0NjEzNg==&ccode=0401&client_ip=192.168.1.1&utid=PLwaEkRBTXMCAXQZ8wuAdN6q&client_ts=1502858802
site:                优酷 (Youku)
title:               因为热 我们一错三千年 170816
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          258.6 MiB (271114274 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjk3Mjc0NjEzNg%3D%3D&type=hd3&ups_client_netip=116.25.243.11&ups_ts=1502858813&utid=PLwaEkRBTXMCAXQZ8wuAdN6q&ccode=0401&psid=57482d34466e2bac8da9e27fdbf37fdb&duration=1544&expire=18000&ups_key=7f112ab3bf64599339ec27b80d31dc29
    # download-with: you-get --format=hd3 [URL]

Downloading 因为热 我们一错三千年 170816.flv ...
 100% (258.6/258.6MB) ├███████████████████████████████████████┤[11/11]  438 MB/s
Merging video parts... ffmpeg version 3.3.3 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
[flv @ 00000000028fc540] Auto-inserting h264_mp4toannexb bitstream filter
Input #0, concat, from '.\鍥犱负鐑?鎴戜滑涓€閿欎笁鍗冨勾 170816.mp4.txt':
  Duration: N/A, start: 0.000000, bitrate: 1633 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080, 1505 kb/s, 25.03 fps, 25 tbr, 1k tbn, 50 tbc
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp, 128 kb/s
Output #0, mp4, to '.\鍥犱负鐑?鎴戜滑涓€閿欎笁鍗冨勾 170816.mp4':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p(tv, bt709, progressive), 1920x1080, q=2-31, 1505 kb/s, 25.03 fps, 25 tbr, 16k tbn, 1k tbc
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, fltp, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[concat @ 00000000028f24a0] Impossible to open '鍥犱负鐑?鎴戜滑涓€閿欎笁鍗冨勾 170816[01].flv'
.\鍥犱负鐑?鎴戜滑涓€閿欎笁鍗冨勾 170816.mp4.txt: Invalid data found when processing input
frame= 3376 fps=0.0 q=-1.0 Lsize=   27011kB time=00:02:15.00 bitrate=1639.1kbits/s speed= 576x
video:24794kB audio:2110kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.398168%
Merged into 因为热 我们一错三千年 170816.mp4

**Comment by rosynirvana** [comment]
You got a broken segments from CDN servers and ffmpeg did report it.

>  Invalid data found when processing input

**Comment by scegg** [comment]
@rosynirvana 
Thanks for your information.
How to get avoid of that CDN server?
The same file can be downloaded at the same computer using youtube-dl.

**Comment by rosynirvana** [comment]
retry or wait

**Comment by scegg** [comment]
@rosynirvana 
>.<

Do you know how youtube-dl deal with the CDN server...? I found that download the mp4 as one piece directly without the flv stage. Maybe using another server?

**Comment by rosynirvana** [comment]
Let me explain ``retry or wait'' a little.
When someone watch youku videos or videos from any other site in their favourite web browser, without doing anything hacky, it's not surprising the video cannot be loaded, right? 
What will they do? Refresh the page. This is ``retry''.
But sometimes there's still no luck after several tries, they wil check it later. This is ``wait''.
This is the answer to your emoji.

AFAIK youku provide no content in a single mp4 segment so I guess the merging process is hdden from you.

**Comment by scegg** [comment]
@rosynirvana

I waited 12 hrs with 20+ times retries... Maybe it requires more...
