### ISSUE TITLE
youku视频“客户端无权播放”(you-get fail: youku, client premisson denied

### ISSUE THREAD

**Issue by numberwolf** [soimort/you-get#2281]
log:
$ you-get --debug http://v.youku.com/v_show/id_XMjk0NTYwODQ4NA==.html
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk0NTYwODQ4NA==&ccode=0401&client_ip=192.168.1.1&utid=K3McEsBfrV0CARvdJYWch6xq&client_ts=1502971179
you-get: \u5ba2\u6237\u7aef\u65e0\u6743\u64ad\u653e,201

**Comment by lki2019** [comment]
＃2244
看看这个里面的回复，按照所说的更新就好了，

**Comment by note286** [comment]
@numberwolf 使用python3的pip3安装you-get即可，然后更新到开发版本即可
```
pip3 install you-get
pip3 install --upgrade git+https://github.com/soimort/you-get@develop
```
可以参考 [https://github.com/soimort/you-get#upgrading](https://github.com/soimort/you-get#upgrading)

**Comment by yuanchongfu** [comment]
youku视频“客户端无权播放 201

**Comment by kfcceo** [comment]
我也是 这个问题。怎么办？

**Comment by note286** [comment]
@kfcceo @yuanchongfu 你们都不看上面的吗？？？我在上面回答了啊，更新到开发版就可以了啊，既然都用命令行工具了，这种更新操作应该都会吧，我亲测好几次了，绝对好使。

**Comment by yuanchongfu** [comment]
爱奇艺不能下载

**Comment by xtay573269555** [comment]
是的，更新到开发版就可以了。没有git的可以用这个命令。
pip3 install --upgrade https://github.com/soimort/you-get/archive/develop.zip
