### ISSUE TITLE
爱课程好几个URL下载到333.5M停止

### ISSUE THREAD

**Issue by 121786404** [soimort/you-get#2283]
我发现了好几个URL都是下载到333.5M停止，好奇怪，下面是一个例子

you-get --debug "http://www.icourses.cn/jpk/changeforVideo.action?resId=147055&courseId=3518"
[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=147055&courseId=3518
[DEBUG] get_content: http://www.icourses.cn/jpk/getResPlayInfo.action?v=1502982821797&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&uuid=147055&other=
[DEBUG] get_content: http://media1.icourses.cn:8080/process4/campus//ssl/host.shtml
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=3156961
[DEBUG] url_info: http://media2.icourses.cn/process4/campus/processres/flv/2012/11/25/ff808081-3b2d5ab6-013b-37d6aa25-00ba.flv?r=1503066998&h=L5T6zpoq77B-B-aX5llJuw&ls=play&start=0&p=151020&lv=150606-1&lt=8-17%2F8%3A12%3A34
Site:       icourses.cn
Title:      通信原理   第9课【卷积码编码】
Type:       Flash video (video/x-flv)
Size:       355.31 MiB (372573335 Bytes)

[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=6890526
Downloading 通信原理   第9课【卷积码编码】.flv ...
 4.1% ( 14.5/355.3MB) ├███────────────────────────────────────────────────────────────────┤[1/1]  427 kB/s[DEBUG] Calling callback update_url for new URL from 15204352
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=6705909
 8.2% ( 29.0/355.3MB) ├██████─────────────────────────────────────────────────────────────┤[1/1]  838 kB/s[DEBUG] Calling callback update_url for new URL from 30408704
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=3654610
12.2% ( 43.5/355.3MB) ├█████████──────────────────────────────────────────────────────────┤[1/1]  522 kB/s[DEBUG] Calling callback update_url for new URL from 45613056
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=3208876
16.3% ( 58.0/355.3MB) ├███████████────────────────────────────────────────────────────────┤[1/1]  694 kB/s[DEBUG] Calling callback update_url for new URL from 60817408
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=8076501
20.4% ( 72.5/355.3MB) ├██████████████─────────────────────────────────────────────────────┤[1/1]  606 kB/s[DEBUG] Calling callback update_url for new URL from 76021760
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=9447062
24.5% ( 87.0/355.3MB) ├█████████████████──────────────────────────────────────────────────┤[1/1]  424 kB/s[DEBUG] Calling callback update_url for new URL from 91226112
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=4169957
28.6% (101.5/355.3MB) ├███████████████████────────────────────────────────────────────────┤[1/1]  426 kB/s[DEBUG] Calling callback update_url for new URL from 106430464
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=5125837
32.6% (116.0/355.3MB) ├██████████████████████─────────────────────────────────────────────┤[1/1]  375 kB/s[DEBUG] Calling callback update_url for new URL from 121634816
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=7387693
36.7% (130.5/355.3MB) ├█████████████████████████──────────────────────────────────────────┤[1/1]  423 kB/s[DEBUG] Calling callback update_url for new URL from 136839168
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=903825
40.8% (145.0/355.3MB) ├███████████████████████████────────────────────────────────────────┤[1/1]  376 kB/s[DEBUG] Calling callback update_url for new URL from 152043520
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=2717679
44.9% (159.5/355.3MB) ├██████████████████████████████─────────────────────────────────────┤[1/1]  595 kB/s[DEBUG] Calling callback update_url for new URL from 167247872
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=4926550
49.0% (174.0/355.3MB) ├█████████████████████████████████──────────────────────────────────┤[1/1]  345 kB/s[DEBUG] Calling callback update_url for new URL from 182452224
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=8545667
53.1% (188.5/355.3MB) ├████████████████████████████████████───────────────────────────────┤[1/1]  469 kB/s[DEBUG] Calling callback update_url for new URL from 197656576
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=6126153
57.1% (203.0/355.3MB) ├███████████████████████████████████████────────────────────────────┤[1/1]  619 kB/s[DEBUG] Calling callback update_url for new URL from 212860928
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=2653909
61.2% (217.5/355.3MB) ├█████████████████████████████████████████──────────────────────────┤[1/1]  258 kB/s[DEBUG] Calling callback update_url for new URL from 228065280
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=2955572
65.3% (232.0/355.3MB) ├████████████████████████████████████████████───────────────────────┤[1/1]  276 kB/s[DEBUG] Calling callback update_url for new URL from 243269632
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=9748562
69.4% (246.5/355.3MB) ├███████████████████████████████████████████████────────────────────┤[1/1]  618 kB/s[DEBUG] Calling callback update_url for new URL from 258473984
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=4006640
73.5% (261.0/355.3MB) ├█████████████████████████████████████████████████──────────────────┤[1/1]  710 kB/s[DEBUG] Calling callback update_url for new URL from 273678336
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=413093
77.5% (275.5/355.3MB) ├████████████████████████████████████████████████████───────────────┤[1/1]  575 kB/s[DEBUG] Calling callback update_url for new URL from 288882688
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=6820494
81.6% (290.0/355.3MB) ├███████████████████████████████████████████████████████────────────┤[1/1]  318 kB/s[DEBUG] Calling callback update_url for new URL from 304087040
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=4409875
85.7% (304.5/355.3MB) ├█████████████████████████████████████████████████████████──────────┤[1/1]  398 kB/s[DEBUG] Calling callback update_url for new URL from 319291392
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=3045515
89.8% (319.0/355.3MB) ├████████████████████████████████████████████████████████████───────┤[1/1]  532 kB/s[DEBUG] Calling callback update_url for new URL from 334495744
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=3875642
93.9% (333.5/355.3MB) ├███████████████████████████████████████████████████████████████────┤[1/1]  373 kB/s[DEBUG] Calling callback update_url for new URL from 349700096
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=9707960
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://www.icourses.cn/jpk/changeforVideo.action?resId=147055&courseId=3518']
Traceback (most recent call last):
  File "/home/sheldon.liu/bin/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/sheldon.liu/bin/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/sheldon.liu/bin/you-get/src/you_get/common.py", line 1352, in main
    m, url = url_to_module(url)
  File "/home/sheldon.liu/bin/you-get/src/you_get/common.py", line 1259, in script_main
    try:
  File "/home/sheldon.liu/bin/you-get/src/you_get/common.py", line 1057, in download_main
    def download_main(download, download_playlist, urls, playlist, **kwargs):
  File "/home/sheldon.liu/bin/you-get/src/you_get/common.py", line 1345, in any_download
    location = res.getheader('location')
  File "/home/sheldon.liu/bin/you-get/src/you_get/extractors/icourses.py", line 45, in icourses_download
    download_urls_icourses(real_url, title, 'flv',total_size=size, output_dir=output_dir, max_size=15000000, dyn_callback=icourses_parser.update_url)
  File "/home/sheldon.liu/bin/you-get/src/you_get/extractors/icourses.py", line 315, in download_urls_icourses
    url_save_icourses(url, filepath, bar, total_size, headers=headers, **kwargs)
  File "/home/sheldon.liu/bin/you-get/src/you_get/extractors/icourses.py", line 386, in url_save_icourses
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "/home/sheldon.liu/bin/you-get/src/you_get/common.py", line 344, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by lki2019** [comment]
<pre><code>[DEBUG] get_content: http://media3.icourses.cn/ssl/ssl.shtml?r=2844529
Downloading 通信原理   第9课【卷积码编码】.flv ...
93.9% (333.5/355.3MB) ├████████████████████████████
███████████──┤[1/1]  326 GB/s[DEBUG] Calling callback update_url f
or new URL from 349700096
[DEBUG] get_content: http://media3.icourses.cn/ssl/ssl.shtml?r=4963475
[DEBUG] HTTP Error with code404
[DEBUG] HTTP Error with code404
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://www.icourses.cn/jpk/changeforVideo.action?resId=147055&courseI
d=3518']
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts
\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1360, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1267, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1065, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1353, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\icourses.py", line 45, in icourses_download
    download_urls_icourses(real_url, title, 'flv',total_size=size, output_dir=ou
tput_dir, max_size=15000000, dyn_callback=icourses_parser.update_url)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\icourses.py", line 315, in download_urls_icourses
    url_save_icourses(url, filepath, bar, total_size, headers=headers, **kwargs)

  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\icourses.py", line 374, in url_save_icourses
    buffer = response.read(to_read)
AttributeError: 'NoneType' object has no attribute 'read'<pre><code>



楼主说的情况的确存在·······

**Comment by 121786404** [comment]
you-get "http://www.icourses.cn/jpk/changeforVideo.action?resId=784439&courseId=3827"
you-get "http://www.icourses.cn/jpk/changeforVideo.action?resId=784441&courseId=3827"
you-get "http://www.icourses.cn/jpk/changeforVideo.action?resId=784443&courseId=3827"
you-get "http://www.icourses.cn/jpk/changeforVideo.action?resId=784445&courseId=3827"
you-get "http://www.icourses.cn/jpk/changeforVideo.action?resId=784447&courseId=3827"
you-get "http://www.icourses.cn/jpk/changeforVideo.action?resId=784449&courseId=3827"
you-get "http://www.icourses.cn/jpk/changeforVideo.action?resId=784459&courseId=3827"
you-get "http://www.icourses.cn/jpk/changeforVideo.action?resId=784451&courseId=3827"
you-get "http://www.icourses.cn/jpk/changeforVideo.action?resId=784453&courseId=3827"
you-get "http://www.icourses.cn/jpk/changeforVideo.action?resId=784455&courseId=3827"

这几个也都是下载到333.5M就停止

**Comment by rosynirvana** [comment]
下了20几个分片被踢了呗

**Comment by 121786404** [comment]
下了20几个分片被踢了呗
可是过一会 续传 也不行

**Comment by rosynirvana** [comment]
这站就别抱希望了，自己乱改http协议实现的视频分段，debug请求基本都block掉，能下载一部分都是运气了

**Comment by rosynirvana** [comment]
我知道发生什么了，offset大于一定值时，不能再256x1024边界上seek，而在1024x1024x15边界上seek是可以的……

**Comment by 121786404** [comment]
这解决效率 太赞了
