### ISSUE TITLE
乐视视频无法下载

### ISSUE THREAD

**Issue by kang0024** [soimort/you-get#2288]
you-get --format 1080p http://www.le.com/ptv/vplay/1487303.html 无法下载，debug的话[DEBUG] url_info: http://107.155.58.12:80/103/14/92/letv-uts/14/ver_00_20-301354272-avc-481168-aac-32001-6224958-406060736-5880c71fc95626061d224e4992e3b07d-1420152433789_mp4/ver_00_22_137_630_4_2726752_169508696_0.ts?mltag=100&platid=1&splatid=101&playid=0&geo=MY-0-0-100&tag=-&ch=&p1=1&p2=10&p3=-&tss=ios&b=521&bf=90&nlh=4096&path=&sign=letv&proxy=2258618614,1909413414,611247494&uuid=fb235e0ffedba044d91d9557d684562f46b98926_0&ntm=1503051000&keyitem=GOw_33YJAAbXYE-cnQwpfLlv_b2zAkYctFVqe5bsXQpaGNn3T1-vhw..&its=0&nkey2=1b49c307a4affc0217ea1d008fa18251&uid=1009841888.rp&qos=3&enckit=&m3v=1&token=&vid=1487303&liveid=&station=&app_name=&app_ver=&fcheck=0&pantm=&panuid=&pantoken=&cips=60.48.246.224&vod_live_path=&ledituid=&leditcid=&leditcip=&leditfl=&leditafl=&ajax=&lsbv=

这一段无限循环。

Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by jyuan15** [comment]
可以下啊，不过乐视任何分辨率都是540p的

$ you-get -o /f/movie -F1080p http://www.le.com/ptv/vplay/1487303.html
Site:       Le.com
Title:      开心家族
Type:       MPEG-4 video (video/mp4)
Size:       411.65 MiB (431642924 Bytes)

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 开心家族.mp4 ...
 100% (411.6/411.6MB) ├█████████┤[356/356]    2 MB/s
Merging video parts... Merged into 开心家族.mp4

**Comment by rosynirvana** [comment]
我猜是因为le.py会刷很多url_info的log，没仔细看以为是在无限循环……

**Comment by kang0024** [comment]
可以下了谢谢！
