### ISSUE TITLE
没有下载FFmpeg为什么也可以合并多段视频？

### ISSUE THREAD

**Issue by reaCodes** [soimort/you-get#2292]
没下载FFmpeg时，下载YouTube视频视频音频是不能合并的，但是下载youku电视剧就能合并，不过合并过的视频有些问题，随机选择时间节点播放，跳转很不流畅，或者直接一段时间视频无法播放。

请问这里边有什么原因？

下载FFmpeg后，这些问题都没有了，YouTube视频音频也能合并，youku合并后的视频跳转也很流畅。

**Comment by rosynirvana** [comment]
项目内有两个内置的合并flv和mp4的模块
只能做合并片段，不能做不同track的重混流

**Comment by reaCodes** [comment]
@rosynirvana 那只需要把ffmpeg添加到环境变量，you-get就能自动调用合并了是么？

**Comment by note286** [comment]
@reaCodes 对，添加到环境变量里就可以，去ffmpeg官网下载就可以，我记得bin里面有三个exe，记得把bin目录添加到环境变量里就可以了。
