### ISSUE TITLE
youku 客户端无权播放,201

### ISSUE THREAD

**Issue by jackal1988** [soimort/you-get#2293]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[C:\Users\Administrator>you-get http://v.youku.com/v_show/id_XMjk3OTM1MzM2MA==.html --debug
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk3OTM1MzM2MA==&ccode=0401&client_ip=192.168.1.1&utid=kfgjEu6O8AUCAYvicQkoQwMT&client_ts=1503464081
you-get: 客户端无权播放,201]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[C:\Users\Administrator>you-get http://v.youku.com/v_show/id_XMjk3OTM1MzM2MA==.html --debug
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk3OTM1MzM2MA==&ccode=0401&client_ip=192.168.1.1&utid=kfgjEu6O8AUCAYvicQkoQwMT&client_ts=1503464081
you-get: 客户端无权播放,201]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by lki2019** [comment]
C:\Users\Administrator>you-get -di http://v.youku.com/v_show/id_XMjk3OTM1MzM2MA=
=.html
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk3OTM1MzM2MA==&cc
ode=0401&client_ip=192.168.1.1&utid=m/sjEnbxVFYCAToSQOz3EnMy&client_ts=150346477
9
you-get: 客户端无权播放,201


复议

**Comment by JayXon** [comment]
same here, it was working yesterday

**Comment by rosynirvana** [comment]
ca5e07c

```
./you-get  http://v.youku.com/v_show/id_XMjk3OTM1MzM2MA\=\=.html
site:                优酷 (Youku)
title:               【评测】美国shubb夏伯专业变调夹介绍 靠谱吉他乐器专营店
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          85.0 MiB (89142319 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjk3OTM1MzM2MA%3D%3D&type=hd2&ups_client_netip=125.45.176.102&ups_ts=1503467642&utid=eAYkEh4bcigCAX0tsGaQBd2u&ccode=0401&psid=f8081de1a1417076c10c40b01dcd6a73&duration=654&expire=18000&ups_key=622edd64f33663591f5ee0e34d37190e
    # download-with: you-get --format=hd2 [URL]

Downloading 【评测】美国shubb夏伯专业变调夹介绍 靠谱吉他乐器专营店.flv ...
50.5% ( 42.9/ 85.0MB) ├█████████████████████────────────────────┤[2/4]   63 kB/s
```

After this commit I will not patch ```youku.py``` any more maybe someone can take its maintenance over.

**Comment by JayXon** [comment]
That worked, thanks.

**Comment by jackal1988** [comment]
thanks everybody~

**Comment by jin6220** [comment]
怎么办啊？ca5e07c打开了 这是想说明什么？

**Comment by StLym** [comment]
@rosynirvana 覆盖了youku.py，依旧201怎么办啊

**Comment by lki2019** [comment]
pip3 install --upgrade https://github.com/soimort/you-get/archive/develop.zip

这样更新一下就好了@StLym
