### ISSUE TITLE
爱奇艺部分无法解析

### ISSUE THREAD

**Issue by lki2019** [soimort/you-get#2294]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

you-get -di http://www.iqiyi.com/dianshiju/sjll_wjt.html
[DEBUG] get_response: http://www.iqiyi.com/dianshiju/sjll_wjt.html
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/dianshiju/sjll_wjt.html']
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts
\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.803', 'console_scripts', 'you-get')()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1361, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1268, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption
)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1066, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1354, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\iqiyi.py", line 139, in prepare
    info_u = 'http://mixer.video.iqiyi.com/jp/mixin/videos/' + tvid
TypeError: must be str, not NoneType

**Comment by rosynirvana** [comment]
```
./you-get -i www.iqiyi.com/dianshiju/sjll_wjt.html
site:                爱奇艺 (Iqiyi)
title:               神剧亮了_20170823期
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
      m3u8_url:      http://cache.m.iqiyi.com/mus/111367401/6660fe50f33cd9427fab1ee3f305d407/afbe8fd3d73448c9//20170823/fd/55/83b23746c75b69d1e2dc73c18290442c.m3u8?qd_originate=tmts_py&tvid=765889300&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1503468772022&qd_p=7d2db066&qd_asc=e6f078bd97436523cb98266ce137d294&qypid=765889300_04022000001000000000_14&qd_k=95aae8da001fde34e30e56a40fe7f389&vf=a52bd2365871ea5b4ffb8f871c2404d1&np_tag=nginx_part_tag
    # download-with: you-get --format=TD [URL]

    - format:        TD_H265
      container:     m3u8
      video-profile: 720p H265
      m3u8_url:      http://cache.m.iqiyi.com/mus/111367401/d88dd1263ea221e0c527393ad28a2f81/afbe8fd3d73448c9//20170823/3a/a0/93063e63cfac9ca737f4869fd477500f.m3u8?qd_originate=tmts_py&tvid=765889300&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1503468772023&qd_p=7d2db066&qd_asc=19875485c8416cf2e4bebc5c864128b5&qypid=765889300_04022000001000000000_17&qd_k=95aae8da001fde34e30e56a40fe7f389&vf=a80b7dfbf9edeb203bfa5d44065b5a42&np_tag=nginx_part_tag
    # download-with: you-get --format=TD_H265 [URL]

    - format:        HD
      container:     m3u8
      video-profile: 540p
      m3u8_url:      http://cache.m.iqiyi.com/mus/111367401/ff0847054f49894d060faf66a53a4141/afbe8fd3d73448c9//20170823/ad/57/1a30d1c99f9f5548405b88070bba7e70.m3u8?qd_originate=tmts_py&tvid=765889300&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1503468772022&qd_p=7d2db066&qd_asc=0eb6bf39364ffed6b70cb82933d5c3eb&qypid=765889300_04022000001000000000_2&qd_k=95aae8da001fde34e30e56a40fe7f389&vf=9263852e97dd10cb36ff34880924c5a7&np_tag=nginx_part_tag
    # download-with: you-get --format=HD [URL]

    - format:        HD_H265
      container:     m3u8
      video-profile: 540p H265
      m3u8_url:      http://cache.m.iqiyi.com/mus/111367401/9afa85bfa45a53d6e3798802d92f8aca/afbe8fd3d73448c9//20170823/12/5f/37d8331aadf32b95b2eee8e4fa949a86.m3u8?qd_originate=tmts_py&tvid=765889300&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1503468772022&qd_p=7d2db066&qd_asc=232dd70ca285c464ae5ccc81e7000526&qypid=765889300_04022000001000000000_21&qd_k=95aae8da001fde34e30e56a40fe7f389&vf=dcdcc161b6c501ff51cedd2f12c23a7a&np_tag=nginx_part_tag
    # download-with: you-get --format=HD_H265 [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
      m3u8_url:      http://cache.m.iqiyi.com/mus/111367401/c6ec254ac8767a3f9866ff7c3c3ae146/afbe8fd3d73448c9//20170823/54/a1/a6fe456896347b5c41cff51ec2123410.m3u8?qd_originate=tmts_py&tvid=765889300&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1503468772022&qd_p=7d2db066&qd_asc=d7b6b5d0582be2a60a3e8d0bdb645fa9&qypid=765889300_04022000001000000000_1&qd_k=95aae8da001fde34e30e56a40fe7f389&vf=93a0d5c7701a4c78c697de9f4dc85fa9&np_tag=nginx_part_tag
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
      m3u8_url:      http://cache.m.iqiyi.com/mus/111367401/7ebf35c6011efcc8958172e0c4a3ed4f/afbe8fd3d73448c9//20170823/3d/42/3d2608a5f1ae124a423dbdfa42d772ec.m3u8?qd_originate=tmts_py&tvid=765889300&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1503468772022&qd_p=7d2db066&qd_asc=7074783bb5b75ce71c54f89c9af1b07e&qypid=765889300_04022000001000000000_96&qd_k=95aae8da001fde34e30e56a40fe7f389&vf=9cd5d39b39291c9e5938a6e86c6adabf&np_tag=nginx_part_tag
    # download-with: you-get --format=LD [URL]
```

**Comment by lki2019** [comment]
@rosynirvana 
大神在这个issue下求教一个问题，
不想开新issue，因为不想太多人看到，

因为也是个爱奇艺视频解析相关的，所以在这个issue下问应该也不算文不对题

http://www.iqiyi.com/v_19rr879y8o.html 比如解析这个爱奇艺VIP视频

http://www.nuexini.shop/api/qq924282761.php?url=http://www.iqiyi.com/v_19rr879y8o.html 

这是一个软件，我抓出来的接口，

get后，

<pre><code>准备停止解析具体请联系作者解析结果请到bejson.com进行校验{
    "code": 0,
    "message": "success",
    "cost": 0.906,
    "type": "vod",
    "data": {
        "duration": 1403,
        "streams": [
            {
                "quality": "SPEED",
                "type": "M3U8",
                "segs": [
                    {
                        "url": "http://cache.m.iqiyi.com/mus/202783001/4f6f9f381d9f7cf11b94c9fbdb67ef81/afbe8fd3d73448c9/1023108576/20170827/84/f8/a2a169362cfa5ef02abdd795628d6aaf.m3u8?qd_originate=tmts_py&tvid=770010100&bossStatus=2&qd_vip=0&px=&qd_src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1503976195602&qd_p=76be2cf8&qd_asc=6c5c4df3a3507c717e842c2b3276b34e&qypid=770010100_04022000001000000000_96&qd_k=a0af377520d76d89bf4ffc2e1004a094&vf=fcc67d9682d21c9eddc9a0e6d83edbb3&np_tag=nginx_part_tag",
                        "duration": 1403
                    }
                ]
            },
            {
                "quality": "1080P",
                "videoCodec": "H265",
                "type": "M3U8",
                "segs": [
                    {
                        "url": "http://cache.m.iqiyi.com/mus/202783001/4aaee2bcd691b632b8f4f7082962709c/afbe8fd3d73448c9/1023108576/20170827/75/6f/9913a32e0f327703629faafd7d8deb3f.m3u8?qd_originate=tmts_py&tvid=770010100&bossStatus=2&qd_vip=0&px=&qd_src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1503976195602&qd_p=76be2cf8&qd_asc=09bc0f294b46ee4732a28e897e45b176&qypid=770010100_04022000001000000000_18&qd_k=a0af377520d76d89bf4ffc2e1004a094&vf=cc64213b18e23b82348b578be15dd769&np_tag=nginx_part_tag",
                        "duration": 1403
                    }
                ]
            },
            {
                "quality": "1080P",
                "type": "M3U8",
                "segs": [
                    {
                        "url": "http://cache.m.iqiyi.com/mus/202783001/b0a688adc6fe044c369fd5bca00ed226/afbe8fd3d73448c9/1023108576/20170827/3f/1d/a03a12898a3a2a818628569182f0a8b6.m3u8?qd_originate=tmts_py&tvid=770010100&bossStatus=2&qd_vip=0&px=&qd_src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1503976195602&qd_p=76be2cf8&qd_asc=a10f2e9cb284d4c104db4ce51dc429d0&qypid=770010100_04022000001000000000_5&qd_k=a0af377520d76d89bf4ffc2e1004a094&vf=b01a5051f5d93b3d6f40dcbdfdfdc84a&np_tag=nginx_part_tag",
                        "duration": 1403
                    }
                ]
            },
            {
                "quality": "720P",
                "videoCodec": "H265",
                "type": "M3U8",
                "segs": [
                    {
                        "url": "http://cache.m.iqiyi.com/mus/202783001/9fa60898d30e18c499ad7ad0b30cda7c/afbe8fd3d73448c9/1023108576/20170827/ab/f4/81ebcf6707419f3d82731aa33048622f.m3u8?qd_originate=tmts_py&tvid=770010100&bossStatus=2&qd_vip=0&px=&qd_src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1503976195602&qd_p=76be2cf8&qd_asc=4e186874512fdcec73c67f61dcf76189&qypid=770010100_04022000001000000000_17&qd_k=a0af377520d76d89bf4ffc2e1004a094&vf=ec9d7cc64cb4041109d0bea21ae3dee9&np_tag=nginx_part_tag",
                        "duration": 1403
                    }
                ]
            },
            {
                "quality": "720P",
                "type": "M3U8",
                "segs": [
                    {
                        "url": "http://cache.m.iqiyi.com/mus/202783001/bcd3ea5f01d715aeb558c6ca9e0bf8ab/afbe8fd3d73448c9/1023108576/20170827/71/c3/6b86abc87ce5cee63a6c3d4b257b4289.m3u8?qd_originate=tmts_py&tvid=770010100&bossStatus=2&qd_vip=0&px=&qd_src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1503976195602&qd_p=76be2cf8&qd_asc=8f9f79957a5ef6b22d038a7d56677332&qypid=770010100_04022000001000000000_4&qd_k=a0af377520d76d89bf4ffc2e1004a094&vf=20cb7d30576d02987f77fb9874d07e45&np_tag=nginx_part_tag",
                        "duration": 1403
                    }
                ]
            },
            {
                "quality": "SD",
                "type": "M3U8",
                "segs": [
                    {
                        "url": "http://cache.m.iqiyi.com/mus/202783001/c2940e87eaecfbf228838efad0b488a1/afbe8fd3d73448c9/1023108576/20170827/8b/ae/3a973a69c82625dc53c581e935e6dbf3.m3u8?qd_originate=tmts_py&tvid=770010100&bossStatus=2&qd_vip=0&px=&qd_src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1503976195602&qd_p=76be2cf8&qd_asc=10c5937f160236b9e05f62620d77deba&qypid=770010100_04022000001000000000_1&qd_k=a0af377520d76d89bf4ffc2e1004a094&vf=efd458e6f8941b5523ba2410c5893484&np_tag=nginx_part_tag",
                        "duration": 1403
                    }
                ]
            },
            {
                "quality": "SUPERHD",
                "videoCodec": "H265",
                "type": "M3U8",
                "segs": [
                    {
                        "url": "http://cache.m.iqiyi.com/mus/202783001/b735b24bdc8e803fbddb8041cb1c1907/afbe8fd3d73448c9/1023108576/20170827/81/27/fd59ab1f917ed0522e26e2f8c8b34abd.m3u8?qd_originate=tmts_py&tvid=770010100&bossStatus=2&qd_vip=0&px=&qd_src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1503976195602&qd_p=76be2cf8&qd_asc=b21731146a137727240c430ba6a856b1&qypid=770010100_04022000001000000000_21&qd_k=a0af377520d76d89bf4ffc2e1004a094&vf=18d5e95333b5435b4ef1287c5e650762&np_tag=nginx_part_tag",
                        "duration": 1403
                    }
                ]
            },
            {
                "quality": "HD",
                "type": "M3U8",
                "segs": [
                    {
                        "url": "http://cache.m.iqiyi.com/mus/202783001/6703f09899fa66903f2d9891eac80318/afbe8fd3d73448c9/1023108576/20170827/8f/b9/23ecaa465b83efee9db3f4755fd336d1.m3u8?qd_originate=tmts_py&tvid=770010100&bossStatus=2&qd_vip=0&px=&qd_src=3_31_312&prv=1&previewType=1&previewTime=6&from=&qd_time=1503976195602&qd_p=76be2cf8&qd_asc=b82e775da9ba49609e112235e6b70371&qypid=770010100_04022000001000000000_2&qd_k=a0af377520d76d89bf4ffc2e1004a094&vf=af1fc2af58277585036b93a8975c676a&np_tag=nginx_part_tag",
                        "duration": 1403
                    }
                ]
            }
        ],
        "title": "龙珠超 第105集"
    }
}
<pre><code>

可以解析出1080P地址，
这个接口腾讯 优酷什么的 也可以直接解析出相对应的m3u8地址
因为m3u8地址下载快，所以我还是很感兴趣的

我的目的本来是想扒下来他这个接口的php文件内容，也就是api
但是不知道怎么弄，过几天这软件貌似就关掉接口了，所以这几天在研究怎么吧他这个接口内容，拔下来

因为技术有限，求大神指点

**Comment by rosynirvana** [comment]
你多学点东西吧
php的代码在服务器端，不给客户端的

**Comment by lki2019** [comment]
因为要学的东西太多了，所以现在是遇到问题后，在根据问题涉及的知识点针对的去学。
宽泛的学，感觉要学的东西好多好多····

**Comment by lki2019** [comment]
在这个问题下说吧，就不开新的了，也是关于爱奇艺的

刚才一个小伙伴问我关于爱奇艺4K视频下载的问题，他有会员账号，也导出cookies了，
但是无法下载到4K视频，他传我了份，我看了下，的确只能解析出720P

我让他用火狐插件和谷歌插件分别导出了2份cookies出来，
我试了都不行，
大神帮忙看看是现在的you-get无法加载cookies下载爱奇艺VIP视频了，还是其他什么问题

=========
http://www.iqiyi.com/v_19rr8ketuo.html#vfrm=24-9-0-1  视频是这个 只是个普通视频
但是1080和4K清晰度 会员才可以切换


2份cookies我打包了  链接: https://pan.baidu.com/s/1bpNGrsb 密码: je5f


G:\我的文档\Tencent Files\509199637\FileRecv>you-get -i -c cookies.txt http://ww
w.iqiyi.com/v_19rr8ketuo.html#vfrm=24-9-0-1
site:                爱奇艺 (Iqiyi)
title:               鬼吹灯之牧野诡事2第1集
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        TD
      container:     m3u8
      video-profile: 720p
      m3u8_url:      http://cache.m.iqiyi.com/mus/215462001/37daa21411197ec9cde4
8ee844a46d12/afbe8fd3d73448c9//20170804/8c/64/721a8cefcf8ab902d14ccf29e99adbb6.m
3u8?qd_originate=tmts_py&tvid=748017100&bossStatus=0&qd_vip=0&px=a5rahekOUu0GPBP
hkYassdWu6Nwzv7gxvACLbQlZm1RxghQ3DUOJRZYQut6y9vXNqNc70&qd_src=3_31_312&prv=&prev
iewType=&previewTime=&from=&qd_time=1504268165689&qd_p=3a1240ea&qd_asc=4ca474a49

**Comment by rosynirvana** [comment]
you-get不支持iqiyi的VIP
https://github.com/soimort/you-get/wiki/Known-Bugs

也没有支持的计划

**Comment by lki2019** [comment]
原来如此 怪不得

**Comment by lki2019** [comment]
那大神能否在不用you-get的情况下，
其他方法在有会员账号的前提下，获取高清晰度的地址呢？

不知道方便说不？不方便我就把上面的问题删了··
