### ISSUE TITLE
可以添加对wasu.cn的支持吗

### ISSUE THREAD

**Issue by luhy118** [soimort/you-get#2295]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by lki2019** [comment]
<pre><code>
https://www.wasu.cn/Play/show/id/9178471


http://wapvod-al.wasu.cn/pcsan12/mams/vod/201708/23/15/201708231526007382c556769.mp4?auth_key=b8724e0b0695148b363b6b36cf8ae01e-1503482695-7ef5b154ef16469f00ddb3c92de9bd5b-&sk=89323f6f0bee5c50ad27f58f56afd0eb&vid=9178471&cid=11&version=MIPlayer_V1.7.0&vtype=201708230001&sign=a3bb44805885f1e4baf0249175c09aeb87b1d218


https://www.wasu.cn/Play/show/id/9176426


http://p2pvod-pc-bj.wasu.cn/pcsan12/mams/vod/201708/22/22/2017082222394264582a77c24.mp4?auth_key=3aad570537e2e82e36c3e1f961d49fe3-1503482736-a1ad21d476b46110c0e641db1d601aa3-&sk=48b1175ec6b2b51519cf141e954912f9&version=P2PPlayer_V.4.2.0&vid=9176426&catid=13&vbytetime=521

https://www.wasu.cn/wap/Play/show/id/9120399

http://wapvod-al.wasu.cn/pcsan12/mams/vod/201708/08/15/20170808150433195edf410a1.mp4?auth_key=d1fa812da91934a20a879ac7b6d7e4f4-1503482814-c93fdc7762f6b5f805aff8f9f0dadaaa-&sk=89323f6f0bee5c50ad27f58f56afd0eb&vid=9120399&cid=60&version=MIPlayer_V1.7.0&vtype=201708230001&sign=41aa7d853bababe32a8625b06e6880954d9ef001




总结：你装个IDM直接就出来地址了，有的是m3u8 你切换下UA就出来MP4直链了
https://www.wasu.cn/Live/show/id/17663

http://livehls1-yf.wasu.cn/htv5/z.m3u8?auth_key=2c33565821fbc5f96f2d08e03ebb83d6-1503482924-2804c58d9f1aa0345d1c9d60a4a82a57-&sk=81a22913b2670bae6e9cddde62c9a021&vid=17663&version=PadPlayer_V1.5.0<pre><code>



这种直播 你直接添加到播放器就可以看

**Comment by luhy118** [comment]
@lki2019 MP4直链下载：http://p2pvod-pc-bj.wasu.cn/pcsan12/mams/vod/201708/22/22/2017082222394264582a77c24.mp4?auth_key=3aad570537e2e82e36c3e1f961d49fe3-1503482736-a1ad21d476b46110c0e641db1d601aa3-&sk=48b1175ec6b2b51519cf141e954912f9&version=P2PPlayer_V.4.2.0&vid=9176426&catid=13&vbytetime=521
有没什么算法或接口可以拼接得到上面这地址？
我要在代码中实现下载功能，为这一个网站装个装个IDM很不方便。

**Comment by lki2019** [comment]
你如果想找个通用的解决方案
那就是你们玩编程的人研究的事情了
如果你只是想下载里面的视频什么的
IDM安装不麻烦啊。你看一个视频自动就依附在视频上方你点击下载就是了
最起码对这个站是这样
你想和you-get大神们那样开发出一个针对这个站的通用解析脚本，
那我就不懂了 如果你懂编程 ，你就研究下啊

**Comment by rosynirvana** [comment]
#1870
