### ISSUE TITLE
网易云音乐单个音频下载接口失效

### ISSUE THREAD

**Issue by zhangjack0310** [soimort/you-get#2302]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
youget/you-get/src/you_get/extractors/netease.py", line 115, in netease_song_download
    songNet = 'p' + song['mp3Url'].split('/')[2][1:]
AttributeError: 'NoneType' object has no attribute 'split'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [你好soimort：
首先感谢做了这么一个强大的项目。
我在使用you-get下载单个网易云链接的时候发现接口失效。
这个接口在netease_cloud_music_download的elif "song" in url的判断分支里。
我去看了一下，这个接口会返回400错误或者返回的json数据没有mp3地址。
应该是网易云接口更新了。
我分别在mac／iphone／web端扒了一下接口，都不是原来所用的接口。想修复这个bug但是一直没有头绪。
想知道这个接口之前是从哪里获得的，希望自己也能做一些贡献。
再次感谢！]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
dup #2074
接口是几年前的安卓客户端
