### ISSUE TITLE
B站下载选择时错误

### ISSUE THREAD

**Issue by saku1119** [soimort/you-get#2303]
汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [X] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [X] 您的`you-get`为最新版.
- [X] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [X] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[C:\Users\Administrator>you-get -c cookies.txt -i https://bangumi.bilibili.com/an
ime/6023/play#114289
you-get: It's a paid item
霹雳天命之仙魔鏖锋Ⅱ斩魔录 [第四十三章 末日风暴]
site:                Bilibili
title:               霹雳天命之仙魔鏖锋Ⅱ斩魔录 [第四十三章 末日风暴]
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        flv
      container:     flv
      size:          2347.7 MiB (2461794233 bytes)
    # download-with: you-get --format=flv [URL]

    - format:        mp4
      container:     mp4
      size:          763.1 MiB (800205855 bytes)
    # download-with: you-get --format=mp4 [URL]


C:\Users\Administrator>you-get -c cookies.txt --format=flv https://bangumi.bilib
ili.com/anime/6023/play#114289
you-get: It's a paid item
霹雳天命之仙魔鏖锋Ⅱ斩魔录 [第四十三章 末日风暴]
site:                Bilibili
title:               霹雳天命之仙魔鏖锋Ⅱ斩魔录 [第四十三章 末日风暴]
stream:
    - format:        flv
      container:     flv
      size:          1111.2 MiB (1165165783 bytes)
    # download-with: you-get --format=flv [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 霹雳天命之仙魔鏖锋Ⅱ斩魔录 (第四十三章 末日风暴).flv ...
 0.0% (   0.0/1111.2MB) ├───────────────────────────
 6.7% (  75.0/1111.2MB) ├███────────────────────────
14.9% ( 166.0/1111.2MB) ├██████─────────────────────
23.3% ( 258.4/1111.2MB) ├█████████──────────────────
30.9% ( 343.2/1111.2MB) ├████████████───────────────
39.0% ( 433.4/1111.2MB) ├███████████████────────────
45.5% ( 506.1/1111.2MB) ├█████████████████──────────
51.8% ( 575.8/1111.2MB) ├███████████████████────────
62.0% ( 688.5/1111.2MB) ├███████████████████████────
68.4% ( 760.5/1111.2MB) ├██████████████████████████─
77.1% ( 856.8/1111.2MB) ├███████████████████████████
80.2% ( 891.1/1111.2MB) ├███████████████████████████
80.2% ( 891.3/1111.2MB) ├███████████████████████████
80.2% ( 891.6/1111.2MB) ├███████████████████████████
80.3% ( 891.8/1111.2MB) ├███████████████████████████
80.3% ( 892.1/1111.2MB) ├███████████████████████████
80.3% ( 892.3/1111.2MB) ├███████████████████████████
80.3% ( 892.6/1111.2MB) ├███████████████████████████
80.3% ( 892.8/1111.2MB) ├███████████████████████████
80.4% ( 893.1/1111.2MB) ├███████████████████████████
80.4% ( 893.3/1111.2MB) ├███████████████████████████
80.4% ( 893.6/1111.2MB) ├███████████████████████████
80.4% ( 893.8/1111.2MB) ├███████████████████████████
80.5% ( 894.1/1111.2MB) ├███████████████████████████
80.5% ( 894.3/1111.2MB) ├███████████████████████████
80.5% ( 894.6/1111.2MB) ├███████████████████████████
███───────┤[11/13]  513 kB/s
C:\Users\Administrator>]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [下载指定是2g那个 --format=flv 但是下载开始后是1g的文件……清晰度应该是变成非高清，不知道为啥……]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
挂了cookie直接用默认format应该就行

**Comment by saku1119** [comment]
噗！好了，谢谢~~

**Comment by rosynirvana** [comment]
帮个忙
贴一下-u的第一个url
和-u --format=hdmp4的第一个url

**Comment by saku1119** [comment]
https://bangumi.bilibili.com/anime/6023/play#114289  这个咩？

**Comment by rosynirvana** [comment]
是

```you-get -u https://bangumi.bilibili.com/anime/6023/play#114289```
```you-get -u --format=hdmp4 https://bangumi.bilibili.com/anime/6023/play#114289```

都会打印出若干url
贴第一个出来就行了

**Comment by saku1119** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>you-get -u https://bangumi.bilibili.com/anime/6023/play#1
14289
you-get: It's a paid item
霹雳天命之仙魔鏖锋Ⅱ斩魔录 [第四十三章 末日风暴]
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>you-get -u --format=hdmp4 https://bangumi.bilibili.com/an
ime/6023/play#114289
you-get: It's a paid item
霹雳天命之仙魔鏖锋Ⅱ斩魔录 [第四十三章 末日风暴]
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>you-get -u -c cookies.txt --format=hdmp4 https://bangumi.
bilibili.com/anime/6023/play#114289
you-get: It's a paid item
霹雳天命之仙魔鏖锋Ⅱ斩魔录 [第四十三章 末日风暴]
site:                Bilibili
title:               霹雳天命之仙魔鏖锋Ⅱ斩魔录 [第四十三章 末日风暴]
stream:
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>you-get -c cookies.txt -u https://bangumi.bilibili.com/an
ime/6023/play#114289
you-get: It's a paid item
霹雳天命之仙魔鏖锋Ⅱ斩魔录 [第四十三章 末日风暴]
site:                Bilibili
title:               霹雳天命之仙魔鏖锋Ⅱ斩魔录 [第四十三章 末日风暴]
stream:
    - format:        flv
      container:     flv
      size:          2347.7 MiB (2461794233 bytes)
    # download-with: you-get --format=flv [URL]

Real URLs:
http://tx.acgvideo.com/91/98/22539891/22539891-1-112.flv?txTime=1503669633&platf
orm=pc&txSecret=d7685af3748291ae06a3efdc3a51d4d0&oi=1894638782&rate=1091367&hfb=
b99ffc3c5c68f00a33123bb25f882d5b
http://tx.acgvideo.com/91/98/22539891/22539891-2-112.flv?txTime=1503669633&platf
orm=pc&txSecret=a775228a76b3c2f15beab4c2d33d1cf3&oi=1894638782&rate=1015892&hfb=
b99ffc3c5c68f00a33123bb25f882d5b
http://tx.acgvideo.com/91/98/22539891/22539891-3-112.flv?txTime=1503669633&platf
orm=pc&txSecret=7c884540056fe5092b5517a8ac1b7b19&oi=1894638782&rate=996745&hfb=b
99ffc3c5c68f00a33123bb25f882d5b
http://tx.acgvideo.com/91/98/22539891/22539891-4-112.flv?txTime=1503669633&platf
orm=pc&txSecret=4640745761ff5b5251b99e7de08b5886&oi=1894638782&rate=967310&hfb=b
99ffc3c5c68f00a33123bb25f882d5b
http://tx.acgvideo.com/91/98/22539891/22539891-5-112.flv?txTime=1503669633&platf
orm=pc&txSecret=1442eb8ca8e5825bd1af3d78bdcb3a33&oi=1894638782&rate=879861&hfb=b
99ffc3c5c68f00a33123bb25f882d5b
http://tx.acgvideo.com/91/98/22539891/22539891-6-112.flv?txTime=1503669633&platf
orm=pc&txSecret=dc19090e041b657d4061c64e7b7a5981&oi=1894638782&rate=889556&hfb=b
99ffc3c5c68f00a33123bb25f882d5b
http://tx.acgvideo.com/91/98/22539891/22539891-7-112.flv?txTime=1503669633&platf
orm=pc&txSecret=3c2fab9032969f31aea7506b7893329b&oi=1894638782&rate=735661&hfb=b
99ffc3c5c68f00a33123bb25f882d5b
http://tx.acgvideo.com/91/98/22539891/22539891-8-112.flv?txTime=1503669633&platf
orm=pc&txSecret=f0be8b32406edab042da5d47169c8812&oi=1894638782&rate=758888&hfb=b
99ffc3c5c68f00a33123bb25f882d5b
http://tx.acgvideo.com/91/98/22539891/22539891-9-112.flv?txTime=1503669633&platf
orm=pc&txSecret=c92a7ea69f0861ff516cd6e56901a1d0&oi=1894638782&rate=908954&hfb=b
99ffc3c5c68f00a33123bb25f882d5b
http://tx.acgvideo.com/91/98/22539891/22539891-10-112.flv?txTime=1503669633&plat
form=pc&txSecret=99c2530618cf5218d4231f8396c81e21&oi=1894638782&rate=858451&hfb=
b99ffc3c5c68f00a33123bb25f882d5b
http://tx.acgvideo.com/91/98/22539891/22539891-11-112.flv?txTime=1503669633&plat
form=pc&txSecret=44b5f64520e858ed0fa405cbd54689a8&oi=1894638782&rate=904029&hfb=
b99ffc3c5c68f00a33123bb25f882d5b
http://tx.acgvideo.com/91/98/22539891/22539891-12-112.flv?txTime=1503669633&plat
form=pc&txSecret=e01ad5bc982ff40491296703de88b93c&oi=1894638782&rate=764651&hfb=
b99ffc3c5c68f00a33123bb25f882d5b
http://tx.acgvideo.com/91/98/22539891/22539891-13-112.flv?txTime=1503669633&plat
form=pc&txSecret=c57e5df49cee9ab73cdffb495cb3291b&oi=1894638782&rate=811988&hfb=
b99ffc3c5c68f00a33123bb25f882d5b

C:\Users\Administrator>


擅自加了一下-c 希望有帮助~

**Comment by rosynirvana** [comment]
OK 明白了，感谢
