### ISSUE TITLE
优酷201 无权播放，之前也是这样然后升级可以了，这次升级了也不行。

### ISSUE THREAD

**Issue by jin6220** [soimort/you-get#2306]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```
在问题中搜索了201相关问题，但是看不懂啊，回答问题的人说的是英文。
如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by jin6220** [comment]
在issue中搜索了201相关问题，但是看不懂，回答问题的人说的是英文。

C:\Users\chao>you-get http://v.youku.com/v_show/id_XMjk2OTM5MzA0OA==.html --d
ebug
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk2OTM5MzA0OA==&cc
ode=0401&client_ip=192.168.1.1&utid=RCcoEgkNIwkCASrqGWhjYxlu&client_ts=150373818
0
you-get: 客户端无权播放,201

**Comment by jin6220** [comment]
https://github.com/soimort/you-get/blob/ca5e07cfa12115592b961d5a4b5760d1eb44e7de/src/you_get/extractors/youku.py
罩着这个文件改吗？但现在变成这样了
C:\Users\chao>you-get v.youku.com/v_show/id_XMjk2OTM5MzA0OA==.html
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by jyuan15** [comment]
视频地址前面缺 http://

**Comment by conanyangqun** [comment]
我的也是201。
http://v.youku.com/v_show/id_XMjkzMzk1MjEwOA==.html?spm=a2h1n.8261147.reload_201707.1~3~DL~DT~A
`you-get -i --debug http://v.youku.com/v_show/id_XMjkzMzk1MjEwOA==.html?spm=a2h1n.8261147.reload_201707.1~3~DL~DT~A
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjkzMzk1MjEwOA==&ccode=0401&client_ip=192.168.1.1&utid=O9QpEnqQZl8CAd3bo0GeAzzU&client_ts=1503847995
you-get: 客户端无权播放,201
`

**Comment by conanyangqun** [comment]
@jin6220 使用最新的develop分支，不要用release的，既可以解决这个问题。

**Comment by jin6220** [comment]
@conanyangqun  你好 开发版是这个嘛 https://you-get.org/ 这个网站第四点提到的链接？

**Comment by jin6220** [comment]
@conanyangqun  你好 下载开发版文件是这样操作吗？解压之后进入该文件下,按住Shift后再点击右键进入该文件夹的Dos命令窗口后输入以下的命令安装即可。
python setup.py install
但是我这里没反应 不知道为什么了 python3.4 win8.1
这是提示：
C:\Users\chao\Desktop\1>python setup.py install

C:\Users\chao\Desktop\1>

**Comment by StLym** [comment]
@conanyangqun 我现在用的0.4.803，优酷各种201，怎么改用develop分支啊

**Comment by VegetableCat** [comment]
好奇怪。。
香港的vps就可以下载。。。
本机上就201
