### ISSUE TITLE
爱奇艺下载的问题

### ISSUE THREAD

**Issue by lki2019** [soimort/you-get#2312]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

C:\Users\Administrator>you-get -d http://www.iqiyi.com/v_19rr87t8i4.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rr87t8i4.html
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/768647200
[DEBUG] get_content: http://www.iqiyi.com/v_19rr87t8i4.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/768647200/7845c037e06635efdec
051201704128c/?t=1504015284673&sc=5dca9b6306072d513099fa8a6f219fcf&src=76f90cbd9
2f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               中国新歌声第2季_20170825期
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      m3u8_url:      http://cache.m.iqiyi.com/mus/207600401/67cae5423ee1c622238e
d2c89c4b6466/afbe8fd3d73448c9//20170826/c1/2a/af451e622b981b00690d4104255cb036.m
3u8?qd_originate=tmts_py&tvid=768647200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_31
2&prv=&previewType=&previewTime=&from=&qd_time=1504015377238&qd_p=3a1240ea&qd_as
c=fd1d4a8958dd02ba14bcea2baf7a939c&qypid=768647200_04022000001000000000_14&qd_k=
5dca9b6306072d513099fa8a6f219fcf&vf=728575a33d24b9ee8926fb1d0d3b68ee&np_tag=ngin
x_part_tag
    # download-with: you-get --format=TD [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -i http://cache.m.iqiyi.com/mus/207600401/67cae5423ee1c622238ed2c89c4b
6466/afbe8fd3d73448c9//20170826/c1/2a/af451e622b981b00690d4104255cb036.m3u8?qd_o
riginate=tmts_py&tvid=768647200&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&p
reviewType=&previewTime=&from=&qd_time=1504015377238&qd_p=3a1240ea&qd_asc=fd1d4a
8958dd02ba14bcea2baf7a939c&qypid=768647200_04022000001000000000_14&qd_k=5dca9b63
06072d513099fa8a6f219fcf&vf=728575a33d24b9ee8926fb1d0d3b68ee&np_tag=nginx_part_t
ag -c copy -bsf:a aac_adtstoasc 中国新歌声第2季_20170825期.mp4
ffmpeg version N-86755-g0780ad9 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --e
nable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --
enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv
--enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-li
bfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug -
-enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enabl
e-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-li
bsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolam
e --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx
 --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable
-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 67.100 / 55. 67.100
  libavcodec     57.100.104 / 57.100.104
  libavformat    57. 75.100 / 57. 75.100
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 95.100 /  6. 95.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
[hls,applehttp @ 003c8920] Opening 'http://data.video.qiyi.com/videos/v0/2017082
6/c1/2a/275a7f911197608d32e2d29c044ab82d.dbts?qdv=1&qypid=768647200_040220000010
00000000_14&start=0&end=2794432&contentlength=2794432&sd=1400&durr=10000&qd_uid=
&qd_vip=0&qd_src=3_31_312&qd_tm=1504015377618&qd_ip=3a1240ea&qd_p=3a1240ea&qd_k=
5dca9b6306072d513099fa8a6f219fcf&qd_sc=393c0a9f43d8953b0f1021e8a10a7d8f' for rea
ding
Input #0, hls,applehttp, from 'http://cache.m.iqiyi.com/mus/207600401/67cae5423e
e1c622238ed2c89c4b6466/afbe8fd3d73448c9//20170826/c1/2a/af451e622b981b00690d4104
255cb036.m3u8?qd_originate=tmts_py&tvid=768647200&bossStatus=0&qd_vip=0&px=&qd_s
rc=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1504015377238&qd_p=3a12
40ea&qd_asc=fd1d4a8958dd02ba14bcea2baf7a939c&qypid=768647200_0402200000100000000
0_14&qd_k=5dca9b6306072d513099fa8a6f219fcf&vf=728575a33d24b9ee8926fb1d0d3b68ee&n
p_tag=nginx_part_tag':
  Duration: 01:41:51.00, start: 1.400000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709)
, 1280x720, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: eac3 ([135][0][0][0] / 0x0087), 48000 Hz, 5.1(side), flt
p, 256 kb/s
    Metadata:
      variant_bitrate : 0
[AVBSFContext @ 0515c840] Codec 'eac3' (86057) is not supported by the bitstream
 filter 'aac_adtstoasc'. Supported codecs are: aac (86018)
Error initializing bitstream filter: aac_adtstoasc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times

直觉上换一个低版本的ffmpeg 应该就好了

可是前段时间下载还没这个提示，

不知道有没有不换ffmpeg版本的办法？

**Comment by rosynirvana** [comment]
这个回复过一次
因为you-get的实现假设所有用ffmpeg下载的都是aac音轨，但这个不是，所以就报错了

**Comment by lki2019** [comment]
http://www.iqiyi.com/v_19rr87fqhk.html

还有这样的

00000_4&start=3060043&end=7300256&hsize=77998&tag=1&v=&contentlength=1643872&qd
uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1504016109728&qd_ip=3a1240ea&qd_p=3a1240ea&
d_k=01873e4eac14a23da565cbe18b218e9e&qd_sc=e5995e45ca02a8405e6ec1c1f13e29b3' fo
 reading
mp4 @ 051e8020] pts has no value
rame= 4631 fps=160 q=-1.0 size=   32000kB time=00:03:33.57 bitrate=1227.4kbits/
hls,applehttp @ 031e8900] Opening 'http://data.video.qiyi.com/videos/v0/2017082
/07/9a/a3aa88b1705bf183ae0f98d338932b8f.ts?qdv=1&qypid=770264500_04022000001000
00000_4&start=4478687&end=9488468&hsize=77998&tag=1&v=&contentlength=1287988&qd
uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1504016109728&qd_ip=3a1240ea&qd_p=3a1240ea&
d_k=01873e4eac14a23da565cbe18b218e9e&qd_sc=e5995e45ca02a8405e6ec1c1f13e29b3' fo
 reading
hls,applehttp @ 031e8900] Failed to open segment of playlist 0
hls,applehttp @ 031e8900] Opening 'http://data.video.qiyi.com/videos/v0/2017082
/07/9a/a3aa88b1705bf183ae0f98d338932b8f.ts?qdv=1&qypid=770264500_04022000001000
00000_4&start=6062422&end=10409445&hsize=77998&tag=1&v=&contentlength=2259760&q
_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1504016109728&qd_ip=3a1240ea&qd_p=3a1240ea
qd_k=01873e4eac14a23da565cbe18b218e9e&qd_sc=e5995e45ca02a8405e6ec1c1f13e29b3' f
r reading


下载的速度很慢···

**Comment by lki2019** [comment]
http://www.iqiyi.com/v_19rr87fqhk.html

还有这样的

00000_4&start=3060043&end=7300256&hsize=77998&tag=1&v=&contentlength=1643872&qd
uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1504016109728&qd_ip=3a1240ea&qd_p=3a1240ea&
d_k=01873e4eac14a23da565cbe18b218e9e&qd_sc=e5995e45ca02a8405e6ec1c1f13e29b3' fo
 reading
mp4 @ 051e8020] pts has no value
rame= 4631 fps=160 q=-1.0 size=   32000kB time=00:03:33.57 bitrate=1227.4kbits/
hls,applehttp @ 031e8900] Opening 'http://data.video.qiyi.com/videos/v0/2017082
/07/9a/a3aa88b1705bf183ae0f98d338932b8f.ts?qdv=1&qypid=770264500_04022000001000
00000_4&start=4478687&end=9488468&hsize=77998&tag=1&v=&contentlength=1287988&qd
uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1504016109728&qd_ip=3a1240ea&qd_p=3a1240ea&
d_k=01873e4eac14a23da565cbe18b218e9e&qd_sc=e5995e45ca02a8405e6ec1c1f13e29b3' fo
 reading
hls,applehttp @ 031e8900] Failed to open segment of playlist 0
hls,applehttp @ 031e8900] Opening 'http://data.video.qiyi.com/videos/v0/2017082
/07/9a/a3aa88b1705bf183ae0f98d338932b8f.ts?qdv=1&qypid=770264500_04022000001000
00000_4&start=6062422&end=10409445&hsize=77998&tag=1&v=&contentlength=2259760&q
_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1504016109728&qd_ip=3a1240ea&qd_p=3a1240ea
qd_k=01873e4eac14a23da565cbe18b218e9e&qd_sc=e5995e45ca02a8405e6ec1c1f13e29b3' f
r reading


下载的速度很慢···

**Comment by ashuai** [comment]
http://www.iqiyi.com/v_19rr8gp6ds.html

Codec 'eac3' (86057) is not supported by the bitstream filter 'aac_adtstoasc'. Supported codecs are: aac (86018)
Error initializing bitstream filter: aac_adtstoasc

eac3? 应该用什么参数？

**Comment by lki2019** [comment]
@ashuai 
修改之后的确 不提示 Codec 'eac3' 

正常下载了

但是不知道这样改了之后 有没有其他影响？

**Comment by rosynirvana** [comment]
没影响
只有一些很老的ffmpeg会在处理某些ts的时候出错

**Comment by yuanchongfu** [comment]
ashuai ：你说的看不懂求帮忙，写写具体步骤。谢谢

**Comment by rosynirvana** [comment]
#813 #1639

**Comment by yuanchongfu** [comment]
Microsoft Windows [版本 10.0.15063]
(c) 2017 Microsoft Corporation。保留所有权利。

C:\Users\Administrator\Desktop>you-get http://www.iqiyi.com/v_19rr910u4s.html?list=19rrl4tiyu
site:                爱奇艺 (Iqiyi)
title:               中国新歌声第2季_20170915期
stream:
    - format:        TD
      container:     m3u8
      video-profile: 720p
      m3u8_url:      http://cache.m.iqiyi.com/mus/207600401/60a35f44fb4b0cd8e94e838857e9aa61/afbe8fd3d73448c9//20170914/40/ad/be3332e1a5f611cb0a6aea660dbb36d1.m3u8?qd_originate=tmts_py&tvid=788466400&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1505371122432&qd_p=7c58bd71&qd_asc=4546eca7c31ff4b92d6ba93d06887d0d&qypid=788466400_04022000001000000000_14&qd_k=b14929dc707992c2d5ecd69eebc9a278&vf=26d3b4307c23608b41effb3ca68b00b6&np_tag=nginx_part_tag
    # download-with: you-get --format=TD [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -i http://cache.m.iqiyi.com/mus/207600401/60a35f44fb4b0cd8e94e838857e9aa61/afbe8fd3d73448c9//20170914/40/ad/be3332e1a5f611cb0a6aea660dbb36d1.m3u8?qd_originate=tmts_py&tvid=788466400&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1505371122432&qd_p=7c58bd71&qd_asc=4546eca7c31ff4b92d6ba93d06887d0d&qypid=788466400_04022000001000000000_14&qd_k=b14929dc707992c2d5ecd69eebc9a278&vf=26d3b4307c23608b41effb3ca68b00b6&np_tag=nginx_part_tag -c copy -bsf:a aac_adtstoasc 中国新歌声第2季_20170915期.mp4
ffmpeg version N-87294-gec1573f Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 75.100 / 55. 75.100
  libavcodec     57.106.101 / 57.106.101
  libavformat    57. 82.100 / 57. 82.100
  libavdevice    57.  8.101 / 57.  8.101
  libavfilter     6.105.100 /  6.105.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
[hls,applehttp @ 00000000006c24a0] Opening 'http://data.video.qiyi.com/videos/v0/20170914/40/ad/4f30aa098b1df2e974a8ab37846d333e.dbts?qdv=1&qypid=788466400_04022000001000000000_14&start=0&end=1779420&contentlength=1779420&sd=1400&durr=8200&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1505371123816&qd_ip=7c58bd71&qd_p=7c58bd71&qd_k=b14929dc707992c2d5ecd69eebc9a278&qd_sc=85ec054d9e0e0741cfa1b3a36f36fb24' for reading
Input #0, hls,applehttp, from 'http://cache.m.iqiyi.com/mus/207600401/60a35f44fb4b0cd8e94e838857e9aa61/afbe8fd3d73448c9//20170914/40/ad/be3332e1a5f611cb0a6aea660dbb36d1.m3u8?qd_originate=tmts_py&tvid=788466400&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1505371122432&qd_p=7c58bd71&qd_asc=4546eca7c31ff4b92d6ba93d06887d0d&qypid=788466400_04022000001000000000_14&qd_k=b14929dc707992c2d5ecd69eebc9a278&vf=26d3b4307c23608b41effb3ca68b00b6&np_tag=nginx_part_tag':
  Duration: 00:11:55.00, start: 1.400000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1280x720, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: eac3 ([135][0][0][0] / 0x0087), 48000 Hz, stereo, fltp, 96 kb/s
    Metadata:
      variant_bitrate : 0
[AVBSFContext @ 00000000006d4480] Codec 'eac3' (86057) is not supported by the bitstream filter 'aac_adtstoasc'. Supported codecs are: aac (86018)
Error initializing bitstream filter: aac_adtstoasc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times

C:\Users\Administrator\Desktop>
