### ISSUE TITLE
期望you-get不远的明天，能开发一个配套的游览器扩展，观看和下载

### ISSUE THREAD

**Issue by lki2019** [soimort/you-get#2313]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

you-get gui工具，在github上面搜了搜就找到一个64位版的gui 我32位所以测试不了效果好不好，

浏览器扩展好像没有吧？
当浏览网页视频的时候，通过扩展调用本地播放器观看，或者一键调用本地you-get下载当前视频

gui吧 市面上 维棠和猎影都可以加载you-get插件，所以gui这个可以忽略，有前面这2个软件也够了

但是浏览器扩展好像没有，

**Comment by lki2019** [comment]
目前我找到一个外部调用you-get和VLC看视频的项目https://github.com/xiaocsl/You-Get-Tool

但是下载好像没有实现，只能吧当前页视频调用you-get传输到VLC里观看

大神可以加工一下，开发一个分支you-get扩展

**Comment by JJJJJJJerk** [comment]
把这个项目使用extractors 用js 写一遍就好了

**Comment by rosynirvana** [comment]
用不着
做好IPC就行了

**Comment by GiriMind** [comment]
https://addons.mozilla.org/zh-CN/firefox/addon/open-with/
Firefox可以用open-with来调用you-get，Chrome也有类似扩展

**Comment by lki2019** [comment]
@GiriMind 谷歌的是哪款？给个地址吧

**Comment by lki2019** [comment]
@GiriMind 谷歌的是哪款？给个地址吧

**Comment by GiriMind** [comment]
https://chrome.google.com/webstore/detail/open-in-external-app/okdopehcdgnellkaldfnaemhbpciplem?hl=zh-CN

**Comment by lki2019** [comment]
@GiriMind  谢谢 我试下

**Comment by GiriMind** [comment]
open-in-external-app确实不能用了（滑稽
https://chrome.google.com/webstore/detail/external-application-butt/bifmfjgpgndemajpeeoiopbeilbaifdo
这个测试可用

**Comment by lki2019** [comment]
@GiriMind 
![qq 20170901092409](https://user-images.githubusercontent.com/30022431/29951773-95c76000-8ef7-11e7-802f-84113a8c3436.png)

尴尬了，不太会用，这样设置？

**Comment by GiriMind** [comment]
可以调用播放器，you-get后面加-p "播放器绝对路径"

**Comment by lki2019** [comment]
![qq 20170901111928](https://user-images.githubusercontent.com/30022431/29954074-aee7387a-8f07-11e7-9ee8-1a37bcc5f830.png)


you-get.exe -p "播放器路径"


![qq 20170901112045](https://user-images.githubusercontent.com/30022431/29954097-dc29212c-8f07-11e7-8d7b-f5b135bb094d.png)


还是提示这个····安装包也安装了

不知道哪里出问题了

还有一键下载的生成目录不可以自己定义么？
默认都到这里了 C:\Users\Administrator\AppData\Local\com.add0n.node

**Comment by GiriMind** [comment]
![default](https://user-images.githubusercontent.com/22651937/29954370-02faca4c-8f0a-11e7-921b-12a94bf3ebe8.jpg)

我是把命令写在一个bat里，这样方便加各种参数
看一般视频的you-get.bat
C:/Python36/python.exe %~dp0you-get-develop/you-get -p "D:/Develop/mpv/mpv/mpv.exe" %1
B站番组的bilibili-bangumi.bat
C:/Python36/python.exe %~dp0you-get-develop/you-get -p "D:/Develop/mpv/mpv/mpv.exe --merge-files --http-header-fields='Referer: http://www.bilibili.com'" %1

**Comment by lki2019** [comment]
C:/Python36/python.exe %~dp0you-get-develop/you-get -p "D:/Develop/mpv/mpv/mpv.exe" %1
B站番组的bilibili-bangumi.bat
C:/Python36/python.exe %~dp0you-get-develop/you-get -p "D:/Develop/mpv/mpv/mpv.exe --merge-files --http-header-fields='Referer: http://www.bilibili.com'" %1


========

B站番组的bilibili-bangumi.bat  这个bat里面是什么 我在里面写什么内容

还有第2行

我直接照抄 把播放器路径换成我的就行了，其他的不用动就行吧？

**Comment by GiriMind** [comment]
https://www.panda.tv/66624 you-get.bat可以，要不你下个mpv？
https://live.bilibili.com/64715 已经下播了

**Comment by lki2019** [comment]
我you-get.bat里

我就放了一句

you-get -p mpv.exe


===================
http://www.acfun.cn/v/ac3880772
 https://v.qq.com/x/page/b0024rch3aq.html
http://www.le.com/ptv/vplay/30383361.html

直播都不行

我大概看了下，好像是自动调用的youtube-dl

因为我也装着youtube-dl py

**Comment by GiriMind** [comment]
mpv加--no-ytdl参数，youtube-dl把token用掉了

**Comment by lki2019** [comment]
![qq 20170901130228](https://user-images.githubusercontent.com/30022431/29955955-3199b456-8f16-11e7-9509-56e526df8a44.png)


![qq 20170901130358](https://user-images.githubusercontent.com/30022431/29955967-468f2f3a-8f16-11e7-91b7-0a6174257efe.png)

还不行··

**Comment by GiriMind** [comment]
you-get -p "mpv.exe --no-ytdl"

**Comment by lki2019** [comment]
一样的提示，如上图····

**Comment by GiriMind** [comment]
错误显示mpv还是调用了youtube-dl
嘛，我这里3个链接都能播放

**Comment by lki2019** [comment]
我卸载，重新装了下扩展，

you-get -p "mpv.exe --no-ytdl"

bat里


然后呢，现在是一个命令行窗口一闪而过就没了

**Comment by GiriMind** [comment]
you-get -p "mpv.exe --no-ytdl" %1
%1是调用bat的第一个参数，表示扩展传过来的URL

**Comment by lki2019** [comment]
十分感谢，正常调用出播放器了 ，

you-get -p "mpv.exe --no-ytdl" %1

一行命令 OK的

@GiriMind 

对了，一键下载下载的视频文件，可以自定义保存到指定目录么？

现在默认在C盘一个很深的目录里，

**Comment by GiriMind** [comment]
you-get -o "指定目录" %1

**Comment by lki2019** [comment]
OK ，明白了 十分感谢

**Comment by lki2019** [comment]
you-get -p "mpv.exe --no-ytdl" %1
you-get -o "D:\下载" %1


这2行命令 我放到bat里

先调出播放器观看，然后我关掉播放器后，会执行第2个下载命令

怎么修改命令可以在播放的同时，又在下载？

边播边下载·的意思

**Comment by GiriMind** [comment]
分开2个bat写，操作2次（滑稽

**Comment by lki2019** [comment]
哈哈，好吧也只能这样了，

其实还有一个延伸的想法，在打开视频页面的时候，点击扩展，自动调出播放器观看的同时有没有办法自动就把当前页面关掉了。这样省资源也省了一个步骤，或者说自动停止加载当前页面的flash播放器出来，当然可以在谷歌浏览器设置里吧flash禁止加载，但是一些时候需要flash 所以直接禁止也不是台方便·


这个想法好弄不？不好弄也就算了，动手点个叉叉···

**Comment by GiriMind** [comment]
![default](https://user-images.githubusercontent.com/22651937/29957105-3e2ed734-8f1e-11e7-9045-d7fb34b58f34.jpg)
 扩展设置里选context menu - on link context，然后在视频列表页面，在视频链接上用鼠标右键打开
我一般是这样用的

**Comment by lki2019** [comment]
OK，懂了 这样就根本不用点进去了，也就没有关闭不关闭的问题了

**Comment by lki2019** [comment]
![qq 20170901141250](https://user-images.githubusercontent.com/30022431/29957419-f23293fa-8f1f-11e7-9c38-4e4641206317.jpg)


B站首页 我圈的红色区域这几个视频，右键 好像无法播放，

下面那些倒是可以，你试试

**Comment by GiriMind** [comment]
B站直播可以直接看，番组会检查referer
mpv加--http-header-fields='Referer: http://www.bilibili.com'参数，参考前面的bilibili-bangumi.bat

**Comment by lki2019** [comment]
这才明白，你最开始回复里bat里为什么要那样写，

原来如此，长知识了，谢谢

**Comment by cnbeining** [comment]
应该加入wiki。
