### ISSUE TITLE
无法下载niconico弹幕

### ISSUE THREAD

**Issue by toorich** [soimort/you-get#2314]
在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:
PS D:\Program Files (x86)\ViDownSoft\ViDown\analyzers> you-get http://www.nicovideo.jp/watch/sm13089137 --debug
User:     huanghou1967@gmail.com
Password:
Logging in...
[DEBUG] get_response: http://www.nicovideo.jp/watch/sm13089137
[DEBUG] get_response: http://flapi.nicovideo.jp/api/getflv?v=sm13089137
[DEBUG] url_info: http://smile-fnl60.nicovideo.jp/smile?m=13089137.11770
Site:       Nicovideo.jp
Title:      とある学区の超男子寮 - ニコニコ動画
Type:       MPEG-4 video (video/mp4)
Size:       26.07 MiB (27337778 Bytes)

Skipping .\とある学区の超男子寮 - ニコニコ動画.mp4: file already exists
（视频之前下载完了）
如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> http://www.nicovideo.jp/watch/sm13089137 ，能下载视频，但下载不了弹幕
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
dup #100
