### ISSUE TITLE
风行网下载的视频全部一样

### ISSUE THREAD

**Issue by flagang** [soimort/you-get#2315]
例如：you-get http://www.fun.tv/vplay/g-302555/
总共三集，虽然抽取的MP4地址不一样，但是下载下来后三个视频是同一个视频。

**Comment by rosynirvana** [comment]
风行的extractor失效了很久了

**Comment by rosynirvana** [comment]
close #1435 #1304 #1184 #1039 #1004

The algo is rather trivial but a magic list must be fetched from obfuscated js. Not in the near future by me.

**Comment by denobisipsis** [comment]
You should read the magic list (4 codes) from these 2 javascripts (decoding both from eval(packed)): mcore and mtool. Search for .mozEcName.push and you'll find them.

Then every code has 2 parts: the last which is the array index and the number. For example:

"80", "5b1", "cd3", "3b2"

so keys:

key[0]=8
key[1]=5b=91
key[2]=3b=59
key[3]=cd=205

then apply the algorithm for every infohash and token, beginning from position 2.

Token for last mp4 url is base64 of decoded token, mp4 path is decoded infohash

Example:

http://m.fun.tv/vplay/?vid=8966429

keys array(4) { [0]=> string(3) "f90" [1]=> string(3) "7f1" [2]=> string(3) "2a3" [3]=> string(3) "a72" } 

Then

reordered keys array(4) { [0]=> int(249) [1]=> int(127) [3]=> int(42) [2]=> int(167) }


for sdvd h.264

infohash 219ukBqXpmgyZV3JzzT7fSYhJXjOYYS7GhRPcCde/NEldNvXJHqd6Q4EY=
token 21yXGosPu1MU9J7hdOkd374Ov+AtdM63FEqNtTsR1CpeTd60fDYMf6uHvkozQbyXc+9MS7Xng7780=

decoded infohash ED894B591CAB870BC460E609EBE023C405343C00
decoded token 8A88672ECCA541CEEA3D9BE7EF27C79CB1D71F26_mweb_1504515623

Then
http://58.255.172.44/play/ED894B591CAB870BC460E609EBE023C405343C00/13168613.mp4?token=OEE4ODY3MkVDQ0E1NDFDRUVBM0Q5QkU3RUYyN0M3OUNCMUQ3MUYyNl9td2ViXzE1MDQ1MTU2MjM%3D&user_id=0&user_token=&vf=MCwxQjU1QQ%3D%3D&app_code=mweb
-

**Comment by x28622930** [comment]
@denobisipsis 风行算法你说的不太懂，求PHP版的解密算法。。

**Comment by denobisipsis** [comment]
function o(t) {
    for (var e = "", i = 0; i < t.length;) {
        var o = t.charCodeAt(i++),
            r = t.charCodeAt(i++);
        if (e += a(n(o, r).z1), e += a(n(o, r).z2), i == t.length - 1) {
            e += a(t.charCodeAt(i));
            break
        }
    }
    return e
}

function n(t, e) {
    var i = document.mozEcName,
        o = 256,
        n = [0, 0, 0, 0],
        a = [],
        r = {};
    $.each(i, function(t, e) {
        r[e] || (r[e] = !0, a.push(e))
    });
    for (var s = 0, d = a.length; d > s; s++) { 
        n[a[s].substr(a[s].length - 1)] = parseInt(a[s].substr(0, a[s].length - 1), 16)
    }; 
    return {
        z1: (t * n[0] + e * n[2]) % o,
        z2: (t * n[1] + e * n[3]) % o
    }
}

n is the array of keys, t and e charcodes of the base64_Decode of the infohash or token

**Comment by rosynirvana** [comment]
如果打算用PHP实现，问题是从uglify的js里找到```mozEcName```的值，token本身的解密是非常trivial的东西

**Comment by denobisipsis** [comment]
in html of video, for example http://m.fun.tv/vplay/?vid=8966429

take these js's

<script type="text/javascript" charset="utf-8" src="/static/js/v12/pkg/mcore_v12_d54636928.js"></script>
--
  | <script type="text/javascript" charset="utf-8" src="/static/js/v12/pkg/mtool_v12_27d0c4739.js"></script>

They are packed. So unpack them and search 

.mozEcName.push

you'll find the 4 codes

**Comment by rosynirvana** [comment]
It's volatile.

**Comment by denobisipsis** [comment]
Keys change every time, but you can catch them unpacking the js's, which is easy to code

**Comment by denobisipsis** [comment]
try this to unpack, passing the entire js packed

$unpacked=unpackeval::go(file_get_contents("http://m.fun.tv/static/js/v12/pkg/mcore_v12_d54636928.js"));
class unpackeval
{
function xtract($file,$begin,$first,$second,$last="")
	{
	$p1=strpos($file,$begin,$last);
	$p2=strpos($file,$first,$p1+strlen($begin)-1); 
	$p3=strpos($file,$second,$p2+strlen($first));
	return substr($file,$p2+strlen($first),$p3-$p2-strlen($first));
	}
	
function e($c,$a)
	{
	if ($c<$a) $x=""; else $x=unpackeval::e(intval($c/$a),$a);
	
	$d=$c % $a;
	
	if ($d>35) $x.=chr($d+29);
	else	   $x.=base_convert($d,10,36);
	
	return $x;
	}
			
function go($script)
	{
	$res=substr(unpackeval::xtract($script,"val(functio","(",")"),0,1)."}(";	
	
	$script=str_replace("'",'"',unpackeval::xtract($script,"val(functio","return $res",".split("));
	$script=str_replace('\"','"',$script);
	
	$t=explode('"',$script);
	$t=$t[sizeof($t)-2];
	
	$script=explode(",\"$t\"",$script)[0];
	
	$n=explode(",",$script);
	
	$a=$n[sizeof($n)-1];
	$c=$n[sizeof($n)-2];

	$m=explode(",$c,$a",$script)[0];
			
	$t=explode('|',$t);
	
	if ($c>0 and $a>0)
		{	
		for ($k=$a;$k>=0;$k--)
			{
			$f=unpackeval::e($k,$c);
			
			if ($t[$k])
			$m=preg_replace("/\b".$f."\b/", $t[$k],$m);
			}
		}
	return $m;
	}
}
