### ISSUE TITLE
希望推出GUI图形界面

### ISSUE THREAD

**Issue by thisisjin** [soimort/you-get#2317]
> [em。。今天接触了you-get，确实强大。
但是比较尬意的一点就是没有图形界面好难受。
我对于cmd界面的能力十分的，，应该说是差劲吧。 
之前都是在用youtube-dl gui,感觉图形界面的操作来说要方便不少，
然后我又在github找了下相关内容。没有找到合适的,所以来这里提出一个issue,
真的希望有一个windows 的图形界面的you-get啊！]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
https://github.com/soimort/you-get/projects
是有这种计划
但是估计项目本身没人会去做
因为没什么用

**Comment by lki2019** [comment]
you-get有gui 不过只有64位的

**Comment by lki2019** [comment]
https://github.com/ingbyr/GUI-YouGet/releases  64位

我是32位  所以测试不了好用不好用 

其实还有个jar的  但是界面很简陋

**Comment by lki2019** [comment]
https://github.com/bajingxiaozi/YougetGUI/releases jar版的

**Comment by thisisjin** [comment]
@lki2019 我有尝试你这个。但是貌似没用?
我等下再试试

**Comment by thisisjin** [comment]
@rosynirvana 感觉像一些熟悉使用CMD命令行的人来说。GUI可能是没多用把。
但是我这种小白之类的。。有个GUI会方便很多。
you-get真的很强大

**Comment by thisisjin** [comment]
@lki2019 这个64位的我又试验了一遍。下载视频无效。  可能是you-get核心文件没有更新还是怎么回事。
现在貌似没有有效的GUI版本吧

**Comment by thisisjin** [comment]
@lki2019 下面是我用的那个0.12 win的日志

Sep04 2017 00:01:48 main_window.py[line:124] DEBUG >>> 
Sep04 2017 00:01:48 main_window.py[line:126] DEBUG >>> remote version is 0.1.2
Sep04 2017 00:02:36 main_window.py[line:76] DEBUG >>> http://v.youku.com/v_show/id_XMzAwNDk2NjgwOA==.html?spm=a2h0k.8191407.0.0&from=s1.8-1-1.1
Sep04 2017 00:02:36 download_thread.py[line:39] DEBUG >>> disable the proxy
Sep04 2017 00:02:36 common.py[line:345] DEBUG >>> get_content: http://play.youku.com/play/get.json?vid=XMzAwNDk2NjgwOA==&ct=10
Sep04 2017 00:03:03 main_window.py[line:124] DEBUG >>> 
Sep04 2017 00:03:03 main_window.py[line:126] DEBUG >>> remote version is 0.1.2
Sep04 2017 00:03:39 download_thread.py[line:49] ERROR >>> HTTP Error 502: Bad Gateway
Traceback (most recent call last):
  File "app\util\download_thread.py", line 45, in run
  File "app\you_get\common.py", line 1202, in download_main
  File "app\you_get\common.py", line 1470, in any_download
  File "app\you_get\extractor.py", line 41, in download_by_url
  File "app\you_get\extractors\youku.py", line 176, in prepare
  File "app\you_get\common.py", line 352, in get_content
  File "app\you_get\common.py", line 328, in urlopen_with_retry
  File "urllib\request.py", line 163, in urlopen
  File "urllib\request.py", line 472, in open
  File "urllib\request.py", line 582, in http_response
  File "urllib\request.py", line 510, in error
  File "urllib\request.py", line 444, in _call_chain
  File "urllib\request.py", line 590, in http_error_default
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
Sep04 2017 00:03:39 main_window.py[line:83] DEBUG >>> finish_get_info: False
Sep04 2017 00:13:40 main_window.py[line:76] DEBUG >>> http://v.youku.com/v_show/id_XMzAwNDk2NjgwOA==.html?spm=a2h0k.8191407.0.0&from=s1.8-1-1.1
Sep04 2017 00:13:40 download_thread.py[line:39] DEBUG >>> disable the proxy
Sep04 2017 00:13:40 common.py[line:345] DEBUG >>> get_content: http://play.youku.com/play/get.json?vid=XMzAwNDk2NjgwOA==&ct=10
Sep04 2017 00:14:43 download_thread.py[line:49] ERROR >>> HTTP Error 502: Bad Gateway
Traceback (most recent call last):
  File "app\util\download_thread.py", line 45, in run
  File "app\you_get\common.py", line 1202, in download_main
  File "app\you_get\common.py", line 1470, in any_download
  File "app\you_get\extractor.py", line 41, in download_by_url
  File "app\you_get\extractors\youku.py", line 176, in prepare
  File "app\you_get\common.py", line 352, in get_content
  File "app\you_get\common.py", line 328, in urlopen_with_retry
  File "urllib\request.py", line 163, in urlopen
  File "urllib\request.py", line 472, in open
  File "urllib\request.py", line 582, in http_response
  File "urllib\request.py", line 510, in error
  File "urllib\request.py", line 444, in _call_chain
  File "urllib\request.py", line 590, in http_error_default
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
Sep04 2017 00:14:43 main_window.py[line:83] DEBUG >>> finish_get_info: False

**Comment by rosynirvana** [comment]
说GUI没用是因为主要操作都是从浏览器地址栏复制一个url
这个url贴到一个传统的gui窗口，或是贴到终端模拟器里，差别真不大，只差几个字母的键盘输入
为了省这一点输入增加的debug负担太重

比如cli的current dic一直显示在行首而gui是隐藏的，为了解决这个gui上必须随时提供一个写入路径，再加上win那种没人搞得懂的权限管理……
最终这个gui做出来学习曲线会比cli更陡峭

再加上you-get本身是整体的cli tool设计，并不是很多人想象的那样前端加上一个库。很多部分是直接写到stdout，像process bar那几百行代码用到GUI里又要完全重写

最后也不存在一种容易部署的跨平台的GUI实现方法，据我所知这项目的用户除了win OSX linux distro之外还有用android的。you-get现在提供的部署方法，一个win可执行一个osx homebrew引出的麻烦已经够多了，再加上一个GUI……

从开发者的角度来看正确思路是让浏览器和you-get之间的IPC绕过粘贴板，you-get这端实现一个daemon并且提供接口，浏览器端做个插件把url传出去。虽说几百行代码应该能实现，但确实没什么余力去做。

**Comment by thisisjin** [comment]
@rosynirvana    虽然看不很懂。。应该也大致了解了。 
我多熟悉下应该就没问题，反正操作也很简便

**Comment by thisisjin** [comment]
@rosynirvana   有一些疑问想请教下
例如通过代理下载Youtube， 
此命令"you-get -x 127.0.0.1:8087 'https://www.youtube.com/watch?v=jNQXAC9IVRw'" 中的8087端口就是对应自己的代理端口嘛，比如sock5是1080, 就将其改变为1080？
第二个疑问。我想在选择清晰度。也就是使用了"-i"获取视频信息后，再想通过代理来下载相应选择的视频，。命令行该如何做呢。 假如要选择-format hd2 是"you-get -x 127.0.0.1:8087 
-format hd2 https://www.youtube.com/watch?v=jNQXAC9IVRw"  这样来执行嘛？  
第三个，如果在选择清晰度，走代理的情况下，再让他下载到特定地址，那个“-o 文件路径”应该加在哪个位置?

麻烦解答下我的疑问

**Comment by rosynirvana** [comment]
-x指定http代理地址，不是socks代理
不建议非开发者直接使用socks代理，建议使用privoxy之类的软件部署一个中间的http代理，现在众多ss client也直接包含了privoxy
如果想要直接使用socks代理，要先给py环境安装pysocks包，然后用-s指定socks代理地址

-F hd2

加在哪里无所谓，现在的实现里flag的次序没有要求，但是不建议使用-o，用cd切换到目标目录然后用默认的当前路径可以减少一些问题。最后winnt 6和以上版本禁止写入到盘符根目录是很常见的或许应该注意一下

**Comment by Axl2017** [comment]
不知道楼主是不是需要这样的效果：把地址贴到输入框，点击按钮一键下载
这样的话，可以考虑在GUI里面调用系统命令（加一个壳）
也就相当于免去输入you-get 这几个字而已

**Comment by thisisjin** [comment]
@ @Axl2017 差不多是这个意思，不过现在慢慢熟悉了也没问题拉。

**Comment by thisisjin** [comment]
@rosynirvana   em。。  看不太懂你给出的建议。。
我去主页翻了下用户手册，没看到除-o之外的设置路径的说明
麻烦你详细说明下“cd切换到目标目录然后是默认当前路径”这个意思。
拜托了。

**Comment by lki2019** [comment]
https://github.com/soimort/you-get/issues/2313 也许这个 比gui更实用

**Comment by thisisjin** [comment]
@rosynirvana 另外。 想问下，现在 -p 调用potplayer看视频还有效嘛。
需要去potplayer目录下执行
you-get -p potplayermini64.exe 视频链接
来实行嘛。
我用此命令看youku得到如下反应
F:\You-get>you-get -p D:\PotPlayer\PotPlayerMini64.exe http://v.youku.com/v_show/id_XMzAwNTM4NTE1Mg==.html?spm=a2hww.20023042.m_223465.5~5~5~5!2~5~5~A&f=50926040
site:                优酷 (Youku)
title:               男子突然钻车底碰瓷 车上女子吓得尖叫
stream:
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          6.2 MiB (6456491 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMzAwNTM4NTE1Mg%3D%3D&type=mp4&ups_client_netip=218.77.74.153&ups_ts=1504528195&utid=QjU0EokfkmQCAdpNSpkn7dfR&ccode=0401&psid=091102c642223a2cddf33f1f527f8cdc&duration=64&expire=18000&ups_key=2916ec759c9162048e4df85001ca8fd8
    # download-with: you-get --format=mp4 [URL]

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
DNS 服务器对区域没有权威。

**Comment by thisisjin** [comment]
@lki2019 好的，谢谢。我去看看

**Comment by lki2019** [comment]
![111](https://user-images.githubusercontent.com/30022431/30026756-e37ad2d0-91b0-11e7-86a4-016d261989b3.jpg)



<pre><code>
you-get -p PotPlayerMini.exe http://v.youku.com/v_show/id_XMzAwNTM4NTE1Mg==.html?spm=a2hww.20023042.m_223465.5~5~5~5!2~5~5~A&f=50926040
<pre><code>


正常调用，

播放器在环境变量里···
you-get版本是最新···

**Comment by thisisjin** [comment]
@lki2019 我在potplayer目录里执行你的这个指令可以播放，
但是如果CMD没在potplayer里的话，  用绝对路径 D:/POTPLAYER/POTPLAYERMINI64.EXE 貌似会播放失败， 

啊，还有，你给我的哪个issue链接， 如果bat里的命令是"you-get -o "D:\下载" %1"
如何去选择分辨率呢
