### ISSUE TITLE
如何把解析结果输出到指定文件里

### ISSUE THREAD

**Issue by zuishizhi** [soimort/you-get#2318]
比如我解析出视频的信息，想输出到指定文件里，而不是直接显示在命令行中，用什么指令可以实现呢？

**Comment by lki2019** [comment]
you-get -di http://v.youku.com/v_show/id_XMzAwMDQyMzEwMA==.html >e:\1.txt

[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMzAwMDQyMzEwMA==&cc
ode=0401&client_ip=192.168.1.1&utid=zZkzEt7bCRQCAToSQOqdJGox&client_ts=150448828
8

**Comment by lamlam123tld3** [comment]
just pipe it out to a specified file

**Comment by thisisjin** [comment]
你拖一个cmd到你想要的下载位置，
然后执行you-get命令即可。
