### ISSUE TITLE
请问能不能把歪歪网站下载视频支持一下！

### ISSUE THREAD

**Issue by fanmli** [soimort/you-get#2320]
例如：http://www.yy.com/x/15012_147125102_54880976_1504611031651
http://www.yy.com/x/15012_147125102_54880976_1504265354742
请问能不能支持歪歪视频的下载？

**Comment by rosynirvana** [comment]
#1846

**Comment by lki2019** [comment]
YY。com的确是个很主流的直播站 ，希望可以早点支持

**Comment by stevezhou6** [comment]
强烈赞成支持yy
