### ISSUE TITLE
新手小白，贡献代码问题

### ISSUE THREAD

**Issue by numberwolf** [soimort/you-get#2321]
updateBilibiliFromMyLuaScript #2262
这个显示passed了，但是没有看到最新代码里有更改，是否还需要做其他操作呢？

**Comment by rosynirvana** [comment]
首先您应该举出一个patch的适用范围
对于这个patch来说，就是从url中读bangumi id会出错，必须从页面里读取的情况

然后patch应该确保最小更改
这个pull request里不应该出现两次commit

最后这样写也不怎么合理，如果确定有时候从url中读bangumi id是错误的，那就不需要从url中读一个，从页面中读一个，进行比较

pass是TI检测能不能通过几项测试，基本上可以不用管

**Comment by numberwolf** [comment]
好的，了解啦，那下次我如果传一个新站的嗅探，是不是这边审核通过是自动merge的呢？

**Comment by rosynirvana** [comment]
不是，merge都是手动的

**Comment by numberwolf** [comment]
好的 谢谢啦
