### ISSUE TITLE
Can't get stream from youku

### ISSUE THREAD

**Issue by xboxp** [soimort/you-get#2322]
Please make sure these boxes are checked before submitting your issue – thank you!

- [*] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [*] Your `you-get` is up-to-date.
- [*] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [*] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [*] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk5NjQ0NjQ3Mg==&ccode=0401&client_ip=192.168.1.1&utid=RMY2Ev8SNAcCAXt9JeaVsegr&client_ts=1504696388
you-get: 客户端无权播放,201
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

**Comment by Blaok** [comment]
I am encountering the same issue! Previous fixes don't seem to work.

**Comment by dashenniuyiniu** [comment]
我也是下载优酷的时候说“客户端无权播放，201。用这个pip3 install --upgrade https://github.com/soimort/you-get/archive/develop.zip升级之后也还是201错误
