### ISSUE TITLE
无法更新you-get v0.4.775 is the latest version available based on your source(s).

### ISSUE THREAD

**Issue by HJH12315** [soimort/you-get#2323]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
C:\WINDOWS\system32>pip3 install --upgrade you-get
Requirement already up-to-date: you-get in e:\python\python36-32\lib\site-packages

C:\WINDOWS\system32>choco upgrade you-get
Chocolatey v0.10.8
Upgrading the following packages:
you-get
By upgrading you accept licenses for the packages.
you-get v0.4.775 is the latest version available based on your source(s).

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
一个包不该用两个package manager去管理
用choco是不建议的，例如在你的这个例子里，0.4.803这个release没在choco上发布

**Comment by HJH12315** [comment]
我想更新到最新0.4.803，可我用这两个命令都提示我0.4.775最新，我该具体怎么更新呢（Win10）？

**Comment by rosynirvana** [comment]
你怎么从pip3的log看出是0.4.775的？

个人建议是整个删掉
装python3
用pip3装you-get

**Comment by HJH12315** [comment]
我用you-get -V看版本号的
问一下如何全部删除you-get？
刚刚试了下载Release的最新版本包，不太会用更新。
C:\Users\lenovo\master\you-get-master>pip install you-get-0.4.803.tar.gz
Processing c:\users\lenovo\master\you-get-master\you-get-0.4.803.tar.gz
  Requirement already satisfied (use --upgrade to upgrade): you-get==0.4.803 from file:///C:/Users/lenovo/master/you-get-master/you-get-0.4.803.tar.gz in e:\python\python36-32\lib\site-packages

**Comment by rosynirvana** [comment]
把choco安装的python3整个删掉

**Comment by HJH12315** [comment]
多谢，用命令choco uninstall you-get 然后在运行you-get -V就是最新版本了。
并且加上cookies可以优酷会员下载，之前的0.4.775不行。
再次谢谢作者~
