### ISSUE TITLE
优酷新问题

### ISSUE THREAD

**Issue by huanghe2015** [soimort/you-get#2326]
在提交前，请确保您已经检查了以下内容!

- [ √] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ √] 您的`you-get`为最新版.
- [√ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [√ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [√ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
D:\ZWB\我的文档\我的视频\教程\ROM适配>you-get -V
you-get: version 0.4.803, a tiny downloader that scrapes the web.

D:\ZWB\我的文档\我的视频\教程\ROM适配>you-get -d -o D:\ZWB\我的文档\我的视频\教
程\ROM适配 http://v.youku.com/v_show/id_XODE0MjIyOTky.html?spm=a2hzp.8253869.0.0

[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XODE0MjIyOTky&ccode=
0401&client_ip=192.168.1.1&utid=Lfc3EjmrzVACAdyyBLgPTmsY&client_ts=1504774447
you-get: 客户端无权播放,201
```

**Comment by hnliyuan** [comment]
the same to me .

**Comment by sanmeiji** [comment]
要用-c加载包含登录信息cookie吧，版本相同，加载cookie后会员视频可正常下载

**Comment by rosynirvana** [comment]
youku api现在的封禁似乎是基于UA和IP的综合统计
麻烦拿去滥用的自己改个随机UA
repo里一直改UA好麻烦的

**Comment by pxia** [comment]
优酷至于不至于。。。要不要默认成优酷客户端的ua？

**Comment by rosynirvana** [comment]
https://github.com/soimort/you-get/commit/ca5e07cfa12115592b961d5a4b5760d1eb44e7de

**Comment by pxia** [comment]
这个commit是从iOS Safari的ua换成了macOS Safari的ua吧？我刚抓了一个iOS客户端的UA：
`%E4%BC%98%E9%85%B7/20316549 CFNetwork/811.5.4 Darwin/16.7.0`
