### ISSUE TITLE
有什么参数是 you-get + 参数 + 视频链接 返回这个链接的MP4或者m3u8等的播放地址吗？

### ISSUE THREAD

**Issue by kakashilw** [soimort/you-get#2330]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ √] ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [  √]] Your `you-get` is up-to-date.
- [ √] ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ √] ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [  √]] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [  √] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [  √] 您的`you-get`为最新版.
- [  √] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ √ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ √ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]

有什么参数是 you-get + 参数 + 视频链接 返回这个链接的MP4或者m3u8等的播放地址吗？

比如 you-get + 参数 + youku url，返回类似这种格式的 http://k.youku.com/player/getFlvPath/sid/050484652156112923be1/st/mp4/fileid/030008010054003E34FF5819559136286C9767-461D-FD39-3EBF-52EFD0987207?k=198c54b4265829c7282ca60a&hd=1&myp=0&ts=211&ctype=12&ev=1&token=0509&oip=1928717765&ep=cieUHkGJUMsC5CbZiT8bbi7hJiIOXP4J9h%2BFidJjALshTOi%2FmkvSw%2BvGS%2FdDH%2FwceyMFFun5raPu%0AbUYTYfRFqBwQqTqrMPrji4KV5ahRseZ0ZhA%2Bdc%2FXs1SeRjD4&ccode=0501&duration=210&expire=18000&psid=fc41546f920b73f2d424451f96936a0f&ups_client_netip=114.245.229.197&ups_ts=1504846521&ups_userid=&utid=PdPhDWSLl18CAXL140SrlZWo&vid=XNzYzNzQxODA0&vkey=A0716279810a6dae7c83125625aef90ef

> [舔 :icecream:!]

**Comment by mogu1121** [comment]
you-get -u url

**Comment by kakashilw** [comment]
you-get -u 之后返回 you-get: 客户端无权播放,201

**Comment by pxia** [comment]
用develop branch

**Comment by kakashilw** [comment]
多谢2位的指教，已经可以了。。不过现在有个问题，就是获取到的url播放链接里面都有ups_client_netip=xxx.xxx.xxx.xxx 这个参数，因为是用服务器去获取，都是同一个ip，这样用久了会不会被youku发现哇，有没有办法获取播放链接的时候，用一个随机的ip去获取呢？

**Comment by rosynirvana** [comment]
随机IP?
基于TCP只能用代理
