### ISSUE TITLE
fantasy.tv checks referer

### ISSUE THREAD

**Issue by rosynirvana** [soimort/you-get#2331]
@soimort-bot test https://www.fantasy.tv/video/play.html?tvId=87293&channelId=146

**Comment by rosynirvana** [comment]
close via 9c55f93

**Comment by soimort** [comment]
@soimort-bot test https://www.fantasy.tv/video/play.html?tvId=87293&channelId=146

**Comment by soimort** [comment]
I guess this is now fixed.
