### ISSUE TITLE
能否获取 YouTube 含音频的 1080P 视频下载地址？

### ISSUE THREAD

**Issue by microka** [soimort/you-get#2335]
> you-get -x 127.0.0.1:1080 -u --itag=137 https://www.youtube.com/watch?v=AwFP-RrU4Ss
site:                YouTube
title:               Taylor Swift - Look What You Made Me Do歌曲介紹&MV故事解析
stream:
    - itag:          137
      container:     mp4
      quality:       1920x1080
      size:          190.6 MiB (199877431 bytes)
    # download-with: you-get --itag=137 [URL]

> Real
 URLs:
https://r1---sn-oguesnzs.googlevideo.com/videoplayback?mn=sn-oguesnzs&mm=31&id=o-AMGkRHFeyv7Puyn857sgsqyABLQ-snyFvCAMan3eLECa&mv=m&ip=xx.xx.xx.xx&key=yt6&gir=yes&mt=1505058963&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ms=au&requiressl=yes&lmt=1505008500118017&ei=F2G1WZrsMMLU4gLFxpSYDQ&expire=1505080695&mime=video%2Fmp4&itag=137&pl=26&dur=684.049&source=youtube&keepalive=yes&clen=189011489&ipbits=0&initcwndbps=4617500&signature=548A0C9E82E65AD840BFA51497B49B49FEC60C17.8A4A1D826B4353B4ACA07367A6EC5C3C78FB7699&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&ratebypass=yes
https://r1---sn-oguesnzs.googlevideo.com/videoplayback?mn=sn-oguesnzs&mm=31&id=o-AMGkRHFeyv7Puyn857sgsqyABLQ-snyFvCAMan3eLECa&mv=m&ip=xx.xx.xx.xx&key=yt6&gir=yes&mt=1505058963&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ms=au&requiressl=yes&lmt=1505008687848247&ei=F2G1WZrsMMLU4gLFxpSYDQ&expire=1505080695&mime=audio%2Fmp4&itag=140&pl=26&dur=684.106&source=youtube&keepalive=yes&clen=10865942&ipbits=0&initcwndbps=4617500&signature=2ABB6FBB5351A9E77122C6955AC5BCF66E2E4553.5A731F3BD845582A9D25E2AAEC9ED219D907BCB7&ratebypass=yes

众所周知目前 YouTube 1080P 格式的视频是音视频分开的，但通过 IDM 对 https://www.youtube.com/watch?v=AwFP-RrU4Ss 该链接进行解析，得到的 1080P 下载链接为
`https://r1---sn-oguesnzs.googlevideo.com/videoplayback?gir=yes&initcwndbps=4595000&ipbits=0&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&expire=1505080426&mime=video%2Fmp4&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&id=o-ALwgjvbEATc_dUmEKq29JbQ9LHKM2zDPHR20HjTo2Vf5&source=youtube&dur=684.049&ip=xx.xx.xx.xx&keepalive=yes&itag=137&lmt=1505008500118017&requiressl=yes&mt=1505058682&mv=m&pl=26&ei=CmC1WZzhBMG94gL0uKXgBA&ms=au&signature=31F3CAF0224B3393B9713167DAFCFC103F828CEC.578324BBB9FED2BE25B18822758231EE854D48D3&clen=189011489&key=yt6&mm=31&mn=sn-oguesnzs`
下载回来是已经内嵌了音频文件的 1080P MP4 文件，请问 you-get 能否针对该类情况进行优化，增加探测内嵌音频文件的 1080P MP4 视频下载链接。

**Comment by rosynirvana** [comment]
装ffmpeg，会自动合并

**Comment by microka** [comment]
@rosynirvana 现在不是讨论合并的问题，是希望能够获取 YouTube 原始是音视频合一的文件。

**Comment by jyuan15** [comment]
IDM下载1080P仍然是合并的，楼主发的那个链接视频含音轨大小是191M，而IDM显示的只有180M，这是视频流大小，还是要合并音轨。

![2017-09-11_173058](https://user-images.githubusercontent.com/12642186/30268266-c200f62c-9717-11e7-830b-cada6910f747.jpg)

**Comment by soimort** [comment]
同上。
