### ISSUE TITLE
为什么acfun单独用下载地址不能不能下载？

### ISSUE THREAD

**Issue by zuishizhi** [soimort/you-get#2339]
单独用给的下载地址不能下载视频？是不是需要设置头部信息才可以呢？

**Comment by rosynirvana** [comment]
你是说-u or --json得到的地址不能用外部工具下载吗？

**Comment by zuishizhi** [comment]
是啊 比如说这个地址

http://player.acfun.cn/route_mp4?uid=ACFUN&timestamp=1505145536&fid=0100400204000059B60E6100010000880000000000-0000-0000-01A2-94A800000000.mp4&ns=video.acfun.cn&ran=10100791313676e7c6b64c537f5b41150cb687e130c8rpcx12125p77p226p7bc2e07baac8498&vid=59b60e4b0cf23b9f0a25596d&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct59b6b2c00cf2ac5958fe31d7

**Comment by zuishizhi** [comment]
但是用you-get是可以下载下来的

**Comment by rosynirvana** [comment]
HTTP header user-agent中不能含moziila，也就是绝大多数现代浏览器的UA都不行
```
curl -I http://player.acfun.cn/route_mp4\?uid\=ACFUN\&timestamp\=1505145536\&fid\=0100400204000059B60E6100010000880000000000-0000-0000-01A2-94A800000000.mp4\&ns\=video.acfun.cn\&ran\=10100791313676e7c6b64c537f5b41150cb687e130c8rpcx12125p77p226p7bc2e07baac8498\&vid\=59b60e4b0cf23b9f0a25596d\&customer_id\=5859fdaee4b0eaf5dd325b91\&sign\=ct59b6b2c00cf2ac5958fe31d7 -L -H 'user-agent: Mozilla'
HTTP/1.1 302 Found
Server: openresty
Date: Mon, 11 Sep 2017 16:03:43 GMT
Content-Type: text/plain;charset=UTF-8
Content-Length: 110
Connection: keep-alive
location: http://video.acfun.cn/0100400204000059B60E6100010000880000000000-0000-0000-01A2-94A800000000.mp4?customer_id=5859fdaee4b0eaf5dd325b91&auth_key=1505154823-10100791313676e7c6b64c537f5b41150cb687e130c8rpcx12125p77p226p7bc2e07baac8498-ACFUN-028c10db35af1af7d99abfc75ba25cf1

HTTP/1.1 403 Forbidden
Server: Tengine
Date: Mon, 11 Sep 2017 16:03:43 GMT
Content-Type: video/mp4
Connection: keep-alive
X-Tengine-Error: denied by req auth: auth center check fail
Via: cache1.cn606[,0]
Timing-Allow-Origin: *
EagleId: 9dff1c4115051458236156333e
```
注意这行 X-Tengine-Error: denied by req auth: auth center check fail

python urllib或者curl的默认UA都是可以的

**Comment by zuishizhi** [comment]
好的，我明天试试看，谢谢😃

**Comment by lki2019** [comment]
我测试了下


比如这个地址：http://www.acfun.cn/v/ac3880772

C:\Users\Administrator>you-get -di http://www.acfun.cn/v/ac3880772
[DEBUG] get_content: http://www.acfun.cn/v/ac3880772
[DEBUG] get_content: http://www.acfun.tv/video/getVideo.aspx?id=5461277
[DEBUG] get_content: http://player.acfun.cn/flash_data?vid=597966e30cf2075329cbd
0a7&ct=85&ev=3&sign=1_1505146917_4b3b1a9d764ebf9ca9e299e0ca7173c1&time=150514678
5969
[DEBUG] url_info: http://player.acfun.cn/route_mp4?uid=ACFUN&timestamp=150514691
7&fid=01004002040000597966F0000100004A0000000000-0000-0000-0192-44DA00000000.mp4
&ns=video.acfun.cn&ran=1010079145171507a57d7170299e287b946e124f4832rpcx1258p18p6
4p5497a587a2f6468&vid=597966e30cf2075329cbd0a7&customer_id=5859fdaee4b0eaf5dd325
b91&sign=ct59b6b8250cf24964f6af6590
Site:       AcFun.tv
Title:      张一山升级红烧肉男神，耍帅不过三秒。。。。。。 - 酷哥撩热剧
Type:       MPEG-4 video (video/mp4)
Size:       27.82 MiB (29172631 Bytes)


复制解析出来的地址，添加到IDM 迅雷 QQ旋风之类的下载工具里都无法下载

打开这个视频地址，IDM嗅探出来的地址 直接点下载正常下载

http://video.acfun.cn/01004002040000597966F0000100004A0000000000-0000-0000-0192-44DA00000000.mp4?customer_id=5859fdaee4b0eaf5dd325b91&start=0.0&auth_key=1505156034-10100791462994a935bedf47c2a4ba28418546935e3crpcx1258p18p64p65473c116752225-ACFUN-e46ddb82544db2e03c597488472cab30


我复制这个地址 从新添加到IDM，无法下载。，

ffmpeg -user_agent "curl/7.51.0" -i "http://player.acfun.cn/route_mp4?uid=ACFUN&timestamp=1505146917&fid=01004002040000597966F0000100004A0000000000-0000-0000-0192-44DA00000000.mp4&ns=video.acfun.cn&ran=1010079145171507a57d7170299e287b946e124f4832rpcx1258p18p64p5497a587a2f6468&vid=597966e30cf2075329cbd0a7&customer_id=5859fdaee4b0eaf5dd325b91&sign=ct59b6b8250cf24964f6af6590" -c copy oooo.mp4

正常下载·····
