### ISSUE TITLE
建议：优酷播单下载时，建议加入自动重试功能！

### ISSUE THREAD

**Issue by neatgz** [soimort/you-get#2341]
昨天晚上睡觉前，
开始下载一个优酷播单（某电视剧），使用命令
you-get -o G:\you-get -l http://list.youku.com/show/id_z6b5d941629a011e4b8b7.html
今天早上起来，发现，提示错误。。。只下载到第十五集就停了。
重新输入上述命令，现在又正常下载中。。。。
由于是播单下载，且目前没有再出错，所以无法提供debug
鉴于上述情况，建议，播单下载时，加入自动重试功能。。。以防这种无人值守下载时，出现失败了而不自知。。。
谢谢。
![default](https://user-images.githubusercontent.com/22790906/30303586-bc97f008-979b-11e7-9d5c-4a9f01301258.PNG)

**Comment by rosynirvana** [comment]
忽略原因重试会增加ip和ua被youku api server封禁的速度

而且，现在的youku很喜欢封ua和ip

**Comment by neatgz** [comment]
好的。知道啦。下载播单的情景其实也不是太多。
那就关掉这个issue吧。
谢谢啦。
