### ISSUE TITLE
腾讯视频，这种无法解析

### ISSUE THREAD

**Issue by lki2019** [soimort/you-get#2342]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

C:\Users\Administrator>you-get -di http://henan.qq.com/zt2017/xdlbzb/index.htm
[DEBUG] get_content: http://henan.qq.com/zt2017/xdlbzb/index.htm
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333
&platform=11&defnpayver=1&vid=None
you-get: vid is wrong

**Comment by lki2019** [comment]
当然下载地址还是很好找的，

**Comment by rosynirvana** [comment]
4c116c6
