### ISSUE TITLE
爱奇艺视频无法下载

### ISSUE THREAD

**Issue by luanmajun** [soimort/you-get#2349]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
$ you-get -d http://www.iqiyi.com/v_19rrjdrjq0.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rrjdrjq0.html
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/95290100
[DEBUG] get_content: http://www.iqiyi.com/v_19rrjdrjq0.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/95290100/33fb593f856c4fc6800dc340e1f2cf08/?t=1505260886466&sc=e1938a479051e8ba4ddf46df2f931f58&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.909, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.iqiyi.com/v_19rrjdrjq0.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1270, in script_main
    **extra
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1072, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1355, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/iqiyi.py", line 147, in prepare
    assert info['code'] == 'A00000', "can't play this video"
AssertionError: can't play this video
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> I actually can watch it online. However, I cannot download it with you-get.
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
```
./you-get -i http://www.iqiyi.com/v_19rrjdrjq0.html
site:                爱奇艺 (Iqiyi)
title:               欢喜冤家_20101202期
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        HD
      container:     m3u8
      video-profile: 540p
      m3u8_url:      http://cache.m.iqiyi.com/mus/180786901/33fb593f856c4fc6800dc340e1f2cf08/afbe8fd3d73448c9//20150405/a6/15/9599b8bc669dbee39c4920f6c6e56b8e.m3u8?qd_originate=tmts_py&tvid=95290100&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1505271403236&qd_p=b6720383&qd_asc=b52897bee0025a62ba22a5f642c46b33&qypid=95290100_04022000001000000000_2&qd_k=0af9cbff5181b5bd0c55d1915dc0df4e&vf=b1ba7e0ebb92ed04f351ebe9672f134a&np_tag=nginx_part_tag
    # download-with: you-get --format=HD [URL]

    - format:        SD
      container:     m3u8
      video-profile: 360p
      m3u8_url:      http://cache.m.iqiyi.com/mus/180786901/94a99c5eb87a45c7ac6f1568c932f303/afbe8fd3d73448c9//20150405/1a/bc/a7b29b293ef317ebdba96adbb724cd4a.m3u8?qd_originate=tmts_py&tvid=95290100&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1505271403236&qd_p=b6720383&qd_asc=16ebb5df67930be57854bf5fa5c4d65d&qypid=95290100_04022000001000000000_1&qd_k=0af9cbff5181b5bd0c55d1915dc0df4e&vf=340ca8d85b78a656920cce609fa5b12b&np_tag=nginx_part_tag
    # download-with: you-get --format=SD [URL]

    - format:        LD
      container:     m3u8
      video-profile: 210p
      m3u8_url:      http://cache.m.iqiyi.com/mus/180786901/75af0819e09c4c3cad6cccd77a20cbe1/afbe8fd3d73448c9//20150405/1a/6f/b51d0c34fa61e5f83c760d0d70d175cc.m3u8?qd_originate=tmts_py&tvid=95290100&bossStatus=0&qd_vip=0&px=&qd_src=3_31_312&prv=&previewType=&previewTime=&from=&qd_time=1505271403236&qd_p=b6720383&qd_asc=a699a930666acf77aad5b82559fb1f98&qypid=95290100_04022000001000000000_96&qd_k=0af9cbff5181b5bd0c55d1915dc0df4e&vf=f1224ea8fac341a9432cceaf89e47e45&np_tag=nginx_part_tag
    # download-with: you-get --format=LD [URL]
```

**Comment by luanmajun** [comment]
Just cannot download it.
you-get -d http://www.iqiyi.com/v_19rrjckrro.html
[DEBUG] get_response: http://www.iqiyi.com/v_19rrjckrro.html
[DEBUG] get_content: http://mixer.video.iqiyi.com/jp/mixin/videos/95524600
[DEBUG] get_content: http://www.iqiyi.com/v_19rrjckrro.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/95524600/0cae1ba520d24b7e82289b70df5e3e90/?t=1505272813936&sc=50ec9f6caed464d86412f2269e882e42&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.909, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.iqiyi.com/v_19rrjckrro.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1270, in script_main
    **extra
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1072, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1355, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/iqiyi.py", line 147, in prepare
    assert info['code'] == 'A00000', "can't play this video"
AssertionError: can't play this video

**Comment by rosynirvana** [comment]
Blocked outside China mainland
