### ISSUE TITLE
B站通过you-get获取真实地址后用requests下载报403

### ISSUE THREAD

**Issue by luhy118** [soimort/you-get#2359]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
D:\workspace\clip-spider>you-get --json https://bangumi.bilibili.com/anime/6262/play#109726
{
    "extra": {
        "referer": "https://bangumi.bilibili.com/anime/6262/play#109726",
        "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
    },
    "site": "Bilibili",
    "streams": {
        "flv": {
            "container": "flv",
            "size": 25448758,
            "src": [
                "http://cn-jszj-dx-v-05.acgvideo.com/vg3/0/da/18462590-1.flv?expires=1505391900&platform=pc&ssig=gyhLddD0f5AzNEXS4K27sw&oi=3071182160&nfa=NVPjdnMce6y7JSmxZHqtiw==&dynamic=1&hfa=2072606785&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI="
            ]
        }
    },
    "title": "蜡笔小新 第二季（国语） [1 年糕已经吃腻了]",
    "url": "https://bangumi.bilibili.com/anime/6262/play#109726"
}
我只想用you-get获取真实地址(上面的"src"值)，并不想用它下载，因为它不会多线程，也不会断点续传，所以我单独用requests来下载得到的视频真实地址，但是下载时报403，也加了Referer和User-Agent，结果还是一样，真没思路了，大家有没什么解决的思路可以帮下吗，需要添加什么参数才不报403
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
可能性有
1. 你写错什么了
2. connection太多被踢了

requests同样不支持多线程（如果你说的是那个py库），you-get支持断点续传

**Comment by luhy118** [comment]
@rosynirvana  应该没有写错，报403的只有这个B站的番剧栏目，其它栏目用同样的方法下载基本没有问题。我现在主要是用requests来实现断点续传，可以自定义每次续传数据块的大小，you-get的断点续传参数怎么用，可以传入参数没？

**Comment by rosynirvana** [comment]
1. 下载什么行，下载什么不行
是下载这个视频不行，还是下载所有试过的Bilibili bangumi都不行，还是下载所有bilibili视频都不行

2. 断点续传为什么需要参数？你说之前提到的用HTTP Range header来绕过限速吗？那个不叫断点续传

**Comment by luhy118** [comment]
@rosynirvana 下载视频文件，如楼主正文所说的"src": [
                "http://cn-jszj-dx-v-05.acgvideo.com/vg3/0/da/18462590-1.flv?expires=1505391900&platform=pc&ssig=gyhLddD0f5AzNEXS4K27sw&oi=3071182160&nfa=NVPjdnMce6y7JSmxZHqtiw==&dynamic=1&hfa=2072606785&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=" 这个视频，这是视频是B站的番剧栏目下的视频，我现在先用you-get拿到这个真实视频地址后再用requests去下载，通过HTTP Range header来绕过限速，目前我的代码除了B站番剧栏目报403（用requests访问读取视频真实地址）外，其它栏目都成功了。
另外，HTTP Range header不叫断点续传那叫啥，我查了网络上的断点续传看了几个例子，都是通过Range来分块读取数据

**Comment by rosynirvana** [comment]
你这段是把上面几楼的说过的东西又说了一遍

是试了一个链接不行，还是试了几个bangumi的链接都不行？
行的是哪种服务器(tx.acgvideo.com ?)，不行的是哪种服务器(地区拼音开头的acgvideo.com)？

断点续传是个用户级的概念，它确实要用HTTP Range header来实现。多次分块请求是bilibili特有的，因为bilibili搞了个两段限速，它没有对应的用户级的名称，如果要说相近那么和分块下载更相近

**Comment by luhy118** [comment]
@rosynirvana 都说是栏目了，不是说一个视频，栏目的意思就是所有本栏目下视频bangumi。目前URL中不含有bangumi的都正常下载，含有bangumi的全部报403

**Comment by rosynirvana** [comment]
"栏目“真的不是所有人都用的用法

这个就是你写错了，需要的确实只有ua和referer
```
curl -I http://cn-sdjn-cu-v-07.acgvideo.com/vg3/1/31/18462590-1.flv\?expires\=1505401500\&platform\=pc\&ssig\=OsVZUKVyd6Itk_xvy7FPtQ\&oi\=2100146371\&nfa\=NVPjdnMce6y7JSmxZHqtiw\=\=\&dynamic\=1\&hfa\=_\&hfb\=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI\= -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0' -H 'referer: https://bangumi.bilibili.com/anime/6262/play\#109726'
HTTP/1.1 200 OK
Server: openresty
Date: Thu, 14 Sep 2017 13:09:51 GMT
Content-Type: video/x-flv
Content-Length: 25448758
Last-Modified: Fri, 16 Jun 2017 10:50:36 GMT
Connection: keep-alive
ETag: "5943b7fc-1845136"
X-Cache: HIT 0/0 1/1 1/2  cn-sdjn-cu-v-07.hdslb.com Disk
Accept-Ranges: bytes
```

**Comment by luhy118** [comment]
奇怪了，为咐我在自己电脑上WINDOWS试了也是报403，找了了个朋友在他电脑上也是403，
import requests
url = 'http://cn-jszj-dx-v-05.acgvideo.com/vg3/0/da/18462590-1.flv?expires=1505391900&platform=pc&ssig=gyhLddD0f5AzNEXS4K27sw&oi=3071182160&nfa=NVPjdnMce6y7JSmxZHqtiw==&dynamic=1&hfa=2072606785&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI='
ref = 'https://bangumi.bilibili.com/anime/6262/play#109726'
headers = {
             "Referer": "https://bangumi.bilibili.com/anime/6262/play#109726",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
         }

info = requests.get(url,headers=headers)
info.status_code

@rosynirvana  你可以在你电脑上帮我试一下这块代码吗

**Comment by rosynirvana** [comment]
用你那段代码里的url不行
但是如果用you-get对https://bangumi.bilibili.com/anime/6262/play#109726重新生成一个url就可以

另外为什么要这么写，不应该是```requests.get(url, headers=headers, stream=True)```吗

**Comment by luhy118** [comment]
@rosynirvana 哦，刚也试了，stream=True后面下载时是要添加的，前面只想想测试访问是否正常就忘记加了。应该是那个URL过期了，在此向大神再请教个问题。就是用我楼上代码读取返回的info.headers的含有“ 'Accept-Ranges': 'bytes' ”  ，表明 是支持ranges的，可是，为啥我在发请求时添加ranges时就直接报403，难道前面返回的头部Accept-Ranges': 'bytes 是假的吗？
import requests
url = 'http://cn-jszj-dx-v-05.acgvideo.com/vg3/0/da/18462590-1.flv?expires=1505464800&platform=pc&ssig=B62HAXLO3AUTj6xHT5hU6A&oi=3071182160&nfa=NVPjdnMce6y7JSmxZHqtiw==&dynamic=1&hfa=2072532238&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI='
headers = {
"range":"bytes=0-145728",
"Referer": "https://bangumi.bilibili.com/anime/6262/play#109726",
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
}

info = requests.get(url,headers=headers,stream=True)
info.status_code

**Comment by rosynirvana** [comment]
正常的206
还是你哪里搞错了

**Comment by luhy118** [comment]
@rosynirvana  我感觉我贴的代码没有错阿，用这代码，测试别的视频，正常且都返回206
