### ISSUE TITLE
腾讯视频下载限速

### ISSUE THREAD

**Issue by flagang** [soimort/you-get#2360]
example：
you-get https://v.qq.com/x/cover/uqt7am9f9dmvoss/c0020gjgssi.html
下载速度只有十几kb
使用you-get -u https://v.qq.com/x/cover/uqt7am9f9dmvoss/c0020gjgssi.html 获取MP4地址放到浏览器速度也是很慢
在浏览器直接访问https://v.qq.com/x/cover/uqt7am9f9dmvoss/c0020gjgssi.html 视频播放速度正常

一种可行的方式：

```
info_api = 'https://h5vv.video.qq.com/getinfo?otype=json&platform=11001&appVer=3.3.89&host=m.v.qq.com&vid=%s' % vid
info = get_content(info_api)
video_json = json.loads(match1(info, r'QZOutputJson=(.*)')[:-1])
host = video_json['vl']['vi'][0]['ul']['ui'][0]['url']
filename= video_json['vl']['vi'][0]['fn']
vkey = video_json['vl']['vi'][0]['fvkey']
url = '{}{}?vkey={}'.format(host, filename, vkey)
```
获取的url可以正常播放，但是无法选择视频质量

**Comment by lki2019** [comment]
腾讯视频下载限速是老生常谈的问题了

**Comment by redstoneleo** [comment]
维棠下载器号称解决了这个问题，大家研究下它的做法吧
维棠2.1.3.4更新日志：
> 1、解决了腾讯视频下载慢的问题
> 2、内嵌浏览器添加下载按钮，下载视频更快捷
>
