### ISSUE TITLE
icourse support problem

### ISSUE THREAD

**Issue by wy7980** [soimort/you-get#2364]
the part for icourse can not work now, 
you-get -i http://www.icourses.cn/coursestatic/course_3610.html

you-get http://www.icourses.cn/jpk/changeforVideo.action?resId=79809
2&courseId=3610&firstShowFlag=1

you-get  http://media3.icourses.cn/process6/campus/processres/flv/20
13/9/6/ff808081-40e2481c-0140-f1cdac59-00be.flv?lv=150606-1&lt=9-16/17:45:52&ls=
play&h=EvAw2WeDxJmnIj3N2MClqw&r=1505555181&p=151020&start=0

**Comment by rosynirvana** [comment]
It works
Pleaser update your you-get

**Comment by redstoneleo** [comment]
@rosynirvana 付费找你帮忙破解下载视频行不行？至少30元一个月，我的QQ2281570025

**Comment by rosynirvana** [comment]
不收钱……
你有问题还是发issue吧

**Comment by redstoneleo** [comment]
@rosynirvana 是需要账号登陆的视频，不收钱也就不好意思浪费阁下时间了

**Comment by wy7980** [comment]
@rosynirvana  you-get-0.4.915

**Comment by rosynirvana** [comment]
```
you-get -i http://www.icourses.cn/jpk/changeforVideo.action\?resId\=798092\&courseId\=3610\&firstShowFlag\=1
Site:       icourses.cn
Title:      神经病学   神经病学绪论
Type:       Flash video (video/x-flv)
Size:       159.73 MiB (167487310 Bytes)
```

**Comment by wy7980** [comment]
you-get -i http://www.icourses.cn/jpk/changeforVideo.action\
?resId\=798092\&courseId\=3610\&firstShowFlag\=1

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
'courseId\' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'firstShowFlag\' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by rosynirvana** [comment]
```? &``` are special characters in your console so they must be quoted, or wrong urls will be sent to python.

https://github.com/soimort/you-get/wiki/Window-Console-Problems
check part 2

**Comment by wy7980** [comment]
OK，it works now, thx!
