### ISSUE TITLE
macOS 10.13 支持计划

### ISSUE THREAD

**Issue by Cavolo** [soimort/you-get#2368]
macOS 10.13 已经推送 GM 版了，9.26将会发布正式版，想问 you-get 有支持计划吗

Error: You are using macOS 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Error: You are using macOS 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

**Comment by ztytian** [comment]
在High Sierra GM正常使用无异常
请问开这个issue是为了什么？

**Comment by Cavolo** [comment]
@ztytian 请问你是通过brew安装的吗，通过brew安装就会提示high Sierra是它不支持的版本

**Comment by rosynirvana** [comment]
不该使用brew安装一个纯py软件的

**Comment by soimort** [comment]
这不是我们的问题。

https://github.com/Homebrew/homebrew-core/issues/14418

**Comment by ztytian** [comment]
我用pip install you-get的
