### ISSUE TITLE
优酷视频，在线观看403

### ISSUE THREAD

**Issue by jpacg** [soimort/you-get#2370]
视频解析是没问题的，但如果在线播放，过几分钟后，后面的地址就无法使用了。

cdn的地址是vali.cp31.ott.cibntv.net也没用，还是会返回403。

示例视频
http://v.youku.com/v_show/id_XMjk3Njc3NTU4MA==.html

**Comment by GiriMind** [comment]
地址超时了吧，mpv加--merge-files参数合并了看，不过视频载入会变慢，优酷分段丧心病狂

**Comment by jpacg** [comment]
@GiriMind 谢谢，已经解决了，请求这个地址就行了http://gm.mmstat.com/yt/youkuplayer.fdl.h5send

**Comment by fan26a** [comment]
@jpacg 请问怎么解决的？这个地址是什么意思[http://gm.mmstat.com/yt/youkuplayer.fdl.h5send](url)

**Comment by zhaoyujia11808** [comment]
@fan26a  你解决了吗

**Comment by jpacg** [comment]
@fan26a @zhaoyujia11808 我自己解决了，你们也要弄吗？

**Comment by jpacg** [comment]
@fan26a @zhaoyujia11808 我创建了一个QQ群，你们加进来吧，我暂时工作就是弄视频解析。QQ群号：679133371。
