### ISSUE TITLE
bilibili无法用you-get在线播放

### ISSUE THREAD

**Issue by emberrolland** [soimort/you-get#2373]
bilibili可以下载但是不能使用-p调用播放器播放。播放器提示没有找到文件。

**Comment by rosynirvana** [comment]
bilibili CDN要求提供正常的user-agent和referer，很多播放器本身就无法满足这点

**Comment by emberrolland** [comment]
那什么播放器支持播放bilibili呢？我用的mpcbe不行，试了试mpv也不行

**Comment by rosynirvana** [comment]
mpv可以，但是you-get没去实现

**Comment by emberrolland** [comment]
哦，那就希望you-get以后能实现吧。

**Comment by GiriMind** [comment]
you-get -p "mpv.exe --merge-files --http-header-fields='Referer: http://www.bilibili.com'" URL
这样能看不？

**Comment by emberrolland** [comment]
这样就可以了，但是mpcbe不行。而且不知道为什么这命令在open with这个firefox扩展中不成功

**Comment by GiriMind** [comment]
你的open with怎么设置

**Comment by emberrolland** [comment]
就是选youget然后在参数中输入 -p "mpv.exe --merge-files --http-header-fields='Referer: http://www.bilibili.com'"

**Comment by GiriMind** [comment]
这样设置也可以，you-get和mpv都在PATH环境变量里吗？

**Comment by emberrolland** [comment]
都在的。其他站播放都行，唯独针对bilibili加了这条命令后mpv却不启动。

**Comment by emberrolland** [comment]
额，刚试了一下又能用了，谢谢了。想问一下能让mpcbe播放bilibili的视频吗？因为我用本地播放器的目的就是用上madvr

**Comment by GiriMind** [comment]
mpcbe没用过，不知道支不支持修改http头

**Comment by emberrolland** [comment]
谢谢了

**Comment by GiriMind** [comment]
话说mpv开profile=opengl-hq icc-profile-auto，比madvr画质如何

**Comment by emberrolland** [comment]
不太清楚，只是在用youget时用了mpv。不过我估计比不上madvr。

**Comment by GiriMind** [comment]
额额，有空再研究下
