### ISSUE TITLE
有些腾讯视频下载不了

### ISSUE THREAD

**Issue by kungfucop** [soimort/you-get#2374]
在提交前，请确保您已经检查了以下内容!

- [* ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ *] 您的`you-get`为最新版.
- [* ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [* ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [* ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

you-get --debug 'http://v.qq.com/x/page/u0310z7tfpj.html'
[DEBUG] get_content: http://v.qq.com/x/page/u0310z7tfpj.html
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=11&defnpayver=1&vid=u0310z7tfpj
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format=2&vid=u0310z7tfpj&filename=u0310z7tfpj.p2.1.mp4&appver=3.2.19.333

```
[在这里粘贴完整日志]
```

基本上这些不能下载的都是16年7月前的视频。

> [舔 :icecream:!]

**Comment by rosynirvana** [comment]
dup #2353
