### ISSUE TITLE
Win如何导入.netrc文件

### ISSUE THREAD

**Issue by CarlosWangjun** [soimort/you-get#2378]
我是Win系统，you-get版本是0.4.909，我希望批量下载niconico上的视频，希望在netrc文件中配置我的登录名和密码，现在配置好了：
machine niconico
login [ACCOUNT]
password [PASSWORD]

请问怎么在cmd中导入呢？

**Comment by soimort** [comment]
https://superuser.com/questions/620143/is-there-a-windows-solution-for-a-program-that-relies-on-netrc
