### ISSUE TITLE
腾讯视频下载异常：cannot play outside

### ISSUE THREAD

**Issue by luhy118** [soimort/you-get#2384]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[root@easub-spider1 clip-spider]# you-get --debug https://v.qq.com/x/cover/b27vau2axvld41r/r0024rbuwwd.html
[DEBUG] get_content: https://v.qq.com/x/cover/b27vau2axvld41r/r0024rbuwwd.html
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=11&defnpayver=1&vid=r0024rbuwwd
you-get: cannot play outside
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by luhy118** [comment]
刚才又发现一个新的问题：you-get: ip-copy limit  这是什么意思
D:\workspace\clip-spider>you-get https://v.qq.com/x/page/n039079epog.html --debug
[DEBUG] get_content: https://v.qq.com/x/page/n039079epog.html
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=11&defnpayver=1&vid=n039079epog
you-get: ip-copy limit

**Comment by lki2019** [comment]
https://v.qq.com/x/cover/b27vau2axvld41r/r0024rbuwwd.html

https://ltsbsy.qq.com/gpun20MPGjiC-frZFN3UvXhMl3HQ3sNJASs6F3Z9ziGWIfy2IegH5ldX0v_DUQff5TsonhGaLnHvLlP8OAYZxI7E9HntSC3txWVsk70wlmu4HKgyBFmD_2yuW_DhzWi1AUYXXwAqBQrSa8myjNynOQ/r0024rbuwwd.321003.ts.m3u8?ver=4

**Comment by lki2019** [comment]
第2个 网站你打开看看，显示被外星人夺走了，意思可能视频呗删除了吧

**Comment by luhy118** [comment]
@lki2019 应该不是删除，在普通浏览器上都可以正常播放源视频地址：https://v.qq.com/x/cover/b27vau2axvld41r/r0024rbuwwd.html

**Comment by luhy118** [comment]
@lki2019 你说的，还有第二个网站，是怎么得来的

**Comment by luhy118** [comment]
@airdge @rosynirvana  大神，help

**Comment by airdge** [comment]
https://v.qq.com/x/cover/b27vau2axvld41r/r0024rbuwwd.html 类似这种版权视频,必须带ehost参数
`http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=10201&defnpayver=1&vid=r0024rbuwwd&ehost=https%3A%2F%2Fv.qq.com%2Fx%2Fcover%2Fdhzimk1qzznf301%2Fr0024rbuwwd.html`
https://v.qq.com/x/page/n039079epog.html 这个链接应该是删除或者隐藏了 解析不了

**Comment by luhy118** [comment]
@airdge  3Q！！
