### ISSUE TITLE
腾讯视频https://v.qq.com/x/page/p0552k8fpar.html解析不了

### ISSUE THREAD

**Issue by zuishizhi** [soimort/you-get#2385]
[DEBUG] get_content: https://v.qq.com/x/page/p0552k8fpar.html
None
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=11&defnpayver=1&vid=p0552k8fpar
None
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format=2&vid=p0552k8fpar&filename=p0552k8fpar.p2.1.mp4&appver=3.2.19.333
None
you-get: check vid&filename failed
you-get: version 0.4.900, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://v.qq.com/x/page/p0552k8fpar.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1364, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1272, in script_main
    **extra
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1074, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/common.py", line 1357, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.4/site-packages/you_get/extractors/qq.py", line 144, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/usr/lib/python3.4/site-packages/you_get/extractors/qq.py", line 45, in qq_download_by_vid
    print_info(site_info, title, ext, total_size)
UnboundLocalError: local variable 'ext' referenced before assignment

**Comment by levinit** [comment]
you-get的问题吧

**Comment by lki2019** [comment]
http://111.161.124.40/om.tc.qq.com/AoX4HYtYObEzyVIM7njh3phF1EeoLovu2v4XqxO6BIRA/p0552k8fpar.mp4?sdtfrom=v1010&guid=19bec55d008e56cb628c595aea488cf6&vkey=1CA5906D54FA4C160EB2897692610A2B1D736C3EBAF88E944BD71BD57A20798A4BE88D9939C6831CC734DF1EC42032A908960AFDA015D51EBF201194824466E4D19B0D49ACDE2371E4A81E1E86BD429B236A6B39476BC41072DE4665BA5A0E9767CD93DE89C5C8BB56BAFA03DE2AF8AE&locid=9266428b-aaa3-4ff7-befd-ca3580bb2992&size=27150747&ocid=546051500

**Comment by zuishizhi** [comment]
@lki2019 你这个地址也是you-get解析出来的吗？怎么我的解析就报错了？你的也是最新版？

**Comment by airdge** [comment]
` filename = fn_pre + '.p' + str(part_format_id % 10000) + '.' + str(part) + '.mp4'`
这个弄错,format=2时, 取单段mp4
` filename = fn_pre + '.mp4'`

```
http://vv.video.qq.com/getkey?otype=json&platform=11&format=2&vid=p0552k8fpar&filename=p0552k8fpar.mp4&appver=3.2.19.333
```

**Comment by luhy118** [comment]
@airdge  666

**Comment by luhy118** [comment]
@rosynirvana you-get可以更新下上面提到的format=2时, 取单段mp4这个bug吗

**Comment by rosynirvana** [comment]
我猜我不会再维护这个项目了
等有人愿意修吧

**Comment by lki2019** [comment]
@rosynirvana 
额，，这是个悲伤的消息
大神那下一站是？

**Comment by luhy118** [comment]
@rosynirvana 为啥，发现这项目真离不开你，说真的

**Comment by lki2019** [comment]
@soimort 
@rosynirvana 

我只见这2位活动者，维护这个项目

@rosynirvana 大神更新解决问题效率非常高，

如果不维护了，如果有TG群组或者其他交流圈子 希望大神可以留一个
想跟随大神学习啊

**Comment by luhy118** [comment]
确实离不开这两个，如果离开了，这项目的生命就开始走向死亡了

**Comment by zuishizhi** [comment]
这有点悲伤
