### ISSUE TITLE
I can't download a full version video in youku

### ISSUE THREAD

**Issue by kanmaz** [soimort/you-get#2390]
Please help me with this problem.

My you-get version is 0.4.915. I am able to download the video. However, the download seems not to download all parts. It just downloaded first part of video and complete the task.

Somebody know how I can fix it.

Here is the video link: http://v.youku.com/v_show/id_XMjkxMTQ5MTgyMA==.html?v=nextstage&id=6defbfbd23efbfbd7058
Thanks,

**Comment by kanmaz** [comment]
`>you-get -format=flvhd http://v.youku.com/v_show/id_XMjkxMTQ5MTgyMA==.html
you-get: hd2 is a preview
you-get: hd3 is a preview
you-get: flvhd is a preview
you-get: mp4 is a preview
site:                优酷 (Youku)
title:               生有余罪
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          619.8 MiB (649887911 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjkxMTQ5MTgyMA%3D%3D&type=hd3&ups_client_netip=171.249.80.35&ups_ts=1506142521&utid=NtdMEgdU9nACAav5UCMqOEh3&ccode=0401&psid=04a376e53f28c77a45c594613bd31961&duration=3619&expire=18000&ups_key=9d33e3e153b553c7266338c33a3ef733
    # download-with: you-get --format=hd3 [URL]

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Downloading 生有余罪.flv ...
12.1% ( 74.7/619.8MB) ├█████────────────────────────────────────┤[3/3]    8 MB/s
Merging video parts... Merged into 生有余罪.mp4`

Here is my process.  It cant complete

**Comment by lki2019** [comment]
This is a member of the video, you-get does not support download video,
But you can load your member cookies information to download it

**Comment by zglzw** [comment]
我也是同样的问题，下载的视频不全就自动合并了

**Comment by jyuan15** [comment]
这个是VIP视频，只能看6分钟

**Comment by ztytian** [comment]
you-get: hd2 is a preview
you-get: hd3 is a preview
you-get: flvhd is a preview
you-get: mp4 is a preview
Use the -c argument to load cookies. You need a VIP account to access those videos.
