### ISSUE TITLE
B站视频无法下载

### ISSUE THREAD

**Issue by yfang1644** [soimort/you-get#2398]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
./you-get --debug https://www.bilibili.com/video/av14611850
[DEBUG] url_locations: https://www.bilibili.com/video/av14611850
[DEBUG] get_content: https://www.bilibili.com/video/av14611850/
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=11&defnpayver=1&vid=s00246tq05v
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.bilibili.com/video/av14611850'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/fang/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/fang/you-get/src/you_get/common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/home/fang/you-get/src/you_get/common.py", line 1270, in script_main
    **extra
  File "/home/fang/you-get/src/you_get/common.py", line 1072, in download_main
    download(url, **kwargs)
  File "/home/fang/you-get/src/you_get/common.py", line 1355, in any_download
    m.download(url, **kwargs)
  File "/home/fang/you-get/src/you_get/extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "/home/fang/you-get/src/you_get/extractors/bilibili.py", line 137, in prepare
    self.entry(**kwargs)
  File "/home/fang/you-get/src/you_get/extractors/bilibili.py", line 154, in entry
    qq_download_by_vid(tc_flashvars, self.title, output_dir=kwargs['output_dir'], merge=kwargs['merge'], info_only=kwargs['info_only'])
  File "/home/fang/you-get/src/you_get/extractors/qq.py", line 17, in qq_download_by_vid
    log.wtf(video_json['msg'])
KeyError: 'msg'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 似乎连到腾讯视频的都有这个问题
> [舔 :icecream:!]

**Comment by aoxiang594** [comment]
you-get --debug http://www.bilibili.com/video/av14664686/
[DEBUG] url_locations: http://www.bilibili.com/video/av14664686/
[DEBUG] get_content: http://www.bilibili.com/video/av14664686/
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=23906277&player=1&quality=3&ts=1506587493&sign=72ea2f4ed42aa520d050e3995b781b27
[DEBUG] get_content: http://comment.bilibili.com/23906277.xml
site:                Bilibili
title:               上学时你有没有这样的特色同学？
stream:
    - format:        mp4
      container:     mp4
      size:          4.8 MiB (5026180 bytes)
    # download-with: you-get --format=mp4 [URL]

Downloading 上学时你有没有这样的特色同学？.mp4 ...
83.4% (  4.0/  4.8MB) ├███████████████████████████████████──────┤[1/1]    5 MB/s



到了5mb左右以后就会停止

**Comment by lyzready** [comment]
[DEBUG] url_locations: https://www.bilibili.com/video/av14617382/
[DEBUG] get_content: https://www.bilibili.com/video/av14617382/
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=23833027&player=1&quality=3&ts=1506654664&sign=b07b7694add69debf167afef0e053faa
[DEBUG] get_content: http://comment.bilibili.com/23833027.xml
site:                Bilibili
title:               【1080P】【纪录片/剧情】时间之旅.导演剪辑加长版【2016】【中英字幕】【凯特·布兰切特/布拉德·皮特】
stream:
    - format:        flv
      container:     flv
      size:          1301.2 MiB (1364419655 bytes)
    # download-with: you-get --format=flv [URL]

Downloading 【1080P】【纪录片-剧情】时间之旅.导演剪辑加长版【2016】【中英字幕】【凯特·布兰切特-布拉德·皮特】.flv ...
 9.6% ( 125.1/1301.2MB) ├████─────────────────────────────────┤[ 2/15]    1 kB/s

我也遇到了，中断重新运行后只会下载两三秒，然后又停止了。
