### ISSUE TITLE
CCTV 大于30分钟的视频似乎无法下载

### ISSUE THREAD

**Issue by oooitiger** [soimort/you-get#2400]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
C:\Users\Administrator>you-get -di http://tv.cctv.com/2017/09/23/VIDESFJZ3CBIjP1HaPT3y5pl170923.shtml
[DEBUG] get_content: http://tv.cctv.com/2017/09/23/VIDESFJZ3CBIjP1HaPT3y5pl170923.shtml
[DEBUG] get_content: http://vdn.apps.cntv.cn/api/getHttpVideoInfo.do?pid=effbc032d1de4dd78c60ac433467db94
site:                CNTV.com
title:               《新闻调查》 20170923 重生
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        1
      container:     mp4
      video-profile: 1280x720_2000kb/s
    # download-with: you-get --format=1 [URL]

    - format:        2
      container:     mp4
      video-profile: 1280x720_1200kb/s
    # download-with: you-get --format=2 [URL]

    - format:        3
      container:     mp4
      video-profile: 640x360_850kb/s
    # download-with: you-get --format=3 [URL]

    - format:        4
      container:     mp4
      video-profile: 480x270_450kb/s
    # download-with: you-get --format=4 [URL]

    - format:        5
      container:     mp4
      video-profile: 320x180_200kb/s
    # download-with: you-get --format=5 [URL]


C:\Users\Administrator>you-get -o E: http://tv.cctv.com/2017/09/23/VIDESFJZ3CBIjP1HaPT3y5pl170923.shtml
site:                CNTV.com
title:               《新闻调查》 20170923 重生
stream:
    - format:        1
      container:     mp4
      video-profile: 1280x720_2000kb/s
    # download-with: you-get --format=1 [URL]

Downloading 《新闻调查》 20170923 重生.mp4 ...
 100% (622.6/622.6MB) ├███████████████████████████████████████┤[22/22]    1 MB/s
Merging video parts...
E:《新闻调查》 20170923 重生[00].mp4
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by oooitiger** [comment]
没有合成~

**Comment by oooitiger** [comment]
C:\Users\Administrator>you-get -o E:\youget\ http://tv.cctv.com/2017/09/27/VIDEavD2FloLIvilnu808rVw170927.shtml
site:                CNTV.com
title:               [欧冠]C罗独中两元 皇马客场击败多特蒙德（晨报）
stream:
    - format:        1
      container:     mp4
      video-profile: 1280x720_2000kb/s
    # download-with: you-get --format=1 [URL]

Downloading (欧冠)C罗独中两元 皇马客场击败多特蒙德（晨报）.mp4 ...
 100% ( 33.8/ 33.8MB) ├█████████████████████████████████████████┤[2/2]    1 MB/s
Merging video parts...
E:\youget\(欧冠)C罗独中两元 皇马客场击败多特蒙德（晨报）[00].mp4
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.


合成出了问题，怎么解？

**Comment by mengmo** [comment]
**[README](https://github.com/soimort/you-get/blob/develop/README.md)**
> **Prerequisites**
> 
> The following dependencies are required and must be installed separately, unless you are using a pre-built package or chocolatey on Windows:
> 
> **[Python 3](https://www.python.org/downloads/)**
> **[FFmpeg](https://www.ffmpeg.org/)** (strongly recommended) or [Libav](https://libav.org/)
> (Optional) [RTMPDump](https://rtmpdump.mplayerhq.hu/)

**[中文说明](https://github.com/soimort/you-get/wiki/中文说明)**
> **绪论**
> 
> 以下乃必要依赖，需要单独安装，除非于Windows下使用预包装包:
> 
> **[Python 3](https://www.python.org/downloads/)**
> **[FFmpeg](https://www.ffmpeg.org/)** (强烈推荐) or [Libav](https://libav.org/)
> (可选) [RTMPDump](https://rtmpdump.mplayerhq.hu/)

**Comment by cnbeining** [comment]
@mengmo nice catch.

@oooitiger 请检查依赖。
