### ISSUE TITLE
Bilibili - AttributeError 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Zapiboss** [soimort/you-get#2403]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

D:\DOWNLOAD\you-get>you-get --debug http://www.bilibili.com/vide
o/av5173589
[DEBUG] url_locations: http://www.bilibili.com/video/av5173589
[DEBUG] get_content: http://www.bilibili.com/video/av5173589/
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.bilibili.com/video/av5173589'], cookies=None
, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_p
roxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False,
 no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=
None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, u
rl=False, version=False)
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1362, in main
  File "src\you_get\common.py", line 1270, in script_main
  File "src\you_get\common.py", line 1072, in download_main
  File "src\you_get\common.py", line 1355, in any_download
  File "src\you_get\extractor.py", line 46, in download_by_url
  File "src\you_get\extractors\bilibili.py", line 135, in prepare
  File "src\you_get\extractors\bilibili.py", line 155, in entry
AttributeError: 'NoneType' object has no attribute 'group'
you-get returned -1

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

o/

**Comment by soimort** [comment]
@soimort-bot test http://www.bilibili.com/video/av5173589/

**Comment by mengmo** [comment]
works for me (you-get=soimort:develop db8f59c)
```
you-get -di http://www.bilibili.com/video/av5173589/
D:\PortableApps\Python\lib\runpy.py:125: RuntimeWarning: 'you_get.__main__' found in sys.modules after import of package 'you_get', but prior to execution of 'you_get.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[DEBUG] url_locations: http://www.bilibili.com/video/av5173589/
[DEBUG] get_content: http://www.bilibili.com/video/av5173589/
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=8407718&player=1&quality=4&ts=1506792352&sign=b6f3259ace07f05a53bad427941ab817
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=8407718&player=1&quality=3&ts=1506792352&sign=804c6aa8a1cb6ed4d3604d326bd38b8f
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=8407718&player=1&quality=2&ts=1506792352&sign=8c7e8becc2c95054aa8fc8d5565fd409
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=8407718&player=1&quality=1&ts=1506792352&sign=922c3c0b466042572f62df883e6f0db7
site:                Bilibili
title:               疯味英雄 12 流离
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        flv
      container:     flv
      size:          498.0 MiB (522154314 bytes)
    # download-with: you-get --format=flv [URL]

    - format:        hdmp4
      container:     mp4
      size:          328.3 MiB (344241459 bytes)
    # download-with: you-get --format=hdmp4 [URL]

    - format:        mp4
      container:     mp4
      size:          143.5 MiB (150475448 bytes)
    # download-with: you-get --format=mp4 [URL]
```
Python version: `3.6.2`
GeoIP location: China

**Comment by Zapiboss** [comment]
Does that means it's restricted only in China ?
I also tried with the developer version but i still get the same error message.

**Comment by mengmo** [comment]
@Zapiboss   seems so
![0](https://user-images.githubusercontent.com/17815250/31050783-5edc9e2c-a688-11e7-9596-479adeb9f29a.png)
check this url: http://bangumi.bilibili.com/anime/2925

**Comment by Zapiboss** [comment]
But... but...
![image](https://user-images.githubusercontent.com/4704947/31055571-0d343908-a6c5-11e7-9490-d294df130468.png)
Very strange that i get the error message in that case.

**Comment by cnbeining** [comment]
I would boldly guess you are using proxy/VPN like service with ``you-get``` without knowing.

If you are using software like ```Proxifier```, PAC file or geo-unblocking DNS, try disable them and retry.

**Comment by soimort** [comment]
As far as I can tell, this video is inaccessible from all US IPs. (You're using Unblock Youku, right?)

US:

![screenshot from 2017-10-13 16-41-30](https://user-images.githubusercontent.com/342945/31551703-a9b3e476-b035-11e7-9277-b11ab8d1382a.png)

Europe / China:

![screenshot from 2017-10-13 16-41-51](https://user-images.githubusercontent.com/342945/31551707-ab9a618e-b035-11e7-8476-e2573505c616.png)

**Comment by Zapiboss** [comment]
In France at least, i don't have any problem watching vids in bilibili.
@cnbeining Sadly, i don't use any proxy and don't have any in my computer. I already tested from another location in France with a laptop computer, same. Can watch online, but can't download with you-get :(

@soimort I am not using unblock youku, don't even knew the software.

Pretty strange in all cases.
