### ISSUE TITLE
无法获取优酷（youku）9月27日（或9月28日）后发布视频的超清/1080P 地址

### ISSUE THREAD

**Issue by chaosphinx** [soimort/you-get#2405]
以账户“新车评网（http://i.youku.com/i/UMzEwNjAyNzMy ）”为例：

9月26日发布视频（http://v.youku.com/v_show/id_XMzA0Nzg0NzY0OA==.html ）及9月27日视频（http://v.youku.com/v_show/id_XMzA1MDI5MDc5Mg==.html ）可以获取超清/1080P 格式地址；

9月28日视频（http://v.youku.com/v_show/id_XMzA1MjUwNzgxMg==.html ）及9月29日视频（http://v.youku.com/v_show/id_XMzA1NDU5MDU0OA==.html ）只能获取高清格式。

**Comment by sy1412** [comment]
同求作者帮忙 在要用时就正巧不好使了。。。

**Comment by HJH12315** [comment]
确实，我用-p 想通过potplayer在线观看优酷1080p视频，发现potplayer无法打开。希望作者能够帮忙解决~

**Comment by wushilin** [comment]
确实是个问题，一律都只是高清了。

**Comment by StLym** [comment]
最近我也遇到了同样的问题，优酷不能下载1080p，默认只有高清，版本是0.4.915

**Comment by Amehinou** [comment]
同求

**Comment by HJH12315** [comment]
用会员的cookies好像可以下载1080p的。就是不能在线看了。

**Comment by ztytian** [comment]
you-get -c cookies.sqlite -i http://v.youku.com/v_show/id_XMzA1NDU5MDU0OA==.html 
you-get: Found cna in imported cookies. Use it
site:                优酷 (Youku)
title:               购车我帮你：全新卡罗拉配置价格分析
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          25.3 MiB (26514244 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMzA1NDU5MDU0OA%3D%3D&type=mp4&ups_client_netip=222.152.168.233&ups_ts=1507367810&utid=GJP1ESyBhX8CAbZ2CCpmAJ6o&ccode=0401&psid=903860705d993d6868eac434834b45e2&ups_userid=150169847&ups_ytid=709370578&duration=361&expire=18000&ups_key=3a21bea6e9b53325b232f1af738d6171
    # download-with: you-get --format=mp4 [URL]

**Comment by ztytian** [comment]
会员cookies无效

**Comment by mogu1121** [comment]
flash版 在线的json有1080p 不用会员。不知道you-get获取的json有没有 或者是解析json做得不好

**Comment by wushilin** [comment]
貌似我也确认会员cookie无用。

**Comment by lamlam123tld3** [comment]
mp4hd3 => mp4hd3v2
mp4hd2 => mp4hd2v2

**Comment by ParkerOutlook** [comment]
通过-i选项只能找到高清。

**Comment by Amehinou** [comment]
旧上传的视频 可以用 mp4hd3 获取到1080P
新上传的视频 可以用 mp4hd3v2 获取到1080P

**Comment by ParkerOutlook** [comment]
@Amehinou 打上patch之后可以了，thank you so much

**Comment by F1uYu4n** [comment]
@Amehinou patch后在merge时候报错
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjk4ODA1MzI0NA==&ccode=0401&client_ip=192.168.1.1&utid=/Q9jEtLXC04CAd9EChh3rEgY&client_ts=1507598848
site:                优酷 (Youku)
title:               白夜追凶 04
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          755.3 MiB (792040315 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMjk4ODA1MzI0NA%3D%3D&type=hd3&ups_client_netip=223.68.10.24&ups_ts=1507598848&utid=%2FQ9jEtLXC04CAd9EChh3rEgY&ccode=0401&psid=21a6c812c377b2958607faf25240f00a&duration=2717&expire=18000&ups_key=4a39ff38fb9971e4baed37b6ac98f8bd
    # download-with: you-get --format=hd3 [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XMjk4ODA1MzI0NA==

Downloading 白夜追凶 04.flv ...
 100% (755.3/755.3MB) ├██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[40/40]  277 MB/s
Merging video parts...
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://v.youku.com/v_show/id_XMjk4ODA1MzI0NA==.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1270, in script_main
    **extra
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1072, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1355, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/youku.py", line 299, in youku_download_by_url
    Youku().download_by_url(url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/you_get/extractor.py", line 227, in download
    av=stream_id in self.dash_streams)
  File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 821, in download_urls
    concat_flv(parts, output_filepath)
  File "/usr/local/lib/python3.5/dist-packages/you_get/processor/join_flv.py", line 306, in concat_flv
    read_flv_header(stream)
  File "/usr/local/lib/python3.5/dist-packages/you_get/processor/join_flv.py", line 243, in read_flv_header
    assert stream.read(3) == b'FLV'
AssertionError

**Comment by IMLink** [comment]
@F1uYu4n 容器不对，原来的flv，新的是mp4，对应改下就OK

stream_types = [
        {'id': 'mp4hd3v2', 'alias-of': 'hd3v2'},
        {'id': 'hd3v2',    'container': 'mp4', 'video_profile': '1080P'},
        {'id': 'mp4hd3', 'alias-of': 'hd3'},
        {'id': 'hd3',    'container': 'flv', 'video_profile': '1080P'},
        {'id': 'mp4hd2v2', 'alias-of': 'hd2v2'},
        {'id': 'hd2v2',    'container': 'mp4', 'video_profile': '超清'},
        {'id': 'mp4hd2', 'alias-of': 'hd2'},
        {'id': 'hd2',    'container': 'flv', 'video_profile': '超清'},
        {'id': 'mp4hd',  'alias-of': 'mp4'},
        {'id': 'mp4',    'container': 'mp4', 'video_profile': '高清'},
        {'id': 'flvhd',  'container': 'flv', 'video_profile': '标清'},
        {'id': 'flv',    'container': 'flv', 'video_profile': '标清'},
        {'id': '3gphd',  'container': 'mp4', 'video_profile': '标清（3GP）'},
    ]

改成这样

**Comment by soimort** [comment]
Fixed by 6169894.
