### ISSUE TITLE
你好，能否支持其他的下载工具比如aria2或者wget？

### ISSUE THREAD

**Issue by goxofy** [soimort/you-get#241]
aria2的多线程对下载速度提升还是很明显的，wget的话基本上常见的linux发行版都默认有安装，不知you-get能否加上这两个工具的支持？

**Comment by petronny** [comment]
@soimort 能否整理一下downloader的接口？ 我看到现在cli_wrapper/downloader下面还是空的。
建一下urllib.py, curl.py, wget.py, aria2.py 什么的，留一下接口我们来填坑？

**Comment by soimort** [comment]
Duplicate of #25.
