### ISSUE TITLE
Some miaopai videos failed

### ISSUE THREAD

**Issue by magicknight** [soimort/you-get#2411]
Please make sure these boxes are checked before submitting your issue – thank you!

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]

[DEBUG] get_content: http://weibo.com/tv/v/FnUyKA2Jc?from=vfun
[DEBUG] get_content: https://weibo.cn/sinaurl/blocked39841440?luicode=20000061&lfid=4156989628590298&u=http://miaopai.com/show/7RWHoORkqQNqHaDPOYC7yyDXuLOaSkhZ7FrYPQ__.htm
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://weibo.com/tv/v/FnUyKA2Jc?from=vfun'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=True, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    load_entry_point('you-get==0.4.915', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/__main__.py", line 92, in main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/common.py", line 1362, in main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/common.py", line 1270, in script_main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/common.py", line 1072, in download_main
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/common.py", line 1355, in any_download
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/extractors/miaopai.py", line 47, in miaopai_download
  File "/usr/local/lib/python3.5/dist-packages/you_get-0.4.915-py3.5.egg/you_get/extractors/miaopai.py", line 44, in miaopai_download
Exception: Unknown pattern

```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by cnbeining** [comment]
>[DEBUG] get_content: https://weibo.cn/sinaurl/blocked39841440?luicode=20000061&lfid=4156989628590298&u=http://miaopai.com/show/7RWHoORkqQNqHaDPOYC7yyDXuLOaSkhZ7FrYPQ__.htm

By using so you are using ```sina.com```'s extractor rather than ```miaopai.com```'s .

To avoid this you probably have to call the CLI by ```you-get http://miaopai.com/show/7RWHoORkqQNqHaDPOYC7yyDXuLOaSkhZ7FrYPQ__.htm ```.
