### ISSUE TITLE
bilibili only 3Mb/run

### ISSUE THREAD

**Issue by Greatjian** [soimort/you-get#2416]
Please make sure these boxes are checked before submitting your issue – thank you!

- [1] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [] Your `you-get` is up-to-date.
- [] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [] 您的`you-get`为最新版.
- [] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
~ you-get --format=flv 'https://www.bilibili.com/video/av8920130/?from=search&seid=13135936656988061284#page=2' --debug
[DEBUG] url_locations: https://www.bilibili.com/video/av8920130/?from=search&seid=13135936656988061284#page=2
[DEBUG] get_content: http://www.bilibili.com/video/av8920130/index_2.html
[DEBUG] get_content: http://interface.bilibili.com/playurl?cid=20189227&player=1&quality=3&ts=1507346721&sign=dae90fded4f551308ad85731fa706bdd
[DEBUG] get_content: http://comment.bilibili.com/20189227.xml
site:                Bilibili
title:               【Musical Fans字幕组】2017年托尼奖最佳音乐剧《埃文汉森》Dear Evan Hansen 2016年11月粉丝录像(2)
stream:
    - format:        flv
      container:     flv
      size:          1947.6 MiB (2042225377 bytes)
    # download-with: you-get --format=flv [URL]

Downloading 【Musical Fans字幕组】2017年托尼奖最佳音乐剧《埃文汉森》Dear Evan Hansen 2016年11月粉丝录像(2).flv ...
 0.8% (  15.0/1947.6MB) ├─────────────────────────────────────┤[ 1/31]    5 MB/s
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> I tried to download a video on bilibili, but it stucked at 3Mb. Every time I paused and resumed, it only downloaded 3 Mb more per time. Since the video size is too large, I consider it too time-consuming... Anything I can do to keep it downloading? Thanks!
> [舔 :icecream:!]

**Comment by conan06** [comment]
+1

上周也有人上报过这个问题。
bilibili每次下载3MB-7MB左右的文件后就暂停，每次都要自己手动继续下载……

**Comment by gonejack** [comment]
这个已经修复了，brew还没更新（估计你也是brew安装的），git clone master分支可以解决

**Comment by Greatjian** [comment]
我是用的pip3 install的，也upgrade到最新版本了，试了下还是会卡住 :(

**Comment by gonejack** [comment]
pip3也不是最新，当前分支head才是最新

**Comment by Greatjian** [comment]
我develop和master branch都试过了还是不行啊，你尝试下载下我这个视频看看会卡吗？

**Comment by zuishizhi** [comment]
@Greatjian 可以吗

**Comment by Greatjian** [comment]
@zuishizhi 还是会卡

**Comment by ethenlong** [comment]
@gonejack 那要怎么更新到其他版本啊，用什么命令呢，小白求教，谢谢！

**Comment by gonejack** [comment]
git clone git@github.com:soimort/you-get.git
cd you-get
python3 you-get "https://www.bilibili.com/video/av8920130/?from=search&seid=13135936656988061284#page=2"

不会卡啊，你试试

**Comment by Greatjian** [comment]
![image](https://user-images.githubusercontent.com/28743422/31418627-21e4621e-ae05-11e7-8b31-09801420afdc.png)
@gonejack  我试了，还是会卡，难道和地区有关系...

**Comment by gonejack** [comment]
进文件夹里用python3 you-get 跑那个最新的you-get

我看你还是用之前装的you-get
