### ISSUE TITLE
爱课程网的视频如何下载？

### ISSUE THREAD

**Issue by gjjpkc** [soimort/you-get#2417]
请问有会下载爱课程网页的视频吗？
如此课程：http://www.icourses.cn/coursestatic/course_6955.html
单讲视频如：http://www.icourses.cn/jpk/viewCharacterDetail.action?sectionId=71497&courseId=6955
请问如果用you-get来下载这样的视频？如果可以请问怎么一次下载一整门课程，或者一次指定其中一讲或多讲的视频下载，请求大神的帮忙。
非常感谢了......

**Comment by gjjpkc** [comment]
you-get -di -l http://www.icourses.cn/coursestatic/course_6955.html

you-get --debug "http://www.icourses.cn/jpk/viewCharacterDetail.action?sectionId=71497&courseId=6955"

看了别人的这些都没办法下载。

**Comment by soimort** [comment]
```
$ you-get -di 'http://www.icourses.cn/jpk/viewCharacterDetail.action?sectionId=71497&courseId=6955' 
[DEBUG] get_content: http://www.icourses.cn/jpk/viewCharacterDetail.action?sectionId=71497&courseId=6955
[DEBUG] get_content: http://www.icourses.cn/jpk/getResPlayInfo.action?IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&uuid=1076162&other=&v=1507908173552
[DEBUG] get_content: http://media1.icourses.cn:8080/process7/campus//ssl/host.shtml
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=3142264
[DEBUG] url_info: http://media2.icourses.cn/process7/campus/processres/flv/2014/12/18/ff808081-4a386b96-014a-5bc09b02-00a6.flv?lv=150606-1&p=151020&ls=play&start=0&lt=10-13%2F17%3A23%3A30&h=OD2rY2FrWDfXGf3Qkb_aEg&r=1507960133
Site:       icourses.cn
Title:      行政管理学 第一课 第1节 行政管理学的含义、研究对象与方法
Type:       Flash video (video/x-flv)
Size:       243.13 MiB (254940361 Bytes)
```

```
$ you-get -dli 'http://www.icourses.cn/coursestatic/course_6955.html'
[DEBUG] get_content: http://www.icourses.cn/coursestatic/course_6955.html
[DEBUG] get_content: http://www.icourses.cn/jpk/viewCharacterDetail.action?sectionId=71496&courseId=6955
[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=1076162&courseId=6955
[DEBUG] get_content: http://www.icourses.cn/jpk/getResPlayInfo.action?IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&uuid=1076162&other=&v=1507908232616
[DEBUG] get_content: http://media1.icourses.cn:8080/process7/campus//ssl/host.shtml
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=4946837
[DEBUG] url_info: http://media2.icourses.cn/process7/campus/processres/flv/2014/12/18/ff808081-4a386b96-014a-5bc09b02-00a6.flv?lv=150606-1&p=151020&ls=play&start=0&lt=10-13%2F17%3A24%3A30&h=uRdAcVr84GQrkETYIYKJ4g&r=1507960194
Site:       icourses.cn
Title:      行政管理学 第一课 第1节 行政管理学的含义、研究对象与方法
Type:       Flash video (video/x-flv)
Size:       243.13 MiB (254940361 Bytes)

[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=545330&courseId=6955
[DEBUG] get_content: http://www.icourses.cn/jpk/getResPlayInfo.action?IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPlayInfo.action&uuid=545330&other=&v=1507908242958
[DEBUG] get_content: http://media1.icourses.cn:8080/process6/campus//ssl/host.shtml
[DEBUG] get_content: http://media3.icourses.cn/ssl/ssl.shtml?r=6552251
[DEBUG] url_info: http://media3.icourses.cn/process6/campus/processres/flv/2013/10/10/ff808081-419c09bf-0141-a2d4cb98-0083.flv?lv=150606-1&p=151020&ls=play&start=0&lt=10-13%2F17%3A24%3A46&h=hm5iWvKGuNm4KVWF-dalrA&r=1507929900
Site:       icourses.cn
Title:      行政管理学 第一课 第2节 行政管理学的产生和发展
Type:       Flash video (video/x-flv)
Size:       356.9 MiB (374238633 Bytes)
```

**Comment by gjjpkc** [comment]
@soimort 这些信息能获取到，但是没办法下载啊。

>you-get -dli http://www.icourses.cn/coursestatic/course_6955.html
[DEBUG] get_content: http://www.icourses.cn/coursestatic/course_6955.html
[DEBUG] get_content: http://www.icourses.cn/jpk/viewCharacterDetail.action?secti
onId=71496&courseId=6955
[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=1076
162&courseId=6955
[DEBUG] get_content: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=10761
62&v=1507969344549&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPl
ayInfo.action
[DEBUG] get_content: http://media1.icourses.cn:8080/process7/campus//ssl/host.sh
tml
[DEBUG] get_content: http://media2.icourses.cn/ssl/ssl.shtml?r=5447242
[DEBUG] url_info: http://media2.icourses.cn/process7/campus/processres/flv/2014/
12/18/ff808081-4a386b96-014a-5bc09b02-00a6.flv?p=151020&start=0&ls=play&lv=15060
6-1&lt=10-14%2F16%3A16%3A28&r=1507999702&h=xBQFyQtxOZ7I-FBbhLByHw
Site:       icourses.cn
Title:      Type:       Flash video (video/x-flv)
Size:       243.13 MiB (254940361 Bytes)

[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=5453
30&courseId=6955
[DEBUG] get_content: http://www.icourses.cn/jpk/getResPlayInfo.action?uuid=54533
0&v=1507969370807&other=&IService=http%3A%2F%2Fwww.icourses.cn%2Fjpk%2FgetResPla
yInfo.action
[DEBUG] get_content: http://media1.icourses.cn:8080/process6/campus//ssl/host.sh
tml
[DEBUG] get_content: http://media3.icourses.cn/ssl/ssl.shtml?r=5417770
you-get: version 0.4.915, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.icourses.cn/coursestatic/course_6955.html'],
 cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=
False, http_proxy=None, info=True, input_file=None, itag=None, json=False, no_ca
ption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=Non
e, password=None, player=None, playlist=True, socks_proxy=None, stream=None, tim
eout=600, url=False, version=False)
Traceback (most recent call last):
  File "urllib\request.py", line 1240, in do_open
  File "http\client.py", line 1083, in request
  File "http\client.py", line 1128, in _send_request
  File "http\client.py", line 1079, in endheaders
  File "http\client.py", line 911, in _send_output
  File "http\client.py", line 854, in send
  File "http\client.py", line 826, in connect
  File "socket.py", line 707, in create_connection
  File "socket.py", line 698, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没
有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1362, in main
  File "src\you_get\common.py", line 1270, in script_main
  File "src\you_get\common.py", line 1070, in download_main
  File "src\you_get\common.py", line 1359, in any_download_playlist
  File "src\you_get\extractors\icourses.py", line 118, in icourses_playlist_down
load
  File "src\you_get\extractors\icourses.py", line 29, in icourses_download
  File "src\you_get\extractors\icourses.py", line 285, in generate_url
  File "src\you_get\extractors\icourses.py", line 254, in update_url
  File "src\you_get\extractors\icourses.py", line 290, in get_sign
  File "src\you_get\common.py", line 372, in get_content
  File "src\you_get\common.py", line 346, in urlopen_with_retry
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 465, in open
  File "urllib\request.py", line 483, in _open
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 1268, in http_open
  File "urllib\request.py", line 1242, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没
有正确答复或连接的主机没有反应，连接尝试失败。>
you-get returned -1

**Comment by hbliyafei** [comment]
@gjjpkc 我昨天也遇到了, 重试两次就可以下载了.

**Comment by gjjpkc** [comment]
@hbliyafei 你QQ是多少啊，我加你请教，谢谢。

**Comment by hbliyafei** [comment]
@gjjpkc  2313773884

**Comment by gjjpkc** [comment]
@hbliyafei 加你了啊。怎么没反应的？
