### ISSUE TITLE
you-get项目就此慢慢被遗弃了吗

### ISSUE THREAD

**Issue by luhy118** [soimort/you-get#2420]
我接触you-get的时间四个月多了，但近一个月来，明显感觉到you-get项目有种无人维断的状态，或许是维护这项目的大神太少，或许是大神们精力时间有限无法及时跟进，总之，目前的维护效率已无法跟上BUG出现的进度了。
开源精神在哪里？希望有能力的大神一起参与进来吧

**Comment by cnbeining** [comment]
>you-get项目就此慢慢被遗弃了吗 

不会的。虽然没什么理由：但是不会的。
