### ISSUE TITLE
10.10号 PPTV下载失败

### ISSUE THREAD

**Issue by lki2019** [soimort/you-get#2422]
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>you-get -di http://v.pptv.com/show/RTUFgupQwP5h30c.html
[DEBUG] get_content: http://v.pptv.com/show/RTUFgupQwP5h30c.html
[DEBUG] get_content: http://web-play.pptv.com/webplay3-0-26718789.xml?type=web.f
pp&version=4
site:                PPTV
title:               国外一支超欢脱广告，全程脑洞
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        0
      container:     mp4
      video-profile: 480x272@328kbps
      size:          3.3 MiB (3494173 bytes)
    # download-with: you-get --format=0 [URL]

解析出来的是3M的广告····

**Comment by lamlam123tld3** [comment]
simple

api_url = 'http://web-play.pptv.com/webplay3-0-{}.xml?appplt=flp&appid=pptv.flashplayer.vod&appver=3.4.2.28&type=web.fpp&version=4'.format(self.vid)

**Comment by yangaowei** [comment]
@lamlam123tld3 这种方式失效了

**Comment by airdge** [comment]
```
http://web-play.pptv.com/webplay3-0-26436157.xml?appplt=flp&appid=pptv.flashplayer.vod&appver=3.4.2.28&type=&version=4
http://web-play.pptv.com/webplay3-15-26436157.xml?appplt=flp&appid=pptv.flashplayer.vod&appver=3.4.2.28&type=&version=4
```
第二个估计会稳定一点

**Comment by yangaowei** [comment]
@airdge  下载的URL拼接有问题，应该是改规则了，您试试

**Comment by mk6012** [comment]
@yangaowei 拼接的视频也不要type的值，即"&fpp.ver=1.3.0.4&type=web.fpp"改为"&fpp.ver=1.3.0.4&type="

**Comment by huwenkai26** [comment]
@mk6012  能说详细点吗
