### ISSUE TITLE
B站下载，下载过程中卡住，或者网速极慢！

### ISSUE THREAD

**Issue by ethenlong** [soimort/you-get#2423]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:
Downloading 【BDF-SPECIAL第三弹！带着家人一起来跳舞吧！】交织together.flv ..
 0.0% (  0.0/ 92.0MB) ├──────────────────────────
 0.3% (  0.2/ 92.0MB) ├──────────────────────────
 0.5% (  0.5/ 92.0MB) ├──────────────────────────
 0.8% (  0.8/ 92.0MB) ├──────────────────────────
 1.1% (  1.0/ 92.0MB) ├█─────────────────────────
 1.4% (  1.2/ 92.0MB) ├█─────────────────────────
 1.6% (  1.5/ 92.0MB) ├█─────────────────────────
 1.9% (  1.8/ 92.0MB) ├█─────────────────────────
 2.2% (  2.0/ 92.0MB) ├█─────────────────────────
 2.4% (  2.2/ 92.0MB) ├█─────────────────────────
 2.7% (  2.5/ 92.0MB) ├█─────────────────────────
 3.0% (  2.8/ 92.0MB) ├██────────────────────────
 3.3% (  3.0/ 92.0MB) ├██────────────────────────
 3.5% (  3.2/ 92.0MB) ├██────────────────────────
 3.8% (  3.5/ 92.0MB) ├██────────────────────────
 4.1% (  3.8/ 92.0MB) ├██────────────────────────
 4.3% (  4.0/ 92.0MB) ├██────────────────────────
 4.6% (  4.2/ 92.0MB) ├██────────────────────────
 4.9% (  4.5/ 92.0MB) ├██────────────────────────
─────────────┤[1/1]    1 kB/s

刚开始用，一开始下载速度听好，然后后面就一直卡在这了，或者速度很慢，有知道的大神，指导下，感激不尽！
> [您的内容]
> [舔 :icecream:!]

**Comment by kobemtl** [comment]
重新下載安裝最新的you-get源碼就可以了。
