### ISSUE TITLE
Youku视频下载提示“you-get: 客户端无权播放,201”

### ISSUE THREAD

**Issue by yywf** [soimort/you-get#2512]
root@H:/home/lpz# you-get http://v.youku.com/v_show/id_XMzE2NzI2NTA2OA==.html?spm=a2h1n.8261147.point_reload_201711.5~5~5~5~A -d
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMzE2NzI2NTA2OA==&ccode=0401&client_ip=192.168.1.1&utid=W4ScEkcyWnICAdy4YFu3fls1&client_ts=1511364190
you-get: 客户端无权播放,201
root@H:/home/lpz#
<img width="1417" alt="2017-11-22 23 20 44" src="https://user-images.githubusercontent.com/4133268/33134999-33cc7978-cfdc-11e7-8264-391ba4d25671.png">

**Comment by dkl3** [comment]
you-get http://video.tudou.com/v/XMjQ1MTExOTc4OA==.html?spm=a2hzp.8253869.0.0 --debug
[DEBUG] get_content: http://video.tudou.com/v/XMjQ1MTExOTc4OA==.html?spm=a2hzp.8253869.0.0
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMjQ1MTExOTc4OA==&ccode=050F&client_ip=192.168.1.1&utid=8ZicEnXhET4CAUkL8KkAFhwl&client_ts=1511369460
you-get: 客户端无权播放,201

Not again... :(

**Comment by benwu7** [comment]
same issue

**Comment by lll423** [comment]
\Python\Python36-32\Lib\site-packages\you_get\extractors\youku.py
第81行 self.ccode = '0401' 改成 self.ccode = '0502'

**Comment by JiangDing1990** [comment]
我找不到“\Python\Python36-32\Lib\site-packages\you_get\extractors\youku.py”这个路径，我只找到了项目里的“src/you_get/\extractors/youku.py”这个文件。。。你说的这个是在哪里改啊？ @lll423 可以告诉一下具体一点的位置吗？谢谢了！

**Comment by huzy0909** [comment]
你可以搜一下youku.py这个文件，看看有几个，如果只又你说的这个，那就改了试试，应该就好了

**Comment by JiangDing1990** [comment]
我的是Mac系统，“\Python\Python36-32\Lib\site-packages\you_get\extractors\youku.py”这个路径貌似是Windows下的路径。。我说我咋找不到呢。。

**Comment by JiangDing1990** [comment]
Mac系统下，用homebrew安装的you-get，路径是这样的“/usr/local/Cellar/you-get/0.4.964/libexec/lib/python3.6/site-packages/you_get/extractors/youku.py” 。。刚改了文件，现在优酷的视频下载没有问题了。 感谢 @lll423 和 @huzy0909

**Comment by woodword** [comment]
> \Python\Python36-32\Lib\site-packages\you_get\extractors\youku.py
第 81 行 self.ccode = '0401' 改成 self.ccode = '0502'

给力

**Comment by icase** [comment]
@JiangDing1990 @soimort 我的是最新版本04.909修改了self.ccode为0502，依然显示客户端201无法下载。MAC系统

**Comment by huzy0909** [comment]
@icase 把连接发出来，是一个视频不能下载，还是所有的都不能下载？

**Comment by icase** [comment]
@huzy0909 是优酷的都不能下载，都是我修改了也提示201。其他的网站没问题。测试过了。

**Comment by huzy0909** [comment]
@icase 你应该是没有改对，我这边优酷的都能下载，速度也很快，你改成0406试试，我现在是 0406

**Comment by Syh15198462** [comment]
Ubuntu17.04通过pip3安装后的youku.py路径在这里
./usr/local/lib/python3.5/dist-packages/you_get/extractors/youku.py

**Comment by JiangDing1990** [comment]
我的另一台mac通过`pip3`安装的，文件路径是这个 ```/usr/local/lib/python3.6/site-packages/you_get/extractors/youku.py```  把第81行的`0401`改为`0502`也解决问题了。。对了，我先升级到最新版本的`you-get`了，然后改的`self.ccode`为`0502`。。使用命令```pip3 install --upgrade you-get```升级到最新，我的版本现在是0.4.964。试试看吧 @icase

**Comment by Cappuccin0** [comment]
改为0502后可用 Thanks @lll423
