### ISSUE TITLE
无法下载完整程度的优酷视频

### ISSUE THREAD

**Issue by apollopy** [soimort/you-get#390]
例子 http://v.youku.com/v_show/id_XNzM3OTM0OTEy.html
下载下来只有40分钟

**Comment by danran-php** [comment]
![image](https://cloud.githubusercontent.com/assets/12946324/9986677/22640a6a-6072-11e5-8f77-2a8c068cf633.png)

http://v.youku.com/v_show/id_XMTM0MDkxMjc5Mg==_ev_1.html?from=y1.3-idx-uhome-1519-20887.205805-205902.1-1&x

**Comment by zhangn1985** [comment]
1, 通过``http://play.youku.com/play/get.json?vid=XNTc2NDk2MDMy&ct=10&ran=8005``
取得视频信息
2, 通过``http://k.youku.com/player/getFlvPath/sid/744845891090910acc6e6_00/st/flv/fileid/030002100051D4531BE14405CF07DD46D1E90B-DAB6-BA76-3252-99CDEB847AFF?K=84b30437b33b79ff24126b09&hd=0&myp=0&ts=369&ymovie=1&ypp=2&ctype=10&ev=1&token=4260&oip=1988458793&ep=Txai2dzSN0Uxvss9FblhBz54rGo2Ars1izYvuKUEuBNbktXlq14wrDtYj8UAsensj5lKNf4YbcyM5t0Je%2F1w1PBa6jeG0HvJlgAURfKXZ5h89ueWjTFQKQxmOhKBFKDNxNgDySjstls%3D&yxon=1&special=true``
取得分段信息

**Comment by zhangn1985** [comment]
其中K，fileid，oip，是直接由1得出，其余需要计算。目前没找到方法。
https://github.com/soimort/you-get/pull/463 已经失效。

**Comment by danran-php** [comment]
昨天就更新了

**Comment by zhangn1985** [comment]
就是因为更新了所以 #463 已经失效。

**Comment by zhangn1985** [comment]
经我调查，我们代码里面请求视频的api_url：
``http://play.youku.com/play/get.json?vid=XNTc2NDk2MDMy&ct=12``
这个api 目前无法获得完整的视频分段信息。这也是 #463 失效的原因。
能获得完整信息的api是
``http://play.youku.com/play/get.json?vid=XNTc2NDk2MDMy&ct=10``

但简单改这个api是完全没用的。
因为``ct=12``对应的算法是优酷的js算法，这个还比较好办，也是我们代码里面已经写好的。
而``ct=10``对应的是优酷swf里面的算法，我反汇编过，但具体到ep, sid, token等，就很麻烦。

而js算法和swf算法完全不一样。 直接把js算法套用到``ct=10``上得到的是程序逻辑错误。

我目前的研究结果就是，必须深入研究swf算法。

**Comment by danran-php** [comment]
对的，可是那个flash看的晕。
有机会加q讨论
没法调试flash
as3.0反编译后就编译不回去了

**Comment by zhangn1985** [comment]
```
         if(param2.ep)
         {
            _loc17_ = PlayListUtil.getInstance().getSize(param2.ep);
            _loc18_ = _loc17_.split("_");
            param1.sid = _loc18_[0];
            param1.tk = _loc18_[1];
         }
```
```
         var _loc12_:String = param2.sid + "_" + param3.fileId + "_" + param2.tk;
         _loc12_ = _loc12_ + ("_" + PlayerConfig.bctime);
         _loc13_ = PlayListUtil.getInstance().changeSize(_loc12_);
         _loc6_ = _loc6_ + ("&ep=" + PlayListUtil.getInstance().setSize(_loc12_ + "_" + _loc13_.substr(0,4)));
```
这就是算sid, token, ep的算法。
但是getSize, changeSize， 采用了``Alchemy``技术，不知道怎么看了。

暂时作为日记记录下来。

**Comment by linhua55** [comment]
@zhangn1985 
也是到这里卡了下来，不过 @boyxuper  在 https://github.com/soimort/you-get/issues/331#issuecomment-46515104 说js的算法和swf的一样。
不知道set/get/changeSize的实现有没有改?可以试一下。
用ct=12得到的分段没有1080p，而用ct=10得到的分段有1080p。

**Comment by zhangn1985** [comment]
@linhua55  那个留言我也看到过，但是事实是用``ct=10``请求到的``encrypt_string``代入到js的算法中去，根本算不到sid/token，而``ct=12``的``encrypt_string``就能。

所以只能破解swf的算法。

**Comment by linhua55** [comment]
@zhangn1985 
1.ct=12 得到的encrypt_string 的长度是36，而ct=10 得到的encrypt_string 的长度是44。
在 https://github.com/soimort/you-get/issues/331#issuecomment-46515104 中， @boyxuper 给出的例子中ep的长度也是44。用提供的程序检验，得到的token是空，sid是乱码。
2.用ct=12 得到的视频的hd2分段（json数据中的segs）只有50分钟，而用ct=10 能得到全部（使用的是k.youku.com的地址）。
如
you-get -u --format=hd2 http://v.youku.com/v_show/id_XNTc2NDk2MDMy 
下面使用的是ct=12的例子，虽然能用，但还是不完整
https://gist.github.com/linhua55/eca0272147454a4cfe1b

**Comment by zhangn1985** [comment]
@linhua55  我跟你观察的结果是一样的，ct=12下载的视频不完整，而ct=10 js算法不支持。

**Comment by zhangn1985** [comment]
另外，我用iphone5的UA，网页播放视频，浏览器得到的m3u8也是不完整的。所以我想一定是有后续请求，不然视频就看不完了。

**Comment by danran-php** [comment]
确实看不完，除非带上优酷会员的cookie

**Comment by zhangn1985** [comment]
没什么好讲了哦，散会~~~
看代码

**Comment by danran-php** [comment]
ct=10的key不同，代码在flascc中，有大触知道方法吗

**Comment by leeeboo** [comment]
@danran-php 代码在flask中是什么意思？

**Comment by danran-php** [comment]
@leeeboo flascc 自己百度

**Comment by leeeboo** [comment]
Flascc和优酷啥关系 还有哈 好久不百度了 一般都google

2015年12月22日星期二，danran-php <notifications@github.com> 写道：

> @leeeboo <https://github.com/leeeboo> flascc 自己百度
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soimort/you-get/issues/390#issuecomment-166494369>.
>


-- 
李博

我们是搞开发的

<http://t.sina.com.cn/1749026125?s=6uyXnP>
