### ISSUE TITLE
[Failed] LETV

### ISSUE THREAD

**Issue by zmchu** [soimort/you-get#419]
/opt/python3.3/bin/you-get http://www.letv.com/ptv/vplay/1744455.html
Video Site: letv.com
Title:      敢死队2
Type:       Flash video (video/x-flv)
Size:       0.27 MiB (279110 Bytes)

Downloading 敢死队2.flv ...
100.0% (  0.3/0.3  MB) [========================================] 1/1

>> But the flv file is an advertisement, not a movie.

**Comment by freeyoung** [comment]
+1

**Comment by asuna** [comment]
Met the same problem.

**Comment by soimort** [comment]
Fixed by #493.
