### ISSUE TITLE
腾讯视频下载支持

### ISSUE THREAD

**Issue by lvqier** [soimort/you-get#443]
Hi，我新写了一个下载腾讯视频的：https://github.com/lvqier/crawlers/blob/master/txsp/txsp.py 可以更新啦

**Comment by pikeszfish** [comment]
Hi，我根据@lvqier 提供的改成python3下的
https://github.com/pikeszfish/you-get/blob/develop/src/you_get/extractor/qq.py
现在一般的qq视频的页面可以解析了，部分视频页面做了特效好像不行(如http://v.qq.com/wuzetian/index.htm )
然后可以下载到视频的分片

但有几个问题
1、在合并几个文件的时候，出现
  File "/you-get/src/you_get/processor/join_mp4.py", line 665, in read_atom
    return atom_readers[type](stream, size, left, type)
  File "/you-get/src/you_get/processor/join_mp4.py", line 244, in read_hdlr
    assert stream.read(1) == b'\x00'
AssertionError

2、acfun解析qq的视频没有进行测试

**Comment by soimort** [comment]
关于mp4合并：不推荐使用 join_mp4.py，建议安装 FFmpeg。

如果一定需要 join_mp4 的话，#466 应该可以解决这个问题。

**Comment by pikeszfish** [comment]
装了FFmpeg之后，合并已经可以了
acfun好像原来方法不行，而且源好像是letv的了，不需要qq这个解析了？

**Comment by soimort** [comment]
@pikeszfish acfun 你指的是具体哪个视频？

**Comment by pikeszfish** [comment]
啊，我的意思是，看到acfun.py里面原本有调用qq.py的接口来解析的，但我没去测过
https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/acfun.py   
用了from .qq import qq_download_by_id
但现在qq改了

但dev分支去解析acfun，现在好像不能用了的，没有输出

所以，我这个修改，只保证腾讯视频能够解析
