### ISSUE TITLE
ERROR: download pptv video 

### ISSUE THREAD

**Issue by wyx0578** [soimort/you-get#447]
OS:window 7
you-get -u http://v.pptv.com/show/xt7FQ6sRgb8iaoAg.html
========following is one clip ===============
http://ccf.pptv.com/14/05c37a2e9818fd8bcafe6af18beaf668.mp4?key=1aa3ca1fe388e809108a0ad90a9bc5a9&fpp.ver=1.3.0.4&k=a8167bd73f6018242d91e895667c4d20-bde7-1416211806&type=web.fpp
chorme:  403 error

you-get  http://v.pptv.com/show/xt7FQ6sRgb8iaoAg.html
==================================================
Downloading \\xe8\\xaf\\xb7\\xe4\\xbd\\xa0\\xe9\\x97\\xad\\xe5\\x98\\xb4.mp4 ...

Video Site: PPTV.com
Title:      \xe8\xaf\xb7\xe4\xbd\xa0\xe9\x97\xad\xe5\x98\xb4
Type:       MPEG-4 video (video/mp4)
Size:       282.05 MiB (295754051 Bytes)

Downloading \\xe8\\xaf\\xb7\\xe4\\xbd\\xa0\\xe9\\x97\\xad\\xe5\\x98\\xb4.mp4 ...

Video Site: PPTV.com
Title:      \xe8\xaf\xb7\xe4\xbd\xa0\xe9\x97\xad\xe5\x98\xb4
Type:       MPEG-4 video (video/mp4)
Size:       282.05 MiB (295754051 Bytes)

Downloading \\xe8\\xaf\\xb7\\xe4\\xbd\\xa0\\xe9\\x97\\xad\\xe5\\x98\\xb4.mp4 ...

Video Site: PPTV.com
Title:      \xe8\xaf\xb7\xe4\xbd\xa0\xe9\x97\xad\xe5\x98\xb4
Type:       MPEG-4 video (video/mp4)
Size:       282.05 MiB (295754051 Bytes)

Downloading \\xe8\\xaf\\xb7\\xe4\\xbd\\xa0\\xe9\\x97\\xad\\xe5\\x98\\xb4.mp4 ...

**Comment by yangl326-Dylan** [comment]
405error now.

**Comment by gumplee** [comment]
400 bad request error ，pptv.py这里调用自身会陷入死循环
if not info_only:
        try:
            download_urls(urls, title, 'mp4', total_size, output_dir = output_dir, merge = merge)
        except urllib.error.HTTPError:
            #for key expired
            pptv_download_by_id(id, output_dir = output_dir, merge = merge, info_only = info_only)

解决的方向应该是哪里？最后组装的request已经过期了么？

**Comment by ckz1211** [comment]
给楼主一个暂时的解决办法，目前维棠可以下载PPTV的高清视频：
http://vidown.cn/
不过还是希望作者尽快修复PPTV的问题，因为维棠曾因为被警告而先后取消了对爱奇艺和优土豆的支持，我觉得维棠早晚也会取消对PPTV的支持……

**Comment by zmwangx** [comment]
I know this issue is almost two years old, but here's a small update: at the moment we can't even run `get_html` on a `v.ppty.com/show` page without a cookie, which means we can't even extract the video id. However, the cookie is relatively easy to construct:

```sh
$ curl -sS -c - -o /dev/null 'http://c1.pptv.com/puid/get?cb=jQuery&format=jsonp'
# Netscape HTTP Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

.pptv.com	TRUE	/	FALSE	2102235756	PUID	3335a148a4b25bb4e56a8307788a0dd4
.pptv.com	TRUE	/	FALSE	2102235756	PUID_CTM	1471515756
$ curl http://tools.aplusapi.pptv.com/get_ppi
({"ppi":"302c3532"})
$ # Construct cookie header with PUID, PUID_CTM and ppi for vid extraction
$ curl -sS -H 'Cookie:PUID=d619c2bfbf8de0f7edaa7b101e26cde8; PUID_CTM=1471511173; ppi=302c3532' http://v.pptv.com/show/of7mZc0zoibFEwiao.html | grep -Po '(?<=webcfg = \{"id":)\d+'
24994209
```

I haven't looked at the video extraction part (and don't have time at the moment), which is probably far more problematic.
