### ISSUE TITLE
下载优酷视频不完整

### ISSUE THREAD

**Issue by gmg137** [soimort/you-get#450]
我用 you-get 从优酷下载电影疯狂原始人,费了半天下好却发现只下载了一半。
然后我用：
you-get -u --format=hd2 http://v.youku.com/v_show/id_XNTc2NDk2MDMy
看到的下载链接只有 13 个，但我用飞驴分析的地址却有31个
http://www.flvxz.com/?url=aHR0cDojI3YueW91a3UuY29tL3Zfc2hvdy9pZF9YTlRjMk5EazJNRE15

**Comment by phpengineer** [comment]
优酷长一点的视频都是分成多个流下载，下载后需要合并，you-get分析出下载地址后，可以自己Axel多线程下载下来，然后通过ffmpeg合并

**Comment by soimort** [comment]
Duplicate of #390.
