### ISSUE TITLE
Only get 40 minutes in Youku

### ISSUE THREAD

**Issue by tq04t46** [soimort/you-get#451]
I have tried many youku video but all only get a 40 minutes file.

**Comment by soimort** [comment]
Interesting. Given such a `m3u8` URL, we might find an alternative way to get full-length videos, besides #463...

**Comment by maosong1019** [comment]
yes, it seems a problem. I got same issue.

root@MSX61:~/git/you-get# python3 ./you-get --format=hd2 http://v.youku.com/v_show/id_XODQwMTY4NDg0.html
site:                优酷 (Youku)
title:               一个人的武林
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          826.7 MiB (866897697 bytes)
    # download-with: you-get --format=hd2 [URL]

Downloading 一个人的武林.flv ...
 43.4% (358.6/826.7MB) [==================                      ] 13/13
Merging video parts...

**Comment by frankfuu** [comment]
seems to be happening to me too, it cuts off at around the 365-366MB mark

------------------------------------------------------------------------

you-get "http://v.youku.com/v_show/id_XODY0OTA0ODc2.html"
site:                优酷 (Youku)
title:               等一个人咖啡
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          1016.0 MiB (1065390336 bytes)
    # download-with: you-get --format=hd2 [URL]

Downloading 等一个人咖啡.flv ...
 36.0% (366.0/1016.0MB) [===============                         ] 13/13
Merging video parts...

------------------------------------------------------------------------

you-get "http://v.youku.com/v_show/id_XODY0OTA0ODc2.html"
site:                优酷 (Youku)
title:               等一个人咖啡
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          1016.0 MiB (1065390336 bytes)
    # download-with: you-get --format=hd2 [URL]

Downloading 等一个人咖啡.flv ...
 36.0% (366.0/1016.0MB) [===============                         ] 13/13
Merging video parts...

**Comment by rnt999** [comment]
For me it doesn't allow download video at all.

**Comment by A-Circle-Zhang** [comment]
@tq04t46 Could you tell me whats app are you got the m3u8 from?
