### ISSUE TITLE
Cannot download from Tudou

### ISSUE THREAD

**Issue by nemosum0908** [soimort/you-get#465]
I cannot download from tudou. I tested several different source url in tudou but it is not working.
Version of you-get is 0.3.32, Python version is 3.4.1. OS is Windows 7. (Locale is CP949 (Korean))

Message is the same below:
---------------------------------------------------------------------------------------------------------------------------
D:\you-get>python you-get http://www.tudou.com/programs/view/0rZMHoTNdi4
Video Site: Tudou.com
Title:      \xe5\x85\x94\xe5\xad\x90\xe8\x88\x9e\xe8\x8b\xb1\xe6\x96\x87\xe5\x84
\xbf\xe6\xad\x8c
Type:       Flash video (video/x-flv)
Size:       2.22 MiB (2332488 Bytes)

Downloading \\xe5\\x85\\x94\\xe5\\xad\\x90\\xe8\\x88\\x9e\\xe8\\x8b\\xb1\\xe6\\x
96\\x87\\xe5\\x84\\xbf\\xe6\\xad\\x8c.f4v ...
Traceback (most recent call last):
  File "you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "D:\you-get\src\you_get\__main__.py", line 91, in main
    main()
  File "D:\you-get\src\you_get\common.py", line 998, in main
    script_main('you-get', any_download, any_download_playlist)
  File "D:\you-get\src\you_get\common.py", line 892, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only)
  File "D:\you-get\src\you_get\common.py", line 784, in download_main
    download(url, **kwargs)
  File "D:\you-get\src\you_get\common.py", line 991, in any_download
    m.download(url, **kwargs)
  File "D:\you-get\src\you_get\extractors\tudou.py", line 56, in tudou_download
    tudou_download_by_iid(iid, title, output_dir = output_dir, merge = merge, in
fo_only = info_only)
  File "D:\you-get\src\you_get\extractors\tudou.py", line 23, in tudou_download_
by_iid
    download_urls(urls, title, ext, size, output_dir=output_dir, merge = merge)
  File "D:\you-get\src\you_get\common.py", line 512, in download_urls
    url_save(url, filepath, bar, refer = refer, faker = faker)
  File "D:\you-get\src\you_get\common.py", line 285, in url_save
    os.mkdir(os.path.dirname(filepath))
FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: '\\xe5\\x85\\x94
\\xe5\\xad\\x90\\xe8\\x88\\x9e\\xe8\\x8b\\xb1\\xe6\\x96\\x87\\xe5\\x84\\xbf\\xe6
\\xad'

D:\you-get>
---------------------------------------------------------------------------------------------------------------------------

Thank you for developing and maintaining this nice script!

**Comment by soimort** [comment]
To clarify: you-get does have a `--cookies` option, but this issue has nothing to do with cookies, UAs or download URLs, it's caused by the Windows locale (CP949). You can download this video on OS X or Linux without any problem.

See #418 for further reference. (it's not easy to handle CJK encoded strings without prior knowledge of user's code page, that's why it has not yet fixed)

**Comment by nemosum0908** [comment]
Hmm.. But, many sources that successfully downloaded with 0.3.3.0dev were output error the same message with 0.3.3.2. (For example this link: http://www.56.com/u43/v_MTMyMTUzODU2.html) So I thought that it seems a bug, not simply locale problem of Windows.

Sorry to bother you, please check one more time whether simply locale problem or not.

**Comment by Sinla** [comment]
编码问题非常难办,cmd并不能设置utf8这种支持多国语言的编码,这是个大问题
http://pan.baidu.com/s/1hquzHmW 你试试这个,覆盖掉原来的 common.py

**Comment by soimort** [comment]
> many sources that successfully downloaded with 0.3.3.0dev were output error the same message with 0.3.3.2

@nemosum0908 I'm not sure what do you mean by that.
You have two choices:

1. Use `chcp 65001` to switch to UTF-8 encoding.
2. Use PowerShell. (I always suggest Windows users to do that)

Let me know if these work for you.

**Comment by nemosum0908** [comment]
@soimort I mean that.. many video source that downloadable with 0.3.30 (old version) are not  downloadable with 0.3.32 (new version). Error message is all the same - "FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다:". 

For example, video "http://www.56.com/u43/v_MTMyMTUzODU2.html" was downloadable with you-get 0.3.30. but this video is not downloadable with you-get 0.3.32.

Result of running with your suggestion:

## 1) Using "chcp 65001" ##

Active code page: 65001

D:\you-get>dir
Volume in drive D is DATA
 Volume Serial Number is D414-0A94

 Directory of D:\you-get

The system cannot write to the specified device.

D:\you-get>python you-get http://www.56.com/u43/v_MTMyMTUzODU2.html
Video Site: 56.com
Title:      \xe3\x80\x90\xe6\x8e\x98\xe5\x9b\xbe\xe5\xbf\x97\xe3\x80\x91\xe9\xa3
\x9e\xe4\xb8\x8d\xe5\x8a\xa8\xe4\xba\x86
Type:       Flash video (video/x-flv)
Size:       1.11 MiB (1166228 Bytes)

Downloading \\xe3\\x80\\x90\\xe6\\x8e\\x98\\xe5\\x9b\\xbe\\xe5\\xbf\\x97\\xe3\\x
80\\x91\\xe9\\xa3\\x9e\\xe4\\xb8\\x8d\\xe5\\x8a\\xa8\\xe4\\xba\\x86.flv ...
Traceback (most recent call last):
  File "you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "D:\you-get\src\you_get\__main__.py", line 91, in main
    main()
  File "D:\you-get\src\you_get\common.py", line 998, in main
    script_main('you-get', any_download, any_download_playlist)
  File "D:\you-get\src\you_get\common.py", line 892, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only)
  File "D:\you-get\src\you_get\common.py", line 784, in download_main
    download(url, **kwargs)
  File "D:\you-get\src\you_get\common.py", line 991, in any_download
    m.download(url, **kwargs)
  File "D:\you-get\src\you_get\extractors\w56.py", line 29, in w56_download
    w56_download_by_id(id, output_dir = output_dir, merge = merge, info_only = i
nfo_only)
  File "D:\you-get\src\you_get\extractors\w56.py", line 25, in w56_download_by_i
d
    download_urls([url], title, ext, size, output_dir = output_dir, merge = merg
e)
  File "D:\you-get\src\you_get\common.py", line 512, in download_urls
    url_save(url, filepath, bar, refer = refer, faker = faker)
  File "D:\you-get\src\you_get\common.py", line 285, in url_save
    os.mkdir(os.path.dirname(filepath))
FileNotFoundError: [WinError 3] ì§€ì •ëœ ê²½ë¡œë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤: '\\
xe3\\x80\\x90\\xe6\\x8e\\x98\\xe5\\x9b\\xbe\\xe5\\xbf\\x97\\xe3\\x80\\x91\\xe9\\
xa3\\x9e\\xe4\\xb8\\x8d\\xe5\\x8a\\xa8\\xe4\\xba'

D:\you-get>

## 2) Using Windows PowerShell ##

PS D:\you-get> python you-get  http://www.56.com/u43/v_MTMyMTUzODU2.html
Video Site: 56.com
Title:      \xe3\x80\x90\xe6\x8e\x98\xe5\x9b\xbe\xe5\xbf\x97\xe3\x80\x91\xe9\xa3\x9e\xe4\xb8\x8d\xe5\x8a\xa8\xe4\xba\x86

Type:       Flash video (video/x-flv)
Size:       1.11 MiB (1166228 Bytes)

Downloading \\xe3\\x80\\x90\\xe6\\x8e\\x98\\xe5\\x9b\\xbe\\xe5\\xbf\\x97\\xe3\\x80\\x91\\xe9\\xa3\\x9e\\xe4\\xb8\\x8d\\x
e5\\x8a\\xa8\\xe4\\xba\\x86.flv ...
Traceback (most recent call last):
  File "you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "D:\you-get\src\you_get\__main__.py", line 91, in main
    main()
  File "D:\you-get\src\you_get\common.py", line 998, in main
    script_main('you-get', any_download, any_download_playlist)
  File "D:\you-get\src\you_get\common.py", line 892, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "D:\you-get\src\you_get\common.py", line 784, in download_main
    download(url, **kwargs)
  File "D:\you-get\src\you_get\common.py", line 991, in any_download
    m.download(url, **kwargs)
  File "D:\you-get\src\you_get\extractors\w56.py", line 29, in w56_download
    w56_download_by_id(id, output_dir = output_dir, merge = merge, info_only = info_only)
  File "D:\you-get\src\you_get\extractors\w56.py", line 25, in w56_download_by_id
    download_urls([url], title, ext, size, output_dir = output_dir, merge = merge)
  File "D:\you-get\src\you_get\common.py", line 512, in download_urls
    url_save(url, filepath, bar, refer = refer, faker = faker)
  File "D:\you-get\src\you_get\common.py", line 285, in url_save
    os.mkdir(os.path.dirname(filepath))
FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: '\\xe3\\x80\\x90\\xe6\\x8e\\x98\\xe5\\x9b\\xbe\\xe5\\xbf
\\x97\\xe3\\x80\\x91\\xe9\\xa3\\x9e\\xe4\\xb8\\x8d\\xe5\\x8a\\xa8\\xe4\\xba'
PS D:\you-get>


Both Using chcp and Using Powershell were not working.... Only ubuntu with virtual machine is my hope? :-)

**Comment by soimort** [comment]
@nemosum0908 Interesting. If you-get 0.3.30 works for you while 0.3.32 doesn't, then it should be a regression issue.

Can you post your command-line output when you **can** download these videos? Also, please indicate which exact version of you-get 0.3.30 were you using (is it `0.3.30` or `0.3.30dev-2014xxyy`?)

**Comment by nemosum0908** [comment]
@soimort Ah... There are several version of you-get 0.3.30... I didn't know that. (I met this script in July 2014.) All data are below which you asked. I wish these data is useful.

### 1) Result of running with -V (with 0.3.30) ###

D:\you-get>python you-get -V
You-Get 0.3.30dev-20140629, a video downloader.

D:\you-get>

### 2) output when I downloaded successfully with 0.3.30dev (I think that it is useful, I am running with --debug option.) ###

D:\you-get>python you-get -V
You-Get 0.3.30dev-20140629, a video downloader.

D:\you-get>python you-get --debug http://www.56.com/u43/v_MTMyMTUzODU2.html
Video Site: 56.com
Title:      \xe3\x80\x90\xe6\x8e\x98\xe5\x9b\xbe\xe5\xbf\x97\xe3\x80\x91\xe9\xa3
\x9e\xe4\xb8\x8d\xe5\x8a\xa8\xe4\xba\x86
Type:       Flash video (video/x-flv)
Size:       1.11 MiB (1166228 Bytes)

Downloading \xe3\x80\x90\xe6\x8e\x98\xe5\x9b\xbe\xe5\xbf\x97\xe3\x80\x91\xe9\xa3
\x9e\xe4\xb8\x8d\xe5\x8a\xa8\xe4\xba\x86.flv ...
100.0% (  1.1/1.1  MB) [========================================] 1/1


D:\you-get>

### 3) output when I failed to downloaded with 0.3.32 (I think that it is useful, I am running with --debug option.) ###

D:\you-get>python you-get -V
You-Get 0.3.32, a video downloader.

D:\you-get>python you-get --debug http://www.56.com/u43/v_MTMyMTUzODU2.html
Video Site: 56.com
Title:      \xe3\x80\x90\xe6\x8e\x98\xe5\x9b\xbe\xe5\xbf\x97\xe3\x80\x91\xe9\xa3
\x9e\xe4\xb8\x8d\xe5\x8a\xa8\xe4\xba\x86
Type:       Flash video (video/x-flv)
Size:       1.11 MiB (1166228 Bytes)

Downloading \\xe3\\x80\\x90\\xe6\\x8e\\x98\\xe5\\x9b\\xbe\\xe5\\xbf\\x97\\xe3\\x
80\\x91\\xe9\\xa3\\x9e\\xe4\\xb8\\x8d\\xe5\\x8a\\xa8\\xe4\\xba\\x86.flv ...
Traceback (most recent call last):
  File "you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "D:\you-get\src\you_get\__main__.py", line 91, in main
    main()
  File "D:\you-get\src\you_get\common.py", line 998, in main
    script_main('you-get', any_download, any_download_playlist)
  File "D:\you-get\src\you_get\common.py", line 892, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only)
  File "D:\you-get\src\you_get\common.py", line 784, in download_main
    download(url, **kwargs)
  File "D:\you-get\src\you_get\common.py", line 991, in any_download
    m.download(url, **kwargs)
  File "D:\you-get\src\you_get\extractors\w56.py", line 29, in w56_download
    w56_download_by_id(id, output_dir = output_dir, merge = merge, info_only = i
nfo_only)
  File "D:\you-get\src\you_get\extractors\w56.py", line 25, in w56_download_by_i
d
    download_urls([url], title, ext, size, output_dir = output_dir, merge = merg
e)
  File "D:\you-get\src\you_get\common.py", line 512, in download_urls
    url_save(url, filepath, bar, refer = refer, faker = faker)
  File "D:\you-get\src\you_get\common.py", line 285, in url_save
    os.mkdir(os.path.dirname(filepath))
FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: '\\xe3\\x80\\x90
\\xe6\\x8e\\x98\\xe5\\x9b\\xbe\\xe5\\xbf\\x97\\xe3\\x80\\x91\\xe9\\xa3\\x9e\\xe4
\\xb8\\x8d\\xe5\\x8a\\xa8\\xe4\\xba'

D:\you-get>

**Comment by soimort** [comment]
Let me know if the current `develop` branch works.

We have long-running problems with encoding under Windows: `cmd.exe` display / code page, Windows' filesystem restriction, etc. In order to download a video with a Chinese title under a European-only code page, we used to convert the video title into its raw byte string form, but doing so seems to raise other errors in Windows' filesystem. From now on, I decided that users should always choose the correct code page themselves.

So, if you want to download a video with a Chinese title, you might need Unicode `chcp 65001` or another code page that supports Chinese charset. Same if you want to download a video with a Korean title, the code page must support Korean charset.
I know this might not be the best solution, but I can't think of a better one at the moment. Hopefully the annoying `WinError 3` has now gone. (I haven't test the new code on a Windows machine myself, so I'll appreciate if any Windows user can provide any feedback on this issue)

**Comment by nemosum0908** [comment]
@soimort Thank you. I downloaded new 0.3.32 script and ran with chcp 65001. It successfully downloaded. it seems to be working!

Though I'm not professional programmer, I am using Perl a little for fun. So I know that charset issue (especially CJK) is very annoying one for programmer and it is very difficult problem to solve. So I am satisfied because this script is working correctly, though a little bit complicated. Thank you very much!

**Comment by nemosum0908** [comment]
p.s. Another possible solution is making new option that user can make a filename manually. For example --savefilename option. I prefer to this solution.

**Comment by soimort** [comment]
There is an open issue for that, #425, but not yet implemented.

Everybody is having encoding issue with Windows code page. youtube-dl has a `--restrict-filenames` option to strip all non-ASCII characters (so you don't need a specific code page to support this), but still, users have to know their encoding beforehand.
