### ISSUE TITLE
YouKu m3u8 resolved video URLs are always 240p

### ISSUE THREAD

**Issue by wushilin** [soimort/you-get#467]
No matter which format you specify. For example:
# you-get -F hd3 http://v.youku.com/v_show/id_XODY2MjM2NjI0.html
site:                优酷 (Youku)
title:               【VP.P VS LV#1】D2L线下赛 DOTA2西瓦幽鬼0107
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          1137.2 MiB (1192491770 bytes)
    # download-with: you-get --format=hd3 [URL]

Downloading 【VP.P VS LV#1】D2L线下赛 DOTA2西瓦幽鬼0107.flv ...
  0.9% ( 10.6/1137.2MB) [                                        ] 2/11

This is wrong apparently. The number of segments should be much higher than 11 (should be close to 50)

**Comment by wushilin** [comment]
It worked well until a few days ago. meanwhile, flvcd.com resolves FLV address fine.

**Comment by soimort** [comment]
Can you check out if the [youku-full-video](https://github.com/soimort/you-get/tree/youku-full-video) branch works for you?

**Comment by wushilin** [comment]
Checked ur code and the new code should work. I will try and let u know
again tomorrow when I got chance to test. The old m3u8 method won't work
anymore.

**Comment by wushilin** [comment]
Yes this copy works! Thank you!

**Comment by soimort** [comment]
Thanks for the feedback - I'll just close this one and leave the issue to #463.
