### ISSUE TITLE
Pip Installing error on Ubuntu 14.10

### ISSUE THREAD

**Issue by XelionXS** [soimort/you-get#477]
Downloading/unpacking you-get
  Downloading you-get-0.3.32.tar.gz (70kB): 70kB downloaded
  Running setup.py (path:/tmp/pip_build_root/you-get/setup.py) egg_info for package you-get
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/you-get/setup.py", line 10, in <module>
        proj_info = json.loads(open(os.path.join(here, PROJ_METADATA), encoding='utf-8').read())
    TypeError: 'encoding' is an invalid keyword argument for this function
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/you-get/setup.py", line 10, in <module>

    proj_info = json.loads(open(os.path.join(here, PROJ_METADATA), encoding='utf-8').read())

TypeError: 'encoding' is an invalid keyword argument for this function

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/you-get
Storing debug log for failure in /home/xelion/.pip/pip.log

**Comment by soimort** [comment]
You should use pip3.


------------------------------
Den ons 21 jan 2015 03:39 PST skrev Hugo Sokolowsky:

**Comment by XelionXS** [comment]
Thanks, problem solved !

With Pip3 ->
Downloading/unpacking you-get
Downloading you_get-0.3.32-py3-none-any.whl (96kB): 96kB downloaded
Installing collected packages: you-get
Successfully installed you-get
Cleaning up...
