### ISSUE TITLE
mp4获取单段的原视频地址

### ISSUE THREAD

**Issue by xstudio** [soimort/you-get#483]
视频源文件过大时会返回多块源地址

you-get -u --format=mp4 'http://v.youku.com/v_show/id_XNzE3MTkwMTgw.html'
site:                优酷 (Youku)
title:               舌尖上的高考《高考风云》140526
stream:
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          36.5 MiB (38228124 bytes)
    # download-with: you-get --format=mp4 [URL]

Real URLs:
['http://27.221.48.210/6772241C81142839B14DAC4BCE/03000802005382B3B0750A0105B787DAB059A2-2DC3-5421-441B-ABBDBE10FA73.mp4', 'http://27.221.31.174/67727F76C323D8353D2F9144BF/03000802015382B3B0750A0105B787DAB059A2-2DC3-5421-441B-ABBDBE10FA73.mp4']

是否可以只返回mp4的单段视频地址呢？（清晰度可以是标清的）

谢谢！

**Comment by soimort** [comment]
不可能。优酷的视频源本来就是分段的，又不是YouTube。

**Comment by xstudio** [comment]
飞驴解析出的标清视频地址是单段的，不知道you-get近期是否可以增加清晰度的选项呢
