### ISSUE TITLE
-u 输出源视频地址是能不能不加逗号

### ISSUE THREAD

**Issue by imzf** [soimort/you-get#485]
因为在使用 you-get 播放视频时，播放倒下一个分段时会卡顿一下，所以我会先使用 you-get 解析出源视频地址，再用 mpv 播放
例子：you-get -u http://v.youku.com/v_show/id_XODgwNDY4NDIw.html?ev=4
site:                优酷 (Youku)
title:               第六集 艺考女神养成记 足尖上的青春
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          95.8 MiB (100436760 bytes)
    # download-with: you-get --format=hd2 [URL]

Real URLs:
['http://58.221.70.55/6571377C77F40837F022B53C55/030001040054C85A10C3791894F5A17E322106-3145-3B2B-4DC0-DB01F6894588.flv', 'http://61.147.204.232/677221196333A822404D93437B/030001040154C85A10C3791894F5A17E322106-3145-3B2B-4DC0-DB01F6894588.flv', 'http://61.147.204.231/6571D33ABDC3B822DA21CC453D/030001040254C85A10C3791894F5A17E322106-3145-3B2B-4DC0-DB01F6894588.flv', 'http://182.140.226.74/6772BCD75CB3281C1EC1BE6E93/030001040354C85A10C3791894F5A17E322106-3145-3B2B-4DC0-DB01F6894588.flv']
然后用 mpv 播放
mpv 'http://58.221.70.55/6571377C77F40837F022B53C55/030001040054C85A10C3791894F5A17E322106-3145-3B2B-4DC0-DB01F6894588.flv' 'http://61.147.204.232/677221196333A822404D93437B/030001040154C85A10C3791894F5A17E322106-3145-3B2B-4DC0-DB01F6894588.flv' 'http://61.147.204.231/6571D33ABDC3B822DA21CC453D/030001040254C85A10C3791894F5A17E322106-3145-3B2B-4DC0-DB01F6894588.flv' 'http://182.140.226.74/6772BCD75CB3281C1EC1BE6E93/030001040354C85A10C3791894F5A17E322106-3145-3B2B-4DC0-DB01F6894588.flv' --cache-default=8000 --cache-seek-min=300 --merge-files
这样就不会卡滞和黑屏了，不过每次都要去掉逗号实在是太麻烦了！所以希望在输出源视频地址时可以不加逗号。

**Comment by linhua55** [comment]
可以指定播放器播放
>you-get -p mpv http://v.youku.com/v_show/id_XODgwNDY4NDIw.html\?ev\=4

**Comment by pastebt** [comment]
你要是在linux下，自己直接加后处理：

you-get -u http://v.youku.com/v_show/id_XODgwNDY4NDIw.html?ev=4 | tr "[]," "   "

**Comment by imzf** [comment]
@linhua55  指定的播放器在播放多分段视频时会黑屏卡滞一下的

**Comment by imzf** [comment]
@pastebt 谢谢

**Comment by linhua55** [comment]
@imzf  可在-p参数里加入选项。
>you-get -p "mpv  --cache-default=8000 --cache-seek-min=300 --merge-files" http://v.youku.com/v_show/id_XODgwNDY4NDIw.html\?ev\=4
