### ISSUE TITLE
乐视视频取到的地址是广告...

### ISSUE THREAD

**Issue by Geew** [soimort/you-get#490]
$ you-get -u http://www.letv.com/ptv/vplay/835594.html
Video Site: LeTV.com
Title:      倚天屠龙记邓超版02
Type:       Flash video (video/x-flv)
Size:       0.27 MiB (279110 Bytes)
Real URLs:
['http://183.61.63.81/78/34/110/letv-uts/14/ver_00_16-24748008-avc-404076-aac-32000-4960-279110-e043c7f8ed53f6b665add55ea348a6a1-1405055263771.letv?crypt=5aa7f2e97&b=418&nlh=3072&nlt=45&bf=19&p2p=1&video_type=mp4&termid=1&tss=no&geo=CN-19-248-1&tm=1423144800&key=b4b69a710735e9c1215d2b8ca2f49635&platid=3&splatid=301&its=0&keyitem=platid,splatid,its&ntm=1423144800&nkey=b4b69a710735e9c1215d2b8ca2f49635&proxy=2030989149,2002892184&m3v=1&mmsid=21547390&playid=0&vtype=13&cvid=1609880064882&ctv=pc&hwtype=un&ostype=Linux&tag=letv&sign=letv&tn=0.18303503974726976&pay=0&iscpn=f9051&rateid=1300&errc=0&gn=605&buss=4701&qos=4&cips=202.104.136.197']

**Comment by Geew** [comment]
版本号 You-Get 0.3.32, a video downloader. 
开发版

**Comment by soimort** [comment]
Fixed by #493.
