### ISSUE TITLE
能否添加一个文件选项

### ISSUE THREAD

**Issue by maonx** [soimort/you-get#491]
您好，能否添加一个文件选项，可以把网址都放在文件中，用此文件作参数

**Comment by linhua55** [comment]
可利用管道符号，加xargs命令实现。如：
>cat file.txt|xargs  you-get

**Comment by maonx** [comment]
好的，谢谢了 今天上午折腾了一上午，刚试出来用 python3 `cat file.txt` ,我试试你的去

**Comment by soimort** [comment]
Duplicated #325.
