### ISSUE TITLE
下载多个链接，文件判断问题

### ISSUE THREAD

**Issue by maonx** [soimort/you-get#492]
我在下载时 把整部电视剧的url都输入进去了，下载的时候有时就会下载不动，当我重启下载的时候，判断是否下载过的文件时有问题，文件已经存在了的 还是继续下载了，我没有加 `-f` 命令。

**Comment by soimort** [comment]
报issue时请给出：
1. 具体URL
2. 具体命令行参数
3. 所有输出。

否则不予修复。
