### ISSUE TITLE
Letv Failed

### ISSUE THREAD

**Issue by mysucklife** [soimort/you-get#499]
Letv just downloading the ads, not the video, please fix it ASAP, thank you!

**Comment by jackyzy823** [comment]
pls update to the latest version of you-get

for me ,it works.
see below:
$ python3 you-get http://www.letv.com/ptv/vplay/835594.html
Current Video Supports:
	--format 1300 <URL>
	--format 1000 <URL>
	--format 350 <URL>
Video Site: LeTV.com
Title:      倚天屠龙记邓超版02
Type:       MPEG-4 video (video/mp4)
Size:       321.67 MiB (337292868 Bytes)

Downloading 倚天屠龙记邓超版02.mp4 ...
  3.6% ( 11.7/321.7MB) [==                                      ] 10/160

**Comment by SuperN0va** [comment]
下载没问题，但是合并有问题

**Comment by allencch** [comment]
Merge problem, I solved with "cat" (concatenate) into one file. But this will lose the video duration information. So, I run the following command,
`ffmpeg -i combined.mp4 -c copy -bsf:a aac_adtstoasc fixed.mp4`

**Comment by soimort** [comment]
Closing.

Please open another issue if it's still relevant, remember to include the video URL when reporting (otherwise there's no way we can fix it!)
