### ISSUE TITLE
真的支持斗鱼和战旗吗？

### ISSUE THREAD

**Issue by al123xiaaaa** [soimort/you-get#507]
you-get -p smplayer 'http://www.douyutv.com/2211'
Video Site: douyutv.com
Title:      七煌独播2015OGNLOL春季赛
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

这是运行在 Linux 上的 SMPlayer v. 0.8.6
-------------------------------------------------------------------
什么都没显示诶

**Comment by yan12125** [comment]
鬥魚最近改了取得網址的方法，我寫了一份patch送到 rg3/youtube-dl#5311，可以試試看我的 https://github.com/yan12125/youtube-dl

**Comment by al123xiaaaa** [comment]
直接用smplayer看斗鱼，感觉好酷！

**Comment by soimort** [comment]
斗鱼的支持早已失效了，如果没有人愿意修复的话，恐怕也要放弃支持（我自己并不care这两个网站） :tired_face:

**Comment by guest6379** [comment]
@yan12125 很贊！用了你的patch果然可以下鬥魚的視頻了，台灣水平果然厲害！

**Comment by zhangn1985** [comment]
https://github.com/soimort/you-get/pull/631
是可以被merge的。只是楼主报告的链接要用-l来支持，只是因为room_id取得不太对。
