### ISSUE TITLE
新手求教

### ISSUE THREAD

**Issue by lele2010lele** [soimort/you-get#513]
大家好，这软件我昨天刚听说。所以不会用，所以请大家教教我。
1，这软件要在哪个系统上用啊？mac还是windows？
2，运行哪个文件才能进行下载啊？求告知
3，下载YouTube的时候要设置代理，请问在哪里设置啊

**Comment by fluviusmagnus** [comment]
既然你已经来了这里就请到项目首页读文档，那里写得很详细。

**Comment by lele2010lele** [comment]
谢谢，但是英文的有点困难

**Comment by imzf** [comment]
@lele2010lele [中文说明](https://github.com/soimort/you-get/wiki/%E4%B8%AD%E6%96%87%E8%AF%B4%E6%98%8E)

**Comment by fr0zenrain** [comment]
@lele2010lele http://lieying.ilewo.cn/ 试试这个。

**Comment by soimort** [comment]
[中文说明](https://github.com/soimort/you-get/wiki/%E4%B8%AD%E6%96%87%E8%AF%B4%E6%98%8E) +1
