### ISSUE TITLE
要是能加一个断点续传的功能(选项)就好了

### ISSUE THREAD

**Issue by liangyaozhan** [soimort/you-get#517]
要是能加一个断点续传的功能(选项)就更好了.

**Comment by soimort** [comment]
然而下载的 `.download` 文件本来就是支持断点续传的。
https://github.com/soimort/you-get/wiki/%E4%B8%AD%E6%96%87%E8%AF%B4%E6%98%8E#%E6%96%AD%E7%82%B9%E7%BB%AD%E4%BC%A0
