### ISSUE TITLE
Can I use this in python code?

### ISSUE THREAD

**Issue by gengjiawen** [soimort/you-get#518]
For example,I have a video url, how do I get the video download url using python code instead of do it in terminal?

**Comment by jackyzy823** [comment]
`you-get -u <video-url>`

**Comment by gengjiawen** [comment]
@jackyzy823 I want to use it in python code in native way,not something like subprocess.Popen().

**Comment by yan12125** [comment]
```any_download``` and ```any_download_playlist``` functions in [common.py](https://github.com/soimort/you-get/blob/develop/src/you_get/common.py#L991-L997) might be helpful. For example:
```Python
from you_get.common import any_download
any_download('http://www.youtube.com/watch?v=ma-V4Lr-Kiw', info_only=False, output_dir='.', merge=False)
```
Note that these codes are my straightforward snippets arising from studying the source code of you-get. I can't find official tutorials/examples on how to embed you-get in python-based applications, either. There's no guarantee that such a usage is proper for different sites, or it will work when you-get changes its internal implementation in the future.

**Comment by soimort** [comment]
The current API needs a complete refactor to better support this. For now, you can just use `any_download`, or call `you-get` directly from command-line with `--json` option. The JSON output should have everything you need.

Closing.
