### ISSUE TITLE
TypeError: tudou (-y proxy.uku.im:8888)

### ISSUE THREAD

**Issue by porloser** [soimort/you-get#524]
run with command
```
you-get -y proxy.uku.im:8888 http://www.tudou.com/programs/view/0TN42zfyAwM
```
get error 
```
TypeError: tudou_download() got an unexpected keyword argument 'extractor_proxy'
```
log
```
you-get -y proxy.uku.im:8888 http://www.tudou.com/programs/view/0TN42zfyAwM

Traceback (most recent call last):
  File "\Python34\lib\runpy.py", line 170, in _run_mod
ule_as_main
    "__main__", mod_spec)
  File "\Python34\lib\runpy.py", line 85, in _run_code

    exec(code, run_globals)
  File "\Python34\Scripts\you-get.exe\__main__.py", li
ne 9, in <module>
  File "\Python34\lib\site-packages\you_get\__main__.p
y", line 91, in main
    main()
  File "\Python34\lib\site-packages\you_get\common.py"
, line 998, in main
    script_main('you-get', any_download, any_download_playlist)
  File "\Python34\lib\site-packages\you_get\common.py"
, line 894, in script_main
    download_main(download, download_playlist, args, playlist, extractor_proxy=e
xtractor_proxy, output_dir=output_dir, merge=merge, info_only=info_only)
  File "\Python34\lib\site-packages\you_get\common.py"
, line 784, in download_main
    download(url, **kwargs)
  File "\Python34\lib\site-packages\you_get\common.py"
, line 991, in any_download
    m.download(url, **kwargs)
TypeError: tudou_download() got an unexpected keyword argument 'extractor_proxy'
```

**Comment by jackyzy823** [comment]
works well for me.
You may update to the latest version of you-get.
you-get -y proxy.uku.im:8888 http://www.tudou.com/programs/view/0TN42zfyAwM
Video Site: Tudou.com
Title:      《罗小黑战记》第十六集
Type:       Flash video (video/x-flv)
Size:       25.94 MiB (27200927 Bytes)

Downloading 《罗小黑战记》第十六集.f4v ...
100.0% ( 25.9/25.9 MB) [========================================] 1/1

**Comment by porloser** [comment]
i'm not sure is it the latest version
 ```You-Get 0.3.32, a video downloader```
, and i upgrade it by
```pip3 install --upgrade you-get```
but the problem still exist

**Comment by jackyzy823** [comment]
yes, i checkout the version v0.3.32 by `git checkout v0.3.32 `,and this problem appears.since there are many commits after the relese of v0.3.32,this problem may be fixed in some commits.
there are two ways for you to handle this problem. 1) get you-get source code from github to keep pace with. 2) wait for @soimort to make a new release.

**Comment by porloser** [comment]
Thank you @jackyzy823 , i finally solve that problem. 
you are so nice :+1:
