### ISSUE TITLE
你好，请问you get 有编程接口吗？

### ISSUE THREAD

**Issue by xsjqqq123** [soimort/you-get#529]
用you-get -i url输出的格式不太好利用，是否有json的接口？

**Comment by xsjqqq123** [comment]
或能否修改成运行在服务器上

**Comment by mozbugbox** [comment]
[Web GUI 图形界面](https://github.com/mozbugbox/you-get/wiki/Web-GUI-图形界面)

**Comment by yan12125** [comment]
如果是用Python，可以參考我的[comment](https://github.com/soimort/you-get/issues/518#issuecomment-100285869)

**Comment by xsjqqq123** [comment]
如果you-get -i url能输出json就好了……。我打算重写我以前的一个开源视频客户端，用您的这个进行解析。可惜似乎you-get不够稳定啊，不知道是不是我个人电脑上的问题，贴出来帮看下，谢谢。
我试了下优酷正常，乐视视频下载到的是广告……爱奇艺、搜狐、腾讯出错。不知道是不是个人问题，出错信息类似下面：
python3 you-get -i http://tv.sohu.com/20140317/n396758747.shtml
                                       
Traceback (most recent call last):
  File "you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/deepin/you-get/src/you_get/__main__.py", line 91, in main
    main()
  File "/home/deepin/you-get/src/you_get/common.py", line 1001, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/deepin/you-get/src/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/deepin/you-get/src/you_get/common.py", line 785, in download_main
    download(url, **kwargs)
  File "/home/deepin/you-get/src/you_get/common.py", line 994, in any_download
    m.download(url, **kwargs)
  File "/home/deepin/you-get/src/you_get/extractors/sohu.py", line 20, in sohu_download
    assert vid
AssertionError

**Comment by sceext2** [comment]
you-get 的 有些解析算法, 可能已经过时了. 
所以可能无法使用.

**Comment by sceext2** [comment]
you-get 好像没有 json 格式输出. 
可以自己加上一个. 
可以看看 我加的 json 格式输出 <https://github.com/sceext2/you_get>

> ```
> $ ./you-get --json "http://v.youku.com/v_show/id_XOTIwNTA4NDAw.html"
> {
>     "video": [
>         {
>             "quality": "超清",
>             "site": "优酷 (Youku)",
>             "size": 408089728,
>             "title": "封神英雄 72",
>             "type": "flv",
>             "url": [
>                 "http://119.147.157.237/67753100EF33081C3658CD511B/0300010E005513EF3CEAA503BAF2B125BFB764-002B-1103-DD7C-190A1A263348.flv",
>                 "http://182.140.226.132/67760E8055539820245A806BFD/0300010E015513EF3CEAA503BAF2B125BFB764-002B-1103-DD7C-190A1A263348.flv",
>             /* 此处省略一部分 */
> ```

**Comment by nutcrackers2** [comment]
不错不错，

**Comment by xsjqqq123** [comment]
呃，出错的原因是我下载到主分支的了，而develope分支没问题……这些视频分片也太多了吧，乐视的100片以上￥……&￥&#

**Comment by soimort** [comment]
Closing via #676.
