### ISSUE TITLE
bilibili 已失效

### ISSUE THREAD

**Issue by rchen9012** [soimort/you-get#531]
python3 you-get http://www.bilibili.com/video/av1074223
Traceback (most recent call last):
  File "you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/var/www/docs/you-get-develop/src/you_get/__main__.py", line 91, in main
    main()
  File "/var/www/docs/you-get-develop/src/you_get/common.py", line 1001, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/var/www/docs/you-get-develop/src/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/var/www/docs/you-get-develop/src/you_get/common.py", line 785, in download_main
    download(url, **kwargs)
  File "/var/www/docs/you-get-develop/src/you_get/common.py", line 994, in any_download
    m.download(url, **kwargs)
  File "/var/www/docs/you-get-develop/src/you_get/extractors/bilibili.py", line 130, in bilibili_download
    title = unescape_html(title)
  File "/usr/local/lib/python3.4/html/__init__.py", line 130, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable

**Comment by sffxzzp** [comment]
视频已经被删除了当然无法下载。。

**Comment by rchen9012** [comment]
不好意思，没有检测那个测试视频，这个视频可以在网上看 http://www.bilibili.com/video/av2365609，  不过还是出错

python3 you-get -u "http://www.bilibili.com/video/av2365609"

Traceback (most recent call last):
  File "you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/var/www/docs/you-get-develop/src/you_get/__main__.py", line 91, in main
    main()
  File "/var/www/docs/you-get-develop/src/you_get/common.py", line 1001, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/var/www/docs/you-get-develop/src/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/var/www/docs/you-get-develop/src/you_get/common.py", line 785, in download_main
    download(url, **kwargs)
  File "/var/www/docs/you-get-develop/src/you_get/common.py", line 994, in any_download
    m.download(url, **kwargs)
  File "/var/www/docs/you-get-develop/src/you_get/extractors/bilibili.py", line 130, in bilibili_download
    title = unescape_html(title)
  File "/var/www/docs/you-get-develop/src/you_get/util/strings.py", line 10, in unescape_html
    string = re.sub(r'&#[^;]+;', _sharp2uni, string)
  File "/usr/local/lib/python3.2/re.py", line 170, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by sffxzzp** [comment]
测试了一下是appkey失效了。换一个就好>.>

**Comment by rchen9012** [comment]
怎样拿到 appkey？

**Comment by cnbeining** [comment]
别闹。

Biligrab使用的是同一个key，复测可用。

对于某些用户的某些视频（常见于海外与版权与会员的世界），使用某些自定义UA，会造成500错误。

重试，或者换个key就OK。

日志：

https://paster.li/?25eac417dd9ed7bd#6V8FPbXlsLxChwrvoNVtZ0i3a4dvxIp6at1ofRJZppA=

（竟然是WoSign的证书，你妹。有心思我会换个站。）

@rchen9012 自己申请，或者反编译。

请不要abuse他人的key，可能对他人造成困扰。

正常使用我这个key 我是不care的。别弄封了就行。

**Comment by sffxzzp** [comment]
我用的是反编译b站播放器swf得到的key，而直接用浏览器get两个key确是这个有点问题，具体没向ua上想，后来也稍微借用acdown的key测试了，和官方key一样正常。。有点魔法哦。

**Comment by cnbeining** [comment]
It's SCIENCE!

我也弄过，但是懒得用了。

创自己品牌。。。

**Comment by yan12125** [comment]
似乎Bilibili不會檢查appkey。另外一個下載器youtube-dl可以下載，但是他的appkey應該不是個合法的key
```
$ youtube-dl "http://www.bilibili.com/video/av2365609"         
[generic] av2365609: Requesting header
[redirect] Following redirect to http://www.bilibili.com/video/av2365609/
[BiliBili] 2365609: Downloading webpage
[BiliBili] 2365609: Downloading LQ video info
[BiliBili] 2365609: Downloading HQ video info
[download] Downloading playlist: 【国产】我是男神 07
[BiliBili] playlist 【国产】我是男神 07: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[download] Destination: 【国产】我是男神 07-2365609_part1.flv
[download]   6.7% of 58.78MiB at 237.59KiB/s ETA 03:56^C
ERROR: Interrupted by user
```
appkey在[這裡](https://github.com/rg3/youtube-dl/blob/1434184c577953ff6fe558ccc6751697791f4076/youtube_dl/extractor/bilibili.py#L71)

**Comment by cnbeining** [comment]
仅在某些特殊情况下。而且某几个api功能不可以使用。

当然有个神key。

Yen Chi Hsuan <notifications@github.com>于2015年5月26日星期二写道：

**Comment by cnbeining** [comment]
Just to clarify:

Bilibili会检查appkey，非法的KEY会直接报错。

但是```youtube-dl```的KEY是一个神key，所以不受限制。

Bilibili模块和Biligrab使用同一套KEY，但是UA不同。

偶尔的报错报告和UA有关，和KEY的关系正在观察中。

**Comment by yan12125** [comment]
@rchen9012 你遇到的問題和 #522 有關。這個問題在Python 3.2和Python 3.4的錯誤訊息不同

@cnbeining 我不確定哪些功能需要合法的appkey，至少http://interface.bilibili.com/playurl 不需要。這可能是Bilibili的bug。我加了以下幾行：
```Diff
diff --git a/src/you_get/extractors/bilibili.py b/src/you_get/extractors/bilibili.py
index 190d62c..b9390ed 100644
--- a/src/you_get/extractors/bilibili.py
+++ b/src/you_get/extractors/bilibili.py
@@ -98,8 +98,11 @@ def bilibili_download_by_cids(cids, title, output_dir='.', merge=True, info_only
         download_urls(urls, title, type, total_size=None, output_dir=output_dir, merge=merge)
 
 def bilibili_download_by_cid(id, title, output_dir='.', merge=True, info_only=False):
+    appkey = 'some_random_string_fjkdsjfsl'
     sign_this = hashlib.md5(bytes('appkey=' + appkey + '&cid=' + id + secretkey, 'utf-8')).hexdigest()
+    sign_this = 'another_random_string_kwle8f'
     url = 'http://interface.bilibili.com/playurl?appkey=' + appkey + '&cid=' + id + '&sign=' + sign_this
+    print(url)
     urls = [i
             if not re.match(r'.*\.qqvideo\.tc\.qq\.com', i)
             else re.sub(r'.*\.qqvideo\.tc\.qq\.com', 'http://vsrc.store.qq.com', i)
```

you-get還是work：
```
$ python3.2 ./you-get http://www.bilibili.com/video/av2365609                 
http://interface.bilibili.com/playurl?appkey=some_random_string_fjkdsjfsl&cid=3697368&sign=another_random_string_kwle8f
Video Site: bilibili.com
Title:      【国产】我是男神 07
Type:       Flash video (video/x-flv)
Size:       58.88 MiB (61744694 Bytes)

Downloading 【国产】我是男神 07.flv ...
  8.1% (  4.8/58.9 MB) [====                                    ] 1/3^C%    
```

我是在台灣測試的，中國內部可能結果不同

**Comment by cnbeining** [comment]
非法的appkey会招致更大的法律风险。

如果一定不准备使用正常的key 至少使用a这个key。

Yen Chi Hsuan <notifications@github.com>于2015年5月29日星期五写道：
