### ISSUE TITLE
如何获取视频的链接地址

### ISSUE THREAD

**Issue by ss098** [soimort/you-get#537]
基本的阅读了源码，不是太明白从哪里获取视频的链接地址（mp4 之类的），这个变量在哪里。

**Comment by linhua55** [comment]
1、请求特定url直接获取视频文件地址，或m3u8播放列表文件(里面包含分段视频文件地址)地址
2、用Flash播放器运行swf文件内的用ActionScript语言编译生成的程序，通过一定的算法得到分段的视频文件地址。所以为了获得算法，需要反编译swf文件

**Comment by cnbeining** [comment]
really depends.

我们解析不同网站的算法，看地址如何获取。

变量？没有一定之规。需要点耐心，还有运气。

建议关闭这个Issue，仅作为讨论。

**Comment by ss098** [comment]
谢谢上面两位，我可能表述的有些错误。

我希望的是通过修改 you-get 源码得到解析后的 URL 地址输出，而不是通过 you-get 去下载这个视频。

**Comment by ss098** [comment]
谢谢上面两位，我可能表述的有些错误。

我希望的是通过修改 you-get 源码得到解析后的 URL 地址输出，而不是通过 you-get 去下载这个视频。

**Comment by cnbeining** [comment]
请参考#529 。
