### ISSUE TITLE
Youku extraxtor

### ISSUE THREAD

**Issue by rnt999** [soimort/you-get#539]
Youku extrator m3u8_url doesn't contain working corect flv url.

**Comment by soimort** [comment]
Please be specific about your video URL and command-line output when reporting an issue.

**Comment by rnt999** [comment]
Thanks for reply.
The problem with M3u8 is that I am getting M3U8 file with flv url's and if I try to dowload these files it is super slow trying to download 10 minutes 6mb file and it shows only 20% (and it looks it stuck on that). I added generated m3u8 file url, but just wondering is it the right way to download file? or that issue just for me?
http://pl.youku.com/playlist/m3u8?keyframe=1&sid=0433943252199122b939b&ctype=12&oip=1358171144&ep=ciaXGUCJVcwF5yLWgT8bZX7rd35dXJZ3kmaE%2F5g1AMZALaLBzjPcqJWyTvg%3D&ts=1433943776&type=flv&vid=XMTI1Nzg0MTUzNg%3D%3D&token=8207&ev=1

**Comment by soimort** [comment]
Please specify your **VIDEO URL**, otherwise I can't tell you what the problem is, if any.

**Comment by rnt999** [comment]
Video URL: http://v.youku.com/v_show/id_XMTI1Nzg0MTUzNg==.html?f=25833127&ev=2

**Comment by soimort** [comment]
Works fine for me.
First, the full video is 64.0 MiB, not 6 MB; Second, the command-line interface of you-get never print the URL of M3U8 file. I don't know how you generated this M3U8, but every video URL on Youku expires after a time period (i.e. it's not a permanent address), which means, once your network gets stuck, those URLs will not be downloadable forever.

The suggestion is to try `you-get` multiple times (every time it generates a new set of URLs), or use `you-get -u` to find out the real URLs and download them manually.

![screenshot from 2015-06-10 23 12 21](https://cloud.githubusercontent.com/assets/342945/8086276/316ee9b8-0fc7-11e5-8bb7-d8e0a3d344c1.png)
