### ISSUE TITLE
如何删除旧版本的you-get ???

### ISSUE THREAD

**Issue by xnastudio** [soimort/you-get#554]
我发现在mac上，我好像曾经 run过 python3 setup.py 或者  pip3 install you-get 什么的。
之后在 terminal内打 you-get -V 一直显示是0.3.31旧版本。我想知道这个旧版本被安装到了什么目录。因为我想删除旧版本，却不知道旧版本在哪里？

**Comment by linhua55** [comment]
查看文件位置
which you-get
升级
pip3 install --upgrade you-get
卸载
pip3 uninstall you-get

**Comment by soimort** [comment]
以上。
