### ISSUE TITLE
哔哩哔哩只能下载最低画质。

### ISSUE THREAD

**Issue by nuomi1** [soimort/you-get#560]
latest commit 162b06028f

http://www.bilibili.com/video/av806122/

you-get 和 flvcd 下载都是 480x272 17.7MB，bilibili for Android 下载是 1280x720 74.3MB。

**Comment by cnbeining** [comment]
感谢报错，我dig一下这个问题。（在小本子上assign自己

我认为，Bilibili的API没有返回最佳分辨率。

怀疑客户端使用了SDK或者API已经更改。

加入to-do.

**Comment by typcn** [comment]
使用非浏览器的UA，会导致无法解析高清画质以及64kbps限速

**Comment by cnbeining** [comment]
然而这是违反API文档的（

想寄刀片（

**Comment by typcn** [comment]
那只能用黑科技 key 了（逃

**Comment by typcn** [comment]
或者把 客户端/Flash 的 key 拿出来（目测死得快

**Comment by debugzxcv** [comment]
应该是要加上 quality=4 参数才行.
使用 [you-get 的 appkey: 85eb6835b0a1034e](https://github.com/soimort/you-get/blob/33ee28e615063becd8c2805c03b4c86bc56c4b68/src/you_get/extractors/bilibili.py#L15)

```curl -v "http://interface.bilibili.com/playurl?appkey=85eb6835b0a1034e&cid=1170370&quality=4"```

![test1](https://cloud.githubusercontent.com/assets/5125392/9985202/aba1c2ea-6059-11e5-9277-1cffea80e592.PNG)

**Comment by typcn** [comment]
@debugzxcv 你换一个直传的

**Comment by debugzxcv** [comment]
直传是需要验证 UA 的
我所知能过验证的 UA 是 ```Mozilla/``` 和 ```bilianime/```
![test2](https://cloud.githubusercontent.com/assets/5125392/9985322/7b4fa0f0-605c-11e5-8184-a5bd4d91c8ed.PNG)

**Comment by typcn** [comment]
@debugzxcv 他们的文档规定不能用浏览器 UA，当然有一个玩文字游戏的办法，Mozilla 只是一个公司名，PKI / SSL / TLS 库 NSS 就是他们开发的 ，使用类似以下的 UA

(Example)   ProgramName/x.x ( libcurl/1.0 NSS-Mozilla/2.0 )

**Comment by debugzxcv** [comment]
新发现, 我用国外 ip 访问直传是需要 UA 验证的, 否则显示 video is encoding. 用国内 ip 不需要 UA 验证

**Comment by cnbeining** [comment]
@debugzxcv Known issue.

可以考虑fake一下XFF和X-Real-IP，参见Biligrab的实现。

**Comment by cnbeining** [comment]
回头想 我觉得Encoding纯属分发问题吧。。

话说这个issue还是不是valid？在多大意义上有？

**Comment by cnbeining** [comment]
@nuomi1 问题是否继续存在？

另：

WS的IP和解析绑定 必须从解析相同的IP才能下载。

**Comment by nuomi1** [comment]
@cnbeining 问题依旧……
特不喜欢 QQ 的源，画质差还没速度。

**Comment by cnbeining** [comment]
QQ的速度没办法。

话说这个视频 我试着点了高清 结果解析结果完全一样 URL也是。

丫玩我呢。
