### ISSUE TITLE
Please use https for youtube

### ISSUE THREAD

**Issue by bigeagle** [soimort/you-get#564]
Hi,
I found in `extractors/youtube.py` youtube url starts with `http`, which is insecure and easy to be blocked. I've tried to substitute each of them to `https` and everything seems to work fine.

Maybe it's too small for a PR, could you update this in upstream?

Cheers,
Justin

**Comment by soimort** [comment]
This reminds me that code for many other sites needs to be updated respectively, as long as they have HTTPS support (e.g. Twitter, Vine)
