### ISSUE TITLE
爱奇艺无法下载 1080p。

### ISSUE THREAD

**Issue by nuomi1** [soimort/you-get#565]
➜  ~  you-get -i http://www.iqiyi.com/v_19rrnsxt9k.html
Video Site: iQIYI.com
Title:      心理罪第1集
Type:       Flash video (video/x-flv)
Size:       341.48 MiB (358072943 Bytes)

➜  ~  iScript/flv_cmd.py http://www.iqiyi.com/v_19rrnsxt9k.html
1
  ++ pick a quality:
  1 673.6MB	1080P
  2 341.4MB	720P
  3 138.0MB	HD
  4 100.3MB	Fluency
  5 51.8MB	Speed

————————————————————

you-get latest commit 9f076a0d35
iScript latest commit 7b5173664c

**Comment by soimort** [comment]
这个视频，目前的 API 返回的只有四种画质

- 592x248 (bid: 1)
- 848x360 (bid: 2)
- 416x176 (bid: 96)
- 1280x544 (bid: 4)

**Comment by nuomi1** [comment]
「12:00 ~ 23:00 是 1080P 画质 VIP 会员专属时段」
开通 VIP 或者使用桌面版客户端可观看 1080P。
今晚再试试 VIP 时段外能否返回 1080P。

**Comment by nuomi1** [comment]
不行……

**Comment by nuomi1** [comment]
latest commit 5d47a66507，早上 10:30，可解析 1080P。
