### ISSUE TITLE
iqiyi 算法 07月09日 改动

### ISSUE THREAD

**Issue by sceext2** [soimort/you-get#569]
iqiyi 今天 (2015年07月09日) 又改动了算法. 
@jackyzy823 
新的盐是 `341c0055ad1d4e798c2b784d9dbed29f`

现在服务器还支持 旧版算法, 但是播放器已经更新了. 
可能明天就不能用旧版算法了. 

:-)

**Comment by starchou** [comment]
最近变动的好多，10号又是一个新的播放器了。持续关注中

**Comment by univert** [comment]
Iqiyi update its keys weekly.
But as per current iqiyi's algorithm, it seems impossible to automatically extract the keys. Or is it?

**Comment by sceext2** [comment]
But this time (2015-07-10) iqiyi did not change the md5 salt.
