### ISSUE TITLE
douyuTV 解析有错误

### ISSUE THREAD

**Issue by zhangn1985** [soimort/you-get#580]
代码中用：
get_html("http://www.douyutv.com/api/client/room/"+room_id)
获取JSON 请求
实际上是
http://www.douyutv.com/swf_api/room/ + room_id + ?cdn=&nofan=yes&_t=xxx&sign=zzz

例如：
http://www.douyutv.com/swf_api/room/272097?cdn=&nofan=yes&_t=23966627&sign=6556f08f3fdd4d9d943a76bad5ea179a

但我不太清楚xxx和zzz是如何生成的，所以还请大家帮忙。

**Comment by yan12125** [comment]
可以參考
https://github.com/rg3/youtube-dl
以及
https://github.com/yan12125/douyu-hack

**Comment by liushuyu** [comment]
_t is unix time / 60,i.e. convert unix time (second) to minute
sign is the salted hash.

**Comment by zhangn1985** [comment]
OK, I will try.

**Comment by zhangn1985** [comment]
搞不定，球接手。

**Comment by liushuyu** [comment]
Well, then I will have a try...

**Comment by zhangn1985** [comment]
这个方法还真有一套呀。

**Comment by zhangn1985** [comment]
关于斗鱼sign的计算，斗鱼用到了一个很高明的技术，就时loadable flash module.
player.swf 会load core.swf，调用里面的函数来算sign。但是core.swf不能被abcexport等decompiler 反编译。
所以很难搞。
