### ISSUE TITLE
Iqiyi parse error 

### ISSUE THREAD

**Issue by Freshman585** [soimort/you-get#585]
iqiyi video parse error

**Comment by Freshman585** [comment]
爱奇艺视频的加密修改了，把之前的8e29ab5666d041c3a1ea76e06dabdffb修改成7c4d2505ad0544b88c7679c65d6748a1即可

**Comment by bubifengyun** [comment]
可不可以分享获取这个加密密钥的方式？因为过一段时间就需要来寻求帮助了。
