### ISSUE TITLE
-u does not corresponds to the format specified

### ISSUE THREAD

**Issue by francis-kf-kong** [soimort/you-get#587]
Edit:  For sufficiently new (not sure how new it has to be but seems to affect to newly updated videos) videos while you can watch each format in the flash-based player (you can see the resolution difference),  `you-get -u` only gives the URL that eventually results in seemingly the same file.  Is that the normal behaviour?

This issue has been tested on youku.  Not sure if it applies to the others.

**Comment by jackyzy823** [comment]
```
you-get -u --format=hd2 http://v.youku.com/v_show/id_XMTMwNjQ5ODQ3Mg\=\=_ev_1.html 
site:                优酷 (Youku)
title:               纪中展 温城辉《最懂礼物的90后》
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          166.8 MiB (174925032 bytes)
    # download-with: you-get --format=hd2 [URL]

Real URLs:
http://140.207.235.20/697618704134783A8555895B19/030002030055C9F09079B400422C397B001289-6430-3162-C2FE-36F87BD50E1A.flv.ts
http://140.207.235.18/6573CF4662746839AF501E46FC/030002030155C9F09079B400422C397B001289-6430-3162-C2FE-36F87BD50E1A.flv.ts
http://140.207.235.12/67761870A1A3782D2505C8380C/030002030255C9F09079B400422C397B001289-6430-3162-C2FE-36F87BD50E1A.flv.ts```
```
you-get -u --format=hd3 http://v.youku.com/v_show/id_XMTMwNjQ5ODQ3Mg\=\=_ev_1.html 
site:                优酷 (Youku)
title:               纪中展 温城辉《最懂礼物的90后》
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          324.3 MiB (340053160 bytes)
    # download-with: you-get --format=hd3 [URL]

Real URLs:
http://140.207.235.20/65730C387B63F833D52E812557/030002030055C9F09079B400422C397B001289-6430-3162-C2FE-36F87BD50E1A.flv.ts
http://140.207.235.18/677555628A1418358137C44222/030002030155C9F09079B400422C397B001289-6430-3162-C2FE-36F87BD50E1A.flv.ts
http://140.207.235.12/69779E8C8E64C83EB36B973A01/030002030255C9F09079B400422C397B001289-6430-3162-C2FE-36F87BD50E1A.flv.ts
```

Real URLS are different.

**Comment by francis-kf-kong** [comment]
Ah.  Looks like it only happens to newly updated videos:

    you-get -u --format=mp4 http://v.youku.com/v_show/id_XMTMwODEzNTg2OA==.html?from=y1.6-97.3.1.5d985078c0b811e4b432
    site:                优酷 (Youku)
    title:               仙剑客栈 第一季 第18话 暖男谈穿越时空爱恋 逍遥灵儿再续前缘
    stream:
        - format:        mp4
        container:     mp4
        video-profile: 高清
        size:          79.2 MiB (83049858 bytes)
        # download-with: you-get --format=mp4 [URL]

    Real URLs:
    http://112.25.61.243/6561A947454277F54C1D67C4/030002040055CB5820F81D2BBEAFBCCA52DBF5-2BF6-F368-069E-C689BA701E22.flv.ts
    http://112.25.45.43/6562139D4E4A78EB419E5CE3/030002040155CB5820F81D2BBEAFBCCA52DBF5-2BF6-F368-069E-C689BA701E22.flv.ts
    http://112.25.51.16/6763528B2F47788F09214D51/030002040255CB5820F81D2BBEAFBCCA52DBF5-2BF6-F368-069E-C689BA701E22.flv.ts
    http://112.25.61.244/6562E83CED3C77393D715688/030002040355CB5820F81D2BBEAFBCCA52DBF5-2BF6-F368-069E-C689BA701E22.flv.ts

    you-get -u --format=hd2 http://v.youku.com/v_show/id_XMTMwODEzNTg2OA==.html?from=y1.6-97.3.1.5d985078c0b811e4b432
    site:                优酷 (Youku)
    title:               仙剑客栈 第一季 第18话 暖男谈穿越时空爱恋 逍遥灵儿再续前缘
    stream:
        - format:        hd2
        container:     flv
        video-profile: 超清
        size:          172.8 MiB (181199833 bytes)
        # download-with: you-get --format=hd2 [URL]

    Real URLs:
    http://112.25.61.243/6963528E0A35765DD67E31C3/030002040055CB5820F81D2BBEAFBCCA52DBF5-2BF6-F368-069E-C689BA701E22.flv.ts
    http://112.25.45.43/6762E837264978CBFA955802/030002040155CB5820F81D2BBEAFBCCA52DBF5-2BF6-F368-069E-C689BA701E22.flv.ts
    http://112.25.51.16/65627DE8A34B790C3CDA4047/030002040255CB5820F81D2BBEAFBCCA52DBF5-2BF6-F368-069E-C689BA701E22.flv.ts
    http://112.25.61.244/6763BCD685467872ABA729CB/030002040355CB5820F81D2BBEAFBCCA52DBF5-2BF6-F368-069E-C689BA701E22.flv.ts


Downloading the first one from each list ended up looking like the same file (same sha1sum)

**Comment by soimort** [comment]
Please try #463 to see if it fixes the issue for you.

**Comment by francis-kf-kong** [comment]
Seems to work fine now.  Thanks
