### ISSUE TITLE
iqiyi, how to update salt.如何更新爱奇艺的那个密钥？

### ISSUE THREAD

**Issue by bubifengyun** [soimort/you-get#588]
似乎过一段时间，爱奇艺就更新一下那个密钥，有没有教程我们自己获得，然后自己去修改这个密钥，就不需要每次都到这里来求助了。看到有几位朋友也有类似需求的。
这个密钥指：[#585](https://github.com/soimort/you-get/issues/585)issue

**Comment by jackyzy823** [comment]
使用任何swf的反编译工具提取出actionscript脚本，加密方法的调用者在 com.qiyi.player.core.model.remote.MixerRemote#getRequest函数中。加密方法大致是salt + tvid + tm然后md5,salt生成方法每次都不同。

**Comment by jackyzy823** [comment]
当然还有一种理论上的方法，就是将播放视频的请求作为样本，把其中的enc,tvid,tm记录下来，然后md5(salt+tm+tvid) = enc 暴力算出salt ([0-9a-z]{32}) 也就是32 ** 16种可能性=。=

**Comment by sceext2** [comment]
@jackyzy823 
请问 暴力 计算 salt 实际上 可行 吗?
能不能 用 彩虹表 之类 的 方法 破解?
; - )

**Comment by jackyzy823** [comment]
1）实际上计算量太大，如果你有什么GPU集群可以尝试=。=
2）tvid可以固定，tm这个东西的值是swf运行到这个请求发送出去的时间，这个值基本是一定范围内随机的吧。如果tm能够固定下来，生成彩虹表就可以破解。
总之都是得不偿失的方法-=
