### ISSUE TITLE
A recomendation for the Readme

### ISSUE THREAD

**Issue by andygitgud** [soimort/you-get#590]
If you are using Windows 7  and want to download videos from Asian websites (or just a video with Asian titles) just add a line with 'chcp 65001' before:

> chcp 65001
> d:\Python34\python d:\youget\you-get http://www.bilibili.com/video/av1704785

I hope someone could write about this after been lurking for half hour looking for an answer. And I already knew python, not a pro but still.

**Comment by soimort** [comment]
The best place to host such information is [Wiki/FAQ](https://github.com/soimort/you-get/wiki/FAQ). I've added a brief QA entry about this, hopefully someone could expand it with more technical details (I myself am not familiar with those weird code pages). But err, I have to agree with you, encoding-related issues caused a lot of pains while I was working on Windows.
