### ISSUE TITLE
The downloaded youku movie is not complete (for a 854.1M movie only 363.9M is downloaded 

### ISSUE THREAD

**Issue by suokunlong** [soimort/you-get#595]
Console output:
(Please take note that this movie is 854.1M in size, but you-get only downloaded 363.9M and at this point it detected 13/13 is finished, so the download is stopped and the 13 parts are merged.)

```
D:\Media>you-get http://v.youku.com/v_show/id_XMjA2OTE2NjAw.html
site:                优酷 (Youku)
title:               泰坦尼克号
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          854.1 MiB (895573467 bytes)
    # download-with: you-get --format=hd2 [URL]

audio-languages:
    - lang:          英语
      download-url:  http://v.youku.com/v_show/id_XMjA2OTE2NjAw

    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XNDQ5MzcwOTcy

Downloading 泰坦尼克号.flv ...
 42.6% (363.9/854.1MB) [=================                       ] 13/13
Merging video parts...
```

Above is just an example, this happens for all youku movies.

**Comment by nuomi1** [comment]
you-get latest commit 8cd18fa67a
ISP 中国移动 广东 湛江 12M 对等光纤
看看是不是你的 ISP 对优酷的资源进行了缓存，请求不同清晰度只返回一种。

you-get http://v.youku.com/v_show/id_XMjA2OTE2NjAw.html
site:                优酷 (Youku)
title:               泰坦尼克号
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          854.1 MiB (895573467 bytes)
    # download-with: you-get --format=hd2 [URL]

audio-languages:
    - lang:          英语
      download-url:  http://v.youku.com/v_show/id_XMjA2OTE2NjAw

    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XNDQ5MzcwOTcy

Downloading 泰坦尼克号.flv ...
100.0% (854.1/854.1MB) [========================================] 32/32
ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.7.2_1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
[flv @ 0x7fcc1c808c00] Auto-inserting h264_mp4toannexb bitstream filter
Input #0, concat, from './泰坦尼克号.mp4.txt':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p, 1280x544 [SAR 1:1 DAR 40:17], 25 fps, 25 tbr, 1k tbn, 50 tbc
    Stream #0:1: Audio: aac (HE-AAC), 44100 Hz, stereo, fltp
[mp4 @ 0x7fcc1d01e200] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x7fcc1d01e200] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to './泰坦尼克号.mp4':
  Metadata:
    encoder         : Lavf56.36.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x544 [SAR 1:1 DAR 40:17], q=2-31, 25 fps, 25 tbr, 16k tbn, 1k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[aac @ 0x7fcc1c010600] element type mismatch 1 != 0
[flv @ 0x7fcc1c00fa00] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c029e00] element type mismatch 1 != 0
[flv @ 0x7fcc1c00f000] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c029800] element type mismatch 1 != 0
[flv @ 0x7fcc1c02ba00] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c017c00] element type mismatch 1 != 0
[flv @ 0x7fcc1c017000] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c017600] element type mismatch 1 != 0
[flv @ 0x7fcc1c028a00] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c818e00] element type mismatch 1 != 0
[flv @ 0x7fcc1c835400] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c824000] element type mismatch 1 != 0
[flv @ 0x7fcc1c823400] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c00f000] element type mismatch 1 != 0
[flv @ 0x7fcc1c02ba00] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c00fc00] element type mismatch 1 != 0
[flv @ 0x7fcc1c00f000] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c836000] element type mismatch 1 != 0
[flv @ 0x7fcc1c835400] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c00f600] element type mismatch 1 != 0
[flv @ 0x7fcc1c00f000] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c00fc00] element type mismatch 1 != 0
[flv @ 0x7fcc1c00f000] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c818e00] element type mismatch 1 != 0
[flv @ 0x7fcc1c835400] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c00f600] element type mismatch 1 != 0
[flv @ 0x7fcc1c00f000] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c818e00] element type mismatch 1 != 0
[flv @ 0x7fcc1c835400] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c868600] element type mismatch 1 != 0
[flv @ 0x7fcc1c867a00] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c819400] element type mismatch 1 != 0
[flv @ 0x7fcc1c818800] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c818e00] element type mismatch 1 != 0
[flv @ 0x7fcc1c823400] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c818e00] element type mismatch 1 != 0
[flv @ 0x7fcc1c818800] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c818800] element type mismatch 1 != 0
[flv @ 0x7fcc1c83b200] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c018400] element type mismatch 1 != 0
[flv @ 0x7fcc1c00f800] Auto-inserting h264_mp4toannexb bitstream filter
[flv @ 0x7fcc1c02a800] Auto-inserting h264_mp4toannexb bitstream filter
[flv @ 0x7fcc1c028e00] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c017c00] element type mismatch 1 != 0
[flv @ 0x7fcc1c017000] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c017600] element type mismatch 1 != 0
[flv @ 0x7fcc1c027a00] Auto-inserting h264_mp4toannexb bitstream filter
[flv @ 0x7fcc1c017000] Auto-inserting h264_mp4toannexb bitstream filter
[flv @ 0x7fcc1c022a00] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c02ac00] element type mismatch 1 != 0
[flv @ 0x7fcc1c02a000] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c016a00] element type mismatch 1 != 0
[flv @ 0x7fcc1c015e00] Auto-inserting h264_mp4toannexb bitstream filter
[aac @ 0x7fcc1c818e00] element type mismatch 1 != 0
[flv @ 0x7fcc1c835400] Auto-inserting h264_mp4toannexb bitstream filter
frame=155569 fps=31982 q=-1.0 Lsize=  873053kB time=01:43:43.13 bitrate=1149.3kbits/s    
video:796425kB audio:72927kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.425800%

**Comment by suokunlong** [comment]
好像跟清晰度没有关系，我下载超清格式和高清格式的，merge不同parts之后得到的都是一部不完整的影片。
我用的是联通10M光纤。话说是否被缓存怎么看？
需要其他的什么调试信息吗？

**Comment by suokunlong** [comment]
这个movie应该是有32段，但是我下载开始时就只检测到了有13段而不是32
```
you-get -u http://v.youku.com/v_show/id_XMjA2OTE2NjAw.html
site:                优酷 (Youku)
title:               泰坦尼克号
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          854.1 MiB (895573467 bytes)
    # download-with: you-get --format=hd2 [URL]

audio-languages:
    - lang:          英语
      download-url:  http://v.youku.com/v_show/id_XMjA2OTE2NjAw

    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XNDQ5MzcwOTcy

Real URLs:
http://218.26.231.143/677611886D74879277DEF2FF9/0300012000511B03F2C929055EEB3ED2
37F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
http://113.6.235.136/69791A4CCFB34729825112E78/0300012001511B03F2C929055EEB3ED23
7F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
http://103.224.233.51/697A1D38C1C3D83624CCDC4EDB/0300012002511B03F2C929055EEB3ED
237F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
http://218.26.231.205/697B2024F1B3C779B76F04603/0300012003511B03F2C929055EEB3ED2
37F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
http://218.60.17.16/677A1D38FDB357D70CA70282F/0300012004511B03F2C929055EEB3ED237
F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
http://106.74.24.82/697D25FC83547815EDD17B5F31/0300012005511B03F2C929055EEB3ED23
7F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
http://221.204.199.84/657A1D3893830826B768883256/0300012006511B03F2C929055EEB3ED
237F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
http://60.211.205.21/657B20249F13E833EC1D203F94/0300012007511B03F2C929055EEB3ED2
37F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
http://218.60.17.22/677E28E865C42810CCFE92383F/0300012008511B03F2C929055EEB3ED23
7F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
http://175.22.3.136/677F2BD4E544A78047B7C4BFC/0300012009511B03F2C929055EEB3ED237
F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
http://221.204.194.238/698123498733438365D038F4ACF/030001200A511B03F2C929055EEB3
ED237F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
http://175.22.3.215/6781131ACDC64B7820B0116ABB/030001200B511B03F2C929055EEB3ED23
7F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
http://218.60.17.73/698143A7071E307C25FC834494/030001200C511B03F2C929055EEB3ED23
7F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
```

**Comment by nuomi1** [comment]
you-get 与 flvcd 解析出的第一个视频片段，都在广东移动的 CDN。MD5 结果一致，分辨率均为 1280x544。
you-get（配搭 ss）解析出的第一个视频片段虽然在杭州移动的 CDN，但是文件名一致。下载只有 20k 的速度，就不下载来验证 MD5 了。

```
以下为 you-get 解析出的第一个视频片段。

➜  movies  curl -I http://183.232.42.103/697817B86834C845CE1D586375/0300012000511B03F2C929055EEB3ED237F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
HTTP/1.1 200 OK
Content-Type: video/flv
Accept-Ranges: bytes
ETag: "2044187518"
Last-Modified: Wed, 13 Feb 2013 03:09:41 GMT
Content-Length: 28275673
Connection: close
Date: Mon, 17 Aug 2015 01:26:17 GMT
Server: YOUKU.GD.MOBILE

➜  movies  md5 0300012000511B03F2C929055EEB3ED237F517-5CA9-E697-AD31-BCA98AA884CC.you-get.flv
MD5 (0300012000511B03F2C929055EEB3ED237F517-5CA9-E697-AD31-BCA98AA884CC.you-get.flv) = 0401e8494f3d96ff152fc8bcd55a0e3d
```

```
以下为 flvcd 解析出的第一个视频片段。

➜  movies  curl -I http://k.youku.com/player/getFlvPath/sid/043977589629910639fbb_00/st/flv/fileid/0300012000511B03F2C929055EEB3ED237F517-5CA9-E697-AD31-BCA98AA884CC\?K\=ec19b401b190ef0324124ec5\&ctype\=10\&ev\=1\&oip\=3079447839\&token\=7397\&ep\=zq8mKWqLLrXN6Yb92ZUeGyXARBx2%2FhFSbiuW94uh2d%2BQR5jl%2BfZ5sZRTjSUERWIV47quGnOdMjgQ9LZOoF1FO3rw9%2BPszJe10pmJusTeajdFtdRLnaMy8A3UewR44QWRc1soQIVIJus%3D\&ymovie\=1
HTTP/1.1 302 Found
X-Powered-By: PHP/5.3.3
Expires: -1
Cache-Control: private, max-age=0
Pragma: no-cache
Location: http://183.232.42.103/youku/65740BDCB403F839B4A0E520A7/0300012000511B03F2C929055EEB3ED237F517-5CA9-E697-AD31-BCA98AA884CC.flv
Content-type: text/html
Connection: close
Date: Mon, 17 Aug 2015 01:52:01 GMT
Server: F_LIGHTY_NJ_MOBILE

➜  movies  md5 0300012000511B03F2C929055EEB3ED237F517-5CA9-E697-AD31-BCA98AA884CC.flvcd.flv
MD5 (0300012000511B03F2C929055EEB3ED237F517-5CA9-E697-AD31-BCA98AA884CC.flvcd.flv) = 0401e8494f3d96ff152fc8bcd55a0e3d
```

```
以下为 you-get 解析出的第一个视频片段，配搭加拿大的 shadowsocks。

➜  movies  curl -I http://111.1.16.184/697817B8930497204164B5B25/0300012000511B03F2C929055EEB3ED237F517-5CA9-E697-AD31-BCA98AA884CC.flv.ts
HTTP/1.1 200 OK
Content-Type: video/flv
Accept-Ranges: bytes
ETag: "1575093611"
Last-Modified: Wed, 13 Feb 2013 03:09:41 GMT
Content-Length: 28275673
Connection: close
Date: Mon, 17 Aug 2015 02:18:33 GMT
Server: YOUKU.HZ.MOBILE
```

**Comment by soimort** [comment]
This is a known bug - before it gets fixed in the master branch, please try #463 for now.

**Comment by soimort** [comment]
This vi

**Comment by soimort** [comment]
This video is a dead link - please head to #451 for further discussions.
