### ISSUE TITLE
爱奇艺视频只返回一个清晰度的结果

### ISSUE THREAD

**Issue by RockWithBoA** [soimort/you-get#596]
比如：python you-get -i http://www.iqiyi.com/v_19rro8a2os.html
返回：
Video Site: iQIYI.com
Title:      晓松奇谈之三个令人发指的问题
Type:       Flash video (video/x-flv)
Size:       301.86 MiB (316521948 Bytes)

使用的commit是：8cd18fa67a649b1d90da0cbe2ef8684d8e00b016

返回的结果似乎是720P的，在12:00~23:00之外的时间也是同样的结果，无法返回1080P的结果

**Comment by nuomi1** [comment]
前段时间可以返回 1080p，现在只能返回 720p，广东湛江移动。

**Comment by sceext2** [comment]
现在用的 iqiyi 解析算法, 会自动选择最高清晰度的视频. 
其它结果被忽略, 只输出一种结果.

**Comment by sceext2** [comment]
通过把 `um=0` 改成 `um=1` 即可让 iqiyi 返回 1080p 结果. 

已开 PR #597

效果:

```
$ ./you-get --info "http://www.iqiyi.com/v_19rro8a2os.html"
Video Site: iQIYI.com
Title:      晓松奇谈之三个令人发指的问题
Type:       Flash video (video/x-flv)
Size:       614.13 MiB (643965680 Bytes)

$ 
```

**Comment by RockWithBoA** [comment]
刚才测试把 um=0 改成 um=1 后仍然返回的是720P的结果，难道爱奇艺又改东西了？

**Comment by sceext2** [comment]
刚才又试了一次, 我这里正常, 能够解析出 1080p 结果. 
a13daf8981

**Comment by RockWithBoA** [comment]
那可能是公司网络的问题了，公司IP都是国外的，回头换个环境再测下

**Comment by sceext2** [comment]
@RockWithBoA 
parse_video 那个 需要手动 修改一下. (嘿嘿)
创建文件  `lib/bks1/o/enc/salt.py` 然后 里面写 `enc = '3601ba290e4f4662848c710e2122007e'`

把 盐 放在单独的 文件中, 是为了 方便换盐. ;-)

**Comment by RockWithBoA** [comment]
哈哈，大神早说嘛，冥思苦想了好几天哪里出问题了:)

**Comment by jackyzy823** [comment]
thanks @sceext
