### ISSUE TITLE
好像不能下载 youtube 上的 4K 格式？

### ISSUE THREAD

**Issue by i0sdev** [soimort/you-get#599]
https://www.youtube.com/watch?v=pbNEeAAiIKk
试了下，网站上显示4K分辨率3840 x 2026@25，但下载下来查看信息是1280 × 676。

**Comment by liushuyu** [comment]
Because youtube 4K formats are in so-called "DASH" form (video and audio are seperated) which you-get currently can't handle.

**Comment by liushuyu** [comment]
Because youtube 4K formats are in so-called "DASH" form (video and audio are seperated) which you-get currently can't handle, also you-get can't handle HFR (high frame rate) format as well.

**Comment by soimort** [comment]
Duplicate of #395.

**Comment by liushuyu** [comment]
Great job!
