### ISSUE TITLE
爱其艺 key 值的问题

### ISSUE THREAD

**Issue by benhong** [soimort/you-get#617]
是否有哪位大大可以大致解说一下
key 取得流程呢，目前卡在
 和   ȇ[ȗ] = _loc_3["seek"]([_loc_4[ȇ[ȗ]]()]); 
以下是我使用的code
package 
{
    import flash.utils.*;

    public class Zombie extends Object
    {
        public static var kcuf:Array = []; 
        private static var Ǵ:Dictionary = null;
        private static var ǵ:Object = null;

        public function Zombie()
        {
            return;
        }// end function

        public static function set thd(param1:Object) : void
        {
            ǵ = param1;
            return;
        }// end function

        public static function bite(param1:String) : Object
        {
            var ǹ:Array;
            var Ǻ:Function;
            var ǻ:Function;
            var Ǽ:Function;
            var ǽ:Function;
            var Ǿ:Function;
            var ǿ:Function;
            var Ȁ:Function;
            var ȁ:Function;
            var Ȃ:Function;
            var ȃ:Function;
            var ȇ:Array;
            var Ȉ:Function;
            var ȉ:Function;
            var Ȋ:Function;
            var ȋ:Function;
            var Ȍ:Function;
            var ȍ:Function;
            var Ȏ:Function;
            var ȏ:Function;
            var Ȑ:Function;
            var ȑ:Function;
            var Ȓ:Function;
            var ȓ:Function;
            var Ȕ:Function;
            var ȕ:Function;
            var Ȝ:Function;
            var ȝ:Function;
            var Ȟ:String;
            var ȟ:int;
            var Ƞ:int;
            var ȡ:int;
            var Ȣ:int;
            var Ƕ:* = param1;
            if (Ǵ == null)
            {
                Ǵ = new Dictionary();
            }
            var Ƿ:* = function (param1:Array, param2) : void
            {
                param1.push(param2);
                return;
            }// end function
            ;
            var Ǹ:Array;
            ǹ;
            Ǻ = function () : int
            {
                return ǹ.indexOf(ȁ);
            }// end function
            ;
            Ǵ["cfcd208495d565ef66e7dff9f98764da"] = Ǻ;
            Zombie.Ƿ(Ǹ, "0cc175b9c0f1b6a831c399e269772661");
            ǻ = function () : int
            {
                return ǹ.indexOf(Ǽ);
            }// end function
            ;
            Ǵ["c4ca4238a0b923820dcc509a6f75849b"] = ǻ;
            Zombie.Ƿ(Ǹ, "c81e728d9d4c2f636f067f89cc14862c");
            Zombie.Ƿ(Ǹ, "1679091c5a880faf6fb5e6087eb1b2dc");
            Zombie.Ƿ(Ǹ, "eccbc87e4b5ce2fe28308fd9f2a7baf3");
            Zombie.Ƿ(Ǹ, "c9f0f895fb98ab9159f51fd0297e236d");
            Ǽ = function () : int
            {
                return ǹ.indexOf(Ȃ);
            }// end function
            ;
            Ǵ["c81e728d9d4c2f636f067f89cc14862c"] = Ǽ;
            Zombie.Ƿ(Ǹ, "cfcd208495d565ef66e7dff9f98764da");
            Zombie.Ƿ(Ǹ, "e1671797c52e15f763380b45e841ec32");
            ǽ = function () : int
            {
                return ǹ.indexOf(Ǻ);
            }// end function
            ;
            Ǵ["eccbc87e4b5ce2fe28308fd9f2a7baf3"] = ǽ;
            Zombie.Ƿ(Ǹ, "cfcd208495d565ef66e7dff9f98764da");
            Zombie.Ƿ(Ǹ, "92eb5ffee6ae2fec3ad71c777531578f");
            Zombie.Ƿ(Ǹ, "4a8a08f09d37b73795649038408b5f33");
            Zombie.Ƿ(Ǹ, "0cc175b9c0f1b6a831c399e269772661");
            Zombie.Ƿ(Ǹ, "cfcd208495d565ef66e7dff9f98764da");
            Ǿ = function () : int
            {
                return ǹ.indexOf(Ȕ);
            }// end function
            ;
            Ǵ["a87ff679a2f3e71d9181a67b7542122c"] = Ǿ;
            Zombie.Ƿ(Ǹ, "92eb5ffee6ae2fec3ad71c777531578f");
            Zombie.Ƿ(Ǹ, "4a8a08f09d37b73795649038408b5f33");
            ǿ = function () : int
            {
                return ǹ.indexOf(ǽ);
            }// end function
            ;
            Ǵ["e4da3b7fbbce2345d7772b0674a318d5"] = ǿ;
            Zombie.Ƿ(Ǹ, "92eb5ffee6ae2fec3ad71c777531578f");
            Zombie.Ƿ(Ǹ, "0cc175b9c0f1b6a831c399e269772661");
            Zombie.Ƿ(Ǹ, "8fa14cdd754f91cc6554c9e71929cce7");
            Zombie.Ƿ(Ǹ, "eccbc87e4b5ce2fe28308fd9f2a7baf3");
            Ȁ = function () : int
            {
                return ǹ.indexOf(Ȍ);
            }// end function
            ;
            Ǵ["1679091c5a880faf6fb5e6087eb1b2dc"] = Ȁ;
            Zombie.Ƿ(Ǹ, "c81e728d9d4c2f636f067f89cc14862c");
            Zombie.Ƿ(Ǹ, "4a8a08f09d37b73795649038408b5f33");
            Zombie.Ƿ(Ǹ, "45c48cce2e2d7fbdea1afc51c7c6ad26");
            Zombie.Ƿ(Ǹ, "92eb5ffee6ae2fec3ad71c777531578f");
            ȁ = function () : int
            {
                return ǹ.indexOf(ǻ);
            }// end function
            ;
            Ǵ["8f14e45fceea167a5a36dedd4bea2543"] = ȁ;
            Zombie.Ƿ(Ǹ, "e1671797c52e15f763380b45e841ec32");
            Zombie.Ƿ(Ǹ, "4a8a08f09d37b73795649038408b5f33");
            Zombie.Ƿ(Ǹ, "c9f0f895fb98ab9159f51fd0297e236d");
            Zombie.Ƿ(Ǹ, "8fa14cdd754f91cc6554c9e71929cce7");
            Zombie.Ƿ(Ǹ, "0cc175b9c0f1b6a831c399e269772661");
            Ȃ = function () : int
            {
                return ǹ.indexOf(ȉ);
            }// end function
            ;
            Ǵ["c9f0f895fb98ab9159f51fd0297e236d"] = Ȃ;
            Zombie.Ƿ(Ǹ, "1679091c5a880faf6fb5e6087eb1b2dc");
            Zombie.Ƿ(Ǹ, "c81e728d9d4c2f636f067f89cc14862c");
            ȃ = function () : int
            {
                return ǹ.indexOf(Ǿ);
            }// end function
            ;
            Ǵ["45c48cce2e2d7fbdea1afc51c7c6ad26"] = ȃ;
            Zombie.Ƿ(Ǹ, "c4ca4238a0b923820dcc509a6f75849b");
            Zombie.Ƿ(Ǹ, "8fa14cdd754f91cc6554c9e71929cce7");
            Zombie.Ƿ(Ǹ, "8277e0910d750195b448797616e091ad");
            var Ȅ:* = function (param1:int) : String
            {
                return String.fromCharCode(param1);
            }// end function
            ;
            var ȅ:* = function (param1:Number) : Boolean
            {
                return param1 > 0;
            }// end function
            ;
            var Ȇ:* = function (param1:Array, param2) : void
            {
                Ƿ(param1, param2);
                return;
            }// end function
            ;
            ȇ;
            while ("0" < "1")
            {
                
                Ȝ = function () : int
            {
                return ǹ.indexOf(Ȝ);
            }// end function
            ;
                ȝ = function () : int
            {
                return ǹ.indexOf(ȑ);
            }// end function
            ;
                break;
                Zombie.Ȇ(ȇ, ȟ);
                Zombie.Ȇ(ȇ, Ƞ);
            }
            Ǵ["0cc175b9c0f1b6a831c399e269772661"] = Ȝ;
            Ǵ["92eb5ffee6ae2fec3ad71c777531578f"] = ȝ;
            Ȉ = function () : int
            {
                return ǹ.indexOf(Ȉ);
            }// end function
            ;
            ȉ = function () : int
            {
                return ǹ.indexOf(ǿ);
            }// end function
            ;
            Ȋ = function () : int
            {
                return ǹ.indexOf(Ȋ);
            }// end function
            ;
            ȋ = function () : int
            {
                return ǹ.indexOf(ȋ);
            }// end function
            ;
            Ȍ = function () : int
            {
                return ǹ.indexOf(ȃ);
            }// end function
            ;
            ȍ = function () : int
            {
                return ǹ.indexOf(ȍ);
            }// end function
            ;
            Ȏ = function () : int
            {
                return ǹ.indexOf(Ȏ);
            }// end function
            ;
            ȏ = function () : int
            {
                return ǹ.indexOf(ȏ);
            }// end function
            ;
            Ȑ = function () : int
            {
                return ǹ.indexOf(Ȑ);
            }// end function
            ;
            ȑ = function () : int
            {
                return ǹ.indexOf(ȝ);
            }// end function
            ;
            Ȓ = function () : int
            {
                return ǹ.indexOf(Ȓ);
            }// end function
            ;
            ȓ = function () : int
            {
                return ǹ.indexOf(ȓ);
            }// end function
            ;
            Ȕ = function () : int
            {
                return ǹ.indexOf(Ȁ);
            }// end function
            ;
            ȕ = function () : int
            {
                return ǹ.indexOf(ȕ);
            }// end function
            ;
            Ǵ["4a8a08f09d37b73795649038408b5f33"] = ȉ;
            Ǵ["8277e0910d750195b448797616e091ad"] = Ȍ;
            ǹ.push(Ǻ);
            ǹ.push(ǻ);
            ǹ.push(Ǽ);
            ǹ.push(ǽ);
            ǹ.push(Ǿ);
            ǹ.push(ǿ);
            ǹ.push(Ȁ);
            ǹ.push(ȁ);
            ǹ.push(Ȃ);
            ǹ.push(ȃ);
            ǹ.push(Ȝ);
            ǹ.push(ȝ);
            ǹ.push(ȉ);
            ǹ.push(Ȍ);
            ǹ.push(ȑ);
            ǹ.push(Ȕ);
            Ǵ["e1671797c52e15f763380b45e841ec32"] = ȑ;
            Ǵ["8fa14cdd754f91cc6554c9e71929cce7"] = Ȕ;
            ǹ.push(Ȉ);
            ǹ.push(Ȋ);
            ǹ.push(ȋ);
            ǹ.push(ȕ);
            ǹ.push(Ȓ);
            ǹ.push(ȓ);
            ǹ.push(Ȏ);
            while (Ǹ.length)
            {
                
                var _loc_3:* = Ǵ;
                Zombie.Ƿ(ȇ, _loc_3[Ǹ.shift()]());
            }
            var Ȗ:* = ȇ.join("") + "7b11c5408ff342318da3e7c97b92e890";
            var ȗ:int;
            while (ȗ < ȇ.length)
            {
                
                var _loc_3:* = ǵ;
                var _loc_4:* = kcuf;
                ȇ[ȗ] = _loc_3["seek"]([_loc_4[ȇ[ȗ]]()]); //这段code有点问题
                ȗ = (ȗ + 1);
            }
	//ȇ 就是key值 
            return ȇ;
        }// end function

    }
}

**Comment by fffonion** [comment]
反正我静态看不出来……装了debug版的flash player，然后trace出来的hhh
（咦上上星期没变我以为iqiyi良心发现了ww

**Comment by benhong** [comment]
是否可以大致交一下如何使用 debug版的flash player，然后trace
謝謝

**Comment by fffonion** [comment]
推荐你两个软件，WinRABCDAsm做修改用，ffdec验证用
debug版的flash player可以在adobe上下，选择自己浏览器所使用的版本
具体怎么做请google

**Comment by benhong** [comment]
@fffonion  謝謝大大的指導，我已經學會了自己取的key了,WinRABCDAsm 真是好東西~
