### ISSUE TITLE
下载最高清晰度和两个函数的疑问

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#628]
1.download_urls_chunked()和download_urls()这两个函数的区别在哪里？
2.视频网站上都提供视频的各种清晰度，那么怎样才能下载最高清晰度呢？

**Comment by zhangn1985** [comment]
一般来说时默认最高分辨率，除非没实现。你可以用-i 来获得分辨率信息。

**Comment by redstoneleo** [comment]
you-get.exe -i http://www.iqiyi.com/v_19rrh4l8eg.html#vfrm=2-3-0-1
只获取到这些
Video Site: iQIYI.com

Title:      霹雳侠影之轰霆剑海录 第1集

Type:       Flash video (video/x-flv)

Size:       1107.69 MiB (1161501724 Bytes)


并且感觉you-get是好是坏，有时候网络正常还报错

**Comment by cnbeining** [comment]
因为很多网站只支持一个清晰度，或者是。。。。。。。。。懒得写（

**Comment by zhangn1985** [comment]
我已经完成sohu 和 letv
https://github.com/zhangn1985/you-get/commit/030b66884ce23e971d6d0cfb692266fa276b5b08
https://github.com/zhangn1985/you-get/commit/573cfd7c9f7feab752348a3eae3db92fffde4f6f
https://github.com/zhangn1985/you-get/commit/217347c114786811fdff07ee5e4a7bc381defa36
https://github.com/zhangn1985/you-get/commit/f05a058687a609707ddd57dda333042dd22001c9

等我提PR吧

**Comment by soimort** [comment]
如 @cnbeining 所言
