### ISSUE TITLE
音悦台下载不稳定,同一个网址有时能下有时不能下

### ISSUE THREAD

**Issue by Friday21** [soimort/you-get#632]
如下所示, 第二次输入的时候就卡在那里不动了
friday@friday:~/git/you-get$ python3 ./you-get -i http://v.yinyuetai.com/video366384?f=SY-ZZLX-QB-1
Video Site: YinYueTai.com
Title:      Beyonce Made In America 音乐节 全场 - Beyonce
Type:       Flash video (video/x-flv)
Size:       2054.5 MiB (2154298784 Bytes)

friday@friday:~/git/you-get$ python3 ./you-get -i http://v.yinyuetai.com/video/2366384?f=SY-ZZLX-QB-1
^Cfriday@friday:~/git/you-get$ python3 ./you-get -i http://v.yinyuetai.com/video366384?f=SY-ZZLX-QB-1

**Comment by Friday21** [comment]
额, 好像是我网络问题, 关掉此issue吧

**Comment by cnbeining** [comment]
可以自己关，点下面的close and commit.
