### ISSUE TITLE
来个芒果tv下载吧

### ISSUE THREAD

**Issue by danran-php** [soimort/you-get#640]
另外问下，如果只获取真实下载地址返回 不下载，怎么做

感谢这么好用的东东 大爱

**Comment by jackyzy823** [comment]
`you-get -u url `

details are in readme.

**Comment by cnbeining** [comment]
吼啊。

我去吃饭，回来把这个写了。

但是IP限制不保证能破，不考虑破解VIP（我觉得```you-get```不会考虑这种东西的）。

**Comment by zhangn1985** [comment]
https://github.com/soimort/you-get/pull/624

**Comment by zhangn1985** [comment]
https://github.com/soimort/you-get/pull/624 
可以参考我的实现哦，不过不知怎的，老是403。
估计还是有地方写的不对。

**Comment by zhangn1985** [comment]
403 已经解决了。

**Comment by cnbeining** [comment]
@zhangn1985 OK，我也是你这个写法，那我不发了。
