### ISSUE TITLE
new way to import extractors?

### ISSUE THREAD

**Issue by zhangn1985** [soimort/you-get#642]
currently there is a big dict in common.py, each time when we need to support new site, we need to add the new site to the dict.
if we can do like this:
```
site = get_site_form_url(url)
#site = "youku"
form .extractors import site as m
m.download(url)
```
so we don't need to maintain the big dict.

but I don't know how to do it...

**Comment by sceext2** [comment]
I think this is a good idea.

**Comment by zhangn1985** [comment]
python3 有内置方法__import__，可以xml = __import__('xml') 和import xml 效果类似。但今天我__import__('.extractors') 就不太对

**Comment by jackyzy823** [comment]
@zhangn1985  @sceext2  What about this kind of import mechanism https://github.com/jackyzy823/you-get/commit/33ceb875d8caec8458f5247f6a55fb0ee73df4e7 and https://github.com/jackyzy823/you-get/commit/a2d48850b0bd56568937ec760f44a5a7b7424ee1

**Comment by zhangn1985** [comment]
@jackyzy823 if you can rename some site.py, I think you can remove downloads dict.
do you think?

**Comment by jackyzy823** [comment]
@zhangn1985  There are many conditions, such as site `bilibili` and `smgbb` all point to bilibili.py and  netease.py cannot be named after site 163 because python do not support module startswith number.
Many a single python file to hold this dict is much better.

**Comment by soimort** [comment]
:+1: for using `importlib.import_module`. The official Python documentation recommend not to use `__import__` directly.

Even better, you may traverse the [`src/you_get/extractors`](https://github.com/soimort/you-get/tree/develop/src/you_get/extractors) directory and automatically import all modules in the path, so there will be no need for modifying `common.py`; to implement a new extractor for website foobar, you'd just add a file like `foobar.py` into that directory. That will make life much easier.

**Comment by zhangn1985** [comment]
@jackyzy823 @soimort we can have a alias dict. that will be much smaller.

**Comment by zhangn1985** [comment]
@jackyzy823 when do you plan PR?

**Comment by alresvor** [comment]
这是我以前写的
    _path_ = os.path.dirname(__file__)
    for pyfile in os.listdir(os.path.join(_path_,'extractors')):
        name,ext = os.path.splitext(pyfile)
        if ext == '.py':
            if name in url:
                exec('from extractors.%s import _main_' % name)
                if not _main_(url):
                    break
extractors 里的文件可以对url再匹配一遍，因为上面的判断太简单了
