### ISSUE TITLE
优酷只能下载45分钟视频

### ISSUE THREAD

**Issue by danran-php** [soimort/you-get#649]
举个栗子 http://v.youku.com/v_show/id_XMzM4MDYzMjI4.html?from=y1.6-96.1.1.8dc32f90211911e097c0

**Comment by danran-php** [comment]
@soimort

**Comment by danran-php** [comment]
没有人遇到吗

**Comment by aOJzQT** [comment]
今天第一次用就遇到了，大小解析都正常，各种格式都试过了，只有大概45分钟左右

**Comment by cnbeining** [comment]
duplicate. @soimort

**Comment by soimort** [comment]
已知bug：#390
