### ISSUE TITLE
爱奇艺似乎又无法下载了

### ISSUE THREAD

**Issue by phpengineer** [soimort/you-get#653]
今天中午开始，爱奇艺似乎又无法下载了。

**Comment by sinnhinn126** [comment]
def mix(tvid):
	enc = []
	enc.append('3cba91f1453145438ac5e4f5983bc086')
	tm = str(randint(2000,4000))
	src = 'eknas'
	enc.append(str(tm))
	enc.append(tvid)
	sc = hashlib.new('md5',str(bytearray("".join(enc),'utf-8'))).hexdigest()
	return tm,sc,src

求3cba91f1453145438ac5e4f5983bc086 的算法，谢谢

**Comment by yan12125** [comment]
There's some info at #617, though I've never succeeded.

**Comment by phpengineer** [comment]
我反编译爱奇艺播放器后，发现算法变了，在调用http://cache.video.qiyi.com/vms这个接口的时候增加了两个额外的参数。不知道各位大侠是否注意到！

**Comment by jackyzy823** [comment]
@yan12125  some comments in iqiyi.py for your reference.

**Comment by jackyzy823** [comment]
@fffonion thanks for your method. Dynamic trace is much faster than static analysis.

**Comment by yan12125** [comment]
@jackyzy823 Much gratitude to the excellent work and detailed explanations!

**Comment by fffonion** [comment]
@jackyzy823 You're welcome. I learned it from OpenGG. For those who are insterested in flash manipulating, [here's a list](https://github.com/zbtang/OpenGG.Clean.Player-client/blob/master/README.md) about how to manage it. And personally I recommand ffdec to sothink flash decompiler which is opensourced and under active development. :)
