### ISSUE TITLE
怎样选择不同的格式（清晰度）

### ISSUE THREAD

**Issue by bandaotiehewen** [soimort/you-get#661]
![issue](https://cloud.githubusercontent.com/assets/10446544/9990050/64ce3ef2-6090-11e5-9e9b-1922d1b53226.png)
 

如图，在下载的时候回提醒不同的格式，怎么选择呢？

**Comment by zhangn1985** [comment]
you-get --format 1080p http://.....

目前程序设计，format的选项是动态生成的，所以必须先用-i参数获得。

这点应该可以改进。
