### ISSUE TITLE
iqiyi had update the algorithm 150922

### ISSUE THREAD

**Issue by lamlam123tld3** [soimort/you-get#664]

**Comment by univert** [comment]
yes, indeed

**Comment by cnbeining** [comment]
The thing is, iQiyi will be changing their salt (maybe algorithm) all the time.

This could be too rapid for ```you-get``` to follow. 

One way is to parse the video addresses on the fly as the video plays, but has to be semi-automatic.

We should try to find some better way for that, ~~like PT or Usenet~~.

**Comment by univert** [comment]
I am thinking how does Iqiyi's mobile APP download its video? 
Are they update the APP every time they change a new salt? I don't think so.
So there must be a back door for the mobile APP to download video. At least I guess so.

**Comment by univert** [comment]
@jackyzy823 any update?

**Comment by yan12125** [comment]
This time not only enc but also authkey is updated. I've followed @jackyzy823's approach and gotten the key. See https://github.com/rg3/youtube-dl/commit/57565375c85ff6adb11beb961fd61d6bdd023ec1

**Comment by sceext2** [comment]
@yan12125 
I don't think you have to change the authkey. 
I did not change the authkey, and it works well.

**Comment by yan12125** [comment]
You're right. ```authkey``` is changed but it's not checked.

**Comment by lucifekit** [comment]
What is the mean of "not checked", i saw you update your youtube-dl, can u provide the fix to the current you-get ?

I changed the key to eac64f22daf001da6ba9aa8da4d501508bbe90a4d4091fea3b0582a85b38c2cc but it wont work

**Comment by sceext2** [comment]
@yan12125 I know what the problem is. 
In fact, iqiyi did not update the authkey this time, but many months ago. 
As far as I know, iqiyi has been using the new authkey from June, 2015. 
https://github.com/sceext2/parse_video/blame/version/lib/bks1/o/raw/remote_mixer.py#L79

**Comment by yan12125** [comment]
@sceext2 Much thanks for that info. I guess it's better to use the correct authkey in you-get, too.
@lucifekit 'Not checked' means using the wrong ```authkey``` does not cause errors. By the way, I'll try to post a PR.

**Comment by lucifekit** [comment]
@yan12125 Thank you.

By the way, i just want to say this is the first time i played with flash disassemble, it is so amazing. I love the way programmer all over the world work in a much higher level of coding than i am doing now, it is so much more thing to learn. ( is my english not clear? forgive me :D, hope you understand  what i said ) :+1:
