### ISSUE TITLE
并行下载

### ISSUE THREAD

**Issue by rtlanceroad** [soimort/you-get#668]
有时候，某些剧在kickass,katcr等种子网站上找不到种子，所以，只能从bilibili或者youku上下载，但是，
$ you-get URL1 URL2 URL3 ...
回车后，只能一个接一个的下载。有没有可能添加一个option或者flag, 来规定几个视频同时下载？

**Comment by zhangn1985** [comment]
目前似乎 you-get URL1 URL2 URL3，对于使用了VideoEctractor的site，下载会有问题。
所以并不支持。

**Comment by sceext2** [comment]
可以 尝试 同时运行多个 you-get 实现并行下载.

**Comment by soimort** [comment]
Duplicate of #158 or #510.
