### ISSUE TITLE
优酷视频无法下载超清画质

### ISSUE THREAD

**Issue by zhuiying001** [soimort/you-get#672]
Z:\>you-get http://v.youku.com/v_show/id_XMTM0NDE2MDYxNg==.html
site:                优酷 (Youku)
title:               决战在即：预告 - 英雄联盟2015全球总决赛宣传片预告
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          10.0 MiB (10479914 bytes)
    # download-with: you-get --format=hd2 [URL]

Downloading 决战在即：预告 - 英雄联盟2015全球总决赛宣传片预告.flv ...
 24.0% (  2.4/10.0 MB) [==========                              ] 1/1

**Comment by zhangn1985** [comment]
其实是文件大小获取错了。
