### ISSUE TITLE
报bug，B站这个视频下载下来的视频文件体积太小

### ISSUE THREAD

**Issue by gonejack** [soimort/you-get#674]
http://www.bilibili.com/video/av2597614/

下载下来是空视频

**Comment by soimort** [comment]
```
$ you-get -i http://www.bilibili.com/video/av2597614/ 
Video Site: bilibili.com
Title:      【小瓶子】盛夏的Letter Rainbow 【sec7】
Type:       Flash video (video/x-flv)
Size:       64.02 MiB (67129340 Bytes)
```

**Comment by gonejack** [comment]
我这边的解析结果依然是

i@debian:~/pytools/you-get$ python3 you-get http://www.bilibili.com/video/av2597614/
Video Site: bilibili.com
Title:      【小瓶子】盛夏的Letter Rainbow 【sec7】
Type:       Flash video (video/x-flv)
Size:       0.0 MiB (1065 Bytes)

Downloading 【小瓶子】盛夏的Letter Rainbow 【sec7】.flv ...
100.0% (  0.0/0.0  MB) [========================================] 1/1

Downloading 【小瓶子】盛夏的Letter Rainbow 【sec7】.cmt.xml ...
