### ISSUE TITLE
Youku无法解析1080P

### ISSUE THREAD

**Issue by hitechbeijing** [soimort/you-get#681]
地址：http://v.youku.com/v_show/id_XMTMzOTkzNjU0OA
解析结果：
site:                优酷 (Youku)
title:               琅琊榜 01
streams:             # Available quality and codecs
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          387.3 MiB (406160722 bytes)
    # download-with: you-get --format=hd2 [URL]

    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          177.4 MiB (185976912 bytes)
    # download-with: you-get --format=mp4 [URL]

    - format:        flv
      container:     flv
      video-profile: 标清
      size:          92.5 MiB (96956930 bytes)
    # download-with: you-get --format=flv [URL]

    - format:        3gphd
      container:     3gp
      video-profile: 高清（3GP）
      size:          97.2 MiB (101885653 bytes)
    # download-with: you-get --format=3gphd [URL]

此视频是无需登录都能观看1080P的。

**Comment by soimort** [comment]
![screenshot from 2015-10-02 10-05-30](https://cloud.githubusercontent.com/assets/342945/10241951/775841ca-68ed-11e5-82cb-b407434bfbc0.png)

**Comment by hitechbeijing** [comment]
@soimort 

![image](https://cloud.githubusercontent.com/assets/9780601/10242097/d5f1471c-6920-11e5-94cb-459582a93c75.png)

**Comment by soimort** [comment]
I don't have access to 1080P anyway, not even in my browser. Anyone can reproduce this?

**Comment by hitechbeijing** [comment]
@soimort I can choose 1080P sometimes without login and member user account.  I don't know why.If I find the reason I will let you know.  But I have found a windows software names "lieying" which can download 1080P video.

**Comment by cnbeining** [comment]
猎影是另一个故事了。

虽然我觉得他的youku解析模块应该是you-get.

猎影不开源，我去问问开发者吧。但是这种破解不是you-get的目的。

**Comment by A-Circle-Zhang** [comment]
@cnbeining 猎影的解析模块（非插件）并没有用到 you-get 的。

**Comment by xujiangit** [comment]
好像要用google chrome浏览器才能观看1080p的

**Comment by zhangn1985** [comment]
```
you-get -i http://v.youku.com/v_show/id_XMTMzOTkzNjU0OA
site:                优酷 (Youku)
title:               琅琊榜 01
streams:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          387.3 MiB (406160722 bytes)
    # download-with: you-get --format=hd2 [URL]
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          177.4 MiB (185976912 bytes)
    # download-with: you-get --format=mp4 [URL]
    - format:        3gphd
      container:     mp4
      video-profile: 高清（3GP）
      size:          97.2 MiB (101885653 bytes)
    # download-with: you-get --format=3gphd [URL]
    - format:        flv
      container:     flv
      video-profile: 标清
      size:          92.5 MiB (96956930 bytes)
    # download-with: you-get --format=flv [URL]
```
为嘛我这边输出的是这样的？
我的you-get合并了https://github.com/soimort/you-get/pull/463 是不是根这个有关？

**Comment by soimort** [comment]
1080p is not accessible through the public API. Closing.
