### ISSUE TITLE
如何解析的

### ISSUE THREAD

**Issue by danran-php** [soimort/you-get#682]
如何解析的
需要那些原料
debug flash
flash反汇编工具
chrome

具体需要哪些?

感激不尽

**Comment by cnbeining** [comment]
抓包器（能拦截SSL的，包括移动端）
APK解包脚本

我自己就用到这，至于反汇编的我就不用了。

**Comment by soimort** [comment]
看需求。

没有什么工具是必须的，不同网站播放视频的方式各不相同。大部分时候 Chrome DevTools + curl 足矣。

复杂一点的抓包可用 Wireshark，但是真正用到的时候很少。

分析 JS（混淆源地址的算法）用 js-beautify 和 spidermonkey。

反向 Flash 用 JPEXS。现在不支持 HTML5 的视频网站越来越少，所以我都很少用。

**Comment by cnbeining** [comment]
Wireshark除非抓xmlsocket否则我觉得重，我用Charles。

懒人用postman，或者web-sniffer测试http请求。

jpexs抓一般藏的key和算法是好的，然而对于iqiyi这种变态货还是需要奇招的。甚至直接抓请求，放弃解析。

2015年10月2日星期五，Mort Yao <notifications@github.com> 写道：

**Comment by danran-php** [comment]
@cnbeining  嗯嗯，经过不懈努力，终于搞定了爱奇艺vip解析，爱奇艺的工程师都是羊驼吗
