### ISSUE TITLE
算不出来了

### ISSUE THREAD

**Issue by danran-php** [soimort/you-get#683]
抓包得到的post数据
aid:202550601
utt:1262
platform:b6c13e26323c537d
cid:afbe8fd3d73448c9
deviceId:bdf02d37c4c65b2db2f787488f876e59
playType:main
uuid:bdf02d37c4c65b2db2f787488f876e59
v:57649d8c27a7dcd4784792219953c168
version:1.0
vid:73ae4fcc72ed61eae9f0ced13d80623f
ut:1443833658083

下面是flash里面的计算方式，根据其他值算出v值

            try 
            {
                this._holder.runtimeData.authenticationError = false;
                s = uint(0 ^ 2391461978).toString();
                ut = new Date().time;
                uts = ut.toString();
                utt = String(ut % 1000 * int(uts.substr(0, 2)) + (100 + this._segmentIndex));
                MdStr = this._holder.runtimeData.albumId + "_" + this._holder.runtimeData.communicationlId + "_" + this._holder.runtimeData.vid + "_" + uts + "_" + utt + "_" + s;
                vt = com.qiyi.player.base.utils.MD5.calculate(MdStr);
                this._log.debug("primitive MD5 String :" + MdStr);
                this._log.debug("MD5 String:" + vt);
                request = new flash.net.URLRequest(com.qiyi.player.core.Config.VIP_AUTH_URL);
                variables = new flash.net.URLVariables();
                variables.ut = ut;
                variables.vid = this._holder.runtimeData.vid;
                variables.cid = this._holder.runtimeData.communicationlId;
                variables.aid = this._holder.runtimeData.albumId;
                variables.utt = utt;
                variables.v = vt;
                variables.version = "1.0";
                if (!(com.qiyi.player.user.impls.UserManager.getInstance().user && com.qiyi.player.user.impls.UserManager.getInstance().user.P00001)) 
                {
                };
                variables.uuid = com.qiyi.player.base.uuid.UUIDManager.instance.uuid;
                variables.deviceId = com.qiyi.player.base.uuid.UUIDManager.instance.uuid;
                if (this._holder.runtimeData.playerType) 
                {
                    variables.playType = this._holder.runtimeData.playerType.name;
                }
                variables.platform = "b6c13e26323c537d";
                request.method = flash.net.URLRequestMethod.POST;
                request.data = variables;
            }

大概就是
aid + "_" + cid + "_" + vid + "_" + uts + "_" + utt + "_" + uint(0 ^ 2391461978).toString();

md5('202550601'.'_'.'afbe8fd3d73448c9'.'_'.'73ae4fcc72ed61eae9f0ced13d80623f'.'_'.'1443833658083'.'_'.'1262'.'_'.abs(0 ^ 2391461978));

算出来的值和v值不一样，哪错了

**Comment by sceext2** [comment]
注意此处
```
s = uint(0 ^ 2391461978).toString();
```
python 中 没有 `uint` 函数

**Comment by sceext2** [comment]
不好意思, 看错了 ;-)

**Comment by sceext2** [comment]
此处
```
            MdStr = this._holder.runtimeData.albumId + "_" + this._holder.runtimeData.communicationlId + "_" + this._holder.runtimeData.vid + "_" + uts + "_" + utt + "_" + s;
```
中间 都是 使用 `_` 分割 的, 然而 
```
aid + "" + cid + "" + vid + "" + uts + "" + utt 
```
怎么 变成 了 '' 了?

**Comment by danran-php** [comment]
@sceext2  

我用的php，php是世界上最好的语言。

下划线复制的时候掉了，你可以用python复现吗？

**Comment by danran-php** [comment]
已经解决
