### ISSUE TITLE
爱奇艺 最新的key

### ISSUE THREAD

**Issue by benhong** [soimort/you-get#689]
因有人曾经指点过我怎样修改flash 档
所以我就分享一下我解出来的key
请享用

http://www.iqiyi.com/common/flashplayer/20150922/MainPlayer_5_2_28_c3_3_7_5.swf
a6f2a01ab9ad4510be0449fab528b82c

请帮忙更新谢谢

**Comment by sceext2** [comment]
https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/iqiyi.py#L48

感谢 你的 贡献 ^_^

不过 十几天前 you-get 就 已经 更新 了. 
下次 要 快一点 哦. ;-)

**Comment by redstoneleo** [comment]
能分享一些你得到key的方法吗？谢谢

**Comment by benhong** [comment]
@seccxt2 因為changelog 沒有改，所以我以為它是舊的
Changelog:
-> http://www.iqiyi.com/common/flashplayer/20150916/MainPlayer_5_2_28_c3_3_7_4.swf

**Comment by xyuanmu** [comment]
请问下如何通过源码获得key的，源码有了：#692，可是看不懂，能稍微解释下吗？
