### ISSUE TITLE
安装了不能用，找不到命令

### ISSUE THREAD

**Issue by i0sdev** [soimort/you-get#694]
`Mac, 10.11, Python3, pip3`

试了用了`pip3`和`git`两种方法安装，但是都用不了，敲了`you-get`显示没有这个。但是`pip3 list`都能显示`you-get (0.3.36)`，`pip3 uninstall you-get`也能反安装掉。

装了，就是不能用。为啥？

**Comment by cnbeining** [comment]
PATH是不是设置正确了？

**Comment by i0sdev** [comment]
在哪里设置？记得以前装没有设置过就可以直接用了。

**Comment by soimort** [comment]
```
$ echo $PATH
```

**Comment by i0sdev** [comment]
Mac 上用的是 `oh-my-zsh`，`echo $PATH`显示`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`，使用其他命令没有问题。

**Comment by soimort** [comment]
找到setuptools默认的entry point位置，手动把这个位置添加到PATH。如果不知道怎么设置PATH，可以直接用

    $ pip3 install you-get --install-option="--install-scripts=/usr/bin"`

安装。

**Comment by i0sdev** [comment]
close的太早啦～

卸掉了原来用安装器安装的 Python3.5，用`brew install python3`重新安装后，`you-get`就能用了。虽然不知道为什么。。。

**Comment by liuxuzxx** [comment]
好像是安装到了/home/用户/.local/bin  目录下面，之后看看PATH的路径，使用一个ln命令，链接一个you-get到/usr/bin下面的you-get就行了
