### ISSUE TITLE
acfun.tudou.com

### ISSUE THREAD

**Issue by zhangn1985** [soimort/you-get#695]
acfun.tudou.com 无法使用acfun.py解析，导致错误。

程序入口需要适配子站。
```

**Comment by soimort** [comment]
可以在`tudou.py`里直接import `acfun`模块。

**Comment by soimort** [comment]
但是 `acfun.py` 里面又 import 了 tudou 所以好像不行:sweat:

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/you-get/commit/fb0c20954116fab83b7328d48e72744414ee2eb0
我这边比较好实现，但是上游比较难。

**Comment by cnbeining** [comment]
其实就是死活不能有from ... import ... .

那么就手动简单实现一下importlib好了。
