### ISSUE TITLE
有没有什么方法可以下载到iqiyi的vip视频

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#696]
通过Chrome开发者工具拿得到json文件，
http://cache.vip.qiyi.com/vms?key=fvinp&src=1702633101b340d8917a69cf8a4b8c7c&tvId=321983&vid=5ff35099c75c4a4f9cd6337fb226c0b1&cid=afbe8fd3d73448c9&token=a2a2eec6499ad81099def5aaa086cfe3&uid=2096661666&pf=b6c13e26323c537d&vinfo=1&tm=7650&enc=90e0b875e2e5b0b8793ce134dd16ba32&qyid=13bff3c9874e05a53ac625b3113fc4ca&puid=2096661666&authKey=5333234a4ace8549dac690ceeb8907f8&um=0&thdk=&thdt=&rs=1&tn=0.7887325473129749
不知道下一部怎么办？求大神指教

**Comment by zhangn1985** [comment]
然后你要通过chrome开发者工具分析JSON，这个JSON里面应该包含了正确的视频URL list，或者相应信息。
了解了这些后，试着弄清楚生成JSON的URL是怎么拼出来的。知道这一步之后呢，就只剩下写代码和调试了。

**Comment by benhong** [comment]
怎樣重 JSON 內取的下載位置，iqiyi.py 裡面就有實作了，看一下吧並不難

至於如何取的請求位置，這部份看需要反組譯swf檔就可以知道了
 
1.要先登入取的cookies
2.要將特定的參數傳到 "http://api.vip.iqiyi.com/services/ck.action" 包含cookies
3.根據地2點資料 就可以取的token ，其他參數就跟一般的沒有什麼不一樣
