### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by i0sdev** [soimort/you-get#700]
Downloading Ellie Goulding - On My Mind.mp4 ...
 73.7% ( 41.8/56.6 MB) [==============================          ] 1/1

下载时能在显示信息里提供下载速度吗？

**Comment by zhangn1985** [comment]
-p wget 可以现实速度。

**Comment by i0sdev** [comment]
你的意思是先用 `you-get -u`查`url`，然后再用上面的命令下载？

**Comment by soimort** [comment]
Duplicate of #178 and #284
