### ISSUE TITLE
修改爱奇艺swf文件

### ISSUE THREAD

**Issue by dujiancheng** [soimort/you-get#701]
修改爱奇艺的swf文件，添加了trace信息，使用fiddler替换原来的swf后，显示存在恶意插件，视频无法播放。请问该怎么办？谢谢了

**Comment by soimort** [comment]
我也不清楚，建议你email去问对iqiyi这块比较熟悉的人（#689），或者直接在相应issue下@他们。

这里是汇报you-get相关bug的地方，并不是一般性地讨论如何破解修改swf的技术论坛。（除非是…算法又改了，关系到you-get的使用，之类）
