### ISSUE TITLE
[Youku] False warning "This video can only be streamed within Mainland China"

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#714]
There are videos which **could be** streamed from overseas ([sample link](http://v.youku.com/v_show/id_XNzE3NTIzNjQw.html)), however `you-get` wrongly prints a false warning.

```
you_get: [Warning] This video can only be streamed within Mainland China!
you_get: Use '-y' to specify a proxy server for extracting stream data.
```

**Comment by benhong** [comment]
重code 看來 是因為Youku 的server 的 response 的結果
並不是 you_get 的問題

**Comment by soimort** [comment]
No longer relevant since Youku's latest change. Closing.
