### ISSUE TITLE
cx_Freeze打包最新版出问题

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#739]
环境
Python3.4
cx_Freeze 5.0
Win7 32bit

打包后运行
D:\我的文档\Downloads\you-get-develop\build\exe.win32-3.4>you-get --json http://
www.iqiyi.com/v_19rrgxmoiw.html
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by soimort** [comment]
1. Please isolate the problem. Is it related to cx_Freeze, or you-get itself?
2. Please run the command with '--debug' option, as the message suggests you to.

**Comment by redstoneleo** [comment]
运行'--debug提示没有各种module，其中一个问题如下
ImportError: No module named 'you_get.extractor'
仿佛是cx_Freeze很难打包you-get一样，

**Comment by soimort** [comment]
我用cx_Freeze打包并没有遇到这问题。不清楚你具体是怎样操作的，这部分也不在本项目范畴以内，帮不了你了。

建议去cx_Freeze的官方文档找答案，或者看看其他人有没有遇到类似问题。

**Comment by ih4cku** [comment]
@soimort How did you create the [pre-built version](https://github.com/soimort/you-get/releases/download/v0.4.236/you-get-0.4.236-win32.exe) of `you-get` on Windows? Did you use `cv_Freeze`?

**Comment by soimort** [comment]
@ih4cku that was generated by using [PyInstaller](https://github.com/pyinstaller/pyinstaller). :shipit:

**Comment by ih4cku** [comment]
Thanks, Mort, I'll have a try.

**Comment by tryerrorman** [comment]
@soimort After I build by using PyInstaller, when I try to excute the exe, I got the error "SystemError: Parent module ' ' not loaded, cannot perform relative import".

**Comment by zhangn1985** [comment]
you may need a hook: https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong 

``pyinstaller --additional-hooks-dir YOUR_HOOKS_DIR``

**Comment by zhangn1985** [comment]
this better: https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-encodings.py

**Comment by tryerrorman** [comment]
thank you, @zhangn1985 . I have been trying the 'hooks' option, And it still occur the same error. I will check it deeply.

**Comment by redstoneleo** [comment]
@tryerrorman if succeed , please let me know, thanks!

**Comment by redstoneleo** [comment]
@soimort 能分享下你们用PyInstaller编译成单独exe文件的脚本或方法吗？
cx_Freeze没辙了

**Comment by johnxian1** [comment]
@soimort @redstoneleo 能分享下你们用PyInstaller编译成单独exe文件的脚本或方法吗？
谢谢各位
