### ISSUE TITLE
腾讯视频的问题

### ISSUE THREAD

**Issue by mcjoeng** [soimort/you-get#741]
腾讯视频好像不能解析有版权的影片（腾讯自己上传的影片），用户自己上传的就能解析。。。只能解析一些网友上传的短片。。电视剧，综艺，电影，音乐之类的栏目都不能解析， 搞笑，拍客，微电影之类的个人上传视频就能解析。而且二者的网址有不同特点，前者都是以.html结尾，后者都是以vid=xxxxxxxxx结尾

**Comment by cnbeining** [comment]
```you-get```的目的不是为了规避版权限制。

**Comment by mcjoeng** [comment]
你是不是误会了，我又不是说要解析vip付费视频，我说的是那些免费的版权归腾讯的视频（例如各大卫视的综艺节目）解析不了，而那些免费的版权归个人上传者的视频（例如飞碟说系列视频）就能解析。

**Comment by soimort** [comment]
Know issue #663.
