### ISSUE TITLE
music.163.com / netease does not work anymore!

### ISSUE THREAD

**Issue by madStEvil** [soimort/you-get#743]
Hey guys,

since 3 days the download form netease is broken!

I think they have switched the encrypted download key.
Hope you can fix it!

Thanks a lot. PS. nice tool :)

**Comment by soimort** [comment]
I've been experiencing consistent outages on [music.163.com](http://music.163.com/) these days, can't stream any music even from their web interface. I guess they might be facing some copyright issues so they've shut down the access (at least for overseas users).

It'd be helpful if mainland users can confirm this (whether it's working or not).

![screenshot from 2015-10-29 14-01-30](https://cloud.githubusercontent.com/assets/342945/10819055/5be42968-7e46-11e5-8717-020b373265fb.png)

**Comment by soimort** [comment]
As for now, the old server `m1.music.126.net` seems no longer working (everything returns a 404 error), `m2.music.126.net` (which is supposed to work) sometimes just resolves to 1.1.1.1. I'll keep an eye on the issue.

```
λ  you-get-develop [develop] dig m2.music.126.net

; <<>> DiG 9.10.3 <<>> m2.music.126.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6315
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;m2.music.126.net.		IN	A

;; ANSWER SECTION:
m2.music.126.net.	1565	IN	CNAME	m2.music.126.net.wscdns.com.
m2.music.126.net.wscdns.com. 299 IN	A	1.1.1.1

;; Query time: 362 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Oct 29 21:17:05 CET 2015
;; MSG SIZE  rcvd: 102
```

**Comment by soimort** [comment]
As of today, the `m2.music.126.net` starts working. Fixed for myself now, but let me know how it goes.

```
λ  you-get-develop [develop] you-get -i 'http://music.163.com/#/song?id=5259501' 
Site:       163.com
Title:      6. Air on the G String
Type:       MP3 (audio/mpeg)
Size:       10.01 MiB (10494848 Bytes)

```

**Comment by madStEvil** [comment]
no sorry, me it makes no diffrent! But i found out when i use a chinese proxy it worked with m1.music.126.net. I belive they block all none chinese ip addresses. Thats bad...

**Comment by soimort** [comment]
Can you post the result of `dig m2.music.126.net`?

afaik, the block happens on the DNS side, and even if it resolves correctly, you will get timeout on some generated URLs easily. However, the key (`3go8&$8*3*3h0k(2)2`) remains unchanged.

Overseas users will have to go through a proxy. That's all we know.

(For me, my ISP's DNS server does work, but Google's `8.8.8.8` won't resolve)

**Comment by madStEvil** [comment]
I used "m1.music.126.net" for many months, without any proxy and all worked fine. i come from germany, but my server located in the usa have the same problem.

soo i have to use a proxy from now... ?

[steve@c404arch ~]$ dig m1.music.126.net

; <<>> DiG 9.10.3 <<>> m1.music.126.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58268
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;m1.music.126.net.		IN	A

;; ANSWER SECTION:
m1.music.126.net.	18000	IN	CNAME	region.163.com.usgcac.cdnetworks.net.
region.163.com.usgcac.cdnetworks.net. 1800 IN CNAME n2.panthercdn.com.
n2.panthercdn.com.	1701	IN	A	151.249.89.8
n2.panthercdn.com.	1701	IN	A	174.35.71.32

;; Query time: 591 msec
;; SERVER: 192.168.178.1#53(192.168.178.1)
;; WHEN: Di Nov 03 19:05:20 CET 2015
;; MSG SIZE  rcvd: 144



[steve@c404arch ~]$ dig m2.music.126.net

; <<>> DiG 9.10.3 <<>> m2.music.126.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40028
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;m2.music.126.net.		IN	A

;; ANSWER SECTION:
m2.music.126.net.	17370	IN	CNAME	m2.music.126.net.wscdns.com.
m2.music.126.net.wscdns.com. 1800 IN	A	1.1.1.1

;; Query time: 1623 msec
;; SERVER: 192.168.178.1#53(192.168.178.1)
;; WHEN: Di Nov 03 18:47:13 CET 2015
;; MSG SIZE  rcvd: 91

**Comment by soimort** [comment]
For most of the time, m2.music.126.net does not work, and m1.music.126.net simply raises 404 (I haven't tried a Chinese proxy yet, but I can imagine that this blocking could be IP specific). It's not something we can fix on our side.

So sadly yes, you have to get a proxy.

**Comment by happyfalcon** [comment]
I get this: 
1. You have to get a link like this: http://m1.music.126.net/ZLn4bgi7pH_uSTWFsHtwUA==/3141304720605922.mp3.
2. You must change m1 to m5:
http://m5.music.126.net/ZLn4bgi7pH_uSTWFsHtwUA==/3141304720605922.mp3
3. Now you can listen songs from netease music again.

m5.music.126.net works fine and u can download!
Could it be developed any way to automize the process??

**Comment by soimort** [comment]
@happyfalcon It does the trick :+1:

Thanks for figuring it out. I'm changing it right now.
