### ISSUE TITLE
Add a dummy sample of VideoExtractor

### ISSUE THREAD

**Issue by cnbeining** [soimort/you-get#744]
Since there aren't a lot of current usage examples of ```VideoExtractor```, I am still confused about what exactly should a ```VideoExtractor``` achieves.

With a well-commented dummy sample, it could be very helpful to accelerate the process of the transformation to ```VideoExtractor``` for existing sites.

**Comment by zhangn1985** [comment]
广告时间:
https://github.com/zhangn1985/you-get

**Comment by cnbeining** [comment]
@zhangn1985 就是被这个启发的。

**Comment by zhangn1985** [comment]
可惜我这个改动实在时太大了，没办法upstream了。

**Comment by soimort** [comment]
Not now.

As this point, I can't guarantee you anything persistent on the base class interface of `VideoExtractor`. In fact, I would say it will definitely change or even be rewritten, provided that I have spare time working on that. You may see @zhangn1985's implementation if you just want to get video format selection working on more sites (that's the whole point of using `VideoExtractor`, if you wonder _what should a `VideoExtractor` achieves_.)
