### ISSUE TITLE
iqiyi 11/05 版 key

### ISSUE THREAD

**Issue by benhong** [soimort/you-get#750]
iqiyi 11/05 版 key (20151105/MainPlayer_5_2_29_2_c3_3_8_1.swf)
Key
6967d2088d8843eea0ee38ad1a6f9173

驗證
md5(6967d2088d8843eea0ee38ad1a6f9173+7319+397684100)
=B1BBBE223BB0C41112B3785EC2311EF8
故key是正確的

![image](https://cloud.githubusercontent.com/assets/13610597/10993913/9990b142-84ad-11e5-8587-04561c024208.png)

**Comment by sceext2** [comment]
确实是正确的.

**Comment by xyuanmu** [comment]
新版的Zombie.as更改了，我把 ș.sc = Ț; 改成 ș.sc = Ȇ; 只得到了37开头的不过不是正确的，6967d2088d8843eea0ee38ad1a6f9173 这个是如何得来的？

**Comment by benhong** [comment]
@xyuanmu  表示你沒有把全部的code 看完

教你分析

         var Ș:Function = function(param1:String):String
         {
            var k:Array = null;
            var ȣ:int = 0;
            var Ȣ:String = param1;
            k = [];
            ȣ = 16;
            var t:int = 0;
            while(t < ȣ << 2)
            {
               k[t] = 0 | Math.abs(Math.sin(++t)) * 4.294967296E9;
            }
            var add:Function = function(param1:Number, param2:Number):Number
            {
               return ((param1 >> 1) + (param2 >> 1) << 1) + (param1 & 1) + (param2 & 1);
            };
            var msg:Function = function():String
            {
               var _loc1_:* = NaN;
               var _loc2_:* = NaN;
               var _loc3_:* = NaN;
               var _loc5_:* = 0;
               var _loc15_:Array = null;
               var _loc4_:* = 0;
               var _loc6_:Array = [];
               var _loc7_:String = unescape(encodeURI(Ȣ));
               var _loc8_:int = _loc7_.length;
               var _loc9_:Array = [_loc1_ = 1732584193,_loc2_ = -271733879,~_loc1_,~_loc2_];
               var _loc10_:Array = [0.0,0.0,0.0,0.0];
               var _loc11_:Array = [0,0,0,0];
               var _loc12_:Array = [7,4 * 3,17,22,5,3 * 3,14,20,4,11,ȣ,23,2 * 3,10,5 * 3,7 * 3];
               while(_loc4_ <= _loc8_)
               {
                  _loc6_[_loc4_ >> 2] = _loc6_[_loc4_ >> 2] | (_loc7_.charCodeAt(_loc4_) || 1 << 7) << 8 * (_loc4_++ % 4);
               }
               var _loc13_:int = (1 + (_loc8_ + 8 >> 6)) * ȣ - 2;
               _loc6_[_loc13_] = _loc8_ * 8;
               _loc4_ = 0;
               while(_loc4_ < _loc13_)
               {
                  _loc15_ = _loc9_.concat();
                  _loc5_ = 0;
                  while(_loc5_ < ȣ * 4)
                  {
                     _loc3_ = _loc15_[3];
                     _loc1_ = _loc15_[1];
                     _loc10_[0] = _loc1_ & (_loc2_ = _loc15_[2]) | ~_loc1_ & _loc3_;
                     _loc10_[1] = _loc3_ & _loc1_ | ~_loc3_ & _loc2_;
                     _loc10_[2] = _loc1_ ^ _loc2_ ^ _loc3_;
                     _loc10_[3] = _loc2_ ^ (_loc1_ | ~_loc3_);
                     _loc11_[0] = _loc5_;
                     _loc11_[1] = 5 * _loc5_ + 1;
                     _loc11_[2] = 3 * _loc5_ + 5;
                     _loc11_[3] = 7 * _loc5_;
                     _loc15_ = [_loc3_ = _loc15_[3],add(_loc1_ = _loc15_[1],(_loc3_ = add(add(_loc15_[0],_loc10_[_loc8_ = _loc5_ >> 4]),add(k[_loc5_],_loc6_[_loc11_[_loc8_] % ȣ + _loc4_]))) << (_loc8_ = _loc12_[4 * _loc8_ + _loc5_++ % 4]) | _loc3_ >>> 32 - _loc8_),_loc1_,_loc2_];
                  }
                  _loc5_ = Math.sqrt(ȣ);
                  while(_loc5_)
                  {
                     _loc9_[--_loc5_] = add(_loc9_[_loc5_],_loc15_[_loc5_]);
                  }
                  _loc4_ = _loc4_ + ȣ;
               }
               var _loc14_:* = "";
               while(_loc5_ < 32)
               {
                  _loc14_ = _loc14_ + (_loc9_[_loc5_ >> 3] >> (1 ^ _loc5_++ & 7) * 4 & 15).toString(ȣ);
               }
               return _loc14_;
            };
            Ȣ = Ȣ.substr(0,2 * ȣ).split("").reverse().join("") + Ȣ.substr(ȣ << 1);
            return msg();
         };
         var ș:Object = {};
         var Ț:String = Ș(Ȇ.join(""));
         if(Ț.length > 4)
         {
            ș.src = "eknas";
            ș.tm = ȗ;
            ș.sc = Ț;
         }

用反向推算，已知 sc = T，T=Ș(Ȇ.join(""));
根據經驗Ș 裡的msg:Function 其實就是md5 故只要不要讓他運算md5就好
所以我們要修改的地方則是，

            Ȣ = Ȣ.substr(0,2 * ȣ).split("").reverse().join("") + Ȣ.substr(ȣ << 1);
            return msg();
修改成
            Ȣ = Ȣ.substr(0,2 * ȣ).split("").reverse().join("") + Ȣ.substr(ȣ << 1);
            return Ȣ;
這樣答案不救出來了，你可以查詢一下Ȣ這個變數在msg()裡肯定有用到

**Comment by xyuanmu** [comment]
@benhong 非常感谢！

**Comment by yangl326-Dylan** [comment]
@benhong 怎么不让它调用这个msg呢？
