### ISSUE TITLE
希望增加对华数的支持

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#751]
http://www.wasu.cn/Play/show/id/346947

**Comment by zhangn1985** [comment]
'key'		: '998ed31dc30d34d8deacda02068f243b',
		'url'   : 'aHR0cDovL3dhcHZvZC1jbmMud2FzdS5jbi9wY3NhbjA2L21ybXMvdm9kLzIwMTIwNzE0LzIwMTIwNzE0MjI1NzA0OTQ2MTJhZjk0OTVfZjEyYjFiNTQubXA0',

url, base64 -d 就是真实url了。

**Comment by zhangn1985** [comment]
但是要构造合法请求可不容易。

**Comment by redstoneleo** [comment]
你在说什么啊？我听不懂

**Comment by cnbeining** [comment]
网页，320+请求了还没到播放URL。

WAP，跑不动。

手机，curl直接copy都403.

是不是他自己的用户。。。也看不了?

**Comment by jindaxia** [comment]
let me have a try

**Comment by soimort** [comment]
这个我真修不了。

![screenshot from 2015-11-20 07-18-52](https://cloud.githubusercontent.com/assets/342945/11293211/1d36557e-8f58-11e5-9d24-92920157b8ae.png)
