### ISSUE TITLE
Why not zip_safe?

### ISSUE THREAD

**Issue by lilydjwg** [soimort/you-get#759]
我觉得 you-get 是 zip_safe 的啊。我试了一下，把整个包和一个入口程序打包到一个 zip 文件里都能够正常使用呢。

**Comment by soimort** [comment]
I can't recall why `zip_safe` [was set to `False`](https://github.com/soimort/you-get/commit/66698f71b80d65c448440ed1ded0631d26465752#diff-2eeaed663bd0d25b7e608891384b7298) (it could be 'cause I want to play safe, since I was uncertain whether it can be `True`), but it seems to be indeed, zip-safe.
