### ISSUE TITLE
you-get这个文件里的代码优化

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#762]
下面是you-get这个文件里之前的代码

if getattr(sys, 'frozen', False):
The application is frozen
    _filepath = os.path.dirname(os.path.realpath(sys.executable))
else:
The application is not frozen
Change this bit to match where you store your data files:
    _filepath = os.path.dirname(os.path.realpath(__file__))

我认为这些代码可以用下面这两行代替掉

_filepath = os.path.dirname(sys.argv[0])
sys.path.insert(1, os.path.join(_filepath, _srcdir))

请大神核实后考虑融入you-get这个文件。

PS我玩不来github，就只能这样了。。。

**Comment by zhangn1985** [comment]
其实我也没搞懂什么是``frozen``

**Comment by soimort** [comment]
I think #392 was simply following the convention here https://cx-freeze.readthedocs.org/en/latest/faq.html#data-files

However, `sys.argv[0]` seems to work as well, thanks.
