### ISSUE TITLE
QQ only downloads SD quality vidoes 

### ISSUE THREAD

**Issue by epikish** [soimort/you-get#763]
There should be 3 different file sizes to choose from 270, 360 and 720. 

> you-get -i http://v.qq.com/cover/j/j0fp5yhsgkh6c29.html?vid=n001877b10t
> Site:       QQ.com
> Title:      英雄联盟2015世界总决赛比赛视频
> Type:       MPEG-4 video (video/mp4)
> Size:       172.63 MiB (181017975 Bytes)

This site can sniff out all the videos, you would just need to merge them with ffmpeg. 
www.flvurl.cn

**Comment by rosynirvana** [comment]
outdated
