### ISSUE TITLE
部分cctv的视频下载完成后在合并阶段出错！

### ISSUE THREAD

**Issue by xujiangit** [soimort/you-get#767]
http://tv.cntv.cn/video/C10606/91fda28a86c94543b3fced47a9f20ea5
上面这个在合并后明显大小不对（只有80多M），后面自己采用以下方法实现：
先转换成ts封装格式：
ffmpeg -i 00.mp4  -c copy -bsf:v h264_mp4toannexb -f mpegts 00.mp4.ts
中间略
ffmpeg -i 07.mp4  -c copy -bsf:v h264_mp4toannexb -f mpegts 07.mp4.ts
然后用concat合并就没有问题了
ffmpeg  -f concat -y -i 'ml.txt' -c copy output.mp4

发现下载的300多个视频里面有15个左右的这种视频
比如：
http://tv.cntv.cn/video/C10606/d82398509c3d4f009d2e47fe4423dd48
http://tv.cntv.cn/video/C10606/54119dd86c3643b688b66710bce7f01c
还有等等。

**Comment by soimort** [comment]
导致这问题的原因是：

1. CNTV 的某些视频分段是损坏的（比如这一段 <https://www.dropbox.com/s/qf688bqjbvrjdzd/part-05.mp4> 丢失了 7492 到 7515 之间的帧），虽然可以正常播放，ffmpeg 单独转码的时候报错但不影响，但是会抛出`EINVAL`错误。
2. 用 FFmpeg 的 concat demuxer 合并的时候，遇到`EINVAL`信号就自动终止，所以产生的文件是不完整的。后面的内容丢掉了。

目前看来可行的解决办法就是多转码一遍，先把损坏的`mp4`转成好的`mpegts`或者`mkv`，最后合并回一个`mp4`。

暂时先把 CNTV 设成 `merge=False` 了。有需要的用户可以手动合并。

**Comment by xujiangit** [comment]
@soimort 这样不能解决这一类问题阿，其他网站下载的视频要是出点错，也会中断。是否可以检测到合并视频出错的时候，采用转成mpegts或者mkv，再合并成一个mp4？

**Comment by soimort** [comment]
以前确实就是这么实现的，后来FFmpeg 1.1有了concat demuxer，就针对新版本改用demuxer了，因为这样效率更高，而且拼接过程中不占用额外的硬盘空间。（参见#324）

FFmpeg demuxer目前存在的问题是解码过程中遇到坏帧会自动终止，但是exit status仍然返回0，没有办法可以知道是否完整合并成功。除非做个Python API wrapper来调用FFmpeg。

**Comment by xujiangit** [comment]
可以用批处理实现吗？linux用sh脚本，windows用bat批处理

**Comment by rosynirvana** [comment]
#2201 
unmerge as default means more complaint so in 5a8715f auto-merge is default behavior again
