### ISSUE TITLE
SOHU 403Error

### ISSUE THREAD

**Issue by yangl326-Dylan** [soimort/you-get#769]
can't download the video! I have try the proxy, it still can't download it!

**Comment by shileimr** [comment]
yes, 403 forbidden...

**Comment by cnbeining** [comment]
Sample URLs please.

**Comment by soimort** [comment]
Next time when reporting an issue, please always attach **at least 1~2 example links, together with --debug output**, for by so doing you will save both of us some time.

**Comment by shileimr** [comment]
ok,thank you..
