### ISSUE TITLE
优酷视频下载不了

### ISSUE THREAD

**Issue by Friday21** [soimort/you-get#771]
今早开始优酷的视频就下载不了了,现在仍然无法下载

**Comment by Friday21** [comment]
friday@friday:~/git/you-get$ python3 you-get -i 'http://v.youku.com/v_show/id_XMTM4OTI0NzkxNg==.html?f=26256295'
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by zhangn1985** [comment]
这下药丸了，

**Comment by Friday21** [comment]
meta = json.loads(get_html('http://v.youku.com/player/getPlayList/VideoIDS/%s/Pf/4/ctype/12/ev/1' % self.vid)

**Comment by Friday21** [comment]
meta = json.loads(get_html('http://v.youku.com/player/getPlayList/VideoIDS/%s/Pf/4/ctype/12/ev/1' % self.vid),    我觉着是http://v.youku.com/player/getPlayList/VideoIDS/%s/Pf/4/ctype/12/ev/1 失效了

**Comment by nuomi1** [comment]
我这也死了……

**Comment by linhua55** [comment]
有人已经给出新的方法
http://www.cnblogs.com/zhxilin/p/4993074.html
好像还是有40分钟限制的。

**Comment by edward32tnt** [comment]
解析ip 与 播放ip 一致才能播放

**Comment by soimort** [comment]
![marshal-you-get-caption](https://cloud.githubusercontent.com/assets/342945/11377619/0da1ea32-92e7-11e5-8cf6-8552bb9d7e8e.png)
