### ISSUE TITLE
patch for w56.py

### ISSUE THREAD

**Issue by kwokts** [soimort/you-get#775]
before patch:
you-get -i http://www.56.com/u64/v_MTM5NjU2NTgx.html
you-get: [error] oops, something went wrong.

patch at line 15:
hd_types = [['normal', 'qvga'], ['clear', 'vga'], ['super', 'dvga']][hd]
change to
hd_types = [['normal', 'qvga'], ['clear', 'vga'], ['super', 'wvga']][hd]

after patch:
you-get -i http://www.56.com/u64/v_MTM5NjU2NTgx.html
Site:       56.com
Title:      《功夫熊猫3》鹿与熊猫奇遇记MV预告
Type:       MPEG-4 video (video/mp4)
Size:       3.34 MiB (3505152 Bytes)

**Comment by soimort** [comment]
Thanks!
