### ISSUE TITLE
letv在线播放为什么是5秒一小段  我用其他方法解析是一整段的

### ISSUE THREAD

**Issue by mcjoeng** [soimort/you-get#777]
letv解析出的在线播放列表怎么是5秒一段 太夸张了根本没法一边解析一边播放 随便一集40多分钟的电视剧就有150段视频 是不是解析方案不妥啊
 我用 http://www.shokdown.com/ 这个网站解析出的letv是一整段视频

**Comment by soimort** [comment]
Duplicate of #606.
