### ISSUE TITLE
优酷视频又下载不了

### ISSUE THREAD

**Issue by Friday21** [soimort/you-get#779]
friday@friday:~/git/you-get$ python3 you-get http://v.youku.com/v_show/id_XMTM5OTc5NzUyOA==.html?f=26308550&ev=4&from=y1.3-idx-uhome-1519-20887.205805-205902.7-1
[1] 5123
[2] 5124
friday@friday:~/git/you-get$ site:                优酷 (Youku)
title:               NBA球星科比亲口宣布退役  本赛季结束将隐退江湖 上海早晨 151130
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          7.9 MiB (8316552 bytes)
    # download-with: you-get --format=hd2 [URL]

you-get: [Failed] Cannot extract video source.

**Comment by linhua55** [comment]
用双引号把网址括住

2015-11-30 15:10 GMT+08:00 李东勇 <notifications@github.com>:

**Comment by Friday21** [comment]
@linhua55  然而并没有什么用

**Comment by yueyaquanBoy** [comment]
@linhua55是的，问题依然存在

**Comment by Friday21** [comment]
我用postman 访问 pl.youku.com 是可以得到结果的:
#EXTM3U
#EXT-X-TARGETDURATION:13
#EXT-X-VERSION:3
#EXTINF:6,
http://60.217.224.107/6572996CA2740837211E733D26/0300080100565BA7C5FBED2F8F1275825400EC-A4AB-72C4-A654-D7CAD83CB486.mp4.ts?ts_start=0&ts_end=5.9&ts_seg_no=0&ts_keyframe=1
#EXTINF:6,
http://60.217.224.107/6572996CA2740837211E733D26/0300080100565BA7C5FBED2F8F1275825400EC-A4AB-72C4-A654-D7CAD83CB486.mp4.ts?ts_start=5.9&ts_end=11.9&ts_seg_no=1&ts_keyframe=1
#EXTINF:6,
http://60.217.224.107/6572996CA2740837211E733D26/0300080100565BA7C5FBED2F8F1275825400EC-A4AB-72C4-A654-D7CAD83CB486.mp4.ts?ts_start=11.9&ts_end=17.9&ts_seg_no=2&ts_keyframe=1
#EXTINF:12,
http://60.217.224.107/6572996CA2740837211E733D26/0300080100565BA7C5FBED2F8F1275825400EC-A4AB-72C4-A654-D7CAD83CB486.mp4.ts?ts_start=17.9&ts_end=29.9&ts_seg_no=3&ts_keyframe=1
#EXTINF:12,
http://60.217.224.107/6572996CA2740837211E733D26/0300080100565BA7C5FBED2F8F1275825400EC-A4AB-72C4-A654-D7CAD83CB486.mp4.ts?ts_start=29.9&ts_end=41.9&ts_seg_no=4&ts_keyframe=1
#EXTINF:12.84,
http://60.217.224.107/6572996CA2740837211E733D26/0300080100565BA7C5FBED2F8F1275825400EC-A4AB-72C4-A654-D7CAD83CB486.mp4.ts?ts_start=41.9&ts_end=54.74&ts_seg_no=5&ts_keyframe=1
#EXT-X-ENDLIST

但用程序就只能得到这样的结果:
#EXTM3U
#EXT-X-TARGETDURATION:-1
#EXT-X-VERSION:3
#EXT-X-ENDLIST

所以可能是headers的设置问题

**Comment by yangaowei** [comment]
是cookies的问题，不过下载视频合并之后又问题  解决中

**Comment by yangaowei** [comment]
过滤m3u8_url的正则匹配有问题，获取urls之后set去重就ok了

**Comment by Friday21** [comment]
@yangaowei  cookies的问题怎么解决的？

**Comment by yangaowei** [comment]
import httplib
import cookielib
import urllib2
cj = cookielib.CookieJar()
opener = urllib2.build_opener(urllib2.HTTPCookieProcessor(cj))
urllib2.install_opener(opener)
response = urllib2.urlopen(url)  #url地址
data = response.read()

现请求下youku播放页的地址，在进行url分析，就会带上cookies访问

**Comment by yangaowei** [comment]
这是python2.7的写法，python3有些不同

**Comment by imlewc** [comment]
估计什么时候能修复呢？以前自己找的个下载  自己改了改  还不错，前几天不好使了，是不是被阿里收了，出了这种问题，周六时的时候还可以呢  昨天就不行了

**Comment by jiemoon** [comment]
为什么和阿里有关？:s

**Comment by zhangn1985** [comment]
为嘛我没遇到，你们有git pull吗？

**Comment by linhua55** [comment]
@zhangn1985
这里有介绍
http://www.cnblogs.com/zhxilin/p/4993074.html

2015-12-01 18:51 GMT+08:00 zhangn1985 <notifications@github.com>:

**Comment by zhangn1985** [comment]
难道我见鬼了，you-get的确能下载优酷视频呀。不知道你们讨论什么。

**Comment by Friday21** [comment]
我这已修复, 修复代码如下(待会儿push commit):
修改common.py , 加入获取cookie 功能

# get cookie(新加)
def getOpener(head):
    cj = http.cookiejar.CookieJar()
    pro = request.HTTPCookieProcessor(cj)
    opener = request.build_opener(pro)
    header = []
    for key, value in head.items():
        elem = (key, value)
        header.append(elem)
    opener.addheaders = header
    return opener


# DEPRECATED in favor of get_content()(修改)
def get_response(url, faker = False):
    if faker:
        response = request.urlopen(request.Request(url, headers = fake_headers), None)
    else:
        user_agent = r'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36'
        headers = {'User-Agent': user_agent, 'Connection': 'keep-alive'}
        opener = getOpener(headers)
        response = opener.open(url)
    data = response.read()
    if response.info().get('Content-Encoding') == 'gzip':
        data = ungzip(data)
    elif response.info().get('Content-Encoding') == 'deflate':
        data = undeflate(data)
    response.data = data
    return response

**Comment by linhua55** [comment]
@zhangn1985 
的确可以用

**Comment by soimort** [comment]
这个视频确实不需要cookie。
