### ISSUE TITLE
可以把代码集成在服务器上吗，不用每次都打命令行获取。

### ISSUE THREAD

**Issue by westice007** [soimort/you-get#780]
我在ios中嵌入了python环境，想把解析视频的功能加上，但是此框架貌似全部是从命令行获取参数，不太好直接访问函数，不太好集成。 
可不可以提供一个函数，传参数进入就把视频信息返回给我。

**Comment by Shawn0987** [comment]
Hi, @westice007 

我也在做相似的事情. 如果方便的话. 想请问下是如何把python环境集成进iOS工程中的?

**Comment by kcao** [comment]
这功能作为学习研究用就好了。搞到服务器上，对外提供服务要吃官司吧。

想调用函数很简单，设好path，import 适当的package （包、文件），就可以了啊，
这是python 的基础性的知识。

**Comment by Shawn0987** [comment]
只是为了自己用new Apple TV看视频方便点.
不对外. 倒是可能开源.

**Comment by kcao** [comment]
@Shawn0987 他说的 iso 用python 是越狱装python 环境吧。
我不清楚移动应用开发。也许你想要的是，
Can I write native iPhone apps using Python
http://stackoverflow.com/questions/43315/can-i-write-native-iphone-apps-using-python

目前来看这个讨论已经不在这个项目范围内了。就再扯远一点，
我自己在家是搞个dlna，电视、手机、电脑想用什么看用什么看。。。

**Comment by soimort** [comment]
（参见 #676）

目前`you-get`并没有简单一致的Python API，一定要用的话，从命令行返回JSON是比较通用的方案。

**Comment by westice007** [comment]
@Shawn0987  我用github上的一个编译脚本，可以编译出python.framework  
https://github.com/pybee/Python-iOS-support

**Comment by westice007** [comment]
@kcao app里一个比较隐藏的功能，应该问题不大吧。

**Comment by westice007** [comment]
@soimort  如果能有直接python函数可以调用那就比较好了，这样我就能在app里使用，哈哈。

**Comment by kcao** [comment]
@westice007  依我的认识，提供服务肯定是不行的。具体发你westice007/test0 issue 说吧。
