### ISSUE TITLE
tudou.py: keyword argument extractor_proxy seems completely ignored

### ISSUE THREAD

**Issue by zmwangx** [soimort/you-get#787]
See [`tudou.py`](https://github.com/soimort/you-get/blob/cd1823e9241cb634d9b68a623490a41052c2b69b/src/you_get/extractors/tudou.py), especially [`tudou_download`](https://github.com/soimort/you-get/blob/cd1823e9241cb634d9b68a623490a41052c2b69b/src/you_get/extractors/tudou.py#L32-L56). It is immediately obvious that although a bunch of keyword arguments can be passed in as `kwargs` (possibly from `common.py`), the only kwarg that's ever utilized is `stream_id`, and in particular, `extractor_proxy` is completely ignored. In my case it led to parsing failure even when an extractor proxy was specified.

A quick and dirty fix is to drop `extractor_proxy=kwargs['extractor_proxy'] if 'extractor_proxy' in kwargs else None` to the appropriate calls, but this issue seems to be pointing to a dirtier larger picture. Since I don't know the you-get API and only traced the problem of a single video, there might be other important kwargs that are equally ignored. Also, `tudou.py` is still using quite some API functions marked as deprecated, e.g., `get_decoded_html`, `r1`. Therefore, it is my belief that `tudou.py` needs a thorough code review from someone who's familiar with the ins and outs of you-get. Thanks.

**Comment by linhua55** [comment]
Please provide the command and url you use.

**Comment by zmwangx** [comment]
Didn't I already identify the problem? I'm not looking for help with troubleshooting.

```
you-get -x host:port http://www.tudou.com/albumplay/anything
```

Substitute anything you like in place of proxy and video URL (as long as it's from Tudou — and in my case it has a `vcode`, so it's eventually delegated to `youku.py`). The fact is in the end `extractor_proxy` just isn't passed to `youku.youku_download_by_vid`.

**Comment by linhua55** [comment]
@zmwangx 
Just add `**kwargs` to the end of parameter list of the `youku_download_by_vid` function which in `tudou_download` function.
I don't have environment to test.Could you test this?
BTW,The abbreviation of  `--extractor-proxy` option is `-y`.

**Comment by zmwangx** [comment]
> Just add `**kwargs` to the end of parameter list of the `youku_download_by_vid` function which in `tudou_download` function.

Apparently that's the first thing anyone would try first, and I did try that. It worked, but since I don't know why the `stream_id` conditional was there in the first place but not anything else (maybe it's just legacy, non-extensible code; I didn't review the history), and I didn't have cases with other keyword arguments to test with, so I was cautious not to suggest removing that conditional in favor of a single call with `**kwargs`, but instead suggest a code review by someone knowledgeable in you-get.

Also, `youku_download_by_vid` isn't the only problem in `tudou.py`. It has its own HTTP request to retrieve the Tudou page, which should be proxied when appropriate. Moreover, as I said above, it has other problems, e.g., deprecated API calls.

**Comment by zmwangx** [comment]
In fact, now that I blamed it, the non-extensible code was introduced in commit https://github.com/soimort/you-get/commit/ef16e74fe72e7779a0b10af56f435cb2558d90c7 as a quick fix to another similar problem. It might be better to view the package as a whole instead of issuing quick local fixes, which might introduce problems later. Thus a code review is needed.

**Comment by zmwangx** [comment]
By the way, I found yet another problem: shouldn't we just `return` after `youku_download_by_vid`?

**Comment by soimort** [comment]
FYI, I myself haven't used `extractor_proxy` or Unblock Youku's proxy for ages. And I wouldn't be surprised if `tudou.py` seems broken to you, because I rarely use it. (partly due to Tudou's slowness for overseas access)

I'm not quite sure what's the main point you're trying to address here, if it's anything about the failure of using `extractor_proxy`: if I recall correctly, `--extractor_proxy` was **only implemented for Youku and Sohu** (which seems broken for now).

In the beginning there was `--extractor_proxy` (for Youku and Sohu), then we tried to rewrite some of our nasty code using `VideoExtractor` (for YouTube and Youku), then `kwargs` was added to almost every extractor (#675) as a quick hack to implement `--json`. You may not expect everything to be perfect or even consistent, because we (maintainers and contributors) prefer to get some code that just works, and fix things only when necessary.

When you have a concrete idea about how things should be improved -- pull requests are always welcome.

**Comment by zmwangx** [comment]
> `--extractor_proxy` was only implemented for Youku and Sohu.

Sure, but `tudou.py` calls `youku_download_by_vid` in many cases, so you just need to relay `kwargs` for a free ride. No need for separate support.

> When you have a concrete idea about how things should be improved -- pull requests are always welcome.

Well, I'd rather be conservative and not submit PRs that might break other people's use cases (due to limited global understanding), unless the changes are truly localized. Anyway, here's a patch that would fix the issues described here (for me at least):

```diff
diff --git a/src/you_get/extractors/tudou.py b/src/you_get/extractors/tudou.py
old mode 100644
new mode 100755
index 331a535..9f4f124
--- a/src/you_get/extractors/tudou.py
+++ b/src/you_get/extractors/tudou.py
@@ -44,10 +44,7 @@ def tudou_download(url, output_dir = '.', merge = True, info_only = False, **kwa
     vcode = r1(r'vcode\s*[:=]\s*\'([^\']+)\'', html)
     if vcode:
         from .youku import youku_download_by_vid
-        if 'stream_id' in kwargs:
-            return youku_download_by_vid(vcode, title=title, output_dir=output_dir, merge=merge, info_only=info_only, stream_id=kwargs['stream_id'])
-        else:
-            return youku_download_by_vid(vcode, title=title, output_dir=output_dir, merge=merge, info_only=info_only)
+        return youku_download_by_vid(vcode, title=title, output_dir=output_dir, merge=merge, info_only=info_only, **kwargs)
 
     iid = r1(r'iid\s*[:=]\s*(\d+)', html)
     if not iid:
```

**Comment by soimort** [comment]
Correct. Thanks for your fix -- it does work properly.
