### ISSUE TITLE
Help! Error

### ISSUE THREAD

**Issue by leovoon** [soimort/you-get#790]
![capture](https://cloud.githubusercontent.com/assets/16155802/11595947/14b00b5c-9aed-11e5-83f8-7b6d5d846d00.PNG)

succesfully installed you-get with pip3 but get this

**Comment by linhua55** [comment]
you-get -du http://www.iqiyi.com/kszt/bpbxd3.html

2015-12-05 1:12 GMT+08:00 leovoon <notifications@github.com>:

**Comment by leovoon** [comment]
Sorry i didn't mention that I was using Ultrasulf proxy, something wrong with the connection. When I don't use it, it works fine. Is there any way to make it works?


C:\WINDOWS\system32>you-get -du http://www.iqiyi.com/kszt/bpbxd3.html
you-get: version 0.4.176, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/kszt/bpbxd3.html']
Traceback (most recent call last):
  File "c:\users\eldy\appdata\local\programs\python\python35\lib\runpy.p
 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\eldy\appdata\local\programs\python\python35\lib\runpy.p
 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Eldy\AppData\Local\Programs\Python\Python35\Scripts\you
\__main__.py", line 9, in <module>
  File "c:\users\eldy\appdata\local\programs\python\python35\lib\site-pa
ou_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\eldy\appdata\local\programs\python\python35\lib\site-pa
ou_get\common.py", line 1216, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs
  File "c:\users\eldy\appdata\local\programs\python\python35\lib\site-pa
ou_get\common.py", line 1137, in script_main
    download_main(download, download_playlist, args, playlist, output_di
_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "c:\users\eldy\appdata\local\programs\python\python35\lib\site-pa
ou_get\common.py", line 990, in download_main
    download(url, **kwargs)
  File "c:\users\eldy\appdata\local\programs\python\python35\lib\site-pa
ou_get\common.py", line 1209, in any_download
    m.download(url, **kwargs)
  File "c:\users\eldy\appdata\local\programs\python\python35\lib\site-pa
ou_get\extractor.py", line 48, in download_by_url
    self.extract(**kwargs)
  File "c:\users\eldy\appdata\local\programs\python\python35\lib\site-pa
ou_get\extractors\iqiyi.py", line 194, in extract
    urls.append(json.loads(get_content(url))["l"])
  File "c:\users\eldy\appdata\local\programs\python\python35\lib\json\__
y", line 319, in loads
    return _default_decoder.decode(s)
  File "c:\users\eldy\appdata\local\programs\python\python35\lib\json\de
", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\eldy\appdata\local\programs\python\python35\lib\json\de
", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by cnbeining** [comment]
Cannot reproduce.

```
you-get -du http://www.iqiyi.com/kszt/bpbxd3.html
site:                爱奇艺 (Iqiyi)
title:               奔跑吧兄弟第3季之鹿晗秒变傻狍子 陈赫遭爆料
stream:
    - format:        suprt-high
      container:     f4v
      video-profile: 超高清
      size:          1198.3 MiB (1256513722 bytes)
    # download-with: you-get --format=suprt-high [URL]

Real URLs:
(omited)
```

Also
```
{
ip: "142.1.**.**",
hostname: "wifihost-****.wireless.utsc.utoronto.ca",
city: "Toronto",
region: "Ontario",
country: "CA",
loc: "43.6629,-79.3987",
org: "AS239 University of Toronto",
postal: "***"
}
```

**Comment by nuomi1** [comment]
@cnbeining 我这默认解析的是 `fullhd` 诶？

```
you-get -du http://www.iqiyi.com/kszt/bpbxd3.html
site:                爱奇艺 (Iqiyi)
title:               奔跑吧兄弟第3季之鹿晗秒变傻狍子 陈赫遭爆料
stream:
    - format:        fullhd
      container:     f4v
      video-profile: 全高清
      size:          2337.9 MiB (2451449146 bytes)
    # download-with: you-get --format=fullhd [URL]

Real URLs:
(omitted)
```

**Comment by cnbeining** [comment]
@nuomi1 也许是因为我的脸比较黑？

![y7_ d9 q kf m5o2](https://cloud.githubusercontent.com/assets/1560962/11605427/526afc74-9acd-11e5-8754-b91e4e979d0a.png)

**Comment by soimort** [comment]
> Sorry i didn't mention that I was using Ultrasulf proxy, something wrong with the connection. When I don't use it, it works fine. Is there any way to make it works?

If that is the case, shouldn't you just try to fix your proxy?
