### ISSUE TITLE
you-get: [Failed] 用户没有权限观看，请返回主站播放

### ISSUE THREAD

**Issue by dengzhp** [soimort/you-get#793]
RT

**Comment by phpengineer** [comment]
我刚刚也遇到这个问题了
you_get: [Failed] 用户没有权限观看，请返回主站播放
you_get: [Failed] 用户没有权限观看，请返回主站播放
you_get: [Failed] 用户没有权限观看，请返回主站播放
you_get: [Failed] 用户没有权限观看，请返回主站播放
you_get: [Failed] 用户没有权限观看，请返回主站播放
Traceback (most recent call last):
  File "/data0/htdocs/downloadvideo/you-get/you-get", line 13, in <module>
    you_get.main(repo_path=_filepath)
  File "/data0/htdocs/downloadvideo/you-get/src/you_get/__main__.py", line 91, in main
    main()
  File "/data0/htdocs/downloadvideo/you-get/src/you_get/common.py", line 993, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/data0/htdocs/downloadvideo/you-get/src/you_get/common.py", line 891, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/data0/htdocs/downloadvideo/you-get/src/you_get/common.py", line 783, in download_main
    download(url, **kwargs)
  File "/data0/htdocs/downloadvideo/you-get/src/you_get/common.py", line 986, in any_download
    m.download(url, **kwargs)
  File "/data0/htdocs/downloadvideo/you-get/src/you_get/extractors/ku6.py", line 35, in ku6_download
    ku6_download_by_id(id, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/data0/htdocs/downloadvideo/you-get/src/you_get/extractors/ku6.py", line 11, in ku6_download_by_id
    data = json.loads(get_html('http://v.ku6.com/fetchVideo4Player/%s...html' % id))['data']
  File "/data0/htdocs/downloadvideo/you-get/src/you_get/common.py", line 147, in get_html
    content = get_response(url, faker).data
  File "/data0/htdocs/downloadvideo/you-get/src/you_get/common.py", line 135, in get_response
    response = request.urlopen(url)
  File "/usr/local/python3/lib/python3.3/urllib/request.py", line 160, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python3/lib/python3.3/urllib/request.py", line 479, in open
    response = meth(req, response)
  File "/usr/local/python3/lib/python3.3/urllib/request.py", line 591, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/python3/lib/python3.3/urllib/request.py", line 517, in error
    return self._call_chain(*args)
  File "/usr/local/python3/lib/python3.3/urllib/request.py", line 451, in _call_chain
    result = func(*args)
  File "/usr/local/python3/lib/python3.3/urllib/request.py", line 599, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by Friday21** [comment]
我也是

**Comment by lotabout** [comment]
楼上的好快啊，我也刚遇到

**Comment by linhua55** [comment]
请贴出命令，是哪个视频站？

**Comment by phpengineer** [comment]
python3 /downloadvideo/you-get/you-get -u 'http://v.youku.com/v_show/id_XMTQwNzEwNDgzMg==.html?from=s1.8-1-1.2'

**Comment by zpyxxlove** [comment]
你们这速度好快. 优酷是不是被阿里收购之后, 对数据安全又加了很多东西.

**Comment by jiemoon** [comment]
原来大家都一样

**Comment by linhua55** [comment]
需要添加HTTP头
  Referer: http://static.youku.com

**Comment by phpengineer** [comment]
对，在116行请求api_url时，出现了这个错误，加上referer就能正常请求了

**Comment by yangaowei** [comment]
代码是哪个分支是哪个分支上的？我这加referer不行，抓包发现，解析规则有变化

**Comment by phpengineer** [comment]
直接就是develop这个分支，你加了referer后报什么错？我加了referer后就能正常返回之前的json串了

**Comment by yangaowei** [comment]
返回json串，不能下载

**Comment by leeeboo** [comment]
现在返回的格式貌似有变化。今天找时间研究研究。

2015年12月8日星期二，闫高威 <notifications@github.com> 写道：

> 返回json串，不能下载
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soimort/you-get/issues/793#issuecomment-162802599>.
>


-- 
李博

我们是搞开发的

<http://t.sina.com.cn/1749026125?s=6uyXnP>

**Comment by phpengineer** [comment]
那就是下载逻辑这块也改了！oops

**Comment by yangaowei** [comment]
获取播放地址的url是这样：http://k.youku.com/player/getFlvPath/sid/14495582013571004d43f_00/st/flv/fileid/0300020100565497A1DC9A2F39C2043D7AEA8C-82E0-EADF-F986-7D2096683919?K=f07314a907cdd3e724126e9d&hd=0&myp=0&ts=377&ypp=2&ctype=10&ev=1&token=5181&oip=2034572266&ep=sTkIAJ%2FwP2MZsknV7NcLV0FRZlwynVbSDJaH%2BcpJokG51tGN7pQmsGfUOuclAksUCRifFpCsUxjFdKw1RPeUa%2FlEZ8aOxrkUx6BOXNrCkWNzLKSqqYQcXkEcHrjnHoYhHpWlsRuQxBU%3D&yxon=1&special=true

感觉又回到之前了

**Comment by leeeboo** [comment]
是的。。。

2015年12月8日星期二，xrh <notifications@github.com> 写道：

> 那就是下载逻辑这块也改了！oops
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soimort/you-get/issues/793#issuecomment-162802749>.
>


-- 
李博

我们是搞开发的

<http://t.sina.com.cn/1749026125?s=6uyXnP>

**Comment by Friday21** [comment]
没有啊, 我这返回的还是http://pl.youku.com/playlist/m3u8?type=mp4&oip=1033160962&keyframe=1&ts=1449558702&vid=XMTI2MDYyMTg2MA%3D%3D&ctype=12&ev=1&token=3110&sid=844955870258712a02250&ep=eiaQE0yIXskA5ybXjz8bNizgdnIPXJZ3kmaH%2FKYLScZAH%2BrC6DPcqJ6xT%2F8%3D
我的Referer是下载优酷视频的url, 不是http://static.youku.com

**Comment by phpengineer** [comment]
只要是youku.com域的就行吧，我刚刚加了http://v.youku.com也行

**Comment by Friday21** [comment]
@phpengineer 那你的能下载吗现在?

**Comment by leeeboo** [comment]
肯定不行的 按照老算法获得的m3u8是空的。

2015年12月8日星期二，李东勇 <notifications@github.com> 写道：

> @phpengineer <https://github.com/phpengineer> 那你的能下载吗现在?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soimort/you-get/issues/793#issuecomment-162804152>.
>


-- 
李博

我们是搞开发的

<http://t.sina.com.cn/1749026125?s=6uyXnP>

**Comment by phpengineer** [comment]
不能

**Comment by Friday21** [comment]
你们没更新吧?代码已经为新算法更新一次了

**Comment by yangaowei** [comment]
python3  you-get --debug 'http://v.youku.com/v_show/id_XMTQwNzEwNDgzMg==.html' @Friday21  看能下载吗？

**Comment by Friday21** [comment]
能下啊,[{'url': 'http://111.206.134.201/67744D96A653682C0789FE45FA/030008010056662BE010A12F8F1275850E2C57-0822-7006-B792-878A38F210AD.mp4.ts', 'start': 0, 'stype': 'mp4', 'end': 55, 'key': '45d1988c6f'}]

**Comment by yangaowei** [comment]
我想问下，你在哪个地区？规则还没有变化，我这真心不行  @Friday21

**Comment by leeeboo** [comment]
规则肯定变化了 北京联通 电信都已经不行了

2015年12月8日星期二，闫高威 <notifications@github.com> 写道：

> 我想问下，你在哪个地区？规则还没有变化，我这真心不行 @Friday21 <https://github.com/Friday21>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soimort/you-get/issues/793#issuecomment-162810055>.
>


-- 
李博

我们是搞开发的

<http://t.sina.com.cn/1749026125?s=6uyXnP>

**Comment by yangaowei** [comment]
好的，谢谢 @leeeboo   一起看看

**Comment by leeeboo** [comment]
嗯 晚一点看一看 估计不会有什么大的变化

2015年12月8日星期二，闫高威 <notifications@github.com> 写道：

> 好的，谢谢 @leeeboo <https://github.com/leeeboo> 一起看看
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soimort/you-get/issues/793#issuecomment-162810266>.
>


-- 
李博

我们是搞开发的

<http://t.sina.com.cn/1749026125?s=6uyXnP>

**Comment by Friday21** [comment]
我在北京啊, 现在第二步是:http://play.youku.com/play/get.json?vid={vid}&ct=12

**Comment by leeeboo** [comment]
第二步是这个的 加了referer也可以获得数据。但是按照老的办法算出的m3u8是空白的。

2015年12月8日星期二，李东勇 <notifications@github.com> 写道：

> 我在北京啊, 现在第二步是:http://play.youku.com/play/get.json?vid={vid}&ct=12
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soimort/you-get/issues/793#issuecomment-162810489>.
>


-- 
李博

我们是搞开发的

<http://t.sina.com.cn/1749026125?s=6uyXnP>

**Comment by Friday21** [comment]
哦, 拼接好m3u8后访问时要带上http://play.youku.com/play/get.json?vid={vid}&ct=12返回的Cookie

**Comment by yangaowei** [comment]
能加下qq吗？我的313541012  看看是什么情况 @Friday21 @leeeboo

**Comment by Friday21** [comment]
我待会pull request 你们看看吧

**Comment by leeeboo** [comment]
我这边php实现了：


'http://play.youku.com/play/get.json?vid=' . $vid . 'ct=12’
这个接口会返回一个r=XXX的cookie


在最后请求m3u8的时候带上这个cookie就好了。


原始邮件
发件人:李东勇notifications@github.com
收件人:soimort/you-getyou-get@noreply.github.com
抄送:Albert Leelb13810398408@gmail.com
发送时间:2015年12月8日(周二) 16:26
主题:Re: [you-get] you-get: [Failed] 用户没有权限观看，请返回主站播放 (#793)


我待会pull request 你们看看吧

**Comment by yangaowei** [comment]
http://play.youku.com/play/get.json?vid=XMTM0NDk1ODM4NA==&ct=12  请求这个url就会返回错误信息。

**Comment by Friday21** [comment]
@yangaowei , 看看我新提交的#794能解决吗?
#794

**Comment by yangaowei** [comment]
还是不行，http://play.youku.com/play/get.json?vid=XMTM0NDk1ODM4NA==&ct=12 请求这个url就会报错：ExtractorError: 用户没有权限观看，请返回主站播放，我再看看  谢谢  @Friday21

**Comment by puderty** [comment]
我这边试的的是不定时的出现403，下载地址，多刷新一会儿又变回了正常的302

**Comment by zlotus** [comment]
西安，电信，我这边改成ct=11就可以了。

**Comment by zlotus** [comment]
@Friday21 如果只改**youku.py**不知道行不行？
在`from ..common import *`之后，就可以修改**common.py**里的全局变量`cookies`和`fake_headers`，然后使用`get_content(url, headers={}, decoded=True)`方法代替`get_html(url, encoding = None, faker = False)`获得结果。

**Comment by puderty** [comment]
我并没有采用你们的m3u8的方式，而是用的以前的老方法，只是套用了一下这个security_strings来获取EP，这个fix之后还是不定时的有403.

**Comment by puderty** [comment]
对，我就是用的ct=12获取security_strings然后用ct=10获取分段的方法实现的，ct=10的security_strings解析不了，我现在马上试试你的这个fix

**Comment by puderty** [comment]
@linhua55 我试了， 你这个思路和我一样啊，还是有很大几率403

**Comment by leeeboo** [comment]
最终请求ctype=12的m3u8的时候是需要之前的cookie的。


原始邮件
发件人:pudertynotifications@github.com
收件人:soimort/you-getyou-get@noreply.github.com
抄送:Albert Leelb13810398408@gmail.com
发送时间:2015年12月9日(周三) 15:28
主题:Re: [you-get] you-get: [Failed] 用户没有权限观看，请返回主站播放 (#793)


@linhua55 我试了， 你这个思路和我一样啊，还是有很大几率403

**Comment by puderty** [comment]
@leeeboo 你是说用cookie的形式添加吗？我用java实现的，那么比如说播放器中也要添加这个Cookie吗？播放器好像加不了啊

**Comment by puderty** [comment]
谢谢@soimort 和 @linhua55 我加上cookie并且对每个getFlvPath head一遍获取最终地址后，现在OK了

**Comment by phpengineer** [comment]
![2hw_k owq_h dft60gyv1](https://cloud.githubusercontent.com/assets/4864847/11682307/d690ac5e-9e9e-11e5-91fe-8fd202b8bcc8.png)
403是为什么？

**Comment by phpengineer** [comment]
git pull后OK了！
