### ISSUE TITLE
[youku]The video's default language is "粤语"

### ISSUE THREAD

**Issue by linhua55** [soimort/you-get#797]
Sample command:

    you-get -du --format=hd2  "http://v.youku.com/v_show/id_XNTc2NDk2MDMy"

Though the title  is `疯狂原始人（国语）` in its output.But the video's language is "粤语".Since the output json of `play.youku.com` for this vid not only contain **segs information** for "国语",but also have segs information for "英语" and "粤语".While the segs information of "粤语" is the last one in the order.The segs information of "国语" was overrided by the segs information of "粤语".
related codes:

https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/youku.py#L176-L189

**Comment by soimort** [comment]
Looks ok to me.

As a more proper fix, I would use `'audio_lang'` to identify different audio tracks - because we don't know when the duplicated `stream_id` would exactly occur (the sequence matters in that case).
