### ISSUE TITLE
优酷下载几个文件后失速

### ISSUE THREAD

**Issue by zlotus** [soimort/you-get#799]
使用 commit 4d1e69eae0aafa2bbfefa5eef86744723c338aff 下载优酷大文件时（如链接：[http://v.youku.com/v_show/id_XMTQwNzk0MDQzMg==.html?from=y1.7-2](http://v.youku.com/v_show/id_XMTQwNzk0MDQzMg==.html?from=y1.7-2)），urls列表共36个文件，满速下载到第5、6个文件时，总是会出现速度突然降低的现象，优酷有anti-robot的设置吗？

不知道是我的个案还是普遍现象。

**Comment by univert** [comment]
是有这个情况

**Comment by zlotus** [comment]
奇怪的是，今天腾出时间专门测试了一下，这个现象消失了-_-||

**Comment by nuomi1** [comment]
CDN 不一定所有文件都是最近最快的服务器。
