### ISSUE TITLE
Letv Error 403

### ISSUE THREAD

**Issue by szz27106** [soimort/you-get#801]
scott@t420s-u1404:~$ python3 /home/scott/git/you-get/you-get --debug --format 720p http://www.letv.com/ptv/vplay/24116585.html#vid=24116585
you-get: version 0.4.176, a tiny downloader that scrapes the web.
you-get: ['http://www.letv.com/ptv/vplay/24116585.html#vid=24116585']
Traceback (most recent call last):
  File "/home/scott/git/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/scott/git/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/scott/git/you-get/src/you_get/common.py", line 1216, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/scott/git/you-get/src/you_get/common.py", line 1132, in script_main
    download_main(download, download_playlist, args, playlist, stream_id=stream_id, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/home/scott/git/you-get/src/you_get/common.py", line 990, in download_main
    download(url, **kwargs)
  File "/home/scott/git/you-get/src/you_get/common.py", line 1209, in any_download
    m.download(url, **kwargs)
  File "/home/scott/git/you-get/src/you_get/extractors/letv.py", line 139, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "/home/scott/git/you-get/src/you_get/extractors/letv.py", line 93, in letv_download_by_vid
    _, _, tmp = url_info(i)
  File "/home/scott/git/you-get/src/you_get/common.py", line 336, in url_info
    response = request.urlopen(request.Request(url))
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by soimort** [comment]
Anyone can confirm this? I timed-out on Letv all the time.

**Comment by szz27106** [comment]
It's working now for this episode, but got 403 on other episodes.
Small bug on progress bar when total pieces over 100:
scott@t420s-u1404:~/Videos/miyue$ !1983
python3 /home/scott/git/you-get/you-get --debug --format 720p http://www.letv.com/ptv/vplay/24116585.html#vid=24116585
Site:       LeTV.com
Title:      芈月传05
Type:       MPEG-4 video (video/mp4)
Size:       505.94 MiB (530517952 Bytes)

Downloading 芈月传05.mp4 ...
  7.1% ( 36.2/505.9MB) ├████████─────────────────────────────────────────────────────────────────────────────────────────────────────────┤[10/149]  310 kB/     7.2% ( 36.4/505.9MB) ├████████─────────────────────────────────────────────────────────────────────────────────────────────────────────┤[10/149]    1 MB/     7.2% ( 36.7/505.9MB) ├████████─────────────────────────────────────────────────────────────────────────────────────────────────────────┤[10/149]    2 MB/     7.3% ( 36.9/505.9MB) ├████████─────────────────────────────────────────────────────────────────────────────────────────────────────────┤[10/149]    4 MB/     7.3% ( 37.2/505.9MB) ├████████─────────────────────────────────────────────────────────────────────────────────────────────────────────┤[10/149]    4 MB/     7.4% ( 37.4/505.9MB) ├████████─────────────────────────────────────────────────────────────────────────────────────────────────────────┤[10/149]    4 MB/     7.4% ( 37.7/505.9MB) ├████████─────────────────────────────────────────────────────────────────────────────────────────────────────────┤[10/149]    4 MB/     7.5% ( 37.9/505.9MB) ├████████─────────────────────────────────────────────────────────────────────────────────────────────────────────┤[10/149]    4 MB/     7.5% ( 38.2/505.9MB) ├████████─────────────────────────────────────────────────────────────────────────────────────────────────────────┤[10/149]    4 MB/

**Comment by szz27106** [comment]
I tried same command on a machine in China and not even to get the list of urls.

**Comment by soimort** [comment]
Seems good. Closing.

```
$ you-get -di http://www.letv.com/ptv/vplay/24116585.html\#vid\=24116585 
Current Video Supports:
	--format 720p <URL>
	--format 1080p <URL>
	--format 1000 <URL>
	--format 1300 <URL>
	--format 350 <URL>
Site:       LeTV.com
Title:      芈月传05
Type:       MPEG-4 video (video/mp4)
Size:       1004.78 MiB (1053592420 Bytes)

[⌛] (0.120s : sys + 0.963s : user) / 22.914s : all = 4% : cpu $ noglob /home/soimort/Projects/you-get/you-get -di 

```
