### ISSUE TITLE
windows 8.1 64位系统下载爱奇艺视频经常会断开

### ISSUE THREAD

**Issue by lzy0699** [soimort/you-get#804]
![youget](https://cloud.githubusercontent.com/assets/16253242/11740378/080faac0-a02d-11e5-81b8-997ac4b49404.png)
如题，每次都需要手动重连，有没有什么方法设置自动重新连接？

还有一个问题就是：现在新版you-get的是不是只能在Python 3.5环境下才能运行，不能在Python 3.4.3下运行吗？因为我经常用的XP系统，XP系统好像只能装Python 3.4.3，然后运行you-get的时候说找不到一个
Python 3.5的dll文件而运行不了。

最后感谢开发了这么好的工具！

**Comment by zhangn1985** [comment]
爱奇艺的链接是会超时的。

**Comment by linhua55** [comment]
因为所有分段的地址是有时间限制的，如果下载速度较慢，下到最后几个分段时，这些分段的地址可能就超时了，就不可用了。只有重新解析，生成有效地址。

**Comment by soimort** [comment]
同上。

> 还有一个问题

如果你用的是打包好的`you-get.exe`，应该是不依赖具体系统和Python版本的（运行时需要的链接库已经包含在内）。
当然如果XP下运行出现任何问题，也没什么好奇怪，毕竟我手头没有XP机器用来测试，也没有打算支持XP。
