### ISSUE TITLE
为什么有的是有下载链接的  有的却没有

### ISSUE THREAD

**Issue by imlewc** [soimort/you-get#806]
{
    "site": "优酷 (Youku)",
    "streams": {
        "flvhd": {
            "container": "flv",
            "size": 6554871,
            "video_profile": "标清"
        },
        "hd2": {
            "container": "flv",
            "size": 27558163,
            "src": [
                "http://103.41.141.111/youku/697477A04EB387A3F674D6156/03000101005657C590B51905C062B8F9AD5AB8-8E22-1CF0-8D76-029C1E0BEEC8.flv"
            ],
            "video_profile": "超清"
        },
        "mp4": {
            "container": "mp4",
            "size": 12581158,
            "video_profile": "高清"
        }
    },
    "title": "#Einstein100 - General Relativity_1",
    "url": "http://v.youku.com/v_show/id_XMTM5NzE3MzYzMg==.html"
}

**Comment by soimort** [comment]
因为默认只会解析最高画质（超清）的地址。

如要解析其他画质，需要用`--format`选项指定。

**Comment by imlewc** [comment]
其实就是获取各种格式的下载地址   我们这边想借用下  做个接口
