### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by ziuldeargon** [soimort/you-get#808]
Can't download this one =/

http://www.nicovideo.jp/watch/sm27781153

![screeenshot](https://cloud.githubusercontent.com/assets/7907421/11765969/7589bb02-a12e-11e5-9ed2-c9efecd91ae5.png)

**Comment by soimort** [comment]
Nicovideo's server isn't always stable, you'll just have to try the download later.

**Comment by ziuldeargon** [comment]
Yeah, I got it working after 15mins. I found it weird for a random link to fail. This never happened when downloading stuff from bilibili for example.

Thanks for clarifying anyway =)

**Comment by ziuldeargon** [comment]
Is there a way to make you-get keep re-trying to download a video?
Over 95% of my attempts are failing since yesterday with this error =(
It could take me the whole afternoon to download just 1 video by trying, failing and waiting over and over for the server to be "stable". Even though I am using a premium account and I don't see the website player failing to load any video =/

Any thoughts?

**Comment by ziuldeargon** [comment]
Another program I used to download from nico is showing the exact same behaviour as you-get recently. I think this is an actual issue.
