### ISSUE TITLE
关于you-get运行问题疑问

### ISSUE THREAD

**Issue by tommyzhaozbh** [soimort/you-get#812]
今天好不容易把python装进电脑，也把you-get装上了。但运行起来就是各种syntax error。究竟是哪里有问题……
![2](https://cloud.githubusercontent.com/assets/8757104/11803592/41b10028-a337-11e5-94f7-b33009109626.PNG)

**Comment by cnbeining** [comment]
请在命令行下运行，而不是Python的交互模式下。

**Comment by cnbeining** [comment]
另：请使用有意义标题。

**Comment by tommyzhaozbh** [comment]
@cnbeining 但是如果直接在cmd下面执行的话那也直接输入you-get? 这样的话压根就没法运行……

**Comment by gumplee** [comment]
你这是在python交互模式下运行的啊,直接在命令行pyhon you-get .....

**Comment by tommyzhaozbh** [comment]
@gumplee 兴许是我没把you-get的安装包放对地方，运行起来变成file not found......7z里面的东西该放哪儿？

**Comment by soimort** [comment]
![99a28b2e-869c-11e5-842e-4bca14cd7f81 png](https://cloud.githubusercontent.com/assets/342945/11805247/963105b2-a30a-11e5-9a02-e2ca3cadaa94.png)

**Comment by zhangn1985** [comment]
nice

**Comment by tommyzhaozbh** [comment]
@soimort 这个问题算是告一段落了。但我在英文版windows中测试却出现这样子的错误
![1](https://cloud.githubusercontent.com/assets/8757104/11806673/aba88ff6-a34f-11e5-85ad-73a595457c64.PNG)
如果按照wiki里面的进行修改，连程序都崩溃了……
![3](https://cloud.githubusercontent.com/assets/8757104/11806685/c25ff50e-a34f-11e5-9f62-ef97613c85b5.PNG)

**Comment by lzy0699** [comment]
地址要把#及以後的都刪掉吧，只到.html。

**Comment by soimort** [comment]
Related: https://github.com/pyinstaller/pyinstaller/issues/1705

**Comment by soimort** [comment]
Reminder to myself: build the next release of `you-get` on PyInstaller 3.1, see if the issue mentioned in https://github.com/soimort/you-get/issues/812#issuecomment-164696201 persists.

In case I forget, someone please remind me. :memo:
