### ISSUE TITLE
Add "-bsf:a aac_adtstoasc" when merging letv mp4 parts

### ISSUE THREAD

**Issue by sodz** [soimort/you-get#813]
Proof of failure: `you-get --format 720p http://www.letv.com/ptv/vplay/20013073.html` (you-get: 0.4.192, ffmpeg: 2.8.3)

When merging letv video parts with ffmpeg in function `ffmpeg_concat_mp4_to_mp4` (processor/ffmpeg.py:171), option "aac_adtstoasc" is required to fix the "malformed AAC bitstream."

This works for me:
L171 `params += ['-c', 'copy', '-bsf:a', 'aac_adtstoasc', output]`

**Comment by cnbeining** [comment]
Sounds legible. 

I would suggest that you open an PR to add yourself to contributors.

**Comment by cnbeining** [comment]
I want to raise this problem to a higher level:

How do we know with ```ffmpeg``` or ```ffprobe``` that whether the stream is raw AAC or ADTS?

**Comment by nareix** [comment]
you-get 下载的视频大多数是 mp4,flv,ts 三种
只有 ts 是 adts 的，其他都不是

**Comment by cnbeining** [comment]
问题是如果不需要 加了这条 会有什么问题？

**Comment by nareix** [comment]
刚测了下没问题。看了 libavcodec/aac_adtstoasc_bsf.c 发现它只在有需要的时候转。

**Comment by redstoneleo** [comment]
乐视的那些 ts 片段，我不加 -bsf:a aac_adtstoasc 参数依然可以正常合并为MP4单文件，请你们也测试下看看这个参数是不是多余的

**Comment by cnbeining** [comment]
很多情况下不是。

为了安全 我们加上。

**Comment by redstoneleo** [comment]
能否提供一个不加 -bsf:a aac_adtstoasc 参数就不能合并的视频来我试试看？

**Comment by nareix** [comment]
低版本的 ffmpeg 需要 -bsf:a aac_adtstoasc 这个参数，高版本的不需要。
为了兼容加上最好。

2017-04-12 22:14 GMT+08:00 redstoneleo <notifications@github.com>:
