### ISSUE TITLE
已解决,重启下就好了：第一次使用，下载优酷视频一直卡在视频合并这里，you-get好用到感动的想哭

### ISSUE THREAD

**Issue by evolutionboy** [soimort/you-get#818]
最新更新，已经解决了，
本来别人下载好自动合并，我第一次用卡在合并那，后来手动合并感觉麻烦，重启，改下载目录权限为都可读写，就好了，不知道具体怎么好的。

，，，，，，，，，，，，，，，，，，，，，，，，，，，，，，
ubuntu15.10 amd64 +kde5.X笔记本版最新版， 
本人邮箱evolutionboy1@gmail.com全天在线。
evolution@evolution:~$ aptitude show ffmpeg
软件包： ffmpeg                  
状态: 已安装
自动安装: 否
Multi-Arch: foreign
版本号： 7:2.7.3-0ubuntu0.15.10.1
优先级： 可选
evolution@evolution:~$ aptitude show python3
软件包： python3                 
状态: 已安装
自动安装: 否
Multi-Arch: allowed
版本号： 3.4.3-4ubuntu1
优先级： 重要
部分： python
evolution@evolution:~$ aptitude show rtmpdump
软件包： rtmpdump                
状态: 已安装
自动安装: 是
版本号： 2.4+20150115.gita107cef-1build1
优先级： 额外
部分： universe/web
维护者： Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
体系： amd64
未压缩尺寸： 166 k

evolution@evolution:~$ sudo pip3 install you-get
[sudo] evolution 的密码： 
The directory '/home/evolution/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/evolution/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting you-get
  Downloading you_get-0.4.210-py3-none-any.whl (124kB)
    100% |████████████████████████████████| 126kB 245kB/s 
Installing collected packages: you-get
Successfully installed you-get-0.4.210
evolution@evolution:~$ you-get http://v.youku.com/v_show/id_XMTQxNjM0MDQ0NA==.html?f=286842&from=sub-y1.9-3.1
[1] 3501
evolution@evolution:~$ site:                优酷 (Youku)
title:               走错路的日本人 152
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          487.0 MiB (510702804 bytes)
    # download-with: you-get --format=hd2 [URL]

Downloading 走错路的日本人 152.flv ...
100.0% (487.0/487.0MB) ├███████████████████████████████████████████████████████████████████████████████████████┤[18/18]  535 kB/s
Merging video parts... ^C
（一直卡在这，按ctrl+C才中断。
[1]+  已停止               you-get http://v.youku.com/v_show/id_XMTQxNjM0MDQ0NA==.html?f=286842
evolution@evolution:~$ you-get -p firefox
Usage: you-get [OPTION]... [URL]...

**Comment by linhua55** [comment]
@evolutionboy  视频链接已经无效了
以前在刚开始要合并时也卡住过一回，重新运行就好了

**Comment by evolutionboy** [comment]
哦， 我试试。

**Comment by evolutionboy** [comment]
@linhua55 
刚试了，详情如下，还是卡在哪，另外默认合并后文件输出目录是家目录吗？现在看分段下载的是在家目录。
evolution@evolution:~$ you-get http://v.youku.com/v_show/id_XMTQxNjM0MDQ0NA==.html?f=286842&from=sub-y1.9-3.1
[2] 8871
evolution@evolution:~$ site:                优酷 (Youku)
title:               走错路的日本人 152
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          487.0 MiB (510702804 bytes)
    # download-with: you-get --format=hd2 [URL]

Downloading 走错路的日本人 152.flv ...
100.0% (487.0/487.0MB) ├███████████████████████████████████████████████████████████████████████████████████████┤[18/18]  150 MB/s
Merging video parts...

**Comment by linhua55** [comment]
经测试，合并没有问题。
运行一下这个命令
    ffmpeg  -version

**Comment by evolutionboy** [comment]
@linhua55 呵呵，谢谢已经好了，主题已更新，
本来别人下载好自动合并，我第一次用卡在合并那，后来手动合并感觉麻烦，重启，改下载目录权限为都可读写，就好了，不知道具体怎么好的。

**Comment by cnbeining** [comment]
请关闭此issue。
