### ISSUE TITLE
iqiyi下载出错

### ISSUE THREAD

**Issue by yangaowei** [soimort/you-get#820]
http://www.iqiyi.com/w_19rt6ksmsh.html

you-get: [error] outdated iQIYI key
you-get: is your you-get up-to-date?

**Comment by lzy0699** [comment]
自己先试试网页是否可以播放。。。

**Comment by yangaowei** [comment]
可以播放  @lzy0699

**Comment by yan12125** [comment]
The latest key is d7184ccc20a84a9d8be798087386b6b8. (http://www.iqiyi.com/common/flashplayer/20151217/MainPlayer_5_2_30_4_c3_3_8_2.swf)

**Comment by DARKTERRORTIW** [comment]
同样情况

**Comment by nuomi1** [comment]
@yangaowei @DARKTERRORTIW 更新 key 即可。

**Comment by danran-php** [comment]
@yan12125 大触怎么拿到key的，zombie.as 里面都是特殊字符

**Comment by yan12125** [comment]
Some resources:
The script I use: https://github.com/yan12125/iqiyi-hack (Linux only)
The idea: https://github.com/soimort/you-get/issues/692#issuecomment-147048333

**Comment by i0sdev** [comment]
@yangaowei  安装了下载iqiyi也是这个问题，在哪里更新key呢？

**Comment by yan12125** [comment]
See #822

**Comment by i0sdev** [comment]
iqiyi盐值多久会更新？万一再次失效后，用什么方法查到？
