### ISSUE TITLE
下载专辑，多语种选择

### ISSUE THREAD

**Issue by meergod** [soimort/you-get#821]
http://www.youku.com/show_page/id_z2ae8ee1c837b11e18195.html?from=y1.12-84
这是一个多语种专辑
默认下载的是英语版本
但是想下载国语版专辑。。。？？？

**Comment by jinjiachen** [comment]
试过you-get -i url没

**Comment by meergod** [comment]
@jinjiachen 
试过了，没用

**Comment by rosynirvana** [comment]
现在这个视频打开是 
语言 不可选
