### ISSUE TITLE
首页的图片不该是fork me吗?

### ISSUE THREAD

**Issue by iphyer** [soimort/you-get#826]
首页的图片不该是fork me吗?

![screenshot - 2015 12 22 - 23 24 16](https://cloud.githubusercontent.com/assets/1913891/11958527/5060c1e0-a903-11e5-941e-30605346e772.png)

fork 是主动动词,然后...不该是you fork 或者 fork me吗?

**Comment by soimort** [comment]
因为用 fork me 的话，图片就会变成受的一方啊。

![fork-me](https://cloud.githubusercontent.com/assets/342945/11966552/cb69bde4-a8fc-11e5-9e65-0509f124223f.jpg)

**Comment by nuomi1** [comment]
@soimort 瞬间觉得好污，不愧是全球最大同性交友网站（捂脸
