### ISSUE TITLE
-u 无法显示完整的列表，只显示了一部分

### ISSUE THREAD

**Issue by kashuorg** [soimort/you-get#834]
you-get在列出“视频列表”里的视频URL时，无法显示完整。
例如：
蜡笔小新第一部480集：http://www.youku.com/show_page/id_zcc008d1a962411de83b1.html
蜡笔小新第二部873集：http://www.youku.com/show_page/id_za7c275ecd7b411e1a19e.html
you-get -u http://www.youku.com/show_page/id_zcc008d1a962411de83b1.html
you-get -u http://www.youku.com/show_page/id_za7c275ecd7b411e1a19e.html
只显示了80个或100个，剩下的全部都没显示出来。

场景：
在873个视频当中，我不用全部下载，只想下载一部分（因为有的我之前已看过了），但如果直接用 you-get下载视频列表的话，它默认会从第1个开始下（肯定不行），而且you-get没有提供可供选择的列表出来，让用户选择需要下载哪些视频。

希望you-get能越来越完善，谢谢！

**Comment by kashuorg** [comment]
我之前一直用youtube-dl，但它有一个很大的问题：不会像you-get一样自动merge（合并）所下载的视频片段。

现在，我尝试了you-get，发现挺好用的。它会自动合并从U酷那下载下来的视频，最终得到一个完整的视频文件。

但是，像碰到这种需要下载“视频列表”里的视频时，这两个软件都显得有些不太方便了。
几百甚至上千个视频，我不需要全部下载的话，想下载其中的一部分（若有一个完整的列表显示出来，供用户选择哪几个需要下载，用户手工勾选上，就好），挺不方便的。

**Comment by yan12125** [comment]
youtube-dl有一個選項--playlist-items，可以選擇要下載哪些。

**Comment by yan12125** [comment]
不過youtube-dl不支援優酷的show_page

**Comment by linhua55** [comment]
只显示100个，是由于分页的问题导致的

在 2015年12月27日 下午4:08，kashu.org <notifications@github.com>写道：

**Comment by kashuorg** [comment]
@yan12125 
youtube-dl有这功能！ 但我现在使用的最新版的youtube-dl不支持U酷，我试了youtube.com里的就没问题
-g, --get-url                    Simulate, quiet but print URL
如：
不行：youtube-dl -g http://www.youku.com/show_page/id_zcc008d1a962411de83b1.html
   行：youtube-dl -g https://www.youtube.com/playlist?list=PLjyuVPBuorqIhlqZtoIvnAVQ3x18sNev4

而且选项还挺丰富：
 -e, --get-title                  Simulate, quiet but print title
    --get-id                         Simulate, quiet but print id
    --get-thumbnail                  Simulate, quiet but print thumbnail URL
    --get-description                Simulate, quiet but print video description
    --get-duration                   Simulate, quiet but print video length
    --get-filename                   Simulate, quiet but print output filename
    --get-format                     Simulate, quiet but print output format
    -j, --dump-json                  Simulate, quiet but print JSON information. See --output for a description of available keys.
    -J, --dump-single-json           Simulate, quiet but print JSON information for each command-line argument. If the URL refers to a playlist, dump the whole playlist
                                     information in a single line.
    --print-json                     Be quiet and print the video information as JSON (video is still being downloaded).

**Comment by kashuorg** [comment]
@linhua55 
那下载视频列表里的几百个文件时，会不会因为分页的原因，导致you-get只能下载到其中的一部分视频而已？

**Comment by soimort** [comment]
Unable to confirm, closing (before #838 gets fixed)
