### ISSUE TITLE
56视频下载

### ISSUE THREAD

**Issue by yangaowei** [soimort/you-get#837]
http://www.56.com/u50/v_MTM3NjU2MDYz.html

urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable

大家有遇到的吗

**Comment by nuomi1** [comment]
可解析无法下载。

**Comment by kwokts** [comment]
把解析出來的地址加上 &prod=56 後可以下載。

**Comment by soimort** [comment]
@kwokts :+1:
