### ISSUE TITLE
无法下载 U酷 视频

### ISSUE THREAD

**Issue by kashuorg** [soimort/you-get#838]
$ you-get http://v.youku.com/v_show/id_XNDQzNTIyMDQ0.html?from=y1.6-100.3.1.a7c275ecd7b411e1a19e

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

是不是软件需要更新了？

**Comment by Friday21** [comment]
我这也是诶

**Comment by linhua55** [comment]
还是cookie的问题，不知道请求哪个网页可以得到cookie
`play.youku.com` 不需要referer header了

**Comment by evolutionboy** [comment]
上午还用过一切OK，刚用就出前一样的错误信息，更新到最新一样错误，

**Comment by A-Circle-Zhang** [comment]
优酷这次有点作死，他自己分享出去的视频都不能手机播放了，问题比较严重。

**Comment by zhangn1985** [comment]
```
python3 ~/source/you-get/you-get  http://v.youku.com/v_show/id_XNDQzNTIyMDQ0.html?from=y1.6-100.3.1.a7c275ecd7b411e1a19e
site:                优酷 (Youku)
title:               第0641话 小葵比我更受欢迎
streams:
    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          14.4 MiB (15105109 bytes)
    # download-with: you-get --format=flvhd [URL]

Downloading 第0641话 小葵比我更受欢迎.flv ...
  5.2% (  0.8/14.4 MB) [===                                     ] 1/2
```
这个我的fork输出的结果，依然能下载。
和upstream的区别，在https://github.com/soimort/you-get/pull/783#discussion-diff-47060765 已经说了。

**Comment by linhua55** [comment]
@zhangn1985  @soimort 
好吧，又恢复成原来的了。不需要任何改动。
@A-Circle-Zhang 
看来优酷修复好了

**Comment by kashuorg** [comment]
@linhua55 
可以了，谢谢！

**Comment by soimort** [comment]
I don't think we need to fix anything for now, not even #839 and #841.

So I reverted back to 511d319.
