### ISSUE TITLE
优酷好多视频解析失败原因是版 权受限，希望增加一个版权受限的反馈信息，防止误以为BUG，影响调试。附使用环境，网址及视频年份，实时关注反馈

### ISSUE THREAD

**Issue by evolutionboy** [soimort/you-get#852]
具推测：优酷相当多的视频解决失败，原因 是版 权受限，但程序 无相关反馈，连09年的法证先锋第一部都 版 权受限。希望增加个版 权受限的反馈信息，方便排错。因在linux下，火狐和chrome浏览器禁了flash，网页上看不到版权限受限字样。
版本及使用环境：
ubuntu15.10 amd 64 +KDE5桌面
最新版you-get
evolution@evolution:/media/evolution/xin/mp4$ you-get -V
you-get: version 0.4.232, a tiny downloader that scrapes the web.
,,,,,,,,,,,,,,,,,,,,,,,,,
不能解析视频，
http://v.youku.com/v_show/id_XOTQzMzA5Mzc2.html?from=y1.6-97.3.1.f14b1596dd9911e49e2a
,,,,,,,,,,,,,,,2015年第一集播放地址，但是直接解析专辑地址可以解析出来真实播放列表及真实下载地址。如这个就可以解析
http://www.youku.com/show_page/id_zf14b1596dd9911e49e2a.html?from=y1.12-97
下面地址全为不能解析。原因是版权受限。
，，，，，，，，，，
http://v.youku.com/v_show/id_XNzIwODU5NDc2.html?from=y1.6-97.3.1.428adf4cda7911e38b3f
,,,,,,,,,,,,,,,,,,,,,,2014年。
http://v.youku.com/v_show/id_XMjI2NzU0NTYw.html?from=y1.2-2-97.3.1-1.1-3-1-0-0
，，，，，，，，，，，
http://v.youku.com/v_show/id_XMzExNjM0Mzk2.html?lang=%E5%9B%BD%E8%AF%AD&from=s1.8-1-1.1
法证先锋2011年，
,,,,,,,,,,,,,,,,,,,,
http://v.youku.com/v_show/id_XMjI2NzU0NTYw.html?from=y1.2-2.4.1

**Comment by linhua55** [comment]
就是bug，请不要频繁更改标题，标题也不要写的太长

**Comment by evolutionboy** [comment]
@linhua55 好的，请问自己怎么关闭Issues.

**Comment by cnbeining** [comment]
别改了。

![image](https://cloud.githubusercontent.com/assets/1560962/12108253/90d36792-b343-11e5-9a5a-61b069fd0c11.png)

你在这里有个close 点一下 然后千万别再回复 否则又开了。

**Comment by linhua55** [comment]
@evolutionboy 
只要在浏览器中可以观看的，而下载不了的，都算bug

**Comment by soimort** [comment]
Looking at this issue, I feel like

![bfa235ce71d507b274bde704bbf03cd3](https://cloud.githubusercontent.com/assets/342945/12155619/653b02d2-b4c6-11e5-84af-984e1d459122.jpg)

Too bad I had to close it.
