### ISSUE TITLE
Zhanqi.tv not working. 

### ISSUE THREAD

**Issue by 0834dfbd2b** [soimort/you-get#854]
The fix from #811 is not working anymore.

**Comment by cnbeining** [comment]
Somehow I cannot find out how the heck did the WsSecret is calculated. Anyone can give a hand?

**Comment by 0834dfbd2b** [comment]
Do you think the code is in the flashfile or the javascript?

**Comment by cnbeining** [comment]
I guess the related file is hiding somewhere in a file downloaded for the request by the Flash player. Any change Zhanqi is providing some HTML5 version we can look into?

**Comment by ERioK** [comment]
看了下android客户端代码，这个加密代码是在服务器上的，程序运行时从服务器下载一个so文件( http://dlstatic.cdn.zhanqi.tv/assets/appstatic/ad/libzqld.so)，调用里面的函数加密，用ida打开可以看到，不过这个东西随时都会被改

**Comment by cnbeining** [comment]
反编译乱七八糟。

ios没抓到：我改天用三层工具抓。

2016年1月6日星期三，ERioK <notifications@github.com> 写道：

**Comment by cnbeining** [comment]
@ERioK 我的私人邮箱 i [[at]] cnbeining.com 详细讨论一下？

这个issue可以关闭了么？
