### ISSUE TITLE
用java重写tudou.py中遇到的问题

### ISSUE THREAD

**Issue by gumplee** [soimort/you-get#856]
在common.py中执行url_size时response code 200.没有问题。

我单独提出来：
abc = "http://218.60.38.5/f4v/18/246755318.h264_1.0400020100568B295E53AE0E53DB1BB6D60AD9-376C-6BC3-302B-000383961947.f4v?key=6c75948fbc45933761c25c568b801500112a08b9e3&qrs=86392026&p=9548052764214222257&playtype=2&tk=142762909734490276050014773&brt=2&bc=0&xid=0400020100568B295E53AE0E53DB1BB6D60AD9-376C-6BC3-302B-000383961947&nt=0&nw=1&bs=0&ispid=12&rc=200&inf=12&si=un&npc=634&pp=0&ul=2&mt=0&sid=0&pc=0&cip=111.205.187.18&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=383961947&fi=0&sz=805210"

from urllib import request

response = request.urlopen(abc)
size = response.headers['content-length']
print(size)

然后我用java重写：

String url = "http://218.60.38.5/f4v/18/246755318.h264_1.0400020100568B295E53AE0E53DB1BB6D60AD9-376C-6BC3-302B-000383961947.f4v?key=6c75948fbc45933761c25c568b801500112a08b9e3&qrs=86392026&p=9548052764214222257&playtype=2&tk=142762909734490276050014773&brt=2&bc=0&xid=0400020100568B295E53AE0E53DB1BB6D60AD9-376C-6BC3-302B-000383961947&nt=0&nw=1&bs=0&ispid=12&rc=200&inf=12&si=un&npc=634&pp=0&ul=2&mt=0&sid=0&pc=0&cip=111.205.187.18&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=383961947&fi=0&sz=805210";
		
		HttpGet get = new HttpGet(url);
		CloseableHttpClient client = HttpClients.createDefault();
		try
		{
			CloseableHttpResponse response = client.execute(get);
			int code = response.getStatusLine().getStatusCode();
			System.out.println(code);
		}
		catch (ClientProtocolException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		catch (IOException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

响应code为403.

我看python request没有加一些header啊。有大神能告知python urllib requ和java httpclient在上面的区别么？

**Comment by linhua55** [comment]
也可能是cookie的问题
建议用wireshark抓包看看

**Comment by A-Circle-Zhang** [comment]
对 User-Agent 有要求。
下载时的 UA 必须和解析时的 UA 相同。

**Comment by gumplee** [comment]
@linhua55 直接在浏览器上访问这个url也是403错误。我看you-get源码这次视频下载的请求中request中的cookie 是 none，这应该没有用到Cookie吧。

**Comment by gumplee** [comment]
@A-Circle-Zhang 确定么？我每次请求设置的User-Agent都一样啊。

**Comment by A-Circle-Zhang** [comment]
@gumplee 对 UA 有要求，而且要求 不能为 PC 浏览器的 UA

**Comment by gumplee** [comment]
@A-Circle-Zhang 能解释详细一些吗？或者在you-get源码中体现在哪里，非常感谢！

**Comment by gumplee** [comment]
@A-Circle-Zhang 最后就设置了UA 为user-agent: python-urllib/3.4 可以了...
