### ISSUE TITLE
获取到的搜狐视频地址不能直接播放？

### ISSUE THREAD

**Issue by hugecheng** [soimort/you-get#860]
用you-get获取到的地址，例如：http://tv.sohu.com/20141119/n406192681.shtml 得到第一段地址http://222.173.50.130/sohu/s26h23eab6/v1/TmPGqAIOfOeHyewFWm8Oyp9ehAfRotAXgYAtWYAmMYXUyYbSoO2VqVw.mp4?k=6X6eGY&p=j9lvzSwCqSPGqmoA0p1BqmvWXZxIWhoVqTPcWJ6sZYy4fOoBoJ2svm1BqVPcNmsdytP&r=TmI20LscWOo70Sc2ZDASqt8IS3aalDlJmjLamr7XkOkj63wjUqdqwlFj3O3OkjTOmhZXAODOfoIWDW4vmXAyBj&q=OpC7hW7IWh6Soh24fY1XvmfCyY2sWhdHfhAO5Gyt5GbXwmbcWJbOfYvXWFdSqD24fDoUZDS&cip=118.192.76.48
第一次在浏览器打开，不能播放，刷新一下才可以播放。用you-get是可以下载的。

用you-get搭建了一个web service，android客户端从web service请求到的这个地址后在本地的播放器也播放不了，即使反复尝试播放也不行。

麻烦看下，这个是什么问题？谢谢！

**Comment by soimort** [comment]
需要 UA 一致。

**Comment by hugecheng** [comment]
关于搭建web-service发现一个问题，本地调试时解析sohu的视频地址http://127.0.0.1:5000/?url=http://tv.sohu.com/20141119/n406192681.shtml时得到的是这样的地址：http://sohu.u.00cdn.com/217/235/uBC6e3pkTNCNcy9h9709gX.mp4?key=psNSpQxuGZ7VqSvZiiVk6BX1VyPsuixW&n=1&a=1803&cip=183.37.227.154&uid=1452363054161&pt=1&vid=2108743&rb=1&prod=flash；这个地址在浏览器和本地播放器是可以直接播放的。

而在搭建的web service上，去解析同样的视频http://you-get-service.coding.io/?url=http://tv.sohu.com/20141119/n406192681.shtml 得到的却是http://222.187.0.35/sohu/s26h23eab6/v1/TmPGqAIOfOeHyewFWm8Oyp9ehAfRotAXgYAtWYAmMYXUyYbSoO2VqVw.mp4?k=t9mzop&p=j9lvzSwCqSPmqLPBopvComrWXZxIWhoVqTPcWJ6sZYy4fOoBoJ2svm1BqVPcNmsdytP&r=TmI20LscWOo70Sc2ZDASqt8IS3vt9vCOvDLjCJo0f3dJWDe9aIuD6Xvg6ncR5ZkpP39LrW49JLzSkAqEOyOHXIY&q=OpC7hW7IWh6Soh24fY1XvmfCyY2sWhdHfhAO5Gyt5GbXwmbcWJbOfYNsWYdSqD2tfOoUZDS&cip=118.192.76.48 ，这个地址在浏览器和本地播放器都不能直接播放。

这个还是跟UserAgent有关吗？如何在web service上也能得到类似http://sohu.u.00cdn.com/这样的地址？

麻烦帮忙看下，多谢了！

本地环境是win7 64位，http://you-get-service.coding.io/的环境是linux

**Comment by CoXier** [comment]
I met the same issue.

## Chrome and FireFox
 On firefox,I can play this video url directly,however on chrome I need to refresh

**Comment by yan12125** [comment]
兩者之間的差別是Chrome多了一個"Range: bytes=0-"的header，而sohu的server對這種request回傳403。理論上收到403應該要自動reload。從Chrome的devtools中可以看到有另外一個不包含Range header的request，但畫面卻沒有自動reload。看來是Chrome的問題，請向Google回報。

附帶一提，ffmpeg也有類似的bug [1]，需要額外的參數防止"Range: bytes=0-"產生 [2]
[1] https://github.com/rg3/youtube-dl/issues/11800#issuecomment-275037127
[2] http://trac.ffmpeg.org/ticket/6125#comment:10
