### ISSUE TITLE
土豆视频无法播放, 但是可以下载

### ISSUE THREAD

**Issue by sephrioth** [soimort/you-get#865]
下载和查看都没有问题, 但是一旦播放就报错,  求问如何解决.

you-get -p mpv http://www.tudou.com/programs/view/9OolTOJefuA
Site:       Tudou.com
Title:      点个赞科技2014老顾客回馈活动介绍
Type:       Flash video (video/x-flv)
Size:       51.69 MiB (54204679 Bytes)

Playing: http://114.80.236.206/f4v/7/218341407.h264_4_seg_0.0400150200549A7100D68C8C4AC35C81F28CB9-C00C-3655-EE3C-000272368785.f4v?key=78131bb1ddf3ce27a96ba656922d8000115d0f8975&qrs=3471593586&p=9597888316965624209&playtype=15&tk=147806941317149607680664644&brt=15&bc=0&xid=0400150200549A7100D68C8C4AC35C81F28CB9-C00C-3655-EE3C-000272368785&nt=0&nw=0&bs=0&ispid=23&rc=200&inf=12&si=un&npc=3341&pp=-1&ul=2&mt=0&sid=0&pc=0&cip=116.192.16.53&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=272368785&fi=0&sz=27299571
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://114.80.236.206/f4v/7/218341407.h264_4_seg_0.0400150200549A7100D68C8C4AC35C81F28CB9-C00C-3655-EE3C-000272368785.f4v?key=78131bb1ddf3ce27a96ba656922d8000115d0f8975&qrs=3471593586&p=9597888316965624209&playtype=15&tk=147806941317149607680664644&brt=15&bc=0&xid=0400150200549A7100D68C8C4AC35C81F28CB9-C00C-3655-EE3C-000272368785&nt=0&nw=0&bs=0&ispid=23&rc=200&inf=12&si=un&npc=3341&pp=-1&ul=2&mt=0&sid=0&pc=0&cip=116.192.16.53&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=272368785&fi=0&sz=27299571.

Playing: http://114.80.235.17/f4v/7/218341407.h264_4_seg_1.0400150201549A710090E1C6CB25A5C7659C78-EF69-500C-7142-000272368786.f4v?key=6b2f5ee0eddae7694dd99456922d8000115d0f8975&qrs=300634226&p=6780195079246761569&playtype=15&tk=73587641448316389120275903&brt=15&bc=0&xid=0400150201549A710090E1C6CB25A5C7659C78-EF69-500C-7142-000272368786&nt=0&nw=0&bs=0&ispid=23&rc=200&inf=12&si=un&npc=2234&pp=-1&ul=2&mt=0&sid=0&pc=0&cip=116.192.16.53&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=272368786&fi=0&sz=26905108
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://114.80.235.17/f4v/7/218341407.h264_4_seg_1.0400150201549A710090E1C6CB25A5C7659C78-EF69-500C-7142-000272368786.f4v?key=6b2f5ee0eddae7694dd99456922d8000115d0f8975&qrs=300634226&p=6780195079246761569&playtype=15&tk=73587641448316389120275903&brt=15&bc=0&xid=0400150201549A710090E1C6CB25A5C7659C78-EF69-500C-7142-000272368786&nt=0&nw=0&bs=0&ispid=23&rc=200&inf=12&si=un&npc=2234&pp=-1&ul=2&mt=0&sid=0&pc=0&cip=116.192.16.53&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=272368786&fi=0&sz=26905108.

Exiting... (Errors when loading file)

**Comment by nuomi1** [comment]
搭车，OS X 下无法拉起 VLC.app。
```
you-get -d -p vlc http://www.tudou.com/programs/view/9OolTOJefuA
Site:       Tudou.com
Title:      点个赞科技2014老顾客回馈活动介绍
Type:       Flash video (video/x-flv)
Size:       51.69 MiB (54204679 Bytes)

you-get: version 0.4.217, a tiny downloader that scrapes the web.
you-get: ['http://www.tudou.com/programs/view/9OolTOJefuA']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.217', 'console_scripts', 'you-get')()
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.217-py3.5.egg/you_get/__main__.py", line 92, in main
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.217-py3.5.egg/you_get/common.py", line 1229, in main
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.217-py3.5.egg/you_get/common.py", line 1150, in script_main
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.217-py3.5.egg/you_get/common.py", line 1003, in download_main
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.217-py3.5.egg/you_get/common.py", line 1222, in any_download
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.217-py3.5.egg/you_get/extractors/tudou.py", line 53, in tudou_download
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.217-py3.5.egg/you_get/extractors/tudou.py", line 23, in tudou_download_by_iid
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.217-py3.5.egg/you_get/common.py", line 660, in download_urls
  File "/usr/local/lib/python3.5/site-packages/you_get-0.4.217-py3.5.egg/you_get/common.py", line 191, in launch_player
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'vlc'  
```

**Comment by yan12125** [comment]
要有Referer header

**Comment by sephrioth** [comment]
小白求问怎么加...加哪里...

**Comment by yan12125** [comment]
眼下貌似無簡單解法，先拉下來再看唄。

也可以先安裝youtube-dl，再把我的PR https://github.com/mpv-player/mpv/pull/2703 抓下來自行compile一個mpv，如此就能用
```
mpv http://www.tudou.com/programs/view/9OolTOJefuA
```
直接播放。

**Comment by sephrioth** [comment]
不明觉厉, 我还是先下载了看把... 非常感谢.

**Comment by soimort** [comment]
@yan12125 Thanks!

<hr/>

> FileNotFoundError: [Errno 2] No such file or directory: 'vlc'  

@nuomi1 `vlc`在系统路径中么？

<hr/>

只是Referer的话还好，如果要求cookies的话基本无解。
所以这个`-p`的功能，也只能对某些网站（和某些播放器）适用而已。

**Comment by nuomi1** [comment]
@soimort VLC.app 在`/Applications/VLC.app`，在 Terminal 运行`/Applications/VLC.app/Contents/MacOS/VLC` 可以拉起 VLC，如果运行 `/Applications/VLC.app/Contents/MacOS/vlc` 则提示`core libvlc error: No plugins found! Check your VLC installation`。
