### ISSUE TITLE
利用you-get做web service获取sohu视频地址的问题

### ISSUE THREAD

**Issue by hugecheng** [soimort/you-get#866]
搭建web-service发现一个问题，本地调试时解析sohu的视频地址http://127.0.0.1:5000/?url=http://tv.sohu.com/20141119/n406192681.shtml时得到的是这样的地址：http://sohu.u.00cdn.com/217/235/uBC6e3pkTNCNcy9h9709gX.mp4?key=psNSpQxuGZ7VqSvZiiVk6BX1VyPsuixW&n=1&a=1803&cip=183.37.227.154&uid=1452363054161&pt=1&vid=2108743&rb=1&prod=flash；这个地址在浏览器和本地播放器是可以直接播放的。

而在搭建的web service上，去解析同样的视频http://you-get-service.coding.io/?url=http://tv.sohu.com/20141119/n406192681.shtml 得到的却是http://222.187.0.35/sohu/s26h23eab6/v1/TmPGqAIOfOeHyewFWm8Oyp9ehAfRotAXgYAtWYAmMYXUyYbSoO2VqVw.mp4?k=t9mzop&p=j9lvzSwCqSPmqLPBopvComrWXZxIWhoVqTPcWJ6sZYy4fOoBoJ2svm1BqVPcNmsdytP&r=TmI20LscWOo70Sc2ZDASqt8IS3vt9vCOvDLjCJo0f3dJWDe9aIuD6Xvg6ncR5ZkpP39LrW49JLzSkAqEOyOHXIY&q=OpC7hW7IWh6Soh24fY1XvmfCyY2sWhdHfhAO5Gyt5GbXwmbcWJbOfYNsWYdSqD2tfOoUZDS&cip=118.192.76.48 ，这个地址在浏览器和本地播放器都不能直接播放。

这个还是跟UserAgent有关吗？如何在web service上也能得到类似http://sohu.u.00cdn.com/这样的地址？

请帮忙看下，多谢了！

本地环境是win7 64位，http://you-get-service.coding.io/的环境是linux

**Comment by soimort** [comment]
抱歉，我没有能力解决你的问题。而且这问题和you-get本身的开发和维护无关，不适合放在这里讨论。

请移步别处，谢谢。
