### ISSUE TITLE
56网的地址http://www.56.com/w78/play_album-aid-14365735_vid-MTQwMDM1ODQy.html下载不了

### ISSUE THREAD

**Issue by zhaoff2015** [soimort/you-get#867]
http://www.56.com/u90/v_MTQwMDM2MDYz.html

http://www.56.com/w78/play_album-aid-14365735_vid-MTQwMDM1ODQy.html

这两个地址都下载不了

**Comment by kwokts** [comment]
解析頁面得出搜狐地址後可以下載
http://my.tv.sohu.com/us/221959899/82684512.shtml
http://my.tv.sohu.com/us/265186576/82683509.shtml

**Comment by zhaoff2015** [comment]
怎么解析？

**Comment by zhaoff2015** [comment]
已解决，谢谢

**Comment by cnbeining** [comment]
请关闭issue，写谢谢。

**Comment by soimort** [comment]
然而you-get并不支持这类URL。

所以请暂时不要关闭issue。
