### ISSUE TITLE
爱奇艺新key

### ISSUE THREAD

**Issue by xyuanmu** [soimort/you-get#870]
昨天更新的播放器，新key：6ab6d0280511493ba85594779759d4ed
<del>旧key还未失效：d7184ccc20a84a9d8be798087386b6b8</del>
测试地址：http://yuanmu.000webhost.cn/iqiyi/

**Comment by Nullizer** [comment]
今天旧 key 已经失效了
此 key 可用，已验证

**Comment by SmarmyWu** [comment]
如何更新iqiyi的key?

**Comment by xyuanmu** [comment]
@SmarmyWu 找到这个iqiyi.py替换即可：https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/iqiyi.py#L48

**Comment by SmarmyWu** [comment]
换成salt = '6ab6d0280511493ba85594779759d4ed'这个也没有效果

**Comment by Cappuccin0** [comment]
@SmarmyWu 我试了一下 更新key以后就没问题了

**Comment by yxjxx** [comment]
salt = '6ab6d0280511493ba85594779759d4ed'

好像有失效了？

**Comment by cnbeining** [comment]
Salt as 2016年03月25日01:53:34：

enc_key = 4a1caba4b4465345366f28da7c117d20

**Comment by yxjxx** [comment]
设置成 salt = '4a1caba4b4465345366f28da7c117d20' 就可以了。

那请问如何获取 iqiyi 最新的 key 呢？
