### ISSUE TITLE
Windows 64-bit error

### ISSUE THREAD

**Issue by jlsw** [soimort/you-get#874]
Hello, I have downloaded you-get from https://github.com/soimort/you-get/releases/download/v0.4.136/you-get-0.4.136-win32-full.7z ran you-get.bat and got an error http://i.imgur.com/EtErQ4s.png. I do not know why it does not work. Could you help me, please?

**Comment by hitechbeijing** [comment]
Please remove quotes.

**Comment by soimort** [comment]
Do I have to repeat this?
**Run the command with '--debug' option, and report this issue with the full output.**

![](http://i.imgur.com/EtErQ4s.png)
