### ISSUE TITLE
Unable to download some youtube clips

### ISSUE THREAD

**Issue by mouyigang** [soimort/you-get#881]
Successfully installed you-get-0.4.245
deploy@10-8-1-203:/data/tmp$ you-get https://www.youtube.com/watch?v=DE-LcDgv4Oc

site:                YouTube
title:               Llewelyn Ash {Adventures of a Glass Blower}
stream:
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          50.4 MiB (52880624 bytes)
    # download-with: you-get --itag=22 [URL]

Downloading Llewelyn Ash {Adventures of a Glass Blower}.mp4 ...
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

Another clip doesn't work, too: Sigur Rós - Dauðalogn	https://www.youtube.com/watch?v=grl1pbpoSuk

deploy@10-8-1-203:/data/tmp$ you-get --debug https://www.youtube.com/watch?v=grl1pbpoSuk
site:                YouTube
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=grl1pbpoSuk']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1237, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1158, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1006, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1230, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 50, in download_by_url
    self.download(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 186, in download
    self.p(stream_id)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 121, in p
    print("title:               %s" % self.title)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 28: ordinal not in range(128)

Maybe it's the naming issue of the clips?

$ uname -a
Linux 10-8-1-203 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ you-get --version
you-get: version 0.4.245, a tiny downloader that scrapes the web.
$ python3 --version
Python 3.4.0

**Comment by mouyigang** [comment]
I fixed this locally.
refer to:
http://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

I changed title:
self.title = self.title.encode('ascii', 'ignore').decode('ascii')
in "extractor.py" 122,

I also changed bar:
sys.stdout.write('\r' + bar.encode('ascii', 'ignore').decode('ascii'))
in "common.py"  571

**Comment by mouyigang** [comment]
I'm not a python programmer so the fix probably very naive, but if you want I can create a pull request for the fix.

**Comment by soimort** [comment]
You need to set your locale to UTF-8.
