### ISSUE TITLE
如何卸载？

### ISSUE THREAD

**Issue by kashu** [soimort/you-get#889]
Option 4: Download from GitHub

我是通过 make install 安装的，请问如何才能卸载掉（卸载干净）？
操作系统是Xubuntu 14.04

谢谢！

**Comment by nuomi1** [comment]
http://blog.sina.com.cn/s/blog_6c7214590101fn9f.html
https://www.zhihu.com/question/20092756

**Comment by kashu** [comment]
1. 安装时我直接是make && make install，没有指定 --prefix
2. 看网上的教程，sudo make uninstall 好像得要回到原软件的目录里，可当时安装完软件后，我就把软件目录删除了
3. 我下载了最新的you-get解压后，想看makefile文件，看不懂……
4. 手动删除，不知道删哪里

**Comment by soimort** [comment]
```
$ pip uninstall you-get
```
