### ISSUE TITLE
U酷视频无法下载

### ISSUE THREAD

**Issue by kashu** [soimort/you-get#890]
you-get版本：
you-get: version 0.4.245, a tiny downloader that scrapes the web.

U酷视频无法下载
kashu:/tmp/kvm$ you-get http://v.youku.com/v_show/id_XOTMxMDA5NzYw.html
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

$ you-get  --debug http://v.youku.com/v_show/id_XOTIwMjcxNjg0.html?f=23617928&from=y1.7-3
[1] 29219
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XOTIwMjcxNjg0.html?f=23617928']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "./src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "./src/you_get/common.py", line 1237, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "./src/you_get/common.py", line 1158, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "./src/you_get/common.py", line 1006, in download_main
    download(url, **kwargs)
  File "./src/you_get/common.py", line 1230, in any_download
    m.download(url, **kwargs)
  File "./src/you_get/extractor.py", line 39, in download_by_url
    self.prepare(**kwargs)
  File "./src/you_get/extractors/youku.py", line 192, in prepare
    audio_lang = data1['stream'][0]['audio_lang']
KeyError: 'stream'

[1]+  Exit 1          you-get --debug http://v.youku.com/v_show/id_XOTIwMjcxNjg0.html?f=23617928

YouTube视频没问题
$ you-get -x 127.0.0.1:8787 -i https://www.youtube.com/watch?v=Kr9_RveMst4
site:                YouTube
title:               Shen Rework: MAGICAL SWORD FOLLOWS YOU
streams:             # Available quality and codecs
    [ DASH ] ____________________________________
    - itag:          137
      container:     mp4
      quality:       1920x1080
      size:          150.7 MiB (158053628 bytes)
    # download-with: you-get --itag=137 [URL]

    - itag:          248
      container:     webm
      quality:       1920x1080
      size:          118.1 MiB (123873968 bytes)
    # download-with: you-get --itag=248 [URL]

    - itag:          136
      container:     mp4
      quality:       1280x720
      size:          91.6 MiB (96045782 bytes)
    # download-with: you-get --itag=136 [URL]

    - itag:          247
      container:     webm
      quality:       1280x720
      size:          66.4 MiB (69580492 bytes)
    # download-with: you-get --itag=247 [URL]

    - itag:          135
      container:     mp4
      quality:       854x480
      size:          55.0 MiB (57715900 bytes)
    # download-with: you-get --itag=135 [URL]

    - itag:          244
      container:     webm
      quality:       854x480
      size:          39.0 MiB (40933094 bytes)
    # download-with: you-get --itag=244 [URL]

    - itag:          133
      container:     mp4
      quality:       426x240
      size:          34.8 MiB (36451263 bytes)
    # download-with: you-get --itag=133 [URL]

    - itag:          134
      container:     mp4
      quality:       640x360
      size:          33.4 MiB (35051605 bytes)
    # download-with: you-get --itag=134 [URL]

    - itag:          243
      container:     webm
      quality:       640x360
      size:          28.0 MiB (29326112 bytes)
    # download-with: you-get --itag=243 [URL]

    - itag:          160
      container:     mp4
      quality:       256x144
      size:          22.1 MiB (23161347 bytes)
    # download-with: you-get --itag=160 [URL]

    - itag:          242
      container:     webm
      quality:       426x240
      size:          19.9 MiB (20814789 bytes)
    # download-with: you-get --itag=242 [URL]

    - itag:          278
      container:     webm
      quality:       256x144
      size:          18.0 MiB (18879344 bytes)
    # download-with: you-get --itag=278 [URL]

    [ DEFAULT ] _________________________________
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          114.8 MiB (120391975 bytes)
    # download-with: you-get --itag=22 [URL]

    - itag:          43
      container:     webm
      quality:       medium
    # download-with: you-get --itag=43 [URL]

    - itag:          18
      container:     mp4
      quality:       medium
    # download-with: you-get --itag=18 [URL]

    - itag:          5
      container:     flv
      quality:       small
    # download-with: you-get --itag=5 [URL]

    - itag:          36
      container:     3gp
      quality:       small
    # download-with: you-get --itag=36 [URL]

    - itag:          17
      container:     3gp
      quality:       small
    # download-with: you-get --itag=17 [URL]

**Comment by soimort** [comment]
> 该视频被设为仅粉丝观看，请关注上传者。

请带上cookies。

除此之外似乎并没有别的解决办法。
