### ISSUE TITLE
本机优酷解析

### ISSUE THREAD

**Issue by zouhua** [soimort/you-get#903]
[root@vagrant-centos65 you-get]# ./you-get -d 'http://v.youku.com/v_show/id_XMTQ1MjU4NDQ2MA==.html'
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://v.youku.com/v_show/id_XMTQ1MjU4NDQ2MA==.html']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "./src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "./src/you_get/common.py", line 1237, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "./src/you_get/common.py", line 1158, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "./src/you_get/common.py", line 1006, in download_main
    download(url, **kwargs)
  File "./src/you_get/common.py", line 1230, in any_download
    m.download(url, **kwargs)
  File "./src/you_get/extractor.py", line 50, in download_by_url
    self.download(**kwargs)
  File "./src/you_get/extractor.py", line 186, in download
    self.p(stream_id)
  File "./src/you_get/extractor.py", line 120, in p
    print("site:                %s" % self.__class__.name)

**Comment by zhangn1985** [comment]
python --version

**Comment by zouhua** [comment]
[root@vagrant-centos65 you-get]# python -V
Python 3.5.1

**Comment by soimort** [comment]
你的 Traceback 输出没贴全。

**Comment by zouhua** [comment]
![1](https://cloud.githubusercontent.com/assets/11640833/12573804/72af06f8-c438-11e5-9e9b-caa66b141dd5.png)

**Comment by zhangn1985** [comment]
@soimort 是时候引入i18n了，python-gettext?

**Comment by zhangn1985** [comment]
@zouhua 请执行一下：locate命令

**Comment by zouhua** [comment]
@zhangn1985 
[root@vagrant-centos65 you-get]# locate
bash: locate: command not found

**Comment by zhangn1985** [comment]
sorry, 写错了， 是： locale

确定一下你的机器的语言环境。

**Comment by zouhua** [comment]
[root@vagrant-centos65 iScript]# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=zh_CN.UTF-8
LC_CTYPE=zh_CN.UTF-8
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=
[root@vagrant-centos65 iScript]#

**Comment by zhangn1985** [comment]
cat /etc/default/locale

然后 locale-gen

重新生成locale

**Comment by zhangn1985** [comment]
cat /etc/default/locale 我的结果是：
LANG="zh_CN.UTF-8"
LANGUAGE="zh_CN:"

**Comment by zouhua** [comment]
bash: locale-gen: command not found

**Comment by soimort** [comment]
> bash: locale-gen: command not found

Let me google that for you.

http://unix.stackexchange.com/a/140303
