### ISSUE TITLE
outdated iQIYI key

### ISSUE THREAD

**Issue by e-securite** [soimort/you-get#905]
您好，我在使用you-get下载爱奇艺视频时遇到了这个问题
![image](https://cloud.githubusercontent.com/assets/10863240/12639094/01513e6c-c5dd-11e5-99ff-9c6c61d5bf46.png)
是不是因为爱奇艺调整了参数，导致软件无法下载呢？该如何解决这个问题呢？

**Comment by nuomi1** [comment]
pip 并不会同步 github latest，请手动检查 https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/iqiyi.py#L48 是否为最新。

**Comment by xyuanmu** [comment]
pip更新的好像是master分支的，最近更新的都在 develop 分支。

**Comment by soimort** [comment]
Fixed in #891.

暂时没有发布新版本，请使用 develop 分支。
