### ISSUE TITLE
[弱問]有關下載youtube字幕

### ISSUE THREAD

**Issue by xnastudio** [soimort/you-get#911]
youtube的字幕有2種,一種是自動生成的字幕,這種字幕不準確,幾乎每一句的都有錯字
另外一種是上傳者製作的字幕
現在我下載 mit open course的視頻,它會自動下載 自動生成的字幕
https://www.youtube.com/watch?v=moPtwq_cVH8
請問有什麼方法下載另外一種的準確字幕?
![screenshot from 2016-02-03 10 03 51](https://cloud.githubusercontent.com/assets/9460464/12770701/9765c1e6-ca5d-11e5-9978-97a7759f2144.png)

**Comment by soimort** [comment]
Fixed in 78801cc.
