### ISSUE TITLE
[YouTube] Unsupported URL pattern

### ISSUE THREAD

**Issue by VertigoRay** [soimort/you-get#912]
```cmd
(env) C:\Temp>you-get.exe -i --debug 'http://www.youtube.com/watch/cwhLueAWItA'
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ["'http://www.youtube.com/watch/cwhLueAWItA'"]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\Lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Python35-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Temp\env\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\temp\env\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\temp\env\lib\site-packages\you_get\common.py", line 1237, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\temp\env\lib\site-packages\you_get\common.py", line 1158, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\temp\env\lib\site-packages\you_get\common.py", line 1006, in download_main
    download(url, **kwargs)
  File "c:\temp\env\lib\site-packages\you_get\common.py", line 1229, in any_download
    m, url = url_to_module(url)
  File "c:\temp\env\lib\site-packages\you_get\common.py", line 1220, in url_to_module
    conn.request("HEAD", video_url)
  File "C:\Program Files (x86)\Python35-32\Lib\http\client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "C:\Program Files (x86)\Python35-32\Lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Program Files (x86)\Python35-32\Lib\http\client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "C:\Program Files (x86)\Python35-32\Lib\http\client.py", line 911, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Python35-32\Lib\http\client.py", line 854, in send
    self.connect()
  File "C:\Program Files (x86)\Python35-32\Lib\http\client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Program Files (x86)\Python35-32\Lib\socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Program Files (x86)\Python35-32\Lib\socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
```

I thought the second line of output showing the URL double quoting with single quotes inside was odd. I changed it from single to double and got this ...

```cmd
(env) C:\Temp>you-get.exe -i --debug "http://www.youtube.com/watch/cwhLueAWItA"
you-get: [Failed] Unsupported URL pattern.
```

Also tried no quotes ...

```cmd
(env) C:\Temp>you-get.exe -i --debug http://www.youtube.com/watch/cwhLueAWItA
you-get: [Failed] Unsupported URL pattern.
```

I guess I should also note that I'm in Win10 Pro, and this is a fresh virtualenv with Python 3.5.1 and nothing else installed in the virtualenv:

```cmd
C:\Temp>powershell.exe -c [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      10586  0

C:\Temp>"\Program Files (x86)\Python35-32\python.exe" --version
Python 3.5.1

C:\Temp>"\Program Files (x86)\Python35-32\python.exe" -m virtualenv env
Using base prefix 'C:\\Program Files (x86)\\Python35-32'
New python executable in C:\Temp\env\Scripts\python.exe
Installing setuptools, pip, wheel...done.

C:\Temp>env\Scripts\activate

(env) C:\Temp>pip install you-get
Collecting you-get
  Downloading you_get-0.4.245-py3-none-any.whl (126kB)
    100% |################################| 126kB 531kB/s
Installing collected packages: you-get
Successfully installed you-get-0.4.245

(env) C:\Temp>pip freeze
wheel==0.26.0
you-get==0.4.245
```

**Comment by VertigoRay** [comment]
It appears your demo URL does work:

```cmd
(env) C:\Temp>env\Scripts\you-get.exe -i --debug http://www.fsf.org/blogs/rms/20140407-geneva-tedx-talk-free-software-free-society
Site:       fsf.org
Title:      TEDxGE2014_Stallman05_LQ
Type:       WebM video (video/webm)
Size:       27.12 MiB (28435804 Bytes)
```

**Comment by VertigoRay** [comment]
I lied ... the video was in an iframe. I targetted the iframe source and that one's working:

```cmd
(env) C:\Temp>you-get-0.4.245-win32.exe --debug http://www.dailymotion.com/embed/video/x3gvu42?syndication=173592?info=0&logo=0&related=0&
Site:       Dailymotion.com
Title:      Televistazo 13h00 04-12-2015
Type:       MPEG-4 video (video/mp4)
Size:       159.5 MiB (167249952 Bytes)

Downloading Televistazo 13h00 04-12-2015.mp4 ...
  9.6% ( 15.2/159.5MB) ├████──────────────────────────────────┤[1/1]   68 kB/s
```

***Note:*** *I pulled the [latest release](https://github.com/soimort/you-get/releases/tag/v0.4.245) from GitHub and was testing to see if I got the same results. I did get the same results.*

**Comment by soimort** [comment]
1. `[Errno 11001] getaddrinfo failed` was not because of single or double quotes. It's because of an invisible Unicode character lying in the URL (which you might have copied somewhere from a web page without knowing it). When you edited quotes from single to double, those were deleted as well, so this kind of error should not occur anymore.
2. `[Failed] Unsupported URL pattern.` was because - this form of URL is not supported, for the time being. YouTube redirects it to `https://www.youtube.com/watch?v=cwhLueAWItA`,
3. If a general URL contains a video like http://www.ecuavisa.com/ajax-noticiero/nojs/123502/ampliado did not work, that's because our extractor is not perfect. Hopefully we'll get that improved sooner or later!

**Comment by VertigoRay** [comment]
1. I copied it from the address bar and typed it the single quotes manually. The issue is the command line passed the single quotes in as part of the argument because that's what CMD.exe does. Oh well.
1. This should be easy to resolve by simply re-writting YouTube URLs into a format you prefer as part of the YouTube extractor. While at it, should add support for the *share* URLS (ie: https://youtu.be/cwhLueAWItA).
  - Maybe I'll write a patch and post a merge request.
1. As stated, there technically wasn't a video on that page, it was inside of an `iframe` on that page. I targetted the `iframe src` and it worked great. The `iframe src` simply pointed to dailymotion, which you already support.

Thanks for all the great work on `you-get`. I [re-wrote my script in Python](/VertigoRay/Download-EcuaVisa/blob/master/download-ecuavista.py) and put it on my [Synology](https://www.synology.com/en-global/products/DS1511+) to auto-download the latest episodes and put them where [Plex](http://plex.tv) will find them, keeping only the latest episodes since it's just the news.

Cheers!! :beers:

**Comment by soimort** [comment]
> The issue is the command line passed the single quotes in as part of the argument because that's what CMD.exe does.

You're right; I didn't even notice that. But that's a thing on your own shell (having passed command arguments in a mistaken way), shouldn't have included it in an issue report of `you-get`. There are some shells which just don't care about single quotes:sweat_smile:.

> This should be easy to resolve by simply re-writting YouTube URLs into a format you prefer as part of the YouTube extractor.

We already support URLs like https://youtu.be/cwhLueAWItA, I guess. To be honest, I didn't even know patterns like http://www.youtube.com/watch/cwhLueAWItA should work until seeing this issue. And you're very welcome to propose a patch.

**Comment by VertigoRay** [comment]
> shouldn't have included it in an issue report of `you-get`

/agree ... I didn't think about it until after. :smile:

**Comment by soimort** [comment]
Thanks for the bug report, this should be fixed now.
