### ISSUE TITLE
Request: Fix Douyu.tv

### ISSUE THREAD

**Issue by cnbeining** [soimort/you-get#914]
We need to fix DounaiTV.
![itfm le gt 7 ru7 6 mrk](https://cloud.githubusercontent.com/assets/1560962/12799015/a2c71070-ca9a-11e5-97d0-2d791cd1b277.jpg)

Update：如果你有问题，请在此报告；否则3天后关闭issue。

**Comment by zhangn1985** [comment]
斗鱼怎么了？一周之前还可以用呀！

**Comment by cnbeining** [comment]
我怀疑换key 或者换算法了。

现在还加了个反反调试。

**Comment by yan12125** [comment]
Key沒換 我昨天用youtube-dl還能用

**Comment by cnbeining** [comment]
真是奇怪 这个问题偶尔我的确复现。

但是既然有很多不能复现 那就先hold住 等再有再来吧。

**Comment by kevinbakbak** [comment]
修复下吧，debug信息都没的，反馈都不能

**Comment by zhangn1985** [comment]
某些人斗鱼不能用？

**Comment by cnbeining** [comment]
看样这些人又没了。

先关了再说。。。

**Comment by kevinbakbak** [comment]
@zhangn1985 @cnbeining 不好意思。。。域名douyutv.com可以用的。douyu.com不能-.-

**Comment by zhangn1985** [comment]
https://github.com/soimort/you-get/blob/develop/src/you_get/common.py#L3
这一行的数组里面把douyu.com的信息加进去就好了。
