### ISSUE TITLE
不能下载ifeng.com 凤凰台视频

### ISSUE THREAD

**Issue by 668** [soimort/you-get#920]
例如 http://v.ifeng.com/ent/zongyi/201602/0163cf8f-7ba0-467e-be35-18e0f851f180.shtml，给出 
Site:       ifeng.com
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
Title:
求大大解决。

**Comment by soimort** [comment]
Please report the issue with full output.
```
$ you-get -di  http://v.ifeng.com/ent/zongyi/201602/0163cf8f-7ba0-467e-be35-18e0f851f180.shtml
Site:       ifeng.com
Title:      视觉秀《金猴闹春》
Type:       MPEG-4 video (video/mp4)
Size:       10.38 MiB (10884641 Bytes)
```
