### ISSUE TITLE
能支持迅雷下载地址么？（类似thunder://）

### ISSUE THREAD

**Issue by oshell** [soimort/you-get#929]
可以使用迅雷资源 电驴资源 种子 本地调用播放器播放么

**Comment by zhangn1985** [comment]
估计不行！

**Comment by soimort** [comment]
迅雷自己的协议并不开放。

真要支持的话还不如直接支持 ed2k 和 bittorrent……但是工作量太大。

**Comment by nuomi1** [comment]
@soimort 不是迅雷的私有协议。
`thunder://QUFodHRwOi8vMTcuZHVvdGUuY29tL2R1b3RldmI2LmV4ZVpa` 取 `QUFodHRwOi8vMTcuZHVvdGUuY29tL2R1b3RldmI2LmV4ZVpa` 经 debase64 得 `AAhttp://17.duote.com/duotevb6.exeZZ`，其实就是 HTTP / FTP 在最前加两个 `A` 和最后加两个 `Z` 而已。

**Comment by soimort** [comment]
> @soimort 不是迅雷的私有协议。
thunder://QUFodHRwOi8vMTcuZHVvdGUuY29tL2R1b3RldmI2LmV4ZVpa 取 QUFodHRwOi8vMTcuZHVvdGUuY29tL2R1b3RldmI2LmV4ZVpa 经 debase64 得 AAhttp://17.duote.com/duotevb6.exeZZ，其实就是 HTTP / FTP 在最前加两个 A 和最后加两个 Z 而已。

这种只对少数有 HTTP/FTP 资源才有效吧。
显然迅雷上的大部分链接是 P2P，不可能简简单单地通过这种形式下载。

**Comment by cnbeining** [comment]
如果是FTP/HTTP 无意义；

如果是BT，工作量过大且无意义；

如果是专有协议，我们不知道怎么办。

所以，让专业的软件做专业的事情吧。```aria2```就很好。

**Comment by cnbeining** [comment]
我们需要解决2个问题：

- 怎么把这东西丢到extractor

- 有没有BT的专用链？

**Comment by soimort** [comment]
补充：

**(1)** `thunder://`格式的URI确实都可以转化成`http://`或`ftp://`的地址（表面上）。

但是，这个FTP资源可能会是迅雷专用地址，无法使用通常的ftp client下载。举个栗子，某解析出来的地址：

    ftp://ds:ds@d3.dytt.com:10206/[迅雷下载www.xiamp4.com]石膏BOYS[第01话].mkv

对于这些链接，（我揣测）迅雷走的是P2SP，也就是先访问它的索引server，找到真实可用的IP。换句话说，这个URL仅仅起到了一个“资源标识符”的作用，本身也许未必能直接用于下载。

所以说这个东西，不逆向官方客户端恐怕是没法搞的，因为我们不知道它和迅雷服务器之间的协议。

（——关于迅雷，我了解的就这么多。）

**(2)** BT似乎没有专用链这一说，最多是种子文件的URL或磁力链接。

这类协议的支持对我来说意义不大，首先，已经有了`aria2`；其次，我自己也用不上。
