### ISSUE TITLE
Could we add support of Weibo video urls like this: http://weibo.com/p/230444a29a337fd78ce1a2b0c2f3063d150cec

### ISSUE THREAD

**Issue by GQHero** [soimort/you-get#930]
It seems like you-get cannot support domain, like 'weibo.com'.

**Comment by cnbeining** [comment]
Will see.

**Comment by GQHero** [comment]
I dig into it a little, the url above can be redirected by "http://video.weibo.com/show?fid=1034:a29a337fd78ce1a2b0c2f3063d150cec".

"fid=1034:a29a337fd78ce1a2b0c2f3063d150cec" could be found in the source page.

**Comment by cnbeining** [comment]
Link like "http://video.weibo.com/show?fid=1034:a29a337fd78ce1a2b0c2f3063d150cec" is supported.

But I am looking for some other ways to support the URL you provided.

**Comment by GQHero** [comment]
Yes, I know. I am also looking for the transforming ways...

**Comment by zhangn1985** [comment]
请参考：https://github.com/zhangn1985/you-get/blob/master/src/you_get/extractors/weibo.py

但是里面Cookies的实现是错的，将就能用。

**Comment by cnbeining** [comment]
我认为这个办法太没品了 就给官方发邮件问了。

看回复吧。

Beining

**Comment by GQHero** [comment]
@zhangn1985 你的那个也下载不了这个视频……

**Comment by zhangn1985** [comment]
因为那个是个m3u8链接，不能下载真正的视频，除非再解析m3u8.

**Comment by cnbeining** [comment]
算了，只能用最没品的办法了。

我觉得我们达不到这个数字吧。

> > 您好，实现微博视频分享需要申请 linkcard解析。 
linkcard接入条件：移动类型应用，接入平台新版sdk，应用授权人数10000以上，dau3000以上。请知晓。

>----- 原始邮件 -----
发件人：Bei Ning <cnbeining******>
收件人：weibo_api_tech     sina.com.cn
主题：请问如何处理微博视频的播放？
日期：2016年02月23日 13点01分

> 您好：
> 我在开发中遇到了这种地址：
> http://weibo.com/p/230444a29a337fd78ce1a2b0c2f3063d150cec
> 我想提取其中的视频播放器
> 并进行播放。但是我不知道不使用浏览器的方式如何操作，而且我想尽可能通过官方的API完成。
请问如何进行？
感谢！
Beining

**Comment by GQHero** [comment]
没关系，退而求其次啊，我搞不定了，等官方fix哈~~~~

**Comment by cnbeining** [comment]
load cookie 登陆 解析页面出fid 拼出播放页 调用现有解析器好了。

我睡觉了先。。。

**Comment by zhangn1985** [comment]
需要带上cookies才能拿到正确的html，搜索可以拿到m3u8，这样能直接播放，进一步解析m3u8可以得到真正的视频地址。
我那份代码的cookies也许过期了。昨晚还能用。

**Comment by cnbeining** [comment]
要么解析M3U 或者 秒拍的解析我已经写过了 用就是 这样维护方便点？

**Comment by GQHero** [comment]
正常访客打开这个页面从网页源码可以拼出video.weibo.com形式的网址，这个格式目前是支持的。
我觉得这个更易维护，只是这个页面跳转渲染逻辑我没搞定……

**Comment by cnbeining** [comment]
I know the right way is to do a login and get the ```oid```.

But I do not like that: instead I may use some dirty hacks for that...

**Comment by A-Circle-Zhang** [comment]
如果你们只是想解析，很简单的。注意加粗部分：
http://weibo.com/p/230444**a29a337fd78ce1a2b0c2f3063d150cec**
http://video.weibo.com/show?fid=1034:**a29a337fd78ce1a2b0c2f3063d150cec**
其中 230444 是个定值。

**Comment by cnbeining** [comment]
是啊 昨晚观察到了。

啥时候我写一个 或者谁写个我merge吧。。

**Comment by soimort** [comment]
Every time I try to open a weibo.com address, I'm redirected to http://weibo.com/login.php. That's another part I don't like about Weibo, because obviously I don't have a login.

Patches (w/o extra cookies) are welcome.
