### ISSUE TITLE
这个爱奇艺地址解析异常，是为啥呢 ？

### ISSUE THREAD

**Issue by jackey99** [soimort/you-get#931]
>you-get http://www.iqiyi.com/v_19rrn6itu4.html#vfrm=2-3-0-1
site:                爱奇艺 (Iqiyi)
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by cnbeining** [comment]
能不能用debug敲点日志出来呢？谢谢。

2016年2月23日星期二，jackey99 <notifications@github.com> 写道：

**Comment by nuomi1** [comment]
```
you-get: version 0.4.293, a tiny downloader that scrapes the web.
```
```
you-get -i http://www.iqiyi.com/v_19rrn6itu4.html               
site:                爱奇艺 (Iqiyi)
title:               晓松奇谈之两岸秘史（一）​北平无战事​
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        fullhd
      container:     f4v
      video-profile: 全高清
      size:          763.5 MiB (800589066 bytes)
    # download-with: you-get --format=fullhd [URL]

    - format:        suprt-high
      container:     f4v
      video-profile: 超高清
      size:          383.6 MiB (402252241 bytes)
    # download-with: you-get --format=suprt-high [URL]

    - format:        high
      container:     f4v
      video-profile: 高清
      size:          211.5 MiB (221787211 bytes)
    # download-with: you-get --format=high [URL]

    - format:        standard
      container:     f4v
      video-profile: 标清
      size:          112.5 MiB (117948146 bytes)
    # download-with: you-get --format=standard [URL]

    - format:        topspeed
      container:     f4v
      video-profile: 最差
      size:          58.6 MiB (61397414 bytes)
    # download-with: you-get --format=topspeed [URL]
```
没事啊？

**Comment by jackey99** [comment]
奇怪，我这里就是不行
>you-get -i http://www.iqiyi.com/v_19rrn6itu4.html
site:                爱奇艺 (Iqiyi)
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

其他集都可以



jack
 
发件人： nuomi1
发送时间： 2016-02-24 11:06
收件人： soimort/you-get
抄送： jackey99
主题： Re: [you-get] 这个爱奇艺地址解析异常，是为啥呢 ？ (#931)
you-get: version 0.4.293, a tiny downloader that scrapes the web.
you-get -i http://www.iqiyi.com/v_19rrn6itu4.html               
site:                爱奇艺 (Iqiyi)
title:               晓松奇谈之两岸秘史（一）​北平无战事​
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        fullhd
      container:     f4v
      video-profile: 全高清
      size:          763.5 MiB (800589066 bytes)
    # download-with: you-get --format=fullhd [URL]
    - format:        suprt-high
      container:     f4v
      video-profile: 超高清
      size:          383.6 MiB (402252241 bytes)
    # download-with: you-get --format=suprt-high [URL]
    - format:        high
      container:     f4v
      video-profile: 高清
      size:          211.5 MiB (221787211 bytes)
    # download-with: you-get --format=high [URL]
    - format:        standard
      container:     f4v
      video-profile: 标清
      size:          112.5 MiB (117948146 bytes)
    # download-with: you-get --format=standard [URL]
    - format:        topspeed
      container:     f4v
      video-profile: 最差
      size:          58.6 MiB (61397414 bytes)
    # download-with: you-get --format=topspeed [URL]

没事啊？

**Comment by qingsword** [comment]
同样的问题，任何视频都是这个错误
$ python3 you-get -i 'http://www.bilibili.com/video/av3905480/'
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

系统是ubuntu14.04

**Comment by cnbeining** [comment]
请多打一些log，用debug，谢谢，让我们复现一下。。。

**Comment by qingsword** [comment]
$ python3 you-get --debug 'http://www.bilibili.com/video/av3905480/'
you-get: version 0.4.293, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av3905480/']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "src/you_get/common.py", line 1250, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "src/you_get/common.py", line 1171, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "src/you_get/common.py", line 1019, in download_main
    download(url, **kwargs)
  File "src/you_get/common.py", line 1242, in any_download
    m, url = url_to_module(url)
  File "src/you_get/common.py", line 1229, in url_to_module
    return import_module('.'.join(['you_get', 'extractors', SITES[k]])), url
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "src/you_get/extractors/__init__.py", line 3, in <module>
    from .acfun import *
  File "src/you_get/extractors/acfun.py", line 11, in <module>
    from .youku import youku_download_by_vid
  File "src/you_get/extractors/youku.py", line 8, in <module>
    import ssl
  File "/usr/local/lib/python3.4/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named '_ssl'

**Comment by cnbeining** [comment]
@qingsword 你Python的安装姿势不对。

https://stackoverflow.com/questions/15901357/python3-3-1-ssl-module

https://stackoverflow.com/questions/6171210/building-python-and-more-on-missing-modules

重新弄一个吧，编译的时候带上，或者apt-get个。

**Comment by qingsword** [comment]
@cnbeining 原来如此...感谢！~\(≧▽≦)/~

**Comment by jackey99** [comment]
@cnbeining 我用的是window版本，请问如何解决 ？

就是这种    you-get-0.4.306-win32-full

**Comment by freyach** [comment]
@jackey99 解决了吗。我也是一样的问题。

**Comment by freyach** [comment]
@cnbeining python不是正常安装吗。检查python有版本号不就可以了吗
