### ISSUE TITLE
长短参数同时输入无效

### ISSUE THREAD

**Issue by nuomi1** [soimort/you-get#943]
`you-get: version 0.4.306, a tiny downloader that scrapes the web.`

`you-get --no-caption -n http://www.bilibili.com/video/av3988866/` fail
`you-get -n --no-caption http://www.bilibili.com/video/av3988866/` fail
`you-get --no-caption --no-merge http://www.bilibili.com/video/av3988866/` succeed

长短参数同时输入时，`-n` 无效，分段视频会合并。

**Comment by soimort** [comment]
感谢提醒，已在最新`develop`分支中修复。
