### ISSUE TITLE
今天又遇到了同样的报错，上次可能没说清楚，我用的是Windows版本

### ISSUE THREAD

**Issue by jackey99** [soimort/you-get#949]
>you-get -d http://www.iqiyi.com/v_19rrkviljg.html#vfrm=2-3-0-1
site:                爱奇艺 (Iqiyi)
you-get: version 0.4.306, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrkviljg.html#vfrm=2-3-0-1']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1250, in main
  File "src\you_get\common.py", line 1171, in script_main
  File "src\you_get\common.py", line 1019, in download_main
  File "src\you_get\common.py", line 1243, in any_download
  File "src\you_get\extractor.py", line 50, in download_by_url
  File "src\you_get\extractor.py", line 186, in download
  File "src\you_get\extractor.py", line 121, in p
UnicodeEncodeError: 'gbk' codec can't encode character '\u200b' in position 37: illegal multibyte sequence
you-get returned -1

**Comment by jackey99** [comment]
从报错信息里面看是不是编码的问题 ？

**Comment by soimort** [comment]
见 https://github.com/soimort/you-get/wiki/FAQ

**Comment by jackey99** [comment]
看了，没看明白，望指教啊发自网易邮箱大师
            在2016年03月04日 23:33，Mort Yao 写道:见 https://github.com/soimort/you-get/wiki/FAQ

**Comment by soimort** [comment]
```
chcp 65001
```

**Comment by jackey99** [comment]
@soimort 请教，这个是在后面加参数还是怎么搞 ？小白，搞不懂

**Comment by jackey99** [comment]
Change your Windows code page to UTF-8, using chcp 65001.

这个不知道在哪里改

**Comment by cnbeining** [comment]
https://github.com/soimort/you-get/wiki/FAQ

连图都上了。

**Comment by jackey99** [comment]
这么简单个问题就是没有人明说，哎，装的有点狠，给跟我一样的小白看看吧

http://my.oschina.net/renwofei423/blog/112450

**Comment by soimort** [comment]
需要明说的话，命令行下依次敲击：
<kbd>c</kbd><kbd>h</kbd><kbd>c</kbd><kbd>p</kbd><kbd>Space</kbd><kbd>6</kbd><kbd>5</kbd><kbd>0</kbd><kbd>0</kbd><kbd>1</kbd><kbd>Enter</kbd>

`you-get`本身就是一个命令行下的程序，所以……完整的命令都已经贴出来给你了。

提问前多看FAQ，自己照着说明敲两下键盘就能试出来的事情，没有必要什么都等别人来告诉你你才会做。

**Comment by jackey99** [comment]
@soimort  多谢，现在已经明白了，就是执行了这个命令后中文字符就重叠在一起了

**Comment by soimort** [comment]
@jackey99 `cmd.exe`的字体应该可以在属性里调整。

---

按理说这是个中文标题的视频，不应出现`'gbk' codec can't encode character`……暂时原因不明。
