### ISSUE TITLE
[Feature Request] HTTP Live Streaming

### ISSUE THREAD

**Issue by soimort** [soimort/you-get#95]
FOSDEM '13 will be streaming talks live this year!

All I need is a simple feature that automatically handles `.m3u` files and starts recording streams...
https://fosdem.org/2013/news/2013-01-31-streaming/

**Comment by cnbeining** [comment]
Refer to:

https://github.com/K-S-V/Scripts/blob/master/AdobeHDS.php

**Comment by cnbeining** [comment]
Closed via #1237 after 3.5 yrs.
