### ISSUE TITLE
64位wind10系统，怎么窗体一闪 而过？

### ISSUE THREAD

**Issue by wang991** [soimort/you-get#951]
64位wind10系统，打开到you-get时怎么窗体一闪 而过？

**Comment by soimort** [comment]
因为是命令行程序。

请在终端下运行。

**Comment by wang991** [comment]
我是小白。大神，怎么样在终端下运行呀？

**Comment by soimort** [comment]
![963105b2-a30a-11e5-9a02-e2ca3cadaa94](https://cloud.githubusercontent.com/assets/342945/13547471/a76448ee-e2d4-11e5-93bd-7195a3b6922b.png)

**Comment by linhua55** [comment]
@soimort 
哈哈哈
这个怎么样？  https://github.com/chriskiehl/Gooey

**Comment by soimort** [comment]
@linhua55 用这个的话，参数解析模块得用 argparse 改写…

**Comment by wang991** [comment]
非常感谢各位！问题终于得到解决了

**Comment by wang991** [comment]
墙内的下载没问题了，墙外的怎么下载？我用ss翻墙，要设置成全局代理？

**Comment by soimort** [comment]
方法1. 最简单的，设成全局代理。
方法2. https://github.com/soimort/you-get/wiki/%E4%B8%AD%E6%96%87%E8%AF%B4%E6%98%8E#proxy-settings
方法3. 用 [proxychains](https://github.com/rofl0r/proxychains-ng)。

**Comment by linhua55** [comment]
proxyfier

Mort Yao <notifications@github.com>于2016年3月5日周六 下午10:31写道：
