### ISSUE TITLE
不能下载iqiyi电视剧的1080P

### ISSUE THREAD

**Issue by shanmm** [soimort/you-get#962]
希望可以支持爱奇艺的1080P电视剧，有些不能直接播放的視頻无法下载，必須是會員才能播放电视剧

**Comment by cnbeining** [comment]
我知道有算法。

但是我还不知道具体是怎么办的。。。

**Comment by yan12125** [comment]
youtube-dl支援愛奇藝的登錄( https://github.com/rg3/youtube-dl/issues/8569 )，可以試試？

iQiyi的VIP影片解析方法和一般影片略有不同，而登入使用了非常噁心的Javascript obfuscation，詳見https://github.com/rg3/youtube-dl/commit/8e0548e180ee960eff6325b65e6cb2b91ee4d336 與 https://github.com/rg3/youtube-dl/commit/99709cc3f121010421360ba94d75e16ce15f0be5

**Comment by shanmm** [comment]
看了下這三個，但是不知道如何使用，youtube-dl我也在用的，是只需要用命令登錄后，youtube=dl就能解析下载爱奇艺的1080P嗎

**Comment by shanmm** [comment]
@cnbeining謝謝，算法我也一直求的，只可惜没人愿意给的，毕竟這可能就是別人的看家本领，算法要利用PHP和服務器的，具体怎么弄的我也没试过，坐等大神讲解，哈哈

**Comment by cnbeining** [comment]
我觉得他就是用PHP把```youtube-dl```的iQiyi重写了下。

他还是要cookie的，并不是接口有了什么漏洞。

**Comment by shanmm** [comment]
嗯，应该是的，不過youtibe-dl只能下载720的，而且you-get也是，现在大部分基本都是只能下载爱奇艺的720P，现在才觉得mp4ba的站长是有多厉害了

**Comment by nuomi1** [comment]
@shanmm 大部分只能 720p，可否给个例子？
另外 mp4ba 全是高码二压，720p 和1080p 同码，各种坑，不知道哪里厉害啊……

**Comment by shanmm** [comment]
@nuomi1硕鼠最高720P，youtube-dl下载優酷，土豆也是只有720P的，這是我遇到的，可能也和我沒有掌握youtibe-dl和you-get的用法吧，對了你不说我还被騙了，我就說mp4ba的720和1080P的大小怎么都差不多，感觉怪怪的，原来是720P压制成1080P的啊，不過他盗資源还是挺厉害的

**Comment by nuomi1** [comment]
@shanmm 测试「女医明妃传 第 1 集」

http://v.youku.com/v_show/id_XMTQ3MDg4Mjk4MA==.html
http://www.tudou.com/albumplay/RTND2CmJE0c/pu_Z6TTp3u8.html

you-get，国内可解析 1080p，美国不能播放。
flvcd，国内可解析超清。

---

http://www.iqiyi.com/v_19rrlayj6w.html

you-get，国内可解析 1080p（fullhd，全高清），美国可解析（suprt-high，超高清）。
flvcd，禁止解析。

---

@soimort 话说「suprt-high」真没拼错么？

**Comment by soimort** [comment]
> @soimort 话说「suprt-high」真没拼错么？

我也不知道……
 @zhangn1985

**Comment by zhangn1985** [comment]
f2b9bed34652812d570486266fe7b9681cc0f1e4
这个提交的里面的注释就是这么写的，但只要bid是正确的就可以啦。。

**Comment by shanmm** [comment]
@nuomi1嗯，謝謝you-get确实是可以解析部分1080P的，這個我也就满足啦，哈哈😄希望you-get和youtube-dl这2个老大支持的越来越多，嘿嘿

**Comment by hobmgcode** [comment]
iqiyi下载的f4v文件 格式有点不错 希望可以下载后转成MP4

**Comment by nuomi1** [comment]
@hobmgcode Unix-like 在安装 ffmpeg 后，会自动调用并输出合并后的 mp4，除非 `-n | --no-merge` 禁止合并。
Windows 不清楚。

**Comment by bGN4** [comment]
Windows 下格式工厂自带ffmpeg，或者调用硕鼠的合并应该也可以。

**Comment by cnbeining** [comment]
我们不能调用硕鼠的合并；

除非格式工厂等将```ffmpeg```加入```PATH```, 否则我们不能调用。

**Comment by soimort** [comment]
对于 Windows 用户：

1. [you-get 的 Windows 打包版本（7z）](https://github.com/soimort/you-get/releases/tag/v0.4.365) 已经自带了 FFmpeg（虽然有点过时），无需自己设置路径。
2. 请从这里下载 FFmpeg 的最新版本：https://ffmpeg.zeranoe.com/builds/ 。
3. 可以直接调用 `you-get.processor.ffmpeg` 的 `ffmpeg_concat_flv_to_mp4()`……前提是会写脚本的话。
4. 没有必要使用第三方基于 ffmpeg 开发而不遵循它协议的（闭源）转换工具。

**Comment by Token713** [comment]
@soimort 能否教下windows下youtube-dl调用ffmpeg合并？谢谢了

**Comment by nuomi1** [comment]
@Token713 https://github.com/rg3/youtube-dl/blob/master/youtube_dl/postprocessor/ffmpeg.py
youtube-dl only supports merging videos with bestvideo(e.g. DASH).

**Comment by rosynirvana** [comment]
outdated
