### ISSUE TITLE
PPTV http://v.pptv.com/show/IxD8euJIuPZZ1z8.html  无法下载 403错误  KEY 问题么

### ISSUE THREAD

**Issue by tdd00000** [soimort/you-get#968]
C:\Users\Administrator>you-get --debug http://v.pptv.com/show/IxD8euJIuPZZ1z8.ht
ml
Site:       PPTV.com
Title:      女医明妃传(第01集)
Type:       MPEG-4 video (video/mp4)
Size:       165.09 MiB (173112533 Bytes)

Downloading 女医明妃传(第01集).mp4 ...
 0.0% (  0.0/165.1MB) ├────────────────────────────
─────────────┤[1/9] Site:       PPTV.com
Title:      女医明妃传(第01集)
Type:       MPEG-4 video (video/mp4)
Size:       165.09 MiB (173112533 Bytes)

Downloading 女医明妃传(第01集).mp4 ...
 0.0% (  0.0/165.1MB) ├────────────────────────────
─────────────┤[1/9] Site:       PPTV.com
Title:      女医明妃传(第01集)
Type:       MPEG-4 video (video/mp4)
Size:       165.09 MiB (173112533 Bytes)

Downloading 女医明妃传(第01集).mp4 ...
 0.0% (  0.0/165.1MB) ├────────────────────────────
─────────────┤[1/9] Site:       PPTV.com
Title:      女医明妃传(第01集)
Type:       MPEG-4 video (video/mp4)
Size:       165.09 MiB (173112533 Bytes)

Downloading 女医明妃传(第01集).mp4 ...
 0.0% (  0.0/165.1MB) ├────────────────────────────
[在这里粘贴完整日志]
```

**Comment by soimort** [comment]
> - [ ] 您的问题没有在https://github.com/soimort/you-get/issues , https://github.com/soimort/you-get/wiki/FAQ 或 https://github.com/soimort/you-get/wiki/Known-Bugs 报告，否则请在原有issue下报告.

Duplicate of #447.
