### ISSUE TITLE
le.py 怎么解析vip

### ISSUE THREAD

**Issue by shiwq** [soimort/you-get#969]

**Comment by soimort** [comment]
并不能。

**Comment by cnbeining** [comment]
想免费蹭吃蹭喝的还是算了吧。。。

如果挂cookie不能 就是不能。

**Comment by shiwq** [comment]
。。。。

**Comment by soimort** [comment]
补充两句。

1. 我们不知道会员登录后的页面是什么样子的，解析视频的方式是否有所改变；因为开发者都没有VIP帐号，也不可能为了做这个专门去花钱购买；
2. 想绕过帐号而使用 `you-get` 下载付费视频是不可能的（单纯从法律意义上而言）。
3. 如果你针对的是 `le.py` 的具体代码实现，**请把问题描述清楚**，不要空着正文内容不写，也不要只打句号。
4. 有能力又有帐号用来测试的（比如自己经常看乐视），欢迎pull request。
