### ISSUE TITLE
[Admin] Announcing the accomplishment of translation of Chinese Wiki

### ISSUE THREAD

**Issue by cnbeining** [soimort/you-get#979]
Hi all,

I've finished the job. Feel free to use it under the original license.

Beining

@soimort Please kindly close this issue after you've read it.

**Comment by soimort** [comment]
Thanks a lot, @cnbeining! Once I've finished reviewing it'll be on https://you-get.org/,

Link for the lazy: https://github.com/soimort/you-get/wiki/中文说明

If anyone would like to reshare the text anywhere else (on your blog, on a website...): The documentation should be licensed under [CC BY 4.0](https://creativecommons.org/licenses/by-sa/4.0/legalcode).

**Comment by soimort** [comment]
Since you're finished now, mind if I change the big h1 title

```
# 最后翻译：2016年03月10日 @cnbeining
```

to

```
译者：@cnbeining
```

？

**Comment by cnbeining** [comment]
Yes you can do that.

But I would prefer a last-update date located somewhere in the document, in order to avoid any confusion later on.

**Comment by soimort** [comment]
That's not really necessary, gollum will take care of the last-update date.

![screenshot from 2016-03-14 16-30-36](https://cloud.githubusercontent.com/assets/342945/13749540/3e9ba41c-ea02-11e5-8a57-820359c57091.png)

When I convert these wiki to `gh-pages`, I will certainly include such information clearly.

**Comment by cnbeining** [comment]
Nice.

Yeah you can proceed.

**Comment by soimort** [comment]
I've added your name besides the GitHub handle, feel free to tweak this as you want.

**Comment by cnbeining** [comment]
Thanks. I will try to update this WIki as quickly as I can.

**Comment by soimort** [comment]
No, I'd thank _you_ for contributing to the translation!
![](http://tb2.bdstatic.com/tb/editor/images/face/i_f28.png)
