### ISSUE TITLE
0.4.330的Windows版本什么时候发呢 ？

### ISSUE THREAD

**Issue by jackey99** [soimort/you-get#980]
是否解决了iqiyi key的问题 呢 ？

**Comment by nuomi1** [comment]
替换 key 即可
https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/iqiyi.py#L48

**Comment by jackey99** [comment]
@nuomi1 非常感谢，可惜我在使用iqiyi-hack又报错了，还在等作者回复

**Comment by jackey99** [comment]
另外发现window版本似乎无法直接修改py文件

**Comment by jiangjiangflies** [comment]
@nuomi1  怎么修改key呢？麻烦大神告知一下。我不懂，一直在等windows版本更新！谢谢

**Comment by soimort** [comment]
最近有点事情没法在Windows下打包，请再等两天。
这种时候建议直接从pip安装。

**Comment by soimort** [comment]
已上传。

https://github.com/soimort/you-get/releases/tag/v0.4.330
