### ISSUE TITLE
Windows msys2 with mintty UnicodeEncodeError

### ISSUE THREAD

**Issue by j16180339887** [soimort/you-get#982]
I'm using [msys2](http://msys2.github.io/) and latest you-get on Windows, 

this is how I install you-get

`pacman -S mingw64/mingw-w64-x86_64-python3-pip`
`pip3 install you-get`

I've set `LC_CTYPE=en_US.UTF-8` but still got UnicodeEncodeError.

![image](http://i.imgur.com/rrvcEHk.png)

My solution for this is disabling the output text

`you-get.exe http://v.youku.com/v_show/id_XMTQ4MTA2OTAxNg==.html > /dev/null`

which is a bad idea but works.

**Comment by soimort** [comment]
(Hopefully) fixed. Didn't test it on msys2 though.
