### ISSUE TITLE
爱奇艺的视频合并有问题

### ISSUE THREAD

**Issue by burning** [soimort/you-get#983]
一般到第3分03秒的时候 就无法播放了

**Comment by nuomi1** [comment]
example

**Comment by burning** [comment]
http://www.iqiyi.com/v_19rrl6lbtc.html#vfrm=2-3-0-1
每集都是5分钟  全部都是在3分03秒 播不动

**Comment by nuomi1** [comment]
系统版本，ffmpeg 版本，you-get 版本，网络环境。
试了，没问题。

**Comment by jiangjiangflies** [comment]
你能下载爱奇艺？我这边提示outdated aiqiyi key.

**Comment by cnbeining** [comment]
Please pull the latest version.

2016年3月13日星期日，jiangjiangflies <notifications@github.com> 写道：

**Comment by jiangjiangflies** [comment]
@cnbeining  I am using the latest Windows  verson , but it doesn't  work

**Comment by burning** [comment]
更新到最新的 ffmpeg  解决了

**Comment by cnbeining** [comment]
请close吧。

话说您的名和我的真像...每次都以为自己给自己发邮件了（

2016年3月13日星期日，Burning <notifications@github.com> 写道：
