### ISSUE TITLE
B站部分视频无法正常解析

### ISSUE THREAD

**Issue by mengmo** [soimort/you-get#984]
比如这个视频 you-get -i http://www.bilibili.com/video/av4087412/
提示 [Failed] DNS not resolved. Please change your DNS server settings.

you-get --debug http://www.bilibili.com/video/av4087412/
you-get: [Failed] DNS not resolved. Please change your DNS server settings.
you-get: version 0.4.324, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av4087412/']
Traceback (most recent call last):
  File "src\you_get\extractors\bilibili.py", line 104, in bilibili_download_by_cid
    title = r1_of([r'<meta name="title" content="([^<>]{1,999})" />',
  File "src\you_get\common.py", line 353, in url_info
    response = request.urlopen(request.Request(url))
  File "urllib\request.py", line 162, in urlopen
  File "urllib\request.py", line 471, in open
  File "urllib\request.py", line 581, in http_response
  File "urllib\request.py", line 509, in error
  File "urllib\request.py", line 443, in _call_chain
  File "urllib\request.py", line 589, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "src\you_get\common.py", line 1257, in main
    m, url = url_to_module(url)
  File "src\you_get\common.py", line 1178, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "src\you_get\common.py", line 1026, in download_main
    download(url, **kwargs)
  File "src\you_get\common.py", line 1250, in any_download
    location = res.getheader('location')
  File "src\you_get\extractors\bilibili.py", line 150, in bilibili_download
    if not kwargs['caption']:
  File "src\you_get\extractors\bilibili.py", line 107, in bilibili_download_by_cid
    log.wtf('[Failed] Video does not exist. Try to login with --cookies.')
  File "src\you_get\util\log.py", line 98, in wtf
    exit(exit_code)
NameError: name 'exit' is not defined
you-get returned -1

但是这个视频就能正常解析 you-get -i http://www.bilibili.com/video/av4067819/

另外，dilidili.com 和 zhanqi.tv 都失效了

**Comment by cnbeining** [comment]
看起来是您自己的锅。。。

另外的请令开issue，谢谢。


2016年3月13日星期日，mengmo <notifications@github.com> 写道：

**Comment by mengmo** [comment]
![01](https://cloud.githubusercontent.com/assets/17815250/13731176/fd26fa72-e99d-11e5-8d12-19c97847e131.png)
终于贴上来了，请指教 @cnbeining

**Comment by cnbeining** [comment]
请登录。

方法请查看wiki。

2016年3月13日星期日，mengmo <notifications@github.com> 写道：

**Comment by mengmo** [comment]
但是在不登录的情况下是可以正常播放的

**Comment by cnbeining** [comment]
偶尔他的cookie会奇怪，卡住什么的。小王霸服务器嘛。

具体等我睡醒再说。。。或者不说（

2016年3月13日星期日，mengmo <notifications@github.com> 写道：

**Comment by mengmo** [comment]
(⊙o⊙)…
@cnbeining 另外的另开 issue 的话，那两个网站不能解析的问题开一个就行了吧？
谢谢！

**Comment by cnbeining** [comment]
然而并不能复现。

```
python3 you-get --debug http://www.bilibili.com/video/av4087412/
Site:       bilibili.com
Title:       【1月】历物语 10【极影】
Type:       Flash video (video/x-flv)
Size:       105.47 MiB (110594719 Bytes)

Downloading  【1月】历物语 10【极影】.flv ...
 1.2% (  1.2/105.5MB) 
```

单独开issue吧。谢谢。

**Comment by mengmo** [comment]
我这样操作以后，
`python you-get -i http://www.bilibili.com/video/av4087412/`
`Site:       bilibili.com`
`Title:       【1月】历物语 10【极影】`
`Type:       Flash video (video/x-flv)`
`Size:       105.47 MiB (110594719 Bytes)`
再这样
`you-get -i http://www.bilibili.com/video/av4087412/`
`Site:       bilibili.com`
`Title:       【1月】历物语 10【极影】`
`Type:       Flash video (video/x-flv)`
`Size:       105.47 MiB (110594719 Bytes)`
就没问题了。
这什么鬼？
另，上一版的 prebuilt 也存在这个问题，最新版的 prebuilt 就没有这个问题了
还有，我说那两个网站的问题开一个 issue 的意思是“再单独开一个就行了吧？”
@cnbeining

**Comment by soimort** [comment]
也许我该写个机器人来自动回复和关闭此类issue。

（当然如果您能自行关闭最好）

**Comment by mengmo** [comment]
作者您好！也可能是我的问题在您看来太弱智了，但是作为一个不懂这些的人也确实想了解一下原因，当然如果是不值得回答的话，我把 issue关了就是了 @soimort

**Comment by mengmo** [comment]
总之，谢谢 @cnbeining @soimort 两位

**Comment by soimort** [comment]
> you-get: version 0.4.324, a tiny downloader that scrapes the web.

不是出于别的原因，而是因为您在报 issue 之前根本不看版本号。

另一个 issue #985 的标题是“最新的0.4.330版”，但从输出信息看来，您用的仍然的是 0.4.324。

PS. 这两个问题在0.4.330中已经解决了

**Comment by mengmo** [comment]
这个，后来我也发现了，确实是我自己的锅
不过，我在这儿说的
> 还有，我说那两个网站的问题开一个 issue 的意思是“再单独开一个就行了吧？”

那两个网站是指这里边的
> 另外，dilidili.com 和 zhanqi.tv 都失效了

另，谢谢！也很抱歉！
