### ISSUE TITLE
dilidili.com和zhanqi.tv以及live.bilibili.com解析有问题

### ISSUE THREAD

**Issue by mengmo** [soimort/you-get#986]
dilidili.com 不能解析
zhanqi.tv 只有 Windows的 prebuilt 解析有问题
live.bilibili.com 不能解析，--cookies后同样不能解析

**Comment by soimort** [comment]
3个问题请分别开 issue，同时，对于每个 issue：

1、请善用搜索。如果之前有人已经开过 issue，就在原帖下回复，不必再开新的 issue。
2、请提供**用于测试的地址（至少一个）**。
3、请使用**最新版** `you-get` 使用 `--debug` 的命令行输出。
4、任何“不能解析”的情况，都应该把具体的输出贴出来。直接报告“不能解析”不能帮助我们解决任何问题。

**Comment by mengmo** [comment]
这个 issue 要不要关了？
因为开了这个 issue 就被 github 当成了 not human ，所以暂时不敢再开新的 issue
希望您能理解，这儿我先说下其他的(我就只说说)，明天再开新 issue 行不？
1. zhanqi.tv 的问题是否要放到 #854 
2. zhanqi.tv 的解析，exe不能解析，Python版能解析但不能下载，提示403
我把这3个网站放一个里边是看 #671 里放了两个网站才这样做的
如果在 #984 里告诉我不能这样做，我肯定一个网站开一个 issue
并且提供测试地址
不过 zhanqi.tv 和 live.bilibili.com 的不太好办，因为有时间问题
但肯定会贴 you-get --debug 的输出

**Comment by cnbeining** [comment]
bilibili live我好像没写。

算feature request。

2016年3月14日星期一，mengmo <notifications@github.com> 写道：

**Comment by zhangn1985** [comment]
请参考：
https://github.com/zhangn1985/you-get/blob/master/you_get/extractors/biliorig.py#L56
我就不PR了。

**Comment by soimort** [comment]
@mengmo GitHub 不会因为你开_这个 issue_ 就认为你是 not human。
但如果你是新注册的帐号，没有其他任何活动（star、创建项目）只是在大量 comment，会比较容易被认为是 spam bot 这样。

---

@zhangn1985 :+1: +1

**Comment by mengmo** [comment]
@cnbeining 我也找到我在那儿看到的支持B站直播了 #421 #426

**Comment by soimort** [comment]
然而 #426 似乎并没有实际上支持 bilibili live。

直接从页面解析出 `cid` 的话应该用这个 API http://live.bilibili.com/api/ ，否则下载到的东西根本不对。
