### ISSUE TITLE
youku有些链接只能下载第一段视频

### ISSUE THREAD

**Issue by yangaowei** [soimort/you-get#991]
http://v.youku.com/v_show/id_XMTQ5OTAxMzgxNg==.html  

这个视频一共90分钟，但只下载了第一段视频

**Comment by nuomi1** [comment]
可以重现，只能解析第一个 part。

**Comment by soimort** [comment]
现在应该可以下载到40分钟（前13段）。

```
13 361018557
5 135494672
4 90299012
2 45047782
2 45072383
2 45121668
2 45113638
2 45126325
1 7798802
```

和以前不同，前13段是一个单独的 `stream_fileid`，后5段是另一个 `stream_fileid`，后4段又是一个…依次类推。每一块要分开处理。解析出全部33段后合并即可。

我懒得写了（反正我自己并不用），谁有空发个PR吧。

**Comment by soimort** [comment]
```console
$ ./you-get -d http://v.youku.com/v_show/id_XMTQ5OTAxMzgxNg\=\=.html 
site:                优酷 (Youku)
title:               欢乐喜剧人 20160313
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          782.1 MiB (820092839 bytes)
    # download-with: you-get --format=hd2 [URL]

Downloading 欢乐喜剧人 20160313.flv ...
 100% (782.1/782.1MB) ├█████████████████████████████████████████┤[33/33]    8 MB/s
Merging video parts... Done.
```

**Comment by linhua55** [comment]
@soimort 
This commit disable video's 1080P and make some video not complete!

    ➜  my-you-get git:(develop) ./you-get -du  http://v.youku.com/v_show/id_XNTc2NDk2MDMy
    site:                优酷 (Youku)
    title:               疯狂原始人（国语）
    stream:
        - format:        hd2
          container:     flv
          video-profile: 超清
          size:          841.9 MiB (882788723 bytes)
        # download-with: you-get --format=hd2 [URL]
    
    audio-languages:
        - lang:          国语
          download-url:  http://v.youku.com/v_show/id_XNTc2NDk2MDMy
    
        - lang:          英语
          download-url:  http://v.youku.com/v_show/id_XNTc3OTU5NzI4
    
        - lang:          粤语
          download-url:  http://v.youku.com/v_show/id_XNjg3NzM3ODcy

**Comment by soimort** [comment]
@linhua55 
How about changing `ct=12` to `ct=10`? I need more examples for testing.

It seems their `http://play.youku.com/` API is very inconsistent.

**Comment by linhua55** [comment]
@soimort 
The stream parameters(such as `stream_fileid` , `segs`)  should extract from `ct=10`.And others (`ep` , `ip`) should extract from `ct=12`.
The algorithm to calculate `sid` and `token` from `ep` in `ct=12` and `ct=10` is different.

**Comment by linhua55** [comment]
@soimort 
The stream parameters(such as `stream_fileid` , `segs`)  should extract from `ct=10`.And others (`ep` , `ip`) should extract from `ct=12`.
The algorithm to calculate `sid` and `token` from `ep` in `ct=12` and `ct=10` is different.

**Comment by soimort** [comment]
@linhua55 Thanks for the clarification, I was just wondering why `ct=12` and `ct=10` return different `stream_fileid` and `segs`.

It doesn't make any difference whether to use http://play.youku.com/play/get.json?vid=XMTQ5OTAxMzgxNg&ct=12 and http://play.youku.com/play/get.json?vid=XMTQ5OTAxMzgxNg&ct=10, so (in my last commit) I supposed using `ct=12` alone is fine and removed that part. However, given the example you mentioned above, it seems we still have to fallback to `ct=10` sometimes.

**Comment by soimort** [comment]
**UPDATE:** `ct=12` and `ct=10` **were** different and I realized it. So I was not breaking that on purpose.

It's a recent update of Youku that started to divide video segments as an array (is it?), for both. I'm not sure how this would affect the JSON output across various `ct` values. Hopefully this will be an easy fix.

**Comment by linhua55** [comment]
I can understand.If use the  `ct=12` with `ct=10`,the code will be a little aweful.We always want to keep it simple.
But the `segs` information from `ct=10` is more complete than that from `ct=12`(this video url from this issue is a exception).
Yes,it is.Don't know why would Youku do this(divide video segments).And will all of Youku videos be changed eventually?

**Comment by denobisipsis** [comment]
Hi, i have a question. The only generation of stream names doesnt work, although the method is right. So maybe its a question related to headers, cookies, or something else. But i have checked (from Spain) that the way to get the videos seems to be linked to a post-call to 

http://stat.youku.com/player/addPlayerStaticReport

with post

"videoid=$v&url=$url&sid=$sid&referer=null&uid=0&totalseg=&totalsec=&h=$hashcash&fullflag=0&t=$tokenvv&ikuflag=u1%5Fm1&source=video"

where:

1- $sid is extracted from api12.ep
2- $tokenvv is api10->data->token->vv (this info only appears in ct10)
3- $hashcash is a value generated from $tokenvv and coded here

https://github.com/denobisipsis/adownloader/blob/master/youkupartial.php


Also, there is a way to decrypt the ep from ct 10?

**Comment by soimort** [comment]
> the way to get the videos seems to be linked to a post-call to
>
> http://stat.youku.com/player/addPlayerStaticReport

We didn't use that for accessing Youku's API. However, In whichever case, both cookies and a valid referer are necessary.

> Also, there is a way to decrypt the ep from ct 10?

Not to my knowledge. Currently we're sticking with ct=12 only.

**Comment by denobisipsis** [comment]
Hi soimort, also there is a swf 

http://static.youku.com/v1.0.0611/v/swf/youkustream.swf

called i think from 

http://static.youku.com/v1.0.0611/v/swf/player_yknpsv.swf

but i cant download it. Maybe contains something interesting. Have you this swf? It downloads corrupt (?)

**Comment by denobisipsis** [comment]
Hi,

youkustream.swf is encrypted, from p2ploader.as

`_loc2_ = "http://cfg.ykpp.navi.youku.com/stream.swf";
									if(PlayerConfig.rootData.ykstreamURL != null)
									{
												_loc2_ = PlayerConfig.rootData.ykstreamURL;
									}
									this._urlLoader.load(new URLRequest(_loc2_));


var _loc3_:ByteArray = PlayListUtil.getInstance().decode(_loc2_);`

is possible to get the swf decoded in memory?
