### ISSUE TITLE
zhanqi.tv 解析的问题

### ISSUE THREAD

**Issue by mengmo** [soimort/you-get#992]
Windows 上 you-get.exe 的结果
`you-get --debug http://www.zhanqi.tv/meizhi`
`you-get: version 0.4.330, a tiny downloader that scrapes the web.`
`you-get: ['http://www.zhanqi.tv/meizhi']`
`Traceback (most recent call last):`
`  File "<string>", line 11, in <module>`
`  File "src\you_get\__main__.py", line 92, in main`
`  File "src\you_get\common.py", line 1265, in main`
`  File "src\you_get\common.py", line 1178, in script_main`
`  File "src\you_get\common.py", line 1026, in download_main`
`  File "src\you_get\common.py", line 1257, in any_download`
`  File "src\you_get\common.py", line 1244, in url_to_module`
`  File "importlib\__init__.py", line 126, in import_module`
`  File "<frozen importlib._bootstrap>", line 986, in _gcd_import`
`  File "<frozen importlib._bootstrap>", line 969, in _find_and_load`
`  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked`
`ImportError: No module named 'you_get.extractors.zhanqi'`
`you-get returned -1`

python you-get 的结果
`python you-get --debug http://www.zhanqi.tv/meizhi`
`you-get: version 0.4.330, a tiny downloader that scrapes the web.`
`you-get: ['http://www.zhanqi.tv/meizhi']`
`Traceback (most recent call last):`
`  File "you-get", line 11, in <module>`
`    you_get.main(repo_path=_filepath)`
`  File "src\you_get\__main__.py", line 92, in main`
`    main(**kwargs)`
`  File "src\you_get\common.py", line 1265, in main`
`    script_main('you-get', any_download, any_download_playlist, **kwargs)`
`  File "src\you_get\common.py", line 1178, in script_main`
`    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)`
`  File "src\you_get\common.py", line 1026, in download_main`
`    download(url, **kwargs)`
`  File "src\you_get\common.py", line 1257, in any_download`
`    m, url = url_to_module(url)`
`  File "src\you_get\common.py", line 1244, in url_to_module`
`    return import_module('.'.join(['you_get', 'extractors', SITES[k]])), url`
`  File "importlib\__init__.py", line 126, in import_module`
`  File "<frozen importlib._bootstrap>", line 986, in _gcd_import`
`  File "<frozen importlib._bootstrap>", line 969, in _find_and_load`
`  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked`
`  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed`
`  File "<frozen importlib._bootstrap>", line 986, in _gcd_import`
`  File "<frozen importlib._bootstrap>", line 969, in _find_and_load`
`  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked`
`  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked`
`  File "<frozen importlib._bootstrap_external>", line 662, in exec_module`
`  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed`
`  File "src\you_get\extractors\__init__.py", line 12, in <module>`
`    from .dilidili import *`
`  File "src\you_get\extractors\dilidili.py", line 6, in <module>`
`    from .ckplayer import ckplayer_download`
`ImportError: No module named 'you_get.extractors.ckplayer'`

**Comment by mengmo** [comment]
不知道怎么回事儿，解析时灵时不灵，不过确实没法用
`python you-get --debug http://www.zhanqi.tv/meizhi`
`Site:       zhanqi.tv`
`Title:      #~ Live Nico Poi ~#`
`Type:       Flash video (video/x-flv)`
`Size:       inf MiB (inf Bytes)`

`Traceback (most recent call last):`
`  File "src\you_get\common.py", line 686, in download_urls`
`    total_size = urls_size(urls, faker=faker, headers=headers)`
`  File "src\you_get\common.py", line 336, in urls_size`
`    return sum([url_size(url, faker=faker, headers=headers) for url in urls])`
`  File "src\you_get\common.py", line 336, in <listcomp>`
`    return sum([url_size(url, faker=faker, headers=headers) for url in urls])`
`  File "src\you_get\common.py", line 330, in url_size`
`    response = request.urlopen(url)`
`  File "urllib\request.py", line 162, in urlopen`
`  File "urllib\request.py", line 471, in open`
`  File "urllib\request.py", line 581, in http_response`
`  File "urllib\request.py", line 509, in error`
`  File "urllib\request.py", line 443, in _call_chain`
`  File "urllib\request.py", line 589, in http_error_default`
`urllib.error.HTTPError: HTTP Error 403: Forbidden`
`Downloading #~ Live Nico Poi ~#.flv ...`
```
     %[========================================] 1/1you-get: version 0.4.330, a
tiny downloader that scrapes the web.
```
`you-get: ['http://www.zhanqi.tv/meizhi']`
`Traceback (most recent call last):`
`  File "you-get", line 11, in <module>`
`    you_get.main(repo_path=_filepath)`
`  File "src\you_get\__main__.py", line 92, in main`
`    main(**kwargs)`
`  File "src\you_get\common.py", line 1265, in main`
`    script_main('you-get', any_download, any_download_playlist, **kwargs)`
`  File "src\you_get\common.py", line 1178, in script_main`
`    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)`
`  File "src\you_get\common.py", line 1026, in download_main`
`    download(url, **kwargs)`
`  File "src\you_get\common.py", line 1258, in any_download`
`    m.download(url, **kwargs)`
`  File "src\you_get\extractors\zhanqi.py", line 30, in zhanqi_download`
`    download_urls([real_url], title, 'flv', None, output_dir, merge = merge)`
`  File "src\you_get\common.py", line 709, in download_urls`
`    url_save(url, output_filepath, bar, refer = refer, faker = faker, headers = headers)`
`  File "src\you_get\common.py", line 412, in url_save`
`    file_size = url_size(url, faker = faker, headers = headers)`
`  File "src\you_get\common.py", line 330, in url_size`
`    response = request.urlopen(url)`
`  File "urllib\request.py", line 162, in urlopen`
`  File "urllib\request.py", line 471, in open`
`  File "urllib\request.py", line 581, in http_response`
`  File "urllib\request.py", line 509, in error`
`  File "urllib\request.py", line 443, in _call_chain`
`  File "urllib\request.py", line 589, in http_error_default`
`urllib.error.HTTPError: HTTP Error 403: Forbidden`

**Comment by soimort** [comment]
战旗的支持可能早就坏了……

望有人来认领。

**Comment by ERioK** [comment]
回退到上一个版本..暂时还没坏

**Comment by cnbeining** [comment]
zhanqi目前是hotfix。

望认领。

2016年3月18日星期五，ERioK <notifications@github.com> 写道：

**Comment by ERioK** [comment]
请直接回退到这个版本
https://github.com/soimort/you-get/commit/eaab0ce3ed3054db0a12bad5e8511d5e7791f5c8
什么时候坏了再说吧.

**Comment by mengmo** [comment]
@soimort 作者您好 这样修改过之后，解析下载是没问题，不过

`python you-get -p ffplay http://www.zhanqi.tv/zhaojia`

`Site:       zhanqi.tv`
`Title:      【火影忍者-究极风暴4】剧情模式录播·`
`Type:       Flash video (video/x-flv)`
`Size:       inf MiB (inf Bytes)`

`rtmpdump -r 'rtmp://dlrtmp.cdn.zhanqi.tv/zqlive//35384_Abfe2?k=c3323811504e53248`
`35ac3209699856b&t=56ed0f2d'  -o - | ffplay -`
`RTMPDump v2.3`
`(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL`
`WARNING: Unknown protocol!`

`WARNING: You haven't specified an output file (-o filename), using stdout`
`Connecting ...`
`INFO: Connected...`
`ERROR: RTMP_ReadPacket, failed to read RTMP packet header`
`'t' 不是内部或外部命令，也不是可运行的程序`
`或批处理文件。`

拿掉`rtmpdump.exe`后
`python you-get -p ffplay http://www.zhanqi.tv/zhaojia`

`Site:       zhanqi.tv`
`Title:      【火影忍者-究极风暴4】剧情模式录播·`
`Type:       Flash video (video/x-flv)`
`Size:       inf MiB (inf Bytes)`

`rtmpdump -r 'rtmp://dlrtmp.cdn.zhanqi.tv/zqlive//35384_Abfe2?k=a6e14a606e2782a38`
`dfddf0e8c682f98&t=56ed1012'  -o - | ffplay -`
`'rtmpdump' 不是内部或外部命令，也不是可运行的程序`
`或批处理文件。`
`'t' 不是内部或外部命令，也不是可运行的程序`
`或批处理文件。`

**Comment by ERioK** [comment]
linux下ffplay是没问题的..暂时先用vlc什么的吧

**Comment by yan12125** [comment]
1. Windows下command line argument需要用雙引號
2. 要裝rtmpdump

**Comment by zhangn1985** [comment]
呵呵

**Comment by mengmo** [comment]
@zhangn1985 你终于肯出手了，早就发现你个人维护的是好的
另外，我发现不只是`zhanqi`，更换`UA`对`PPTV`的直播如`http://v.pptv.com/show/cSOKCHDWRoTnZc0.html`，搜狐的直播如`http://live.tv.sohu.com/dragontv`，还有`CNTV`的直播如`http://tv.cntv.cn/live/dongfang/``http://tv.cctv.com/live/cctv13/`都是有效的(`CNTV`好像全站的视频都有效)
对了还有这儿`http://live.wasu.cn/show/id/458`

@ERioK 与播放器无关，应该是解析到地址后直接就调用了`rtmpdump`才导致了这个问题
@yan12125 以下是加了双引号的结果。其实，如果只是需要播放的话是不需要独立的`rtmpdump`的，至少以下播放器都支持`rtmp`协议的播放

> `python you-get -p vlc "http://www.zhanqi.tv/meizhi"`
> `Site:       zhanqi.tv`
> `Title:      #~ Live Nico Poi ~#`
> `Type:       Flash video (video/x-flv)`
> `Size:       inf MiB (inf Bytes)`
> 
> `rtmpdump -r 'rtmp://dlrtmp.cdn.zhanqi.tv/zqlive//2045_4MjfZ?k=e6f7bf837182f48fb6af7c5ae361f56b&t=56ed6958'  -o - | vlc -`
> `RTMPDump v2.3`
> `(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL`
> `WARNING: Unknown protocol!`
> 
> `WARNING: You haven't specified an output file (-o filename), using stdout`
> `Connecting ...`
> `INFO: Connected...`
> `ERROR: RTMP_ReadPacket, failed to read RTMP packet header`
> `'t' 不是内部或外部命令，也不是可运行的程序或批处理文件。`

`python you-get -p smplayer "http://www.zhanqi.tv/meizhi"`
`Site:       zhanqi.tv`
`Title:      #~ Live Nico Poi ~#`
`Type:       Flash video (video/x-flv)`
`Size:       inf MiB (inf Bytes)`

`rtmpdump -r 'rtmp://dlrtmp.cdn.zhanqi.tv/zqlive//2045_4MjfZ?k=e46c49634218c203801caf6273890295&t=56ed6964'  -o - | smplayer -`
`RTMPDump v2.3`
`(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL`
`WARNING: Unknown protocol!`

`WARNING: You haven't specified an output file (-o filename), using stdout`
`Connecting ...`
`INFO: Connected...`
`ERROR: RTMP_ReadPacket, failed to read RTMP packet header`
`'t' 不是内部或外部命令，也不是可运行的程序或批处理文件。`

> `python you-get -p mpc-hc64 "http://www.zhanqi.tv/meizhi"`
> `Site:       zhanqi.tv`
> `Title:      #~ Live Nico Poi ~#`
> `Type:       Flash video (video/x-flv)`
> `Size:       inf MiB (inf Bytes)`
> 
> `rtmpdump -r 'rtmp://dlrtmp.cdn.zhanqi.tv/zqlive//2045_4MjfZ?k=6d442dccf2cad4a63980c06e87e815e5&t=56ed69dd'  -o - | mpc-hc64 -`
> `RTMPDump v2.3`
> `(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL`
> `WARNING: Unknown protocol!`
> 
> `WARNING: You haven't specified an output file (-o filename), using stdout`
> `Connecting ...`
> `INFO: Connected...`
> `ERROR: RTMP_ReadPacket, failed to read RTMP packet header`
> `'t' 不是内部或外部命令，也不是可运行的程序或批处理文件。`

`python you-get -p ffplay "http://www.zhanqi.tv/meizhi"`
`Site:       zhanqi.tv`
`Title:      #~ Live Nico Poi ~#`
`Type:       Flash video (video/x-flv)`
`Size:       inf MiB (inf Bytes)`

`rtmpdump -r 'rtmp://dlrtmp.cdn.zhanqi.tv/zqlive//2045_4MjfZ?k=c255d1b853d377c4fc1f3aa8e88260c4&t=56ed68dc'  -o - | ffplay -`
`RTMPDump v2.3`
`(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL`
`WARNING: Unknown protocol!`

`WARNING: You haven't specified an output file (-o filename), using stdout`
`Connecting ...`
`INFO: Connected...`
`ERROR: RTMP_ReadPacket, failed to read RTMP packet header`
`'t' 不是内部或外部命令，也不是可运行的程序或批处理文件。`

**Comment by yan12125** [comment]
是rtmpdump那行需要雙引號
```
rtmpdump -r "rtmp://dlrtmp.cdn.zhanqi.tv/zqlive//2045_4MjfZ?k=e6f7bf837182f48fb6af7c5ae361f56b&t=56ed6958" -o - | vlc -
```
這算是you-get的bug

**Comment by mengmo** [comment]
> `rtmpdump -r "rtmp://dlrtmp.cdn.zhanqi.tv/zqlive//2045_4MjfZ?k=e6f7bf837182f48fb6af7c5ae361f56b&t=56ed6958" -o - | vlc -`

嗯 是我理解有误
不过，我觉得应该没必要这样做吧？一般用`you-get`的，播放的时候应该都会用支持`rtmp`的播放器吧

**Comment by yan12125** [comment]
得問問原作者是一開始是怎麼設計的

**Comment by Justsoos** [comment]
zhanqi.tv 和longzhu.com 我改了两个好用版本，这两天放上来。-- 对github 不太熟悉 -- 摸索中

**Comment by cnbeining** [comment]
@Justsoos 请：

1. fork本项目

2. 将这个项目clone到本地

3. 将您的修改一次性覆盖到clone后的项目

4. 写好commit message，commit，并push到您的repo中

5. 从您的repo的已经修改的branch 发起pull request 到本项目的dev分支。

thx。

**Comment by Justsoos** [comment]
@cnbeining  好像三个commit 合并在一起了？我新写了龙珠，重写了战旗  https://github.com/soimort/you-get/pull/1647
