### ISSUE TITLE
douyutv.com

### ISSUE THREAD

**Issue by binai** [soimort/you-get#997]
斗鱼直播有官方的直播不能播放
http://www.douyutv.com/cms/zt/lpl.html
http://www.douyutv.com/cms/zt/lck.html

**Comment by ERioK** [comment]
因为不支持这种格式的url的解析..可以去页面找到房间号 http://www.douyutv.com/房间号
或者用 http://www.douyutv.com/lpl

**Comment by zhangn1985** [comment]
这个页面就是playlist.

douyu_match_pattern = [ 'class="hroom_id" value="([^"]+)',
                        'data-room_id="([^"]+)'
                      ]
        vids = matchall(html, douyu_match_pattern)

        for vid in vids:
            self.download_by_vid(vid,  **kwargs)

可以用于实现playlist。

**Comment by rosynirvana** [comment]
outdated
